public class agz {
   public static final zn<wp, aiu, agz.a> a = ($$0, $$1) -> new ze<wp, aiu>() {
         public aiu a(wp $$0x) {
            if (!$$1.a()) {
               throw new wr("Not in creative mode");
            } else {
               return (aiu)$$0.decode($$0);
            }
         }

         public void a(wp $$0x, aiu $$1x) {
            if (!$$1.a()) {
               throw new ws("Not in creative mode");
            } else {
               $$0.encode($$0, $$1);
            }
         }
      };
   public static final zv<aha, wp, agz.a> b = zt.c(
      vw.b,
      $$0 -> $$0.a(agy.bk, ahc.a)
            .a(agy.bl, ahd.a)
            .a(agy.bm, aio.a)
            .a(agy.bn, ahe.a)
            .a(agy.bo, ahf.a)
            .a(agy.bp, ahg.a)
            .a(agy.bq, ahh.a)
            .a(agy.br, ahi.a)
            .a(agy.bs, ahj.a)
            .a(agy.bt, ahk.a)
            .a(agy.bu, ahl.a)
            .a(agy.bv, ahm.b)
            .a(aai.l, aak.a)
            .a(agy.bw, ahn.a)
            .a(agy.bx, aho.b)
            .a(agy.by, ahp.a)
            .a(agy.bz, ahq.a)
            .a(agy.bA, ahr.a)
            .a(agy.bB, ahs.a)
            .a(acb.b, acd.a)
            .a(aai.m, aal.a)
            .a(agy.bC, aht.a)
            .a(agy.bD, ahu.a)
            .a(agy.bE, ahv.a)
            .a(agy.bF, ahw.a)
            .a(agy.bG, ahx.a)
            .a(aai.n, aam.a)
            .a(agy.bH, ahy.a)
            .a(agy.bI, ahz.a.j)
            .a(agy.bJ, ahz.b.j)
            .a(agy.bK, ahz.c.j)
            .a(agy.bL, ahz.d.j)
            .a(agy.bM, aia.a)
            .a(agy.bN, aib.a)
            .a(agy.bO, aic.a)
            .a(agy.bP, aid.a)
            .a(aki.b, akk.a)
            .a(agy.bQ, aie.a)
            .a(agy.bR, aif.a)
            .a(agy.bS, aig.a)
            .a(agy.bT, aih.a)
            .a(agy.bU, aii.a)
            .a(agy.bV, aij.a)
            .a(aai.o, aan.a)
            .a(agy.bW, aik.a)
            .a(agy.bX, ail.a)
            .a(agy.bY, aim.a)
            .a(aai.p, aao.a)
            .a(agy.bZ, ain.a)
            .a(agy.ca, aip.a)
            .a(agy.cb, aiq.a)
            .a(agy.cc, air.a)
            .a(agy.cd, ais.a)
            .a(agy.ce, ait.a)
            .a(agy.cf, aiu.a, a)
            .a(agy.cg, aiv.a)
            .a(agy.ch, aiw.a)
            .a(agy.ci, aix.a)
            .a(agy.ck, aiy.a)
            .a(agy.cl, aiz.a)
            .a(agy.cm, aja.a)
            .a(agy.cj, ajb.a)
            .a(agy.cn, ajc.a)
            .a(agy.co, ajd.a)
   );
   public static final zu<acf, wp> c = zt.b(
      vw.b,
      $$0 -> $$0.a(agy.a, acq::new, new acp())
            .a(agy.c, acg.a)
            .a(agy.d, ach.a)
            .a(agy.e, aci.a)
            .a(agy.f, acj.a)
            .a(agy.g, ack.a)
            .a(agy.h, acl.a)
            .a(agy.i, acm.a)
            .a(agy.j, acn.a)
            .a(agy.k, aco.a)
            .a(agy.l, acr.a)
            .a(agy.m, acs.a)
            .a(agy.n, act.b)
            .a(agy.o, acu.a)
            .a(agy.p, acv.a)
            .a(agy.q, acw.a)
            .a(agy.r, acx.a)
            .a(agy.s, acy.a)
            .a(agy.t, acz.a)
            .a(agy.u, ada.a)
            .a(agy.v, adb.a)
            .a(acb.a, aca.a)
            .a(agy.w, adc.a)
            .a(agy.x, add.a)
            .a(aai.a, zx.a)
            .a(agy.y, ade.a)
            .a(agy.z, adf.a)
            .a(agy.A, adg.a)
            .a(aai.c, zz.a)
            .a(agy.B, adh.a)
            .a(agy.C, adi.a)
            .a(agy.D, adj.a)
            .a(agy.E, adk.a)
            .a(agy.F, adl.a)
            .a(agy.G, adm.a)
            .a(agy.H, adn.a)
            .a(agy.I, ado.a)
            .a(agy.J, adp.a)
            .a(aai.d, aaa.a)
            .a(agy.K, adr.a)
            .a(agy.L, ads.a)
            .a(agy.M, adt.a)
            .a(agy.N, adu.a)
            .a(agy.O, adw.a)
            .a(agy.P, adx.a)
            .a(agy.Q, ady.a)
            .a(agy.R, adz.a.j)
            .a(agy.S, adz.b.j)
            .a(agy.T, aea.a)
            .a(agy.U, adz.c.j)
            .a(agy.V, aeb.a)
            .a(agy.W, aec.a)
            .a(agy.X, aed.a)
            .a(agy.Y, aee.a)
            .a(aai.e, aab.a)
            .a(aki.a, akh.a)
            .a(agy.Z, aef.a)
            .a(agy.aa, aeg.a)
            .a(agy.ab, aeh.a)
            .a(agy.ac, aei.a)
            .a(agy.ad, aej.b)
            .a(agy.ae, aek.a)
            .a(agy.af, ael.a)
            .a(agy.ag, aem.a)
            .a(agy.ah, aen.a)
            .a(agy.ai, aeo.a)
            .a(agy.aj, aep.a)
            .a(agy.ak, aer.a)
            .a(agy.al, aes.a)
            .a(agy.am, aet.a)
            .a(agy.an, aeu.a)
            .a(agy.ao, aev.a)
            .a(agy.cp, aew.a)
            .a(aai.f, aac.a)
            .a(aai.g, aad.b)
            .a(agy.ap, aex.a)
            .a(agy.aq, aey.a)
            .a(agy.ar, aez.a)
            .a(agy.as, afa.a)
            .a(agy.at, afb.a)
            .a(agy.au, afc.a)
            .a(agy.av, afd.a)
            .a(agy.aw, afe.a)
            .a(agy.ax, aff.a)
            .a(agy.ay, afg.a)
            .a(agy.az, afh.a)
            .a(agy.aA, afi.a)
            .a(agy.aB, afj.a)
            .a(agy.aC, afk.a)
            .a(agy.cs, afl.a)
            .a(agy.aD, afm.a)
            .a(agy.aE, afn.a)
            .a(agy.aF, afo.a)
            .a(agy.aG, afp.a)
            .a(agy.aH, afq.a)
            .a(agy.aI, afr.a)
            .a(agy.aJ, afs.a)
            .a(agy.aK, aft.a)
            .a(agy.aL, afu.a)
            .a(agy.aM, afv.a)
            .a(agy.aN, afw.a)
            .a(agy.ct, afx.a)
            .a(agy.aO, afy.a)
            .a(agy.aP, afz.a)
            .a(agy.aQ, aga.a)
            .a(agy.aR, agb.a)
            .a(agy.aS, agc.a)
            .a(agy.aT, agd.a)
            .a(agy.aU, age.a)
            .a(agy.aV, agf.a)
            .a(agy.aW, agg.a)
            .a(agy.aX, agh.b)
            .a(agy.aY, agi.a)
            .a(aai.i, aaf.a)
            .a(agy.aZ, agj.a)
            .a(agy.ba, agk.a)
            .a(agy.bb, agl.a)
            .a(agy.bc, agm.a)
            .a(agy.bd, agn.a)
            .a(agy.be, ago.a)
            .a(agy.cq, agp.a)
            .a(agy.cr, agq.a)
            .a(aai.j, aag.a)
            .a(agy.bf, agr.a)
            .a(agy.bg, ags.a)
            .a(agy.bh, agt.a)
            .a(agy.bi, agu.a)
            .a(aai.k, aah.a)
            .a(agy.bj, aeq.a)
            .a(aai.b, zy.a)
            .a(aai.h, aae.a)
   );

   public interface a {
      boolean a();
   }
}
