public class arb {
   public static final ara<cva> a = a("mined", jy.f);
   public static final ara<cle> b = a("crafted", jy.i);
   public static final ara<cle> c = a("used", jy.i);
   public static final ara<cle> d = a("broken", jy.i);
   public static final ara<cle> e = a("picked_up", jy.i);
   public static final ara<cle> f = a("dropped", jy.i);
   public static final ara<bku<?>> g = a("killed", jy.h);
   public static final ara<bku<?>> h = a("killed_by", jy.h);
   public static final ara<agi> i = a("custom", jy.n);
   public static final agi j = a("leave_game", aqz.b);
   public static final agi k = a("play_time", aqz.e);
   public static final agi l = a("total_world_time", aqz.e);
   public static final agi m = a("time_since_death", aqz.e);
   public static final agi n = a("time_since_rest", aqz.e);
   public static final agi o = a("sneak_time", aqz.e);
   public static final agi p = a("walk_one_cm", aqz.d);
   public static final agi q = a("crouch_one_cm", aqz.d);
   public static final agi r = a("sprint_one_cm", aqz.d);
   public static final agi s = a("walk_on_water_one_cm", aqz.d);
   public static final agi t = a("fall_one_cm", aqz.d);
   public static final agi u = a("climb_one_cm", aqz.d);
   public static final agi v = a("fly_one_cm", aqz.d);
   public static final agi w = a("walk_under_water_one_cm", aqz.d);
   public static final agi x = a("minecart_one_cm", aqz.d);
   public static final agi y = a("boat_one_cm", aqz.d);
   public static final agi z = a("pig_one_cm", aqz.d);
   public static final agi A = a("horse_one_cm", aqz.d);
   public static final agi B = a("aviate_one_cm", aqz.d);
   public static final agi C = a("swim_one_cm", aqz.d);
   public static final agi D = a("strider_one_cm", aqz.d);
   public static final agi E = a("jump", aqz.b);
   public static final agi F = a("drop", aqz.b);
   public static final agi G = a("damage_dealt", aqz.c);
   public static final agi H = a("damage_dealt_absorbed", aqz.c);
   public static final agi I = a("damage_dealt_resisted", aqz.c);
   public static final agi J = a("damage_taken", aqz.c);
   public static final agi K = a("damage_blocked_by_shield", aqz.c);
   public static final agi L = a("damage_absorbed", aqz.c);
   public static final agi M = a("damage_resisted", aqz.c);
   public static final agi N = a("deaths", aqz.b);
   public static final agi O = a("mob_kills", aqz.b);
   public static final agi P = a("animals_bred", aqz.b);
   public static final agi Q = a("player_kills", aqz.b);
   public static final agi R = a("fish_caught", aqz.b);
   public static final agi S = a("talked_to_villager", aqz.b);
   public static final agi T = a("traded_with_villager", aqz.b);
   public static final agi U = a("eat_cake_slice", aqz.b);
   public static final agi V = a("fill_cauldron", aqz.b);
   public static final agi W = a("use_cauldron", aqz.b);
   public static final agi X = a("clean_armor", aqz.b);
   public static final agi Y = a("clean_banner", aqz.b);
   public static final agi Z = a("clean_shulker_box", aqz.b);
   public static final agi aa = a("interact_with_brewingstand", aqz.b);
   public static final agi ab = a("interact_with_beacon", aqz.b);
   public static final agi ac = a("inspect_dropper", aqz.b);
   public static final agi ad = a("inspect_hopper", aqz.b);
   public static final agi ae = a("inspect_dispenser", aqz.b);
   public static final agi af = a("play_noteblock", aqz.b);
   public static final agi ag = a("tune_noteblock", aqz.b);
   public static final agi ah = a("pot_flower", aqz.b);
   public static final agi ai = a("trigger_trapped_chest", aqz.b);
   public static final agi aj = a("open_enderchest", aqz.b);
   public static final agi ak = a("enchant_item", aqz.b);
   public static final agi al = a("play_record", aqz.b);
   public static final agi am = a("interact_with_furnace", aqz.b);
   public static final agi an = a("interact_with_crafting_table", aqz.b);
   public static final agi ao = a("open_chest", aqz.b);
   public static final agi ap = a("sleep_in_bed", aqz.b);
   public static final agi aq = a("open_shulker_box", aqz.b);
   public static final agi ar = a("open_barrel", aqz.b);
   public static final agi as = a("interact_with_blast_furnace", aqz.b);
   public static final agi at = a("interact_with_smoker", aqz.b);
   public static final agi au = a("interact_with_lectern", aqz.b);
   public static final agi av = a("interact_with_campfire", aqz.b);
   public static final agi aw = a("interact_with_cartography_table", aqz.b);
   public static final agi ax = a("interact_with_loom", aqz.b);
   public static final agi ay = a("interact_with_stonecutter", aqz.b);
   public static final agi az = a("bell_ring", aqz.b);
   public static final agi aA = a("raid_trigger", aqz.b);
   public static final agi aB = a("raid_win", aqz.b);
   public static final agi aC = a("interact_with_anvil", aqz.b);
   public static final agi aD = a("interact_with_grindstone", aqz.b);
   public static final agi aE = a("target_hit", aqz.b);
   public static final agi aF = a("interact_with_smithing_table", aqz.b);

   private static agi a(String $$0, aqz $$1) {
      agi $$2 = new agi($$0);
      io.a(jy.n, $$0, $$2);
      i.a($$2, $$1);
      return $$2;
   }

   private static <T> ara<T> a(String $$0, io<T> $$1) {
      ur $$2 = ur.c("stat_type.minecraft." + $$0);
      return io.a(jy.y, $$0, new ara<>($$1, $$2));
   }
}
