public class arf {
   public static final are<cvf> a = a("mined", kc.f);
   public static final are<clj> b = a("crafted", kc.i);
   public static final are<clj> c = a("used", kc.i);
   public static final are<clj> d = a("broken", kc.i);
   public static final are<clj> e = a("picked_up", kc.i);
   public static final are<clj> f = a("dropped", kc.i);
   public static final are<bkz<?>> g = a("killed", kc.h);
   public static final are<bkz<?>> h = a("killed_by", kc.h);
   public static final are<agm> i = a("custom", kc.n);
   public static final agm j = a("leave_game", ard.b);
   public static final agm k = a("play_time", ard.e);
   public static final agm l = a("total_world_time", ard.e);
   public static final agm m = a("time_since_death", ard.e);
   public static final agm n = a("time_since_rest", ard.e);
   public static final agm o = a("sneak_time", ard.e);
   public static final agm p = a("walk_one_cm", ard.d);
   public static final agm q = a("crouch_one_cm", ard.d);
   public static final agm r = a("sprint_one_cm", ard.d);
   public static final agm s = a("walk_on_water_one_cm", ard.d);
   public static final agm t = a("fall_one_cm", ard.d);
   public static final agm u = a("climb_one_cm", ard.d);
   public static final agm v = a("fly_one_cm", ard.d);
   public static final agm w = a("walk_under_water_one_cm", ard.d);
   public static final agm x = a("minecart_one_cm", ard.d);
   public static final agm y = a("boat_one_cm", ard.d);
   public static final agm z = a("pig_one_cm", ard.d);
   public static final agm A = a("horse_one_cm", ard.d);
   public static final agm B = a("aviate_one_cm", ard.d);
   public static final agm C = a("swim_one_cm", ard.d);
   public static final agm D = a("strider_one_cm", ard.d);
   public static final agm E = a("jump", ard.b);
   public static final agm F = a("drop", ard.b);
   public static final agm G = a("damage_dealt", ard.c);
   public static final agm H = a("damage_dealt_absorbed", ard.c);
   public static final agm I = a("damage_dealt_resisted", ard.c);
   public static final agm J = a("damage_taken", ard.c);
   public static final agm K = a("damage_blocked_by_shield", ard.c);
   public static final agm L = a("damage_absorbed", ard.c);
   public static final agm M = a("damage_resisted", ard.c);
   public static final agm N = a("deaths", ard.b);
   public static final agm O = a("mob_kills", ard.b);
   public static final agm P = a("animals_bred", ard.b);
   public static final agm Q = a("player_kills", ard.b);
   public static final agm R = a("fish_caught", ard.b);
   public static final agm S = a("talked_to_villager", ard.b);
   public static final agm T = a("traded_with_villager", ard.b);
   public static final agm U = a("eat_cake_slice", ard.b);
   public static final agm V = a("fill_cauldron", ard.b);
   public static final agm W = a("use_cauldron", ard.b);
   public static final agm X = a("clean_armor", ard.b);
   public static final agm Y = a("clean_banner", ard.b);
   public static final agm Z = a("clean_shulker_box", ard.b);
   public static final agm aa = a("interact_with_brewingstand", ard.b);
   public static final agm ab = a("interact_with_beacon", ard.b);
   public static final agm ac = a("inspect_dropper", ard.b);
   public static final agm ad = a("inspect_hopper", ard.b);
   public static final agm ae = a("inspect_dispenser", ard.b);
   public static final agm af = a("play_noteblock", ard.b);
   public static final agm ag = a("tune_noteblock", ard.b);
   public static final agm ah = a("pot_flower", ard.b);
   public static final agm ai = a("trigger_trapped_chest", ard.b);
   public static final agm aj = a("open_enderchest", ard.b);
   public static final agm ak = a("enchant_item", ard.b);
   public static final agm al = a("play_record", ard.b);
   public static final agm am = a("interact_with_furnace", ard.b);
   public static final agm an = a("interact_with_crafting_table", ard.b);
   public static final agm ao = a("open_chest", ard.b);
   public static final agm ap = a("sleep_in_bed", ard.b);
   public static final agm aq = a("open_shulker_box", ard.b);
   public static final agm ar = a("open_barrel", ard.b);
   public static final agm as = a("interact_with_blast_furnace", ard.b);
   public static final agm at = a("interact_with_smoker", ard.b);
   public static final agm au = a("interact_with_lectern", ard.b);
   public static final agm av = a("interact_with_campfire", ard.b);
   public static final agm aw = a("interact_with_cartography_table", ard.b);
   public static final agm ax = a("interact_with_loom", ard.b);
   public static final agm ay = a("interact_with_stonecutter", ard.b);
   public static final agm az = a("bell_ring", ard.b);
   public static final agm aA = a("raid_trigger", ard.b);
   public static final agm aB = a("raid_win", ard.b);
   public static final agm aC = a("interact_with_anvil", ard.b);
   public static final agm aD = a("interact_with_grindstone", ard.b);
   public static final agm aE = a("target_hit", ard.b);
   public static final agm aF = a("interact_with_smithing_table", ard.b);

   private static agm a(String $$0, ard $$1) {
      agm $$2 = new agm($$0);
      is.a(kc.n, $$0, $$2);
      i.a($$2, $$1);
      return $$2;
   }

   private static <T> are<T> a(String $$0, is<T> $$1) {
      uv $$2 = uv.c("stat_type.minecraft." + $$0);
      return is.a(kc.y, $$0, new are<>($$1, $$2));
   }
}
