public class arm {
   public static final arl<cvz> a = a("mined", kb.e);
   public static final arl<cmc> b = a("crafted", kb.h);
   public static final arl<cmc> c = a("used", kb.h);
   public static final arl<cmc> d = a("broken", kb.h);
   public static final arl<cmc> e = a("picked_up", kb.h);
   public static final arl<cmc> f = a("dropped", kb.h);
   public static final arl<blj<?>> g = a("killed", kb.g);
   public static final arl<blj<?>> h = a("killed_by", kb.g);
   public static final arl<agt> i = a("custom", kb.m);
   public static final agt j = a("leave_game", ark.b);
   public static final agt k = a("play_time", ark.e);
   public static final agt l = a("total_world_time", ark.e);
   public static final agt m = a("time_since_death", ark.e);
   public static final agt n = a("time_since_rest", ark.e);
   public static final agt o = a("sneak_time", ark.e);
   public static final agt p = a("walk_one_cm", ark.d);
   public static final agt q = a("crouch_one_cm", ark.d);
   public static final agt r = a("sprint_one_cm", ark.d);
   public static final agt s = a("walk_on_water_one_cm", ark.d);
   public static final agt t = a("fall_one_cm", ark.d);
   public static final agt u = a("climb_one_cm", ark.d);
   public static final agt v = a("fly_one_cm", ark.d);
   public static final agt w = a("walk_under_water_one_cm", ark.d);
   public static final agt x = a("minecart_one_cm", ark.d);
   public static final agt y = a("boat_one_cm", ark.d);
   public static final agt z = a("pig_one_cm", ark.d);
   public static final agt A = a("horse_one_cm", ark.d);
   public static final agt B = a("aviate_one_cm", ark.d);
   public static final agt C = a("swim_one_cm", ark.d);
   public static final agt D = a("strider_one_cm", ark.d);
   public static final agt E = a("jump", ark.b);
   public static final agt F = a("drop", ark.b);
   public static final agt G = a("damage_dealt", ark.c);
   public static final agt H = a("damage_dealt_absorbed", ark.c);
   public static final agt I = a("damage_dealt_resisted", ark.c);
   public static final agt J = a("damage_taken", ark.c);
   public static final agt K = a("damage_blocked_by_shield", ark.c);
   public static final agt L = a("damage_absorbed", ark.c);
   public static final agt M = a("damage_resisted", ark.c);
   public static final agt N = a("deaths", ark.b);
   public static final agt O = a("mob_kills", ark.b);
   public static final agt P = a("animals_bred", ark.b);
   public static final agt Q = a("player_kills", ark.b);
   public static final agt R = a("fish_caught", ark.b);
   public static final agt S = a("talked_to_villager", ark.b);
   public static final agt T = a("traded_with_villager", ark.b);
   public static final agt U = a("eat_cake_slice", ark.b);
   public static final agt V = a("fill_cauldron", ark.b);
   public static final agt W = a("use_cauldron", ark.b);
   public static final agt X = a("clean_armor", ark.b);
   public static final agt Y = a("clean_banner", ark.b);
   public static final agt Z = a("clean_shulker_box", ark.b);
   public static final agt aa = a("interact_with_brewingstand", ark.b);
   public static final agt ab = a("interact_with_beacon", ark.b);
   public static final agt ac = a("inspect_dropper", ark.b);
   public static final agt ad = a("inspect_hopper", ark.b);
   public static final agt ae = a("inspect_dispenser", ark.b);
   public static final agt af = a("play_noteblock", ark.b);
   public static final agt ag = a("tune_noteblock", ark.b);
   public static final agt ah = a("pot_flower", ark.b);
   public static final agt ai = a("trigger_trapped_chest", ark.b);
   public static final agt aj = a("open_enderchest", ark.b);
   public static final agt ak = a("enchant_item", ark.b);
   public static final agt al = a("play_record", ark.b);
   public static final agt am = a("interact_with_furnace", ark.b);
   public static final agt an = a("interact_with_crafting_table", ark.b);
   public static final agt ao = a("open_chest", ark.b);
   public static final agt ap = a("sleep_in_bed", ark.b);
   public static final agt aq = a("open_shulker_box", ark.b);
   public static final agt ar = a("open_barrel", ark.b);
   public static final agt as = a("interact_with_blast_furnace", ark.b);
   public static final agt at = a("interact_with_smoker", ark.b);
   public static final agt au = a("interact_with_lectern", ark.b);
   public static final agt av = a("interact_with_campfire", ark.b);
   public static final agt aw = a("interact_with_cartography_table", ark.b);
   public static final agt ax = a("interact_with_loom", ark.b);
   public static final agt ay = a("interact_with_stonecutter", ark.b);
   public static final agt az = a("bell_ring", ark.b);
   public static final agt aA = a("raid_trigger", ark.b);
   public static final agt aB = a("raid_win", ark.b);
   public static final agt aC = a("interact_with_anvil", ark.b);
   public static final agt aD = a("interact_with_grindstone", ark.b);
   public static final agt aE = a("target_hit", ark.b);
   public static final agt aF = a("interact_with_smithing_table", ark.b);

   private static agt a(String $$0, ark $$1) {
      agt $$2 = new agt($$0);
      ir.a(kb.m, $$0, $$2);
      i.a($$2, $$1);
      return $$2;
   }

   private static <T> arl<T> a(String $$0, ir<T> $$1) {
      vb $$2 = vb.c("stat_type.minecraft." + $$0);
      return ir.a(kb.x, $$0, new arl<>($$1, $$2));
   }
}
