public class avr {
   public static final avq<ddy> a = a("mined", le.e);
   public static final avq<ctj> b = a("crafted", le.h);
   public static final avq<ctj> c = a("used", le.h);
   public static final avq<ctj> d = a("broken", le.h);
   public static final avq<ctj> e = a("picked_up", le.h);
   public static final avq<ctj> f = a("dropped", le.h);
   public static final avq<bsa<?>> g = a("killed", le.g);
   public static final avq<bsa<?>> h = a("killed_by", le.g);
   public static final avq<akm> i = a("custom", le.m);
   public static final akm j = a("leave_game", avp.b);
   public static final akm k = a("play_time", avp.e);
   public static final akm l = a("total_world_time", avp.e);
   public static final akm m = a("time_since_death", avp.e);
   public static final akm n = a("time_since_rest", avp.e);
   public static final akm o = a("sneak_time", avp.e);
   public static final akm p = a("walk_one_cm", avp.d);
   public static final akm q = a("crouch_one_cm", avp.d);
   public static final akm r = a("sprint_one_cm", avp.d);
   public static final akm s = a("walk_on_water_one_cm", avp.d);
   public static final akm t = a("fall_one_cm", avp.d);
   public static final akm u = a("climb_one_cm", avp.d);
   public static final akm v = a("fly_one_cm", avp.d);
   public static final akm w = a("walk_under_water_one_cm", avp.d);
   public static final akm x = a("minecart_one_cm", avp.d);
   public static final akm y = a("boat_one_cm", avp.d);
   public static final akm z = a("pig_one_cm", avp.d);
   public static final akm A = a("horse_one_cm", avp.d);
   public static final akm B = a("aviate_one_cm", avp.d);
   public static final akm C = a("swim_one_cm", avp.d);
   public static final akm D = a("strider_one_cm", avp.d);
   public static final akm E = a("jump", avp.b);
   public static final akm F = a("drop", avp.b);
   public static final akm G = a("damage_dealt", avp.c);
   public static final akm H = a("damage_dealt_absorbed", avp.c);
   public static final akm I = a("damage_dealt_resisted", avp.c);
   public static final akm J = a("damage_taken", avp.c);
   public static final akm K = a("damage_blocked_by_shield", avp.c);
   public static final akm L = a("damage_absorbed", avp.c);
   public static final akm M = a("damage_resisted", avp.c);
   public static final akm N = a("deaths", avp.b);
   public static final akm O = a("mob_kills", avp.b);
   public static final akm P = a("animals_bred", avp.b);
   public static final akm Q = a("player_kills", avp.b);
   public static final akm R = a("fish_caught", avp.b);
   public static final akm S = a("talked_to_villager", avp.b);
   public static final akm T = a("traded_with_villager", avp.b);
   public static final akm U = a("eat_cake_slice", avp.b);
   public static final akm V = a("fill_cauldron", avp.b);
   public static final akm W = a("use_cauldron", avp.b);
   public static final akm X = a("clean_armor", avp.b);
   public static final akm Y = a("clean_banner", avp.b);
   public static final akm Z = a("clean_shulker_box", avp.b);
   public static final akm aa = a("interact_with_brewingstand", avp.b);
   public static final akm ab = a("interact_with_beacon", avp.b);
   public static final akm ac = a("inspect_dropper", avp.b);
   public static final akm ad = a("inspect_hopper", avp.b);
   public static final akm ae = a("inspect_dispenser", avp.b);
   public static final akm af = a("play_noteblock", avp.b);
   public static final akm ag = a("tune_noteblock", avp.b);
   public static final akm ah = a("pot_flower", avp.b);
   public static final akm ai = a("trigger_trapped_chest", avp.b);
   public static final akm aj = a("open_enderchest", avp.b);
   public static final akm ak = a("enchant_item", avp.b);
   public static final akm al = a("play_record", avp.b);
   public static final akm am = a("interact_with_furnace", avp.b);
   public static final akm an = a("interact_with_crafting_table", avp.b);
   public static final akm ao = a("open_chest", avp.b);
   public static final akm ap = a("sleep_in_bed", avp.b);
   public static final akm aq = a("open_shulker_box", avp.b);
   public static final akm ar = a("open_barrel", avp.b);
   public static final akm as = a("interact_with_blast_furnace", avp.b);
   public static final akm at = a("interact_with_smoker", avp.b);
   public static final akm au = a("interact_with_lectern", avp.b);
   public static final akm av = a("interact_with_campfire", avp.b);
   public static final akm aw = a("interact_with_cartography_table", avp.b);
   public static final akm ax = a("interact_with_loom", avp.b);
   public static final akm ay = a("interact_with_stonecutter", avp.b);
   public static final akm az = a("bell_ring", avp.b);
   public static final akm aA = a("raid_trigger", avp.b);
   public static final akm aB = a("raid_win", avp.b);
   public static final akm aC = a("interact_with_anvil", avp.b);
   public static final akm aD = a("interact_with_grindstone", avp.b);
   public static final akm aE = a("target_hit", avp.b);
   public static final akm aF = a("interact_with_smithing_table", avp.b);

   private static akm a(String $$0, avp $$1) {
      akm $$2 = new akm($$0);
      jk.a(le.m, $$0, $$2);
      i.a($$2, $$1);
      return $$2;
   }

   private static <T> avq<T> a(String $$0, jk<T> $$1) {
      wx $$2 = wx.c("stat_type.minecraft." + $$0);
      return jk.a(le.x, $$0, new avq<>($$1, $$2));
   }
}
