public class avz {
   public static final avy<dfy> a = a("mined", lt.e);
   public static final avy<cul> b = a("crafted", lt.g);
   public static final avy<cul> c = a("used", lt.g);
   public static final avy<cul> d = a("broken", lt.g);
   public static final avy<cul> e = a("picked_up", lt.g);
   public static final avy<cul> f = a("dropped", lt.g);
   public static final avy<bsx<?>> g = a("killed", lt.f);
   public static final avy<bsx<?>> h = a("killed_by", lt.f);
   public static final avy<akr> i = a("custom", lt.k);
   public static final akr j = a("leave_game", avx.b);
   public static final akr k = a("play_time", avx.e);
   public static final akr l = a("total_world_time", avx.e);
   public static final akr m = a("time_since_death", avx.e);
   public static final akr n = a("time_since_rest", avx.e);
   public static final akr o = a("sneak_time", avx.e);
   public static final akr p = a("walk_one_cm", avx.d);
   public static final akr q = a("crouch_one_cm", avx.d);
   public static final akr r = a("sprint_one_cm", avx.d);
   public static final akr s = a("walk_on_water_one_cm", avx.d);
   public static final akr t = a("fall_one_cm", avx.d);
   public static final akr u = a("climb_one_cm", avx.d);
   public static final akr v = a("fly_one_cm", avx.d);
   public static final akr w = a("walk_under_water_one_cm", avx.d);
   public static final akr x = a("minecart_one_cm", avx.d);
   public static final akr y = a("boat_one_cm", avx.d);
   public static final akr z = a("pig_one_cm", avx.d);
   public static final akr A = a("horse_one_cm", avx.d);
   public static final akr B = a("aviate_one_cm", avx.d);
   public static final akr C = a("swim_one_cm", avx.d);
   public static final akr D = a("strider_one_cm", avx.d);
   public static final akr E = a("jump", avx.b);
   public static final akr F = a("drop", avx.b);
   public static final akr G = a("damage_dealt", avx.c);
   public static final akr H = a("damage_dealt_absorbed", avx.c);
   public static final akr I = a("damage_dealt_resisted", avx.c);
   public static final akr J = a("damage_taken", avx.c);
   public static final akr K = a("damage_blocked_by_shield", avx.c);
   public static final akr L = a("damage_absorbed", avx.c);
   public static final akr M = a("damage_resisted", avx.c);
   public static final akr N = a("deaths", avx.b);
   public static final akr O = a("mob_kills", avx.b);
   public static final akr P = a("animals_bred", avx.b);
   public static final akr Q = a("player_kills", avx.b);
   public static final akr R = a("fish_caught", avx.b);
   public static final akr S = a("talked_to_villager", avx.b);
   public static final akr T = a("traded_with_villager", avx.b);
   public static final akr U = a("eat_cake_slice", avx.b);
   public static final akr V = a("fill_cauldron", avx.b);
   public static final akr W = a("use_cauldron", avx.b);
   public static final akr X = a("clean_armor", avx.b);
   public static final akr Y = a("clean_banner", avx.b);
   public static final akr Z = a("clean_shulker_box", avx.b);
   public static final akr aa = a("interact_with_brewingstand", avx.b);
   public static final akr ab = a("interact_with_beacon", avx.b);
   public static final akr ac = a("inspect_dropper", avx.b);
   public static final akr ad = a("inspect_hopper", avx.b);
   public static final akr ae = a("inspect_dispenser", avx.b);
   public static final akr af = a("play_noteblock", avx.b);
   public static final akr ag = a("tune_noteblock", avx.b);
   public static final akr ah = a("pot_flower", avx.b);
   public static final akr ai = a("trigger_trapped_chest", avx.b);
   public static final akr aj = a("open_enderchest", avx.b);
   public static final akr ak = a("enchant_item", avx.b);
   public static final akr al = a("play_record", avx.b);
   public static final akr am = a("interact_with_furnace", avx.b);
   public static final akr an = a("interact_with_crafting_table", avx.b);
   public static final akr ao = a("open_chest", avx.b);
   public static final akr ap = a("sleep_in_bed", avx.b);
   public static final akr aq = a("open_shulker_box", avx.b);
   public static final akr ar = a("open_barrel", avx.b);
   public static final akr as = a("interact_with_blast_furnace", avx.b);
   public static final akr at = a("interact_with_smoker", avx.b);
   public static final akr au = a("interact_with_lectern", avx.b);
   public static final akr av = a("interact_with_campfire", avx.b);
   public static final akr aw = a("interact_with_cartography_table", avx.b);
   public static final akr ax = a("interact_with_loom", avx.b);
   public static final akr ay = a("interact_with_stonecutter", avx.b);
   public static final akr az = a("bell_ring", avx.b);
   public static final akr aA = a("raid_trigger", avx.b);
   public static final akr aB = a("raid_win", avx.b);
   public static final akr aC = a("interact_with_anvil", avx.b);
   public static final akr aD = a("interact_with_grindstone", avx.b);
   public static final akr aE = a("target_hit", avx.b);
   public static final akr aF = a("interact_with_smithing_table", avx.b);

   private static akr a(String $$0, avx $$1) {
      akr $$2 = akr.b($$0);
      jz.a(lt.k, $$0, $$2);
      i.a($$2, $$1);
      return $$2;
   }

   private static <T> avy<T> a(String $$0, jz<T> $$1) {
      wz $$2 = wz.c("stat_type.minecraft." + $$0);
      return jz.a(lt.v, $$0, new avy<>($$1, $$2));
   }
}
