public interface bhr {
   aev<bhq> a = aev.a(jc.p, new aew("in_fire"));
   aev<bhq> b = aev.a(jc.p, new aew("lightning_bolt"));
   aev<bhq> c = aev.a(jc.p, new aew("on_fire"));
   aev<bhq> d = aev.a(jc.p, new aew("lava"));
   aev<bhq> e = aev.a(jc.p, new aew("hot_floor"));
   aev<bhq> f = aev.a(jc.p, new aew("in_wall"));
   aev<bhq> g = aev.a(jc.p, new aew("cramming"));
   aev<bhq> h = aev.a(jc.p, new aew("drown"));
   aev<bhq> i = aev.a(jc.p, new aew("starve"));
   aev<bhq> j = aev.a(jc.p, new aew("cactus"));
   aev<bhq> k = aev.a(jc.p, new aew("fall"));
   aev<bhq> l = aev.a(jc.p, new aew("fly_into_wall"));
   aev<bhq> m = aev.a(jc.p, new aew("out_of_world"));
   aev<bhq> n = aev.a(jc.p, new aew("generic"));
   aev<bhq> o = aev.a(jc.p, new aew("magic"));
   aev<bhq> p = aev.a(jc.p, new aew("wither"));
   aev<bhq> q = aev.a(jc.p, new aew("dragon_breath"));
   aev<bhq> r = aev.a(jc.p, new aew("dry_out"));
   aev<bhq> s = aev.a(jc.p, new aew("sweet_berry_bush"));
   aev<bhq> t = aev.a(jc.p, new aew("freeze"));
   aev<bhq> u = aev.a(jc.p, new aew("stalagmite"));
   aev<bhq> v = aev.a(jc.p, new aew("falling_block"));
   aev<bhq> w = aev.a(jc.p, new aew("falling_anvil"));
   aev<bhq> x = aev.a(jc.p, new aew("falling_stalactite"));
   aev<bhq> y = aev.a(jc.p, new aew("sting"));
   aev<bhq> z = aev.a(jc.p, new aew("mob_attack"));
   aev<bhq> A = aev.a(jc.p, new aew("mob_attack_no_aggro"));
   aev<bhq> B = aev.a(jc.p, new aew("player_attack"));
   aev<bhq> C = aev.a(jc.p, new aew("arrow"));
   aev<bhq> D = aev.a(jc.p, new aew("trident"));
   aev<bhq> E = aev.a(jc.p, new aew("mob_projectile"));
   aev<bhq> F = aev.a(jc.p, new aew("fireworks"));
   aev<bhq> G = aev.a(jc.p, new aew("fireball"));
   aev<bhq> H = aev.a(jc.p, new aew("unattributed_fireball"));
   aev<bhq> I = aev.a(jc.p, new aew("wither_skull"));
   aev<bhq> J = aev.a(jc.p, new aew("thrown"));
   aev<bhq> K = aev.a(jc.p, new aew("indirect_magic"));
   aev<bhq> L = aev.a(jc.p, new aew("thorns"));
   aev<bhq> M = aev.a(jc.p, new aew("explosion"));
   aev<bhq> N = aev.a(jc.p, new aew("player_explosion"));
   aev<bhq> O = aev.a(jc.p, new aew("sonic_boom"));
   aev<bhq> P = aev.a(jc.p, new aew("bad_respawn_point"));
   aev<bhq> Q = aev.a(jc.p, new aew("outside_border"));
   aev<bhq> R = aev.a(jc.p, new aew("generic_kill"));

   static void a(nr<bhq> $$0) {
      $$0.a(a, new bhq("inFire", 0.1F, bhm.d));
      $$0.a(b, new bhq("lightningBolt", 0.1F));
      $$0.a(c, new bhq("onFire", 0.0F, bhm.d));
      $$0.a(d, new bhq("lava", 0.1F, bhm.d));
      $$0.a(e, new bhq("hotFloor", 0.1F, bhm.d));
      $$0.a(f, new bhq("inWall", 0.0F));
      $$0.a(g, new bhq("cramming", 0.0F));
      $$0.a(h, new bhq("drown", 0.0F, bhm.c));
      $$0.a(i, new bhq("starve", 0.0F));
      $$0.a(j, new bhq("cactus", 0.1F));
      $$0.a(k, new bhq("fall", bhn.b, 0.0F, bhm.a, bhs.b));
      $$0.a(l, new bhq("flyIntoWall", 0.0F));
      $$0.a(m, new bhq("outOfWorld", 0.0F));
      $$0.a(n, new bhq("generic", 0.0F));
      $$0.a(o, new bhq("magic", 0.0F));
      $$0.a(p, new bhq("wither", 0.0F));
      $$0.a(q, new bhq("dragonBreath", 0.0F));
      $$0.a(r, new bhq("dryout", 0.1F));
      $$0.a(s, new bhq("sweetBerryBush", 0.1F, bhm.e));
      $$0.a(t, new bhq("freeze", 0.0F, bhm.f));
      $$0.a(u, new bhq("stalagmite", 0.0F));
      $$0.a(v, new bhq("fallingBlock", 0.1F));
      $$0.a(w, new bhq("anvil", 0.1F));
      $$0.a(x, new bhq("fallingStalactite", 0.1F));
      $$0.a(y, new bhq("sting", 0.1F));
      $$0.a(z, new bhq("mob", 0.1F));
      $$0.a(A, new bhq("mob", 0.1F));
      $$0.a(B, new bhq("player", 0.1F));
      $$0.a(C, new bhq("arrow", 0.1F));
      $$0.a(D, new bhq("trident", 0.1F));
      $$0.a(E, new bhq("mob", 0.1F));
      $$0.a(F, new bhq("fireworks", 0.1F));
      $$0.a(H, new bhq("onFire", 0.1F, bhm.d));
      $$0.a(G, new bhq("fireball", 0.1F, bhm.d));
      $$0.a(I, new bhq("witherSkull", 0.1F));
      $$0.a(J, new bhq("thrown", 0.1F));
      $$0.a(K, new bhq("indirectMagic", 0.0F));
      $$0.a(L, new bhq("thorns", 0.1F, bhm.b));
      $$0.a(M, new bhq("explosion", bhn.c, 0.1F));
      $$0.a(N, new bhq("explosion.player", bhn.c, 0.1F));
      $$0.a(O, new bhq("sonic_boom", bhn.c, 0.0F));
      $$0.a(P, new bhq("badRespawnPoint", bhn.c, 0.1F, bhm.a, bhs.c));
      $$0.a(Q, new bhq("outsideBorder", 0.0F));
      $$0.a(R, new bhq("genericKill", 0.0F));
   }
}
