public interface biu {
   afv<bit> a = afv.a(jz.q, new afw("in_fire"));
   afv<bit> b = afv.a(jz.q, new afw("lightning_bolt"));
   afv<bit> c = afv.a(jz.q, new afw("on_fire"));
   afv<bit> d = afv.a(jz.q, new afw("lava"));
   afv<bit> e = afv.a(jz.q, new afw("hot_floor"));
   afv<bit> f = afv.a(jz.q, new afw("in_wall"));
   afv<bit> g = afv.a(jz.q, new afw("cramming"));
   afv<bit> h = afv.a(jz.q, new afw("drown"));
   afv<bit> i = afv.a(jz.q, new afw("starve"));
   afv<bit> j = afv.a(jz.q, new afw("cactus"));
   afv<bit> k = afv.a(jz.q, new afw("fall"));
   afv<bit> l = afv.a(jz.q, new afw("fly_into_wall"));
   afv<bit> m = afv.a(jz.q, new afw("out_of_world"));
   afv<bit> n = afv.a(jz.q, new afw("generic"));
   afv<bit> o = afv.a(jz.q, new afw("magic"));
   afv<bit> p = afv.a(jz.q, new afw("wither"));
   afv<bit> q = afv.a(jz.q, new afw("dragon_breath"));
   afv<bit> r = afv.a(jz.q, new afw("dry_out"));
   afv<bit> s = afv.a(jz.q, new afw("sweet_berry_bush"));
   afv<bit> t = afv.a(jz.q, new afw("freeze"));
   afv<bit> u = afv.a(jz.q, new afw("stalagmite"));
   afv<bit> v = afv.a(jz.q, new afw("falling_block"));
   afv<bit> w = afv.a(jz.q, new afw("falling_anvil"));
   afv<bit> x = afv.a(jz.q, new afw("falling_stalactite"));
   afv<bit> y = afv.a(jz.q, new afw("sting"));
   afv<bit> z = afv.a(jz.q, new afw("mob_attack"));
   afv<bit> A = afv.a(jz.q, new afw("mob_attack_no_aggro"));
   afv<bit> B = afv.a(jz.q, new afw("player_attack"));
   afv<bit> C = afv.a(jz.q, new afw("arrow"));
   afv<bit> D = afv.a(jz.q, new afw("trident"));
   afv<bit> E = afv.a(jz.q, new afw("mob_projectile"));
   afv<bit> F = afv.a(jz.q, new afw("fireworks"));
   afv<bit> G = afv.a(jz.q, new afw("fireball"));
   afv<bit> H = afv.a(jz.q, new afw("unattributed_fireball"));
   afv<bit> I = afv.a(jz.q, new afw("wither_skull"));
   afv<bit> J = afv.a(jz.q, new afw("thrown"));
   afv<bit> K = afv.a(jz.q, new afw("indirect_magic"));
   afv<bit> L = afv.a(jz.q, new afw("thorns"));
   afv<bit> M = afv.a(jz.q, new afw("explosion"));
   afv<bit> N = afv.a(jz.q, new afw("player_explosion"));
   afv<bit> O = afv.a(jz.q, new afw("sonic_boom"));
   afv<bit> P = afv.a(jz.q, new afw("bad_respawn_point"));
   afv<bit> Q = afv.a(jz.q, new afw("outside_border"));
   afv<bit> R = afv.a(jz.q, new afw("generic_kill"));

   static void a(oo<bit> $$0) {
      $$0.a(a, new bit("inFire", 0.1F, bip.d));
      $$0.a(b, new bit("lightningBolt", 0.1F));
      $$0.a(c, new bit("onFire", 0.0F, bip.d));
      $$0.a(d, new bit("lava", 0.1F, bip.d));
      $$0.a(e, new bit("hotFloor", 0.1F, bip.d));
      $$0.a(f, new bit("inWall", 0.0F));
      $$0.a(g, new bit("cramming", 0.0F));
      $$0.a(h, new bit("drown", 0.0F, bip.c));
      $$0.a(i, new bit("starve", 0.0F));
      $$0.a(j, new bit("cactus", 0.1F));
      $$0.a(k, new bit("fall", biq.b, 0.0F, bip.a, biv.b));
      $$0.a(l, new bit("flyIntoWall", 0.0F));
      $$0.a(m, new bit("outOfWorld", 0.0F));
      $$0.a(n, new bit("generic", 0.0F));
      $$0.a(o, new bit("magic", 0.0F));
      $$0.a(p, new bit("wither", 0.0F));
      $$0.a(q, new bit("dragonBreath", 0.0F));
      $$0.a(r, new bit("dryout", 0.1F));
      $$0.a(s, new bit("sweetBerryBush", 0.1F, bip.e));
      $$0.a(t, new bit("freeze", 0.0F, bip.f));
      $$0.a(u, new bit("stalagmite", 0.0F));
      $$0.a(v, new bit("fallingBlock", 0.1F));
      $$0.a(w, new bit("anvil", 0.1F));
      $$0.a(x, new bit("fallingStalactite", 0.1F));
      $$0.a(y, new bit("sting", 0.1F));
      $$0.a(z, new bit("mob", 0.1F));
      $$0.a(A, new bit("mob", 0.1F));
      $$0.a(B, new bit("player", 0.1F));
      $$0.a(C, new bit("arrow", 0.1F));
      $$0.a(D, new bit("trident", 0.1F));
      $$0.a(E, new bit("mob", 0.1F));
      $$0.a(F, new bit("fireworks", 0.1F));
      $$0.a(H, new bit("onFire", 0.1F, bip.d));
      $$0.a(G, new bit("fireball", 0.1F, bip.d));
      $$0.a(I, new bit("witherSkull", 0.1F));
      $$0.a(J, new bit("thrown", 0.1F));
      $$0.a(K, new bit("indirectMagic", 0.0F));
      $$0.a(L, new bit("thorns", 0.1F, bip.b));
      $$0.a(M, new bit("explosion", biq.c, 0.1F));
      $$0.a(N, new bit("explosion.player", biq.c, 0.1F));
      $$0.a(O, new bit("sonic_boom", biq.c, 0.0F));
      $$0.a(P, new bit("badRespawnPoint", biq.c, 0.1F, bip.a, biv.c));
      $$0.a(Q, new bit("outsideBorder", 0.0F));
      $$0.a(R, new bit("genericKill", 0.0F));
   }
}
