public interface bjw {
   agl<bjv> a = agl.a(kd.q, new agm("in_fire"));
   agl<bjv> b = agl.a(kd.q, new agm("lightning_bolt"));
   agl<bjv> c = agl.a(kd.q, new agm("on_fire"));
   agl<bjv> d = agl.a(kd.q, new agm("lava"));
   agl<bjv> e = agl.a(kd.q, new agm("hot_floor"));
   agl<bjv> f = agl.a(kd.q, new agm("in_wall"));
   agl<bjv> g = agl.a(kd.q, new agm("cramming"));
   agl<bjv> h = agl.a(kd.q, new agm("drown"));
   agl<bjv> i = agl.a(kd.q, new agm("starve"));
   agl<bjv> j = agl.a(kd.q, new agm("cactus"));
   agl<bjv> k = agl.a(kd.q, new agm("fall"));
   agl<bjv> l = agl.a(kd.q, new agm("fly_into_wall"));
   agl<bjv> m = agl.a(kd.q, new agm("out_of_world"));
   agl<bjv> n = agl.a(kd.q, new agm("generic"));
   agl<bjv> o = agl.a(kd.q, new agm("magic"));
   agl<bjv> p = agl.a(kd.q, new agm("wither"));
   agl<bjv> q = agl.a(kd.q, new agm("dragon_breath"));
   agl<bjv> r = agl.a(kd.q, new agm("dry_out"));
   agl<bjv> s = agl.a(kd.q, new agm("sweet_berry_bush"));
   agl<bjv> t = agl.a(kd.q, new agm("freeze"));
   agl<bjv> u = agl.a(kd.q, new agm("stalagmite"));
   agl<bjv> v = agl.a(kd.q, new agm("falling_block"));
   agl<bjv> w = agl.a(kd.q, new agm("falling_anvil"));
   agl<bjv> x = agl.a(kd.q, new agm("falling_stalactite"));
   agl<bjv> y = agl.a(kd.q, new agm("sting"));
   agl<bjv> z = agl.a(kd.q, new agm("mob_attack"));
   agl<bjv> A = agl.a(kd.q, new agm("mob_attack_no_aggro"));
   agl<bjv> B = agl.a(kd.q, new agm("player_attack"));
   agl<bjv> C = agl.a(kd.q, new agm("arrow"));
   agl<bjv> D = agl.a(kd.q, new agm("trident"));
   agl<bjv> E = agl.a(kd.q, new agm("mob_projectile"));
   agl<bjv> F = agl.a(kd.q, new agm("fireworks"));
   agl<bjv> G = agl.a(kd.q, new agm("fireball"));
   agl<bjv> H = agl.a(kd.q, new agm("unattributed_fireball"));
   agl<bjv> I = agl.a(kd.q, new agm("wither_skull"));
   agl<bjv> J = agl.a(kd.q, new agm("thrown"));
   agl<bjv> K = agl.a(kd.q, new agm("indirect_magic"));
   agl<bjv> L = agl.a(kd.q, new agm("thorns"));
   agl<bjv> M = agl.a(kd.q, new agm("explosion"));
   agl<bjv> N = agl.a(kd.q, new agm("player_explosion"));
   agl<bjv> O = agl.a(kd.q, new agm("sonic_boom"));
   agl<bjv> P = agl.a(kd.q, new agm("bad_respawn_point"));
   agl<bjv> Q = agl.a(kd.q, new agm("outside_border"));
   agl<bjv> R = agl.a(kd.q, new agm("generic_kill"));

   static void a(oz<bjv> $$0) {
      $$0.a(a, new bjv("inFire", 0.1F, bjr.d));
      $$0.a(b, new bjv("lightningBolt", 0.1F));
      $$0.a(c, new bjv("onFire", 0.0F, bjr.d));
      $$0.a(d, new bjv("lava", 0.1F, bjr.d));
      $$0.a(e, new bjv("hotFloor", 0.1F, bjr.d));
      $$0.a(f, new bjv("inWall", 0.0F));
      $$0.a(g, new bjv("cramming", 0.0F));
      $$0.a(h, new bjv("drown", 0.0F, bjr.c));
      $$0.a(i, new bjv("starve", 0.0F));
      $$0.a(j, new bjv("cactus", 0.1F));
      $$0.a(k, new bjv("fall", bjs.b, 0.0F, bjr.a, bjx.b));
      $$0.a(l, new bjv("flyIntoWall", 0.0F));
      $$0.a(m, new bjv("outOfWorld", 0.0F));
      $$0.a(n, new bjv("generic", 0.0F));
      $$0.a(o, new bjv("magic", 0.0F));
      $$0.a(p, new bjv("wither", 0.0F));
      $$0.a(q, new bjv("dragonBreath", 0.0F));
      $$0.a(r, new bjv("dryout", 0.1F));
      $$0.a(s, new bjv("sweetBerryBush", 0.1F, bjr.e));
      $$0.a(t, new bjv("freeze", 0.0F, bjr.f));
      $$0.a(u, new bjv("stalagmite", 0.0F));
      $$0.a(v, new bjv("fallingBlock", 0.1F));
      $$0.a(w, new bjv("anvil", 0.1F));
      $$0.a(x, new bjv("fallingStalactite", 0.1F));
      $$0.a(y, new bjv("sting", 0.1F));
      $$0.a(z, new bjv("mob", 0.1F));
      $$0.a(A, new bjv("mob", 0.1F));
      $$0.a(B, new bjv("player", 0.1F));
      $$0.a(C, new bjv("arrow", 0.1F));
      $$0.a(D, new bjv("trident", 0.1F));
      $$0.a(E, new bjv("mob", 0.1F));
      $$0.a(F, new bjv("fireworks", 0.1F));
      $$0.a(H, new bjv("onFire", 0.1F, bjr.d));
      $$0.a(G, new bjv("fireball", 0.1F, bjr.d));
      $$0.a(I, new bjv("witherSkull", 0.1F));
      $$0.a(J, new bjv("thrown", 0.1F));
      $$0.a(K, new bjv("indirectMagic", 0.0F));
      $$0.a(L, new bjv("thorns", 0.1F, bjr.b));
      $$0.a(M, new bjv("explosion", bjs.c, 0.1F));
      $$0.a(N, new bjv("explosion.player", bjs.c, 0.1F));
      $$0.a(O, new bjv("sonic_boom", bjs.c, 0.0F));
      $$0.a(P, new bjv("badRespawnPoint", bjs.c, 0.1F, bjr.a, bjx.c));
      $$0.a(Q, new bjv("outsideBorder", 0.0F));
      $$0.a(R, new bjv("genericKill", 0.0F));
   }
}
