public interface bmq {
   aix<bmp> a = aix.a(kg.r, new aiy("in_fire"));
   aix<bmp> b = aix.a(kg.r, new aiy("lightning_bolt"));
   aix<bmp> c = aix.a(kg.r, new aiy("on_fire"));
   aix<bmp> d = aix.a(kg.r, new aiy("lava"));
   aix<bmp> e = aix.a(kg.r, new aiy("hot_floor"));
   aix<bmp> f = aix.a(kg.r, new aiy("in_wall"));
   aix<bmp> g = aix.a(kg.r, new aiy("cramming"));
   aix<bmp> h = aix.a(kg.r, new aiy("drown"));
   aix<bmp> i = aix.a(kg.r, new aiy("starve"));
   aix<bmp> j = aix.a(kg.r, new aiy("cactus"));
   aix<bmp> k = aix.a(kg.r, new aiy("fall"));
   aix<bmp> l = aix.a(kg.r, new aiy("fly_into_wall"));
   aix<bmp> m = aix.a(kg.r, new aiy("out_of_world"));
   aix<bmp> n = aix.a(kg.r, new aiy("generic"));
   aix<bmp> o = aix.a(kg.r, new aiy("magic"));
   aix<bmp> p = aix.a(kg.r, new aiy("wither"));
   aix<bmp> q = aix.a(kg.r, new aiy("dragon_breath"));
   aix<bmp> r = aix.a(kg.r, new aiy("dry_out"));
   aix<bmp> s = aix.a(kg.r, new aiy("sweet_berry_bush"));
   aix<bmp> t = aix.a(kg.r, new aiy("freeze"));
   aix<bmp> u = aix.a(kg.r, new aiy("stalagmite"));
   aix<bmp> v = aix.a(kg.r, new aiy("falling_block"));
   aix<bmp> w = aix.a(kg.r, new aiy("falling_anvil"));
   aix<bmp> x = aix.a(kg.r, new aiy("falling_stalactite"));
   aix<bmp> y = aix.a(kg.r, new aiy("sting"));
   aix<bmp> z = aix.a(kg.r, new aiy("mob_attack"));
   aix<bmp> A = aix.a(kg.r, new aiy("mob_attack_no_aggro"));
   aix<bmp> B = aix.a(kg.r, new aiy("player_attack"));
   aix<bmp> C = aix.a(kg.r, new aiy("arrow"));
   aix<bmp> D = aix.a(kg.r, new aiy("trident"));
   aix<bmp> E = aix.a(kg.r, new aiy("mob_projectile"));
   aix<bmp> F = aix.a(kg.r, new aiy("spit"));
   aix<bmp> G = aix.a(kg.r, new aiy("wind_charge"));
   aix<bmp> H = aix.a(kg.r, new aiy("fireworks"));
   aix<bmp> I = aix.a(kg.r, new aiy("fireball"));
   aix<bmp> J = aix.a(kg.r, new aiy("unattributed_fireball"));
   aix<bmp> K = aix.a(kg.r, new aiy("wither_skull"));
   aix<bmp> L = aix.a(kg.r, new aiy("thrown"));
   aix<bmp> M = aix.a(kg.r, new aiy("indirect_magic"));
   aix<bmp> N = aix.a(kg.r, new aiy("thorns"));
   aix<bmp> O = aix.a(kg.r, new aiy("explosion"));
   aix<bmp> P = aix.a(kg.r, new aiy("player_explosion"));
   aix<bmp> Q = aix.a(kg.r, new aiy("sonic_boom"));
   aix<bmp> R = aix.a(kg.r, new aiy("bad_respawn_point"));
   aix<bmp> S = aix.a(kg.r, new aiy("outside_border"));
   aix<bmp> T = aix.a(kg.r, new aiy("generic_kill"));

   static void a(ph<bmp> $$0) {
      $$0.a(a, new bmp("inFire", 0.1F, bml.d));
      $$0.a(b, new bmp("lightningBolt", 0.1F));
      $$0.a(c, new bmp("onFire", 0.0F, bml.d));
      $$0.a(d, new bmp("lava", 0.1F, bml.d));
      $$0.a(e, new bmp("hotFloor", 0.1F, bml.d));
      $$0.a(f, new bmp("inWall", 0.0F));
      $$0.a(g, new bmp("cramming", 0.0F));
      $$0.a(h, new bmp("drown", 0.0F, bml.c));
      $$0.a(i, new bmp("starve", 0.0F));
      $$0.a(j, new bmp("cactus", 0.1F));
      $$0.a(k, new bmp("fall", bmm.b, 0.0F, bml.a, bmr.b));
      $$0.a(l, new bmp("flyIntoWall", 0.0F));
      $$0.a(m, new bmp("outOfWorld", 0.0F));
      $$0.a(n, new bmp("generic", 0.0F));
      $$0.a(o, new bmp("magic", 0.0F));
      $$0.a(p, new bmp("wither", 0.0F));
      $$0.a(q, new bmp("dragonBreath", 0.0F));
      $$0.a(r, new bmp("dryout", 0.1F));
      $$0.a(s, new bmp("sweetBerryBush", 0.1F, bml.e));
      $$0.a(t, new bmp("freeze", 0.0F, bml.f));
      $$0.a(u, new bmp("stalagmite", 0.0F));
      $$0.a(v, new bmp("fallingBlock", 0.1F));
      $$0.a(w, new bmp("anvil", 0.1F));
      $$0.a(x, new bmp("fallingStalactite", 0.1F));
      $$0.a(y, new bmp("sting", 0.1F));
      $$0.a(z, new bmp("mob", 0.1F));
      $$0.a(A, new bmp("mob", 0.1F));
      $$0.a(B, new bmp("player", 0.1F));
      $$0.a(C, new bmp("arrow", 0.1F));
      $$0.a(D, new bmp("trident", 0.1F));
      $$0.a(E, new bmp("mob", 0.1F));
      $$0.a(F, new bmp("mob", 0.1F));
      $$0.a(H, new bmp("fireworks", 0.1F));
      $$0.a(J, new bmp("onFire", 0.1F, bml.d));
      $$0.a(I, new bmp("fireball", 0.1F, bml.d));
      $$0.a(K, new bmp("witherSkull", 0.1F));
      $$0.a(L, new bmp("thrown", 0.1F));
      $$0.a(M, new bmp("indirectMagic", 0.0F));
      $$0.a(N, new bmp("thorns", 0.1F, bml.b));
      $$0.a(O, new bmp("explosion", bmm.c, 0.1F));
      $$0.a(P, new bmp("explosion.player", bmm.c, 0.1F));
      $$0.a(Q, new bmp("sonic_boom", bmm.c, 0.0F));
      $$0.a(R, new bmp("badRespawnPoint", bmm.c, 0.1F, bml.a, bmr.c));
      $$0.a(S, new bmp("outsideBorder", 0.0F));
      $$0.a(T, new bmp("genericKill", 0.0F));
   }
}
