public interface bnz {
   ajg<bny> a = ajg.a(kj.r, new ajh("in_fire"));
   ajg<bny> b = ajg.a(kj.r, new ajh("lightning_bolt"));
   ajg<bny> c = ajg.a(kj.r, new ajh("on_fire"));
   ajg<bny> d = ajg.a(kj.r, new ajh("lava"));
   ajg<bny> e = ajg.a(kj.r, new ajh("hot_floor"));
   ajg<bny> f = ajg.a(kj.r, new ajh("in_wall"));
   ajg<bny> g = ajg.a(kj.r, new ajh("cramming"));
   ajg<bny> h = ajg.a(kj.r, new ajh("drown"));
   ajg<bny> i = ajg.a(kj.r, new ajh("starve"));
   ajg<bny> j = ajg.a(kj.r, new ajh("cactus"));
   ajg<bny> k = ajg.a(kj.r, new ajh("fall"));
   ajg<bny> l = ajg.a(kj.r, new ajh("fly_into_wall"));
   ajg<bny> m = ajg.a(kj.r, new ajh("out_of_world"));
   ajg<bny> n = ajg.a(kj.r, new ajh("generic"));
   ajg<bny> o = ajg.a(kj.r, new ajh("magic"));
   ajg<bny> p = ajg.a(kj.r, new ajh("wither"));
   ajg<bny> q = ajg.a(kj.r, new ajh("dragon_breath"));
   ajg<bny> r = ajg.a(kj.r, new ajh("dry_out"));
   ajg<bny> s = ajg.a(kj.r, new ajh("sweet_berry_bush"));
   ajg<bny> t = ajg.a(kj.r, new ajh("freeze"));
   ajg<bny> u = ajg.a(kj.r, new ajh("stalagmite"));
   ajg<bny> v = ajg.a(kj.r, new ajh("falling_block"));
   ajg<bny> w = ajg.a(kj.r, new ajh("falling_anvil"));
   ajg<bny> x = ajg.a(kj.r, new ajh("falling_stalactite"));
   ajg<bny> y = ajg.a(kj.r, new ajh("sting"));
   ajg<bny> z = ajg.a(kj.r, new ajh("mob_attack"));
   ajg<bny> A = ajg.a(kj.r, new ajh("mob_attack_no_aggro"));
   ajg<bny> B = ajg.a(kj.r, new ajh("player_attack"));
   ajg<bny> C = ajg.a(kj.r, new ajh("arrow"));
   ajg<bny> D = ajg.a(kj.r, new ajh("trident"));
   ajg<bny> E = ajg.a(kj.r, new ajh("mob_projectile"));
   ajg<bny> F = ajg.a(kj.r, new ajh("spit"));
   ajg<bny> G = ajg.a(kj.r, new ajh("wind_charge"));
   ajg<bny> H = ajg.a(kj.r, new ajh("fireworks"));
   ajg<bny> I = ajg.a(kj.r, new ajh("fireball"));
   ajg<bny> J = ajg.a(kj.r, new ajh("unattributed_fireball"));
   ajg<bny> K = ajg.a(kj.r, new ajh("wither_skull"));
   ajg<bny> L = ajg.a(kj.r, new ajh("thrown"));
   ajg<bny> M = ajg.a(kj.r, new ajh("indirect_magic"));
   ajg<bny> N = ajg.a(kj.r, new ajh("thorns"));
   ajg<bny> O = ajg.a(kj.r, new ajh("explosion"));
   ajg<bny> P = ajg.a(kj.r, new ajh("player_explosion"));
   ajg<bny> Q = ajg.a(kj.r, new ajh("sonic_boom"));
   ajg<bny> R = ajg.a(kj.r, new ajh("bad_respawn_point"));
   ajg<bny> S = ajg.a(kj.r, new ajh("outside_border"));
   ajg<bny> T = ajg.a(kj.r, new ajh("generic_kill"));

   static void a(pl<bny> $$0) {
      $$0.a(a, new bny("inFire", 0.1F, bnu.d));
      $$0.a(b, new bny("lightningBolt", 0.1F));
      $$0.a(c, new bny("onFire", 0.0F, bnu.d));
      $$0.a(d, new bny("lava", 0.1F, bnu.d));
      $$0.a(e, new bny("hotFloor", 0.1F, bnu.d));
      $$0.a(f, new bny("inWall", 0.0F));
      $$0.a(g, new bny("cramming", 0.0F));
      $$0.a(h, new bny("drown", 0.0F, bnu.c));
      $$0.a(i, new bny("starve", 0.0F));
      $$0.a(j, new bny("cactus", 0.1F));
      $$0.a(k, new bny("fall", bnv.b, 0.0F, bnu.a, boa.b));
      $$0.a(l, new bny("flyIntoWall", 0.0F));
      $$0.a(m, new bny("outOfWorld", 0.0F));
      $$0.a(n, new bny("generic", 0.0F));
      $$0.a(o, new bny("magic", 0.0F));
      $$0.a(p, new bny("wither", 0.0F));
      $$0.a(q, new bny("dragonBreath", 0.0F));
      $$0.a(r, new bny("dryout", 0.1F));
      $$0.a(s, new bny("sweetBerryBush", 0.1F, bnu.e));
      $$0.a(t, new bny("freeze", 0.0F, bnu.f));
      $$0.a(u, new bny("stalagmite", 0.0F));
      $$0.a(v, new bny("fallingBlock", 0.1F));
      $$0.a(w, new bny("anvil", 0.1F));
      $$0.a(x, new bny("fallingStalactite", 0.1F));
      $$0.a(y, new bny("sting", 0.1F));
      $$0.a(z, new bny("mob", 0.1F));
      $$0.a(A, new bny("mob", 0.1F));
      $$0.a(B, new bny("player", 0.1F));
      $$0.a(C, new bny("arrow", 0.1F));
      $$0.a(D, new bny("trident", 0.1F));
      $$0.a(E, new bny("mob", 0.1F));
      $$0.a(F, new bny("mob", 0.1F));
      $$0.a(H, new bny("fireworks", 0.1F));
      $$0.a(J, new bny("onFire", 0.1F, bnu.d));
      $$0.a(I, new bny("fireball", 0.1F, bnu.d));
      $$0.a(K, new bny("witherSkull", 0.1F));
      $$0.a(L, new bny("thrown", 0.1F));
      $$0.a(M, new bny("indirectMagic", 0.0F));
      $$0.a(N, new bny("thorns", 0.1F, bnu.b));
      $$0.a(O, new bny("explosion", bnv.c, 0.1F));
      $$0.a(P, new bny("explosion.player", bnv.c, 0.1F));
      $$0.a(Q, new bny("sonic_boom", bnv.c, 0.0F));
      $$0.a(R, new bny("badRespawnPoint", bnv.c, 0.1F, bnu.a, boa.c));
      $$0.a(S, new bny("outsideBorder", 0.0F));
      $$0.a(T, new bny("genericKill", 0.0F));
   }
}
