public interface bqi {
   akg<bqh> a = akg.a(le.s, new akh("in_fire"));
   akg<bqh> b = akg.a(le.s, new akh("lightning_bolt"));
   akg<bqh> c = akg.a(le.s, new akh("on_fire"));
   akg<bqh> d = akg.a(le.s, new akh("lava"));
   akg<bqh> e = akg.a(le.s, new akh("hot_floor"));
   akg<bqh> f = akg.a(le.s, new akh("in_wall"));
   akg<bqh> g = akg.a(le.s, new akh("cramming"));
   akg<bqh> h = akg.a(le.s, new akh("drown"));
   akg<bqh> i = akg.a(le.s, new akh("starve"));
   akg<bqh> j = akg.a(le.s, new akh("cactus"));
   akg<bqh> k = akg.a(le.s, new akh("fall"));
   akg<bqh> l = akg.a(le.s, new akh("fly_into_wall"));
   akg<bqh> m = akg.a(le.s, new akh("out_of_world"));
   akg<bqh> n = akg.a(le.s, new akh("generic"));
   akg<bqh> o = akg.a(le.s, new akh("magic"));
   akg<bqh> p = akg.a(le.s, new akh("wither"));
   akg<bqh> q = akg.a(le.s, new akh("dragon_breath"));
   akg<bqh> r = akg.a(le.s, new akh("dry_out"));
   akg<bqh> s = akg.a(le.s, new akh("sweet_berry_bush"));
   akg<bqh> t = akg.a(le.s, new akh("freeze"));
   akg<bqh> u = akg.a(le.s, new akh("stalagmite"));
   akg<bqh> v = akg.a(le.s, new akh("falling_block"));
   akg<bqh> w = akg.a(le.s, new akh("falling_anvil"));
   akg<bqh> x = akg.a(le.s, new akh("falling_stalactite"));
   akg<bqh> y = akg.a(le.s, new akh("sting"));
   akg<bqh> z = akg.a(le.s, new akh("mob_attack"));
   akg<bqh> A = akg.a(le.s, new akh("mob_attack_no_aggro"));
   akg<bqh> B = akg.a(le.s, new akh("player_attack"));
   akg<bqh> C = akg.a(le.s, new akh("arrow"));
   akg<bqh> D = akg.a(le.s, new akh("trident"));
   akg<bqh> E = akg.a(le.s, new akh("mob_projectile"));
   akg<bqh> F = akg.a(le.s, new akh("spit"));
   akg<bqh> G = akg.a(le.s, new akh("wind_charge"));
   akg<bqh> H = akg.a(le.s, new akh("fireworks"));
   akg<bqh> I = akg.a(le.s, new akh("fireball"));
   akg<bqh> J = akg.a(le.s, new akh("unattributed_fireball"));
   akg<bqh> K = akg.a(le.s, new akh("wither_skull"));
   akg<bqh> L = akg.a(le.s, new akh("thrown"));
   akg<bqh> M = akg.a(le.s, new akh("indirect_magic"));
   akg<bqh> N = akg.a(le.s, new akh("thorns"));
   akg<bqh> O = akg.a(le.s, new akh("explosion"));
   akg<bqh> P = akg.a(le.s, new akh("player_explosion"));
   akg<bqh> Q = akg.a(le.s, new akh("sonic_boom"));
   akg<bqh> R = akg.a(le.s, new akh("bad_respawn_point"));
   akg<bqh> S = akg.a(le.s, new akh("outside_border"));
   akg<bqh> T = akg.a(le.s, new akh("generic_kill"));

   static void a(ql<bqh> $$0) {
      $$0.a(a, new bqh("inFire", 0.1F, bqd.d));
      $$0.a(b, new bqh("lightningBolt", 0.1F));
      $$0.a(c, new bqh("onFire", 0.0F, bqd.d));
      $$0.a(d, new bqh("lava", 0.1F, bqd.d));
      $$0.a(e, new bqh("hotFloor", 0.1F, bqd.d));
      $$0.a(f, new bqh("inWall", 0.0F));
      $$0.a(g, new bqh("cramming", 0.0F));
      $$0.a(h, new bqh("drown", 0.0F, bqd.c));
      $$0.a(i, new bqh("starve", 0.0F));
      $$0.a(j, new bqh("cactus", 0.1F));
      $$0.a(k, new bqh("fall", bqe.b, 0.0F, bqd.a, bqj.b));
      $$0.a(l, new bqh("flyIntoWall", 0.0F));
      $$0.a(m, new bqh("outOfWorld", 0.0F));
      $$0.a(n, new bqh("generic", 0.0F));
      $$0.a(o, new bqh("magic", 0.0F));
      $$0.a(p, new bqh("wither", 0.0F));
      $$0.a(q, new bqh("dragonBreath", 0.0F));
      $$0.a(r, new bqh("dryout", 0.1F));
      $$0.a(s, new bqh("sweetBerryBush", 0.1F, bqd.e));
      $$0.a(t, new bqh("freeze", 0.0F, bqd.f));
      $$0.a(u, new bqh("stalagmite", 0.0F));
      $$0.a(v, new bqh("fallingBlock", 0.1F));
      $$0.a(w, new bqh("anvil", 0.1F));
      $$0.a(x, new bqh("fallingStalactite", 0.1F));
      $$0.a(y, new bqh("sting", 0.1F));
      $$0.a(z, new bqh("mob", 0.1F));
      $$0.a(A, new bqh("mob", 0.1F));
      $$0.a(B, new bqh("player", 0.1F));
      $$0.a(C, new bqh("arrow", 0.1F));
      $$0.a(D, new bqh("trident", 0.1F));
      $$0.a(E, new bqh("mob", 0.1F));
      $$0.a(F, new bqh("mob", 0.1F));
      $$0.a(H, new bqh("fireworks", 0.1F));
      $$0.a(J, new bqh("onFire", 0.1F, bqd.d));
      $$0.a(I, new bqh("fireball", 0.1F, bqd.d));
      $$0.a(K, new bqh("witherSkull", 0.1F));
      $$0.a(L, new bqh("thrown", 0.1F));
      $$0.a(M, new bqh("indirectMagic", 0.0F));
      $$0.a(N, new bqh("thorns", 0.1F, bqd.b));
      $$0.a(O, new bqh("explosion", bqe.c, 0.1F));
      $$0.a(P, new bqh("explosion.player", bqe.c, 0.1F));
      $$0.a(Q, new bqh("sonic_boom", bqe.c, 0.0F));
      $$0.a(R, new bqh("badRespawnPoint", bqe.c, 0.1F, bqd.a, bqj.c));
      $$0.a(S, new bqh("outsideBorder", 0.0F));
      $$0.a(T, new bqh("genericKill", 0.0F));
   }
}
