public class dcc {
   public static final aeo<dcb> a = a("base");
   public static final aeo<dcb> b = a("square_bottom_left");
   public static final aeo<dcb> c = a("square_bottom_right");
   public static final aeo<dcb> d = a("square_top_left");
   public static final aeo<dcb> e = a("square_top_right");
   public static final aeo<dcb> f = a("stripe_bottom");
   public static final aeo<dcb> g = a("stripe_top");
   public static final aeo<dcb> h = a("stripe_left");
   public static final aeo<dcb> i = a("stripe_right");
   public static final aeo<dcb> j = a("stripe_center");
   public static final aeo<dcb> k = a("stripe_middle");
   public static final aeo<dcb> l = a("stripe_downright");
   public static final aeo<dcb> m = a("stripe_downleft");
   public static final aeo<dcb> n = a("small_stripes");
   public static final aeo<dcb> o = a("cross");
   public static final aeo<dcb> p = a("straight_cross");
   public static final aeo<dcb> q = a("triangle_bottom");
   public static final aeo<dcb> r = a("triangle_top");
   public static final aeo<dcb> s = a("triangles_bottom");
   public static final aeo<dcb> t = a("triangles_top");
   public static final aeo<dcb> u = a("diagonal_left");
   public static final aeo<dcb> v = a("diagonal_up_right");
   public static final aeo<dcb> w = a("diagonal_up_left");
   public static final aeo<dcb> x = a("diagonal_right");
   public static final aeo<dcb> y = a("circle");
   public static final aeo<dcb> z = a("rhombus");
   public static final aeo<dcb> A = a("half_vertical");
   public static final aeo<dcb> B = a("half_horizontal");
   public static final aeo<dcb> C = a("half_vertical_right");
   public static final aeo<dcb> D = a("half_horizontal_bottom");
   public static final aeo<dcb> E = a("border");
   public static final aeo<dcb> F = a("curly_border");
   public static final aeo<dcb> G = a("gradient");
   public static final aeo<dcb> H = a("gradient_up");
   public static final aeo<dcb> I = a("bricks");
   public static final aeo<dcb> J = a("globe");
   public static final aeo<dcb> K = a("creeper");
   public static final aeo<dcb> L = a("skull");
   public static final aeo<dcb> M = a("flower");
   public static final aeo<dcb> N = a("mojang");
   public static final aeo<dcb> O = a("piglin");

   private static aeo<dcb> a(String $$0) {
      return aeo.a(jd.c, new aep($$0));
   }

   public static dcb a(hs<dcb> $$0) {
      hs.a($$0, a, new dcb("b"));
      hs.a($$0, b, new dcb("bl"));
      hs.a($$0, c, new dcb("br"));
      hs.a($$0, d, new dcb("tl"));
      hs.a($$0, e, new dcb("tr"));
      hs.a($$0, f, new dcb("bs"));
      hs.a($$0, g, new dcb("ts"));
      hs.a($$0, h, new dcb("ls"));
      hs.a($$0, i, new dcb("rs"));
      hs.a($$0, j, new dcb("cs"));
      hs.a($$0, k, new dcb("ms"));
      hs.a($$0, l, new dcb("drs"));
      hs.a($$0, m, new dcb("dls"));
      hs.a($$0, n, new dcb("ss"));
      hs.a($$0, o, new dcb("cr"));
      hs.a($$0, p, new dcb("sc"));
      hs.a($$0, q, new dcb("bt"));
      hs.a($$0, r, new dcb("tt"));
      hs.a($$0, s, new dcb("bts"));
      hs.a($$0, t, new dcb("tts"));
      hs.a($$0, u, new dcb("ld"));
      hs.a($$0, v, new dcb("rd"));
      hs.a($$0, w, new dcb("lud"));
      hs.a($$0, x, new dcb("rud"));
      hs.a($$0, y, new dcb("mc"));
      hs.a($$0, z, new dcb("mr"));
      hs.a($$0, A, new dcb("vh"));
      hs.a($$0, B, new dcb("hh"));
      hs.a($$0, C, new dcb("vhr"));
      hs.a($$0, D, new dcb("hhb"));
      hs.a($$0, E, new dcb("bo"));
      hs.a($$0, F, new dcb("cbo"));
      hs.a($$0, G, new dcb("gra"));
      hs.a($$0, H, new dcb("gru"));
      hs.a($$0, I, new dcb("bri"));
      hs.a($$0, J, new dcb("glb"));
      hs.a($$0, K, new dcb("cre"));
      hs.a($$0, L, new dcb("sku"));
      hs.a($$0, M, new dcb("flo"));
      hs.a($$0, N, new dcb("moj"));
      return hs.a($$0, O, new dcb("pig"));
   }
}
