public class dcp {
   public static final aex<dco> a = a("base");
   public static final aex<dco> b = a("square_bottom_left");
   public static final aex<dco> c = a("square_bottom_right");
   public static final aex<dco> d = a("square_top_left");
   public static final aex<dco> e = a("square_top_right");
   public static final aex<dco> f = a("stripe_bottom");
   public static final aex<dco> g = a("stripe_top");
   public static final aex<dco> h = a("stripe_left");
   public static final aex<dco> i = a("stripe_right");
   public static final aex<dco> j = a("stripe_center");
   public static final aex<dco> k = a("stripe_middle");
   public static final aex<dco> l = a("stripe_downright");
   public static final aex<dco> m = a("stripe_downleft");
   public static final aex<dco> n = a("small_stripes");
   public static final aex<dco> o = a("cross");
   public static final aex<dco> p = a("straight_cross");
   public static final aex<dco> q = a("triangle_bottom");
   public static final aex<dco> r = a("triangle_top");
   public static final aex<dco> s = a("triangles_bottom");
   public static final aex<dco> t = a("triangles_top");
   public static final aex<dco> u = a("diagonal_left");
   public static final aex<dco> v = a("diagonal_up_right");
   public static final aex<dco> w = a("diagonal_up_left");
   public static final aex<dco> x = a("diagonal_right");
   public static final aex<dco> y = a("circle");
   public static final aex<dco> z = a("rhombus");
   public static final aex<dco> A = a("half_vertical");
   public static final aex<dco> B = a("half_horizontal");
   public static final aex<dco> C = a("half_vertical_right");
   public static final aex<dco> D = a("half_horizontal_bottom");
   public static final aex<dco> E = a("border");
   public static final aex<dco> F = a("curly_border");
   public static final aex<dco> G = a("gradient");
   public static final aex<dco> H = a("gradient_up");
   public static final aex<dco> I = a("bricks");
   public static final aex<dco> J = a("globe");
   public static final aex<dco> K = a("creeper");
   public static final aex<dco> L = a("skull");
   public static final aex<dco> M = a("flower");
   public static final aex<dco> N = a("mojang");
   public static final aex<dco> O = a("piglin");

   private static aex<dco> a(String $$0) {
      return aex.a(je.c, new aey($$0));
   }

   public static dco a(ht<dco> $$0) {
      ht.a($$0, a, new dco("b"));
      ht.a($$0, b, new dco("bl"));
      ht.a($$0, c, new dco("br"));
      ht.a($$0, d, new dco("tl"));
      ht.a($$0, e, new dco("tr"));
      ht.a($$0, f, new dco("bs"));
      ht.a($$0, g, new dco("ts"));
      ht.a($$0, h, new dco("ls"));
      ht.a($$0, i, new dco("rs"));
      ht.a($$0, j, new dco("cs"));
      ht.a($$0, k, new dco("ms"));
      ht.a($$0, l, new dco("drs"));
      ht.a($$0, m, new dco("dls"));
      ht.a($$0, n, new dco("ss"));
      ht.a($$0, o, new dco("cr"));
      ht.a($$0, p, new dco("sc"));
      ht.a($$0, q, new dco("bt"));
      ht.a($$0, r, new dco("tt"));
      ht.a($$0, s, new dco("bts"));
      ht.a($$0, t, new dco("tts"));
      ht.a($$0, u, new dco("ld"));
      ht.a($$0, v, new dco("rd"));
      ht.a($$0, w, new dco("lud"));
      ht.a($$0, x, new dco("rud"));
      ht.a($$0, y, new dco("mc"));
      ht.a($$0, z, new dco("mr"));
      ht.a($$0, A, new dco("vh"));
      ht.a($$0, B, new dco("hh"));
      ht.a($$0, C, new dco("vhr"));
      ht.a($$0, D, new dco("hhb"));
      ht.a($$0, E, new dco("bo"));
      ht.a($$0, F, new dco("cbo"));
      ht.a($$0, G, new dco("gra"));
      ht.a($$0, H, new dco("gru"));
      ht.a($$0, I, new dco("bri"));
      ht.a($$0, J, new dco("glb"));
      ht.a($$0, K, new dco("cre"));
      ht.a($$0, L, new dco("sku"));
      ht.a($$0, M, new dco("flo"));
      ht.a($$0, N, new dco("moj"));
      return ht.a($$0, O, new dco("pig"));
   }
}
