import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class feb {
   private static final fei a = new fei(0.008F);
   private static final fei b = new fei(1.0F);
   private static final fei c = new fei(0.5F);

   public static Map<fec, fek> a() {
      Builder<fec, fek> $$0 = ImmutableMap.builder();
      fek $$1 = fek.a(fbs.a(fei.a, 0.0F), 64, 64);
      fek $$2 = fek.a(fbr.a(b), 64, 32);
      fek $$3 = fek.a(fbr.a(new fei(1.02F)), 64, 32);
      fek $$4 = fek.a(fbr.a(c), 64, 32);
      fek $$5 = fca.b();
      fek $$6 = fdb.c();
      fek $$7 = fek.a(fbq.a(fei.a), 64, 64);
      fek $$8 = fbt.b();
      fek $$9 = fay.c();
      fek $$10 = fek.a(fcd.a(fei.a), 64, 32);
      fek $$11 = fek.a(fcj.a(fei.a), 64, 64);
      fek $$12 = fek.a(fci.a(), 64, 64);
      fek $$13 = fdb.b();
      fek $$14 = fby.a(fei.a);
      fek $$15 = fdi.b();
      fek $$16 = fbp.c();
      fek $$17 = fda.c();
      fek $$18 = fek.a(fdq.b(), 64, 64);
      fek $$19 = fdg.b();
      $$0.put(fed.a, fae.b());
      $$0.put(fed.b, fai.c());
      $$0.put(fed.c, fah.a(c));
      $$0.put(fed.d, fah.a(b));
      $$0.put(fed.e, faj.c());
      $$0.put(fed.f, flp.a());
      $$0.put(fed.g, fak.b());
      $$0.put(fed.h, flr.c());
      $$0.put(fed.i, flr.b());
      $$0.put(fed.j, fal.c());
      $$0.put(fed.k, fls.b());
      $$0.put(fed.l, fam.b());
      $$0.put(fed.m, fao.a());
      $$0.put(fed.n, $$10);
      $$0.put(fed.o, fek.a(fcd.a(new fei(0.01F)), 64, 32));
      $$0.put(fed.p, fap.b());
      $$0.put(fed.q, $$19);
      $$0.put(fed.r, fma.b());
      $$0.put(fed.s, $$5);
      $$0.put(fed.t, fau.c());
      $$0.put(fed.u, fav.b());
      $$0.put(fed.v, $$5);
      $$0.put(fed.x, fmb.b());
      $$0.put(fed.z, fmb.c());
      $$0.put(fed.y, fmb.d());
      $$0.put(fed.w, fmb.e());
      $$0.put(fed.A, $$9);
      $$0.put(fed.B, faz.a(fei.a));
      $$0.put(fed.C, faz.a(new fei(2.0F)));
      $$0.put(fed.D, $$6);
      $$0.put(fed.E, fmc.b());
      $$0.put(fed.F, fmc.c());
      $$0.put(fed.G, fba.b());
      $$0.put(fed.H, fat.c());
      $$0.put(fed.I, fma.d());
      $$0.put(fed.J, fma.c());
      $$0.put(fed.K, fdy.a());
      $$0.put(fed.L, fbb.a(fei.a));
      $$0.put(fed.M, $$4);
      $$0.put(fed.N, $$4);
      $$0.put(fed.O, fbb.a(new fei(0.25F)));
      $$0.put(fed.P, fbm.b());
      $$0.put(fed.Q, fbc.c());
      $$0.put(fed.R, fbd.c());
      $$0.put(fed.S, fbe.b());
      $$0.put(fed.T, fot.a());
      $$0.put(fed.U, fos.a());
      $$0.put(fed.V, $$8);
      $$0.put(fed.W, fbg.b());
      $$0.put(fed.X, fbh.c());
      $$0.put(fed.Y, fbi.b());
      $$0.put(fed.Z, $$5);
      $$0.put(fed.aa, fbj.b());
      $$0.put(fed.ab, $$1);
      $$0.put(fed.ac, $$4);
      $$0.put(fed.ad, $$2);
      $$0.put(fed.ae, fdh.b());
      $$0.put(fed.af, fbl.c());
      $$0.put(fed.ag, fbm.b());
      $$0.put(fed.ah, $$16);
      $$0.put(fed.ai, $$5);
      $$0.put(fed.aj, $$7);
      $$0.put(fed.ak, fek.a(fbq.a(new fei(0.1F)), 64, 64));
      $$0.put(fed.al, $$1);
      $$0.put(fed.am, $$4);
      $$0.put(fed.an, $$2);
      $$0.put(fed.ao, $$8);
      $$0.put(fed.ap, fbu.b());
      $$0.put(fed.aq, fbw.b());
      $$0.put(fed.ar, $$14);
      $$0.put(fed.as, fby.a(new fei(0.5F)));
      $$0.put(fed.at, fbz.b());
      $$0.put(fed.au, fbv.b());
      $$0.put(fed.av, $$5);
      $$0.put(fed.aw, $$9);
      $$0.put(fed.ax, fat.c());
      $$0.put(fed.ay, $$10);
      $$0.put(fed.az, fce.c());
      $$0.put(fed.aA, fcf.b());
      $$0.put(fed.aB, fcg.b());
      $$0.put(fed.aC, fch.a(fei.a));
      $$0.put(fed.aK, fch.a(new fei(0.5F)));
      $$0.put(fed.aD, $$11);
      $$0.put(fed.aI, $$4);
      $$0.put(fed.aJ, $$3);
      $$0.put(fed.aE, $$11);
      $$0.put(fed.aF, $$4);
      $$0.put(fed.aG, $$3);
      $$0.put(fed.aH, $$12);
      $$0.put(fed.aL, $$8);
      $$0.put(fed.aM, fek.a(fck.a(fei.a, false), 64, 64));
      $$0.put(fed.aN, $$13);
      $$0.put(fed.aO, $$4);
      $$0.put(fed.aP, $$2);
      $$0.put(fed.aQ, fek.a(fck.a(fei.a, true), 64, 64));
      $$0.put(fed.aR, $$4);
      $$0.put(fed.aS, $$2);
      $$0.put(fed.aT, ftn.a());
      $$0.put(fed.aU, fcl.c());
      $$0.put(fed.aV, fcm.b());
      $$0.put(fed.aW, fcn.b());
      $$0.put(fed.aX, fco.b());
      $$0.put(fed.aY, fcq.a());
      $$0.put(fed.aZ, fcs.b());
      $$0.put(fed.ba, fct.b());
      $$0.put(fed.bb, fcv.c());
      $$0.put(fed.bc, fcu.c());
      $$0.put(fed.bd, fcw.a());
      $$0.put(fed.be, fcy.a());
      $$0.put(fed.bf, fcx.b());
      $$0.put(fed.bg, fcz.b());
      $$0.put(fed.bh, $$17);
      $$0.put(fed.bj, $$4);
      $$0.put(fed.bk, $$2);
      $$0.put(fed.bi, $$7);
      $$0.put(fed.bl, $$6);
      $$0.put(fed.bm, fdd.c());
      $$0.put(fed.bn, fdd.b());
      $$0.put(fed.bo, fde.b());
      $$0.put(fed.bp, fdf.b());
      $$0.put(fed.bq, $$5);
      $$0.put(fed.br, $$19);
      $$0.put(fed.bs, fdh.b());
      $$0.put(fed.bt, $$17);
      $$0.put(fed.bu, $$4);
      $$0.put(fed.bv, $$2);
      $$0.put(fed.bw, fek.a(fbs.a(new fei(0.25F), 0.0F), 64, 32));
      $$0.put(fed.bx, $$15);
      $$0.put(fed.by, $$15);
      $$0.put(fed.bz, fdj.c());
      $$0.put(fed.bA, $$5);
      $$0.put(fed.bB, $$14);
      $$0.put(fed.bC, fdk.a());
      $$0.put(fed.bD, fdm.a(fei.a));
      $$0.put(fed.bE, fdm.a(a));
      $$0.put(fed.bF, fdl.a(fei.a));
      $$0.put(fed.bG, fdl.a(a));
      $$0.put(fed.bH, fdn.c());
      $$0.put(fed.bI, fdo.b());
      $$0.put(fed.bJ, $$18);
      $$0.put(fed.bK, $$8);
      $$0.put(fed.bL, fdr.b());
      $$0.put(fed.bM, $$18);
      $$0.put(fed.bN, fdt.c());
      $$0.put(fed.bO, fdu.a(fei.a));
      $$0.put(fed.bP, fdu.a(c));
      $$0.put(fed.bU, frz.a());
      $$0.put(fed.bQ, $$17);
      $$0.put(fed.bR, $$4);
      $$0.put(fed.bS, $$2);
      $$0.put(fed.bT, $$6);
      $$0.put(fed.bV, fdv.c());
      $$0.put(fed.bW, $$16);
      $$0.put(fed.bX, $$1);
      $$0.put(fed.ca, $$4);
      $$0.put(fed.cb, $$2);
      $$0.put(fed.bY, $$13);
      $$0.put(fed.bZ, $$7);
      $$0.put(fed.cc, fdx.c());
      $$0.put(fed.cd, fdx.a(c));
      $$0.put(fed.ce, fdx.a(b));
      $$0.put(fed.cf, $$11);
      $$0.put(fed.cg, $$4);
      $$0.put(fed.ch, $$3);
      fek $$20 = fan.a();
      fek $$21 = far.e();
      fek $$22 = fcr.b();
      fek $$23 = fas.a();

      for (cah.b $$24 : cah.b.values()) {
         if ($$24 == cah.b.i) {
            $$0.put(fed.c($$24), $$22);
            $$0.put(fed.d($$24), $$23);
         } else {
            $$0.put(fed.c($$24), $$20);
            $$0.put(fed.d($$24), $$21);
         }
      }

      fek $$25 = fmi.f();
      ddo.a().forEach($$2x -> $$0.put(fed.a($$2x), $$25));
      fek $$26 = fme.e();
      ddo.a().forEach($$2x -> $$0.put(fed.b($$2x), $$26));
      ImmutableMap<fec, fek> $$27 = $$0.build();
      List<fec> $$28 = fed.a().filter($$1x -> !$$27.containsKey($$1x)).collect(Collectors.toList());
      if (!$$28.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$28);
      } else {
         return $$27;
      }
   }
}
