import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class fhp {
   private static final fhw a = new fhw(0.008F);
   private static final fhw b = new fhw(1.0F);
   private static final fhw c = new fhw(0.5F);

   public static Map<fhq, fhy> a() {
      Builder<fhq, fhy> $$0 = ImmutableMap.builder();
      fhy $$1 = fhy.a(ffg.a(fhw.a, 0.0F), 64, 64);
      fhy $$2 = fhy.a(fff.a(b), 64, 32);
      fhy $$3 = fhy.a(fff.a(new fhw(1.02F)), 64, 32);
      fhy $$4 = fhy.a(fff.a(c), 64, 32);
      fhy $$5 = ffo.b();
      fhy $$6 = fgp.c();
      fhy $$7 = fhy.a(ffe.a(fhw.a), 64, 64);
      fhy $$8 = ffh.b();
      fhy $$9 = fem.c();
      fhy $$10 = fhy.a(ffr.a(fhw.a), 64, 32);
      fhy $$11 = fhy.a(ffx.a(fhw.a), 64, 64);
      fhy $$12 = fhy.a(ffw.a(), 64, 64);
      fhy $$13 = fgp.b();
      fhy $$14 = ffm.a(fhw.a);
      fhy $$15 = fgw.b();
      fhy $$16 = ffd.c();
      fhy $$17 = fgo.c();
      fhy $$18 = fhy.a(fhe.b(), 64, 64);
      fhy $$19 = fgu.b();
      $$0.put(fhr.a, fds.b());
      $$0.put(fhr.b, fdw.c());
      $$0.put(fhr.c, fdv.a(c));
      $$0.put(fhr.d, fdv.a(b));
      $$0.put(fhr.e, fdx.c());
      $$0.put(fhr.f, fpp.a());
      $$0.put(fhr.g, fdy.b());
      $$0.put(fhr.h, fpr.c());
      $$0.put(fhr.i, fpr.b());
      $$0.put(fhr.j, fdz.c());
      $$0.put(fhr.k, fps.b());
      $$0.put(fhr.l, fea.b());
      $$0.put(fhr.m, fec.a());
      $$0.put(fhr.n, $$10);
      $$0.put(fhr.o, fhy.a(ffr.a(new fhw(0.01F)), 64, 32));
      $$0.put(fhr.p, fed.b());
      $$0.put(fhr.q, $$19);
      $$0.put(fhr.r, fqa.b());
      $$0.put(fhr.s, $$5);
      $$0.put(fhr.t, fei.c());
      $$0.put(fhr.u, fej.b());
      $$0.put(fhr.v, $$5);
      $$0.put(fhr.x, fqb.b());
      $$0.put(fhr.z, fqb.c());
      $$0.put(fhr.y, fqb.d());
      $$0.put(fhr.w, fqb.e());
      $$0.put(fhr.A, $$9);
      $$0.put(fhr.B, fen.a(fhw.a));
      $$0.put(fhr.C, fen.a(new fhw(2.0F)));
      $$0.put(fhr.D, $$6);
      $$0.put(fhr.E, fqc.b());
      $$0.put(fhr.F, fqc.c());
      $$0.put(fhr.G, feo.b());
      $$0.put(fhr.H, feh.c());
      $$0.put(fhr.I, fqa.d());
      $$0.put(fhr.J, fqa.c());
      $$0.put(fhr.K, fhm.a());
      $$0.put(fhr.L, fep.a(fhw.a));
      $$0.put(fhr.M, $$4);
      $$0.put(fhr.N, $$4);
      $$0.put(fhr.O, fep.a(new fhw(0.25F)));
      $$0.put(fhr.P, ffa.b());
      $$0.put(fhr.Q, feq.c());
      $$0.put(fhr.R, fer.c());
      $$0.put(fhr.S, fes.b());
      $$0.put(fhr.T, fss.a());
      $$0.put(fhr.U, fsr.a());
      $$0.put(fhr.V, $$8);
      $$0.put(fhr.W, feu.b());
      $$0.put(fhr.X, fev.c());
      $$0.put(fhr.Y, few.b());
      $$0.put(fhr.Z, $$5);
      $$0.put(fhr.aa, fex.b());
      $$0.put(fhr.ab, $$1);
      $$0.put(fhr.ac, $$4);
      $$0.put(fhr.ad, $$2);
      $$0.put(fhr.ae, fgv.b());
      $$0.put(fhr.af, fez.c());
      $$0.put(fhr.ag, ffa.b());
      $$0.put(fhr.ah, $$16);
      $$0.put(fhr.ai, $$5);
      $$0.put(fhr.aj, $$7);
      $$0.put(fhr.ak, fhy.a(ffe.a(new fhw(0.1F)), 64, 64));
      $$0.put(fhr.al, $$1);
      $$0.put(fhr.am, $$4);
      $$0.put(fhr.an, $$2);
      $$0.put(fhr.ao, $$8);
      $$0.put(fhr.ap, ffi.b());
      $$0.put(fhr.aq, ffk.b());
      $$0.put(fhr.ar, $$14);
      $$0.put(fhr.as, ffm.a(new fhw(0.5F)));
      $$0.put(fhr.at, ffn.b());
      $$0.put(fhr.au, ffj.b());
      $$0.put(fhr.av, $$5);
      $$0.put(fhr.aw, $$9);
      $$0.put(fhr.ax, feh.c());
      $$0.put(fhr.ay, $$10);
      $$0.put(fhr.az, ffs.c());
      $$0.put(fhr.aA, fft.b());
      $$0.put(fhr.aB, ffu.b());
      $$0.put(fhr.aC, ffv.a(fhw.a));
      $$0.put(fhr.aK, ffv.a(new fhw(0.5F)));
      $$0.put(fhr.aD, $$11);
      $$0.put(fhr.aI, $$4);
      $$0.put(fhr.aJ, $$3);
      $$0.put(fhr.aE, $$11);
      $$0.put(fhr.aF, $$4);
      $$0.put(fhr.aG, $$3);
      $$0.put(fhr.aH, $$12);
      $$0.put(fhr.aL, $$8);
      $$0.put(fhr.aM, fhy.a(ffy.a(fhw.a, false), 64, 64));
      $$0.put(fhr.aN, $$13);
      $$0.put(fhr.aO, $$4);
      $$0.put(fhr.aP, $$2);
      $$0.put(fhr.aQ, fhy.a(ffy.a(fhw.a, true), 64, 64));
      $$0.put(fhr.aR, $$4);
      $$0.put(fhr.aS, $$2);
      $$0.put(fhr.aT, fxm.a());
      $$0.put(fhr.aU, ffz.c());
      $$0.put(fhr.aV, fga.b());
      $$0.put(fhr.aW, fgb.b());
      $$0.put(fhr.aX, fgc.b());
      $$0.put(fhr.aY, fge.a());
      $$0.put(fhr.aZ, fgg.b());
      $$0.put(fhr.ba, fgh.b());
      $$0.put(fhr.bb, fgj.c());
      $$0.put(fhr.bc, fgi.c());
      $$0.put(fhr.bd, fgk.a());
      $$0.put(fhr.be, fgm.a());
      $$0.put(fhr.bf, fgl.b());
      $$0.put(fhr.bg, fgn.b());
      $$0.put(fhr.bh, $$17);
      $$0.put(fhr.bj, $$4);
      $$0.put(fhr.bk, $$2);
      $$0.put(fhr.bi, $$7);
      $$0.put(fhr.bl, $$6);
      $$0.put(fhr.bm, fgr.c());
      $$0.put(fhr.bn, fgr.b());
      $$0.put(fhr.bo, fgs.b());
      $$0.put(fhr.bp, fgt.b());
      $$0.put(fhr.bq, $$5);
      $$0.put(fhr.br, $$19);
      $$0.put(fhr.bs, fgv.b());
      $$0.put(fhr.bt, $$17);
      $$0.put(fhr.bu, $$4);
      $$0.put(fhr.bv, $$2);
      $$0.put(fhr.bw, fhy.a(ffg.a(new fhw(0.25F), 0.0F), 64, 32));
      $$0.put(fhr.bx, $$15);
      $$0.put(fhr.by, $$15);
      $$0.put(fhr.bz, fgx.c());
      $$0.put(fhr.bA, $$5);
      $$0.put(fhr.bB, $$14);
      $$0.put(fhr.bC, fgy.a());
      $$0.put(fhr.bD, fha.a(fhw.a));
      $$0.put(fhr.bE, fha.a(a));
      $$0.put(fhr.bF, fgz.a(fhw.a));
      $$0.put(fhr.bG, fgz.a(a));
      $$0.put(fhr.bH, fhb.c());
      $$0.put(fhr.bI, fhc.b());
      $$0.put(fhr.bJ, $$18);
      $$0.put(fhr.bK, $$8);
      $$0.put(fhr.bL, fhf.b());
      $$0.put(fhr.bM, $$18);
      $$0.put(fhr.bN, fhh.c());
      $$0.put(fhr.bO, fhi.a(fhw.a));
      $$0.put(fhr.bP, fhi.a(c));
      $$0.put(fhr.bU, fvy.a());
      $$0.put(fhr.bQ, $$17);
      $$0.put(fhr.bR, $$4);
      $$0.put(fhr.bS, $$2);
      $$0.put(fhr.bT, $$6);
      $$0.put(fhr.bV, fhj.c());
      $$0.put(fhr.bW, $$16);
      $$0.put(fhr.bX, $$1);
      $$0.put(fhr.ca, $$4);
      $$0.put(fhr.cb, $$2);
      $$0.put(fhr.bY, $$13);
      $$0.put(fhr.bZ, $$7);
      $$0.put(fhr.cc, fhl.c());
      $$0.put(fhr.cd, fhl.a(c));
      $$0.put(fhr.ce, fhl.a(b));
      $$0.put(fhr.cf, $$11);
      $$0.put(fhr.cg, $$4);
      $$0.put(fhr.ch, $$3);
      fhy $$20 = feb.a();
      fhy $$21 = fef.e();
      fhy $$22 = fgf.b();
      fhy $$23 = feg.a();

      for (cdf.b $$24 : cdf.b.values()) {
         if ($$24 == cdf.b.i) {
            $$0.put(fhr.c($$24), $$22);
            $$0.put(fhr.d($$24), $$23);
         } else {
            $$0.put(fhr.c($$24), $$20);
            $$0.put(fhr.d($$24), $$21);
         }
      }

      fhy $$25 = fqi.f();
      dgm.a().forEach($$2x -> $$0.put(fhr.a($$2x), $$25));
      fhy $$26 = fqe.e();
      dgm.a().forEach($$2x -> $$0.put(fhr.b($$2x), $$26));
      ImmutableMap<fhq, fhy> $$27 = $$0.build();
      List<fhq> $$28 = fhr.a().filter($$1x -> !$$27.containsKey($$1x)).collect(Collectors.toList());
      if (!$$28.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$28);
      } else {
         return $$27;
      }
   }
}
