import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class fib {
   private static final fii a = new fii(0.008F);
   private static final fii b = new fii(1.0F);
   private static final fii c = new fii(0.5F);

   public static Map<fic, fik> a() {
      Builder<fic, fik> $$0 = ImmutableMap.builder();
      fik $$1 = fik.a(ffs.a(fii.a, 0.0F), 64, 64);
      fik $$2 = fik.a(ffr.a(b), 64, 32);
      fik $$3 = fik.a(ffr.a(new fii(1.02F)), 64, 32);
      fik $$4 = fik.a(ffr.a(c), 64, 32);
      fik $$5 = fga.b();
      fik $$6 = fhb.c();
      fik $$7 = fik.a(ffq.a(fii.a), 64, 64);
      fik $$8 = fft.b();
      fik $$9 = fey.c();
      fik $$10 = fik.a(fgd.a(fii.a), 64, 32);
      fik $$11 = fik.a(fgj.a(fii.a), 64, 64);
      fik $$12 = fik.a(fgi.a(), 64, 64);
      fik $$13 = fhb.b();
      fik $$14 = ffy.a(fii.a);
      fik $$15 = fhi.b();
      fik $$16 = ffp.c();
      fik $$17 = fha.c();
      fik $$18 = fik.a(fhq.b(), 64, 64);
      fik $$19 = fhg.b();
      $$0.put(fid.a, fee.b());
      $$0.put(fid.b, fei.c());
      $$0.put(fid.c, feh.a(c));
      $$0.put(fid.d, feh.a(b));
      $$0.put(fid.e, fej.c());
      $$0.put(fid.f, fqb.a());
      $$0.put(fid.g, fek.b());
      $$0.put(fid.h, fqd.c());
      $$0.put(fid.i, fqd.b());
      $$0.put(fid.j, fel.c());
      $$0.put(fid.k, fqe.b());
      $$0.put(fid.l, fem.b());
      $$0.put(fid.m, feo.a());
      $$0.put(fid.n, $$10);
      $$0.put(fid.o, fik.a(fgd.a(new fii(0.01F)), 64, 32));
      $$0.put(fid.p, fep.b());
      $$0.put(fid.q, $$19);
      $$0.put(fid.r, fqm.b());
      $$0.put(fid.s, $$5);
      $$0.put(fid.t, feu.c());
      $$0.put(fid.u, fev.b());
      $$0.put(fid.v, $$5);
      $$0.put(fid.x, fqn.b());
      $$0.put(fid.z, fqn.c());
      $$0.put(fid.y, fqn.d());
      $$0.put(fid.w, fqn.e());
      $$0.put(fid.A, $$9);
      $$0.put(fid.B, fez.a(fii.a));
      $$0.put(fid.C, fez.a(new fii(2.0F)));
      $$0.put(fid.D, $$6);
      $$0.put(fid.E, fqo.b());
      $$0.put(fid.F, fqo.c());
      $$0.put(fid.G, ffa.b());
      $$0.put(fid.H, fet.c());
      $$0.put(fid.I, fqm.d());
      $$0.put(fid.J, fqm.c());
      $$0.put(fid.K, fhy.a());
      $$0.put(fid.L, ffb.a(fii.a));
      $$0.put(fid.M, $$4);
      $$0.put(fid.N, $$4);
      $$0.put(fid.O, ffb.a(new fii(0.25F)));
      $$0.put(fid.P, ffm.b());
      $$0.put(fid.Q, ffc.c());
      $$0.put(fid.R, ffd.c());
      $$0.put(fid.S, ffe.b());
      $$0.put(fid.T, fte.a());
      $$0.put(fid.U, ftd.a());
      $$0.put(fid.V, $$8);
      $$0.put(fid.W, ffg.b());
      $$0.put(fid.X, ffh.c());
      $$0.put(fid.Y, ffi.b());
      $$0.put(fid.Z, $$5);
      $$0.put(fid.aa, ffj.b());
      $$0.put(fid.ab, $$1);
      $$0.put(fid.ac, $$4);
      $$0.put(fid.ad, $$2);
      $$0.put(fid.ae, fhh.b());
      $$0.put(fid.af, ffl.c());
      $$0.put(fid.ag, ffm.b());
      $$0.put(fid.ah, $$16);
      $$0.put(fid.ai, $$5);
      $$0.put(fid.aj, $$7);
      $$0.put(fid.ak, fik.a(ffq.a(new fii(0.1F)), 64, 64));
      $$0.put(fid.al, $$1);
      $$0.put(fid.am, $$4);
      $$0.put(fid.an, $$2);
      $$0.put(fid.ao, $$8);
      $$0.put(fid.ap, ffu.b());
      $$0.put(fid.aq, ffw.b());
      $$0.put(fid.ar, $$14);
      $$0.put(fid.as, ffy.a(new fii(0.5F)));
      $$0.put(fid.at, ffz.b());
      $$0.put(fid.au, ffv.b());
      $$0.put(fid.av, $$5);
      $$0.put(fid.aw, $$9);
      $$0.put(fid.ax, fet.c());
      $$0.put(fid.ay, $$10);
      $$0.put(fid.az, fge.c());
      $$0.put(fid.aA, fgf.b());
      $$0.put(fid.aB, fgg.b());
      $$0.put(fid.aC, fgh.a(fii.a));
      $$0.put(fid.aK, fgh.a(new fii(0.5F)));
      $$0.put(fid.aD, $$11);
      $$0.put(fid.aI, $$4);
      $$0.put(fid.aJ, $$3);
      $$0.put(fid.aE, $$11);
      $$0.put(fid.aF, $$4);
      $$0.put(fid.aG, $$3);
      $$0.put(fid.aH, $$12);
      $$0.put(fid.aL, $$8);
      $$0.put(fid.aM, fik.a(fgk.a(fii.a, false), 64, 64));
      $$0.put(fid.aN, $$13);
      $$0.put(fid.aO, $$4);
      $$0.put(fid.aP, $$2);
      $$0.put(fid.aQ, fik.a(fgk.a(fii.a, true), 64, 64));
      $$0.put(fid.aR, $$4);
      $$0.put(fid.aS, $$2);
      $$0.put(fid.aT, fxy.a());
      $$0.put(fid.aU, fgl.c());
      $$0.put(fid.aV, fgm.b());
      $$0.put(fid.aW, fgn.b());
      $$0.put(fid.aX, fgo.b());
      $$0.put(fid.aY, fgq.a());
      $$0.put(fid.aZ, fgs.b());
      $$0.put(fid.ba, fgt.b());
      $$0.put(fid.bb, fgv.c());
      $$0.put(fid.bc, fgu.c());
      $$0.put(fid.bd, fgw.a());
      $$0.put(fid.be, fgy.a());
      $$0.put(fid.bf, fgx.b());
      $$0.put(fid.bg, fgz.b());
      $$0.put(fid.bh, $$17);
      $$0.put(fid.bj, $$4);
      $$0.put(fid.bk, $$2);
      $$0.put(fid.bi, $$7);
      $$0.put(fid.bl, $$6);
      $$0.put(fid.bm, fhd.c());
      $$0.put(fid.bn, fhd.b());
      $$0.put(fid.bo, fhe.b());
      $$0.put(fid.bp, fhf.b());
      $$0.put(fid.bq, $$5);
      $$0.put(fid.br, $$19);
      $$0.put(fid.bs, fhh.b());
      $$0.put(fid.bt, $$17);
      $$0.put(fid.bu, $$4);
      $$0.put(fid.bv, $$2);
      $$0.put(fid.bw, fik.a(ffs.a(new fii(0.25F), 0.0F), 64, 32));
      $$0.put(fid.bx, $$15);
      $$0.put(fid.by, $$15);
      $$0.put(fid.bz, fhj.c());
      $$0.put(fid.bA, $$5);
      $$0.put(fid.bB, $$14);
      $$0.put(fid.bC, fhk.a());
      $$0.put(fid.bD, fhm.a(fii.a));
      $$0.put(fid.bE, fhm.a(a));
      $$0.put(fid.bF, fhl.a(fii.a));
      $$0.put(fid.bG, fhl.a(a));
      $$0.put(fid.bH, fhn.c());
      $$0.put(fid.bI, fho.b());
      $$0.put(fid.bJ, $$18);
      $$0.put(fid.bK, $$8);
      $$0.put(fid.bL, fhr.b());
      $$0.put(fid.bM, $$18);
      $$0.put(fid.bN, fht.c());
      $$0.put(fid.bO, fhu.a(fii.a));
      $$0.put(fid.bP, fhu.a(c));
      $$0.put(fid.bU, fwk.a());
      $$0.put(fid.bQ, $$17);
      $$0.put(fid.bR, $$4);
      $$0.put(fid.bS, $$2);
      $$0.put(fid.bT, $$6);
      $$0.put(fid.bV, fhv.c());
      $$0.put(fid.bW, $$16);
      $$0.put(fid.bX, $$1);
      $$0.put(fid.ca, $$4);
      $$0.put(fid.cb, $$2);
      $$0.put(fid.bY, $$13);
      $$0.put(fid.bZ, $$7);
      $$0.put(fid.cc, fhx.c());
      $$0.put(fid.cd, fhx.a(c));
      $$0.put(fid.ce, fhx.a(b));
      $$0.put(fid.cf, $$11);
      $$0.put(fid.cg, $$4);
      $$0.put(fid.ch, $$3);
      fik $$20 = fen.a();
      fik $$21 = fer.e();
      fik $$22 = fgr.b();
      fik $$23 = fes.a();

      for (cdp.b $$24 : cdp.b.values()) {
         if ($$24 == cdp.b.i) {
            $$0.put(fid.c($$24), $$22);
            $$0.put(fid.d($$24), $$23);
         } else {
            $$0.put(fid.c($$24), $$20);
            $$0.put(fid.d($$24), $$21);
         }
      }

      fik $$25 = fqu.f();
      dgy.a().forEach($$2x -> $$0.put(fid.a($$2x), $$25));
      fik $$26 = fqq.e();
      dgy.a().forEach($$2x -> $$0.put(fid.b($$2x), $$26));
      ImmutableMap<fic, fik> $$27 = $$0.build();
      List<fic> $$28 = fid.a().filter($$1x -> !$$27.containsKey($$1x)).collect(Collectors.toList());
      if (!$$28.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$28);
      } else {
         return $$27;
      }
   }
}
