import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class fmt {
   private static final fna a = new fna(0.008F);
   private static final fna b = new fna(1.0F);
   private static final fna c = new fna(0.5F);

   public static Map<fmu, fnc> a() {
      Builder<fmu, fnc> $$0 = ImmutableMap.builder();
      fnc $$1 = fnc.a(fkj.a(fna.a, 0.0F), 64, 64);
      fnc $$2 = fnc.a(fki.a(b), 64, 32);
      fnc $$3 = fnc.a(fki.a(new fna(1.02F)), 64, 32);
      fnc $$4 = fnc.a(fki.a(c), 64, 32);
      fnc $$5 = fkr.b();
      fnc $$6 = fls.c();
      fnc $$7 = fnc.a(fkh.a(fna.a), 64, 64);
      fnc $$8 = fkk.b();
      fnc $$9 = fjp.c();
      fnc $$10 = fnc.a(fku.a(fna.a), 64, 32);
      fnc $$11 = fnc.a(fla.a(fna.a), 64, 64);
      fnc $$12 = fnc.a(fkz.a(), 64, 64);
      fnc $$13 = fls.b();
      fnc $$14 = fkp.a(fna.a);
      fnc $$15 = flz.b();
      fnc $$16 = fkg.c();
      fnc $$17 = flr.c();
      fnc $$18 = fnc.a(fmh.b(), 64, 64);
      fnc $$19 = flx.b();
      $$0.put(fmv.a, fiu.b());
      $$0.put(fmv.b, fiy.c());
      $$0.put(fmv.c, fix.a(c));
      $$0.put(fmv.d, fix.a(b));
      $$0.put(fmv.e, fiz.c());
      $$0.put(fmv.f, fvb.a());
      $$0.put(fmv.g, fja.b());
      $$0.put(fmv.h, fvd.c());
      $$0.put(fmv.i, fvd.b());
      $$0.put(fmv.j, fjb.c());
      $$0.put(fmv.k, fve.b());
      $$0.put(fmv.l, fjc.b());
      $$0.put(fmv.m, fje.a());
      $$0.put(fmv.n, fjf.b());
      $$0.put(fmv.p, fjf.c());
      $$0.put(fmv.o, fjf.d());
      $$0.put(fmv.q, $$10);
      $$0.put(fmv.r, fnc.a(fku.a(new fna(0.01F)), 64, 32));
      $$0.put(fmv.s, fjg.b());
      $$0.put(fmv.t, $$19);
      $$0.put(fmv.u, fvm.b());
      $$0.put(fmv.v, $$5);
      $$0.put(fmv.w, fjl.c());
      $$0.put(fmv.x, fjm.b());
      $$0.put(fmv.y, $$5);
      $$0.put(fmv.A, fvn.b());
      $$0.put(fmv.C, fvn.c());
      $$0.put(fmv.B, fvn.d());
      $$0.put(fmv.z, fvn.e());
      $$0.put(fmv.D, $$9);
      $$0.put(fmv.E, fjq.a(fna.a));
      $$0.put(fmv.F, fjq.a(new fna(2.0F)));
      $$0.put(fmv.G, $$6);
      $$0.put(fmv.H, fvo.b());
      $$0.put(fmv.I, fvo.c());
      $$0.put(fmv.J, fjr.b());
      $$0.put(fmv.K, fjk.c());
      $$0.put(fmv.L, fvm.d());
      $$0.put(fmv.M, fvm.c());
      $$0.put(fmv.N, fmq.a());
      $$0.put(fmv.O, fjs.a(fna.a));
      $$0.put(fmv.P, $$4);
      $$0.put(fmv.Q, $$4);
      $$0.put(fmv.R, fjs.a(new fna(0.25F)));
      $$0.put(fmv.S, fkd.b());
      $$0.put(fmv.T, fjt.c());
      $$0.put(fmv.U, fju.c());
      $$0.put(fmv.V, fjv.b());
      $$0.put(fmv.W, fyh.a());
      $$0.put(fmv.X, fyg.a());
      $$0.put(fmv.Y, $$8);
      $$0.put(fmv.Z, fjx.b());
      $$0.put(fmv.aa, fjy.c());
      $$0.put(fmv.ab, fjz.b());
      $$0.put(fmv.ac, $$5);
      $$0.put(fmv.ad, fka.b());
      $$0.put(fmv.ae, $$1);
      $$0.put(fmv.af, $$4);
      $$0.put(fmv.ag, $$2);
      $$0.put(fmv.ah, fly.b());
      $$0.put(fmv.ai, fkc.c());
      $$0.put(fmv.aj, fkd.b());
      $$0.put(fmv.ak, $$16);
      $$0.put(fmv.al, $$5);
      $$0.put(fmv.am, $$7);
      $$0.put(fmv.an, fnc.a(fkh.a(new fna(0.1F)), 64, 64));
      $$0.put(fmv.ao, $$1);
      $$0.put(fmv.ap, $$4);
      $$0.put(fmv.aq, $$2);
      $$0.put(fmv.ar, $$8);
      $$0.put(fmv.as, fkl.b());
      $$0.put(fmv.at, fkn.b());
      $$0.put(fmv.au, $$14);
      $$0.put(fmv.av, fkp.a(new fna(0.5F)));
      $$0.put(fmv.aw, fkq.b());
      $$0.put(fmv.ax, fkm.b());
      $$0.put(fmv.ay, $$5);
      $$0.put(fmv.az, $$9);
      $$0.put(fmv.aA, fjk.c());
      $$0.put(fmv.aB, $$10);
      $$0.put(fmv.aC, fkv.c());
      $$0.put(fmv.aD, fkw.b());
      $$0.put(fmv.aE, fkx.b());
      $$0.put(fmv.aF, fky.a(fna.a));
      $$0.put(fmv.aN, fky.a(new fna(0.5F)));
      $$0.put(fmv.aG, $$11);
      $$0.put(fmv.aL, $$4);
      $$0.put(fmv.aM, $$3);
      $$0.put(fmv.aH, $$11);
      $$0.put(fmv.aI, $$4);
      $$0.put(fmv.aJ, $$3);
      $$0.put(fmv.aK, $$12);
      $$0.put(fmv.aO, $$8);
      $$0.put(fmv.aP, fnc.a(flb.a(fna.a, false), 64, 64));
      $$0.put(fmv.aQ, $$13);
      $$0.put(fmv.aR, $$4);
      $$0.put(fmv.aS, $$2);
      $$0.put(fmv.aT, fnc.a(flb.a(fna.a, true), 64, 64));
      $$0.put(fmv.aU, $$4);
      $$0.put(fmv.aV, $$2);
      $$0.put(fmv.aW, gde.a());
      $$0.put(fmv.aX, flc.c());
      $$0.put(fmv.aY, fld.b());
      $$0.put(fmv.aZ, fle.b());
      $$0.put(fmv.ba, flf.b());
      $$0.put(fmv.bb, flh.a());
      $$0.put(fmv.bc, flj.b());
      $$0.put(fmv.bd, flk.b());
      $$0.put(fmv.be, flm.c());
      $$0.put(fmv.bf, fll.c());
      $$0.put(fmv.bg, fln.a());
      $$0.put(fmv.bh, flp.a());
      $$0.put(fmv.bi, flo.b());
      $$0.put(fmv.bj, flq.b());
      $$0.put(fmv.bk, $$17);
      $$0.put(fmv.bm, $$4);
      $$0.put(fmv.bn, $$2);
      $$0.put(fmv.bl, $$7);
      $$0.put(fmv.bo, $$6);
      $$0.put(fmv.bp, flu.c());
      $$0.put(fmv.bq, flu.b());
      $$0.put(fmv.br, flv.b());
      $$0.put(fmv.bs, flw.b());
      $$0.put(fmv.bt, $$5);
      $$0.put(fmv.bu, $$19);
      $$0.put(fmv.bv, fly.b());
      $$0.put(fmv.bw, $$17);
      $$0.put(fmv.bx, $$4);
      $$0.put(fmv.by, $$2);
      $$0.put(fmv.bz, fnc.a(fkj.a(new fna(0.25F), 0.0F), 64, 32));
      $$0.put(fmv.bA, $$15);
      $$0.put(fmv.bB, $$15);
      $$0.put(fmv.bC, fma.c());
      $$0.put(fmv.bD, $$5);
      $$0.put(fmv.bE, $$14);
      $$0.put(fmv.bF, fmb.a());
      $$0.put(fmv.bG, fmd.a(fna.a));
      $$0.put(fmv.bH, fmd.a(a));
      $$0.put(fmv.bI, fmc.a(fna.a));
      $$0.put(fmv.bJ, fmc.a(a));
      $$0.put(fmv.bK, fme.c());
      $$0.put(fmv.bL, fmf.b());
      $$0.put(fmv.bM, $$18);
      $$0.put(fmv.bN, $$8);
      $$0.put(fmv.bO, fmi.b());
      $$0.put(fmv.bP, $$18);
      $$0.put(fmv.bQ, fmk.b());
      $$0.put(fmv.bR, fml.c());
      $$0.put(fmv.bS, fmm.a(fna.a));
      $$0.put(fmv.bT, fmm.a(c));
      $$0.put(fmv.bY, gbo.a());
      $$0.put(fmv.bU, $$17);
      $$0.put(fmv.bV, $$4);
      $$0.put(fmv.bW, $$2);
      $$0.put(fmv.bX, $$6);
      $$0.put(fmv.bZ, fmn.c());
      $$0.put(fmv.ca, $$16);
      $$0.put(fmv.cb, $$1);
      $$0.put(fmv.ce, $$4);
      $$0.put(fmv.cf, $$2);
      $$0.put(fmv.cc, $$13);
      $$0.put(fmv.cd, $$7);
      $$0.put(fmv.cg, fmp.c());
      $$0.put(fmv.ch, fmp.a(c));
      $$0.put(fmv.ci, fmp.a(b));
      $$0.put(fmv.cj, $$11);
      $$0.put(fmv.ck, $$4);
      $$0.put(fmv.cl, $$3);
      fnc $$20 = fjd.a();
      fnc $$21 = fji.e();
      fnc $$22 = fli.b();
      fnc $$23 = fjj.a();

      for (chb.b $$24 : chb.b.values()) {
         if ($$24 == chb.b.i) {
            $$0.put(fmv.c($$24), $$22);
            $$0.put(fmv.d($$24), $$23);
         } else {
            $$0.put(fmv.c($$24), $$20);
            $$0.put(fmv.d($$24), $$21);
         }
      }

      fnc $$25 = fvu.f();
      dkt.a().forEach($$2x -> $$0.put(fmv.a($$2x), $$25));
      fnc $$26 = fvq.e();
      dkt.a().forEach($$2x -> $$0.put(fmv.b($$2x), $$26));
      ImmutableMap<fmu, fnc> $$27 = $$0.build();
      List<fmu> $$28 = fmv.a().filter($$1x -> !$$27.containsKey($$1x)).collect(Collectors.toList());
      if (!$$28.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$28);
      } else {
         return $$27;
      }
   }
}
