import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class fts {
   private static final ftz a = new ftz(0.008F);
   private static final ftz b = new ftz(1.0F);
   private static final ftz c = new ftz(0.5F);

   public static Map<ftt, fub> a() {
      Builder<ftt, fub> $$0 = ImmutableMap.builder();
      fub $$1 = fub.a(fri.a(ftz.a, 0.0F), 64, 64);
      fub $$2 = fub.a(frh.a(b), 64, 32);
      fub $$3 = fub.a(frh.a(new ftz(1.02F)), 64, 32);
      fub $$4 = fub.a(frh.a(c), 64, 32);
      fub $$5 = frq.b();
      fub $$6 = fsr.c();
      fub $$7 = fub.a(frg.a(ftz.a), 64, 64);
      fub $$8 = frj.b();
      fub $$9 = fqo.c();
      fub $$10 = fub.a(frt.a(ftz.a), 64, 32);
      fub $$11 = fub.a(frz.a(ftz.a), 64, 64);
      fub $$12 = fub.a(fry.a(), 64, 64);
      fub $$13 = fsr.b();
      fub $$14 = fro.a(ftz.a);
      fub $$15 = fsy.b();
      fub $$16 = frf.c();
      fub $$17 = fsq.e();
      fub $$18 = fub.a(ftg.b(), 64, 64);
      fub $$19 = fsw.b();
      $$0.put(ftu.a, fpr.b());
      $$0.put(ftu.b, fpt.b());
      $$0.put(ftu.c, fpw.c());
      $$0.put(ftu.d, fpv.a(c));
      $$0.put(ftu.e, fpv.a(b));
      $$0.put(ftu.f, fpx.c());
      $$0.put(ftu.g, gcd.a());
      $$0.put(ftu.h, fpy.b());
      $$0.put(ftu.i, gcf.c());
      $$0.put(ftu.j, gcf.b());
      $$0.put(ftu.k, fpz.c());
      $$0.put(ftu.l, gcg.b());
      $$0.put(ftu.m, fqa.b());
      $$0.put(ftu.n, fqc.c());
      $$0.put(ftu.o, $$4);
      $$0.put(ftu.p, $$2);
      $$0.put(ftu.q, fub.a(fri.a(new ftz(0.2F), 0.0F), 64, 32));
      $$0.put(ftu.r, fqd.a());
      $$0.put(ftu.s, fqe.a(32, 32));
      $$0.put(ftu.t, $$10);
      $$0.put(ftu.u, fub.a(frt.a(new ftz(0.01F)), 64, 32));
      $$0.put(ftu.v, fqf.b());
      $$0.put(ftu.w, $$19);
      $$0.put(ftu.x, gco.b());
      $$0.put(ftu.y, $$5);
      $$0.put(ftu.z, fqk.c());
      $$0.put(ftu.A, fql.b());
      $$0.put(ftu.B, $$5);
      $$0.put(ftu.D, gcp.b());
      $$0.put(ftu.F, gcp.c());
      $$0.put(ftu.E, gcp.d());
      $$0.put(ftu.C, gcp.e());
      $$0.put(ftu.G, $$9);
      $$0.put(ftu.H, fqp.a(ftz.a));
      $$0.put(ftu.I, fqp.a(new ftz(2.0F)));
      $$0.put(ftu.J, $$6);
      $$0.put(ftu.K, gcq.b());
      $$0.put(ftu.L, gcq.c());
      $$0.put(ftu.M, fqq.b());
      $$0.put(ftu.N, fqj.c());
      $$0.put(ftu.O, gco.d());
      $$0.put(ftu.P, gco.c());
      $$0.put(ftu.Q, ftp.a());
      $$0.put(ftu.R, fqr.a(ftz.a));
      $$0.put(ftu.S, $$4);
      $$0.put(ftu.T, $$4);
      $$0.put(ftu.U, fqr.a(new ftz(0.25F)));
      $$0.put(ftu.V, frc.b());
      $$0.put(ftu.W, fqs.c());
      $$0.put(ftu.X, fqt.c());
      $$0.put(ftu.Y, fqu.b());
      $$0.put(ftu.Z, gfm.a());
      $$0.put(ftu.aa, gfl.a());
      $$0.put(ftu.ab, $$8);
      $$0.put(ftu.ac, fqw.b());
      $$0.put(ftu.ad, fqx.c());
      $$0.put(ftu.ae, fqy.b());
      $$0.put(ftu.af, $$5);
      $$0.put(ftu.ag, fqz.b());
      $$0.put(ftu.ah, $$1);
      $$0.put(ftu.ai, $$4);
      $$0.put(ftu.aj, $$2);
      $$0.put(ftu.ak, fsx.b());
      $$0.put(ftu.al, frb.c());
      $$0.put(ftu.am, frc.b());
      $$0.put(ftu.an, $$16);
      $$0.put(ftu.ao, $$5);
      $$0.put(ftu.ap, $$7);
      $$0.put(ftu.aq, fub.a(frg.a(new ftz(0.1F)), 64, 64));
      $$0.put(ftu.ar, $$1);
      $$0.put(ftu.as, $$4);
      $$0.put(ftu.at, $$2);
      $$0.put(ftu.au, $$8);
      $$0.put(ftu.av, frk.b());
      $$0.put(ftu.aw, frm.b());
      $$0.put(ftu.ax, $$14);
      $$0.put(ftu.ay, fro.a(new ftz(0.5F)));
      $$0.put(ftu.az, frp.b());
      $$0.put(ftu.aA, frl.b());
      $$0.put(ftu.aB, $$5);
      $$0.put(ftu.aC, $$9);
      $$0.put(ftu.aD, fqj.c());
      $$0.put(ftu.aE, $$10);
      $$0.put(ftu.aF, fru.c());
      $$0.put(ftu.aG, frv.b());
      $$0.put(ftu.aH, frw.b());
      $$0.put(ftu.aI, frx.a(ftz.a));
      $$0.put(ftu.aQ, frx.a(new ftz(0.5F)));
      $$0.put(ftu.aJ, $$11);
      $$0.put(ftu.aO, $$4);
      $$0.put(ftu.aP, $$3);
      $$0.put(ftu.aK, $$11);
      $$0.put(ftu.aL, $$4);
      $$0.put(ftu.aM, $$3);
      $$0.put(ftu.aN, $$12);
      $$0.put(ftu.aR, $$8);
      $$0.put(ftu.aS, fub.a(fsa.a(ftz.a, false), 64, 64));
      $$0.put(ftu.aT, $$13);
      $$0.put(ftu.aU, $$4);
      $$0.put(ftu.aV, $$2);
      $$0.put(ftu.aW, fub.a(fsa.a(ftz.a, true), 64, 64));
      $$0.put(ftu.aX, $$4);
      $$0.put(ftu.aY, $$2);
      $$0.put(ftu.aZ, gkk.a());
      $$0.put(ftu.ba, fsb.c());
      $$0.put(ftu.bb, fsc.b());
      $$0.put(ftu.bc, fsd.b());
      $$0.put(ftu.bd, fse.b());
      $$0.put(ftu.be, fsg.a());
      $$0.put(ftu.bf, fsi.b());
      $$0.put(ftu.bg, fsj.b());
      $$0.put(ftu.bh, fsl.c());
      $$0.put(ftu.bi, fsk.c());
      $$0.put(ftu.bj, fsm.a());
      $$0.put(ftu.bk, fso.a());
      $$0.put(ftu.bl, fsn.b());
      $$0.put(ftu.bm, fsp.b());
      $$0.put(ftu.bn, $$17);
      $$0.put(ftu.bp, $$4);
      $$0.put(ftu.bq, $$2);
      $$0.put(ftu.bo, $$7);
      $$0.put(ftu.br, $$6);
      $$0.put(ftu.bs, fst.c());
      $$0.put(ftu.bt, fst.b());
      $$0.put(ftu.bu, fsu.b());
      $$0.put(ftu.bv, fsv.b());
      $$0.put(ftu.bw, $$5);
      $$0.put(ftu.bx, $$19);
      $$0.put(ftu.by, fsx.b());
      $$0.put(ftu.bz, $$17);
      $$0.put(ftu.bA, $$4);
      $$0.put(ftu.bB, $$2);
      $$0.put(ftu.bC, fub.a(fri.a(new ftz(0.25F), 0.0F), 64, 32));
      $$0.put(ftu.bD, $$15);
      $$0.put(ftu.bE, $$15);
      $$0.put(ftu.bF, fsz.c());
      $$0.put(ftu.bG, $$5);
      $$0.put(ftu.bH, $$14);
      $$0.put(ftu.bI, fta.a());
      $$0.put(ftu.bJ, ftc.a(ftz.a));
      $$0.put(ftu.bK, ftc.a(a));
      $$0.put(ftu.bL, ftb.a(ftz.a));
      $$0.put(ftu.bM, ftb.a(a));
      $$0.put(ftu.bN, ftd.c());
      $$0.put(ftu.bO, fte.b());
      $$0.put(ftu.bP, $$18);
      $$0.put(ftu.bQ, $$8);
      $$0.put(ftu.bR, fth.b());
      $$0.put(ftu.bS, $$18);
      $$0.put(ftu.bT, ftj.b());
      $$0.put(ftu.bU, ftk.c());
      $$0.put(ftu.bV, ftl.a(ftz.a));
      $$0.put(ftu.bW, ftl.a(c));
      $$0.put(ftu.cb, git.a());
      $$0.put(ftu.bX, $$17);
      $$0.put(ftu.bY, $$4);
      $$0.put(ftu.bZ, $$2);
      $$0.put(ftu.ca, $$6);
      $$0.put(ftu.cc, fub.a(ftm.a(ftz.a), 64, 32));
      $$0.put(ftu.cd, fub.a(ftm.a(new ftz(0.2F)), 64, 32));
      $$0.put(ftu.ce, $$16);
      $$0.put(ftu.cf, $$1);
      $$0.put(ftu.ci, $$4);
      $$0.put(ftu.cj, $$2);
      $$0.put(ftu.cg, $$13);
      $$0.put(ftu.ch, $$7);
      $$0.put(ftu.ck, fto.c());
      $$0.put(ftu.cl, fto.a(c));
      $$0.put(ftu.cm, fto.a(b));
      $$0.put(ftu.cn, $$11);
      $$0.put(ftu.co, $$4);
      $$0.put(ftu.cp, $$3);
      fub $$20 = fqb.a();
      fub $$21 = fqh.e();
      fub $$22 = fsh.b();
      fub $$23 = fqi.a();

      for (clx.b $$24 : clx.b.values()) {
         if ($$24 == clx.b.i) {
            $$0.put(ftu.c($$24), $$22);
            $$0.put(ftu.d($$24), $$23);
         } else {
            $$0.put(ftu.c($$24), $$20);
            $$0.put(ftu.d($$24), $$21);
         }
      }

      fub $$25 = gcw.f();
      dqv.a().forEach($$2x -> $$0.put(ftu.a($$2x), $$25));
      fub $$26 = gcs.e();
      dqv.a().forEach($$2x -> $$0.put(ftu.b($$2x), $$26));
      ImmutableMap<ftt, fub> $$27 = $$0.build();
      List<ftt> $$28 = ftu.a().filter($$1x -> !$$27.containsKey($$1x)).collect(Collectors.toList());
      if (!$$28.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$28);
      } else {
         return $$27;
      }
   }
}
