import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class fuo {
   private static final fuv a = new fuv(0.008F);
   private static final fuv b = new fuv(1.0F);
   private static final fuv c = new fuv(0.5F);

   public static Map<fup, fux> a() {
      Builder<fup, fux> $$0 = ImmutableMap.builder();
      fux $$1 = fux.a(fse.a(fuv.a, 0.0F), 64, 64);
      fux $$2 = fux.a(fsd.a(b), 64, 32);
      fux $$3 = fux.a(fsd.a(new fuv(1.02F)), 64, 32);
      fux $$4 = fux.a(fsd.a(c), 64, 32);
      fux $$5 = fsm.b();
      fux $$6 = ftn.c();
      fux $$7 = fux.a(fsc.a(fuv.a), 64, 64);
      fux $$8 = fsf.b();
      fux $$9 = frk.c();
      fux $$10 = fux.a(fsp.a(fuv.a), 64, 32);
      fux $$11 = fux.a(fsv.a(fuv.a), 64, 64);
      fux $$12 = fux.a(fsu.a(), 64, 64);
      fux $$13 = ftn.b();
      fux $$14 = fsk.a(fuv.a);
      fux $$15 = ftu.b();
      fux $$16 = fsb.c();
      fux $$17 = ftm.e();
      fux $$18 = fux.a(fuc.b(), 64, 64);
      fux $$19 = fts.b();
      $$0.put(fuq.a, fqn.b());
      $$0.put(fuq.b, fqp.b());
      $$0.put(fuq.c, fqs.c());
      $$0.put(fuq.d, fqr.a(c));
      $$0.put(fuq.e, fqr.a(b));
      $$0.put(fuq.f, fqt.c());
      $$0.put(fuq.g, gcz.a());
      $$0.put(fuq.h, fqu.b());
      $$0.put(fuq.i, gdb.c());
      $$0.put(fuq.j, gdb.b());
      $$0.put(fuq.k, fqv.c());
      $$0.put(fuq.l, gdc.b());
      $$0.put(fuq.m, fqw.b());
      $$0.put(fuq.n, fqy.c());
      $$0.put(fuq.o, $$4);
      $$0.put(fuq.p, $$2);
      $$0.put(fuq.q, fux.a(fse.a(new fuv(0.2F), 0.0F), 64, 32));
      $$0.put(fuq.r, fqz.a());
      $$0.put(fuq.s, fra.a(32, 32));
      $$0.put(fuq.t, $$10);
      $$0.put(fuq.u, fux.a(fsp.a(new fuv(0.01F)), 64, 32));
      $$0.put(fuq.v, frb.b());
      $$0.put(fuq.w, $$19);
      $$0.put(fuq.x, gdk.b());
      $$0.put(fuq.y, $$5);
      $$0.put(fuq.z, frg.c());
      $$0.put(fuq.A, frh.b());
      $$0.put(fuq.B, $$5);
      $$0.put(fuq.D, gdl.b());
      $$0.put(fuq.F, gdl.c());
      $$0.put(fuq.E, gdl.d());
      $$0.put(fuq.C, gdl.e());
      $$0.put(fuq.G, $$9);
      $$0.put(fuq.H, frl.a(fuv.a));
      $$0.put(fuq.I, frl.a(new fuv(2.0F)));
      $$0.put(fuq.J, $$6);
      $$0.put(fuq.K, gdm.b());
      $$0.put(fuq.L, gdm.c());
      $$0.put(fuq.M, frm.b());
      $$0.put(fuq.N, frf.c());
      $$0.put(fuq.O, gdk.d());
      $$0.put(fuq.P, gdk.c());
      $$0.put(fuq.Q, ful.a());
      $$0.put(fuq.R, frn.a(fuv.a));
      $$0.put(fuq.S, $$4);
      $$0.put(fuq.T, $$4);
      $$0.put(fuq.U, frn.a(new fuv(0.25F)));
      $$0.put(fuq.V, fry.b());
      $$0.put(fuq.W, fro.c());
      $$0.put(fuq.X, frp.c());
      $$0.put(fuq.Y, frq.b());
      $$0.put(fuq.Z, ggi.a());
      $$0.put(fuq.aa, ggh.a());
      $$0.put(fuq.ab, $$8);
      $$0.put(fuq.ac, frs.b());
      $$0.put(fuq.ad, frt.c());
      $$0.put(fuq.ae, fru.b());
      $$0.put(fuq.af, $$5);
      $$0.put(fuq.ag, frv.b());
      $$0.put(fuq.ah, $$1);
      $$0.put(fuq.ai, $$4);
      $$0.put(fuq.aj, $$2);
      $$0.put(fuq.ak, ftt.b());
      $$0.put(fuq.al, frx.c());
      $$0.put(fuq.am, fry.b());
      $$0.put(fuq.an, $$16);
      $$0.put(fuq.ao, $$5);
      $$0.put(fuq.ap, $$7);
      $$0.put(fuq.aq, fux.a(fsc.a(new fuv(0.1F)), 64, 64));
      $$0.put(fuq.ar, $$1);
      $$0.put(fuq.as, $$4);
      $$0.put(fuq.at, $$2);
      $$0.put(fuq.au, $$8);
      $$0.put(fuq.av, fsg.b());
      $$0.put(fuq.aw, fsi.b());
      $$0.put(fuq.ax, $$14);
      $$0.put(fuq.ay, fsk.a(new fuv(0.5F)));
      $$0.put(fuq.az, fsl.b());
      $$0.put(fuq.aA, fsh.b());
      $$0.put(fuq.aB, $$5);
      $$0.put(fuq.aC, $$9);
      $$0.put(fuq.aD, frf.c());
      $$0.put(fuq.aE, $$10);
      $$0.put(fuq.aF, fsq.c());
      $$0.put(fuq.aG, fsr.b());
      $$0.put(fuq.aH, fss.b());
      $$0.put(fuq.aI, fst.a(fuv.a));
      $$0.put(fuq.aQ, fst.a(new fuv(0.5F)));
      $$0.put(fuq.aJ, $$11);
      $$0.put(fuq.aO, $$4);
      $$0.put(fuq.aP, $$3);
      $$0.put(fuq.aK, $$11);
      $$0.put(fuq.aL, $$4);
      $$0.put(fuq.aM, $$3);
      $$0.put(fuq.aN, $$12);
      $$0.put(fuq.aR, $$8);
      $$0.put(fuq.aS, fux.a(fsw.a(fuv.a, false), 64, 64));
      $$0.put(fuq.aT, $$13);
      $$0.put(fuq.aU, $$4);
      $$0.put(fuq.aV, $$2);
      $$0.put(fuq.aW, fux.a(fsw.a(fuv.a, true), 64, 64));
      $$0.put(fuq.aX, $$4);
      $$0.put(fuq.aY, $$2);
      $$0.put(fuq.aZ, glg.a());
      $$0.put(fuq.ba, fsx.c());
      $$0.put(fuq.bb, fsy.b());
      $$0.put(fuq.bc, fsz.b());
      $$0.put(fuq.bd, fta.b());
      $$0.put(fuq.be, ftc.a());
      $$0.put(fuq.bf, fte.b());
      $$0.put(fuq.bg, ftf.b());
      $$0.put(fuq.bh, fth.c());
      $$0.put(fuq.bi, ftg.c());
      $$0.put(fuq.bj, fti.a());
      $$0.put(fuq.bk, ftk.a());
      $$0.put(fuq.bl, ftj.b());
      $$0.put(fuq.bm, ftl.b());
      $$0.put(fuq.bn, $$17);
      $$0.put(fuq.bp, $$4);
      $$0.put(fuq.bq, $$2);
      $$0.put(fuq.bo, $$7);
      $$0.put(fuq.br, $$6);
      $$0.put(fuq.bs, ftp.c());
      $$0.put(fuq.bt, ftp.b());
      $$0.put(fuq.bu, ftq.b());
      $$0.put(fuq.bv, ftr.b());
      $$0.put(fuq.bw, $$5);
      $$0.put(fuq.bx, $$19);
      $$0.put(fuq.by, ftt.b());
      $$0.put(fuq.bz, $$17);
      $$0.put(fuq.bA, $$4);
      $$0.put(fuq.bB, $$2);
      $$0.put(fuq.bC, fux.a(fse.a(new fuv(0.25F), 0.0F), 64, 32));
      $$0.put(fuq.bD, $$15);
      $$0.put(fuq.bE, $$15);
      $$0.put(fuq.bF, ftv.c());
      $$0.put(fuq.bG, $$5);
      $$0.put(fuq.bH, $$14);
      $$0.put(fuq.bI, ftw.a());
      $$0.put(fuq.bJ, fty.a(fuv.a));
      $$0.put(fuq.bK, fty.a(a));
      $$0.put(fuq.bL, ftx.a(fuv.a));
      $$0.put(fuq.bM, ftx.a(a));
      $$0.put(fuq.bN, ftz.c());
      $$0.put(fuq.bO, fua.b());
      $$0.put(fuq.bP, $$18);
      $$0.put(fuq.bQ, $$8);
      $$0.put(fuq.bR, fud.b());
      $$0.put(fuq.bS, $$18);
      $$0.put(fuq.bT, fuf.b());
      $$0.put(fuq.bU, fug.c());
      $$0.put(fuq.bV, fuh.a(fuv.a));
      $$0.put(fuq.bW, fuh.a(c));
      $$0.put(fuq.cb, gjp.a());
      $$0.put(fuq.bX, $$17);
      $$0.put(fuq.bY, $$4);
      $$0.put(fuq.bZ, $$2);
      $$0.put(fuq.ca, $$6);
      $$0.put(fuq.cc, fux.a(fui.a(fuv.a), 64, 32));
      $$0.put(fuq.cd, fux.a(fui.a(new fuv(0.2F)), 64, 32));
      $$0.put(fuq.ce, $$16);
      $$0.put(fuq.cf, $$1);
      $$0.put(fuq.ci, $$4);
      $$0.put(fuq.cj, $$2);
      $$0.put(fuq.cg, $$13);
      $$0.put(fuq.ch, $$7);
      $$0.put(fuq.ck, fuk.c());
      $$0.put(fuq.cl, fuk.a(c));
      $$0.put(fuq.cm, fuk.a(b));
      $$0.put(fuq.cn, $$11);
      $$0.put(fuq.co, $$4);
      $$0.put(fuq.cp, $$3);
      fux $$20 = fqx.a();
      fux $$21 = frd.e();
      fux $$22 = ftd.b();
      fux $$23 = fre.a();

      for (cmi.b $$24 : cmi.b.values()) {
         if ($$24 == cmi.b.i) {
            $$0.put(fuq.c($$24), $$22);
            $$0.put(fuq.d($$24), $$23);
         } else {
            $$0.put(fuq.c($$24), $$20);
            $$0.put(fuq.d($$24), $$21);
         }
      }

      fux $$25 = gds.f();
      drl.a().forEach($$2x -> $$0.put(fuq.a($$2x), $$25));
      fux $$26 = gdo.e();
      drl.a().forEach($$2x -> $$0.put(fuq.b($$2x), $$26));
      ImmutableMap<fup, fux> $$27 = $$0.build();
      List<fup> $$28 = fuq.a().filter($$1x -> !$$27.containsKey($$1x)).collect(Collectors.toList());
      if (!$$28.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$28);
      } else {
         return $$27;
      }
   }
}
