import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class fwv {
   private static final fxc a = new fxc(0.008F);
   private static final fxc b = new fxc(1.0F);
   private static final fxc c = new fxc(0.5F);

   public static Map<fww, fxe> a() {
      Builder<fww, fxe> $$0 = ImmutableMap.builder();
      fxe $$1 = fxe.a(ful.a(fxc.a, 0.0F), 64, 64);
      fxe $$2 = fxe.a(fuk.a(b), 64, 32);
      fxe $$3 = fxe.a(fuk.a(new fxc(1.02F)), 64, 32);
      fxe $$4 = fxe.a(fuk.a(c), 64, 32);
      fxe $$5 = fut.b();
      fxe $$6 = fvu.c();
      fxe $$7 = fxe.a(fuj.a(fxc.a), 64, 64);
      fxe $$8 = fum.b();
      fxe $$9 = ftr.c();
      fxe $$10 = fxe.a(fuw.a(fxc.a), 64, 32);
      fxe $$11 = fxe.a(fvc.a(fxc.a), 64, 64);
      fxe $$12 = fxe.a(fvb.a(), 64, 64);
      fxe $$13 = fvu.b();
      fxe $$14 = fur.a(fxc.a);
      fxe $$15 = fwb.b();
      fxe $$16 = fui.c();
      fxe $$17 = fvt.e();
      fxe $$18 = fxe.a(fwj.b(), 64, 64);
      fxe $$19 = fvz.b();
      $$0.put(fwx.a, fsu.b());
      $$0.put(fwx.b, fsw.b());
      $$0.put(fwx.c, fsz.c());
      $$0.put(fwx.d, fsy.a(c));
      $$0.put(fwx.e, fsy.a(b));
      $$0.put(fwx.f, fta.c());
      $$0.put(fwx.g, gfh.a());
      $$0.put(fwx.h, ftb.b());
      $$0.put(fwx.i, gfj.c());
      $$0.put(fwx.j, gfj.b());
      $$0.put(fwx.k, ftc.c());
      $$0.put(fwx.l, gfk.b());
      $$0.put(fwx.m, ftd.b());
      $$0.put(fwx.n, ftf.c());
      $$0.put(fwx.o, $$4);
      $$0.put(fwx.p, $$2);
      $$0.put(fwx.q, fxe.a(ful.a(new fxc(0.2F), 0.0F), 64, 32));
      $$0.put(fwx.r, ftg.a());
      $$0.put(fwx.s, fth.a(32, 32));
      $$0.put(fwx.t, $$10);
      $$0.put(fwx.u, fxe.a(fuw.a(new fxc(0.01F)), 64, 32));
      $$0.put(fwx.v, fti.b());
      $$0.put(fwx.w, $$19);
      $$0.put(fwx.x, gfs.b());
      $$0.put(fwx.y, $$5);
      $$0.put(fwx.z, ftn.c());
      $$0.put(fwx.A, fto.b());
      $$0.put(fwx.B, $$5);
      $$0.put(fwx.D, gft.b());
      $$0.put(fwx.F, gft.c());
      $$0.put(fwx.E, gft.d());
      $$0.put(fwx.C, gft.e());
      $$0.put(fwx.G, $$9);
      $$0.put(fwx.H, fts.a(fxc.a));
      $$0.put(fwx.I, fts.a(new fxc(2.0F)));
      $$0.put(fwx.J, $$6);
      $$0.put(fwx.K, gfu.b());
      $$0.put(fwx.L, gfu.c());
      $$0.put(fwx.M, ftt.b());
      $$0.put(fwx.N, ftm.c());
      $$0.put(fwx.O, gfs.d());
      $$0.put(fwx.P, gfs.c());
      $$0.put(fwx.Q, fws.a());
      $$0.put(fwx.R, ftu.a(fxc.a));
      $$0.put(fwx.S, $$4);
      $$0.put(fwx.T, $$4);
      $$0.put(fwx.U, ftu.a(new fxc(0.25F)));
      $$0.put(fwx.V, fuf.b());
      $$0.put(fwx.W, ftv.c());
      $$0.put(fwx.X, ftw.c());
      $$0.put(fwx.Y, ftx.b());
      $$0.put(fwx.Z, giq.a());
      $$0.put(fwx.aa, gip.a());
      $$0.put(fwx.ab, $$8);
      $$0.put(fwx.ac, ftz.b());
      $$0.put(fwx.ad, fua.c());
      $$0.put(fwx.ae, fub.b());
      $$0.put(fwx.af, $$5);
      $$0.put(fwx.ag, fuc.b());
      $$0.put(fwx.ah, $$1);
      $$0.put(fwx.ai, $$4);
      $$0.put(fwx.aj, $$2);
      $$0.put(fwx.ak, fwa.b());
      $$0.put(fwx.al, fue.c());
      $$0.put(fwx.am, fuf.b());
      $$0.put(fwx.an, $$16);
      $$0.put(fwx.ao, $$5);
      $$0.put(fwx.ap, $$7);
      $$0.put(fwx.aq, fxe.a(fuj.a(new fxc(0.1F)), 64, 64));
      $$0.put(fwx.ar, $$1);
      $$0.put(fwx.as, $$4);
      $$0.put(fwx.at, $$2);
      $$0.put(fwx.au, $$8);
      $$0.put(fwx.av, fun.b());
      $$0.put(fwx.aw, fup.b());
      $$0.put(fwx.ax, $$14);
      $$0.put(fwx.ay, fur.a(new fxc(0.5F)));
      $$0.put(fwx.az, fus.b());
      $$0.put(fwx.aA, fuo.b());
      $$0.put(fwx.aB, $$5);
      $$0.put(fwx.aC, $$9);
      $$0.put(fwx.aD, ftm.c());
      $$0.put(fwx.aE, $$10);
      $$0.put(fwx.aF, fux.c());
      $$0.put(fwx.aG, fuy.b());
      $$0.put(fwx.aH, fuz.b());
      $$0.put(fwx.aI, fva.a(fxc.a));
      $$0.put(fwx.aQ, fva.a(new fxc(0.5F)));
      $$0.put(fwx.aJ, $$11);
      $$0.put(fwx.aO, $$4);
      $$0.put(fwx.aP, $$3);
      $$0.put(fwx.aK, $$11);
      $$0.put(fwx.aL, $$4);
      $$0.put(fwx.aM, $$3);
      $$0.put(fwx.aN, $$12);
      $$0.put(fwx.aR, $$8);
      $$0.put(fwx.aS, fxe.a(fvd.a(fxc.a, false), 64, 64));
      $$0.put(fwx.aT, $$13);
      $$0.put(fwx.aU, $$4);
      $$0.put(fwx.aV, $$2);
      $$0.put(fwx.aW, fxe.a(fvd.a(fxc.a, true), 64, 64));
      $$0.put(fwx.aX, $$4);
      $$0.put(fwx.aY, $$2);
      $$0.put(fwx.aZ, gnp.a());
      $$0.put(fwx.ba, fve.c());
      $$0.put(fwx.bb, fvf.b());
      $$0.put(fwx.bc, fvg.b());
      $$0.put(fwx.bd, fvh.b());
      $$0.put(fwx.be, fvj.a());
      $$0.put(fwx.bf, fvl.b());
      $$0.put(fwx.bg, fvm.b());
      $$0.put(fwx.bh, fvo.c());
      $$0.put(fwx.bi, fvn.c());
      $$0.put(fwx.bj, fvp.a());
      $$0.put(fwx.bk, fvr.a());
      $$0.put(fwx.bl, fvq.b());
      $$0.put(fwx.bm, fvs.b());
      $$0.put(fwx.bn, $$17);
      $$0.put(fwx.bp, $$4);
      $$0.put(fwx.bq, $$2);
      $$0.put(fwx.bo, $$7);
      $$0.put(fwx.br, $$6);
      $$0.put(fwx.bs, fvw.c());
      $$0.put(fwx.bt, fvw.b());
      $$0.put(fwx.bu, fvx.b());
      $$0.put(fwx.bv, fvy.b());
      $$0.put(fwx.bw, $$5);
      $$0.put(fwx.bx, $$19);
      $$0.put(fwx.by, fwa.b());
      $$0.put(fwx.bz, $$17);
      $$0.put(fwx.bA, $$4);
      $$0.put(fwx.bB, $$2);
      $$0.put(fwx.bC, fxe.a(ful.a(new fxc(0.25F), 0.0F), 64, 32));
      $$0.put(fwx.bD, $$15);
      $$0.put(fwx.bE, $$15);
      $$0.put(fwx.bF, fwc.c());
      $$0.put(fwx.bG, $$5);
      $$0.put(fwx.bH, $$14);
      $$0.put(fwx.bI, fwd.a());
      $$0.put(fwx.bJ, fwf.a(fxc.a));
      $$0.put(fwx.bK, fwf.a(a));
      $$0.put(fwx.bL, fwe.a(fxc.a));
      $$0.put(fwx.bM, fwe.a(a));
      $$0.put(fwx.bN, fwg.c());
      $$0.put(fwx.bO, fwh.b());
      $$0.put(fwx.bP, $$18);
      $$0.put(fwx.bQ, $$8);
      $$0.put(fwx.bR, fwk.b());
      $$0.put(fwx.bS, $$18);
      $$0.put(fwx.bT, fwm.b());
      $$0.put(fwx.bU, fwn.c());
      $$0.put(fwx.bV, fwo.a(fxc.a));
      $$0.put(fwx.bW, fwo.a(c));
      $$0.put(fwx.cb, gly.a());
      $$0.put(fwx.bX, $$17);
      $$0.put(fwx.bY, $$4);
      $$0.put(fwx.bZ, $$2);
      $$0.put(fwx.ca, $$6);
      $$0.put(fwx.cc, fxe.a(fwp.a(fxc.a), 64, 32));
      $$0.put(fwx.cd, fxe.a(fwp.a(new fxc(0.2F)), 64, 32));
      $$0.put(fwx.ce, $$16);
      $$0.put(fwx.cf, $$1);
      $$0.put(fwx.ci, $$4);
      $$0.put(fwx.cj, $$2);
      $$0.put(fwx.cg, $$13);
      $$0.put(fwx.ch, $$7);
      $$0.put(fwx.ck, fwr.c());
      $$0.put(fwx.cl, fwr.a(c));
      $$0.put(fwx.cm, fwr.a(b));
      $$0.put(fwx.cn, $$11);
      $$0.put(fwx.co, $$4);
      $$0.put(fwx.cp, $$3);
      fxe $$20 = fte.a();
      fxe $$21 = ftk.e();
      fxe $$22 = fvk.b();
      fxe $$23 = ftl.a();

      for (cot.b $$24 : cot.b.values()) {
         if ($$24 == cot.b.i) {
            $$0.put(fwx.c($$24), $$22);
            $$0.put(fwx.d($$24), $$23);
         } else {
            $$0.put(fwx.c($$24), $$20);
            $$0.put(fwx.d($$24), $$21);
         }
      }

      fxe $$25 = gga.f();
      dtn.a().forEach($$2x -> $$0.put(fwx.a($$2x), $$25));
      fxe $$26 = gfw.e();
      dtn.a().forEach($$2x -> $$0.put(fwx.b($$2x), $$26));
      ImmutableMap<fww, fxe> $$27 = $$0.build();
      List<fww> $$28 = fwx.a().filter($$1x -> !$$27.containsKey($$1x)).collect(Collectors.toList());
      if (!$$28.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$28);
      } else {
         return $$27;
      }
   }
}
