import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class fyf {
   private static final fym a = new fym(0.008F);
   private static final fym b = new fym(1.0F);
   private static final fym c = new fym(0.5F);

   public static Map<fyg, fyo> a() {
      Builder<fyg, fyo> $$0 = ImmutableMap.builder();
      fyo $$1 = fyo.a(fvv.a(fym.a, 0.0F), 64, 64);
      fyo $$2 = fyo.a(fvu.a(b), 64, 32);
      fyo $$3 = fyo.a(fvu.a(new fym(1.02F)), 64, 32);
      fyo $$4 = fyo.a(fvu.a(c), 64, 32);
      fyo $$5 = fwd.b();
      fyo $$6 = fxe.c();
      fyo $$7 = fyo.a(fvt.a(fym.a), 64, 64);
      fyo $$8 = fvw.b();
      fyo $$9 = fvb.c();
      fyo $$10 = fyo.a(fwg.a(fym.a), 64, 32);
      fyo $$11 = fyo.a(fwm.a(fym.a), 64, 64);
      fyo $$12 = fyo.a(fwl.a(), 64, 64);
      fyo $$13 = fxe.b();
      fyo $$14 = fwb.a(fym.a);
      fyo $$15 = fxl.b();
      fyo $$16 = fvs.c();
      fyo $$17 = fxd.e();
      fyo $$18 = fyo.a(fxt.b(), 64, 64);
      fyo $$19 = fxj.b();
      $$0.put(fyh.a, fue.b());
      $$0.put(fyh.b, fug.b());
      $$0.put(fyh.c, fuj.c());
      $$0.put(fyh.d, fui.a(c));
      $$0.put(fyh.e, fui.a(b));
      $$0.put(fyh.f, fuk.c());
      $$0.put(fyh.g, ggs.a());
      $$0.put(fyh.h, ful.b());
      $$0.put(fyh.i, ggu.c());
      $$0.put(fyh.j, ggu.b());
      $$0.put(fyh.k, fum.c());
      $$0.put(fyh.l, ggv.b());
      $$0.put(fyh.m, fun.b());
      $$0.put(fyh.n, fup.c());
      $$0.put(fyh.o, $$4);
      $$0.put(fyh.p, $$2);
      $$0.put(fyh.q, fyo.a(fvv.a(new fym(0.2F), 0.0F), 64, 32));
      $$0.put(fyh.r, fuq.a());
      $$0.put(fyh.s, fur.a(32, 32));
      $$0.put(fyh.t, fur.a(128, 128));
      $$0.put(fyh.u, $$10);
      $$0.put(fyh.v, fyo.a(fwg.a(new fym(0.01F)), 64, 32));
      $$0.put(fyh.w, fus.b());
      $$0.put(fyh.x, $$19);
      $$0.put(fyh.y, ghd.b());
      $$0.put(fyh.z, $$5);
      $$0.put(fyh.A, fux.c());
      $$0.put(fyh.B, fuy.b());
      $$0.put(fyh.C, $$5);
      $$0.put(fyh.E, ghe.b());
      $$0.put(fyh.G, ghe.c());
      $$0.put(fyh.F, ghe.d());
      $$0.put(fyh.D, ghe.e());
      $$0.put(fyh.H, $$9);
      $$0.put(fyh.I, fvc.a(fym.a));
      $$0.put(fyh.J, fvc.a(new fym(2.0F)));
      $$0.put(fyh.K, $$6);
      $$0.put(fyh.L, ghf.b());
      $$0.put(fyh.M, ghf.c());
      $$0.put(fyh.N, fvd.b());
      $$0.put(fyh.O, fuw.c());
      $$0.put(fyh.P, ghd.d());
      $$0.put(fyh.Q, ghd.c());
      $$0.put(fyh.R, fyc.a());
      $$0.put(fyh.S, fve.a(fym.a));
      $$0.put(fyh.T, $$4);
      $$0.put(fyh.U, $$4);
      $$0.put(fyh.V, fve.a(new fym(0.25F)));
      $$0.put(fyh.W, fvp.b());
      $$0.put(fyh.X, fvf.c());
      $$0.put(fyh.Y, fvg.c());
      $$0.put(fyh.Z, fvh.b());
      $$0.put(fyh.aa, gkc.a());
      $$0.put(fyh.ab, gkb.a());
      $$0.put(fyh.ac, $$8);
      $$0.put(fyh.ad, fvj.b());
      $$0.put(fyh.ae, fvk.c());
      $$0.put(fyh.af, fvl.b());
      $$0.put(fyh.ag, $$5);
      $$0.put(fyh.ah, fvm.b());
      $$0.put(fyh.ai, $$1);
      $$0.put(fyh.aj, $$4);
      $$0.put(fyh.ak, $$2);
      $$0.put(fyh.al, fxk.b());
      $$0.put(fyh.am, fvo.c());
      $$0.put(fyh.an, fvp.b());
      $$0.put(fyh.ao, $$16);
      $$0.put(fyh.ap, $$5);
      $$0.put(fyh.aq, $$7);
      $$0.put(fyh.ar, fyo.a(fvt.a(new fym(0.1F)), 64, 64));
      $$0.put(fyh.as, $$1);
      $$0.put(fyh.at, $$4);
      $$0.put(fyh.au, $$2);
      $$0.put(fyh.av, $$8);
      $$0.put(fyh.aw, fvx.b());
      $$0.put(fyh.ax, fvz.b());
      $$0.put(fyh.ay, $$14);
      $$0.put(fyh.az, fwb.a(new fym(0.5F)));
      $$0.put(fyh.aA, fwc.b());
      $$0.put(fyh.aB, fvy.b());
      $$0.put(fyh.aC, $$5);
      $$0.put(fyh.aD, $$9);
      $$0.put(fyh.aE, fuw.c());
      $$0.put(fyh.aF, $$10);
      $$0.put(fyh.aG, fwh.c());
      $$0.put(fyh.aH, fwi.b());
      $$0.put(fyh.aI, fwj.b());
      $$0.put(fyh.aJ, fwk.a(fym.a));
      $$0.put(fyh.aR, fwk.a(new fym(0.5F)));
      $$0.put(fyh.aK, $$11);
      $$0.put(fyh.aP, $$4);
      $$0.put(fyh.aQ, $$3);
      $$0.put(fyh.aL, $$11);
      $$0.put(fyh.aM, $$4);
      $$0.put(fyh.aN, $$3);
      $$0.put(fyh.aO, $$12);
      $$0.put(fyh.aS, $$8);
      $$0.put(fyh.aT, fyo.a(fwn.a(fym.a, false), 64, 64));
      $$0.put(fyh.aU, $$13);
      $$0.put(fyh.aV, $$4);
      $$0.put(fyh.aW, $$2);
      $$0.put(fyh.aX, fyo.a(fwn.a(fym.a, true), 64, 64));
      $$0.put(fyh.aY, $$4);
      $$0.put(fyh.aZ, $$2);
      $$0.put(fyh.ba, gpb.a());
      $$0.put(fyh.bb, fwo.c());
      $$0.put(fyh.bc, fwp.b());
      $$0.put(fyh.bd, fwq.b());
      $$0.put(fyh.be, fwr.b());
      $$0.put(fyh.bf, fwt.a());
      $$0.put(fyh.bg, fwv.b());
      $$0.put(fyh.bh, fww.b());
      $$0.put(fyh.bi, fwy.c());
      $$0.put(fyh.bj, fwx.c());
      $$0.put(fyh.bk, fwz.a());
      $$0.put(fyh.bl, fxb.a());
      $$0.put(fyh.bm, fxa.b());
      $$0.put(fyh.bn, fxc.b());
      $$0.put(fyh.bo, $$17);
      $$0.put(fyh.bq, $$4);
      $$0.put(fyh.br, $$2);
      $$0.put(fyh.bp, $$7);
      $$0.put(fyh.bs, $$6);
      $$0.put(fyh.bt, fxg.c());
      $$0.put(fyh.bu, fxg.b());
      $$0.put(fyh.bv, fxh.b());
      $$0.put(fyh.bw, fxi.b());
      $$0.put(fyh.bx, $$5);
      $$0.put(fyh.by, $$19);
      $$0.put(fyh.bz, fxk.b());
      $$0.put(fyh.bA, $$17);
      $$0.put(fyh.bB, $$4);
      $$0.put(fyh.bC, $$2);
      $$0.put(fyh.bD, fyo.a(fvv.a(new fym(0.25F), 0.0F), 64, 32));
      $$0.put(fyh.bE, $$15);
      $$0.put(fyh.bF, $$15);
      $$0.put(fyh.bG, fxm.c());
      $$0.put(fyh.bH, $$5);
      $$0.put(fyh.bI, $$14);
      $$0.put(fyh.bJ, fxn.a());
      $$0.put(fyh.bK, fxp.a(fym.a));
      $$0.put(fyh.bL, fxp.a(a));
      $$0.put(fyh.bM, fxo.a(fym.a));
      $$0.put(fyh.bN, fxo.a(a));
      $$0.put(fyh.bO, fxq.c());
      $$0.put(fyh.bP, fxr.b());
      $$0.put(fyh.bQ, $$18);
      $$0.put(fyh.bR, $$8);
      $$0.put(fyh.bS, fxu.b());
      $$0.put(fyh.bT, $$18);
      $$0.put(fyh.bU, fxw.b());
      $$0.put(fyh.bV, fxx.c());
      $$0.put(fyh.bW, fxy.a(fym.a));
      $$0.put(fyh.bX, fxy.a(c));
      $$0.put(fyh.cc, gnk.a());
      $$0.put(fyh.bY, $$17);
      $$0.put(fyh.bZ, $$4);
      $$0.put(fyh.ca, $$2);
      $$0.put(fyh.cb, $$6);
      $$0.put(fyh.cd, fyo.a(fxz.a(fym.a), 64, 32));
      $$0.put(fyh.ce, fyo.a(fxz.a(new fym(0.2F)), 64, 32));
      $$0.put(fyh.cf, $$16);
      $$0.put(fyh.cg, $$1);
      $$0.put(fyh.cj, $$4);
      $$0.put(fyh.ck, $$2);
      $$0.put(fyh.ch, $$13);
      $$0.put(fyh.ci, $$7);
      $$0.put(fyh.cl, fyb.c());
      $$0.put(fyh.cm, fyb.a(c));
      $$0.put(fyh.cn, fyb.a(b));
      $$0.put(fyh.co, $$11);
      $$0.put(fyh.cp, $$4);
      $$0.put(fyh.cq, $$3);
      fyo $$20 = fuo.a();
      fyo $$21 = fuu.e();
      fyo $$22 = fwu.b();
      fyo $$23 = fuv.a();

      for (cov.b $$24 : cov.b.values()) {
         if ($$24 == cov.b.i) {
            $$0.put(fyh.c($$24), $$22);
            $$0.put(fyh.d($$24), $$23);
         } else {
            $$0.put(fyh.c($$24), $$20);
            $$0.put(fyh.d($$24), $$21);
         }
      }

      fyo $$25 = ghl.f();
      dup.a().forEach($$2x -> $$0.put(fyh.a($$2x), $$25));
      fyo $$26 = ghh.e();
      dup.a().forEach($$2x -> $$0.put(fyh.b($$2x), $$26));
      ImmutableMap<fyg, fyo> $$27 = $$0.build();
      List<fyg> $$28 = fyh.a().filter($$1x -> !$$27.containsKey($$1x)).collect(Collectors.toList());
      if (!$$28.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$28);
      } else {
         return $$27;
      }
   }
}
