import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gai {
   private static final gap a = new gap(0.008F);
   private static final gap b = new gap(1.0F);
   private static final gap c = new gap(0.5F);

   public static Map<gaj, gar> a() {
      Builder<gaj, gar> $$0 = ImmutableMap.builder();
      gar $$1 = gar.a(fxx.a(gap.a, 0.0F), 64, 64);
      gar $$2 = gar.a(fxw.a(b), 64, 32);
      gar $$3 = gar.a(fxw.a(new gap(1.02F)), 64, 32);
      gar $$4 = gar.a(fxw.a(c), 64, 32);
      gar $$5 = fye.b();
      gar $$6 = fzg.d();
      gar $$7 = gar.a(fwb.a(gap.a), 64, 64);
      gar $$8 = gar.a(fwb.b(gap.a), 64, 64);
      gau $$9 = gau.scaling(0.9375F);
      gar $$10 = fxy.b().a($$9);
      gar $$11 = fwl.b();
      gar $$12 = fwo.b();
      gar $$13 = fxb.b();
      gar $$14 = $$13.a(fxb.a);
      gar $$15 = fxg.b();
      gar $$16 = gar.a(fyg.a(gap.a), 64, 32);
      gar $$17 = $$16.a(fwx.a);
      gar $$18 = gar.a(fyg.a(new gap(0.01F)), 64, 32).a(fwx.a);
      gar $$19 = gar.a(fym.a(gap.a), 64, 64);
      gar $$20 = gar.a(fyl.b(), 64, 64);
      gar $$21 = fzg.c();
      gar $$22 = fyc.a(gap.a);
      gar $$23 = fyc.a(new gap(0.5F));
      gar $$24 = fzn.b();
      gar $$25 = fxu.b();
      gar $$26 = fxu.c();
      gar $$27 = fzf.d();
      gar $$28 = gar.a(fzv.b(), 64, 64).a($$9);
      gar $$29 = fzl.b();
      gar $$30 = fwg.b();
      gar $$31 = fww.b();
      gar $$32 = fwz.b();
      gar $$33 = fxr.b();
      gar $$34 = fyh.b();
      gar $$35 = fyk.a(gap.a);
      gar $$36 = fyk.a(new gap(0.5F));
      gar $$37 = fyq.b();
      gar $$38 = fza.b();
      gar $$39 = fyz.b();
      gar $$40 = fzj.b();
      gar $$41 = fzs.b();
      gar $$42 = gar.a(gaa.a(gap.a), 64, 32);
      gar $$43 = gar.a(gaa.a(new gap(0.2F)), 64, 32);
      gar $$44 = gac.b();
      gar $$45 = fwj.b();
      gar $$46 = fwi.a(c);
      gar $$47 = fwi.a(b);
      gar $$48 = fxf.a(gap.a);
      gar $$49 = fxf.a(new gap(0.25F));
      gar $$50 = fzm.b();
      gar $$51 = fxd.b();
      gar $$52 = fyy.b();
      $$0.put(gak.a, fwe.b());
      $$0.put(gak.b, $$30);
      $$0.put(gak.c, $$30.a(fwg.a));
      $$0.put(gak.d, $$45);
      $$0.put(gak.e, $$46);
      $$0.put(gak.f, $$47);
      $$0.put(gak.g, $$45.a(fxx.i));
      $$0.put(gak.h, $$46.a(fxx.i));
      $$0.put(gak.i, $$47.a(fxx.i));
      $$0.put(gak.j, fwk.b());
      $$0.put(gak.k, $$11);
      $$0.put(gak.l, $$11.a(fwl.b));
      $$0.put(gak.m, gjm.a());
      $$0.put(gak.n, fwn.b());
      $$0.put(gak.o, gjo.c());
      $$0.put(gak.p, gjo.b());
      $$0.put(gak.q, $$12);
      $$0.put(gak.r, $$12.a(fwo.a));
      $$0.put(gak.s, fwp.b());
      $$0.put(gak.t, fwq.b());
      $$0.put(gak.u, fwr.b());
      $$0.put(gak.v, fws.d());
      $$0.put(gak.w, fwt.b());
      $$0.put(gak.x, $$4);
      $$0.put(gak.y, $$2);
      $$0.put(gak.z, gar.a(fxx.a(new gap(0.2F), 0.0F), 64, 32));
      $$0.put(gak.A, fwu.b());
      $$0.put(gak.B, fwv.a(32, 32));
      $$0.put(gak.C, fwv.a(128, 128));
      $$0.put(gak.D, $$17);
      $$0.put(gak.E, $$17.a(fwx.b));
      $$0.put(gak.F, $$18);
      $$0.put(gak.G, $$18.a(fwx.b));
      $$0.put(gak.H, $$31);
      $$0.put(gak.I, $$31.a(fww.a));
      $$0.put(gak.J, $$29.a(gau.scaling(0.7F)));
      $$0.put(gak.K, fwy.b());
      $$0.put(gak.L, $$5);
      $$0.put(gak.M, $$32);
      $$0.put(gak.N, $$32.a(fwz.b));
      $$0.put(gak.O, fxa.b());
      $$0.put(gak.P, $$5);
      $$0.put(gak.R, gjy.b());
      $$0.put(gak.T, gjy.c());
      $$0.put(gak.S, gjy.d());
      $$0.put(gak.Q, gjy.e());
      $$0.put(gak.U, $$13);
      $$0.put(gak.V, $$14);
      $$0.put(gak.W, fxc.a(gap.a));
      $$0.put(gak.X, fxc.a(new gap(2.0F)));
      $$0.put(gak.Y, $$6);
      $$0.put(gak.Z, gjz.b());
      $$0.put(gak.aa, gjz.c());
      $$0.put(gak.ab, $$51);
      $$0.put(gak.ac, $$51.a(fxd.a));
      $$0.put(gak.ad, fxe.b());
      $$0.put(gak.ae, fxe.c());
      $$0.put(gak.af, fwy.d());
      $$0.put(gak.ag, fwy.c());
      $$0.put(gak.ah, gae.b());
      $$0.put(gak.ai, $$48);
      $$0.put(gak.aj, $$4);
      $$0.put(gak.ak, $$4);
      $$0.put(gak.al, $$49);
      $$0.put(gak.am, $$48.a(fxx.i));
      $$0.put(gak.an, $$4.a(fxx.i));
      $$0.put(gak.ao, $$4.a(fxx.i));
      $$0.put(gak.ap, $$49.a(fxx.i));
      $$0.put(gak.aq, fxs.c());
      $$0.put(gak.ar, $$15);
      $$0.put(gak.as, $$15.a(fxg.a));
      $$0.put(gak.at, fxi.b());
      $$0.put(gak.au, fxj.b());
      $$0.put(gak.av, gaf.b());
      $$0.put(gak.aw, fxh.b());
      $$0.put(gak.ax, $$10);
      $$0.put(gak.ay, fxl.b());
      $$0.put(gak.az, fxn.b());
      $$0.put(gak.aA, fxn.b().a(fxn.a));
      $$0.put(gak.aB, fxo.b());
      $$0.put(gak.aC, $$5);
      $$0.put(gak.aD, fxp.b());
      gau $$53 = gau.scaling(6.0F);
      $$0.put(gak.aE, $$1.a($$53));
      $$0.put(gak.aF, $$4.a($$53));
      $$0.put(gak.aG, $$2.a($$53));
      $$0.put(gak.aH, $$50);
      $$0.put(gak.aI, $$50.a(fzm.a));
      $$0.put(gak.aJ, $$33);
      $$0.put(gak.aK, $$33.a(fxr.a));
      $$0.put(gak.aL, fxs.b());
      $$0.put(gak.aM, $$25);
      $$0.put(gak.aN, $$26);
      $$0.put(gak.aO, $$5);
      $$0.put(gak.aP, $$7);
      $$0.put(gak.aQ, $$8);
      $$0.put(gak.aR, gar.a(fwb.a(new gap(0.1F)), 64, 64));
      $$0.put(gak.aS, gar.a(fwb.b(new gap(0.1F)), 64, 64));
      gau $$54 = gau.scaling(1.0625F);
      $$0.put(gak.aT, $$1.a($$54));
      $$0.put(gak.aU, $$4.a($$54));
      $$0.put(gak.aV, $$2.a($$54));
      $$0.put(gak.aW, $$1.a(fxx.i).a($$54));
      $$0.put(gak.aX, $$4.a(fxx.i).a($$54));
      $$0.put(gak.aY, $$2.a(fxx.i).a($$54));
      $$0.put(gak.aZ, $$10);
      $$0.put(gak.ba, fxz.b());
      $$0.put(gak.bb, fyb.b());
      $$0.put(gak.bc, $$22);
      $$0.put(gak.bd, $$22.a(fyc.a));
      $$0.put(gak.be, $$23);
      $$0.put(gak.bf, $$23.a(fyc.a));
      $$0.put(gak.bg, fyd.b());
      $$0.put(gak.bh, fya.b());
      $$0.put(gak.bi, $$5);
      $$0.put(gak.bj, $$13);
      $$0.put(gak.bk, $$14);
      $$0.put(gak.bl, fxe.b());
      $$0.put(gak.bm, fxe.c());
      $$0.put(gak.bn, $$16);
      $$0.put(gak.bo, $$16.a(fyg.b));
      $$0.put(gak.bp, $$34);
      $$0.put(gak.bq, $$34.a(fyh.a));
      $$0.put(gak.br, fyi.b());
      $$0.put(gak.bs, fyj.b());
      $$0.put(gak.bt, $$35);
      $$0.put(gak.bu, $$35.a(fyk.a));
      $$0.put(gak.bv, $$36);
      $$0.put(gak.bw, $$36.a(fyk.a));
      $$0.put(gak.bx, $$19);
      $$0.put(gak.bC, $$4);
      $$0.put(gak.bD, $$3);
      $$0.put(gak.by, $$19);
      $$0.put(gak.bz, $$4);
      $$0.put(gak.bA, $$3);
      $$0.put(gak.bE, $$19.a(fxx.i));
      $$0.put(gak.bF, $$4.a(fxx.i));
      $$0.put(gak.bG, $$3.a(fxx.i));
      $$0.put(gak.bB, $$20);
      $$0.put(gak.bH, $$10);
      $$0.put(gak.bI, gar.a(fyp.a(gap.a, false), 64, 64));
      $$0.put(gak.bJ, fyo.b());
      $$0.put(gak.bK, fyn.b());
      $$0.put(gak.bL, $$21);
      $$0.put(gak.bM, $$4);
      $$0.put(gak.bN, $$2);
      $$0.put(gak.bO, gar.a(fyp.a(gap.a, true), 64, 64));
      $$0.put(gak.bP, $$4);
      $$0.put(gak.bQ, $$2);
      $$0.put(gak.bR, gsd.a());
      $$0.put(gak.bS, $$37);
      $$0.put(gak.bT, $$37.a(fyq.a));
      $$0.put(gak.bU, fyr.b());
      $$0.put(gak.bV, fys.b());
      $$0.put(gak.bW, fyt.b());
      $$0.put(gak.bX, fyv.a(false));
      $$0.put(gak.bY, fyv.a(true));
      $$0.put(gak.bZ, fyx.b());
      $$0.put(gak.ca, $$52);
      $$0.put(gak.cb, $$52.a(fyy.a));
      $$0.put(gak.cc, $$52.a(fyy.b));
      $$0.put(gak.cd, $$38);
      $$0.put(gak.ce, $$38.a(fza.a));
      $$0.put(gak.cf, $$39);
      $$0.put(gak.cg, $$39.a(fza.a));
      $$0.put(gak.ch, fzb.b());
      $$0.put(gak.ci, fzd.b());
      $$0.put(gak.cj, fzd.c());
      $$0.put(gak.ck, fzc.b());
      $$0.put(gak.cl, fze.b());
      $$0.put(gak.cm, $$27);
      $$0.put(gak.cp, $$4);
      $$0.put(gak.cq, $$2);
      $$0.put(gak.cn, $$7);
      $$0.put(gak.co, $$8);
      $$0.put(gak.cr, $$6);
      $$0.put(gak.cs, fzi.c());
      $$0.put(gak.ct, fzi.b());
      $$0.put(gak.cu, $$40);
      $$0.put(gak.cv, $$40.a(fzj.a));
      $$0.put(gak.cw, fzk.b());
      $$0.put(gak.cx, $$5);
      $$0.put(gak.cy, $$29);
      $$0.put(gak.cz, $$50);
      $$0.put(gak.cA, $$50.a(fzm.a));
      $$0.put(gak.cB, $$27);
      $$0.put(gak.cC, $$4);
      $$0.put(gak.cD, $$2);
      $$0.put(gak.cE, gar.a(fxx.a(new gap(0.25F), 0.0F), 64, 32));
      $$0.put(gak.cF, $$24);
      $$0.put(gak.cG, $$24);
      $$0.put(gak.cH, fzo.b());
      $$0.put(gak.cI, $$5);
      $$0.put(gak.cJ, $$22);
      $$0.put(gak.cK, $$22.a(fyc.a));
      $$0.put(gak.cL, fzp.b());
      $$0.put(gak.cM, fzr.a(gap.a));
      $$0.put(gak.cN, fzr.a(a));
      $$0.put(gak.cO, fzq.a(gap.a));
      $$0.put(gak.cP, fzq.a(a));
      $$0.put(gak.cQ, $$41);
      $$0.put(gak.cR, $$41.a(fzs.a));
      $$0.put(gak.cS, fzt.b());
      $$0.put(gak.cT, $$28);
      $$0.put(gak.cU, $$10);
      $$0.put(gak.cV, fzw.b());
      $$0.put(gak.cW, $$28);
      $$0.put(gak.cX, fzx.b());
      $$0.put(gak.cY, fzy.b().a($$9));
      $$0.put(gak.cZ, fzz.a(gap.a));
      $$0.put(gak.da, fzz.a(c));
      $$0.put(gak.df, gqm.a());
      gau $$55 = gau.scaling(1.2F);
      $$0.put(gak.db, $$27.a($$55));
      $$0.put(gak.dc, $$4.a($$55));
      $$0.put(gak.dd, $$2.a($$55));
      $$0.put(gak.de, $$6);
      $$0.put(gak.dg, $$42);
      $$0.put(gak.dh, $$43);
      $$0.put(gak.di, $$42.a(gaa.a));
      $$0.put(gak.dj, $$43.a(gaa.a));
      $$0.put(gak.dk, $$25);
      $$0.put(gak.dl, $$26);
      $$0.put(gak.dm, $$1);
      $$0.put(gak.dq, $$4);
      $$0.put(gak.dr, $$2);
      $$0.put(gak.ds, $$1.a(fxx.i));
      $$0.put(gak.dt, $$4.a(fxx.i));
      $$0.put(gak.du, $$2.a(fxx.i));
      $$0.put(gak.dn, $$21);
      $$0.put(gak.do, $$7);
      $$0.put(gak.dp, $$8);
      $$0.put(gak.dv, $$44);
      $$0.put(gak.dw, gac.a(c));
      $$0.put(gak.dx, gac.a(b));
      $$0.put(gak.dy, $$44.a(fxx.i));
      $$0.put(gak.dz, gac.a(c).a(fxx.i));
      $$0.put(gak.dA, gac.a(b).a(fxx.i));
      $$0.put(gak.dB, $$19);
      $$0.put(gak.dC, $$4);
      $$0.put(gak.dD, $$3);
      $$0.put(gak.dE, $$19.a(fxx.i));
      $$0.put(gak.dF, $$4.a(fxx.i));
      $$0.put(gak.dG, $$3.a(fxx.i));
      gar $$56 = fws.b();
      gar $$57 = fws.c();
      gar $$58 = fyw.b();
      gar $$59 = fyw.c();

      for (cpu.b $$60 : cpu.b.values()) {
         if ($$60 == cpu.b.i) {
            $$0.put(gak.a($$60), $$58);
            $$0.put(gak.b($$60), $$59);
         } else {
            $$0.put(gak.a($$60), $$56);
            $$0.put(gak.b($$60), $$57);
         }
      }

      gar $$61 = gkf.a(true);
      gar $$62 = gkf.a(false);
      gar $$63 = gkb.e();
      dwb.a().forEach($$4x -> {
         $$0.put(gak.a($$4x), $$61);
         $$0.put(gak.b($$4x), $$62);
         $$0.put(gak.c($$4x), $$63);
      });
      ImmutableMap<gaj, gar> $$64 = $$0.build();
      List<gaj> $$65 = gak.a().filter($$1x -> !$$64.containsKey($$1x)).collect(Collectors.toList());
      if (!$$65.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$65);
      } else {
         return $$64;
      }
   }
}
