import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gbz {
   private static final gcg a = new gcg(0.008F);
   private static final gcg b = new gcg(1.0F);
   private static final gcg c = new gcg(0.5F);

   public static Map<gca, gci> a() {
      Builder<gca, gci> $$0 = ImmutableMap.builder();
      gci $$1 = gci.a(fzn.a(gcg.a, 0.0F), 64, 64);
      gci $$2 = gci.a(fzm.a(b), 64, 32);
      gci $$3 = gci.a(fzm.a(new gcg(1.02F)), 64, 32);
      gci $$4 = gci.a(fzm.a(c), 64, 32);
      gci $$5 = fzu.a();
      gci $$6 = gaw.c();
      gci $$7 = gci.a(fxr.a(gcg.a), 64, 64);
      gci $$8 = gci.a(fxr.b(gcg.a), 64, 64);
      gcl $$9 = gcl.scaling(0.9375F);
      gci $$10 = fzo.a().a($$9);
      gci $$11 = fyb.a();
      gci $$12 = fye.a();
      gci $$13 = fyr.a();
      gci $$14 = $$13.a(fyr.a);
      gci $$15 = fyw.a();
      gci $$16 = gci.a(fzw.a(gcg.a), 64, 32);
      gci $$17 = $$16.a(fyn.a);
      gci $$18 = gci.a(fzw.a(new gcg(0.01F)), 64, 32).a(fyn.a);
      gci $$19 = gci.a(gac.a(gcg.a), 64, 64);
      gci $$20 = gci.a(gab.a(), 64, 64);
      gci $$21 = gaw.b();
      gci $$22 = fzs.a(gcg.a);
      gci $$23 = fzs.a(new gcg(0.5F));
      gci $$24 = gbe.a();
      gci $$25 = fzk.a();
      gci $$26 = fzk.b();
      gci $$27 = gav.c();
      gci $$28 = gci.a(gbm.a(), 64, 64).a($$9);
      gci $$29 = gbb.a();
      gci $$30 = fxw.a();
      gci $$31 = fym.a();
      gci $$32 = fyp.a();
      gci $$33 = fzh.a();
      gci $$34 = fzx.a();
      gci $$35 = gaa.a(gcg.a);
      gci $$36 = gaa.a(new gcg(0.5F));
      gci $$37 = gag.a();
      gci $$38 = gaq.a();
      gci $$39 = gap.a();
      gci $$40 = gaz.a();
      gci $$41 = gbj.a();
      gci $$42 = gci.a(gbr.a(gcg.a), 64, 32);
      gci $$43 = gci.a(gbr.a(new gcg(0.2F)), 64, 32);
      gci $$44 = gbt.a();
      gci $$45 = fxz.a();
      gci $$46 = fxy.a(c);
      gci $$47 = fxy.a(b);
      gci $$48 = fyv.a(gcg.a);
      gci $$49 = fyv.a(new gcg(0.25F));
      gci $$50 = gbd.a();
      gci $$51 = fyt.a();
      gci $$52 = gao.a();
      $$0.put(gcb.a, fxu.a());
      $$0.put(gcb.b, $$30);
      $$0.put(gcb.c, $$30.a(fxw.a));
      $$0.put(gcb.d, $$45);
      $$0.put(gcb.e, $$46);
      $$0.put(gcb.f, $$47);
      $$0.put(gcb.g, $$45.a(fzn.i));
      $$0.put(gcb.h, $$46.a(fzn.i));
      $$0.put(gcb.i, $$47.a(fzn.i));
      $$0.put(gcb.j, fya.a());
      $$0.put(gcb.k, $$11);
      $$0.put(gcb.l, $$11.a(fyb.b));
      $$0.put(gcb.m, gld.a());
      $$0.put(gcb.n, fyd.a());
      $$0.put(gcb.o, glf.c());
      $$0.put(gcb.p, glf.b());
      $$0.put(gcb.q, $$12);
      $$0.put(gcb.r, $$12.a(fye.a));
      $$0.put(gcb.s, fyf.a());
      $$0.put(gcb.t, fyg.a());
      $$0.put(gcb.u, fyh.a());
      $$0.put(gcb.v, fyi.c());
      $$0.put(gcb.w, fyj.a());
      $$0.put(gcb.x, $$4);
      $$0.put(gcb.y, $$2);
      $$0.put(gcb.z, gci.a(fzn.a(new gcg(0.2F), 0.0F), 64, 32));
      $$0.put(gcb.A, fyk.a());
      $$0.put(gcb.B, fyl.a(32, 32));
      $$0.put(gcb.C, fyl.a(128, 128));
      $$0.put(gcb.D, $$17);
      $$0.put(gcb.E, $$17.a(fyn.b));
      $$0.put(gcb.F, $$18);
      $$0.put(gcb.G, $$18.a(fyn.b));
      $$0.put(gcb.H, $$31);
      $$0.put(gcb.I, $$31.a(fym.a));
      $$0.put(gcb.J, $$29.a(gcl.scaling(0.7F)));
      $$0.put(gcb.K, fyo.a());
      $$0.put(gcb.L, $$5);
      $$0.put(gcb.M, $$32);
      $$0.put(gcb.N, $$32.a(fyp.b));
      $$0.put(gcb.O, fyq.a());
      $$0.put(gcb.P, $$5);
      $$0.put(gcb.R, glp.b());
      $$0.put(gcb.T, glp.c());
      $$0.put(gcb.S, glp.d());
      $$0.put(gcb.Q, glp.e());
      $$0.put(gcb.U, $$13);
      $$0.put(gcb.V, $$14);
      $$0.put(gcb.W, fys.a(gcg.a));
      $$0.put(gcb.X, fys.a(new gcg(2.0F)));
      $$0.put(gcb.Y, $$6);
      $$0.put(gcb.Z, glq.b());
      $$0.put(gcb.aa, glq.c());
      $$0.put(gcb.ab, $$51);
      $$0.put(gcb.ac, $$51.a(fyt.a));
      $$0.put(gcb.ad, fyu.a());
      $$0.put(gcb.ae, fyu.b());
      $$0.put(gcb.af, fyo.c());
      $$0.put(gcb.ag, fyo.b());
      $$0.put(gcb.ah, gbv.a());
      $$0.put(gcb.ai, $$48);
      $$0.put(gcb.aj, $$4);
      $$0.put(gcb.ak, $$4);
      $$0.put(gcb.al, $$49);
      $$0.put(gcb.am, $$48.a(fzn.i));
      $$0.put(gcb.an, $$4.a(fzn.i));
      $$0.put(gcb.ao, $$4.a(fzn.i));
      $$0.put(gcb.ap, $$49.a(fzn.i));
      $$0.put(gcb.aq, fzi.b());
      $$0.put(gcb.ar, $$15);
      $$0.put(gcb.as, $$15.a(fyw.a));
      $$0.put(gcb.at, fyy.a());
      $$0.put(gcb.au, fyz.a());
      $$0.put(gcb.av, gbw.a());
      $$0.put(gcb.aw, fyx.a());
      $$0.put(gcb.ax, $$10);
      $$0.put(gcb.ay, fzb.a());
      $$0.put(gcb.az, fzd.a());
      $$0.put(gcb.aA, fzd.a().a(fzd.a));
      $$0.put(gcb.aB, fze.a());
      $$0.put(gcb.aC, $$5);
      $$0.put(gcb.aD, fzf.a());
      gcl $$53 = gcl.scaling(6.0F);
      $$0.put(gcb.aE, $$1.a($$53));
      $$0.put(gcb.aF, $$4.a($$53));
      $$0.put(gcb.aG, $$2.a($$53));
      $$0.put(gcb.aH, $$50);
      $$0.put(gcb.aI, $$50.a(gbd.a));
      $$0.put(gcb.aJ, $$33);
      $$0.put(gcb.aK, $$33.a(fzh.a));
      $$0.put(gcb.aL, fzi.a());
      $$0.put(gcb.aM, $$25);
      $$0.put(gcb.aN, $$26);
      $$0.put(gcb.aO, $$5);
      $$0.put(gcb.aP, $$7);
      $$0.put(gcb.aQ, $$8);
      $$0.put(gcb.aR, gci.a(fxr.a(new gcg(0.1F)), 64, 64));
      $$0.put(gcb.aS, gci.a(fxr.b(new gcg(0.1F)), 64, 64));
      gcl $$54 = gcl.scaling(1.0625F);
      $$0.put(gcb.aT, $$1.a($$54));
      $$0.put(gcb.aU, $$4.a($$54));
      $$0.put(gcb.aV, $$2.a($$54));
      $$0.put(gcb.aW, $$1.a(fzn.i).a($$54));
      $$0.put(gcb.aX, $$4.a(fzn.i).a($$54));
      $$0.put(gcb.aY, $$2.a(fzn.i).a($$54));
      $$0.put(gcb.aZ, $$10);
      $$0.put(gcb.ba, fzp.a());
      $$0.put(gcb.bb, fzr.a());
      $$0.put(gcb.bc, $$22);
      $$0.put(gcb.bd, $$22.a(fzs.a));
      $$0.put(gcb.be, $$23);
      $$0.put(gcb.bf, $$23.a(fzs.a));
      $$0.put(gcb.bg, fzt.a());
      $$0.put(gcb.bh, fzq.a());
      $$0.put(gcb.bi, $$5);
      $$0.put(gcb.bj, $$13);
      $$0.put(gcb.bk, $$14);
      $$0.put(gcb.bl, fyu.a());
      $$0.put(gcb.bm, fyu.b());
      $$0.put(gcb.bn, $$16);
      $$0.put(gcb.bo, $$16.a(fzw.b));
      $$0.put(gcb.bp, $$34);
      $$0.put(gcb.bq, $$34.a(fzx.a));
      $$0.put(gcb.br, fzy.a());
      $$0.put(gcb.bs, fzz.a());
      $$0.put(gcb.bt, $$35);
      $$0.put(gcb.bu, $$35.a(gaa.a));
      $$0.put(gcb.bv, $$36);
      $$0.put(gcb.bw, $$36.a(gaa.a));
      $$0.put(gcb.bx, $$19);
      $$0.put(gcb.bC, $$4);
      $$0.put(gcb.bD, $$3);
      $$0.put(gcb.by, $$19);
      $$0.put(gcb.bz, $$4);
      $$0.put(gcb.bA, $$3);
      $$0.put(gcb.bE, $$19.a(fzn.i));
      $$0.put(gcb.bF, $$4.a(fzn.i));
      $$0.put(gcb.bG, $$3.a(fzn.i));
      $$0.put(gcb.bB, $$20);
      $$0.put(gcb.bH, $$10);
      $$0.put(gcb.bI, gci.a(gaf.a(gcg.a, false), 64, 64));
      $$0.put(gcb.bJ, gae.a());
      $$0.put(gcb.bK, gad.a());
      $$0.put(gcb.bL, $$21);
      $$0.put(gcb.bM, $$4);
      $$0.put(gcb.bN, $$2);
      $$0.put(gcb.bO, gci.a(gaf.a(gcg.a, true), 64, 64));
      $$0.put(gcb.bP, $$4);
      $$0.put(gcb.bQ, $$2);
      $$0.put(gcb.bR, gbc.a());
      $$0.put(gcb.bS, $$37);
      $$0.put(gcb.bT, $$37.a(gag.a));
      $$0.put(gcb.bU, gah.a());
      $$0.put(gcb.bV, gai.a());
      $$0.put(gcb.bW, gaj.a());
      $$0.put(gcb.bX, gal.a(false));
      $$0.put(gcb.bY, gal.a(true));
      $$0.put(gcb.bZ, gan.a());
      $$0.put(gcb.ca, $$52);
      $$0.put(gcb.cb, $$52.a(gao.a));
      $$0.put(gcb.cc, $$52.a(gao.b));
      $$0.put(gcb.cd, $$38);
      $$0.put(gcb.ce, $$38.a(gaq.a));
      $$0.put(gcb.cf, $$39);
      $$0.put(gcb.cg, $$39.a(gaq.a));
      $$0.put(gcb.ch, gar.a());
      $$0.put(gcb.ci, gat.a());
      $$0.put(gcb.cj, gat.b());
      $$0.put(gcb.ck, gas.a());
      $$0.put(gcb.cl, gau.a());
      $$0.put(gcb.cm, $$27);
      $$0.put(gcb.cp, $$4);
      $$0.put(gcb.cq, $$2);
      $$0.put(gcb.cn, $$7);
      $$0.put(gcb.co, $$8);
      $$0.put(gcb.cr, $$6);
      $$0.put(gcb.cs, gay.b());
      $$0.put(gcb.ct, gay.a());
      $$0.put(gcb.cu, $$40);
      $$0.put(gcb.cv, $$40.a(gaz.a));
      $$0.put(gcb.cw, gba.a());
      $$0.put(gcb.cx, $$5);
      $$0.put(gcb.cy, $$29);
      $$0.put(gcb.cz, $$50);
      $$0.put(gcb.cA, $$50.a(gbd.a));
      $$0.put(gcb.cB, $$27);
      $$0.put(gcb.cC, $$4);
      $$0.put(gcb.cD, $$2);
      $$0.put(gcb.cE, gci.a(fzn.a(new gcg(0.25F), 0.0F), 64, 32));
      $$0.put(gcb.cF, $$24);
      $$0.put(gcb.cG, $$24);
      $$0.put(gcb.cH, gbf.a());
      $$0.put(gcb.cI, $$5);
      $$0.put(gcb.cJ, $$22);
      $$0.put(gcb.cK, $$22.a(fzs.a));
      $$0.put(gcb.cL, gbg.a());
      $$0.put(gcb.cM, gbi.a(gcg.a));
      $$0.put(gcb.cN, gbi.a(a));
      $$0.put(gcb.cO, gbh.a(gcg.a));
      $$0.put(gcb.cP, gbh.a(a));
      $$0.put(gcb.cQ, $$41);
      $$0.put(gcb.cR, $$41.a(gbj.a));
      $$0.put(gcb.cS, gbk.a());
      $$0.put(gcb.cT, $$28);
      $$0.put(gcb.cU, $$10);
      $$0.put(gcb.cV, gbn.a());
      $$0.put(gcb.cW, $$28);
      $$0.put(gcb.cX, gbo.a());
      $$0.put(gcb.cY, gbp.a().a($$9));
      $$0.put(gcb.cZ, gbq.a(gcg.a));
      $$0.put(gcb.da, gbq.a(c));
      $$0.put(gcb.df, gsd.a());
      gcl $$55 = gcl.scaling(1.2F);
      $$0.put(gcb.db, $$27.a($$55));
      $$0.put(gcb.dc, $$4.a($$55));
      $$0.put(gcb.dd, $$2.a($$55));
      $$0.put(gcb.de, $$6);
      $$0.put(gcb.dg, $$42);
      $$0.put(gcb.dh, $$43);
      $$0.put(gcb.di, $$42.a(gbr.a));
      $$0.put(gcb.dj, $$43.a(gbr.a));
      $$0.put(gcb.dk, $$25);
      $$0.put(gcb.dl, $$26);
      $$0.put(gcb.dm, $$1);
      $$0.put(gcb.dq, $$4);
      $$0.put(gcb.dr, $$2);
      $$0.put(gcb.ds, $$1.a(fzn.i));
      $$0.put(gcb.dt, $$4.a(fzn.i));
      $$0.put(gcb.du, $$2.a(fzn.i));
      $$0.put(gcb.dn, $$21);
      $$0.put(gcb.do, $$7);
      $$0.put(gcb.dp, $$8);
      $$0.put(gcb.dv, $$44);
      $$0.put(gcb.dw, gbt.a(c));
      $$0.put(gcb.dx, gbt.a(b));
      $$0.put(gcb.dy, $$44.a(fzn.i));
      $$0.put(gcb.dz, gbt.a(c).a(fzn.i));
      $$0.put(gcb.dA, gbt.a(b).a(fzn.i));
      $$0.put(gcb.dB, $$19);
      $$0.put(gcb.dC, $$4);
      $$0.put(gcb.dD, $$3);
      $$0.put(gcb.dE, $$19.a(fzn.i));
      $$0.put(gcb.dF, $$4.a(fzn.i));
      $$0.put(gcb.dG, $$3.a(fzn.i));
      gci $$56 = fyi.a();
      gci $$57 = fyi.b();
      gci $$58 = gam.a();
      gci $$59 = gam.b();

      for (cqq.b $$60 : cqq.b.values()) {
         if ($$60 == cqq.b.i) {
            $$0.put(gcb.a($$60), $$58);
            $$0.put(gcb.b($$60), $$59);
         } else {
            $$0.put(gcb.a($$60), $$56);
            $$0.put(gcb.b($$60), $$57);
         }
      }

      gci $$61 = glw.a(true);
      gci $$62 = glw.a(false);
      gci $$63 = gls.e();
      dxa.a().forEach($$4x -> {
         $$0.put(gcb.a($$4x), $$61);
         $$0.put(gcb.b($$4x), $$62);
         $$0.put(gcb.c($$4x), $$63);
      });
      ImmutableMap<gca, gci> $$64 = $$0.build();
      List<gca> $$65 = gcb.a().filter($$1x -> !$$64.containsKey($$1x)).collect(Collectors.toList());
      if (!$$65.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$65);
      } else {
         return $$64;
      }
   }
}
