import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gci {
   private static final gcp a = new gcp(0.008F);
   private static final gcp b = new gcp(1.0F);
   private static final gcp c = new gcp(0.5F);

   public static Map<gcj, gcr> a() {
      Builder<gcj, gcr> $$0 = ImmutableMap.builder();
      gcr $$1 = gcr.a(fzw.a(gcp.a, 0.0F), 64, 64);
      gcr $$2 = gcr.a(fzv.a(b), 64, 32);
      gcr $$3 = gcr.a(fzv.a(new gcp(1.02F)), 64, 32);
      gcr $$4 = gcr.a(fzv.a(c), 64, 32);
      gcr $$5 = gad.a();
      gcr $$6 = gbf.c();
      gcr $$7 = gcr.a(fya.a(gcp.a), 64, 64);
      gcr $$8 = gcr.a(fya.b(gcp.a), 64, 64);
      gcu $$9 = gcu.scaling(0.9375F);
      gcr $$10 = fzx.a().a($$9);
      gcr $$11 = fyk.a();
      gcr $$12 = fyn.a();
      gcr $$13 = fza.a();
      gcr $$14 = $$13.a(fza.a);
      gcr $$15 = fzf.a();
      gcr $$16 = gcr.a(gaf.a(gcp.a), 64, 32);
      gcr $$17 = $$16.a(fyw.a);
      gcr $$18 = gcr.a(gaf.a(new gcp(0.01F)), 64, 32).a(fyw.a);
      gcr $$19 = gcr.a(gal.a(gcp.a), 64, 64);
      gcr $$20 = gcr.a(gak.a(), 64, 64);
      gcr $$21 = gbf.b();
      gcr $$22 = gab.a(gcp.a);
      gcr $$23 = gab.a(new gcp(0.5F));
      gcr $$24 = gbn.a();
      gcr $$25 = fzt.a();
      gcr $$26 = fzt.b();
      gcr $$27 = gbe.c();
      gcr $$28 = gcr.a(gbv.a(), 64, 64).a($$9);
      gcr $$29 = gbk.a();
      gcr $$30 = fyf.a();
      gcr $$31 = fyv.a();
      gcr $$32 = fyy.a();
      gcr $$33 = fzq.a();
      gcr $$34 = gag.a();
      gcr $$35 = gaj.a(gcp.a);
      gcr $$36 = gaj.a(new gcp(0.5F));
      gcr $$37 = gap.a();
      gcr $$38 = gaz.a();
      gcr $$39 = gay.a();
      gcr $$40 = gbi.a();
      gcr $$41 = gbs.a();
      gcr $$42 = gcr.a(gca.a(gcp.a), 64, 32);
      gcr $$43 = gcr.a(gca.a(new gcp(0.2F)), 64, 32);
      gcr $$44 = gcc.a();
      gcr $$45 = fyi.a();
      gcr $$46 = fyh.a(c);
      gcr $$47 = fyh.a(b);
      gcr $$48 = fze.a(gcp.a);
      gcr $$49 = fze.a(new gcp(0.25F));
      gcr $$50 = gbm.a();
      gcr $$51 = fzc.a();
      gcr $$52 = gax.a();
      $$0.put(gck.c, fyd.a());
      $$0.put(gck.d, $$30);
      $$0.put(gck.e, $$30.a(fyf.a));
      $$0.put(gck.f, $$45);
      $$0.put(gck.g, $$46);
      $$0.put(gck.h, $$47);
      $$0.put(gck.i, $$45.a(fzw.i));
      $$0.put(gck.j, $$46.a(fzw.i));
      $$0.put(gck.k, $$47.a(fzw.i));
      $$0.put(gck.l, fyj.a());
      $$0.put(gck.m, $$11);
      $$0.put(gck.n, $$11.a(fyk.b));
      $$0.put(gck.q, glm.a());
      $$0.put(gck.r, fym.a());
      $$0.put(gck.s, glo.c());
      $$0.put(gck.t, glo.b());
      $$0.put(gck.u, $$12);
      $$0.put(gck.v, $$12.a(fyn.a));
      $$0.put(gck.w, fyo.a());
      $$0.put(gck.x, fyp.a());
      $$0.put(gck.A, fyq.a());
      $$0.put(gck.B, fyr.c());
      $$0.put(gck.C, fys.a());
      $$0.put(gck.D, $$4);
      $$0.put(gck.E, $$2);
      $$0.put(gck.F, gcr.a(fzw.a(new gcp(0.2F), 0.0F), 64, 32));
      $$0.put(gck.G, fyt.a());
      $$0.put(gck.H, fyu.a(32, 32));
      $$0.put(gck.I, fyu.a(128, 128));
      $$0.put(gck.L, $$17);
      $$0.put(gck.M, $$17.a(fyw.b));
      $$0.put(gck.O, $$18);
      $$0.put(gck.N, $$18.a(fyw.b));
      $$0.put(gck.J, $$31);
      $$0.put(gck.K, $$31.a(fyv.a));
      $$0.put(gck.P, $$29.a(gcu.scaling(0.7F)));
      $$0.put(gck.S, fyx.a());
      $$0.put(gck.T, $$5);
      $$0.put(gck.U, $$32);
      $$0.put(gck.V, $$32.a(fyy.b));
      $$0.put(gck.W, fyz.a());
      $$0.put(gck.X, $$5);
      $$0.put(gck.Z, gly.b());
      $$0.put(gck.ab, gly.c());
      $$0.put(gck.aa, gly.d());
      $$0.put(gck.Y, gly.e());
      $$0.put(gck.ac, $$13);
      $$0.put(gck.ad, $$14);
      $$0.put(gck.ae, fzb.a(gcp.a));
      $$0.put(gck.af, fzb.a(new gcp(2.0F)));
      $$0.put(gck.ag, $$6);
      $$0.put(gck.aj, glz.b());
      $$0.put(gck.ak, glz.c());
      $$0.put(gck.al, $$51);
      $$0.put(gck.am, $$51.a(fzc.a));
      $$0.put(gck.an, fzd.a());
      $$0.put(gck.ao, fzd.b());
      $$0.put(gck.ap, fyx.c());
      $$0.put(gck.aq, fyx.b());
      $$0.put(gck.ar, gce.a());
      $$0.put(gck.as, $$48);
      $$0.put(gck.ax, $$4);
      $$0.put(gck.ay, $$4);
      $$0.put(gck.az, $$49);
      $$0.put(gck.at, $$48.a(fzw.i));
      $$0.put(gck.au, $$4.a(fzw.i));
      $$0.put(gck.av, $$4.a(fzw.i));
      $$0.put(gck.aw, $$49.a(fzw.i));
      $$0.put(gck.aA, fzr.b());
      $$0.put(gck.aB, $$15);
      $$0.put(gck.aC, $$15.a(fzf.a));
      $$0.put(gck.aD, fzh.a());
      $$0.put(gck.aE, fzi.a());
      $$0.put(gck.aF, gcf.a());
      $$0.put(gck.aG, fzg.a());
      $$0.put(gck.aH, $$10);
      $$0.put(gck.aI, fzk.a());
      $$0.put(gck.aJ, fzm.a());
      $$0.put(gck.aK, fzm.a().a(fzm.a));
      $$0.put(gck.aL, fzn.a());
      $$0.put(gck.aM, $$5);
      $$0.put(gck.aN, fzo.a());
      gcu $$53 = gcu.scaling(6.0F);
      $$0.put(gck.aO, $$1.a($$53));
      $$0.put(gck.aP, $$4.a($$53));
      $$0.put(gck.aQ, $$2.a($$53));
      $$0.put(gck.aR, $$50);
      $$0.put(gck.aS, $$50.a(gbm.a));
      $$0.put(gck.aT, $$33);
      $$0.put(gck.aU, $$33.a(fzq.a));
      $$0.put(gck.aV, fzr.a());
      $$0.put(gck.aW, $$25);
      $$0.put(gck.aX, $$26);
      $$0.put(gck.aY, $$5);
      $$0.put(gck.aZ, $$7);
      $$0.put(gck.bb, $$8);
      $$0.put(gck.ba, gcr.a(fya.a(new gcp(0.1F)), 64, 64));
      $$0.put(gck.bc, gcr.a(fya.b(new gcp(0.1F)), 64, 64));
      gcu $$54 = gcu.scaling(1.0625F);
      $$0.put(gck.bd, $$1.a($$54));
      $$0.put(gck.bh, $$4.a($$54));
      $$0.put(gck.bi, $$2.a($$54));
      $$0.put(gck.be, $$1.a(fzw.i).a($$54));
      $$0.put(gck.bf, $$4.a(fzw.i).a($$54));
      $$0.put(gck.bg, $$2.a(fzw.i).a($$54));
      $$0.put(gck.bj, $$10);
      $$0.put(gck.bk, fzy.a());
      $$0.put(gck.bn, gaa.a());
      $$0.put(gck.bo, $$22);
      $$0.put(gck.bp, $$22.a(gab.a));
      $$0.put(gck.br, $$23);
      $$0.put(gck.bq, $$23.a(gab.a));
      $$0.put(gck.bs, gac.a());
      $$0.put(gck.bt, fzz.a());
      $$0.put(gck.bw, $$5);
      $$0.put(gck.bx, $$13);
      $$0.put(gck.by, $$14);
      $$0.put(gck.bz, fzd.a());
      $$0.put(gck.bA, fzd.b());
      $$0.put(gck.bD, $$16);
      $$0.put(gck.bE, $$16.a(gaf.b));
      $$0.put(gck.bF, $$34);
      $$0.put(gck.bG, $$34.a(gag.a));
      $$0.put(gck.bH, gah.a());
      $$0.put(gck.bI, gai.a());
      $$0.put(gck.bJ, $$35);
      $$0.put(gck.bU, $$35.a(gaj.a));
      $$0.put(gck.bW, $$36);
      $$0.put(gck.bV, $$36.a(gaj.a));
      $$0.put(gck.bK, $$19);
      $$0.put(gck.bS, $$4);
      $$0.put(gck.bT, $$3);
      $$0.put(gck.bO, $$19);
      $$0.put(gck.bP, $$4);
      $$0.put(gck.bQ, $$3);
      $$0.put(gck.bL, $$19.a(fzw.i));
      $$0.put(gck.bM, $$4.a(fzw.i));
      $$0.put(gck.bN, $$3.a(fzw.i));
      $$0.put(gck.bR, $$20);
      $$0.put(gck.bX, $$10);
      $$0.put(gck.bY, gcr.a(gao.a(gcp.a, false), 64, 64));
      $$0.put(gck.ca, gan.a());
      $$0.put(gck.bZ, gam.a());
      $$0.put(gck.cb, $$21);
      $$0.put(gck.cc, $$4);
      $$0.put(gck.cd, $$2);
      $$0.put(gck.ce, gcr.a(gao.a(gcp.a, true), 64, 64));
      $$0.put(gck.cf, $$4);
      $$0.put(gck.cg, $$2);
      $$0.put(gck.ch, gbl.a());
      $$0.put(gck.ci, $$37);
      $$0.put(gck.cj, $$37.a(gap.a));
      $$0.put(gck.ck, gaq.a());
      $$0.put(gck.cl, gar.a());
      $$0.put(gck.cm, gas.a());
      $$0.put(gck.cn, gau.a(false));
      $$0.put(gck.co, gau.a(true));
      $$0.put(gck.cp, gaw.a());
      $$0.put(gck.cq, $$52);
      $$0.put(gck.cs, $$52.a(gax.a));
      $$0.put(gck.cr, $$52.a(gax.b));
      $$0.put(gck.ct, $$38);
      $$0.put(gck.cu, $$38.a(gaz.a));
      $$0.put(gck.cw, $$39);
      $$0.put(gck.cv, $$39.a(gaz.a));
      $$0.put(gck.cx, gba.a());
      $$0.put(gck.cy, gbc.a());
      $$0.put(gck.cz, gbc.b());
      $$0.put(gck.cA, gbb.a());
      $$0.put(gck.cB, gbd.a());
      $$0.put(gck.cC, $$27);
      $$0.put(gck.cF, $$4);
      $$0.put(gck.cG, $$2);
      $$0.put(gck.cD, $$7);
      $$0.put(gck.cE, $$8);
      $$0.put(gck.cH, $$6);
      $$0.put(gck.cI, gbh.b());
      $$0.put(gck.cJ, gbh.a());
      $$0.put(gck.cK, $$40);
      $$0.put(gck.cL, $$40.a(gbi.a));
      $$0.put(gck.cM, gbj.a());
      $$0.put(gck.cN, $$5);
      $$0.put(gck.cO, $$29);
      $$0.put(gck.cR, $$50);
      $$0.put(gck.cS, $$50.a(gbm.a));
      $$0.put(gck.cT, $$27);
      $$0.put(gck.cU, $$4);
      $$0.put(gck.cV, $$2);
      $$0.put(gck.cW, gcr.a(fzw.a(new gcp(0.25F), 0.0F), 64, 32));
      $$0.put(gck.cX, $$24);
      $$0.put(gck.cY, $$24);
      $$0.put(gck.cZ, gbo.a());
      $$0.put(gck.da, $$5);
      $$0.put(gck.db, $$22);
      $$0.put(gck.dc, $$22.a(gab.a));
      $$0.put(gck.dd, gbp.a());
      $$0.put(gck.de, gbr.a(gcp.a));
      $$0.put(gck.df, gbr.a(a));
      $$0.put(gck.dg, gbq.a(gcp.a));
      $$0.put(gck.dh, gbq.a(a));
      $$0.put(gck.di, $$41);
      $$0.put(gck.dj, $$41.a(gbs.a));
      $$0.put(gck.dk, gbt.a());
      $$0.put(gck.dl, $$28);
      $$0.put(gck.dm, $$10);
      $$0.put(gck.do, gbw.a());
      $$0.put(gck.dn, $$28);
      $$0.put(gck.dp, gbx.a());
      $$0.put(gck.dq, gby.a().a($$9));
      $$0.put(gck.dr, gbz.a(gcp.a));
      $$0.put(gck.ds, gbz.a(c));
      $$0.put(gck.dx, gso.a());
      gcu $$55 = gcu.scaling(1.2F);
      $$0.put(gck.dt, $$27.a($$55));
      $$0.put(gck.du, $$4.a($$55));
      $$0.put(gck.dv, $$2.a($$55));
      $$0.put(gck.dw, $$6);
      $$0.put(gck.dy, $$42);
      $$0.put(gck.dz, $$43);
      $$0.put(gck.dA, $$42.a(gca.a));
      $$0.put(gck.dB, $$43.a(gca.a));
      $$0.put(gck.dC, $$25);
      $$0.put(gck.dD, $$26);
      $$0.put(gck.dE, $$1);
      $$0.put(gck.dL, $$4);
      $$0.put(gck.dM, $$2);
      $$0.put(gck.dF, $$1.a(fzw.i));
      $$0.put(gck.dG, $$4.a(fzw.i));
      $$0.put(gck.dH, $$2.a(fzw.i));
      $$0.put(gck.dI, $$21);
      $$0.put(gck.dJ, $$7);
      $$0.put(gck.dK, $$8);
      $$0.put(gck.dN, $$44);
      $$0.put(gck.dR, gcc.a(c));
      $$0.put(gck.dS, gcc.a(b));
      $$0.put(gck.dO, $$44.a(fzw.i));
      $$0.put(gck.dP, gcc.a(c).a(fzw.i));
      $$0.put(gck.dQ, gcc.a(b).a(fzw.i));
      $$0.put(gck.dT, $$19);
      $$0.put(gck.dX, $$4);
      $$0.put(gck.dY, $$3);
      $$0.put(gck.dU, $$19.a(fzw.i));
      $$0.put(gck.dV, $$4.a(fzw.i));
      $$0.put(gck.dW, $$3.a(fzw.i));
      $$0.put(gck.p, gav.a());
      $$0.put(gck.o, gav.b());
      gcr $$56 = fyr.a();
      gcr $$57 = fyr.b();
      $$0.put(gck.bB, $$56);
      $$0.put(gck.bC, $$57);
      $$0.put(gck.cP, $$56);
      $$0.put(gck.cQ, $$57);
      $$0.put(gck.y, $$56);
      $$0.put(gck.z, $$57);
      $$0.put(gck.bl, $$56);
      $$0.put(gck.bm, $$57);
      $$0.put(gck.a, $$56);
      $$0.put(gck.b, $$57);
      $$0.put(gck.Q, $$56);
      $$0.put(gck.R, $$57);
      $$0.put(gck.ah, $$56);
      $$0.put(gck.ai, $$57);
      $$0.put(gck.bu, $$56);
      $$0.put(gck.bv, $$57);
      gcr $$58 = gmf.a(true);
      gcr $$59 = gmf.a(false);
      gcr $$60 = gmb.e();
      dxh.a().forEach($$4x -> {
         $$0.put(gck.a($$4x), $$58);
         $$0.put(gck.b($$4x), $$59);
         $$0.put(gck.c($$4x), $$60);
      });
      ImmutableMap<gcj, gcr> $$61 = $$0.build();
      List<gcj> $$62 = gck.a().filter($$1x -> !$$61.containsKey($$1x)).collect(Collectors.toList());
      if (!$$62.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$62);
      } else {
         return $$61;
      }
   }
}
