import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gek {
   private static final ger a = new ger(0.008F);
   private static final ger b = new ger(1.0F);
   private static final ger c = new ger(0.5F);

   public static Map<gel, get> a() {
      Builder<gel, get> $$0 = ImmutableMap.builder();
      get $$1 = get.a(gby.a(ger.a, 0.0F), 64, 64);
      get $$2 = get.a(gbx.a(b), 64, 32);
      get $$3 = get.a(gbx.a(new ger(1.02F)), 64, 32);
      get $$4 = get.a(gbx.a(c), 64, 32);
      get $$5 = gcf.a();
      get $$6 = gdh.c();
      get $$7 = get.a(gab.a(ger.a), 64, 64);
      get $$8 = get.a(gab.b(ger.a), 64, 64);
      gew $$9 = gew.scaling(0.9375F);
      get $$10 = gbz.a().a($$9);
      get $$11 = gal.a();
      get $$12 = gao.a();
      get $$13 = gbb.a();
      get $$14 = $$13.a(gbb.a);
      get $$15 = gbh.a();
      get $$16 = get.a(gch.a(ger.a), 64, 32);
      get $$17 = $$16.a(gax.a);
      get $$18 = get.a(gch.a(new ger(0.01F)), 64, 32).a(gax.a);
      get $$19 = get.a(gcn.a(ger.a), 64, 64);
      get $$20 = get.a(gcm.a(), 64, 64);
      get $$21 = gdh.b();
      get $$22 = gcd.a(ger.a);
      get $$23 = gcd.a(new ger(0.5F));
      get $$24 = gdp.a();
      get $$25 = gbv.a();
      get $$26 = gbv.b();
      get $$27 = gdg.c();
      get $$28 = get.a(gdx.a(), 64, 64).a($$9);
      get $$29 = gdm.a();
      get $$30 = gag.a();
      get $$31 = gaw.a();
      get $$32 = gaz.a();
      get $$33 = gbs.a();
      get $$34 = gci.a();
      get $$35 = gcl.a(ger.a);
      get $$36 = gcl.a(new ger(0.5F));
      get $$37 = gcr.a();
      get $$38 = gdb.a();
      get $$39 = gda.a();
      get $$40 = gdk.a();
      get $$41 = gdu.a();
      get $$42 = get.a(gec.a(ger.a), 64, 32);
      get $$43 = get.a(gec.a(new ger(0.2F)), 64, 32);
      get $$44 = gee.a();
      get $$45 = gaj.a();
      get $$46 = gai.a(c);
      get $$47 = gai.a(b);
      get $$48 = gbg.a(ger.a);
      get $$49 = gbg.a(new ger(0.25F));
      get $$50 = gdo.a();
      get $$51 = gbe.a();
      get $$52 = gcz.a();
      $$0.put(gem.c, gae.a());
      $$0.put(gem.d, $$30);
      $$0.put(gem.e, $$30.a(gag.a));
      $$0.put(gem.f, $$45);
      $$0.put(gem.g, $$46);
      $$0.put(gem.h, $$47);
      $$0.put(gem.i, $$45.a(gby.i));
      $$0.put(gem.j, $$46.a(gby.i));
      $$0.put(gem.k, $$47.a(gby.i));
      $$0.put(gem.l, gak.a());
      $$0.put(gem.m, $$11);
      $$0.put(gem.n, $$11.a(gal.b));
      $$0.put(gem.q, gnq.a());
      $$0.put(gem.r, gan.a());
      $$0.put(gem.s, gns.c());
      $$0.put(gem.t, gns.b());
      $$0.put(gem.u, $$12);
      $$0.put(gem.v, $$12.a(gao.a));
      $$0.put(gem.w, gap.a());
      $$0.put(gem.x, gaq.a());
      $$0.put(gem.A, gar.a());
      $$0.put(gem.B, gas.c());
      $$0.put(gem.C, gat.a());
      $$0.put(gem.D, $$4);
      $$0.put(gem.E, $$2);
      $$0.put(gem.F, get.a(gby.a(new ger(0.2F), 0.0F), 64, 32));
      $$0.put(gem.G, gau.a());
      $$0.put(gem.H, gav.a(32, 32));
      $$0.put(gem.I, gav.a(128, 128));
      $$0.put(gem.L, $$17);
      $$0.put(gem.M, $$17.a(gax.b));
      $$0.put(gem.O, $$18);
      $$0.put(gem.N, $$18.a(gax.b));
      $$0.put(gem.J, $$31);
      $$0.put(gem.K, $$31.a(gaw.a));
      $$0.put(gem.P, $$29.a(gew.scaling(0.7F)));
      $$0.put(gem.S, gay.a());
      $$0.put(gem.T, $$5);
      $$0.put(gem.U, $$32);
      $$0.put(gem.V, $$32.a(gaz.b));
      $$0.put(gem.W, gba.a());
      $$0.put(gem.X, $$5);
      $$0.put(gem.Z, goc.b());
      $$0.put(gem.ab, goc.c());
      $$0.put(gem.aa, goc.d());
      $$0.put(gem.Y, goc.e());
      $$0.put(gem.ac, $$13);
      $$0.put(gem.ad, $$14);
      $$0.put(gem.ae, gbc.a());
      $$0.put(gem.af, gbd.a(ger.a));
      $$0.put(gem.ag, gbd.a(new ger(2.0F)));
      $$0.put(gem.ah, $$6);
      $$0.put(gem.ak, god.b());
      $$0.put(gem.al, god.c());
      $$0.put(gem.am, $$51);
      $$0.put(gem.an, $$51.a(gbe.a));
      $$0.put(gem.ao, gbf.a());
      $$0.put(gem.ap, gbf.b());
      $$0.put(gem.aq, gay.c());
      $$0.put(gem.ar, gay.b());
      $$0.put(gem.as, geg.a());
      $$0.put(gem.at, $$48);
      $$0.put(gem.ay, $$4);
      $$0.put(gem.az, $$4);
      $$0.put(gem.aA, $$49);
      $$0.put(gem.au, $$48.a(gby.i));
      $$0.put(gem.av, $$4.a(gby.i));
      $$0.put(gem.aw, $$4.a(gby.i));
      $$0.put(gem.ax, $$49.a(gby.i));
      $$0.put(gem.aB, gbt.b());
      $$0.put(gem.aC, $$15);
      $$0.put(gem.aD, $$15.a(gbh.a));
      $$0.put(gem.aE, gbj.a());
      $$0.put(gem.aF, gbk.a());
      $$0.put(gem.aG, geh.a());
      $$0.put(gem.aH, gbi.a());
      $$0.put(gem.aI, $$10);
      $$0.put(gem.aJ, gbm.a());
      $$0.put(gem.aK, gbo.a());
      $$0.put(gem.aL, gbo.a().a(gbo.a));
      $$0.put(gem.aM, gbp.a());
      $$0.put(gem.aN, $$5);
      $$0.put(gem.aO, gbq.a());
      gew $$53 = gew.scaling(6.0F);
      $$0.put(gem.aP, $$1.a($$53));
      $$0.put(gem.aQ, $$4.a($$53));
      $$0.put(gem.aR, $$2.a($$53));
      $$0.put(gem.aS, $$50);
      $$0.put(gem.aT, $$50.a(gdo.a));
      $$0.put(gem.aU, $$33);
      $$0.put(gem.aV, $$33.a(gbs.a));
      $$0.put(gem.aW, gbt.a());
      $$0.put(gem.aX, $$25);
      $$0.put(gem.aY, $$26);
      $$0.put(gem.aZ, $$5);
      $$0.put(gem.ba, $$7);
      $$0.put(gem.bc, $$8);
      $$0.put(gem.bb, get.a(gab.a(new ger(0.1F)), 64, 64));
      $$0.put(gem.bd, get.a(gab.b(new ger(0.1F)), 64, 64));
      gew $$54 = gew.scaling(1.0625F);
      $$0.put(gem.be, $$1.a($$54));
      $$0.put(gem.bi, $$4.a($$54));
      $$0.put(gem.bj, $$2.a($$54));
      $$0.put(gem.bf, $$1.a(gby.i).a($$54));
      $$0.put(gem.bg, $$4.a(gby.i).a($$54));
      $$0.put(gem.bh, $$2.a(gby.i).a($$54));
      $$0.put(gem.bk, $$10);
      $$0.put(gem.bl, gca.a());
      $$0.put(gem.bo, gcc.a());
      $$0.put(gem.bp, $$22);
      $$0.put(gem.bq, $$22.a(gcd.a));
      $$0.put(gem.bs, $$23);
      $$0.put(gem.br, $$23.a(gcd.a));
      $$0.put(gem.bt, gce.a());
      $$0.put(gem.bu, gcb.a());
      $$0.put(gem.bx, $$5);
      $$0.put(gem.by, $$13);
      $$0.put(gem.bz, $$14);
      $$0.put(gem.bA, gbf.a());
      $$0.put(gem.bB, gbf.b());
      $$0.put(gem.bE, $$16);
      $$0.put(gem.bF, $$16.a(gch.b));
      $$0.put(gem.bI, $$34);
      $$0.put(gem.bJ, $$34.a(gci.a));
      $$0.put(gem.bK, gcj.a());
      $$0.put(gem.bL, gck.a());
      $$0.put(gem.bM, $$35);
      $$0.put(gem.bX, $$35.a(gcl.a));
      $$0.put(gem.bZ, $$36);
      $$0.put(gem.bY, $$36.a(gcl.a));
      $$0.put(gem.bN, $$19);
      $$0.put(gem.bV, $$4);
      $$0.put(gem.bW, $$3);
      $$0.put(gem.bR, $$19);
      $$0.put(gem.bS, $$4);
      $$0.put(gem.bT, $$3);
      $$0.put(gem.bO, $$19.a(gby.i));
      $$0.put(gem.bP, $$4.a(gby.i));
      $$0.put(gem.bQ, $$3.a(gby.i));
      $$0.put(gem.bU, $$20);
      $$0.put(gem.ca, $$10);
      $$0.put(gem.cb, get.a(gcq.a(ger.a, false), 64, 64));
      $$0.put(gem.cd, gcp.a());
      $$0.put(gem.cc, gco.a());
      $$0.put(gem.ce, $$21);
      $$0.put(gem.cf, $$4);
      $$0.put(gem.cg, $$2);
      $$0.put(gem.ch, get.a(gcq.a(ger.a, true), 64, 64));
      $$0.put(gem.ci, $$4);
      $$0.put(gem.cj, $$2);
      $$0.put(gem.ck, gdn.a());
      $$0.put(gem.cl, $$37);
      $$0.put(gem.cm, $$37.a(gcr.a));
      $$0.put(gem.cn, gcs.a());
      $$0.put(gem.co, gct.a());
      $$0.put(gem.cp, gcu.a());
      $$0.put(gem.cq, gcw.a(false));
      $$0.put(gem.cr, gcw.a(true));
      $$0.put(gem.cs, gcy.a());
      $$0.put(gem.ct, $$52);
      $$0.put(gem.cv, $$52.a(gcz.a));
      $$0.put(gem.cu, $$52.a(gcz.b));
      $$0.put(gem.cw, $$38);
      $$0.put(gem.cx, $$38.a(gdb.a));
      $$0.put(gem.cz, $$39);
      $$0.put(gem.cy, $$39.a(gdb.a));
      $$0.put(gem.cA, gdc.a());
      $$0.put(gem.cB, gde.a());
      $$0.put(gem.cC, gde.b());
      $$0.put(gem.cD, gdd.a());
      $$0.put(gem.cE, gdf.a());
      $$0.put(gem.cF, $$27);
      $$0.put(gem.cI, $$4);
      $$0.put(gem.cJ, $$2);
      $$0.put(gem.cG, $$7);
      $$0.put(gem.cH, $$8);
      $$0.put(gem.cK, $$6);
      $$0.put(gem.cL, gdj.b());
      $$0.put(gem.cM, gdj.a());
      $$0.put(gem.cN, $$40);
      $$0.put(gem.cO, $$40.a(gdk.a));
      $$0.put(gem.cP, gdl.a());
      $$0.put(gem.cQ, $$5);
      $$0.put(gem.cR, $$29);
      $$0.put(gem.cU, $$50);
      $$0.put(gem.cV, $$50.a(gdo.a));
      $$0.put(gem.cW, $$27);
      $$0.put(gem.cX, $$4);
      $$0.put(gem.cY, $$2);
      $$0.put(gem.cZ, get.a(gby.a(new ger(0.25F), 0.0F), 64, 32));
      $$0.put(gem.da, $$24);
      $$0.put(gem.db, $$24);
      $$0.put(gem.dc, gdq.a());
      $$0.put(gem.dd, $$5);
      $$0.put(gem.de, $$22);
      $$0.put(gem.df, $$22.a(gcd.a));
      $$0.put(gem.dg, gdr.a());
      $$0.put(gem.dh, gdt.a(ger.a));
      $$0.put(gem.di, gdt.a(a));
      $$0.put(gem.dj, gds.a(ger.a));
      $$0.put(gem.dk, gds.a(a));
      $$0.put(gem.dl, $$41);
      $$0.put(gem.dm, $$41.a(gdu.a));
      $$0.put(gem.dn, gdv.a());
      $$0.put(gem.do, $$28);
      $$0.put(gem.dp, $$10);
      $$0.put(gem.dr, gdy.a());
      $$0.put(gem.dq, $$28);
      $$0.put(gem.ds, gdz.a());
      $$0.put(gem.dt, gea.a().a($$9));
      $$0.put(gem.du, geb.a(ger.a));
      $$0.put(gem.dv, geb.a(c));
      $$0.put(gem.dA, gut.a());
      gew $$55 = gew.scaling(1.2F);
      $$0.put(gem.dw, $$27.a($$55));
      $$0.put(gem.dx, $$4.a($$55));
      $$0.put(gem.dy, $$2.a($$55));
      $$0.put(gem.dz, $$6);
      $$0.put(gem.dB, $$42);
      $$0.put(gem.dC, $$43);
      $$0.put(gem.dD, $$42.a(gec.a));
      $$0.put(gem.dE, $$43.a(gec.a));
      $$0.put(gem.dF, $$25);
      $$0.put(gem.dG, $$26);
      $$0.put(gem.dH, $$1);
      $$0.put(gem.dO, $$4);
      $$0.put(gem.dP, $$2);
      $$0.put(gem.dI, $$1.a(gby.i));
      $$0.put(gem.dJ, $$4.a(gby.i));
      $$0.put(gem.dK, $$2.a(gby.i));
      $$0.put(gem.dL, $$21);
      $$0.put(gem.dM, $$7);
      $$0.put(gem.dN, $$8);
      $$0.put(gem.dQ, $$44);
      $$0.put(gem.dU, gee.a(c));
      $$0.put(gem.dV, gee.a(b));
      $$0.put(gem.dR, $$44.a(gby.i));
      $$0.put(gem.dS, gee.a(c).a(gby.i));
      $$0.put(gem.dT, gee.a(b).a(gby.i));
      $$0.put(gem.dW, $$19);
      $$0.put(gem.ea, $$4);
      $$0.put(gem.eb, $$3);
      $$0.put(gem.dX, $$19.a(gby.i));
      $$0.put(gem.dY, $$4.a(gby.i));
      $$0.put(gem.dZ, $$3.a(gby.i));
      $$0.put(gem.p, gcx.a());
      $$0.put(gem.o, gcx.b());
      get $$56 = gas.a();
      get $$57 = gas.b();
      $$0.put(gem.bC, $$56);
      $$0.put(gem.bD, $$57);
      $$0.put(gem.cS, $$56);
      $$0.put(gem.cT, $$57);
      $$0.put(gem.y, $$56);
      $$0.put(gem.z, $$57);
      $$0.put(gem.bm, $$56);
      $$0.put(gem.bn, $$57);
      $$0.put(gem.a, $$56);
      $$0.put(gem.b, $$57);
      $$0.put(gem.Q, $$56);
      $$0.put(gem.R, $$57);
      $$0.put(gem.ai, $$56);
      $$0.put(gem.aj, $$57);
      $$0.put(gem.bG, $$56);
      $$0.put(gem.bH, $$57);
      $$0.put(gem.bv, $$56);
      $$0.put(gem.bw, $$57);
      get $$58 = goj.a(true);
      get $$59 = goj.a(false);
      get $$60 = gof.e();
      dzg.a().forEach($$4x -> {
         $$0.put(gem.a($$4x), $$58);
         $$0.put(gem.b($$4x), $$59);
         $$0.put(gem.c($$4x), $$60);
      });
      ImmutableMap<gel, get> $$61 = $$0.build();
      List<gel> $$62 = gem.a().filter($$1x -> !$$61.containsKey($$1x)).collect(Collectors.toList());
      if (!$$62.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$62);
      } else {
         return $$61;
      }
   }
}
