import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gex {
   private static final gfe a = new gfe(0.008F);
   private static final gfe b = new gfe(1.0F);
   private static final gfe c = new gfe(0.5F);

   public static Map<gey, gfg> a() {
      Builder<gey, gfg> $$0 = ImmutableMap.builder();
      gfg $$1 = gfg.a(gcl.a(gfe.a, 0.0F), 64, 64);
      gfg $$2 = gfg.a(gck.a(b), 64, 32);
      gfg $$3 = gfg.a(gck.a(new gfe(1.02F)), 64, 32);
      gfg $$4 = gfg.a(gck.a(c), 64, 32);
      gfg $$5 = gcs.a();
      gfg $$6 = gdu.c();
      gfg $$7 = gfg.a(gam.a(gfe.a), 64, 64);
      gfg $$8 = gfg.a(gam.b(gfe.a), 64, 64);
      gfj $$9 = gfj.scaling(0.9375F);
      gfg $$10 = gcm.a().a($$9);
      gfg $$11 = gaw.a();
      gfg $$12 = gbb.a();
      gfg $$13 = gbo.a();
      gfg $$14 = $$13.a(gbo.a);
      gfg $$15 = gbu.a();
      gfg $$16 = gfg.a(gca.a(gfe.a), 64, 32);
      gfg $$17 = $$16.a(gca.b);
      gfg $$18 = gfg.a(gca.a(new gfe(0.01F)), 64, 32);
      gfg $$19 = gfg.a(gda.a(gfe.a), 64, 64);
      gfg $$20 = gfg.a(gcz.a(), 64, 64);
      gfg $$21 = gdu.b();
      gfg $$22 = gcq.a(gfe.a);
      gfg $$23 = gcq.a(new gfe(0.5F));
      gfg $$24 = gec.a();
      gfg $$25 = gci.a();
      gfg $$26 = gci.b();
      gfg $$27 = gdt.c();
      gfg $$28 = gfg.a(gek.a(), 64, 64).a($$9);
      gfg $$29 = gdz.a();
      gfg $$30 = gar.a();
      gfg $$31 = gbj.a();
      gfg $$32 = gbm.a();
      gfg $$33 = gcf.a();
      gfg $$34 = gcv.a();
      gfg $$35 = gcy.a(gfe.a);
      gfg $$36 = gcy.a(new gfe(0.5F));
      gfg $$37 = gde.a();
      gfg $$38 = gdo.a();
      gfg $$39 = gdn.a();
      gfg $$40 = gdx.a();
      gfg $$41 = geh.a();
      gfg $$42 = gfg.a(gep.a(gfe.a), 64, 32);
      gfg $$43 = gfg.a(gep.a(new gfe(0.2F)), 64, 32);
      gfg $$44 = ger.a();
      gfg $$45 = gau.a();
      gfg $$46 = gat.a(c);
      gfg $$47 = gat.a(b);
      gfg $$48 = gbt.a(gfe.a);
      gfg $$49 = gbt.a(new gfe(0.25F));
      gfg $$50 = geb.a();
      gfg $$51 = gbr.a();
      gfg $$52 = gdm.a();
      $$0.put(gez.c, gap.a());
      $$0.put(gez.d, $$30);
      $$0.put(gez.e, $$30.a(gar.a));
      $$0.put(gez.f, $$45);
      $$0.put(gez.g, $$46);
      $$0.put(gez.h, $$47);
      $$0.put(gez.i, $$45.a(gcl.i));
      $$0.put(gez.j, $$46.a(gcl.i));
      $$0.put(gez.k, $$47.a(gcl.i));
      $$0.put(gez.l, gav.a());
      $$0.put(gez.m, $$11);
      $$0.put(gez.n, $$11.a(gaw.b));
      $$0.put(gez.q, gaz.a(true));
      $$0.put(gez.s, gaz.a(false));
      $$0.put(gez.r, gay.a(true));
      $$0.put(gez.t, gay.a(false));
      $$0.put(gez.u, gba.a());
      $$0.put(gez.v, goe.c());
      $$0.put(gez.w, goe.b());
      $$0.put(gez.x, $$12);
      $$0.put(gez.y, $$12.a(gbb.a));
      $$0.put(gez.z, gbc.a());
      $$0.put(gez.A, gbd.a());
      $$0.put(gez.D, gbe.a());
      $$0.put(gez.E, gbf.c());
      $$0.put(gez.F, gbg.a());
      $$0.put(gez.G, $$4);
      $$0.put(gez.H, $$2);
      $$0.put(gez.I, gfg.a(gcl.a(new gfe(0.2F), 0.0F), 64, 32));
      $$0.put(gez.J, gbh.a());
      $$0.put(gez.K, gbi.a(32, 32));
      $$0.put(gez.L, gbi.a(128, 128));
      $$0.put(gez.O, $$16.a(gbk.a));
      $$0.put(gez.P, $$17.a(gbk.a));
      $$0.put(gez.R, $$18.a(gbk.a));
      $$0.put(gez.Q, $$18.a(gca.b).a(gbk.a));
      $$0.put(gez.M, $$31);
      $$0.put(gez.N, $$31.a(gbj.a));
      $$0.put(gez.S, $$29.a(gfj.scaling(0.7F)));
      $$0.put(gez.V, gbl.a());
      $$0.put(gez.W, $$5);
      $$0.put(gez.X, $$32);
      $$0.put(gez.Y, $$32.a(gbm.b));
      $$0.put(gez.Z, gbn.a());
      $$0.put(gez.aa, $$5);
      $$0.put(gez.ac, goo.b());
      $$0.put(gez.ae, goo.c());
      $$0.put(gez.ad, goo.d());
      $$0.put(gez.ab, goo.e());
      $$0.put(gez.af, $$13);
      $$0.put(gez.ag, $$14);
      $$0.put(gez.ah, gbp.a());
      $$0.put(gez.ai, gbq.a(gfe.a));
      $$0.put(gez.aj, gbq.a(new gfe(2.0F)));
      $$0.put(gez.ak, $$6);
      $$0.put(gez.an, gop.b());
      $$0.put(gez.ao, gop.c());
      $$0.put(gez.ap, $$51);
      $$0.put(gez.aq, $$51.a(gbr.a));
      $$0.put(gez.ar, gbs.a(0.87F));
      $$0.put(gez.as, gbs.b(0.87F));
      $$0.put(gez.at, gbl.c());
      $$0.put(gez.au, gbl.b());
      $$0.put(gez.av, get.a());
      $$0.put(gez.aw, $$48);
      $$0.put(gez.aB, $$4);
      $$0.put(gez.aC, $$4);
      $$0.put(gez.aD, $$49);
      $$0.put(gez.ax, $$48.a(gcl.i));
      $$0.put(gez.ay, $$4.a(gcl.i));
      $$0.put(gez.az, $$4.a(gcl.i));
      $$0.put(gez.aA, $$49.a(gcl.i));
      $$0.put(gez.aE, gcg.b());
      $$0.put(gez.aF, $$15);
      $$0.put(gez.aG, $$15.a(gbu.a));
      $$0.put(gez.aH, gbw.a());
      $$0.put(gez.aI, gbx.a());
      $$0.put(gez.aJ, geu.a());
      $$0.put(gez.aK, gbv.a());
      $$0.put(gez.aL, $$10);
      $$0.put(gez.aM, gbz.a());
      $$0.put(gez.aN, gcb.a());
      $$0.put(gez.aO, gcb.a().a(gcb.a));
      $$0.put(gez.aP, gcc.a());
      $$0.put(gez.aQ, $$5);
      $$0.put(gez.aR, gcd.a());
      gfj $$53 = gfj.scaling(6.0F);
      $$0.put(gez.aS, $$1.a($$53));
      $$0.put(gez.aT, $$4.a($$53));
      $$0.put(gez.aU, $$2.a($$53));
      $$0.put(gez.aV, $$50);
      $$0.put(gez.aW, $$50.a(geb.a));
      $$0.put(gez.aX, $$33);
      $$0.put(gez.aY, $$33.a(gcf.a));
      $$0.put(gez.aZ, gcg.a());
      $$0.put(gez.ba, $$25);
      $$0.put(gez.bb, $$26);
      $$0.put(gez.bc, $$5);
      gfj $$54 = gfj.scaling(1.1F);
      $$0.put(gez.bd, $$7.a($$54));
      $$0.put(gez.bf, $$8.a($$54));
      $$0.put(gez.be, gfg.a(gam.a(new gfe(0.1F)), 64, 64).a($$54));
      $$0.put(gez.bg, gfg.a(gam.b(new gfe(0.1F)), 64, 64).a($$54));
      gfj $$55 = gfj.scaling(1.0625F);
      $$0.put(gez.bh, $$1.a($$55));
      $$0.put(gez.bl, $$4.a($$55));
      $$0.put(gez.bm, $$2.a($$55));
      $$0.put(gez.bi, $$1.a(gcl.i).a($$55));
      $$0.put(gez.bj, $$4.a(gcl.i).a($$55));
      $$0.put(gez.bk, $$2.a(gcl.i).a($$55));
      $$0.put(gez.bn, $$10);
      $$0.put(gez.bo, gcn.a());
      $$0.put(gez.br, gcp.a());
      $$0.put(gez.bs, $$22);
      $$0.put(gez.bt, $$22.a(gcq.a));
      $$0.put(gez.bv, $$23);
      $$0.put(gez.bu, $$23.a(gcq.a));
      $$0.put(gez.bw, gcr.a());
      $$0.put(gez.bx, gco.a());
      $$0.put(gez.bA, $$5);
      $$0.put(gez.bB, $$13);
      $$0.put(gez.bC, $$14);
      $$0.put(gez.bD, gbs.a(0.92F));
      $$0.put(gez.bE, gbs.b(0.92F));
      $$0.put(gez.bH, $$16);
      $$0.put(gez.bI, $$17);
      $$0.put(gez.bL, $$34);
      $$0.put(gez.bM, $$34.a(gcv.a));
      $$0.put(gez.bN, gcw.a());
      $$0.put(gez.bO, gcx.a());
      $$0.put(gez.bP, $$35);
      $$0.put(gez.ca, $$35.a(gcy.a));
      $$0.put(gez.cc, $$36);
      $$0.put(gez.cb, $$36.a(gcy.a));
      $$0.put(gez.bQ, $$19);
      $$0.put(gez.bY, $$4);
      $$0.put(gez.bZ, $$3);
      $$0.put(gez.bU, $$19);
      $$0.put(gez.bV, $$4);
      $$0.put(gez.bW, $$3);
      $$0.put(gez.bR, $$19.a(gcl.i));
      $$0.put(gez.bS, $$4.a(gcl.i));
      $$0.put(gez.bT, $$3.a(gcl.i));
      $$0.put(gez.bX, $$20);
      $$0.put(gez.cd, $$10);
      $$0.put(gez.ce, gfg.a(gdd.a(gfe.a, false), 64, 64));
      $$0.put(gez.cg, gdc.a());
      $$0.put(gez.cf, gdb.a());
      $$0.put(gez.ch, $$21);
      $$0.put(gez.ci, $$4);
      $$0.put(gez.cj, $$2);
      $$0.put(gez.ck, gfg.a(gdd.a(gfe.a, true), 64, 64));
      $$0.put(gez.cl, $$4);
      $$0.put(gez.cm, $$2);
      $$0.put(gez.cn, gea.a());
      $$0.put(gez.co, $$37);
      $$0.put(gez.cp, $$37.a(gde.a));
      $$0.put(gez.cq, gdf.a());
      $$0.put(gez.cr, gdg.a());
      $$0.put(gez.cs, gdh.a());
      $$0.put(gez.ct, gdj.a(false));
      $$0.put(gez.cu, gdj.a(true));
      $$0.put(gez.cv, gdl.a());
      $$0.put(gez.cw, $$52);
      $$0.put(gez.cy, $$52.a(gdm.a));
      $$0.put(gez.cx, $$52.a(gdm.b));
      $$0.put(gez.cz, $$38);
      $$0.put(gez.cA, $$38.a(gdo.a));
      $$0.put(gez.cC, $$39);
      $$0.put(gez.cB, $$39.a(gdo.a));
      $$0.put(gez.cD, gdp.a());
      $$0.put(gez.cE, gdr.a());
      $$0.put(gez.cF, gdr.b());
      $$0.put(gez.cG, gdq.a());
      $$0.put(gez.cH, gds.a());
      $$0.put(gez.cI, $$27);
      $$0.put(gez.cL, $$4);
      $$0.put(gez.cM, $$2);
      $$0.put(gez.cJ, $$7);
      $$0.put(gez.cK, $$8);
      $$0.put(gez.cN, $$6);
      $$0.put(gez.cO, gdw.b());
      $$0.put(gez.cP, gdw.a());
      $$0.put(gez.cQ, $$40);
      $$0.put(gez.cR, $$40.a(gdx.a));
      $$0.put(gez.cS, gdy.a());
      $$0.put(gez.cT, $$5);
      $$0.put(gez.cU, $$29);
      $$0.put(gez.cX, $$50);
      $$0.put(gez.cY, $$50.a(geb.a));
      $$0.put(gez.cZ, $$27);
      $$0.put(gez.da, $$4);
      $$0.put(gez.db, $$2);
      $$0.put(gez.dc, gfg.a(gcl.a(new gfe(0.25F), 0.0F), 64, 32));
      $$0.put(gez.dd, $$24);
      $$0.put(gez.de, $$24);
      $$0.put(gez.df, $$24.a(gec.a));
      $$0.put(gez.dg, $$24.a(gec.a));
      $$0.put(gez.dh, ged.a());
      $$0.put(gez.di, $$5);
      $$0.put(gez.dj, $$22);
      $$0.put(gez.dk, $$22.a(gcq.a));
      $$0.put(gez.dl, gee.a());
      $$0.put(gez.dm, geg.a(gfe.a));
      $$0.put(gez.dn, geg.a(a));
      $$0.put(gez.do, gef.a(gfe.a));
      $$0.put(gez.dp, gef.a(a));
      $$0.put(gez.dq, $$41);
      $$0.put(gez.dr, $$41.a(geh.a));
      $$0.put(gez.ds, gei.a());
      $$0.put(gez.dt, $$28);
      $$0.put(gez.du, $$28.a(gek.a));
      $$0.put(gez.dv, $$10);
      $$0.put(gez.dx, gel.a());
      $$0.put(gez.dw, $$28);
      $$0.put(gez.dy, gem.a());
      $$0.put(gez.dz, gen.a().a($$9));
      $$0.put(gez.dA, geo.a(gfe.a));
      $$0.put(gez.dB, geo.a(c));
      $$0.put(gez.dG, gvf.a());
      gfj $$56 = gfj.scaling(1.2F);
      $$0.put(gez.dC, $$27.a($$56));
      $$0.put(gez.dD, $$4.a($$56));
      $$0.put(gez.dE, $$2.a($$56));
      $$0.put(gez.dF, $$6);
      $$0.put(gez.dH, $$42);
      $$0.put(gez.dI, $$43);
      $$0.put(gez.dJ, $$42.a(gep.a));
      $$0.put(gez.dK, $$43.a(gep.a));
      $$0.put(gez.dL, $$25);
      $$0.put(gez.dM, $$26);
      $$0.put(gez.dN, $$1);
      $$0.put(gez.dU, $$4);
      $$0.put(gez.dV, $$2);
      $$0.put(gez.dO, $$1.a(gcl.i));
      $$0.put(gez.dP, $$4.a(gcl.i));
      $$0.put(gez.dQ, $$2.a(gcl.i));
      $$0.put(gez.dR, $$21);
      $$0.put(gez.dS, $$7);
      $$0.put(gez.dT, $$8);
      $$0.put(gez.dW, $$44);
      $$0.put(gez.ea, ger.a(c));
      $$0.put(gez.eb, ger.a(b));
      $$0.put(gez.dX, $$44.a(gcl.i));
      $$0.put(gez.dY, ger.a(c).a(gcl.i));
      $$0.put(gez.dZ, ger.a(b).a(gcl.i));
      $$0.put(gez.ec, $$19);
      $$0.put(gez.eg, $$4);
      $$0.put(gez.eh, $$3);
      $$0.put(gez.ed, $$19.a(gcl.i));
      $$0.put(gez.ee, $$4.a(gcl.i));
      $$0.put(gez.ef, $$3.a(gcl.i));
      $$0.put(gez.p, gdk.a());
      $$0.put(gez.o, gdk.b());
      gfg $$57 = gbf.a();
      gfg $$58 = gbf.b();
      $$0.put(gez.bF, $$57);
      $$0.put(gez.bG, $$58);
      $$0.put(gez.cV, $$57);
      $$0.put(gez.cW, $$58);
      $$0.put(gez.B, $$57);
      $$0.put(gez.C, $$58);
      $$0.put(gez.bp, $$57);
      $$0.put(gez.bq, $$58);
      $$0.put(gez.a, $$57);
      $$0.put(gez.b, $$58);
      $$0.put(gez.T, $$57);
      $$0.put(gez.U, $$58);
      $$0.put(gez.al, $$57);
      $$0.put(gez.am, $$58);
      $$0.put(gez.bJ, $$57);
      $$0.put(gez.bK, $$58);
      $$0.put(gez.by, $$57);
      $$0.put(gez.bz, $$58);
      gfg $$59 = gov.a(true);
      gfg $$60 = gov.a(false);
      dyh.a().forEach($$3x -> {
         $$0.put(gez.a($$3x), $$59);
         $$0.put(gez.b($$3x), $$60);

         for (gor.a $$4x : gor.a.values()) {
            gfg $$5x = gor.a($$4x);
            $$0.put(gez.a($$3x, $$4x), $$5x);
         }
      });
      ImmutableMap<gey, gfg> $$61 = $$0.build();
      List<gey> $$62 = gez.a().filter($$1x -> !$$61.containsKey($$1x)).collect(Collectors.toList());
      if (!$$62.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$62);
      } else {
         return $$61;
      }
   }
}
