import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gez {
   private static final gfg a = new gfg(0.008F);
   private static final gfg b = new gfg(1.0F);
   private static final gfg c = new gfg(0.5F);

   public static Map<gfa, gfi> a() {
      Builder<gfa, gfi> $$0 = ImmutableMap.builder();
      gfi $$1 = gfi.a(gcn.a(gfg.a, 0.0F), 64, 64);
      gfi $$2 = gfi.a(gcm.a(b), 64, 32);
      gfi $$3 = gfi.a(gcm.a(new gfg(1.02F)), 64, 32);
      gfi $$4 = gfi.a(gcm.a(c), 64, 32);
      gfi $$5 = gcu.a();
      gfi $$6 = gdw.c();
      gfi $$7 = gfi.a(gao.a(gfg.a), 64, 64);
      gfi $$8 = gfi.a(gao.b(gfg.a), 64, 64);
      gfl $$9 = gfl.scaling(0.9375F);
      gfi $$10 = gco.a().a($$9);
      gfi $$11 = gay.a();
      gfi $$12 = gbd.a();
      gfi $$13 = gbq.a();
      gfi $$14 = $$13.a(gbq.a);
      gfi $$15 = gbw.a();
      gfi $$16 = gfi.a(gcc.a(gfg.a), 64, 32);
      gfi $$17 = $$16.a(gcc.b);
      gfi $$18 = gfi.a(gcc.a(new gfg(0.01F)), 64, 32);
      gfi $$19 = gfi.a(gdc.a(gfg.a), 64, 64);
      gfi $$20 = gfi.a(gdb.a(), 64, 64);
      gfi $$21 = gdw.b();
      gfi $$22 = gcs.a(gfg.a);
      gfi $$23 = gcs.a(new gfg(0.5F));
      gfi $$24 = gee.a();
      gfi $$25 = gck.a();
      gfi $$26 = gck.b();
      gfi $$27 = gdv.c();
      gfi $$28 = gfi.a(gem.a(), 64, 64).a($$9);
      gfi $$29 = geb.a();
      gfi $$30 = gat.a();
      gfi $$31 = gbl.a();
      gfi $$32 = gbo.a();
      gfi $$33 = gch.a();
      gfi $$34 = gcx.a();
      gfi $$35 = gda.a(gfg.a);
      gfi $$36 = gda.a(new gfg(0.5F));
      gfi $$37 = gdg.a();
      gfi $$38 = gdq.a();
      gfi $$39 = gdp.a();
      gfi $$40 = gdz.a();
      gfi $$41 = gej.a();
      gfi $$42 = gfi.a(ger.a(gfg.a), 64, 32);
      gfi $$43 = gfi.a(ger.a(new gfg(0.2F)), 64, 32);
      gfi $$44 = get.a();
      gfi $$45 = gaw.a();
      gfi $$46 = gav.a(c);
      gfi $$47 = gav.a(b);
      gfi $$48 = gbv.a(gfg.a);
      gfi $$49 = gbv.a(new gfg(0.25F));
      gfi $$50 = ged.a();
      gfi $$51 = gbt.a();
      gfi $$52 = gdo.a();
      $$0.put(gfb.c, gar.a());
      $$0.put(gfb.d, $$30);
      $$0.put(gfb.e, $$30.a(gat.a));
      $$0.put(gfb.f, $$45);
      $$0.put(gfb.g, $$46);
      $$0.put(gfb.h, $$47);
      $$0.put(gfb.i, $$45.a(gcn.i));
      $$0.put(gfb.j, $$46.a(gcn.i));
      $$0.put(gfb.k, $$47.a(gcn.i));
      $$0.put(gfb.l, gax.a());
      $$0.put(gfb.m, $$11);
      $$0.put(gfb.n, $$11.a(gay.b));
      $$0.put(gfb.q, gbb.a(true));
      $$0.put(gfb.s, gbb.a(false));
      $$0.put(gfb.r, gba.a(true));
      $$0.put(gfb.t, gba.a(false));
      $$0.put(gfb.u, gbc.a());
      $$0.put(gfb.v, gog.c());
      $$0.put(gfb.w, gog.b());
      $$0.put(gfb.x, $$12);
      $$0.put(gfb.y, $$12.a(gbd.a));
      $$0.put(gfb.z, gbe.a());
      $$0.put(gfb.A, gbf.a());
      $$0.put(gfb.D, gbg.a());
      $$0.put(gfb.E, gbh.c());
      $$0.put(gfb.F, gbi.a());
      $$0.put(gfb.G, $$4);
      $$0.put(gfb.H, $$2);
      $$0.put(gfb.I, gfi.a(gcn.a(new gfg(0.2F), 0.0F), 64, 32));
      $$0.put(gfb.J, gbj.a());
      $$0.put(gfb.K, gbk.a(32, 32));
      $$0.put(gfb.L, gbk.a(128, 128));
      $$0.put(gfb.O, $$16.a(gbm.a));
      $$0.put(gfb.P, $$17.a(gbm.a));
      $$0.put(gfb.R, $$18.a(gbm.a));
      $$0.put(gfb.Q, $$18.a(gcc.b).a(gbm.a));
      $$0.put(gfb.M, $$31);
      $$0.put(gfb.N, $$31.a(gbl.a));
      $$0.put(gfb.S, $$29.a(gfl.scaling(0.7F)));
      $$0.put(gfb.V, gbn.a());
      $$0.put(gfb.W, $$5);
      $$0.put(gfb.X, $$32);
      $$0.put(gfb.Y, $$32.a(gbo.b));
      $$0.put(gfb.Z, gbp.a());
      $$0.put(gfb.aa, $$5);
      $$0.put(gfb.ac, goq.b());
      $$0.put(gfb.ae, goq.c());
      $$0.put(gfb.ad, goq.d());
      $$0.put(gfb.ab, goq.e());
      $$0.put(gfb.af, $$13);
      $$0.put(gfb.ag, $$14);
      $$0.put(gfb.ah, gbr.a());
      $$0.put(gfb.ai, gbs.a(gfg.a));
      $$0.put(gfb.aj, gbs.a(new gfg(2.0F)));
      $$0.put(gfb.ak, $$6);
      $$0.put(gfb.an, gor.b());
      $$0.put(gfb.ao, gor.c());
      $$0.put(gfb.ap, $$51);
      $$0.put(gfb.aq, $$51.a(gbt.a));
      $$0.put(gfb.ar, gbu.a(0.87F));
      $$0.put(gfb.as, gbu.b(0.87F));
      $$0.put(gfb.at, gbn.c());
      $$0.put(gfb.au, gbn.b());
      $$0.put(gfb.av, gev.a());
      $$0.put(gfb.aw, $$48);
      $$0.put(gfb.aB, $$4);
      $$0.put(gfb.aC, $$4);
      $$0.put(gfb.aD, $$49);
      $$0.put(gfb.ax, $$48.a(gcn.i));
      $$0.put(gfb.ay, $$4.a(gcn.i));
      $$0.put(gfb.az, $$4.a(gcn.i));
      $$0.put(gfb.aA, $$49.a(gcn.i));
      $$0.put(gfb.aE, gci.b());
      $$0.put(gfb.aF, $$15);
      $$0.put(gfb.aG, $$15.a(gbw.a));
      $$0.put(gfb.aH, gby.a());
      $$0.put(gfb.aI, gbz.a());
      $$0.put(gfb.aJ, gew.a());
      $$0.put(gfb.aK, gbx.a());
      $$0.put(gfb.aL, $$10);
      $$0.put(gfb.aM, gcb.a());
      $$0.put(gfb.aN, gcd.a());
      $$0.put(gfb.aO, gcd.a().a(gcd.a));
      $$0.put(gfb.aP, gce.a());
      $$0.put(gfb.aQ, $$5);
      $$0.put(gfb.aR, gcf.a());
      gfl $$53 = gfl.scaling(6.0F);
      $$0.put(gfb.aS, $$1.a($$53));
      $$0.put(gfb.aT, $$4.a($$53));
      $$0.put(gfb.aU, $$2.a($$53));
      $$0.put(gfb.aV, $$50);
      $$0.put(gfb.aW, $$50.a(ged.a));
      $$0.put(gfb.aX, $$33);
      $$0.put(gfb.aY, $$33.a(gch.a));
      $$0.put(gfb.aZ, gci.a());
      $$0.put(gfb.ba, $$25);
      $$0.put(gfb.bb, $$26);
      $$0.put(gfb.bc, $$5);
      gfl $$54 = gfl.scaling(1.1F);
      $$0.put(gfb.bd, $$7.a($$54));
      $$0.put(gfb.bf, $$8.a($$54));
      $$0.put(gfb.be, gfi.a(gao.a(new gfg(0.1F)), 64, 64).a($$54));
      $$0.put(gfb.bg, gfi.a(gao.b(new gfg(0.1F)), 64, 64).a($$54));
      gfl $$55 = gfl.scaling(1.0625F);
      $$0.put(gfb.bh, $$1.a($$55));
      $$0.put(gfb.bl, $$4.a($$55));
      $$0.put(gfb.bm, $$2.a($$55));
      $$0.put(gfb.bi, $$1.a(gcn.i).a($$55));
      $$0.put(gfb.bj, $$4.a(gcn.i).a($$55));
      $$0.put(gfb.bk, $$2.a(gcn.i).a($$55));
      $$0.put(gfb.bn, $$10);
      $$0.put(gfb.bo, gcp.a());
      $$0.put(gfb.br, gcr.a());
      $$0.put(gfb.bs, $$22);
      $$0.put(gfb.bt, $$22.a(gcs.a));
      $$0.put(gfb.bv, $$23);
      $$0.put(gfb.bu, $$23.a(gcs.a));
      $$0.put(gfb.bw, gct.a());
      $$0.put(gfb.bx, gcq.a());
      $$0.put(gfb.bA, $$5);
      $$0.put(gfb.bB, $$13);
      $$0.put(gfb.bC, $$14);
      $$0.put(gfb.bD, gbu.a(0.92F));
      $$0.put(gfb.bE, gbu.b(0.92F));
      $$0.put(gfb.bH, $$16);
      $$0.put(gfb.bI, $$17);
      $$0.put(gfb.bL, $$34);
      $$0.put(gfb.bM, $$34.a(gcx.a));
      $$0.put(gfb.bN, gcy.a());
      $$0.put(gfb.bO, gcz.a());
      $$0.put(gfb.bP, $$35);
      $$0.put(gfb.ca, $$35.a(gda.a));
      $$0.put(gfb.cc, $$36);
      $$0.put(gfb.cb, $$36.a(gda.a));
      $$0.put(gfb.bQ, $$19);
      $$0.put(gfb.bY, $$4);
      $$0.put(gfb.bZ, $$3);
      $$0.put(gfb.bU, $$19);
      $$0.put(gfb.bV, $$4);
      $$0.put(gfb.bW, $$3);
      $$0.put(gfb.bR, $$19.a(gcn.i));
      $$0.put(gfb.bS, $$4.a(gcn.i));
      $$0.put(gfb.bT, $$3.a(gcn.i));
      $$0.put(gfb.bX, $$20);
      $$0.put(gfb.cd, $$10);
      $$0.put(gfb.ce, gfi.a(gdf.a(gfg.a, false), 64, 64));
      $$0.put(gfb.cg, gde.a());
      $$0.put(gfb.cf, gdd.a());
      $$0.put(gfb.ch, $$21);
      $$0.put(gfb.ci, $$4);
      $$0.put(gfb.cj, $$2);
      $$0.put(gfb.ck, gfi.a(gdf.a(gfg.a, true), 64, 64));
      $$0.put(gfb.cl, $$4);
      $$0.put(gfb.cm, $$2);
      $$0.put(gfb.cn, gec.a());
      $$0.put(gfb.co, $$37);
      $$0.put(gfb.cp, $$37.a(gdg.a));
      $$0.put(gfb.cq, gdh.a());
      $$0.put(gfb.cr, gdi.a());
      $$0.put(gfb.cs, gdj.a());
      $$0.put(gfb.ct, gdl.a(false));
      $$0.put(gfb.cu, gdl.a(true));
      $$0.put(gfb.cv, gdn.a());
      $$0.put(gfb.cw, $$52);
      $$0.put(gfb.cy, $$52.a(gdo.a));
      $$0.put(gfb.cx, $$52.a(gdo.b));
      $$0.put(gfb.cz, $$38);
      $$0.put(gfb.cA, $$38.a(gdq.a));
      $$0.put(gfb.cC, $$39);
      $$0.put(gfb.cB, $$39.a(gdq.a));
      $$0.put(gfb.cD, gdr.a());
      $$0.put(gfb.cE, gdt.a());
      $$0.put(gfb.cF, gdt.b());
      $$0.put(gfb.cG, gds.a());
      $$0.put(gfb.cH, gdu.a());
      $$0.put(gfb.cI, $$27);
      $$0.put(gfb.cL, $$4);
      $$0.put(gfb.cM, $$2);
      $$0.put(gfb.cJ, $$7);
      $$0.put(gfb.cK, $$8);
      $$0.put(gfb.cN, $$6);
      $$0.put(gfb.cO, gdy.b());
      $$0.put(gfb.cP, gdy.a());
      $$0.put(gfb.cQ, $$40);
      $$0.put(gfb.cR, $$40.a(gdz.a));
      $$0.put(gfb.cS, gea.a());
      $$0.put(gfb.cT, $$5);
      $$0.put(gfb.cU, $$29);
      $$0.put(gfb.cX, $$50);
      $$0.put(gfb.cY, $$50.a(ged.a));
      $$0.put(gfb.cZ, $$27);
      $$0.put(gfb.da, $$4);
      $$0.put(gfb.db, $$2);
      $$0.put(gfb.dc, gfi.a(gcn.a(new gfg(0.25F), 0.0F), 64, 32));
      $$0.put(gfb.dd, $$24);
      $$0.put(gfb.de, $$24);
      $$0.put(gfb.df, $$24.a(gee.a));
      $$0.put(gfb.dg, $$24.a(gee.a));
      $$0.put(gfb.dh, gef.a());
      $$0.put(gfb.di, $$5);
      $$0.put(gfb.dj, $$22);
      $$0.put(gfb.dk, $$22.a(gcs.a));
      $$0.put(gfb.dl, geg.a());
      $$0.put(gfb.dm, gei.a(gfg.a));
      $$0.put(gfb.dn, gei.a(a));
      $$0.put(gfb.do, geh.a(gfg.a));
      $$0.put(gfb.dp, geh.a(a));
      $$0.put(gfb.dq, $$41);
      $$0.put(gfb.dr, $$41.a(gej.a));
      $$0.put(gfb.ds, gek.a());
      $$0.put(gfb.dt, $$28);
      $$0.put(gfb.du, $$28.a(gem.a));
      $$0.put(gfb.dv, $$10);
      $$0.put(gfb.dx, gen.a());
      $$0.put(gfb.dw, $$28);
      $$0.put(gfb.dy, geo.a());
      $$0.put(gfb.dz, gep.a().a($$9));
      $$0.put(gfb.dA, geq.a(gfg.a));
      $$0.put(gfb.dB, geq.a(c));
      $$0.put(gfb.dG, gvh.a());
      gfl $$56 = gfl.scaling(1.2F);
      $$0.put(gfb.dC, $$27.a($$56));
      $$0.put(gfb.dD, $$4.a($$56));
      $$0.put(gfb.dE, $$2.a($$56));
      $$0.put(gfb.dF, $$6);
      $$0.put(gfb.dH, $$42);
      $$0.put(gfb.dI, $$43);
      $$0.put(gfb.dJ, $$42.a(ger.a));
      $$0.put(gfb.dK, $$43.a(ger.a));
      $$0.put(gfb.dL, $$25);
      $$0.put(gfb.dM, $$26);
      $$0.put(gfb.dN, $$1);
      $$0.put(gfb.dU, $$4);
      $$0.put(gfb.dV, $$2);
      $$0.put(gfb.dO, $$1.a(gcn.i));
      $$0.put(gfb.dP, $$4.a(gcn.i));
      $$0.put(gfb.dQ, $$2.a(gcn.i));
      $$0.put(gfb.dR, $$21);
      $$0.put(gfb.dS, $$7);
      $$0.put(gfb.dT, $$8);
      $$0.put(gfb.dW, $$44);
      $$0.put(gfb.ea, get.a(c));
      $$0.put(gfb.eb, get.a(b));
      $$0.put(gfb.dX, $$44.a(gcn.i));
      $$0.put(gfb.dY, get.a(c).a(gcn.i));
      $$0.put(gfb.dZ, get.a(b).a(gcn.i));
      $$0.put(gfb.ec, $$19);
      $$0.put(gfb.eg, $$4);
      $$0.put(gfb.eh, $$3);
      $$0.put(gfb.ed, $$19.a(gcn.i));
      $$0.put(gfb.ee, $$4.a(gcn.i));
      $$0.put(gfb.ef, $$3.a(gcn.i));
      $$0.put(gfb.p, gdm.a());
      $$0.put(gfb.o, gdm.b());
      gfi $$57 = gbh.a();
      gfi $$58 = gbh.b();
      $$0.put(gfb.bF, $$57);
      $$0.put(gfb.bG, $$58);
      $$0.put(gfb.cV, $$57);
      $$0.put(gfb.cW, $$58);
      $$0.put(gfb.B, $$57);
      $$0.put(gfb.C, $$58);
      $$0.put(gfb.bp, $$57);
      $$0.put(gfb.bq, $$58);
      $$0.put(gfb.a, $$57);
      $$0.put(gfb.b, $$58);
      $$0.put(gfb.T, $$57);
      $$0.put(gfb.U, $$58);
      $$0.put(gfb.al, $$57);
      $$0.put(gfb.am, $$58);
      $$0.put(gfb.bJ, $$57);
      $$0.put(gfb.bK, $$58);
      $$0.put(gfb.by, $$57);
      $$0.put(gfb.bz, $$58);
      gfi $$59 = gox.a(true);
      gfi $$60 = gox.a(false);
      dyi.a().forEach($$3x -> {
         $$0.put(gfb.a($$3x), $$59);
         $$0.put(gfb.b($$3x), $$60);

         for (got.a $$4x : got.a.values()) {
            gfi $$5x = got.a($$4x);
            $$0.put(gfb.a($$3x, $$4x), $$5x);
         }
      });
      ImmutableMap<gfa, gfi> $$61 = $$0.build();
      List<gfa> $$62 = gfb.a().filter($$1x -> !$$61.containsKey($$1x)).collect(Collectors.toList());
      if (!$$62.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$62);
      } else {
         return $$61;
      }
   }
}
