import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gfb {
   private static final gfi a = new gfi(0.008F);
   private static final gfi b = new gfi(1.0F);
   private static final gfi c = new gfi(0.5F);

   public static Map<gfc, gfk> a() {
      Builder<gfc, gfk> $$0 = ImmutableMap.builder();
      gfk $$1 = gfk.a(gcp.a(gfi.a, 0.0F), 64, 64);
      gfk $$2 = gfk.a(gco.a(b), 64, 32);
      gfk $$3 = gfk.a(gco.a(new gfi(1.02F)), 64, 32);
      gfk $$4 = gfk.a(gco.a(c), 64, 32);
      gfk $$5 = gcw.a();
      gfk $$6 = gdy.c();
      gfk $$7 = gfk.a(gaq.a(gfi.a), 64, 64);
      gfk $$8 = gfk.a(gaq.b(gfi.a), 64, 64);
      gfn $$9 = gfn.scaling(0.9375F);
      gfk $$10 = gcq.a().a($$9);
      gfk $$11 = gba.a();
      gfk $$12 = gbf.a();
      gfk $$13 = gbs.a();
      gfk $$14 = $$13.a(gbs.a);
      gfk $$15 = gby.a();
      gfk $$16 = gfk.a(gce.a(gfi.a), 64, 32);
      gfk $$17 = $$16.a(gce.b);
      gfk $$18 = gfk.a(gce.a(new gfi(0.01F)), 64, 32);
      gfk $$19 = gfk.a(gde.a(gfi.a), 64, 64);
      gfk $$20 = gfk.a(gdd.a(), 64, 64);
      gfk $$21 = gdy.b();
      gfk $$22 = gcu.a(gfi.a);
      gfk $$23 = gcu.a(new gfi(0.5F));
      gfk $$24 = geg.a();
      gfk $$25 = gcm.a();
      gfk $$26 = gcm.b();
      gfk $$27 = gdx.c();
      gfk $$28 = gfk.a(geo.a(), 64, 64).a($$9);
      gfk $$29 = ged.a();
      gfk $$30 = gav.a();
      gfk $$31 = gbn.a();
      gfk $$32 = gbq.a();
      gfk $$33 = gcj.a();
      gfk $$34 = gcz.a();
      gfk $$35 = gdc.a(gfi.a);
      gfk $$36 = gdc.a(new gfi(0.5F));
      gfk $$37 = gdi.a();
      gfk $$38 = gds.a();
      gfk $$39 = gdr.a();
      gfk $$40 = geb.a();
      gfk $$41 = gel.a();
      gfk $$42 = gfk.a(get.a(gfi.a), 64, 32);
      gfk $$43 = gfk.a(get.a(new gfi(0.2F)), 64, 32);
      gfk $$44 = gev.a();
      gfk $$45 = gay.a();
      gfk $$46 = gax.a(c);
      gfk $$47 = gax.a(b);
      gfk $$48 = gbx.a(gfi.a);
      gfk $$49 = gbx.a(new gfi(0.25F));
      gfk $$50 = gef.a();
      gfk $$51 = gbv.a();
      gfk $$52 = gdq.a();
      $$0.put(gfd.c, gat.a());
      $$0.put(gfd.d, $$30);
      $$0.put(gfd.e, $$30.a(gav.a));
      $$0.put(gfd.f, $$45);
      $$0.put(gfd.g, $$46);
      $$0.put(gfd.h, $$47);
      $$0.put(gfd.i, $$45.a(gcp.i));
      $$0.put(gfd.j, $$46.a(gcp.i));
      $$0.put(gfd.k, $$47.a(gcp.i));
      $$0.put(gfd.l, gaz.a());
      $$0.put(gfd.m, $$11);
      $$0.put(gfd.n, $$11.a(gba.b));
      $$0.put(gfd.q, gbd.a(true));
      $$0.put(gfd.s, gbd.a(false));
      $$0.put(gfd.r, gbc.a(true));
      $$0.put(gfd.t, gbc.a(false));
      $$0.put(gfd.u, gbe.a());
      $$0.put(gfd.v, goi.c());
      $$0.put(gfd.w, goi.b());
      $$0.put(gfd.x, $$12);
      $$0.put(gfd.y, $$12.a(gbf.a));
      $$0.put(gfd.z, gbg.a());
      $$0.put(gfd.A, gbh.a());
      $$0.put(gfd.D, gbi.a());
      $$0.put(gfd.E, gbj.c());
      $$0.put(gfd.F, gbk.a());
      $$0.put(gfd.G, $$4);
      $$0.put(gfd.H, $$2);
      $$0.put(gfd.I, gfk.a(gcp.a(new gfi(0.2F), 0.0F), 64, 32));
      $$0.put(gfd.J, gbl.a());
      $$0.put(gfd.K, gbm.a(32, 32));
      $$0.put(gfd.L, gbm.a(128, 128));
      $$0.put(gfd.O, $$16.a(gbo.a));
      $$0.put(gfd.P, $$17.a(gbo.a));
      $$0.put(gfd.R, $$18.a(gbo.a));
      $$0.put(gfd.Q, $$18.a(gce.b).a(gbo.a));
      $$0.put(gfd.M, $$31);
      $$0.put(gfd.N, $$31.a(gbn.a));
      $$0.put(gfd.S, $$29.a(gfn.scaling(0.7F)));
      $$0.put(gfd.V, gbp.a());
      $$0.put(gfd.W, $$5);
      $$0.put(gfd.X, $$32);
      $$0.put(gfd.Y, $$32.a(gbq.b));
      $$0.put(gfd.Z, gbr.a());
      $$0.put(gfd.aa, $$5);
      $$0.put(gfd.ac, gos.b());
      $$0.put(gfd.ae, gos.c());
      $$0.put(gfd.ad, gos.d());
      $$0.put(gfd.ab, gos.e());
      $$0.put(gfd.af, $$13);
      $$0.put(gfd.ag, $$14);
      $$0.put(gfd.ah, gbt.a());
      $$0.put(gfd.ai, gbu.a(gfi.a));
      $$0.put(gfd.aj, gbu.a(new gfi(2.0F)));
      $$0.put(gfd.ak, $$6);
      $$0.put(gfd.an, got.b());
      $$0.put(gfd.ao, got.c());
      $$0.put(gfd.ap, $$51);
      $$0.put(gfd.aq, $$51.a(gbv.a));
      $$0.put(gfd.ar, gbw.a(0.87F));
      $$0.put(gfd.as, gbw.b(0.87F));
      $$0.put(gfd.at, gbp.c());
      $$0.put(gfd.au, gbp.b());
      $$0.put(gfd.av, gex.a());
      $$0.put(gfd.aw, $$48);
      $$0.put(gfd.aB, $$4);
      $$0.put(gfd.aC, $$4);
      $$0.put(gfd.aD, $$49);
      $$0.put(gfd.ax, $$48.a(gcp.i));
      $$0.put(gfd.ay, $$4.a(gcp.i));
      $$0.put(gfd.az, $$4.a(gcp.i));
      $$0.put(gfd.aA, $$49.a(gcp.i));
      $$0.put(gfd.aE, gck.b());
      $$0.put(gfd.aF, $$15);
      $$0.put(gfd.aG, $$15.a(gby.a));
      $$0.put(gfd.aH, gca.a());
      $$0.put(gfd.aI, gcb.a());
      $$0.put(gfd.aJ, gey.a());
      $$0.put(gfd.aK, gbz.a());
      $$0.put(gfd.aL, $$10);
      $$0.put(gfd.aM, gcd.a());
      $$0.put(gfd.aN, gcf.a());
      $$0.put(gfd.aO, gcf.a().a(gcf.a));
      $$0.put(gfd.aP, gcg.a());
      $$0.put(gfd.aQ, $$5);
      $$0.put(gfd.aR, gch.a());
      gfn $$53 = gfn.scaling(6.0F);
      $$0.put(gfd.aS, $$1.a($$53));
      $$0.put(gfd.aT, $$4.a($$53));
      $$0.put(gfd.aU, $$2.a($$53));
      $$0.put(gfd.aV, $$50);
      $$0.put(gfd.aW, $$50.a(gef.a));
      $$0.put(gfd.aX, $$33);
      $$0.put(gfd.aY, $$33.a(gcj.a));
      $$0.put(gfd.aZ, gck.a());
      $$0.put(gfd.ba, $$25);
      $$0.put(gfd.bb, $$26);
      $$0.put(gfd.bc, $$5);
      gfn $$54 = gfn.scaling(1.1F);
      $$0.put(gfd.bd, $$7.a($$54));
      $$0.put(gfd.bf, $$8.a($$54));
      $$0.put(gfd.be, gfk.a(gaq.a(new gfi(0.1F)), 64, 64).a($$54));
      $$0.put(gfd.bg, gfk.a(gaq.b(new gfi(0.1F)), 64, 64).a($$54));
      gfn $$55 = gfn.scaling(1.0625F);
      $$0.put(gfd.bh, $$1.a($$55));
      $$0.put(gfd.bl, $$4.a($$55));
      $$0.put(gfd.bm, $$2.a($$55));
      $$0.put(gfd.bi, $$1.a(gcp.i).a($$55));
      $$0.put(gfd.bj, $$4.a(gcp.i).a($$55));
      $$0.put(gfd.bk, $$2.a(gcp.i).a($$55));
      $$0.put(gfd.bn, $$10);
      $$0.put(gfd.bo, gcr.a());
      $$0.put(gfd.br, gct.a());
      $$0.put(gfd.bs, $$22);
      $$0.put(gfd.bt, $$22.a(gcu.a));
      $$0.put(gfd.bv, $$23);
      $$0.put(gfd.bu, $$23.a(gcu.a));
      $$0.put(gfd.bw, gcv.a());
      $$0.put(gfd.bx, gcs.a());
      $$0.put(gfd.bA, $$5);
      $$0.put(gfd.bB, $$13);
      $$0.put(gfd.bC, $$14);
      $$0.put(gfd.bD, gbw.a(0.92F));
      $$0.put(gfd.bE, gbw.b(0.92F));
      $$0.put(gfd.bH, $$16);
      $$0.put(gfd.bI, $$17);
      $$0.put(gfd.bL, $$34);
      $$0.put(gfd.bM, $$34.a(gcz.a));
      $$0.put(gfd.bN, gda.a());
      $$0.put(gfd.bO, gdb.a());
      $$0.put(gfd.bP, $$35);
      $$0.put(gfd.ca, $$35.a(gdc.a));
      $$0.put(gfd.cc, $$36);
      $$0.put(gfd.cb, $$36.a(gdc.a));
      $$0.put(gfd.bQ, $$19);
      $$0.put(gfd.bY, $$4);
      $$0.put(gfd.bZ, $$3);
      $$0.put(gfd.bU, $$19);
      $$0.put(gfd.bV, $$4);
      $$0.put(gfd.bW, $$3);
      $$0.put(gfd.bR, $$19.a(gcp.i));
      $$0.put(gfd.bS, $$4.a(gcp.i));
      $$0.put(gfd.bT, $$3.a(gcp.i));
      $$0.put(gfd.bX, $$20);
      $$0.put(gfd.cd, $$10);
      $$0.put(gfd.ce, gfk.a(gdh.a(gfi.a, false), 64, 64));
      $$0.put(gfd.cg, gdg.a());
      $$0.put(gfd.cf, gdf.a());
      $$0.put(gfd.ch, $$21);
      $$0.put(gfd.ci, $$4);
      $$0.put(gfd.cj, $$2);
      $$0.put(gfd.ck, gfk.a(gdh.a(gfi.a, true), 64, 64));
      $$0.put(gfd.cl, $$4);
      $$0.put(gfd.cm, $$2);
      $$0.put(gfd.cn, gee.a());
      $$0.put(gfd.co, $$37);
      $$0.put(gfd.cp, $$37.a(gdi.a));
      $$0.put(gfd.cq, gdj.a());
      $$0.put(gfd.cr, gdk.a());
      $$0.put(gfd.cs, gdl.a());
      $$0.put(gfd.ct, gdn.a(false));
      $$0.put(gfd.cu, gdn.a(true));
      $$0.put(gfd.cv, gdp.a());
      $$0.put(gfd.cw, $$52);
      $$0.put(gfd.cy, $$52.a(gdq.a));
      $$0.put(gfd.cx, $$52.a(gdq.b));
      $$0.put(gfd.cz, $$38);
      $$0.put(gfd.cA, $$38.a(gds.a));
      $$0.put(gfd.cC, $$39);
      $$0.put(gfd.cB, $$39.a(gds.a));
      $$0.put(gfd.cD, gdt.a());
      $$0.put(gfd.cE, gdv.a());
      $$0.put(gfd.cF, gdv.b());
      $$0.put(gfd.cG, gdu.a());
      $$0.put(gfd.cH, gdw.a());
      $$0.put(gfd.cI, $$27);
      $$0.put(gfd.cL, $$4);
      $$0.put(gfd.cM, $$2);
      $$0.put(gfd.cJ, $$7);
      $$0.put(gfd.cK, $$8);
      $$0.put(gfd.cN, $$6);
      $$0.put(gfd.cO, gea.b());
      $$0.put(gfd.cP, gea.a());
      $$0.put(gfd.cQ, $$40);
      $$0.put(gfd.cR, $$40.a(geb.a));
      $$0.put(gfd.cS, gec.a());
      $$0.put(gfd.cT, $$5);
      $$0.put(gfd.cU, $$29);
      $$0.put(gfd.cX, $$50);
      $$0.put(gfd.cY, $$50.a(gef.a));
      $$0.put(gfd.cZ, $$27);
      $$0.put(gfd.da, $$4);
      $$0.put(gfd.db, $$2);
      $$0.put(gfd.dc, gfk.a(gcp.a(new gfi(0.25F), 0.0F), 64, 32));
      $$0.put(gfd.dd, $$24);
      $$0.put(gfd.de, $$24);
      $$0.put(gfd.df, $$24.a(geg.a));
      $$0.put(gfd.dg, $$24.a(geg.a));
      $$0.put(gfd.dh, geh.a());
      $$0.put(gfd.di, $$5);
      $$0.put(gfd.dj, $$22);
      $$0.put(gfd.dk, $$22.a(gcu.a));
      $$0.put(gfd.dl, gei.a());
      $$0.put(gfd.dm, gek.a(gfi.a));
      $$0.put(gfd.dn, gek.a(a));
      $$0.put(gfd.do, gej.a(gfi.a));
      $$0.put(gfd.dp, gej.a(a));
      $$0.put(gfd.dq, $$41);
      $$0.put(gfd.dr, $$41.a(gel.a));
      $$0.put(gfd.ds, gem.a());
      $$0.put(gfd.dt, $$28);
      $$0.put(gfd.du, $$28.a(geo.a));
      $$0.put(gfd.dv, $$10);
      $$0.put(gfd.dx, gep.a());
      $$0.put(gfd.dw, $$28);
      $$0.put(gfd.dy, geq.a());
      $$0.put(gfd.dz, ger.a().a($$9));
      $$0.put(gfd.dA, ges.a(gfi.a));
      $$0.put(gfd.dB, ges.a(c));
      $$0.put(gfd.dG, gvj.a());
      gfn $$56 = gfn.scaling(1.2F);
      $$0.put(gfd.dC, $$27.a($$56));
      $$0.put(gfd.dD, $$4.a($$56));
      $$0.put(gfd.dE, $$2.a($$56));
      $$0.put(gfd.dF, $$6);
      $$0.put(gfd.dH, $$42);
      $$0.put(gfd.dI, $$43);
      $$0.put(gfd.dJ, $$42.a(get.a));
      $$0.put(gfd.dK, $$43.a(get.a));
      $$0.put(gfd.dL, $$25);
      $$0.put(gfd.dM, $$26);
      $$0.put(gfd.dN, $$1);
      $$0.put(gfd.dU, $$4);
      $$0.put(gfd.dV, $$2);
      $$0.put(gfd.dO, $$1.a(gcp.i));
      $$0.put(gfd.dP, $$4.a(gcp.i));
      $$0.put(gfd.dQ, $$2.a(gcp.i));
      $$0.put(gfd.dR, $$21);
      $$0.put(gfd.dS, $$7);
      $$0.put(gfd.dT, $$8);
      $$0.put(gfd.dW, $$44);
      $$0.put(gfd.ea, gev.a(c));
      $$0.put(gfd.eb, gev.a(b));
      $$0.put(gfd.dX, $$44.a(gcp.i));
      $$0.put(gfd.dY, gev.a(c).a(gcp.i));
      $$0.put(gfd.dZ, gev.a(b).a(gcp.i));
      $$0.put(gfd.ec, $$19);
      $$0.put(gfd.eg, $$4);
      $$0.put(gfd.eh, $$3);
      $$0.put(gfd.ed, $$19.a(gcp.i));
      $$0.put(gfd.ee, $$4.a(gcp.i));
      $$0.put(gfd.ef, $$3.a(gcp.i));
      $$0.put(gfd.p, gdo.a());
      $$0.put(gfd.o, gdo.b());
      gfk $$57 = gbj.a();
      gfk $$58 = gbj.b();
      $$0.put(gfd.bF, $$57);
      $$0.put(gfd.bG, $$58);
      $$0.put(gfd.cV, $$57);
      $$0.put(gfd.cW, $$58);
      $$0.put(gfd.B, $$57);
      $$0.put(gfd.C, $$58);
      $$0.put(gfd.bp, $$57);
      $$0.put(gfd.bq, $$58);
      $$0.put(gfd.a, $$57);
      $$0.put(gfd.b, $$58);
      $$0.put(gfd.T, $$57);
      $$0.put(gfd.U, $$58);
      $$0.put(gfd.al, $$57);
      $$0.put(gfd.am, $$58);
      $$0.put(gfd.bJ, $$57);
      $$0.put(gfd.bK, $$58);
      $$0.put(gfd.by, $$57);
      $$0.put(gfd.bz, $$58);
      gfk $$59 = goz.a(true);
      gfk $$60 = goz.a(false);
      dyk.a().forEach($$3x -> {
         $$0.put(gfd.a($$3x), $$59);
         $$0.put(gfd.b($$3x), $$60);

         for (gov.a $$4x : gov.a.values()) {
            gfk $$5x = gov.a($$4x);
            $$0.put(gfd.a($$3x, $$4x), $$5x);
         }
      });
      ImmutableMap<gfc, gfk> $$61 = $$0.build();
      List<gfc> $$62 = gfd.a().filter($$1x -> !$$61.containsKey($$1x)).collect(Collectors.toList());
      if (!$$62.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$62);
      } else {
         return $$61;
      }
   }
}
