import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gha {
   private static final ghh a = new ghh(0.008F);
   private static final ghh b = new ghh(1.0F);
   private static final ghh c = new ghh(0.5F);

   public static Map<ghb, ghj> a() {
      Builder<ghb, ghj> $$0 = ImmutableMap.builder();
      ghj $$1 = ghj.a(geo.a(ghh.a, 0.0F), 64, 64);
      ghj $$2 = ghj.a(gen.a(b), 64, 32);
      ghj $$3 = ghj.a(gen.a(new ghh(1.02F)), 64, 32);
      ghj $$4 = ghj.a(gen.a(c), 64, 32);
      ghj $$5 = gev.a();
      ghj $$6 = gfx.c();
      ghj $$7 = ghj.a(gcl.a(ghh.a), 64, 64);
      ghj $$8 = ghj.a(gcl.b(ghh.a), 64, 64);
      ghj $$9 = geb.a(false);
      ghj $$10 = geb.a(true);
      ghm $$11 = ghm.scaling(0.9375F);
      ghj $$12 = gep.a().a($$11);
      ghj $$13 = gcw.a();
      ghj $$14 = gdb.a();
      ghj $$15 = gdq.a();
      ghj $$16 = $$15.a(gdq.a);
      ghj $$17 = gdw.a();
      ghj $$18 = ghj.a(ged.a(ghh.a), 64, 32);
      ghj $$19 = $$18.a(ged.b);
      ghj $$20 = ghj.a(ged.a(new ghh(0.01F)), 64, 32);
      ghj $$21 = ghj.a(gfd.a(ghh.a), 64, 64);
      ghj $$22 = ghj.a(gfc.a(), 64, 64);
      ghj $$23 = gfx.b();
      ghj $$24 = get.a(ghh.a);
      ghj $$25 = get.a(new ghh(0.5F));
      ghj $$26 = ggf.a();
      ghj $$27 = gel.a();
      ghj $$28 = gel.b();
      ghj $$29 = gfw.c();
      ghj $$30 = ghj.a(ggn.a(), 64, 64).a($$11);
      ghj $$31 = ggc.a();
      ghj $$32 = gcr.a();
      ghj $$33 = gdj.a();
      ghj $$34 = gdk.c();
      ghj $$35 = gdn.a();
      ghj $$36 = gei.a();
      ghj $$37 = gey.a();
      ghj $$38 = gfb.b(ghh.a);
      ghj $$39 = gdp.a(ghh.a);
      ghj $$40 = gfb.b(new ghh(0.5F));
      ghj $$41 = gfr.a();
      ghj $$42 = gfq.a();
      ghj $$43 = gga.a();
      ghj $$44 = ggk.a();
      ghj $$45 = ghj.a(ggs.a(ghh.a), 64, 32);
      ghj $$46 = ghj.a(ggs.a(new ghh(0.2F)), 64, 32);
      ghj $$47 = ggu.a();
      ghj $$48 = gcu.a();
      ghj $$49 = gct.a(c);
      ghj $$50 = gct.a(b);
      ghj $$51 = gdv.a(ghh.a);
      ghj $$52 = gdv.a(new ghh(0.25F));
      ghj $$53 = gge.a();
      ghj $$54 = gdt.a();
      ghj $$55 = gfp.a();
      $$0.put(ghc.c, gcp.a());
      $$0.put(ghc.d, $$32);
      $$0.put(ghc.e, $$32.a(gcr.a));
      $$0.put(ghc.f, $$48);
      $$0.put(ghc.g, $$49);
      $$0.put(ghc.h, $$50);
      $$0.put(ghc.i, $$48.a(geo.i));
      $$0.put(ghc.j, $$49.a(geo.i));
      $$0.put(ghc.k, $$50.a(geo.i));
      $$0.put(ghc.l, gcv.a());
      $$0.put(ghc.m, $$13);
      $$0.put(ghc.n, $$13.a(gcw.b));
      $$0.put(ghc.q, gcz.a(true));
      $$0.put(ghc.s, gcz.a(false));
      $$0.put(ghc.r, gcy.a(true));
      $$0.put(ghc.t, gcy.a(false));
      $$0.put(ghc.u, gda.a());
      $$0.put(ghc.v, gqh.c());
      $$0.put(ghc.w, gqh.b());
      $$0.put(ghc.x, $$14);
      $$0.put(ghc.y, $$14.a(gdb.a));
      $$0.put(ghc.z, gdc.a());
      $$0.put(ghc.A, gdd.a());
      $$0.put(ghc.D, gde.a());
      $$0.put(ghc.E, gdf.c());
      $$0.put(ghc.F, gdg.a());
      $$0.put(ghc.G, $$4);
      $$0.put(ghc.H, $$2);
      $$0.put(ghc.I, ghj.a(geo.a(new ghh(0.2F), 0.0F), 64, 32));
      $$0.put(ghc.J, gdh.a());
      $$0.put(ghc.K, gdi.a(32, 32));
      $$0.put(ghc.L, gdi.a(128, 128));
      $$0.put(ghc.Q, $$18.a(gdl.a));
      $$0.put(ghc.R, $$19.a(gdl.a));
      $$0.put(ghc.T, $$20.a(gdl.a));
      $$0.put(ghc.S, $$20.a(ged.b).a(gdl.a));
      $$0.put(ghc.M, $$33);
      $$0.put(ghc.N, $$33.a(gdj.a));
      $$0.put(ghc.O, $$34);
      $$0.put(ghc.P, $$34.a(gdj.a));
      $$0.put(ghc.U, $$31.a(ghm.scaling(0.7F)));
      $$0.put(ghc.X, gdm.a());
      $$0.put(ghc.Y, $$5);
      $$0.put(ghc.Z, $$35);
      $$0.put(ghc.aa, $$35.a(gdn.b));
      $$0.put(ghc.ab, gdo.a());
      $$0.put(ghc.ac, $$39);
      $$0.put(ghc.ad, $$39.a(gfb.a));
      $$0.put(ghc.ae, $$5);
      $$0.put(ghc.ag, gqs.b());
      $$0.put(ghc.ai, gqs.c());
      $$0.put(ghc.ah, gqs.d());
      $$0.put(ghc.af, gqs.e());
      $$0.put(ghc.aj, $$15);
      $$0.put(ghc.ak, $$16);
      $$0.put(ghc.al, gdr.a());
      $$0.put(ghc.am, gds.a(ghh.a));
      $$0.put(ghc.an, gds.a(new ghh(2.0F)));
      $$0.put(ghc.ao, $$6);
      $$0.put(ghc.ar, gqt.b());
      $$0.put(ghc.as, gqt.c());
      $$0.put(ghc.at, $$54);
      $$0.put(ghc.au, $$54.a(gdt.a));
      $$0.put(ghc.av, gdu.a(0.87F));
      $$0.put(ghc.aw, gdu.b(0.87F));
      $$0.put(ghc.ax, gdu.a(0.87F, false));
      $$0.put(ghc.ay, gdu.a(0.87F, true));
      $$0.put(ghc.az, gdm.c());
      $$0.put(ghc.aA, gdm.b());
      $$0.put(ghc.aB, ggw.a());
      $$0.put(ghc.aC, $$51);
      $$0.put(ghc.aH, $$4);
      $$0.put(ghc.aI, $$4);
      $$0.put(ghc.aJ, $$52);
      $$0.put(ghc.aD, $$51.a(geo.i));
      $$0.put(ghc.aE, $$4.a(geo.i));
      $$0.put(ghc.aF, $$4.a(geo.i));
      $$0.put(ghc.aG, $$52.a(geo.i));
      $$0.put(ghc.aK, gej.b());
      $$0.put(ghc.aL, $$17);
      $$0.put(ghc.aM, $$17.a(gdw.a));
      $$0.put(ghc.aN, gdy.a());
      $$0.put(ghc.aO, gdz.a());
      $$0.put(ghc.aP, ggx.a());
      $$0.put(ghc.aQ, gdx.a());
      $$0.put(ghc.aR, $$12);
      $$0.put(ghc.aS, gec.a());
      $$0.put(ghc.aT, gee.a());
      $$0.put(ghc.aU, gee.a().a(gee.a));
      $$0.put(ghc.aV, gef.a());
      $$0.put(ghc.aW, $$5);
      $$0.put(ghc.aX, geg.a());
      ghm $$56 = ghm.scaling(6.0F);
      $$0.put(ghc.aY, $$1.a($$56));
      $$0.put(ghc.aZ, $$4.a($$56));
      $$0.put(ghc.ba, $$2.a($$56));
      $$0.put(ghc.bb, $$53);
      $$0.put(ghc.bc, $$53.a(gge.a));
      $$0.put(ghc.bd, $$36);
      $$0.put(ghc.be, $$36.a(gei.a));
      $$0.put(ghc.bf, gej.a());
      $$0.put(ghc.bg, $$27);
      $$0.put(ghc.bh, $$28);
      $$0.put(ghc.bi, $$5);
      ghm $$57 = ghm.scaling(1.1F);
      $$0.put(ghc.bj, $$7.a($$57));
      $$0.put(ghc.bm, $$8.a($$57));
      $$0.put(ghc.bk, ghj.a(gcl.a(new ghh(0.1F)), 64, 64).a($$57));
      $$0.put(ghc.bn, ghj.a(gcl.b(new ghh(0.1F)), 64, 64).a($$57));
      $$0.put(ghc.bl, $$9.a($$57));
      $$0.put(ghc.bo, $$10.a($$57));
      ghm $$58 = ghm.scaling(1.0625F);
      $$0.put(ghc.bp, $$1.a($$58));
      $$0.put(ghc.bt, $$4.a($$58));
      $$0.put(ghc.bu, $$2.a($$58));
      $$0.put(ghc.bq, $$1.a(geo.i).a($$58));
      $$0.put(ghc.br, $$4.a(geo.i).a($$58));
      $$0.put(ghc.bs, $$2.a(geo.i).a($$58));
      $$0.put(ghc.bv, $$12);
      $$0.put(ghc.bw, geq.a());
      $$0.put(ghc.bz, ges.a());
      $$0.put(ghc.bA, $$24);
      $$0.put(ghc.bB, $$24.a(get.a));
      $$0.put(ghc.bD, $$25);
      $$0.put(ghc.bC, $$25.a(get.a));
      $$0.put(ghc.bE, geu.a());
      $$0.put(ghc.bF, ger.a());
      $$0.put(ghc.bI, $$5);
      $$0.put(ghc.bJ, $$15);
      $$0.put(ghc.bK, $$16);
      $$0.put(ghc.bL, gdu.a(0.92F));
      $$0.put(ghc.bM, gdu.b(0.92F));
      $$0.put(ghc.bN, gdu.a(0.92F, false));
      $$0.put(ghc.bO, gdu.a(0.92F, true));
      $$0.put(ghc.bR, $$18);
      $$0.put(ghc.bS, $$19);
      $$0.put(ghc.bV, $$37);
      $$0.put(ghc.bW, $$37.a(gey.a));
      $$0.put(ghc.bX, gez.a());
      $$0.put(ghc.bY, gfa.a());
      $$0.put(ghc.bZ, $$38);
      $$0.put(ghc.ck, $$38.a(gfb.a));
      $$0.put(ghc.cm, $$40);
      $$0.put(ghc.cl, $$40.a(gfb.a));
      $$0.put(ghc.ca, $$21);
      $$0.put(ghc.ci, $$4);
      $$0.put(ghc.cj, $$3);
      $$0.put(ghc.ce, $$21);
      $$0.put(ghc.cf, $$4);
      $$0.put(ghc.cg, $$3);
      $$0.put(ghc.cb, $$21.a(geo.i));
      $$0.put(ghc.cc, $$4.a(geo.i));
      $$0.put(ghc.cd, $$3.a(geo.i));
      $$0.put(ghc.ch, $$22);
      $$0.put(ghc.cn, $$12);
      $$0.put(ghc.co, ghj.a(gfg.a(ghh.a, false), 64, 64));
      $$0.put(ghc.cq, gff.a());
      $$0.put(ghc.cp, gfe.a());
      $$0.put(ghc.cr, $$23);
      $$0.put(ghc.cs, $$4);
      $$0.put(ghc.ct, $$2);
      $$0.put(ghc.cu, ghj.a(gfg.a(ghh.a, true), 64, 64));
      $$0.put(ghc.cv, $$4);
      $$0.put(ghc.cw, $$2);
      $$0.put(ghc.cx, ggd.a());
      $$0.put(ghc.cy, gfh.a(false));
      $$0.put(ghc.cz, gfh.a(true));
      $$0.put(ghc.cA, gfi.a());
      $$0.put(ghc.cB, gfj.a());
      $$0.put(ghc.cC, gfk.a());
      $$0.put(ghc.cD, gfm.a(false));
      $$0.put(ghc.cE, gfm.a(true));
      $$0.put(ghc.cF, gfo.a());
      $$0.put(ghc.cG, $$55);
      $$0.put(ghc.cI, $$55.a(gfp.a));
      $$0.put(ghc.cH, $$55.a(gfp.b));
      $$0.put(ghc.cJ, $$41);
      $$0.put(ghc.cK, $$41.a(gfr.a));
      $$0.put(ghc.cM, $$42);
      $$0.put(ghc.cL, $$42.a(gfr.a));
      $$0.put(ghc.cN, gfs.a());
      $$0.put(ghc.cO, gfu.a());
      $$0.put(ghc.cP, gfu.b());
      $$0.put(ghc.cQ, gft.a());
      $$0.put(ghc.cR, gfv.a());
      $$0.put(ghc.cS, $$29);
      $$0.put(ghc.cX, $$4);
      $$0.put(ghc.cY, $$2);
      $$0.put(ghc.cT, $$7);
      $$0.put(ghc.cU, $$8);
      $$0.put(ghc.cV, $$9);
      $$0.put(ghc.cW, $$10);
      $$0.put(ghc.cZ, $$6);
      $$0.put(ghc.da, gfz.b());
      $$0.put(ghc.db, gfz.a());
      $$0.put(ghc.dc, $$43);
      $$0.put(ghc.dd, $$43.a(gga.a));
      $$0.put(ghc.de, ggb.a());
      $$0.put(ghc.df, $$5);
      $$0.put(ghc.dg, $$31);
      $$0.put(ghc.dj, $$53);
      $$0.put(ghc.dk, $$53.a(gge.a));
      $$0.put(ghc.dl, $$29);
      $$0.put(ghc.dm, $$4);
      $$0.put(ghc.dn, $$2);
      $$0.put(ghc.do, ghj.a(geo.a(new ghh(0.25F), 0.0F), 64, 32));
      $$0.put(ghc.dp, $$26);
      $$0.put(ghc.dq, $$26);
      $$0.put(ghc.dr, $$26.a(ggf.a));
      $$0.put(ghc.ds, $$26.a(ggf.a));
      $$0.put(ghc.dt, ggg.a());
      $$0.put(ghc.du, $$5);
      $$0.put(ghc.dv, $$24);
      $$0.put(ghc.dw, $$24.a(get.a));
      $$0.put(ghc.dx, ggh.a());
      $$0.put(ghc.dy, ggj.a(ghh.a));
      $$0.put(ghc.dz, ggj.a(a));
      $$0.put(ghc.dA, ggi.a(ghh.a));
      $$0.put(ghc.dB, ggi.a(a));
      $$0.put(ghc.dC, $$44);
      $$0.put(ghc.dD, $$44.a(ggk.a));
      $$0.put(ghc.dE, ggl.a());
      $$0.put(ghc.dF, $$30);
      $$0.put(ghc.dG, $$30.a(ggn.a));
      $$0.put(ghc.dH, $$12);
      $$0.put(ghc.dJ, ggo.a());
      $$0.put(ghc.dI, $$30);
      $$0.put(ghc.dK, ggp.a());
      $$0.put(ghc.dL, ggq.a().a($$11));
      $$0.put(ghc.dM, ggr.a(ghh.a));
      $$0.put(ghc.dN, ggr.a(c));
      $$0.put(ghc.dS, gxj.a());
      ghm $$59 = ghm.scaling(1.2F);
      $$0.put(ghc.dO, $$29.a($$59));
      $$0.put(ghc.dP, $$4.a($$59));
      $$0.put(ghc.dQ, $$2.a($$59));
      $$0.put(ghc.dR, $$6);
      $$0.put(ghc.dT, $$45);
      $$0.put(ghc.dU, $$46);
      $$0.put(ghc.dV, $$45.a(ggs.a));
      $$0.put(ghc.dW, $$46.a(ggs.a));
      $$0.put(ghc.dX, $$27);
      $$0.put(ghc.dY, $$28);
      $$0.put(ghc.dZ, $$1);
      $$0.put(ghc.ei, $$4);
      $$0.put(ghc.ej, $$2);
      $$0.put(ghc.ea, $$1.a(geo.i));
      $$0.put(ghc.eb, $$4.a(geo.i));
      $$0.put(ghc.ec, $$2.a(geo.i));
      $$0.put(ghc.ed, $$23);
      $$0.put(ghc.ee, $$7);
      $$0.put(ghc.ef, $$8);
      $$0.put(ghc.eg, $$9);
      $$0.put(ghc.eh, $$10);
      $$0.put(ghc.ek, $$47);
      $$0.put(ghc.eo, ggu.a(c));
      $$0.put(ghc.ep, ggu.a(b));
      $$0.put(ghc.el, $$47.a(geo.i));
      $$0.put(ghc.em, ggu.a(c).a(geo.i));
      $$0.put(ghc.en, ggu.a(b).a(geo.i));
      $$0.put(ghc.eq, $$21);
      $$0.put(ghc.eu, $$4);
      $$0.put(ghc.ev, $$3);
      $$0.put(ghc.er, $$21.a(geo.i));
      $$0.put(ghc.es, $$4.a(geo.i));
      $$0.put(ghc.et, $$3.a(geo.i));
      $$0.put(ghc.p, gfn.a());
      $$0.put(ghc.o, gfn.b());
      ghj $$60 = gdf.a();
      ghj $$61 = gdf.b();
      $$0.put(ghc.bP, $$60);
      $$0.put(ghc.bQ, $$61);
      $$0.put(ghc.dh, $$60);
      $$0.put(ghc.di, $$61);
      $$0.put(ghc.B, $$60);
      $$0.put(ghc.C, $$61);
      $$0.put(ghc.bx, $$60);
      $$0.put(ghc.by, $$61);
      $$0.put(ghc.a, $$60);
      $$0.put(ghc.b, $$61);
      $$0.put(ghc.V, $$60);
      $$0.put(ghc.W, $$61);
      $$0.put(ghc.ap, $$60);
      $$0.put(ghc.aq, $$61);
      $$0.put(ghc.bT, $$60);
      $$0.put(ghc.bU, $$61);
      $$0.put(ghc.bG, $$60);
      $$0.put(ghc.bH, $$61);
      ghj $$62 = gqz.a(true);
      ghj $$63 = gqz.a(false);
      eaa.a().forEach($$3x -> {
         $$0.put(ghc.a($$3x), $$62);
         $$0.put(ghc.b($$3x), $$63);

         for (gqv.a $$4x : gqv.a.values()) {
            ghj $$5x = gqv.a($$4x);
            $$0.put(ghc.a($$3x, $$4x), $$5x);
         }
      });
      ImmutableMap<ghb, ghj> $$64 = $$0.build();
      List<ghb> $$65 = ghc.a().filter($$1x -> !$$64.containsKey($$1x)).collect(Collectors.toList());
      if (!$$65.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$65);
      } else {
         return $$64;
      }
   }
}
