import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gir {
   private static final giy a = new giy(0.008F);
   private static final giy b = new giy(1.0F);
   private static final giy c = new giy(0.5F);

   public static Map<gis, gja> a() {
      Builder<gis, gja> $$0 = ImmutableMap.builder();
      gja $$1 = gja.a(gge.a(giy.a, 0.0F), 64, 64);
      gja $$2 = gja.a(ggd.a(b), 64, 32);
      gja $$3 = gja.a(ggd.a(new giy(1.02F)), 64, 32);
      gja $$4 = gja.a(ggd.a(c), 64, 32);
      gja $$5 = ggl.a();
      gja $$6 = ghn.c();
      gja $$7 = gja.a(gea.a(giy.a), 64, 64);
      gja $$8 = gja.a(gea.b(giy.a), 64, 64);
      gja $$9 = gfr.a(false);
      gja $$10 = gfr.a(true);
      gjd $$11 = gjd.scaling(0.9375F);
      gja $$12 = ggf.a().a($$11);
      gja $$13 = gel.a();
      gja $$14 = geq.a();
      gja $$15 = gfg.b();
      gja $$16 = gfe.a();
      gja $$17 = gff.a(giy.a);
      gja $$18 = gfm.a();
      gja $$19 = gja.a(gft.a(giy.a), 64, 32);
      gja $$20 = $$19.a(gft.b);
      gja $$21 = gja.a(gft.a(new giy(0.01F)), 64, 32);
      gja $$22 = gja.a(ggt.a(giy.a), 64, 64);
      gja $$23 = gja.a(ggs.a(), 64, 64);
      gja $$24 = ghn.b();
      gja $$25 = ggj.a(giy.a);
      gja $$26 = ggj.a(new giy(0.5F));
      gja $$27 = ghv.a();
      gja $$28 = ggb.a();
      gja $$29 = ggb.b();
      gja $$30 = ghm.c();
      gja $$31 = gja.a(gid.a(), 64, 64).a($$11);
      gja $$32 = ghs.a();
      gja $$33 = geg.a();
      gja $$34 = gey.a();
      gja $$35 = gez.c();
      gja $$36 = gfc.a();
      gja $$37 = gfy.a();
      gja $$38 = ggo.a();
      gja $$39 = ggr.b(giy.a);
      gja $$40 = ggr.b(new giy(0.5F));
      gja $$41 = ghh.a();
      gja $$42 = ghg.a();
      gja $$43 = ghq.a();
      gja $$44 = gia.a();
      gja $$45 = gif.a();
      gja $$46 = gja.a(gij.a(giy.a), 64, 32);
      gja $$47 = gja.a(gij.a(new giy(0.2F)), 64, 32);
      gja $$48 = gil.a();
      gja $$49 = gej.a();
      gja $$50 = gei.a(c);
      gja $$51 = gei.a(b);
      gja $$52 = gfl.a(giy.a);
      gja $$53 = gfl.a(new giy(0.25F));
      gja $$54 = ghu.a();
      gja $$55 = gfj.a();
      gja $$56 = ghf.a();
      $$0.put(git.c, gee.a());
      $$0.put(git.d, $$33);
      $$0.put(git.e, $$33.a(geg.a));
      $$0.put(git.f, $$49);
      $$0.put(git.g, $$50);
      $$0.put(git.h, $$51);
      $$0.put(git.i, $$49.a(gge.i));
      $$0.put(git.j, $$50.a(gge.i));
      $$0.put(git.k, $$51.a(gge.i));
      $$0.put(git.l, gek.a());
      $$0.put(git.m, $$13);
      $$0.put(git.n, $$13.a(gel.b));
      $$0.put(git.q, geo.a(true));
      $$0.put(git.s, geo.a(false));
      $$0.put(git.r, gen.a(true));
      $$0.put(git.t, gen.a(false));
      $$0.put(git.u, gep.a());
      $$0.put(git.v, gsb.c());
      $$0.put(git.w, gsb.b());
      $$0.put(git.x, $$14);
      $$0.put(git.y, $$14.a(geq.a));
      $$0.put(git.z, ger.a());
      $$0.put(git.A, ges.a());
      $$0.put(git.D, get.a());
      $$0.put(git.E, geu.c());
      $$0.put(git.F, gev.a());
      $$0.put(git.G, $$4);
      $$0.put(git.H, $$2);
      $$0.put(git.I, gja.a(gge.a(new giy(0.2F), 0.0F), 64, 32));
      $$0.put(git.J, gew.a());
      $$0.put(git.K, gex.a(32, 32));
      $$0.put(git.L, gex.a(128, 128));
      $$0.put(git.Q, $$19.a(gfa.a));
      $$0.put(git.R, $$20.a(gfa.a));
      $$0.put(git.T, $$21.a(gfa.a));
      $$0.put(git.S, $$21.a(gft.b).a(gfa.a));
      $$0.put(git.M, $$34);
      $$0.put(git.N, $$34.a(gey.a));
      $$0.put(git.O, $$35);
      $$0.put(git.P, $$35.a(gey.a));
      $$0.put(git.U, $$32.a(gjd.scaling(0.7F)));
      $$0.put(git.X, gfb.a());
      $$0.put(git.Y, $$5);
      $$0.put(git.Z, $$36);
      $$0.put(git.aa, $$36.a(gfc.b));
      $$0.put(git.ab, gfd.a());
      $$0.put(git.ac, $$16);
      $$0.put(git.ad, $$16.a(gfg.a));
      $$0.put(git.ae, $$17);
      $$0.put(git.af, $$17.a(ggr.a));
      $$0.put(git.ag, $$5);
      $$0.put(git.ai, gsm.b());
      $$0.put(git.ak, gsm.c());
      $$0.put(git.aj, gsm.d());
      $$0.put(git.ah, gsm.e());
      $$0.put(git.al, $$15);
      $$0.put(git.am, $$15.a(gfg.a));
      $$0.put(git.an, gfh.a());
      $$0.put(git.ao, gfi.a(giy.a));
      $$0.put(git.ap, gfi.a(new giy(2.0F)));
      $$0.put(git.aq, $$6);
      $$0.put(git.at, gsn.b());
      $$0.put(git.au, gsn.c());
      $$0.put(git.av, $$55);
      $$0.put(git.aw, $$55.a(gfj.a));
      $$0.put(git.ax, gfk.a(0.87F));
      $$0.put(git.ay, gfk.b(0.87F));
      $$0.put(git.az, gfk.a(0.87F, false));
      $$0.put(git.aA, gfk.a(0.87F, true));
      $$0.put(git.aB, gfb.c());
      $$0.put(git.aC, gfb.b());
      $$0.put(git.aD, gin.a());
      $$0.put(git.aE, $$52);
      $$0.put(git.aJ, $$4);
      $$0.put(git.aK, $$4);
      $$0.put(git.aL, $$53);
      $$0.put(git.aF, $$52.a(gge.i));
      $$0.put(git.aG, $$4.a(gge.i));
      $$0.put(git.aH, $$4.a(gge.i));
      $$0.put(git.aI, $$53.a(gge.i));
      $$0.put(git.aM, gfz.b());
      $$0.put(git.aN, $$18);
      $$0.put(git.aO, $$18.a(gfm.a));
      $$0.put(git.aP, gfo.a());
      $$0.put(git.aQ, gfp.a());
      $$0.put(git.aR, gio.a());
      $$0.put(git.aS, gfn.a());
      $$0.put(git.aT, $$12);
      $$0.put(git.aU, gfs.a());
      $$0.put(git.aV, gfu.a());
      $$0.put(git.aW, gfu.a().a(gfu.a));
      $$0.put(git.aX, gfv.a());
      $$0.put(git.aY, $$5);
      $$0.put(git.aZ, gfw.a());
      gjd $$57 = gjd.scaling(6.0F);
      $$0.put(git.ba, $$1.a($$57));
      $$0.put(git.bb, $$4.a($$57));
      $$0.put(git.bc, $$2.a($$57));
      $$0.put(git.bd, $$54);
      $$0.put(git.be, $$54.a(ghu.a));
      $$0.put(git.bf, $$37);
      $$0.put(git.bg, $$37.a(gfy.a));
      $$0.put(git.bh, gfz.a());
      $$0.put(git.bi, $$28);
      $$0.put(git.bj, $$29);
      $$0.put(git.bk, $$5);
      gjd $$58 = gjd.scaling(1.1F);
      $$0.put(git.bl, $$7.a($$58));
      $$0.put(git.bo, $$8.a($$58));
      $$0.put(git.bm, gja.a(gea.a(new giy(0.1F)), 64, 64).a($$58));
      $$0.put(git.bp, gja.a(gea.b(new giy(0.1F)), 64, 64).a($$58));
      $$0.put(git.bn, $$9.a($$58));
      $$0.put(git.bq, $$10.a($$58));
      gjd $$59 = gjd.scaling(1.0625F);
      $$0.put(git.br, $$1.a($$59));
      $$0.put(git.bv, $$4.a($$59));
      $$0.put(git.bw, $$2.a($$59));
      $$0.put(git.bs, $$1.a(gge.i).a($$59));
      $$0.put(git.bt, $$4.a(gge.i).a($$59));
      $$0.put(git.bu, $$2.a(gge.i).a($$59));
      $$0.put(git.bx, $$12);
      $$0.put(git.by, ggg.a());
      $$0.put(git.bB, ggi.a());
      $$0.put(git.bC, $$25);
      $$0.put(git.bD, $$25.a(ggj.a));
      $$0.put(git.bF, $$26);
      $$0.put(git.bE, $$26.a(ggj.a));
      $$0.put(git.bG, ggk.a());
      $$0.put(git.bH, ggh.a());
      $$0.put(git.bK, $$5);
      $$0.put(git.bL, $$15);
      $$0.put(git.bM, $$15.a(gfg.a));
      $$0.put(git.bN, gfk.a(0.92F));
      $$0.put(git.bO, gfk.b(0.92F));
      $$0.put(git.bP, gfk.a(0.92F, false));
      $$0.put(git.bQ, gfk.a(0.92F, true));
      $$0.put(git.bT, $$19);
      $$0.put(git.bU, $$20);
      $$0.put(git.bX, $$38);
      $$0.put(git.bY, $$38.a(ggo.a));
      $$0.put(git.bZ, ggp.a());
      $$0.put(git.ca, ggq.a());
      $$0.put(git.cb, $$39);
      $$0.put(git.cm, $$39.a(ggr.a));
      $$0.put(git.co, $$40);
      $$0.put(git.cn, $$40.a(ggr.a));
      $$0.put(git.cc, $$22);
      $$0.put(git.ck, $$4);
      $$0.put(git.cl, $$3);
      $$0.put(git.cg, $$22);
      $$0.put(git.ch, $$4);
      $$0.put(git.ci, $$3);
      $$0.put(git.cd, $$22.a(gge.i));
      $$0.put(git.ce, $$4.a(gge.i));
      $$0.put(git.cf, $$3.a(gge.i));
      $$0.put(git.cj, $$23);
      $$0.put(git.cp, $$12);
      $$0.put(git.cq, gja.a(ggw.a(giy.a, false), 64, 64));
      $$0.put(git.cs, ggv.a());
      $$0.put(git.cr, ggu.a());
      $$0.put(git.ct, $$24);
      $$0.put(git.cu, $$4);
      $$0.put(git.cv, $$2);
      $$0.put(git.cw, gja.a(ggw.a(giy.a, true), 64, 64));
      $$0.put(git.cx, $$4);
      $$0.put(git.cy, $$2);
      $$0.put(git.cz, ght.a());
      $$0.put(git.cA, ggx.a(false));
      $$0.put(git.cB, ggx.a(true));
      $$0.put(git.cC, ggy.a());
      $$0.put(git.cD, ggz.a());
      $$0.put(git.cE, gha.a());
      $$0.put(git.cF, ghc.a(false));
      $$0.put(git.cG, ghc.a(true));
      $$0.put(git.cH, ghe.a());
      $$0.put(git.cI, $$56);
      $$0.put(git.cK, $$56.a(ghf.a));
      $$0.put(git.cJ, $$56.a(ghf.b));
      $$0.put(git.cL, $$41);
      $$0.put(git.cM, $$41.a(ghh.a));
      $$0.put(git.cO, $$42);
      $$0.put(git.cN, $$42.a(ghh.a));
      $$0.put(git.cP, ghi.a());
      $$0.put(git.cQ, ghk.a());
      $$0.put(git.cR, ghk.b());
      $$0.put(git.cS, ghj.a());
      $$0.put(git.cT, ghl.a());
      $$0.put(git.cU, $$30);
      $$0.put(git.cZ, $$4);
      $$0.put(git.da, $$2);
      $$0.put(git.cV, $$7);
      $$0.put(git.cW, $$8);
      $$0.put(git.cX, $$9);
      $$0.put(git.cY, $$10);
      $$0.put(git.db, $$6);
      $$0.put(git.dc, ghp.b());
      $$0.put(git.dd, ghp.a());
      $$0.put(git.de, $$43);
      $$0.put(git.df, $$43.a(ghq.a));
      $$0.put(git.dg, ghr.a());
      $$0.put(git.dh, $$5);
      $$0.put(git.di, $$32);
      $$0.put(git.dl, $$54);
      $$0.put(git.dm, $$54.a(ghu.a));
      $$0.put(git.dn, $$30);
      $$0.put(git.do, $$4);
      $$0.put(git.dp, $$2);
      $$0.put(git.dq, gja.a(gge.a(new giy(0.25F), 0.0F), 64, 32));
      $$0.put(git.dr, $$27);
      $$0.put(git.ds, $$27);
      $$0.put(git.dt, $$27.a(ghv.a));
      $$0.put(git.du, $$27.a(ghv.a));
      $$0.put(git.dv, ghw.a());
      $$0.put(git.dw, $$5);
      $$0.put(git.dx, $$25);
      $$0.put(git.dy, $$25.a(ggj.a));
      $$0.put(git.dz, ghx.a());
      $$0.put(git.dA, ghz.a(giy.a));
      $$0.put(git.dB, ghz.a(a));
      $$0.put(git.dC, ghy.a(giy.a));
      $$0.put(git.dD, ghy.a(a));
      $$0.put(git.dE, $$44);
      $$0.put(git.dF, $$44.a(gia.a));
      $$0.put(git.dG, gib.a());
      $$0.put(git.dH, $$31);
      $$0.put(git.dI, $$31.a(gid.a));
      $$0.put(git.dJ, $$12);
      $$0.put(git.dL, gie.a());
      $$0.put(git.dM, $$45);
      $$0.put(git.dN, $$45.a(gfg.a));
      $$0.put(git.dK, $$31);
      $$0.put(git.dO, gig.a());
      $$0.put(git.dP, gih.a().a($$11));
      $$0.put(git.dQ, gii.a(giy.a));
      $$0.put(git.dR, gii.a(c));
      $$0.put(git.dW, gzd.a());
      gjd $$60 = gjd.scaling(1.2F);
      $$0.put(git.dS, $$30.a($$60));
      $$0.put(git.dT, $$4.a($$60));
      $$0.put(git.dU, $$2.a($$60));
      $$0.put(git.dV, $$6);
      $$0.put(git.dX, $$46);
      $$0.put(git.dY, $$47);
      $$0.put(git.dZ, $$46.a(gij.a));
      $$0.put(git.ea, $$47.a(gij.a));
      $$0.put(git.eb, $$28);
      $$0.put(git.ec, $$29);
      $$0.put(git.ed, $$1);
      $$0.put(git.em, $$4);
      $$0.put(git.en, $$2);
      $$0.put(git.ee, $$1.a(gge.i));
      $$0.put(git.ef, $$4.a(gge.i));
      $$0.put(git.eg, $$2.a(gge.i));
      $$0.put(git.eh, $$24);
      $$0.put(git.ei, $$7);
      $$0.put(git.ej, $$8);
      $$0.put(git.ek, $$9);
      $$0.put(git.el, $$10);
      $$0.put(git.eo, $$48);
      $$0.put(git.es, gil.a(c));
      $$0.put(git.et, gil.a(b));
      $$0.put(git.ep, $$48.a(gge.i));
      $$0.put(git.eq, gil.a(c).a(gge.i));
      $$0.put(git.er, gil.a(b).a(gge.i));
      $$0.put(git.eu, $$22);
      $$0.put(git.ey, $$4);
      $$0.put(git.ez, $$3);
      $$0.put(git.ev, $$22.a(gge.i));
      $$0.put(git.ew, $$4.a(gge.i));
      $$0.put(git.ex, $$3.a(gge.i));
      $$0.put(git.p, ghd.a());
      $$0.put(git.o, ghd.b());
      gja $$61 = geu.a();
      gja $$62 = geu.b();
      $$0.put(git.bR, $$61);
      $$0.put(git.bS, $$62);
      $$0.put(git.dj, $$61);
      $$0.put(git.dk, $$62);
      $$0.put(git.B, $$61);
      $$0.put(git.C, $$62);
      $$0.put(git.bz, $$61);
      $$0.put(git.bA, $$62);
      $$0.put(git.a, $$61);
      $$0.put(git.b, $$62);
      $$0.put(git.V, $$61);
      $$0.put(git.W, $$62);
      $$0.put(git.ar, $$61);
      $$0.put(git.as, $$62);
      $$0.put(git.bV, $$61);
      $$0.put(git.bW, $$62);
      $$0.put(git.bI, $$61);
      $$0.put(git.bJ, $$62);
      gja $$63 = gst.a(true);
      gja $$64 = gst.a(false);
      ebn.a().forEach($$3x -> {
         $$0.put(git.a($$3x), $$63);
         $$0.put(git.b($$3x), $$64);

         for (gsp.a $$4x : gsp.a.values()) {
            gja $$5x = gsp.a($$4x);
            $$0.put(git.a($$3x, $$4x), $$5x);
         }
      });
      ImmutableMap<gis, gja> $$65 = $$0.build();
      List<gis> $$66 = git.a().filter($$1x -> !$$65.containsKey($$1x)).collect(Collectors.toList());
      if (!$$66.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$66);
      } else {
         return $$65;
      }
   }
}
