import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gjl {
   private static final gjs a = new gjs(0.008F);
   private static final gjs b = new gjs(1.0F);
   private static final gjs c = new gjs(0.5F);

   public static Map<gjm, gju> a() {
      Builder<gjm, gju> $$0 = ImmutableMap.builder();
      gju $$1 = gju.a(ggy.a(gjs.a, 0.0F), 64, 64);
      gju $$2 = gju.a(ggx.a(b), 64, 32);
      gju $$3 = gju.a(ggx.a(new gjs(1.02F)), 64, 32);
      gju $$4 = gju.a(ggx.a(c), 64, 32);
      gju $$5 = ghf.a();
      gju $$6 = gih.c();
      gju $$7 = gju.a(get.a(gjs.a), 64, 64);
      gju $$8 = gju.a(get.b(gjs.a), 64, 64);
      gju $$9 = ggl.a(false);
      gju $$10 = ggl.a(true);
      gjx $$11 = gjx.scaling(0.9375F);
      gju $$12 = ggz.a().a($$11);
      gju $$13 = gfe.a();
      gju $$14 = gfj.a();
      gju $$15 = gga.b();
      gju $$16 = gfx.c();
      gju $$17 = gfy.a();
      gju $$18 = gfz.a(gjs.a);
      gju $$19 = ggg.a();
      gju $$20 = gju.a(ggn.a(gjs.a), 64, 32);
      gju $$21 = $$20.a(ggn.b);
      gju $$22 = gju.a(ggn.a(new gjs(0.01F)), 64, 32);
      gju $$23 = gju.a(ghn.a(gjs.a), 64, 64);
      gju $$24 = gju.a(ghm.a(), 64, 64);
      gju $$25 = gih.b();
      gju $$26 = ghd.a(gjs.a);
      gju $$27 = ghd.a(new gjs(0.5F));
      gju $$28 = gip.a();
      gju $$29 = ggv.a();
      gju $$30 = ggv.b();
      gju $$31 = gig.c();
      gju $$32 = gju.a(gix.a(), 64, 64).a($$11);
      gju $$33 = gim.a();
      gju $$34 = gez.a();
      gju $$35 = gfr.a();
      gju $$36 = gfs.c();
      gju $$37 = gfv.a();
      gju $$38 = ggs.a();
      gju $$39 = ghi.a();
      gju $$40 = ghl.b(gjs.a);
      gju $$41 = ghl.b(new gjs(0.5F));
      gju $$42 = gib.a();
      gju $$43 = gia.a();
      gju $$44 = gik.a();
      gju $$45 = giu.a();
      gju $$46 = giz.a();
      gju $$47 = gju.a(gjd.a(gjs.a), 64, 32);
      gju $$48 = gju.a(gjd.a(new gjs(0.2F)), 64, 32);
      gju $$49 = gjf.a();
      gju $$50 = gfc.a();
      gju $$51 = gfb.a(c);
      gju $$52 = gfb.a(b);
      gju $$53 = ggf.a(gjs.a);
      gju $$54 = ggf.a(new gjs(0.25F));
      gju $$55 = gio.a();
      gju $$56 = ggd.a();
      gju $$57 = ghz.a();
      $$0.put(gjn.c, gex.a());
      $$0.put(gjn.d, $$34);
      $$0.put(gjn.e, $$34.a(gez.a));
      $$0.put(gjn.f, $$50);
      $$0.put(gjn.g, $$51);
      $$0.put(gjn.h, $$52);
      $$0.put(gjn.i, $$50.a(ggy.i));
      $$0.put(gjn.j, $$51.a(ggy.i));
      $$0.put(gjn.k, $$52.a(ggy.i));
      $$0.put(gjn.l, gfd.a());
      $$0.put(gjn.m, $$13);
      $$0.put(gjn.n, $$13.a(gfe.b));
      $$0.put(gjn.q, gfh.a(true));
      $$0.put(gjn.s, gfh.a(false));
      $$0.put(gjn.r, gfg.a(true));
      $$0.put(gjn.t, gfg.a(false));
      $$0.put(gjn.u, gfi.a());
      $$0.put(gjn.v, gsv.c());
      $$0.put(gjn.w, gsv.b());
      $$0.put(gjn.x, $$14);
      $$0.put(gjn.y, $$14.a(gfj.a));
      $$0.put(gjn.z, gfk.a());
      $$0.put(gjn.A, gfl.a());
      $$0.put(gjn.D, gfm.a());
      $$0.put(gjn.E, gfn.c());
      $$0.put(gjn.F, gfo.a());
      $$0.put(gjn.G, $$4);
      $$0.put(gjn.H, $$2);
      $$0.put(gjn.I, gju.a(ggy.a(new gjs(0.2F), 0.0F), 64, 32));
      $$0.put(gjn.J, gfp.a());
      $$0.put(gjn.K, gfq.a(32, 32));
      $$0.put(gjn.L, gfq.a(128, 128));
      $$0.put(gjn.Q, $$20.a(gft.a));
      $$0.put(gjn.R, $$21.a(gft.a));
      $$0.put(gjn.T, $$22.a(gft.a));
      $$0.put(gjn.S, $$22.a(ggn.b).a(gft.a));
      $$0.put(gjn.M, $$35);
      $$0.put(gjn.N, $$35.a(gfr.a));
      $$0.put(gjn.O, $$36);
      $$0.put(gjn.P, $$36.a(gfr.a));
      $$0.put(gjn.U, $$33.a(gjx.scaling(0.7F)));
      $$0.put(gjn.X, gfu.a());
      $$0.put(gjn.Y, $$5);
      $$0.put(gjn.Z, $$37);
      $$0.put(gjn.aa, $$37.a(gfv.c));
      $$0.put(gjn.ab, gfw.a());
      $$0.put(gjn.ac, $$16);
      $$0.put(gjn.ad, $$16.a(gfv.c));
      $$0.put(gjn.ae, $$17);
      $$0.put(gjn.af, $$17.a(gga.a));
      $$0.put(gjn.ag, $$18);
      $$0.put(gjn.ah, $$18.a(ghl.a));
      $$0.put(gjn.ai, $$5);
      $$0.put(gjn.ak, gtg.b());
      $$0.put(gjn.am, gtg.c());
      $$0.put(gjn.al, gtg.d());
      $$0.put(gjn.aj, gtg.e());
      $$0.put(gjn.an, $$15);
      $$0.put(gjn.ao, $$15.a(gga.a));
      $$0.put(gjn.ap, ggb.a());
      $$0.put(gjn.aq, ggc.a(gjs.a));
      $$0.put(gjn.ar, ggc.a(new gjs(2.0F)));
      $$0.put(gjn.as, $$6);
      $$0.put(gjn.av, gth.b());
      $$0.put(gjn.aw, gth.c());
      $$0.put(gjn.ax, $$56);
      $$0.put(gjn.ay, $$56.a(ggd.a));
      $$0.put(gjn.az, gge.a(0.87F));
      $$0.put(gjn.aA, gge.b(0.87F));
      $$0.put(gjn.aB, gge.a(0.87F, false));
      $$0.put(gjn.aC, gge.a(0.87F, true));
      $$0.put(gjn.aD, gfu.c());
      $$0.put(gjn.aE, gfu.b());
      $$0.put(gjn.aF, gjh.a());
      $$0.put(gjn.aG, $$53);
      $$0.put(gjn.aL, $$4);
      $$0.put(gjn.aM, $$4);
      $$0.put(gjn.aN, $$54);
      $$0.put(gjn.aH, $$53.a(ggy.i));
      $$0.put(gjn.aI, $$4.a(ggy.i));
      $$0.put(gjn.aJ, $$4.a(ggy.i));
      $$0.put(gjn.aK, $$54.a(ggy.i));
      $$0.put(gjn.aO, ggt.b());
      $$0.put(gjn.aP, $$19);
      $$0.put(gjn.aQ, $$19.a(ggg.a));
      $$0.put(gjn.aR, ggi.a());
      $$0.put(gjn.aS, ggj.a());
      $$0.put(gjn.aT, gji.a());
      $$0.put(gjn.aU, ggh.a());
      $$0.put(gjn.aV, $$12);
      $$0.put(gjn.aW, ggm.a());
      $$0.put(gjn.aX, ggo.a());
      $$0.put(gjn.aY, ggo.a().a(ggo.a));
      $$0.put(gjn.aZ, ggp.a());
      $$0.put(gjn.ba, $$5);
      $$0.put(gjn.bb, ggq.a());
      gjx $$58 = gjx.scaling(6.0F);
      $$0.put(gjn.bc, $$1.a($$58));
      $$0.put(gjn.bd, $$4.a($$58));
      $$0.put(gjn.be, $$2.a($$58));
      $$0.put(gjn.bf, $$55);
      $$0.put(gjn.bg, $$55.a(gio.a));
      $$0.put(gjn.bh, $$38);
      $$0.put(gjn.bi, $$38.a(ggs.a));
      $$0.put(gjn.bj, ggt.a());
      $$0.put(gjn.bk, $$29);
      $$0.put(gjn.bl, $$30);
      $$0.put(gjn.bm, $$5);
      gjx $$59 = gjx.scaling(1.1F);
      $$0.put(gjn.bn, $$7.a($$59));
      $$0.put(gjn.bq, $$8.a($$59));
      $$0.put(gjn.bo, gju.a(get.a(new gjs(0.1F)), 64, 64).a($$59));
      $$0.put(gjn.br, gju.a(get.b(new gjs(0.1F)), 64, 64).a($$59));
      $$0.put(gjn.bp, $$9.a($$59));
      $$0.put(gjn.bs, $$10.a($$59));
      gjx $$60 = gjx.scaling(1.0625F);
      $$0.put(gjn.bt, $$1.a($$60));
      $$0.put(gjn.bx, $$4.a($$60));
      $$0.put(gjn.by, $$2.a($$60));
      $$0.put(gjn.bu, $$1.a(ggy.i).a($$60));
      $$0.put(gjn.bv, $$4.a(ggy.i).a($$60));
      $$0.put(gjn.bw, $$2.a(ggy.i).a($$60));
      $$0.put(gjn.bz, $$12);
      $$0.put(gjn.bA, gha.a());
      $$0.put(gjn.bD, ghc.a());
      $$0.put(gjn.bE, $$26);
      $$0.put(gjn.bF, $$26.a(ghd.a));
      $$0.put(gjn.bH, $$27);
      $$0.put(gjn.bG, $$27.a(ghd.a));
      $$0.put(gjn.bI, ghe.a());
      $$0.put(gjn.bJ, ghb.a());
      $$0.put(gjn.bM, $$5);
      $$0.put(gjn.bN, $$15);
      $$0.put(gjn.bO, $$15.a(gga.a));
      $$0.put(gjn.bP, gge.a(0.92F));
      $$0.put(gjn.bQ, gge.b(0.92F));
      $$0.put(gjn.bR, gge.a(0.92F, false));
      $$0.put(gjn.bS, gge.a(0.92F, true));
      $$0.put(gjn.bV, $$20);
      $$0.put(gjn.bW, $$21);
      $$0.put(gjn.bZ, $$39);
      $$0.put(gjn.ca, $$39.a(ghi.a));
      $$0.put(gjn.cb, ghj.a());
      $$0.put(gjn.cc, ghk.a());
      $$0.put(gjn.cd, $$40);
      $$0.put(gjn.co, $$40.a(ghl.a));
      $$0.put(gjn.cq, $$41);
      $$0.put(gjn.cp, $$41.a(ghl.a));
      $$0.put(gjn.ce, $$23);
      $$0.put(gjn.cm, $$4);
      $$0.put(gjn.cn, $$3);
      $$0.put(gjn.ci, $$23);
      $$0.put(gjn.cj, $$4);
      $$0.put(gjn.ck, $$3);
      $$0.put(gjn.cf, $$23.a(ggy.i));
      $$0.put(gjn.cg, $$4.a(ggy.i));
      $$0.put(gjn.ch, $$3.a(ggy.i));
      $$0.put(gjn.cl, $$24);
      $$0.put(gjn.cr, $$12);
      $$0.put(gjn.cs, gju.a(ghq.a(gjs.a, false), 64, 64));
      $$0.put(gjn.cu, ghp.a());
      $$0.put(gjn.ct, gho.a());
      $$0.put(gjn.cv, $$25);
      $$0.put(gjn.cw, $$4);
      $$0.put(gjn.cx, $$2);
      $$0.put(gjn.cy, gju.a(ghq.a(gjs.a, true), 64, 64));
      $$0.put(gjn.cz, $$4);
      $$0.put(gjn.cA, $$2);
      $$0.put(gjn.cB, gin.a());
      $$0.put(gjn.cC, ghr.a(false));
      $$0.put(gjn.cD, ghr.a(true));
      $$0.put(gjn.cE, ghs.a());
      $$0.put(gjn.cF, ght.a());
      $$0.put(gjn.cG, ghu.a());
      $$0.put(gjn.cH, ghw.a(false));
      $$0.put(gjn.cI, ghw.a(true));
      $$0.put(gjn.cJ, ghy.a());
      $$0.put(gjn.cK, $$57);
      $$0.put(gjn.cM, $$57.a(ghz.a));
      $$0.put(gjn.cL, $$57.a(ghz.b));
      $$0.put(gjn.cN, $$42);
      $$0.put(gjn.cO, $$42.a(gib.a));
      $$0.put(gjn.cQ, $$43);
      $$0.put(gjn.cP, $$43.a(gib.a));
      $$0.put(gjn.cR, gic.a());
      $$0.put(gjn.cS, gie.a());
      $$0.put(gjn.cT, gie.b());
      $$0.put(gjn.cU, gid.a());
      $$0.put(gjn.cV, gif.a());
      $$0.put(gjn.cW, $$31);
      $$0.put(gjn.db, $$4);
      $$0.put(gjn.dc, $$2);
      $$0.put(gjn.cX, $$7);
      $$0.put(gjn.cY, $$8);
      $$0.put(gjn.cZ, $$9);
      $$0.put(gjn.da, $$10);
      $$0.put(gjn.dd, $$6);
      $$0.put(gjn.de, gij.b());
      $$0.put(gjn.df, gij.a());
      $$0.put(gjn.dg, $$44);
      $$0.put(gjn.dh, $$44.a(gik.a));
      $$0.put(gjn.di, gil.a());
      $$0.put(gjn.dj, $$5);
      $$0.put(gjn.dk, $$33);
      $$0.put(gjn.dn, $$55);
      $$0.put(gjn.do, $$55.a(gio.a));
      $$0.put(gjn.dp, $$31);
      $$0.put(gjn.dq, $$4);
      $$0.put(gjn.dr, $$2);
      $$0.put(gjn.ds, gju.a(ggy.a(new gjs(0.25F), 0.0F), 64, 32));
      $$0.put(gjn.dt, $$28);
      $$0.put(gjn.du, $$28);
      $$0.put(gjn.dv, $$28.a(gip.a));
      $$0.put(gjn.dw, $$28.a(gip.a));
      $$0.put(gjn.dx, giq.a());
      $$0.put(gjn.dy, $$5);
      $$0.put(gjn.dz, $$26);
      $$0.put(gjn.dA, $$26.a(ghd.a));
      $$0.put(gjn.dB, gir.a());
      $$0.put(gjn.dC, git.a(gjs.a));
      $$0.put(gjn.dD, git.a(a));
      $$0.put(gjn.dE, gis.a(gjs.a));
      $$0.put(gjn.dF, gis.a(a));
      $$0.put(gjn.dG, $$45);
      $$0.put(gjn.dH, $$45.a(giu.a));
      $$0.put(gjn.dI, giv.a());
      $$0.put(gjn.dJ, $$32);
      $$0.put(gjn.dK, $$32.a(gix.a));
      $$0.put(gjn.dL, $$12);
      $$0.put(gjn.dN, giy.a());
      $$0.put(gjn.dO, $$46);
      $$0.put(gjn.dP, $$46.a(gga.a));
      $$0.put(gjn.dM, $$32);
      $$0.put(gjn.dQ, gja.a());
      $$0.put(gjn.dR, gjb.a().a($$11));
      $$0.put(gjn.dS, gjc.a(gjs.a));
      $$0.put(gjn.dT, gjc.a(c));
      $$0.put(gjn.dY, gzx.a());
      gjx $$61 = gjx.scaling(1.2F);
      $$0.put(gjn.dU, $$31.a($$61));
      $$0.put(gjn.dV, $$4.a($$61));
      $$0.put(gjn.dW, $$2.a($$61));
      $$0.put(gjn.dX, $$6);
      $$0.put(gjn.dZ, $$47);
      $$0.put(gjn.ea, $$48);
      $$0.put(gjn.eb, $$47.a(gjd.a));
      $$0.put(gjn.ec, $$48.a(gjd.a));
      $$0.put(gjn.ed, $$29);
      $$0.put(gjn.ee, $$30);
      $$0.put(gjn.ef, $$1);
      $$0.put(gjn.eo, $$4);
      $$0.put(gjn.ep, $$2);
      $$0.put(gjn.eg, $$1.a(ggy.i));
      $$0.put(gjn.eh, $$4.a(ggy.i));
      $$0.put(gjn.ei, $$2.a(ggy.i));
      $$0.put(gjn.ej, $$25);
      $$0.put(gjn.ek, $$7);
      $$0.put(gjn.el, $$8);
      $$0.put(gjn.em, $$9);
      $$0.put(gjn.en, $$10);
      $$0.put(gjn.eq, $$49);
      $$0.put(gjn.eu, gjf.a(c));
      $$0.put(gjn.ev, gjf.a(b));
      $$0.put(gjn.er, $$49.a(ggy.i));
      $$0.put(gjn.es, gjf.a(c).a(ggy.i));
      $$0.put(gjn.et, gjf.a(b).a(ggy.i));
      $$0.put(gjn.ew, $$23);
      $$0.put(gjn.eA, $$4);
      $$0.put(gjn.eB, $$3);
      $$0.put(gjn.ex, $$23.a(ggy.i));
      $$0.put(gjn.ey, $$4.a(ggy.i));
      $$0.put(gjn.ez, $$3.a(ggy.i));
      $$0.put(gjn.p, ghx.a());
      $$0.put(gjn.o, ghx.b());
      gju $$62 = gfn.a();
      gju $$63 = gfn.b();
      $$0.put(gjn.bT, $$62);
      $$0.put(gjn.bU, $$63);
      $$0.put(gjn.dl, $$62);
      $$0.put(gjn.dm, $$63);
      $$0.put(gjn.B, $$62);
      $$0.put(gjn.C, $$63);
      $$0.put(gjn.bB, $$62);
      $$0.put(gjn.bC, $$63);
      $$0.put(gjn.a, $$62);
      $$0.put(gjn.b, $$63);
      $$0.put(gjn.V, $$62);
      $$0.put(gjn.W, $$63);
      $$0.put(gjn.at, $$62);
      $$0.put(gjn.au, $$63);
      $$0.put(gjn.bX, $$62);
      $$0.put(gjn.bY, $$63);
      $$0.put(gjn.bK, $$62);
      $$0.put(gjn.bL, $$63);
      gju $$64 = gtn.a(true);
      gju $$65 = gtn.a(false);
      ecc.a().forEach($$3x -> {
         $$0.put(gjn.a($$3x), $$64);
         $$0.put(gjn.b($$3x), $$65);

         for (gtj.a $$4x : gtj.a.values()) {
            gju $$5x = gtj.a($$4x);
            $$0.put(gjn.a($$3x, $$4x), $$5x);
         }
      });
      ImmutableMap<gjm, gju> $$66 = $$0.build();
      List<gjm> $$67 = gjn.a().filter($$1x -> !$$66.containsKey($$1x)).collect(Collectors.toList());
      if (!$$67.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$67);
      } else {
         return $$66;
      }
   }
}
