import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gko {
   private static final gkv a = new gkv(0.008F);
   private static final gkv b = new gkv(1.0F);
   private static final gkv c = new gkv(0.5F);

   public static Map<gkp, gkx> a() {
      Builder<gkp, gkx> $$0 = ImmutableMap.builder();
      gkx $$1 = gkx.a(gib.a(gkv.a, 0.0F), 64, 64);
      gkx $$2 = gkx.a(gia.a(b), 64, 32);
      gkx $$3 = gkx.a(gia.a(new gkv(1.02F)), 64, 32);
      gkx $$4 = gkx.a(gia.a(c), 64, 32);
      gkx $$5 = gii.a();
      gkx $$6 = gjk.c();
      gkx $$7 = gkx.a(gfw.a(gkv.a), 64, 64);
      gkx $$8 = gkx.a(gfw.b(gkv.a), 64, 64);
      gkx $$9 = gho.a(false);
      gkx $$10 = gho.a(true);
      gla $$11 = gla.scaling(0.9375F);
      gkx $$12 = gic.a().a($$11);
      gkx $$13 = ggh.a();
      gkx $$14 = ggm.a();
      gkx $$15 = ghd.b();
      gkx $$16 = gha.c();
      gkx $$17 = ghb.a();
      gkx $$18 = ghc.a(gkv.a);
      gkx $$19 = ghj.a();
      gkx $$20 = gkx.a(ghq.a(gkv.a), 64, 32);
      gkx $$21 = $$20.a(ghq.b);
      gkx $$22 = gkx.a(ghq.a(new gkv(0.01F)), 64, 32);
      gkx $$23 = gkx.a(giq.a(gkv.a), 64, 64);
      gkx $$24 = gkx.a(gip.a(), 64, 64);
      gkx $$25 = gjk.b();
      gkx $$26 = gig.a(gkv.a);
      gkx $$27 = gig.a(new gkv(0.5F));
      gkx $$28 = gjs.a();
      gkx $$29 = ghy.a();
      gkx $$30 = ghy.b();
      gkx $$31 = gjj.c();
      gkx $$32 = gkx.a(gka.a(), 64, 64).a($$11);
      gkx $$33 = gjp.a();
      gkx $$34 = ggc.a();
      gkx $$35 = ggu.a();
      gkx $$36 = ggv.c();
      gkx $$37 = ggy.a();
      gkx $$38 = ghv.a();
      gkx $$39 = gil.a();
      gkx $$40 = gio.b(gkv.a);
      gkx $$41 = gio.b(new gkv(0.5F));
      gkx $$42 = gje.a();
      gkx $$43 = gjd.a();
      gkx $$44 = gjn.a();
      gkx $$45 = gjx.a();
      gkx $$46 = gkc.a();
      gkx $$47 = gkx.a(gkg.a(gkv.a), 64, 32);
      gkx $$48 = gkx.a(gkg.a(new gkv(0.2F)), 64, 32);
      gkx $$49 = gki.a();
      gkx $$50 = ggf.a();
      gkx $$51 = gge.a(c);
      gkx $$52 = gge.a(b);
      gkx $$53 = ghi.a(gkv.a);
      gkx $$54 = ghi.a(new gkv(0.25F));
      gkx $$55 = gjr.a();
      gkx $$56 = ghg.a();
      gkx $$57 = gjc.a();
      $$0.put(gkq.c, gga.a());
      $$0.put(gkq.d, $$34);
      $$0.put(gkq.e, $$34.a(ggc.a));
      $$0.put(gkq.f, $$50);
      $$0.put(gkq.g, $$51);
      $$0.put(gkq.h, $$52);
      $$0.put(gkq.i, $$50.a(gib.i));
      $$0.put(gkq.j, $$51.a(gib.i));
      $$0.put(gkq.k, $$52.a(gib.i));
      $$0.put(gkq.l, ggg.a());
      $$0.put(gkq.m, $$13);
      $$0.put(gkq.n, $$13.a(ggh.b));
      $$0.put(gkq.q, ggk.a(true));
      $$0.put(gkq.s, ggk.a(false));
      $$0.put(gkq.r, ggj.a(true));
      $$0.put(gkq.t, ggj.a(false));
      $$0.put(gkq.u, ggl.a());
      $$0.put(gkq.v, gtx.c());
      $$0.put(gkq.w, gtx.b());
      $$0.put(gkq.x, $$14);
      $$0.put(gkq.y, $$14.a(ggm.a));
      $$0.put(gkq.z, ggn.a());
      $$0.put(gkq.A, ggo.a());
      $$0.put(gkq.D, ggp.a());
      $$0.put(gkq.E, ggq.c());
      $$0.put(gkq.F, ggr.a());
      $$0.put(gkq.G, $$4);
      $$0.put(gkq.H, $$2);
      $$0.put(gkq.I, gkx.a(gib.a(new gkv(0.2F), 0.0F), 64, 32));
      $$0.put(gkq.J, ggs.a());
      $$0.put(gkq.K, ggt.a(32, 32));
      $$0.put(gkq.L, ggt.a(128, 128));
      $$0.put(gkq.Q, $$20.a(ggw.a));
      $$0.put(gkq.R, $$21.a(ggw.a));
      $$0.put(gkq.T, $$22.a(ggw.a));
      $$0.put(gkq.S, $$22.a(ghq.b).a(ggw.a));
      $$0.put(gkq.M, $$35);
      $$0.put(gkq.N, $$35.a(ggu.a));
      $$0.put(gkq.O, $$36);
      $$0.put(gkq.P, $$36.a(ggu.a));
      $$0.put(gkq.U, $$33.a(gla.scaling(0.7F)));
      $$0.put(gkq.X, ggx.a());
      $$0.put(gkq.Y, $$5);
      $$0.put(gkq.Z, $$37);
      $$0.put(gkq.aa, $$37.a(ggy.c));
      $$0.put(gkq.ab, ggz.a());
      $$0.put(gkq.ac, $$16);
      $$0.put(gkq.ad, $$16.a(ggy.c));
      $$0.put(gkq.ae, $$17);
      $$0.put(gkq.af, $$17.a(ghd.a));
      $$0.put(gkq.ag, $$18);
      $$0.put(gkq.ah, $$18.a(gio.a));
      $$0.put(gkq.ai, $$5);
      $$0.put(gkq.ak, gui.b());
      $$0.put(gkq.am, gui.c());
      $$0.put(gkq.al, gui.d());
      $$0.put(gkq.aj, gui.e());
      $$0.put(gkq.an, $$15);
      $$0.put(gkq.ao, $$15.a(ghd.a));
      $$0.put(gkq.ap, ghe.a());
      $$0.put(gkq.aq, ghf.a(gkv.a));
      $$0.put(gkq.ar, ghf.a(new gkv(2.0F)));
      $$0.put(gkq.as, $$6);
      $$0.put(gkq.av, guj.b());
      $$0.put(gkq.aw, guj.c());
      $$0.put(gkq.ax, $$56);
      $$0.put(gkq.ay, $$56.a(ghg.a));
      $$0.put(gkq.az, ghh.a(0.87F));
      $$0.put(gkq.aA, ghh.b(0.87F));
      $$0.put(gkq.aB, ghh.a(0.87F, false));
      $$0.put(gkq.aC, ghh.a(0.87F, true));
      $$0.put(gkq.aD, ggx.c());
      $$0.put(gkq.aE, ggx.b());
      $$0.put(gkq.aF, gkk.a());
      $$0.put(gkq.aG, $$53);
      $$0.put(gkq.aL, $$4);
      $$0.put(gkq.aM, $$4);
      $$0.put(gkq.aN, $$54);
      $$0.put(gkq.aH, $$53.a(gib.i));
      $$0.put(gkq.aI, $$4.a(gib.i));
      $$0.put(gkq.aJ, $$4.a(gib.i));
      $$0.put(gkq.aK, $$54.a(gib.i));
      $$0.put(gkq.aO, ghw.b());
      $$0.put(gkq.aP, $$19);
      $$0.put(gkq.aQ, $$19.a(ghj.a));
      $$0.put(gkq.aR, ghl.a());
      $$0.put(gkq.aS, ghm.a());
      $$0.put(gkq.aT, gkl.a());
      $$0.put(gkq.aU, ghk.a());
      $$0.put(gkq.aV, $$12);
      $$0.put(gkq.aW, ghp.a());
      $$0.put(gkq.aX, ghr.a());
      $$0.put(gkq.aY, ghr.a().a(ghr.a));
      $$0.put(gkq.aZ, ghs.a());
      $$0.put(gkq.ba, $$5);
      $$0.put(gkq.bb, ght.a());
      gla $$58 = gla.scaling(6.0F);
      $$0.put(gkq.bc, $$1.a($$58));
      $$0.put(gkq.bd, $$4.a($$58));
      $$0.put(gkq.be, $$2.a($$58));
      $$0.put(gkq.bf, $$55);
      $$0.put(gkq.bg, $$55.a(gjr.a));
      $$0.put(gkq.bh, $$38);
      $$0.put(gkq.bi, $$38.a(ghv.a));
      $$0.put(gkq.bj, ghw.a());
      $$0.put(gkq.bk, $$29);
      $$0.put(gkq.bl, $$30);
      $$0.put(gkq.bm, $$5);
      gla $$59 = gla.scaling(1.1F);
      $$0.put(gkq.bn, $$7.a($$59));
      $$0.put(gkq.bq, $$8.a($$59));
      $$0.put(gkq.bo, gkx.a(gfw.a(new gkv(0.1F)), 64, 64).a($$59));
      $$0.put(gkq.br, gkx.a(gfw.b(new gkv(0.1F)), 64, 64).a($$59));
      $$0.put(gkq.bp, $$9.a($$59));
      $$0.put(gkq.bs, $$10.a($$59));
      gla $$60 = gla.scaling(1.0625F);
      $$0.put(gkq.bt, $$1.a($$60));
      $$0.put(gkq.bx, $$4.a($$60));
      $$0.put(gkq.by, $$2.a($$60));
      $$0.put(gkq.bu, $$1.a(gib.i).a($$60));
      $$0.put(gkq.bv, $$4.a(gib.i).a($$60));
      $$0.put(gkq.bw, $$2.a(gib.i).a($$60));
      $$0.put(gkq.bz, $$12);
      $$0.put(gkq.bA, gid.a());
      $$0.put(gkq.bD, gif.a());
      $$0.put(gkq.bE, $$26);
      $$0.put(gkq.bF, $$26.a(gig.a));
      $$0.put(gkq.bH, $$27);
      $$0.put(gkq.bG, $$27.a(gig.a));
      $$0.put(gkq.bI, gih.a());
      $$0.put(gkq.bJ, gie.a());
      $$0.put(gkq.bM, $$5);
      $$0.put(gkq.bN, $$15);
      $$0.put(gkq.bO, $$15.a(ghd.a));
      $$0.put(gkq.bP, ghh.a(0.92F));
      $$0.put(gkq.bQ, ghh.b(0.92F));
      $$0.put(gkq.bR, ghh.a(0.92F, false));
      $$0.put(gkq.bS, ghh.a(0.92F, true));
      $$0.put(gkq.bV, $$20);
      $$0.put(gkq.bW, $$21);
      $$0.put(gkq.bZ, $$39);
      $$0.put(gkq.ca, $$39.a(gil.a));
      $$0.put(gkq.cb, gim.a());
      $$0.put(gkq.cc, gin.a());
      $$0.put(gkq.cd, $$40);
      $$0.put(gkq.co, $$40.a(gio.a));
      $$0.put(gkq.cq, $$41);
      $$0.put(gkq.cp, $$41.a(gio.a));
      $$0.put(gkq.ce, $$23);
      $$0.put(gkq.cm, $$4);
      $$0.put(gkq.cn, $$3);
      $$0.put(gkq.ci, $$23);
      $$0.put(gkq.cj, $$4);
      $$0.put(gkq.ck, $$3);
      $$0.put(gkq.cf, $$23.a(gib.i));
      $$0.put(gkq.cg, $$4.a(gib.i));
      $$0.put(gkq.ch, $$3.a(gib.i));
      $$0.put(gkq.cl, $$24);
      $$0.put(gkq.cr, $$12);
      $$0.put(gkq.cs, gkx.a(git.a(gkv.a, false), 64, 64));
      $$0.put(gkq.cu, gis.a());
      $$0.put(gkq.ct, gir.a());
      $$0.put(gkq.cv, $$25);
      $$0.put(gkq.cw, $$4);
      $$0.put(gkq.cx, $$2);
      $$0.put(gkq.cy, gkx.a(git.a(gkv.a, true), 64, 64));
      $$0.put(gkq.cz, $$4);
      $$0.put(gkq.cA, $$2);
      $$0.put(gkq.cB, gjq.a());
      $$0.put(gkq.cC, giu.a(false));
      $$0.put(gkq.cD, giu.a(true));
      $$0.put(gkq.cE, giv.a());
      $$0.put(gkq.cF, giw.a());
      $$0.put(gkq.cG, gix.a());
      $$0.put(gkq.cH, giz.a(false));
      $$0.put(gkq.cI, giz.a(true));
      $$0.put(gkq.cJ, gjb.a());
      $$0.put(gkq.cK, $$57);
      $$0.put(gkq.cM, $$57.a(gjc.a));
      $$0.put(gkq.cL, $$57.a(gjc.b));
      $$0.put(gkq.cN, $$42);
      $$0.put(gkq.cO, $$42.a(gje.a));
      $$0.put(gkq.cQ, $$43);
      $$0.put(gkq.cP, $$43.a(gje.a));
      $$0.put(gkq.cR, $$42);
      $$0.put(gkq.cS, $$42.a(gje.a));
      $$0.put(gkq.cT, gjf.a());
      $$0.put(gkq.cU, gjh.a());
      $$0.put(gkq.cV, gjh.b());
      $$0.put(gkq.cW, gjg.a());
      $$0.put(gkq.cX, gji.a());
      $$0.put(gkq.cY, $$31);
      $$0.put(gkq.dd, $$4);
      $$0.put(gkq.de, $$2);
      $$0.put(gkq.cZ, $$7);
      $$0.put(gkq.da, $$8);
      $$0.put(gkq.db, $$9);
      $$0.put(gkq.dc, $$10);
      $$0.put(gkq.df, $$6);
      $$0.put(gkq.dg, gjm.b());
      $$0.put(gkq.dh, gjm.a());
      $$0.put(gkq.di, $$44);
      $$0.put(gkq.dj, $$44.a(gjn.a));
      $$0.put(gkq.dk, gjo.a());
      $$0.put(gkq.dl, $$5);
      $$0.put(gkq.dm, $$33);
      $$0.put(gkq.dp, $$55);
      $$0.put(gkq.dq, $$55.a(gjr.a));
      $$0.put(gkq.dr, $$31);
      $$0.put(gkq.ds, $$4);
      $$0.put(gkq.dt, $$2);
      $$0.put(gkq.du, gkx.a(gib.a(new gkv(0.25F), 0.0F), 64, 32));
      $$0.put(gkq.dv, $$28);
      $$0.put(gkq.dw, $$28);
      $$0.put(gkq.dx, $$28.a(gjs.a));
      $$0.put(gkq.dy, $$28.a(gjs.a));
      $$0.put(gkq.dz, gjt.a());
      $$0.put(gkq.dA, $$5);
      $$0.put(gkq.dB, $$26);
      $$0.put(gkq.dC, $$26.a(gig.a));
      $$0.put(gkq.dD, gju.a());
      $$0.put(gkq.dE, gjw.a(gkv.a));
      $$0.put(gkq.dF, gjw.a(a));
      $$0.put(gkq.dG, gjv.a(gkv.a));
      $$0.put(gkq.dH, gjv.a(a));
      $$0.put(gkq.dI, $$45);
      $$0.put(gkq.dJ, $$45.a(gjx.a));
      $$0.put(gkq.dK, gjy.a());
      $$0.put(gkq.dL, $$32);
      $$0.put(gkq.dM, $$32.a(gka.a));
      $$0.put(gkq.dN, $$12);
      $$0.put(gkq.dP, gkb.a());
      $$0.put(gkq.dQ, $$46);
      $$0.put(gkq.dR, $$46.a(ghd.a));
      $$0.put(gkq.dO, $$32);
      $$0.put(gkq.dS, gkd.a());
      $$0.put(gkq.dT, gke.a().a($$11));
      $$0.put(gkq.dU, gkf.a(gkv.a));
      $$0.put(gkq.dV, gkf.a(c));
      $$0.put(gkq.ea, haz.a());
      gla $$61 = gla.scaling(1.2F);
      $$0.put(gkq.dW, $$31.a($$61));
      $$0.put(gkq.dX, $$4.a($$61));
      $$0.put(gkq.dY, $$2.a($$61));
      $$0.put(gkq.dZ, $$6);
      $$0.put(gkq.eb, $$47);
      $$0.put(gkq.ec, $$48);
      $$0.put(gkq.ed, $$47.a(gkg.a));
      $$0.put(gkq.ee, $$48.a(gkg.a));
      $$0.put(gkq.ef, $$29);
      $$0.put(gkq.eg, $$30);
      $$0.put(gkq.eh, $$1);
      $$0.put(gkq.eq, $$4);
      $$0.put(gkq.er, $$2);
      $$0.put(gkq.ei, $$1.a(gib.i));
      $$0.put(gkq.ej, $$4.a(gib.i));
      $$0.put(gkq.ek, $$2.a(gib.i));
      $$0.put(gkq.el, $$25);
      $$0.put(gkq.em, $$7);
      $$0.put(gkq.en, $$8);
      $$0.put(gkq.eo, $$9);
      $$0.put(gkq.ep, $$10);
      $$0.put(gkq.es, $$49);
      $$0.put(gkq.ew, gki.a(c));
      $$0.put(gkq.ex, gki.a(b));
      $$0.put(gkq.et, $$49.a(gib.i));
      $$0.put(gkq.eu, gki.a(c).a(gib.i));
      $$0.put(gkq.ev, gki.a(b).a(gib.i));
      $$0.put(gkq.ey, $$23);
      $$0.put(gkq.eC, $$4);
      $$0.put(gkq.eD, $$3);
      $$0.put(gkq.ez, $$23.a(gib.i));
      $$0.put(gkq.eA, $$4.a(gib.i));
      $$0.put(gkq.eB, $$3.a(gib.i));
      $$0.put(gkq.p, gja.a());
      $$0.put(gkq.o, gja.b());
      gkx $$62 = ggq.a();
      gkx $$63 = ggq.b();
      $$0.put(gkq.bT, $$62);
      $$0.put(gkq.bU, $$63);
      $$0.put(gkq.dn, $$62);
      $$0.put(gkq.do, $$63);
      $$0.put(gkq.B, $$62);
      $$0.put(gkq.C, $$63);
      $$0.put(gkq.bB, $$62);
      $$0.put(gkq.bC, $$63);
      $$0.put(gkq.a, $$62);
      $$0.put(gkq.b, $$63);
      $$0.put(gkq.V, $$62);
      $$0.put(gkq.W, $$63);
      $$0.put(gkq.at, $$62);
      $$0.put(gkq.au, $$63);
      $$0.put(gkq.bX, $$62);
      $$0.put(gkq.bY, $$63);
      $$0.put(gkq.bK, $$62);
      $$0.put(gkq.bL, $$63);
      gkx $$64 = gup.a(true);
      gkx $$65 = gup.a(false);
      ede.a().forEach($$3x -> {
         $$0.put(gkq.a($$3x), $$64);
         $$0.put(gkq.b($$3x), $$65);

         for (gul.a $$4x : gul.a.values()) {
            gkx $$5x = gul.a($$4x);
            $$0.put(gkq.a($$3x, $$4x), $$5x);
         }
      });
      ImmutableMap<gkp, gkx> $$66 = $$0.build();
      List<gkp> $$67 = gkq.a().filter($$1x -> !$$66.containsKey($$1x)).collect(Collectors.toList());
      if (!$$67.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$67);
      } else {
         return $$66;
      }
   }
}
