import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class gld {
   private static final glk a = new glk(0.008F);
   private static final glk b = new glk(1.0F);
   private static final glk c = new glk(0.5F);

   public static Map<gle, glm> a() {
      Builder<gle, glm> $$0 = ImmutableMap.builder();
      glm $$1 = glm.a(giq.a(glk.a, 0.0F), 64, 64);
      glm $$2 = glm.a(gip.a(b), 64, 32);
      glm $$3 = glm.a(gip.a(new glk(1.02F)), 64, 32);
      glm $$4 = glm.a(gip.a(c), 64, 32);
      glm $$5 = gix.a();
      glm $$6 = gjz.c();
      glm $$7 = glm.a(ggl.a(glk.a), 64, 64);
      glm $$8 = glm.a(ggl.b(glk.a), 64, 64);
      glm $$9 = gid.a(false);
      glm $$10 = gid.a(true);
      glp $$11 = glp.scaling(0.9375F);
      glm $$12 = gir.a().a($$11);
      glm $$13 = ggw.a();
      glm $$14 = ghb.a();
      glm $$15 = ghs.b();
      glm $$16 = ghp.c();
      glm $$17 = ghq.a();
      glm $$18 = ghr.a(glk.a);
      glm $$19 = ghy.a();
      glm $$20 = glm.a(gif.a(glk.a), 64, 32);
      glm $$21 = $$20.a(gif.b);
      glm $$22 = glm.a(gif.a(new glk(0.01F)), 64, 32);
      glm $$23 = glm.a(gjf.a(glk.a), 64, 64);
      glm $$24 = glm.a(gje.a(), 64, 64);
      glm $$25 = gjz.b();
      glm $$26 = giv.a(glk.a);
      glm $$27 = giv.a(new glk(0.5F));
      glm $$28 = gkh.a();
      glm $$29 = gin.a();
      glm $$30 = gin.b();
      glm $$31 = gjy.c();
      glm $$32 = glm.a(gkp.a(), 64, 64).a($$11);
      glm $$33 = gke.a();
      glm $$34 = ggr.a();
      glm $$35 = ghj.a();
      glm $$36 = ghk.c();
      glm $$37 = ghn.a();
      glm $$38 = gik.a();
      glm $$39 = gja.a();
      glm $$40 = gjd.b(glk.a);
      glm $$41 = gjd.b(new glk(0.5F));
      glm $$42 = gjt.a();
      glm $$43 = gjs.a();
      glm $$44 = gkc.a();
      glm $$45 = gkm.a();
      glm $$46 = gkr.a();
      glm $$47 = glm.a(gkv.a(glk.a), 64, 32);
      glm $$48 = glm.a(gkv.a(new glk(0.2F)), 64, 32);
      glm $$49 = gkx.a();
      glm $$50 = ggu.a();
      glm $$51 = ggt.a(c);
      glm $$52 = ggt.a(b);
      glm $$53 = ghx.a(glk.a);
      glm $$54 = ghx.a(new glk(0.25F));
      glm $$55 = gkg.a();
      glm $$56 = ghv.a();
      glm $$57 = gjr.a();
      $$0.put(glf.c, ggp.a());
      $$0.put(glf.d, $$34);
      $$0.put(glf.e, $$34.a(ggr.a));
      $$0.put(glf.f, $$50);
      $$0.put(glf.g, $$51);
      $$0.put(glf.h, $$52);
      $$0.put(glf.i, $$50.a(giq.i));
      $$0.put(glf.j, $$51.a(giq.i));
      $$0.put(glf.k, $$52.a(giq.i));
      $$0.put(glf.l, ggv.a());
      $$0.put(glf.m, $$13);
      $$0.put(glf.n, $$13.a(ggw.b));
      $$0.put(glf.q, ggz.a(true));
      $$0.put(glf.s, ggz.a(false));
      $$0.put(glf.r, ggy.a(true));
      $$0.put(glf.t, ggy.a(false));
      $$0.put(glf.u, gha.a());
      $$0.put(glf.v, gum.c());
      $$0.put(glf.w, gum.b());
      $$0.put(glf.x, $$14);
      $$0.put(glf.y, $$14.a(ghb.a));
      $$0.put(glf.z, ghc.a());
      $$0.put(glf.A, ghd.a());
      $$0.put(glf.D, ghe.a());
      $$0.put(glf.E, ghf.c());
      $$0.put(glf.F, ghg.a());
      $$0.put(glf.G, $$4);
      $$0.put(glf.H, $$2);
      $$0.put(glf.I, glm.a(giq.a(new glk(0.2F), 0.0F), 64, 32));
      $$0.put(glf.J, ghh.a());
      $$0.put(glf.K, ghi.a(32, 32));
      $$0.put(glf.L, ghi.a(128, 128));
      $$0.put(glf.Q, $$20.a(ghl.a));
      $$0.put(glf.R, $$21.a(ghl.a));
      $$0.put(glf.T, $$22.a(ghl.a));
      $$0.put(glf.S, $$22.a(gif.b).a(ghl.a));
      $$0.put(glf.M, $$35);
      $$0.put(glf.N, $$35.a(ghj.a));
      $$0.put(glf.O, $$36);
      $$0.put(glf.P, $$36.a(ghj.a));
      $$0.put(glf.U, $$33.a(glp.scaling(0.7F)));
      $$0.put(glf.X, ghm.a());
      $$0.put(glf.Y, $$5);
      $$0.put(glf.Z, $$37);
      $$0.put(glf.aa, $$37.a(ghn.c));
      $$0.put(glf.ab, gho.a());
      $$0.put(glf.ac, $$16);
      $$0.put(glf.ad, $$16.a(ghn.c));
      $$0.put(glf.ae, $$17);
      $$0.put(glf.af, $$17.a(ghs.a));
      $$0.put(glf.ag, $$18);
      $$0.put(glf.ah, $$18.a(gjd.a));
      $$0.put(glf.ai, $$5);
      $$0.put(glf.ak, gux.b());
      $$0.put(glf.am, gux.c());
      $$0.put(glf.al, gux.d());
      $$0.put(glf.aj, gux.e());
      $$0.put(glf.an, $$15);
      $$0.put(glf.ao, $$15.a(ghs.a));
      $$0.put(glf.ap, ght.a());
      $$0.put(glf.aq, ghu.a(glk.a));
      $$0.put(glf.ar, ghu.a(new glk(2.0F)));
      $$0.put(glf.as, $$6);
      $$0.put(glf.av, guy.b());
      $$0.put(glf.aw, guy.c());
      $$0.put(glf.ax, $$56);
      $$0.put(glf.ay, $$56.a(ghv.a));
      $$0.put(glf.az, ghw.a(0.87F));
      $$0.put(glf.aA, ghw.b(0.87F));
      $$0.put(glf.aB, ghw.a(0.87F, false));
      $$0.put(glf.aC, ghw.a(0.87F, true));
      $$0.put(glf.aD, ghm.c());
      $$0.put(glf.aE, ghm.b());
      $$0.put(glf.aF, gkz.a());
      $$0.put(glf.aG, $$53);
      $$0.put(glf.aL, $$4);
      $$0.put(glf.aM, $$4);
      $$0.put(glf.aN, $$54);
      $$0.put(glf.aH, $$53.a(giq.i));
      $$0.put(glf.aI, $$4.a(giq.i));
      $$0.put(glf.aJ, $$4.a(giq.i));
      $$0.put(glf.aK, $$54.a(giq.i));
      $$0.put(glf.aO, gil.b());
      $$0.put(glf.aP, $$19);
      $$0.put(glf.aQ, $$19.a(ghy.a));
      $$0.put(glf.aR, gia.a());
      $$0.put(glf.aS, gib.a());
      $$0.put(glf.aT, gla.a());
      $$0.put(glf.aU, ghz.a());
      $$0.put(glf.aV, $$12);
      $$0.put(glf.aW, gie.a());
      $$0.put(glf.aX, gig.a());
      $$0.put(glf.aY, gig.a().a(gig.a));
      $$0.put(glf.aZ, gih.a());
      $$0.put(glf.ba, $$5);
      $$0.put(glf.bb, gii.a());
      glp $$58 = glp.scaling(6.0F);
      $$0.put(glf.bc, $$1.a($$58));
      $$0.put(glf.bd, $$4.a($$58));
      $$0.put(glf.be, $$2.a($$58));
      $$0.put(glf.bf, $$55);
      $$0.put(glf.bg, $$55.a(gkg.a));
      $$0.put(glf.bh, $$38);
      $$0.put(glf.bi, $$38.a(gik.a));
      $$0.put(glf.bj, gil.a());
      $$0.put(glf.bk, $$29);
      $$0.put(glf.bl, $$30);
      $$0.put(glf.bm, $$5);
      glp $$59 = glp.scaling(1.1F);
      $$0.put(glf.bn, $$7.a($$59));
      $$0.put(glf.bq, $$8.a($$59));
      $$0.put(glf.bo, glm.a(ggl.a(new glk(0.1F)), 64, 64).a($$59));
      $$0.put(glf.br, glm.a(ggl.b(new glk(0.1F)), 64, 64).a($$59));
      $$0.put(glf.bp, $$9.a($$59));
      $$0.put(glf.bs, $$10.a($$59));
      glp $$60 = glp.scaling(1.0625F);
      $$0.put(glf.bt, $$1.a($$60));
      $$0.put(glf.bx, $$4.a($$60));
      $$0.put(glf.by, $$2.a($$60));
      $$0.put(glf.bu, $$1.a(giq.i).a($$60));
      $$0.put(glf.bv, $$4.a(giq.i).a($$60));
      $$0.put(glf.bw, $$2.a(giq.i).a($$60));
      $$0.put(glf.bz, $$12);
      $$0.put(glf.bA, gis.a());
      $$0.put(glf.bD, giu.a());
      $$0.put(glf.bE, $$26);
      $$0.put(glf.bF, $$26.a(giv.a));
      $$0.put(glf.bH, $$27);
      $$0.put(glf.bG, $$27.a(giv.a));
      $$0.put(glf.bI, giw.a());
      $$0.put(glf.bJ, git.a());
      $$0.put(glf.bM, $$5);
      $$0.put(glf.bN, $$15);
      $$0.put(glf.bO, $$15.a(ghs.a));
      $$0.put(glf.bP, ghw.a(0.92F));
      $$0.put(glf.bQ, ghw.b(0.92F));
      $$0.put(glf.bR, ghw.a(0.92F, false));
      $$0.put(glf.bS, ghw.a(0.92F, true));
      $$0.put(glf.bV, $$20);
      $$0.put(glf.bW, $$21);
      $$0.put(glf.bZ, $$39);
      $$0.put(glf.ca, $$39.a(gja.a));
      $$0.put(glf.cb, gjb.a());
      $$0.put(glf.cc, gjc.a());
      $$0.put(glf.cd, $$40);
      $$0.put(glf.co, $$40.a(gjd.a));
      $$0.put(glf.cq, $$41);
      $$0.put(glf.cp, $$41.a(gjd.a));
      $$0.put(glf.ce, $$23);
      $$0.put(glf.cm, $$4);
      $$0.put(glf.cn, $$3);
      $$0.put(glf.ci, $$23);
      $$0.put(glf.cj, $$4);
      $$0.put(glf.ck, $$3);
      $$0.put(glf.cf, $$23.a(giq.i));
      $$0.put(glf.cg, $$4.a(giq.i));
      $$0.put(glf.ch, $$3.a(giq.i));
      $$0.put(glf.cl, $$24);
      $$0.put(glf.cr, $$12);
      $$0.put(glf.cs, glm.a(gji.a(glk.a, false), 64, 64));
      $$0.put(glf.cu, gjh.a());
      $$0.put(glf.ct, gjg.a());
      $$0.put(glf.cv, $$25);
      $$0.put(glf.cw, $$4);
      $$0.put(glf.cx, $$2);
      $$0.put(glf.cy, glm.a(gji.a(glk.a, true), 64, 64));
      $$0.put(glf.cz, $$4);
      $$0.put(glf.cA, $$2);
      $$0.put(glf.cB, gkf.a());
      $$0.put(glf.cC, gjj.a(false));
      $$0.put(glf.cD, gjj.a(true));
      $$0.put(glf.cE, gjk.a());
      $$0.put(glf.cF, gjl.a());
      $$0.put(glf.cG, gjm.a());
      $$0.put(glf.cH, gjo.a(false));
      $$0.put(glf.cI, gjo.a(true));
      $$0.put(glf.cJ, gjq.a());
      $$0.put(glf.cK, $$57);
      $$0.put(glf.cM, $$57.a(gjr.a));
      $$0.put(glf.cL, $$57.a(gjr.b));
      $$0.put(glf.cN, $$42);
      $$0.put(glf.cO, $$42.a(gjt.a));
      $$0.put(glf.cQ, $$43);
      $$0.put(glf.cP, $$43.a(gjt.a));
      $$0.put(glf.cR, $$42);
      $$0.put(glf.cS, $$42.a(gjt.a));
      $$0.put(glf.cT, gju.a());
      $$0.put(glf.cU, gjw.a());
      $$0.put(glf.cV, gjw.b());
      $$0.put(glf.cW, gjv.a());
      $$0.put(glf.cX, gjx.a());
      $$0.put(glf.cY, $$31);
      $$0.put(glf.dd, $$4);
      $$0.put(glf.de, $$2);
      $$0.put(glf.cZ, $$7);
      $$0.put(glf.da, $$8);
      $$0.put(glf.db, $$9);
      $$0.put(glf.dc, $$10);
      $$0.put(glf.df, $$6);
      $$0.put(glf.dg, gkb.b());
      $$0.put(glf.dh, gkb.a());
      $$0.put(glf.di, $$44);
      $$0.put(glf.dj, $$44.a(gkc.a));
      $$0.put(glf.dk, gkd.a());
      $$0.put(glf.dl, $$5);
      $$0.put(glf.dm, $$33);
      $$0.put(glf.dp, $$55);
      $$0.put(glf.dq, $$55.a(gkg.a));
      $$0.put(glf.dr, $$31);
      $$0.put(glf.ds, $$4);
      $$0.put(glf.dt, $$2);
      $$0.put(glf.du, glm.a(giq.a(new glk(0.25F), 0.0F), 64, 32));
      $$0.put(glf.dv, $$28);
      $$0.put(glf.dw, $$28);
      $$0.put(glf.dx, $$28.a(gkh.a));
      $$0.put(glf.dy, $$28.a(gkh.a));
      $$0.put(glf.dz, gki.a());
      $$0.put(glf.dA, $$5);
      $$0.put(glf.dB, $$26);
      $$0.put(glf.dC, $$26.a(giv.a));
      $$0.put(glf.dD, gkj.a());
      $$0.put(glf.dE, gkl.a(glk.a));
      $$0.put(glf.dF, gkl.a(a));
      $$0.put(glf.dG, gkk.a(glk.a));
      $$0.put(glf.dH, gkk.a(a));
      $$0.put(glf.dI, $$45);
      $$0.put(glf.dJ, $$45.a(gkm.a));
      $$0.put(glf.dK, gkn.a());
      $$0.put(glf.dL, $$32);
      $$0.put(glf.dM, $$32.a(gkp.a));
      $$0.put(glf.dN, $$12);
      $$0.put(glf.dP, gkq.a());
      $$0.put(glf.dQ, $$46);
      $$0.put(glf.dR, $$46.a(ghs.a));
      $$0.put(glf.dO, $$32);
      $$0.put(glf.dS, gks.a());
      $$0.put(glf.dT, gkt.a().a($$11));
      $$0.put(glf.dU, gku.a(glk.a));
      $$0.put(glf.dV, gku.a(c));
      $$0.put(glf.ea, hbo.a());
      glp $$61 = glp.scaling(1.2F);
      $$0.put(glf.dW, $$31.a($$61));
      $$0.put(glf.dX, $$4.a($$61));
      $$0.put(glf.dY, $$2.a($$61));
      $$0.put(glf.dZ, $$6);
      $$0.put(glf.eb, $$47);
      $$0.put(glf.ec, $$48);
      $$0.put(glf.ed, $$47.a(gkv.a));
      $$0.put(glf.ee, $$48.a(gkv.a));
      $$0.put(glf.ef, $$29);
      $$0.put(glf.eg, $$30);
      $$0.put(glf.eh, $$1);
      $$0.put(glf.eq, $$4);
      $$0.put(glf.er, $$2);
      $$0.put(glf.ei, $$1.a(giq.i));
      $$0.put(glf.ej, $$4.a(giq.i));
      $$0.put(glf.ek, $$2.a(giq.i));
      $$0.put(glf.el, $$25);
      $$0.put(glf.em, $$7);
      $$0.put(glf.en, $$8);
      $$0.put(glf.eo, $$9);
      $$0.put(glf.ep, $$10);
      $$0.put(glf.es, $$49);
      $$0.put(glf.ew, gkx.a(c));
      $$0.put(glf.ex, gkx.a(b));
      $$0.put(glf.et, $$49.a(giq.i));
      $$0.put(glf.eu, gkx.a(c).a(giq.i));
      $$0.put(glf.ev, gkx.a(b).a(giq.i));
      $$0.put(glf.ey, $$23);
      $$0.put(glf.eC, $$4);
      $$0.put(glf.eD, $$3);
      $$0.put(glf.ez, $$23.a(giq.i));
      $$0.put(glf.eA, $$4.a(giq.i));
      $$0.put(glf.eB, $$3.a(giq.i));
      $$0.put(glf.p, gjp.a());
      $$0.put(glf.o, gjp.b());
      glm $$62 = ghf.a();
      glm $$63 = ghf.b();
      $$0.put(glf.bT, $$62);
      $$0.put(glf.bU, $$63);
      $$0.put(glf.dn, $$62);
      $$0.put(glf.do, $$63);
      $$0.put(glf.B, $$62);
      $$0.put(glf.C, $$63);
      $$0.put(glf.bB, $$62);
      $$0.put(glf.bC, $$63);
      $$0.put(glf.a, $$62);
      $$0.put(glf.b, $$63);
      $$0.put(glf.V, $$62);
      $$0.put(glf.W, $$63);
      $$0.put(glf.at, $$62);
      $$0.put(glf.au, $$63);
      $$0.put(glf.bX, $$62);
      $$0.put(glf.bY, $$63);
      $$0.put(glf.bK, $$62);
      $$0.put(glf.bL, $$63);
      glm $$64 = gve.a(true);
      glm $$65 = gve.a(false);
      ecu.a().forEach($$3x -> {
         $$0.put(glf.a($$3x), $$64);
         $$0.put(glf.b($$3x), $$65);

         for (gva.a $$4x : gva.a.values()) {
            glm $$5x = gva.a($$4x);
            $$0.put(glf.a($$3x, $$4x), $$5x);
         }
      });
      ImmutableMap<gle, glm> $$66 = $$0.build();
      List<gle> $$67 = glf.a().filter($$1x -> !$$66.containsKey($$1x)).collect(Collectors.toList());
      if (!$$67.isEmpty()) {
         throw new IllegalStateException("Missing layer definitions: " + $$67);
      } else {
         return $$66;
      }
   }
}
