import java.util.function.BiConsumer;

public class kf implements kd {
   @Override
   public void generate(BiConsumer<aer, eco.a> $$0) {
      $$0.accept(
         ece.aC,
         eco.b()
            .a(
               ecn.a()
                  .a(efy.a(1.0F))
                  .a(ecw.a(cja.wP).a(2))
                  .a(ecw.a(cja.wR).a(2))
                  .a(ecw.a(cja.pX))
                  .a(ecw.a(cja.nL))
                  .a(ecw.a(cja.oB))
                  .a(
                     ecw.a(cja.va)
                        .a(
                           eek.c()
                              .a(bhx.p, egd.a(7.0F, 10.0F))
                              .a(bhx.h, egd.a(7.0F, 10.0F))
                              .a(bhx.r, egd.a(6.0F, 8.0F))
                              .a(bhx.o, egd.a(5.0F, 7.0F))
                              .a(bhx.s, egd.a(10.0F, 20.0F))
                              .a(bhx.w, egd.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ece.aD,
         eco.b()
            .a(
               ecn.a()
                  .a(efy.a(1.0F))
                  .a(ecw.a(cja.wO))
                  .a(ecw.a(cja.wZ))
                  .a(ecw.a(cja.xc))
                  .a(ecw.a(cja.xf))
                  .a(ecw.a(cja.nK))
                  .a(ecw.a(cja.lH))
                  .a(ecw.a(cja.oG))
                  .a(ecw.a(cja.nL))
            )
      );
      $$0.accept(
         ece.aE,
         eco.b()
            .a(
               ecn.a()
                  .a(efy.a(1.0F))
                  .a(ecw.a(cja.nL).a(2))
                  .a(ecw.a(cja.oI).a(2))
                  .a(ecw.a(cja.ob).a(2))
                  .a(ecw.a(cja.eB).a(2))
                  .a(ecw.a(cja.pX).a(2))
                  .a(ecw.a(cja.qy).a(2))
                  .a(ecw.a(cja.qF).a(2))
                  .a(ecw.a(cja.qx).a(2))
                  .a(ecw.a(cja.qu).a(2))
                  .a(ecw.a(cja.qv).a(2))
                  .a(ecw.a(cja.wj).a(2))
                  .a(ecw.a(cja.wi).a(2))
                  .a(ecw.a(cja.wf).a(2))
                  .a(ecw.a(cja.wh).a(2))
                  .a(ecw.a(cja.hZ))
                  .a(ecw.a(cja.id))
                  .a(ecw.a(cja.ii))
                  .a(ecw.a(cja.ia))
                  .a(ecw.a(cja.il))
                  .a(ecw.a(cja.ib))
                  .a(ecw.a(cja.ih))
                  .a(ecw.a(cja.pA))
                  .a(ecw.a(cja.pz))
                  .a(ecw.a(cja.rt))
                  .a(ecw.a(cja.nI))
                  .a(ecw.a(cja.oH))
                  .a(ecw.a(cja.ur))
                  .a(ecw.a(cja.cv))
                  .a(ecw.a(cja.tk))
                  .a(ecw.a(cja.oE))
                  .a(ecw.a(cja.tQ))
            )
      );
      $$0.accept(
         ece.aF,
         eco.b()
            .a(
               ecn.a()
                  .a(efy.a(1.0F))
                  .a(ecw.a(cja.wS))
                  .a(ecw.a(cja.wT))
                  .a(ecw.a(cja.wV))
                  .a(ecw.a(cja.wW))
                  .a(ecw.a(cja.wX))
                  .a(ecw.a(cja.wY))
                  .a(ecw.a(cja.xd))
                  .a(ecw.a(cja.wI))
                  .a(ecw.a(cja.wL))
                  .a(ecw.a(cja.wJ))
                  .a(ecw.a(cja.wM))
                  .a(ecw.a(cja.uR))
            )
      );
      $$0.accept(
         ece.aG,
         eco.b()
            .a(
               ecn.a()
                  .a(efy.a(1.0F))
                  .a(ecw.a(cja.wN))
                  .a(ecw.a(cja.xe))
                  .a(ecw.a(cja.xg))
                  .a(ecw.a(cja.jU))
                  .a(ecw.a(cja.op))
                  .a(ecw.a(cja.nL).a(2))
                  .a(ecw.a(cja.oI).a(2))
                  .a(ecw.a(cja.ob).a(2))
                  .a(ecw.a(cja.nI).a(2))
                  .a(ecw.a(cja.rt).a(2))
            )
      );
      $$0.accept(
         ece.aH,
         eco.b()
            .a(
               ecn.a()
                  .a(efy.a(1.0F))
                  .a(ecw.a(cja.wQ))
                  .a(ecw.a(cja.wU))
                  .a(ecw.a(cja.xa))
                  .a(ecw.a(cja.xb))
                  .a(ecw.a(cja.op))
                  .a(ecw.a(cja.nL).a(2))
                  .a(ecw.a(cja.oI).a(2))
                  .a(ecw.a(cja.ob).a(2))
                  .a(ecw.a(cja.nI).a(2))
                  .a(ecw.a(cja.rt).a(2))
            )
      );
   }
}
