import java.util.function.BiConsumer;

public class kg implements ke {
   @Override
   public void generate(BiConsumer<aep, ecp.a> $$0) {
      $$0.accept(
         ecd.aC,
         ecp.b()
            .a(
               eco.a()
                  .a(ega.a(1.0F))
                  .a(ecz.a(ciz.wP).a(2))
                  .a(ecz.a(ciz.wR).a(2))
                  .a(ecz.a(ciz.pX))
                  .a(ecz.a(ciz.nL))
                  .a(ecz.a(ciz.oB))
                  .a(
                     ecz.a(ciz.va)
                        .a(
                           eem.c()
                              .a(bhv.p, egf.a(7.0F, 10.0F))
                              .a(bhv.h, egf.a(7.0F, 10.0F))
                              .a(bhv.r, egf.a(6.0F, 8.0F))
                              .a(bhv.o, egf.a(5.0F, 7.0F))
                              .a(bhv.s, egf.a(10.0F, 20.0F))
                              .a(bhv.w, egf.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ecd.aD,
         ecp.b()
            .a(
               eco.a()
                  .a(ega.a(1.0F))
                  .a(ecz.a(ciz.wO))
                  .a(ecz.a(ciz.wZ))
                  .a(ecz.a(ciz.xc))
                  .a(ecz.a(ciz.xf))
                  .a(ecz.a(ciz.nK))
                  .a(ecz.a(ciz.lH))
                  .a(ecz.a(ciz.oG))
                  .a(ecz.a(ciz.nL))
            )
      );
      $$0.accept(
         ecd.aE,
         ecp.b()
            .a(
               eco.a()
                  .a(ega.a(1.0F))
                  .a(ecz.a(ciz.nL).a(2))
                  .a(ecz.a(ciz.oI).a(2))
                  .a(ecz.a(ciz.ob).a(2))
                  .a(ecz.a(ciz.eB).a(2))
                  .a(ecz.a(ciz.pX).a(2))
                  .a(ecz.a(ciz.qy).a(2))
                  .a(ecz.a(ciz.qF).a(2))
                  .a(ecz.a(ciz.qx).a(2))
                  .a(ecz.a(ciz.qu).a(2))
                  .a(ecz.a(ciz.qv).a(2))
                  .a(ecz.a(ciz.wj).a(2))
                  .a(ecz.a(ciz.wi).a(2))
                  .a(ecz.a(ciz.wf).a(2))
                  .a(ecz.a(ciz.wh).a(2))
                  .a(ecz.a(ciz.hZ))
                  .a(ecz.a(ciz.id))
                  .a(ecz.a(ciz.ii))
                  .a(ecz.a(ciz.ia))
                  .a(ecz.a(ciz.il))
                  .a(ecz.a(ciz.ib))
                  .a(ecz.a(ciz.ih))
                  .a(ecz.a(ciz.pA))
                  .a(ecz.a(ciz.pz))
                  .a(ecz.a(ciz.rt))
                  .a(ecz.a(ciz.nI))
                  .a(ecz.a(ciz.oH))
                  .a(ecz.a(ciz.ur))
                  .a(ecz.a(ciz.cv))
                  .a(ecz.a(ciz.tk))
                  .a(ecz.a(ciz.oE))
                  .a(ecz.a(ciz.tQ))
            )
      );
      $$0.accept(
         ecd.aF,
         ecp.b()
            .a(
               eco.a()
                  .a(ega.a(1.0F))
                  .a(ecz.a(ciz.wS))
                  .a(ecz.a(ciz.wT))
                  .a(ecz.a(ciz.wV))
                  .a(ecz.a(ciz.wW))
                  .a(ecz.a(ciz.wX))
                  .a(ecz.a(ciz.wY))
                  .a(ecz.a(ciz.xd))
                  .a(ecz.a(ciz.wI))
                  .a(ecz.a(ciz.wL))
                  .a(ecz.a(ciz.wJ))
                  .a(ecz.a(ciz.wM))
                  .a(ecz.a(ciz.uR))
            )
      );
      $$0.accept(
         ecd.aG,
         ecp.b()
            .a(
               eco.a()
                  .a(ega.a(1.0F))
                  .a(ecz.a(ciz.wN))
                  .a(ecz.a(ciz.xe))
                  .a(ecz.a(ciz.xg))
                  .a(ecz.a(ciz.jU))
                  .a(ecz.a(ciz.op))
                  .a(ecz.a(ciz.nL).a(2))
                  .a(ecz.a(ciz.oI).a(2))
                  .a(ecz.a(ciz.ob).a(2))
                  .a(ecz.a(ciz.nI).a(2))
                  .a(ecz.a(ciz.rt).a(2))
            )
      );
      $$0.accept(
         ecd.aH,
         ecp.b()
            .a(
               eco.a()
                  .a(ega.a(1.0F))
                  .a(ecz.a(ciz.wQ))
                  .a(ecz.a(ciz.wU))
                  .a(ecz.a(ciz.xa))
                  .a(ecz.a(ciz.xb))
                  .a(ecz.a(ciz.op))
                  .a(ecz.a(ciz.nL).a(2))
                  .a(ecz.a(ciz.oI).a(2))
                  .a(ecz.a(ciz.ob).a(2))
                  .a(ecz.a(ciz.nI).a(2))
                  .a(ecz.a(ciz.rt).a(2))
            )
      );
   }
}
