import java.util.function.BiConsumer;

public class kh implements kf {
   @Override
   public void generate(BiConsumer<aeu, ect.a> $$0) {
      $$0.accept(
         ecj.aC,
         ect.b()
            .a(
               ecs.a()
                  .a(egd.a(1.0F))
                  .a(edb.a(cjd.wP).a(2))
                  .a(edb.a(cjd.wR).a(2))
                  .a(edb.a(cjd.pX))
                  .a(edb.a(cjd.nL))
                  .a(edb.a(cjd.oB))
                  .a(
                     edb.a(cjd.va)
                        .a(
                           eep.c()
                              .a(bia.p, egi.a(7.0F, 10.0F))
                              .a(bia.h, egi.a(7.0F, 10.0F))
                              .a(bia.r, egi.a(6.0F, 8.0F))
                              .a(bia.o, egi.a(5.0F, 7.0F))
                              .a(bia.s, egi.a(10.0F, 20.0F))
                              .a(bia.w, egi.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ecj.aD,
         ect.b()
            .a(
               ecs.a()
                  .a(egd.a(1.0F))
                  .a(edb.a(cjd.wO))
                  .a(edb.a(cjd.wZ))
                  .a(edb.a(cjd.xc))
                  .a(edb.a(cjd.xf))
                  .a(edb.a(cjd.nK))
                  .a(edb.a(cjd.lH))
                  .a(edb.a(cjd.oG))
                  .a(edb.a(cjd.nL))
            )
      );
      $$0.accept(
         ecj.aE,
         ect.b()
            .a(
               ecs.a()
                  .a(egd.a(1.0F))
                  .a(edb.a(cjd.nL).a(2))
                  .a(edb.a(cjd.oI).a(2))
                  .a(edb.a(cjd.ob).a(2))
                  .a(edb.a(cjd.eB).a(2))
                  .a(edb.a(cjd.pX).a(2))
                  .a(edb.a(cjd.qy).a(2))
                  .a(edb.a(cjd.qF).a(2))
                  .a(edb.a(cjd.qx).a(2))
                  .a(edb.a(cjd.qu).a(2))
                  .a(edb.a(cjd.qv).a(2))
                  .a(edb.a(cjd.wj).a(2))
                  .a(edb.a(cjd.wi).a(2))
                  .a(edb.a(cjd.wf).a(2))
                  .a(edb.a(cjd.wh).a(2))
                  .a(edb.a(cjd.hZ))
                  .a(edb.a(cjd.id))
                  .a(edb.a(cjd.ii))
                  .a(edb.a(cjd.ia))
                  .a(edb.a(cjd.il))
                  .a(edb.a(cjd.ib))
                  .a(edb.a(cjd.ih))
                  .a(edb.a(cjd.pA))
                  .a(edb.a(cjd.pz))
                  .a(edb.a(cjd.rt))
                  .a(edb.a(cjd.nI))
                  .a(edb.a(cjd.oH))
                  .a(edb.a(cjd.ur))
                  .a(edb.a(cjd.cv))
                  .a(edb.a(cjd.tk))
                  .a(edb.a(cjd.oE))
                  .a(edb.a(cjd.tQ))
            )
      );
      $$0.accept(
         ecj.aF,
         ect.b()
            .a(
               ecs.a()
                  .a(egd.a(1.0F))
                  .a(edb.a(cjd.wS))
                  .a(edb.a(cjd.wT))
                  .a(edb.a(cjd.wV))
                  .a(edb.a(cjd.wW))
                  .a(edb.a(cjd.wX))
                  .a(edb.a(cjd.wY))
                  .a(edb.a(cjd.xd))
                  .a(edb.a(cjd.wI))
                  .a(edb.a(cjd.wL))
                  .a(edb.a(cjd.wJ))
                  .a(edb.a(cjd.wM))
                  .a(edb.a(cjd.uR))
            )
      );
      $$0.accept(
         ecj.aG,
         ect.b()
            .a(
               ecs.a()
                  .a(egd.a(1.0F))
                  .a(edb.a(cjd.wN))
                  .a(edb.a(cjd.xe))
                  .a(edb.a(cjd.xg))
                  .a(edb.a(cjd.jU))
                  .a(edb.a(cjd.op))
                  .a(edb.a(cjd.nL).a(2))
                  .a(edb.a(cjd.oI).a(2))
                  .a(edb.a(cjd.ob).a(2))
                  .a(edb.a(cjd.nI).a(2))
                  .a(edb.a(cjd.rt).a(2))
            )
      );
      $$0.accept(
         ecj.aH,
         ect.b()
            .a(
               ecs.a()
                  .a(egd.a(1.0F))
                  .a(edb.a(cjd.wQ))
                  .a(edb.a(cjd.wU))
                  .a(edb.a(cjd.xa))
                  .a(edb.a(cjd.xb))
                  .a(edb.a(cjd.op))
                  .a(edb.a(cjd.nL).a(2))
                  .a(edb.a(cjd.oI).a(2))
                  .a(edb.a(cjd.ob).a(2))
                  .a(edb.a(cjd.nI).a(2))
                  .a(edb.a(cjd.rt).a(2))
            )
      );
   }
}
