import java.util.function.BiConsumer;

public class kj implements kf {
   @Override
   public void generate(BiConsumer<aex, ecy.a> $$0) {
      $$0.accept(
         eco.aC,
         ecy.b()
            .a(
               ecx.a()
                  .a(egi.a(1.0F))
                  .a(edg.a(cji.wP).a(2))
                  .a(edg.a(cji.wR).a(2))
                  .a(edg.a(cji.pX))
                  .a(edg.a(cji.nL))
                  .a(edg.a(cji.oB))
                  .a(
                     edg.a(cji.va)
                        .a(
                           eeu.c()
                              .a(bif.p, egn.a(7.0F, 10.0F))
                              .a(bif.h, egn.a(7.0F, 10.0F))
                              .a(bif.r, egn.a(6.0F, 8.0F))
                              .a(bif.o, egn.a(5.0F, 7.0F))
                              .a(bif.s, egn.a(10.0F, 20.0F))
                              .a(bif.w, egn.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         eco.aD,
         ecy.b()
            .a(
               ecx.a()
                  .a(egi.a(1.0F))
                  .a(edg.a(cji.wO))
                  .a(edg.a(cji.wZ))
                  .a(edg.a(cji.xc))
                  .a(edg.a(cji.xf))
                  .a(edg.a(cji.nK))
                  .a(edg.a(cji.lH))
                  .a(edg.a(cji.oG))
                  .a(edg.a(cji.nL))
            )
      );
      $$0.accept(
         eco.aE,
         ecy.b()
            .a(
               ecx.a()
                  .a(egi.a(1.0F))
                  .a(edg.a(cji.nL).a(2))
                  .a(edg.a(cji.oI).a(2))
                  .a(edg.a(cji.ob).a(2))
                  .a(edg.a(cji.eB).a(2))
                  .a(edg.a(cji.pX).a(2))
                  .a(edg.a(cji.qy).a(2))
                  .a(edg.a(cji.qF).a(2))
                  .a(edg.a(cji.qx).a(2))
                  .a(edg.a(cji.qu).a(2))
                  .a(edg.a(cji.qv).a(2))
                  .a(edg.a(cji.wj).a(2))
                  .a(edg.a(cji.wi).a(2))
                  .a(edg.a(cji.wf).a(2))
                  .a(edg.a(cji.wh).a(2))
                  .a(edg.a(cji.hZ))
                  .a(edg.a(cji.id))
                  .a(edg.a(cji.ii))
                  .a(edg.a(cji.ia))
                  .a(edg.a(cji.il))
                  .a(edg.a(cji.ib))
                  .a(edg.a(cji.ih))
                  .a(edg.a(cji.pA))
                  .a(edg.a(cji.pz))
                  .a(edg.a(cji.rt))
                  .a(edg.a(cji.nI))
                  .a(edg.a(cji.oH))
                  .a(edg.a(cji.ur))
                  .a(edg.a(cji.cv))
                  .a(edg.a(cji.tk))
                  .a(edg.a(cji.oE))
                  .a(edg.a(cji.tQ))
            )
      );
      $$0.accept(
         eco.aF,
         ecy.b()
            .a(
               ecx.a()
                  .a(egi.a(1.0F))
                  .a(edg.a(cji.wS))
                  .a(edg.a(cji.wT))
                  .a(edg.a(cji.wV))
                  .a(edg.a(cji.wW))
                  .a(edg.a(cji.wX))
                  .a(edg.a(cji.wY))
                  .a(edg.a(cji.xd))
                  .a(edg.a(cji.wI))
                  .a(edg.a(cji.wL))
                  .a(edg.a(cji.wJ))
                  .a(edg.a(cji.wM))
                  .a(edg.a(cji.uR))
            )
      );
      $$0.accept(
         eco.aG,
         ecy.b()
            .a(
               ecx.a()
                  .a(egi.a(1.0F))
                  .a(edg.a(cji.wN))
                  .a(edg.a(cji.xe))
                  .a(edg.a(cji.xg))
                  .a(edg.a(cji.jU))
                  .a(edg.a(cji.op))
                  .a(edg.a(cji.nL).a(2))
                  .a(edg.a(cji.oI).a(2))
                  .a(edg.a(cji.ob).a(2))
                  .a(edg.a(cji.nI).a(2))
                  .a(edg.a(cji.rt).a(2))
            )
      );
      $$0.accept(
         eco.aH,
         ecy.b()
            .a(
               ecx.a()
                  .a(egi.a(1.0F))
                  .a(edg.a(cji.wQ))
                  .a(edg.a(cji.wU))
                  .a(edg.a(cji.xa))
                  .a(edg.a(cji.xb))
                  .a(edg.a(cji.op))
                  .a(edg.a(cji.nL).a(2))
                  .a(edg.a(cji.oI).a(2))
                  .a(edg.a(cji.ob).a(2))
                  .a(edg.a(cji.nI).a(2))
                  .a(edg.a(cji.rt).a(2))
            )
      );
   }
}
