import com.mojang.serialization.Codec;
import java.util.List;
import java.util.function.UnaryOperator;

public class kl {
   static final aze a = new aze(512);
   public static final kk<dcs> b = a("custom_data", $$0 -> $$0.a(dcs.b));
   public static final kk<Integer> c = a("max_stack_size", $$0 -> $$0.a(azg.a(1, 99)).a(zc.h));
   public static final kk<Integer> d = a("max_damage", $$0 -> $$0.a(azg.m).a(zc.h));
   public static final kk<Integer> e = a("damage", $$0 -> $$0.a(azg.l).a(zc.h));
   public static final kk<bbh> f = a("unbreakable", $$0 -> $$0.a(bbh.b).a(bbh.c));
   public static final kk<xg> g = a("custom_name", $$0 -> $$0.a(xi.a).a(xi.b).a());
   public static final kk<xg> h = a("item_name", $$0 -> $$0.a(xi.a).a(xi.b).a());
   public static final kk<alr> i = a("item_model", $$0 -> $$0.a(alr.a).a(alr.b).a());
   public static final kk<ddd> j = a("lore", $$0 -> $$0.a(ddd.c).a(ddd.d).a());
   public static final kk<dbg> k = a("rarity", $$0 -> $$0.a(dbg.e).a(dbg.g));
   public static final kk<dhd> l = a("enchantments", $$0 -> $$0.a(dhd.b).a(dhd.c).a());
   public static final kk<cyl> m = a("can_place_on", $$0 -> $$0.a(cyl.a).a(cyl.b).a());
   public static final kk<cyl> n = a("can_break", $$0 -> $$0.a(cyl.a).a(cyl.b).a());
   public static final kk<ddb> o = a("attribute_modifiers", $$0 -> $$0.a(ddb.b).a(ddb.c).a());
   public static final kk<dct> p = a("custom_model_data", $$0 -> $$0.a(dct.b).a(dct.c));
   public static final kk<ddo> q = a("tooltip_display", $$0 -> $$0.a(ddo.a).a(ddo.b).a());
   public static final kk<Integer> r = a("repair_cost", $$0 -> $$0.a(azg.l).a(zc.h));
   public static final kk<bbh> s = a("creative_slot_lock", $$0 -> $$0.a(bbh.c));
   public static final kk<Boolean> t = a("enchantment_glint_override", $$0 -> $$0.a(Codec.BOOL).a(zc.b));
   public static final kk<bbh> u = a("intangible_projectile", $$0 -> $$0.a(bbh.b));
   public static final kk<cvy> v = a("food", $$0 -> $$0.a(cvy.a).a(cvy.b).a());
   public static final kk<dcp> w = a("consumable", $$0 -> $$0.a(dcp.b).a(dcp.c).a());
   public static final kk<ddr> x = a("use_remainder", $$0 -> $$0.a(ddr.a).a(ddr.b).a());
   public static final kk<ddq> y = a("use_cooldown", $$0 -> $$0.a(ddq.a).a(ddq.b).a());
   public static final kk<dcu> z = a("damage_resistant", $$0 -> $$0.a(dcu.a).a(dcu.b).a());
   public static final kk<ddn> A = a("tool", $$0 -> $$0.a(ddn.a).a(ddn.b).a());
   public static final kk<dds> B = a("weapon", $$0 -> $$0.a(dds.b).a(dds.c).a());
   public static final kk<dgv> C = a("enchantable", $$0 -> $$0.a(dgv.a).a(dgv.b).a());
   public static final kk<dit> D = a("equippable", $$0 -> $$0.a(dit.a).a(dit.b).a());
   public static final kk<dhf> E = a("repairable", $$0 -> $$0.a(dhf.a).a(dhf.b).a());
   public static final kk<bbh> F = a("glider", $$0 -> $$0.a(bbh.b).a(bbh.c));
   public static final kk<alr> G = a("tooltip_style", $$0 -> $$0.a(alr.a).a(alr.b).a());
   public static final kk<dcv> H = a("death_protection", $$0 -> $$0.a(dcv.a).a(dcv.b).a());
   public static final kk<dcl> I = a("blocks_attacks", $$0 -> $$0.a(dcl.a).a(dcl.b).a());
   public static final kk<dhd> J = a("stored_enchantments", $$0 -> $$0.a(dhd.b).a(dhd.c).a());
   public static final kk<dcx> K = a("dyed_color", $$0 -> $$0.a(dcx.a).a(dcx.b));
   public static final kk<ddg> L = a("map_color", $$0 -> $$0.a(ddg.a).a(ddg.b));
   public static final kk<ezt> M = a("map_id", $$0 -> $$0.a(ezt.a).a(ezt.b));
   public static final kk<ddf> N = a("map_decorations", $$0 -> $$0.a(ddf.b).a());
   public static final kk<ddh> O = a("map_post_processing", $$0 -> $$0.a(ddh.d));
   public static final kk<dco> P = a("charged_projectiles", $$0 -> $$0.a(dco.b).a(dco.c).a());
   public static final kk<dcn> Q = a("bundle_contents", $$0 -> $$0.a(dcn.b).a(dcn.c).a());
   public static final kk<dcg> R = a("potion_contents", $$0 -> $$0.a(dcg.c).a(dcg.d).a());
   public static final kk<Float> S = a("potion_duration_scale", $$0 -> $$0.a(azg.n).a(zc.l).a());
   public static final kk<ddm> T = a("suspicious_stew_effects", $$0 -> $$0.a(ddm.c).a(ddm.d).a());
   public static final kk<ddt> U = a("writable_book_content", $$0 -> $$0.a(ddt.e).a(ddt.f).a());
   public static final kk<ddu> V = a("written_book_content", $$0 -> $$0.a(ddu.i).a(ddu.j).a());
   public static final kk<div> W = a("trim", $$0 -> $$0.a(div.a).a(div.b).a());
   public static final kk<dcw> X = a("debug_stick_state", $$0 -> $$0.a(dcw.b).a());
   public static final kk<dcs> Y = a("entity_data", $$0 -> $$0.a(dcs.c).a(dcs.d));
   public static final kk<dcs> Z = a("bucket_entity_data", $$0 -> $$0.a(dcs.b).a(dcs.d));
   public static final kk<dcs> aa = a("block_entity_data", $$0 -> $$0.a(dcs.c).a(dcs.d));
   public static final kk<dda> ab = a("instrument", $$0 -> $$0.a(dda.a).a(dda.b).a());
   public static final kk<ddj> ac = a("provides_trim_material", $$0 -> $$0.a(ddj.a).a(ddj.b).a());
   public static final kk<ddi> ad = a("ominous_bottle_amplifier", $$0 -> $$0.a(ddi.d).a(ddi.e));
   public static final kk<dap> ae = a("jukebox_playable", $$0 -> $$0.a(dap.a).a(dap.b));
   public static final kk<ayc<dyd>> af = a("provides_banner_patterns", $$0 -> $$0.a(ayc.b(mi.aF)).a(ayc.c(mi.aF)).a());
   public static final kk<List<alq<dfb<?>>>> ag = a("recipes", $$0 -> $$0.a(dfb.b.listOf()).a());
   public static final kk<dde> ah = a("lodestone_tracker", $$0 -> $$0.a(dde.a).a(dde.b).a());
   public static final kk<dcy> ai = a("firework_explosion", $$0 -> $$0.a(dcy.c).a(dcy.d).a());
   public static final kk<dcz> aj = a("fireworks", $$0 -> $$0.a(dcz.b).a(dcz.c).a());
   public static final kk<ddk> ak = a("profile", $$0 -> $$0.a(ddk.a).a(ddk.b).a());
   public static final kk<alr> al = a("note_block_sound", $$0 -> $$0.a(alr.a).a(alr.b));
   public static final kk<dye> am = a("banner_patterns", $$0 -> $$0.a(dye.b).a(dye.c).a());
   public static final kk<czi> an = a("base_color", $$0 -> $$0.a(czi.q).a(czi.r));
   public static final kk<dzw> ao = a("pot_decorations", $$0 -> $$0.a(dzw.b).a(dzw.c).a());
   public static final kk<ddc> ap = a("container", $$0 -> $$0.a(ddc.b).a(ddc.c).a());
   public static final kk<dck> aq = a("block_state", $$0 -> $$0.a(dck.b).a(dck.c).a());
   public static final kk<dcj> ar = a("bees", $$0 -> $$0.a(dcj.a).a(dcj.b).a());
   public static final kk<bvd> as = a("lock", $$0 -> $$0.a(bvd.b));
   public static final kk<ddl> at = a("container_loot", $$0 -> $$0.a(ddl.a));
   public static final kk<jg<awx>> au = a("break_sound", $$0 -> $$0.a(awx.b).a(awx.d).a());
   public static final kk<jg<crz>> av = a("villager/variant", $$0 -> $$0.a(crz.h).a(crz.i));
   public static final kk<jg<cna>> aw = a("wolf/variant", $$0 -> $$0.a(cna.c).a(cna.d));
   public static final kk<jg<cmy>> ax = a("wolf/sound_variant", $$0 -> $$0.a(cmy.c).a(cmy.d));
   public static final kk<czi> ay = a("wolf/collar", $$0 -> $$0.a(czi.q).a(czi.r));
   public static final kk<ckk.v> az = a("fox/variant", $$0 -> $$0.a(ckk.v.d).a(ckk.v.e));
   public static final kk<ckw.a> aA = a("salmon/size", $$0 -> $$0.a(ckw.a.e).a(ckw.a.f));
   public static final kk<ckp.b> aB = a("parrot/variant", $$0 -> $$0.a(ckp.b.g).a(ckp.b.i));
   public static final kk<clb.b> aC = a("tropical_fish/pattern", $$0 -> $$0.a(clb.b.m).a(clb.b.n));
   public static final kk<czi> aD = a("tropical_fish/base_color", $$0 -> $$0.a(czi.q).a(czi.r));
   public static final kk<czi> aE = a("tropical_fish/pattern_color", $$0 -> $$0.a(czi.q).a(czi.r));
   public static final kk<ckm.a> aF = a("mooshroom/variant", $$0 -> $$0.a(ckm.a.d).a(ckm.a.e));
   public static final kk<ckv.g> aG = a("rabbit/variant", $$0 -> $$0.a(ckv.g.i).a(ckv.g.k));
   public static final kk<jg<ckr>> aH = a("pig/variant", $$0 -> $$0.a(ckr.c).a(ckr.d));
   public static final kk<jg<ckg>> aI = a("cow/variant", $$0 -> $$0.a(ckg.c).a(ckg.d));
   public static final kk<czl<ckc>> aJ = a("chicken/variant", $$0 -> $$0.a(czl.a(mi.aJ, ckc.c)).a(czl.a(mi.aJ, ckc.d)));
   public static final kk<jg<clu>> aK = a("frog/variant", $$0 -> $$0.a(clu.c).a(clu.d));
   public static final kk<cmn> aL = a("horse/variant", $$0 -> $$0.a(cmn.h).a(cmn.i));
   public static final kk<jg<coj>> aM = a("painting/variant", $$0 -> $$0.a(coj.c).a(coj.d));
   public static final kk<cmh.d> aN = a("llama/variant", $$0 -> $$0.a(cmh.d.f).a(cmh.d.h));
   public static final kk<clk.e> aO = a("axolotl/variant", $$0 -> $$0.a(clk.e.h).a(clk.e.g));
   public static final kk<jg<cjz>> aP = a("cat/variant", $$0 -> $$0.a(cjz.c).a(cjz.d));
   public static final kk<czi> aQ = a("cat/collar", $$0 -> $$0.a(czi.q).a(czi.r));
   public static final kk<czi> aR = a("sheep/color", $$0 -> $$0.a(czi.q).a(czi.r));
   public static final kk<czi> aS = a("shulker/color", $$0 -> $$0.a(czi.q).a(czi.r));
   public static final ki aT = ki.a().a(c, 64).a(j, ddd.a).a(l, dhd.a).a(r, 0).a(o, ddb.a).a(k, dbg.a).a(au, awy.oi).a(q, ddo.c).a();

   public static kk<?> a(jt<kk<?>> $$0) {
      return b;
   }

   private static <T> kk<T> a(String $$0, UnaryOperator<kk.a<T>> $$1) {
      return jt.a(mh.am, $$0, $$1.apply(kk.a()).b());
   }
}
