import java.util.function.BiConsumer;

public class le implements la {
   @Override
   public void generate(BiConsumer<afw, edq.a> $$0) {
      $$0.accept(
         edg.aC,
         edq.b()
            .a(
               edp.a()
                  .a(eha.a(1.0F))
                  .a(edy.a(ckm.wP).a(2))
                  .a(edy.a(ckm.wR).a(2))
                  .a(edy.a(ckm.pX))
                  .a(edy.a(ckm.nL))
                  .a(edy.a(ckm.oB))
                  .a(
                     edy.a(ckm.va)
                        .a(
                           efm.c()
                              .a(bji.p, ehf.a(7.0F, 10.0F))
                              .a(bji.h, ehf.a(7.0F, 10.0F))
                              .a(bji.r, ehf.a(6.0F, 8.0F))
                              .a(bji.o, ehf.a(5.0F, 7.0F))
                              .a(bji.s, ehf.a(10.0F, 20.0F))
                              .a(bji.w, ehf.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         edg.aD,
         edq.b()
            .a(
               edp.a()
                  .a(eha.a(1.0F))
                  .a(edy.a(ckm.wO))
                  .a(edy.a(ckm.wZ))
                  .a(edy.a(ckm.xc))
                  .a(edy.a(ckm.xf))
                  .a(edy.a(ckm.nK))
                  .a(edy.a(ckm.lH))
                  .a(edy.a(ckm.oG))
                  .a(edy.a(ckm.nL))
            )
      );
      $$0.accept(
         edg.aE,
         edq.b()
            .a(
               edp.a()
                  .a(eha.a(1.0F))
                  .a(edy.a(ckm.nL).a(2))
                  .a(edy.a(ckm.oI).a(2))
                  .a(edy.a(ckm.ob).a(2))
                  .a(edy.a(ckm.eB).a(2))
                  .a(edy.a(ckm.pX).a(2))
                  .a(edy.a(ckm.qy).a(2))
                  .a(edy.a(ckm.qF).a(2))
                  .a(edy.a(ckm.qx).a(2))
                  .a(edy.a(ckm.qu).a(2))
                  .a(edy.a(ckm.qv).a(2))
                  .a(edy.a(ckm.wj).a(2))
                  .a(edy.a(ckm.wi).a(2))
                  .a(edy.a(ckm.wf).a(2))
                  .a(edy.a(ckm.wh).a(2))
                  .a(edy.a(ckm.hZ))
                  .a(edy.a(ckm.id))
                  .a(edy.a(ckm.ii))
                  .a(edy.a(ckm.ia))
                  .a(edy.a(ckm.il))
                  .a(edy.a(ckm.ib))
                  .a(edy.a(ckm.ih))
                  .a(edy.a(ckm.pA))
                  .a(edy.a(ckm.pz))
                  .a(edy.a(ckm.rt))
                  .a(edy.a(ckm.nI))
                  .a(edy.a(ckm.oH))
                  .a(edy.a(ckm.ur))
                  .a(edy.a(ckm.cv))
                  .a(edy.a(ckm.tk))
                  .a(edy.a(ckm.oE))
                  .a(edy.a(ckm.tQ))
            )
      );
      $$0.accept(
         edg.aF,
         edq.b()
            .a(
               edp.a()
                  .a(eha.a(1.0F))
                  .a(edy.a(ckm.wS))
                  .a(edy.a(ckm.wT))
                  .a(edy.a(ckm.wV))
                  .a(edy.a(ckm.wW))
                  .a(edy.a(ckm.wX))
                  .a(edy.a(ckm.wY))
                  .a(edy.a(ckm.xd))
                  .a(edy.a(ckm.wI))
                  .a(edy.a(ckm.wL))
                  .a(edy.a(ckm.wJ))
                  .a(edy.a(ckm.wM))
                  .a(edy.a(ckm.uR))
            )
      );
      $$0.accept(
         edg.aG,
         edq.b()
            .a(
               edp.a()
                  .a(eha.a(1.0F))
                  .a(edy.a(ckm.wN))
                  .a(edy.a(ckm.xe))
                  .a(edy.a(ckm.xg))
                  .a(edy.a(ckm.jU))
                  .a(edy.a(ckm.op))
                  .a(edy.a(ckm.nL).a(2))
                  .a(edy.a(ckm.oI).a(2))
                  .a(edy.a(ckm.ob).a(2))
                  .a(edy.a(ckm.nI).a(2))
                  .a(edy.a(ckm.rt).a(2))
            )
      );
      $$0.accept(
         edg.aH,
         edq.b()
            .a(
               edp.a()
                  .a(eha.a(1.0F))
                  .a(edy.a(ckm.wQ))
                  .a(edy.a(ckm.wU))
                  .a(edy.a(ckm.xa))
                  .a(edy.a(ckm.xb))
                  .a(edy.a(ckm.op))
                  .a(edy.a(ckm.nL).a(2))
                  .a(edy.a(ckm.oI).a(2))
                  .a(edy.a(ckm.ob).a(2))
                  .a(edy.a(ckm.nI).a(2))
                  .a(edy.a(ckm.rt).a(2))
            )
      );
   }
}
