import java.util.Optional;
import java.util.stream.IntStream;

public class lg {
   public static final lf a = a("cube", li.c, li.j, li.k, li.l, li.m, li.n, li.o);
   public static final lf b = a("cube_directional", li.c, li.j, li.k, li.l, li.m, li.n, li.o);
   public static final lf c = a("cube_all", li.a);
   public static final lf d = a("cube_mirrored_all", "_mirrored", li.a);
   public static final lf e = a("cube_north_west_mirrored_all", "_north_west_mirrored", li.a);
   public static final lf f = a("cube_column_uv_locked_x", "_x", li.d, li.i);
   public static final lf g = a("cube_column_uv_locked_y", "_y", li.d, li.i);
   public static final lf h = a("cube_column_uv_locked_z", "_z", li.d, li.i);
   public static final lf i = a("cube_column", li.d, li.i);
   public static final lf j = a("cube_column_horizontal", "_horizontal", li.d, li.i);
   public static final lf k = a("cube_column_mirrored", "_mirrored", li.d, li.i);
   public static final lf l = a("cube_top", li.f, li.i);
   public static final lf m = a("cube_bottom_top", li.f, li.e, li.i);
   public static final lf n = a("orientable", li.f, li.g, li.i);
   public static final lf o = a("orientable_with_bottom", li.f, li.e, li.i, li.g);
   public static final lf p = a("orientable_vertical", "_vertical", li.g, li.i);
   public static final lf q = a("button", li.b);
   public static final lf r = a("button_pressed", "_pressed", li.b);
   public static final lf s = a("button_inventory", "_inventory", li.b);
   public static final lf t = a("door_bottom_left", "_bottom_left", li.f, li.e);
   public static final lf u = a("door_bottom_left_open", "_bottom_left_open", li.f, li.e);
   public static final lf v = a("door_bottom_right", "_bottom_right", li.f, li.e);
   public static final lf w = a("door_bottom_right_open", "_bottom_right_open", li.f, li.e);
   public static final lf x = a("door_top_left", "_top_left", li.f, li.e);
   public static final lf y = a("door_top_left_open", "_top_left_open", li.f, li.e);
   public static final lf z = a("door_top_right", "_top_right", li.f, li.e);
   public static final lf A = a("door_top_right_open", "_top_right_open", li.f, li.e);
   public static final lf B = a("custom_fence_post", "_post", li.b, li.c);
   public static final lf C = a("custom_fence_side_north", "_side_north", li.b);
   public static final lf D = a("custom_fence_side_east", "_side_east", li.b);
   public static final lf E = a("custom_fence_side_south", "_side_south", li.b);
   public static final lf F = a("custom_fence_side_west", "_side_west", li.b);
   public static final lf G = a("custom_fence_inventory", "_inventory", li.b);
   public static final lf H = a("fence_post", "_post", li.b);
   public static final lf I = a("fence_side", "_side", li.b);
   public static final lf J = a("fence_inventory", "_inventory", li.b);
   public static final lf K = a("template_wall_post", "_post", li.r);
   public static final lf L = a("template_wall_side", "_side", li.r);
   public static final lf M = a("template_wall_side_tall", "_side_tall", li.r);
   public static final lf N = a("wall_inventory", "_inventory", li.r);
   public static final lf O = a("template_custom_fence_gate", li.b, li.c);
   public static final lf P = a("template_custom_fence_gate_open", "_open", li.b, li.c);
   public static final lf Q = a("template_custom_fence_gate_wall", "_wall", li.b, li.c);
   public static final lf R = a("template_custom_fence_gate_wall_open", "_wall_open", li.b, li.c);
   public static final lf S = a("template_fence_gate", li.b);
   public static final lf T = a("template_fence_gate_open", "_open", li.b);
   public static final lf U = a("template_fence_gate_wall", "_wall", li.b);
   public static final lf V = a("template_fence_gate_wall_open", "_wall_open", li.b);
   public static final lf W = a("pressure_plate_up", li.b);
   public static final lf X = a("pressure_plate_down", "_down", li.b);
   public static final lf Y = a(li.c);
   public static final lf Z = a("slab", li.e, li.f, li.i);
   public static final lf aa = a("slab_top", "_top", li.e, li.f, li.i);
   public static final lf ab = a("leaves", li.a);
   public static final lf ac = a("stairs", li.e, li.f, li.i);
   public static final lf ad = a("inner_stairs", "_inner", li.e, li.f, li.i);
   public static final lf ae = a("outer_stairs", "_outer", li.e, li.f, li.i);
   public static final lf af = a("template_trapdoor_top", "_top", li.b);
   public static final lf ag = a("template_trapdoor_bottom", "_bottom", li.b);
   public static final lf ah = a("template_trapdoor_open", "_open", li.b);
   public static final lf ai = a("template_orientable_trapdoor_top", "_top", li.b);
   public static final lf aj = a("template_orientable_trapdoor_bottom", "_bottom", li.b);
   public static final lf ak = a("template_orientable_trapdoor_open", "_open", li.b);
   public static final lf al = a("pointed_dripstone", li.p);
   public static final lf am = a("cross", li.p);
   public static final lf an = a("tinted_cross", li.p);
   public static final lf ao = a("flower_pot_cross", li.q);
   public static final lf ap = a("tinted_flower_pot_cross", li.q);
   public static final lf aq = a("rail_flat", li.s);
   public static final lf ar = a("rail_curved", "_corner", li.s);
   public static final lf as = a("template_rail_raised_ne", "_raised_ne", li.s);
   public static final lf at = a("template_rail_raised_sw", "_raised_sw", li.s);
   public static final lf au = a("carpet", li.t);
   public static final lf av = a("flowerbed_1", "_1", li.P, li.y);
   public static final lf aw = a("flowerbed_2", "_2", li.P, li.y);
   public static final lf ax = a("flowerbed_3", "_3", li.P, li.y);
   public static final lf ay = a("flowerbed_4", "_4", li.P, li.y);
   public static final lf az = a("coral_fan", li.x);
   public static final lf aA = a("coral_wall_fan", li.x);
   public static final lf aB = a("template_glazed_terracotta", li.u);
   public static final lf aC = a("template_chorus_flower", li.b);
   public static final lf aD = a("template_daylight_detector", li.f, li.i);
   public static final lf aE = a("template_glass_pane_noside", "_noside", li.v);
   public static final lf aF = a("template_glass_pane_noside_alt", "_noside_alt", li.v);
   public static final lf aG = a("template_glass_pane_post", "_post", li.v, li.w);
   public static final lf aH = a("template_glass_pane_side", "_side", li.v, li.w);
   public static final lf aI = a("template_glass_pane_side_alt", "_side_alt", li.v, li.w);
   public static final lf aJ = a("template_command_block", li.g, li.h, li.i);
   public static final lf aK = a("template_chiseled_bookshelf_slot_top_left", "_slot_top_left", li.b);
   public static final lf aL = a("template_chiseled_bookshelf_slot_top_mid", "_slot_top_mid", li.b);
   public static final lf aM = a("template_chiseled_bookshelf_slot_top_right", "_slot_top_right", li.b);
   public static final lf aN = a("template_chiseled_bookshelf_slot_bottom_left", "_slot_bottom_left", li.b);
   public static final lf aO = a("template_chiseled_bookshelf_slot_bottom_mid", "_slot_bottom_mid", li.b);
   public static final lf aP = a("template_chiseled_bookshelf_slot_bottom_right", "_slot_bottom_right", li.b);
   public static final lf aQ = a("template_anvil", li.f);
   public static final lf[] aR = IntStream.range(0, 8).mapToObj($$0 -> a("stem_growth" + $$0, "_stage" + $$0, li.y)).toArray(lf[]::new);
   public static final lf aS = a("stem_fruit", li.y, li.z);
   public static final lf aT = a("crop", li.A);
   public static final lf aU = a("template_farmland", li.B, li.f);
   public static final lf aV = a("template_fire_floor", li.C);
   public static final lf aW = a("template_fire_side", li.C);
   public static final lf aX = a("template_fire_side_alt", li.C);
   public static final lf aY = a("template_fire_up", li.C);
   public static final lf aZ = a("template_fire_up_alt", li.C);
   public static final lf ba = a("template_campfire", li.C, li.K);
   public static final lf bb = a("template_lantern", li.D);
   public static final lf bc = a("template_hanging_lantern", "_hanging", li.D);
   public static final lf bd = a("template_torch", li.G);
   public static final lf be = a("template_torch_wall", li.G);
   public static final lf bf = a("template_piston", li.E, li.e, li.i);
   public static final lf bg = a("template_piston_head", li.E, li.i, li.F);
   public static final lf bh = a("template_piston_head_short", li.E, li.i, li.F);
   public static final lf bi = a("template_seagrass", li.b);
   public static final lf bj = a("template_turtle_egg", li.a);
   public static final lf bk = a("template_two_turtle_eggs", li.a);
   public static final lf bl = a("template_three_turtle_eggs", li.a);
   public static final lf bm = a("template_four_turtle_eggs", li.a);
   public static final lf bn = a("template_single_face", li.b);
   public static final lf bo = a("template_cauldron_level1", li.N, li.M, li.c, li.f, li.e, li.i);
   public static final lf bp = a("template_cauldron_level2", li.N, li.M, li.c, li.f, li.e, li.i);
   public static final lf bq = a("template_cauldron_full", li.N, li.M, li.c, li.f, li.e, li.i);
   public static final lf br = a("template_azalea", li.f, li.i);
   public static final lf bs = a("template_potted_azalea_bush", li.q, li.f, li.i);
   public static final lf bt = a("template_potted_azalea_bush", li.q, li.f, li.i);
   public static final lf bu = a("sniffer_egg", li.f, li.e, li.j, li.k, li.l, li.m);
   public static final lf bv = b("generated", li.H);
   public static final lf bw = b("template_music_disc", li.H);
   public static final lf bx = b("handheld", li.H);
   public static final lf by = b("handheld_rod", li.H);
   public static final lf bz = b("generated", li.H, li.I);
   public static final lf bA = b("generated", li.H, li.I, li.J);
   public static final lf bB = b("template_shulker_box", li.c);
   public static final lf bC = b("template_bed", li.c);
   public static final lf bD = b("template_banner");
   public static final lf bE = b("template_skull");
   public static final lf bF = a("template_candle", li.a, li.c);
   public static final lf bG = a("template_two_candles", li.a, li.c);
   public static final lf bH = a("template_three_candles", li.a, li.c);
   public static final lf bI = a("template_four_candles", li.a, li.c);
   public static final lf bJ = a("template_cake_with_candle", li.L, li.e, li.i, li.f, li.c);
   public static final lf bK = a("template_sculk_shrieker", li.e, li.i, li.f, li.c, li.O);

   private static lf a(li... $$0) {
      return new lf(Optional.empty(), Optional.empty(), $$0);
   }

   private static lf a(String $$0, li... $$1) {
      return new lf(Optional.of(new acq("minecraft", "block/" + $$0)), Optional.empty(), $$1);
   }

   private static lf b(String $$0, li... $$1) {
      return new lf(Optional.of(new acq("minecraft", "item/" + $$0)), Optional.empty(), $$1);
   }

   private static lf a(String $$0, String $$1, li... $$2) {
      return new lf(Optional.of(new acq("minecraft", "block/" + $$0)), Optional.of($$1), $$2);
   }
}
