import java.util.function.BiConsumer;

public class lg implements la {
   @Override
   public void generate(BiConsumer<agg, eet.a> $$0) {
      $$0.accept(
         eej.aC,
         eet.b()
            .a(
               ees.a()
                  .a(eid.a(1.0F))
                  .a(efb.a(cle.wQ).a(2))
                  .a(efb.a(cle.wS).a(2))
                  .a(efb.a(cle.pX))
                  .a(efb.a(cle.nL))
                  .a(efb.a(cle.oB))
                  .a(
                     efb.a(cle.vb)
                        .a(
                           egp.c()
                              .a(bjx.p, eii.a(7.0F, 10.0F))
                              .a(bjx.h, eii.a(7.0F, 10.0F))
                              .a(bjx.r, eii.a(6.0F, 8.0F))
                              .a(bjx.o, eii.a(5.0F, 7.0F))
                              .a(bjx.s, eii.a(10.0F, 20.0F))
                              .a(bjx.w, eii.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         eej.aD,
         eet.b()
            .a(
               ees.a()
                  .a(eid.a(1.0F))
                  .a(efb.a(cle.wP))
                  .a(efb.a(cle.xa))
                  .a(efb.a(cle.xd))
                  .a(efb.a(cle.xg))
                  .a(efb.a(cle.nK))
                  .a(efb.a(cle.lH))
                  .a(efb.a(cle.oG))
                  .a(efb.a(cle.nL))
            )
      );
      $$0.accept(
         eej.aE,
         eet.b()
            .a(
               ees.a()
                  .a(eid.a(1.0F))
                  .a(efb.a(cle.nL).a(2))
                  .a(efb.a(cle.oI).a(2))
                  .a(efb.a(cle.ob).a(2))
                  .a(efb.a(cle.eB).a(2))
                  .a(efb.a(cle.pX).a(2))
                  .a(efb.a(cle.qy).a(2))
                  .a(efb.a(cle.qF).a(2))
                  .a(efb.a(cle.qx).a(2))
                  .a(efb.a(cle.qu).a(2))
                  .a(efb.a(cle.qv).a(2))
                  .a(efb.a(cle.wk).a(2))
                  .a(efb.a(cle.wj).a(2))
                  .a(efb.a(cle.wg).a(2))
                  .a(efb.a(cle.wi).a(2))
                  .a(efb.a(cle.hZ))
                  .a(efb.a(cle.id))
                  .a(efb.a(cle.ii))
                  .a(efb.a(cle.ia))
                  .a(efb.a(cle.il))
                  .a(efb.a(cle.ib))
                  .a(efb.a(cle.ih))
                  .a(efb.a(cle.pA))
                  .a(efb.a(cle.pz))
                  .a(efb.a(cle.ru))
                  .a(efb.a(cle.nI))
                  .a(efb.a(cle.oH))
                  .a(efb.a(cle.us))
                  .a(efb.a(cle.cv))
                  .a(efb.a(cle.tl))
                  .a(efb.a(cle.oE))
                  .a(efb.a(cle.tR))
            )
      );
      $$0.accept(
         eej.aF,
         eet.b()
            .a(
               ees.a()
                  .a(eid.a(1.0F))
                  .a(efb.a(cle.wT))
                  .a(efb.a(cle.wU))
                  .a(efb.a(cle.wW))
                  .a(efb.a(cle.wX))
                  .a(efb.a(cle.wY))
                  .a(efb.a(cle.wZ))
                  .a(efb.a(cle.xe))
                  .a(efb.a(cle.wJ))
                  .a(efb.a(cle.wM))
                  .a(efb.a(cle.wK))
                  .a(efb.a(cle.wN))
                  .a(efb.a(cle.uS))
            )
      );
      $$0.accept(
         eej.aG,
         eet.b()
            .a(
               ees.a()
                  .a(eid.a(1.0F))
                  .a(efb.a(cle.wO))
                  .a(efb.a(cle.xf))
                  .a(efb.a(cle.xh))
                  .a(efb.a(cle.jU))
                  .a(efb.a(cle.op))
                  .a(efb.a(cle.nL).a(2))
                  .a(efb.a(cle.oI).a(2))
                  .a(efb.a(cle.ob).a(2))
                  .a(efb.a(cle.nI).a(2))
                  .a(efb.a(cle.ru).a(2))
            )
      );
      $$0.accept(
         eej.aH,
         eet.b()
            .a(
               ees.a()
                  .a(eid.a(1.0F))
                  .a(efb.a(cle.wR))
                  .a(efb.a(cle.wV))
                  .a(efb.a(cle.xb))
                  .a(efb.a(cle.xc))
                  .a(efb.a(cle.op))
                  .a(efb.a(cle.nL).a(2))
                  .a(efb.a(cle.oI).a(2))
                  .a(efb.a(cle.ob).a(2))
                  .a(efb.a(cle.nI).a(2))
                  .a(efb.a(cle.ru).a(2))
            )
      );
   }
}
