import java.util.function.BiConsumer;

public class lk implements ld {
   @Override
   public void generate(BiConsumer<agt, egm.a> $$0) {
      $$0.accept(
         egc.aO,
         egm.b()
            .a(
               egl.a()
                  .a(ejw.a(1.0F))
                  .a(egu.a(cmk.xC).a(2))
                  .a(egu.a(cmk.xE).a(2))
                  .a(egu.a(cmk.qI))
                  .a(egu.a(cmk.ow))
                  .a(egu.a(cmk.pm))
                  .a(
                     egu.a(cmk.vN)
                        .a(
                           eii.c()
                              .a(bku.p, ekb.a(7.0F, 10.0F))
                              .a(bku.h, ekb.a(7.0F, 10.0F))
                              .a(bku.r, ekb.a(6.0F, 8.0F))
                              .a(bku.o, ekb.a(5.0F, 7.0F))
                              .a(bku.s, ekb.a(10.0F, 20.0F))
                              .a(bku.w, ekb.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         egc.aP,
         egm.b()
            .a(
               egl.a()
                  .a(ejw.a(1.0F))
                  .a(egu.a(cmk.xB))
                  .a(egu.a(cmk.xM))
                  .a(egu.a(cmk.xP))
                  .a(egu.a(cmk.xS))
                  .a(egu.a(cmk.ov))
                  .a(egu.a(cmk.mc))
                  .a(egu.a(cmk.pr))
                  .a(egu.a(cmk.ow))
            )
      );
      $$0.accept(
         egc.aQ,
         egm.b()
            .a(
               egl.a()
                  .a(ejw.a(1.0F))
                  .a(egu.a(cmk.ow).a(2))
                  .a(egu.a(cmk.pt).a(2))
                  .a(egu.a(cmk.oM).a(2))
                  .a(egu.a(cmk.eW).a(2))
                  .a(egu.a(cmk.qI).a(2))
                  .a(egu.a(cmk.rj).a(2))
                  .a(egu.a(cmk.rq).a(2))
                  .a(egu.a(cmk.ri).a(2))
                  .a(egu.a(cmk.rf).a(2))
                  .a(egu.a(cmk.rg).a(2))
                  .a(egu.a(cmk.wW).a(2))
                  .a(egu.a(cmk.wV).a(2))
                  .a(egu.a(cmk.wS).a(2))
                  .a(egu.a(cmk.wU).a(2))
                  .a(egu.a(cmk.iu))
                  .a(egu.a(cmk.iy))
                  .a(egu.a(cmk.iD))
                  .a(egu.a(cmk.iv))
                  .a(egu.a(cmk.iG))
                  .a(egu.a(cmk.iw))
                  .a(egu.a(cmk.iC))
                  .a(egu.a(cmk.ql))
                  .a(egu.a(cmk.qk))
                  .a(egu.a(cmk.sf))
                  .a(egu.a(cmk.ot))
                  .a(egu.a(cmk.ps))
                  .a(egu.a(cmk.ve))
                  .a(egu.a(cmk.cQ))
                  .a(egu.a(cmk.tX))
                  .a(egu.a(cmk.pp))
                  .a(egu.a(cmk.uD))
            )
      );
      $$0.accept(
         egc.aR,
         egm.b()
            .a(
               egl.a()
                  .a(ejw.a(1.0F))
                  .a(egu.a(cmk.xF))
                  .a(egu.a(cmk.xG))
                  .a(egu.a(cmk.xI))
                  .a(egu.a(cmk.xJ))
                  .a(egu.a(cmk.xK))
                  .a(egu.a(cmk.xL))
                  .a(egu.a(cmk.xQ))
                  .a(egu.a(cmk.xv))
                  .a(egu.a(cmk.xy))
                  .a(egu.a(cmk.xw))
                  .a(egu.a(cmk.xz))
                  .a(egu.a(cmk.vE))
            )
      );
      $$0.accept(
         egc.aS,
         egm.b()
            .a(
               egl.a()
                  .a(ejw.a(1.0F))
                  .a(egu.a(cmk.xA))
                  .a(egu.a(cmk.xR))
                  .a(egu.a(cmk.xT))
                  .a(egu.a(cmk.kp))
                  .a(egu.a(cmk.pa))
                  .a(egu.a(cmk.ow).a(2))
                  .a(egu.a(cmk.pt).a(2))
                  .a(egu.a(cmk.oM).a(2))
                  .a(egu.a(cmk.ot).a(2))
                  .a(egu.a(cmk.sf).a(2))
            )
      );
      $$0.accept(
         egc.aT,
         egm.b()
            .a(
               egl.a()
                  .a(ejw.a(1.0F))
                  .a(egu.a(cmk.xD))
                  .a(egu.a(cmk.xH))
                  .a(egu.a(cmk.xN))
                  .a(egu.a(cmk.xO))
                  .a(egu.a(cmk.pa))
                  .a(egu.a(cmk.ow).a(2))
                  .a(egu.a(cmk.pt).a(2))
                  .a(egu.a(cmk.oM).a(2))
                  .a(egu.a(cmk.ot).a(2))
                  .a(egu.a(cmk.sf).a(2))
            )
      );
   }
}
