import java.util.function.BiConsumer;

public class lm implements lf {
   @Override
   public void generate(BiConsumer<ahd, egx.a> $$0) {
      $$0.accept(
         egn.aO,
         egx.b()
            .a(
               egw.a()
                  .a(ekh.a(1.0F))
                  .a(ehf.a(cmu.xC).a(2))
                  .a(ehf.a(cmu.xE).a(2))
                  .a(ehf.a(cmu.qI))
                  .a(ehf.a(cmu.ow))
                  .a(ehf.a(cmu.pm))
                  .a(
                     ehf.a(cmu.vN)
                        .a(
                           eit.c()
                              .a(ble.p, ekm.a(7.0F, 10.0F))
                              .a(ble.h, ekm.a(7.0F, 10.0F))
                              .a(ble.r, ekm.a(6.0F, 8.0F))
                              .a(ble.o, ekm.a(5.0F, 7.0F))
                              .a(ble.s, ekm.a(10.0F, 20.0F))
                              .a(ble.w, ekm.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         egn.aP,
         egx.b()
            .a(
               egw.a()
                  .a(ekh.a(1.0F))
                  .a(ehf.a(cmu.xB))
                  .a(ehf.a(cmu.xM))
                  .a(ehf.a(cmu.xP))
                  .a(ehf.a(cmu.xS))
                  .a(ehf.a(cmu.ov))
                  .a(ehf.a(cmu.mc))
                  .a(ehf.a(cmu.pr))
                  .a(ehf.a(cmu.ow))
            )
      );
      $$0.accept(
         egn.aQ,
         egx.b()
            .a(
               egw.a()
                  .a(ekh.a(1.0F))
                  .a(ehf.a(cmu.ow).a(2))
                  .a(ehf.a(cmu.pt).a(2))
                  .a(ehf.a(cmu.oM).a(2))
                  .a(ehf.a(cmu.eW).a(2))
                  .a(ehf.a(cmu.qI).a(2))
                  .a(ehf.a(cmu.rj).a(2))
                  .a(ehf.a(cmu.rq).a(2))
                  .a(ehf.a(cmu.ri).a(2))
                  .a(ehf.a(cmu.rf).a(2))
                  .a(ehf.a(cmu.rg).a(2))
                  .a(ehf.a(cmu.wW).a(2))
                  .a(ehf.a(cmu.wV).a(2))
                  .a(ehf.a(cmu.wS).a(2))
                  .a(ehf.a(cmu.wU).a(2))
                  .a(ehf.a(cmu.iu))
                  .a(ehf.a(cmu.iy))
                  .a(ehf.a(cmu.iD))
                  .a(ehf.a(cmu.iv))
                  .a(ehf.a(cmu.iG))
                  .a(ehf.a(cmu.iw))
                  .a(ehf.a(cmu.iC))
                  .a(ehf.a(cmu.ql))
                  .a(ehf.a(cmu.qk))
                  .a(ehf.a(cmu.sf))
                  .a(ehf.a(cmu.ot))
                  .a(ehf.a(cmu.ps))
                  .a(ehf.a(cmu.ve))
                  .a(ehf.a(cmu.cQ))
                  .a(ehf.a(cmu.tX))
                  .a(ehf.a(cmu.pp))
                  .a(ehf.a(cmu.uD))
            )
      );
      $$0.accept(
         egn.aR,
         egx.b()
            .a(
               egw.a()
                  .a(ekh.a(1.0F))
                  .a(ehf.a(cmu.xF))
                  .a(ehf.a(cmu.xG))
                  .a(ehf.a(cmu.xI))
                  .a(ehf.a(cmu.xJ))
                  .a(ehf.a(cmu.xK))
                  .a(ehf.a(cmu.xL))
                  .a(ehf.a(cmu.xQ))
                  .a(ehf.a(cmu.xv))
                  .a(ehf.a(cmu.xy))
                  .a(ehf.a(cmu.xw))
                  .a(ehf.a(cmu.xz))
                  .a(ehf.a(cmu.vE))
            )
      );
      $$0.accept(
         egn.aS,
         egx.b()
            .a(
               egw.a()
                  .a(ekh.a(1.0F))
                  .a(ehf.a(cmu.xA))
                  .a(ehf.a(cmu.xR))
                  .a(ehf.a(cmu.xT))
                  .a(ehf.a(cmu.kp))
                  .a(ehf.a(cmu.pa))
                  .a(ehf.a(cmu.ow).a(2))
                  .a(ehf.a(cmu.pt).a(2))
                  .a(ehf.a(cmu.oM).a(2))
                  .a(ehf.a(cmu.ot).a(2))
                  .a(ehf.a(cmu.sf).a(2))
            )
      );
      $$0.accept(
         egn.aT,
         egx.b()
            .a(
               egw.a()
                  .a(ekh.a(1.0F))
                  .a(ehf.a(cmu.xD))
                  .a(ehf.a(cmu.xH))
                  .a(ehf.a(cmu.xN))
                  .a(ehf.a(cmu.xO))
                  .a(ehf.a(cmu.pa))
                  .a(ehf.a(cmu.ow).a(2))
                  .a(ehf.a(cmu.pt).a(2))
                  .a(ehf.a(cmu.oM).a(2))
                  .a(ehf.a(cmu.ot).a(2))
                  .a(ehf.a(cmu.sf).a(2))
            )
      );
   }
}
