import java.util.function.BiConsumer;

public class lo implements lh {
   @Override
   public void generate(BiConsumer<ahg, ehe.a> $$0) {
      $$0.accept(
         egu.aO,
         ehe.b()
            .a(
               ehd.a()
                  .a(eko.a(1.0F))
                  .a(ehm.a(cnb.xC).a(2))
                  .a(ehm.a(cnb.xE).a(2))
                  .a(ehm.a(cnb.qI))
                  .a(ehm.a(cnb.ow))
                  .a(ehm.a(cnb.pm))
                  .a(
                     ehm.a(cnb.vN)
                        .a(
                           eja.c()
                              .a(blk.p, ekt.a(7.0F, 10.0F))
                              .a(blk.h, ekt.a(7.0F, 10.0F))
                              .a(blk.r, ekt.a(6.0F, 8.0F))
                              .a(blk.o, ekt.a(5.0F, 7.0F))
                              .a(blk.s, ekt.a(10.0F, 20.0F))
                              .a(blk.w, ekt.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         egu.aP,
         ehe.b()
            .a(
               ehd.a()
                  .a(eko.a(1.0F))
                  .a(ehm.a(cnb.xB))
                  .a(ehm.a(cnb.xM))
                  .a(ehm.a(cnb.xP))
                  .a(ehm.a(cnb.xS))
                  .a(ehm.a(cnb.ov))
                  .a(ehm.a(cnb.mc))
                  .a(ehm.a(cnb.pr))
                  .a(ehm.a(cnb.ow))
            )
      );
      $$0.accept(
         egu.aQ,
         ehe.b()
            .a(
               ehd.a()
                  .a(eko.a(1.0F))
                  .a(ehm.a(cnb.ow).a(2))
                  .a(ehm.a(cnb.pt).a(2))
                  .a(ehm.a(cnb.oM).a(2))
                  .a(ehm.a(cnb.eW).a(2))
                  .a(ehm.a(cnb.qI).a(2))
                  .a(ehm.a(cnb.rj).a(2))
                  .a(ehm.a(cnb.rq).a(2))
                  .a(ehm.a(cnb.ri).a(2))
                  .a(ehm.a(cnb.rf).a(2))
                  .a(ehm.a(cnb.rg).a(2))
                  .a(ehm.a(cnb.wW).a(2))
                  .a(ehm.a(cnb.wV).a(2))
                  .a(ehm.a(cnb.wS).a(2))
                  .a(ehm.a(cnb.wU).a(2))
                  .a(ehm.a(cnb.iu))
                  .a(ehm.a(cnb.iy))
                  .a(ehm.a(cnb.iD))
                  .a(ehm.a(cnb.iv))
                  .a(ehm.a(cnb.iG))
                  .a(ehm.a(cnb.iw))
                  .a(ehm.a(cnb.iC))
                  .a(ehm.a(cnb.ql))
                  .a(ehm.a(cnb.qk))
                  .a(ehm.a(cnb.sf))
                  .a(ehm.a(cnb.ot))
                  .a(ehm.a(cnb.ps))
                  .a(ehm.a(cnb.ve))
                  .a(ehm.a(cnb.cQ))
                  .a(ehm.a(cnb.tX))
                  .a(ehm.a(cnb.pp))
                  .a(ehm.a(cnb.uD))
            )
      );
      $$0.accept(
         egu.aR,
         ehe.b()
            .a(
               ehd.a()
                  .a(eko.a(1.0F))
                  .a(ehm.a(cnb.xF))
                  .a(ehm.a(cnb.xG))
                  .a(ehm.a(cnb.xI))
                  .a(ehm.a(cnb.xJ))
                  .a(ehm.a(cnb.xK))
                  .a(ehm.a(cnb.xL))
                  .a(ehm.a(cnb.xQ))
                  .a(ehm.a(cnb.xv))
                  .a(ehm.a(cnb.xy))
                  .a(ehm.a(cnb.xw))
                  .a(ehm.a(cnb.xz))
                  .a(ehm.a(cnb.vE))
            )
      );
      $$0.accept(
         egu.aS,
         ehe.b()
            .a(
               ehd.a()
                  .a(eko.a(1.0F))
                  .a(ehm.a(cnb.xA))
                  .a(ehm.a(cnb.xR))
                  .a(ehm.a(cnb.xT))
                  .a(ehm.a(cnb.kp))
                  .a(ehm.a(cnb.pa))
                  .a(ehm.a(cnb.ow).a(2))
                  .a(ehm.a(cnb.pt).a(2))
                  .a(ehm.a(cnb.oM).a(2))
                  .a(ehm.a(cnb.ot).a(2))
                  .a(ehm.a(cnb.sf).a(2))
            )
      );
      $$0.accept(
         egu.aT,
         ehe.b()
            .a(
               ehd.a()
                  .a(eko.a(1.0F))
                  .a(ehm.a(cnb.xD))
                  .a(ehm.a(cnb.xH))
                  .a(ehm.a(cnb.xN))
                  .a(ehm.a(cnb.xO))
                  .a(ehm.a(cnb.pa))
                  .a(ehm.a(cnb.ow).a(2))
                  .a(ehm.a(cnb.pt).a(2))
                  .a(ehm.a(cnb.oM).a(2))
                  .a(ehm.a(cnb.ot).a(2))
                  .a(ehm.a(cnb.sf).a(2))
            )
      );
   }
}
