import java.util.function.BiConsumer;

public class lo implements lh {
   @Override
   public void generate(BiConsumer<ahh, ehn.a> $$0) {
      $$0.accept(
         ehd.aO,
         ehn.b()
            .a(
               ehm.a()
                  .a(ekx.a(1.0F))
                  .a(ehv.a(cnj.xF).a(2))
                  .a(ehv.a(cnj.xH).a(2))
                  .a(ehv.a(cnj.qK))
                  .a(ehv.a(cnj.oy))
                  .a(ehv.a(cnj.po))
                  .a(
                     ehv.a(cnj.vQ)
                        .a(
                           ejj.c()
                              .a(bll.p, elc.a(7.0F, 10.0F))
                              .a(bll.h, elc.a(7.0F, 10.0F))
                              .a(bll.r, elc.a(6.0F, 8.0F))
                              .a(bll.o, elc.a(5.0F, 7.0F))
                              .a(bll.s, elc.a(10.0F, 20.0F))
                              .a(bll.w, elc.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ehd.aP,
         ehn.b()
            .a(
               ehm.a()
                  .a(ekx.a(1.0F))
                  .a(ehv.a(cnj.xE))
                  .a(ehv.a(cnj.xP))
                  .a(ehv.a(cnj.xS))
                  .a(ehv.a(cnj.xV))
                  .a(ehv.a(cnj.ox))
                  .a(ehv.a(cnj.mc))
                  .a(ehv.a(cnj.pt))
                  .a(ehv.a(cnj.oy))
            )
      );
      $$0.accept(
         ehd.aQ,
         ehn.b()
            .a(
               ehm.a()
                  .a(ekx.a(1.0F))
                  .a(ehv.a(cnj.oy).a(2))
                  .a(ehv.a(cnj.pv).a(2))
                  .a(ehv.a(cnj.oO).a(2))
                  .a(ehv.a(cnj.eW).a(2))
                  .a(ehv.a(cnj.qK).a(2))
                  .a(ehv.a(cnj.rl).a(2))
                  .a(ehv.a(cnj.rs).a(2))
                  .a(ehv.a(cnj.rk).a(2))
                  .a(ehv.a(cnj.rh).a(2))
                  .a(ehv.a(cnj.ri).a(2))
                  .a(ehv.a(cnj.wZ).a(2))
                  .a(ehv.a(cnj.wY).a(2))
                  .a(ehv.a(cnj.wV).a(2))
                  .a(ehv.a(cnj.wX).a(2))
                  .a(ehv.a(cnj.iu))
                  .a(ehv.a(cnj.iy))
                  .a(ehv.a(cnj.iD))
                  .a(ehv.a(cnj.iv))
                  .a(ehv.a(cnj.iG))
                  .a(ehv.a(cnj.iw))
                  .a(ehv.a(cnj.iC))
                  .a(ehv.a(cnj.qn))
                  .a(ehv.a(cnj.qm))
                  .a(ehv.a(cnj.sh))
                  .a(ehv.a(cnj.ov))
                  .a(ehv.a(cnj.pu))
                  .a(ehv.a(cnj.vh))
                  .a(ehv.a(cnj.cQ))
                  .a(ehv.a(cnj.ua))
                  .a(ehv.a(cnj.pr))
                  .a(ehv.a(cnj.uG))
            )
      );
      $$0.accept(
         ehd.aR,
         ehn.b()
            .a(
               ehm.a()
                  .a(ekx.a(1.0F))
                  .a(ehv.a(cnj.xI))
                  .a(ehv.a(cnj.xJ))
                  .a(ehv.a(cnj.xL))
                  .a(ehv.a(cnj.xM))
                  .a(ehv.a(cnj.xN))
                  .a(ehv.a(cnj.xO))
                  .a(ehv.a(cnj.xT))
                  .a(ehv.a(cnj.xy))
                  .a(ehv.a(cnj.xB))
                  .a(ehv.a(cnj.xz))
                  .a(ehv.a(cnj.xC))
                  .a(ehv.a(cnj.vH))
            )
      );
      $$0.accept(
         ehd.aS,
         ehn.b()
            .a(
               ehm.a()
                  .a(ekx.a(1.0F))
                  .a(ehv.a(cnj.xD))
                  .a(ehv.a(cnj.xU))
                  .a(ehv.a(cnj.xW))
                  .a(ehv.a(cnj.kp))
                  .a(ehv.a(cnj.pc))
                  .a(ehv.a(cnj.oy).a(2))
                  .a(ehv.a(cnj.pv).a(2))
                  .a(ehv.a(cnj.oO).a(2))
                  .a(ehv.a(cnj.ov).a(2))
                  .a(ehv.a(cnj.sh).a(2))
            )
      );
      $$0.accept(
         ehd.aT,
         ehn.b()
            .a(
               ehm.a()
                  .a(ekx.a(1.0F))
                  .a(ehv.a(cnj.xG))
                  .a(ehv.a(cnj.xK))
                  .a(ehv.a(cnj.xQ))
                  .a(ehv.a(cnj.xR))
                  .a(ehv.a(cnj.pc))
                  .a(ehv.a(cnj.oy).a(2))
                  .a(ehv.a(cnj.pv).a(2))
                  .a(ehv.a(cnj.oO).a(2))
                  .a(ehv.a(cnj.ov).a(2))
                  .a(ehv.a(cnj.sh).a(2))
            )
      );
   }
}
