import java.util.function.BiConsumer;

public class lq implements lj {
   @Override
   public void generate(BiConsumer<aiy, ejk.a> $$0) {
      $$0.accept(
         eja.aO,
         ejk.b()
            .a(
               ejj.a()
                  .a(emu.a(1.0F))
                  .a(ejs.a(cpg.xF).a(2))
                  .a(ejs.a(cpg.xH).a(2))
                  .a(ejs.a(cpg.qK))
                  .a(ejs.a(cpg.oy))
                  .a(ejs.a(cpg.po))
                  .a(
                     ejs.a(cpg.vQ)
                        .a(
                           elg.c()
                              .a(bnf.p, emz.a(7.0F, 10.0F))
                              .a(bnf.h, emz.a(7.0F, 10.0F))
                              .a(bnf.r, emz.a(6.0F, 8.0F))
                              .a(bnf.o, emz.a(5.0F, 7.0F))
                              .a(bnf.s, emz.a(10.0F, 20.0F))
                              .a(bnf.w, emz.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         eja.aP,
         ejk.b()
            .a(
               ejj.a()
                  .a(emu.a(1.0F))
                  .a(ejs.a(cpg.xE))
                  .a(ejs.a(cpg.xP))
                  .a(ejs.a(cpg.xS))
                  .a(ejs.a(cpg.xV))
                  .a(ejs.a(cpg.ox))
                  .a(ejs.a(cpg.mc))
                  .a(ejs.a(cpg.pt))
                  .a(ejs.a(cpg.oy))
            )
      );
      $$0.accept(
         eja.aQ,
         ejk.b()
            .a(
               ejj.a()
                  .a(emu.a(1.0F))
                  .a(ejs.a(cpg.oy).a(2))
                  .a(ejs.a(cpg.pv).a(2))
                  .a(ejs.a(cpg.oO).a(2))
                  .a(ejs.a(cpg.eW).a(2))
                  .a(ejs.a(cpg.qK).a(2))
                  .a(ejs.a(cpg.rl).a(2))
                  .a(ejs.a(cpg.rs).a(2))
                  .a(ejs.a(cpg.rk).a(2))
                  .a(ejs.a(cpg.rh).a(2))
                  .a(ejs.a(cpg.ri).a(2))
                  .a(ejs.a(cpg.wZ).a(2))
                  .a(ejs.a(cpg.wY).a(2))
                  .a(ejs.a(cpg.wV).a(2))
                  .a(ejs.a(cpg.wX).a(2))
                  .a(ejs.a(cpg.iu))
                  .a(ejs.a(cpg.iy))
                  .a(ejs.a(cpg.iD))
                  .a(ejs.a(cpg.iv))
                  .a(ejs.a(cpg.iG))
                  .a(ejs.a(cpg.iw))
                  .a(ejs.a(cpg.iC))
                  .a(ejs.a(cpg.qn))
                  .a(ejs.a(cpg.qm))
                  .a(ejs.a(cpg.sh))
                  .a(ejs.a(cpg.ov))
                  .a(ejs.a(cpg.pu))
                  .a(ejs.a(cpg.vh))
                  .a(ejs.a(cpg.cQ))
                  .a(ejs.a(cpg.ua))
                  .a(ejs.a(cpg.pr))
                  .a(ejs.a(cpg.uG))
            )
      );
      $$0.accept(
         eja.aR,
         ejk.b()
            .a(
               ejj.a()
                  .a(emu.a(1.0F))
                  .a(ejs.a(cpg.xI))
                  .a(ejs.a(cpg.xJ))
                  .a(ejs.a(cpg.xL))
                  .a(ejs.a(cpg.xM))
                  .a(ejs.a(cpg.xN))
                  .a(ejs.a(cpg.xO))
                  .a(ejs.a(cpg.xT))
                  .a(ejs.a(cpg.xy))
                  .a(ejs.a(cpg.xB))
                  .a(ejs.a(cpg.xz))
                  .a(ejs.a(cpg.xC))
                  .a(ejs.a(cpg.vH))
            )
      );
      $$0.accept(
         eja.aS,
         ejk.b()
            .a(
               ejj.a()
                  .a(emu.a(1.0F))
                  .a(ejs.a(cpg.xD))
                  .a(ejs.a(cpg.xU))
                  .a(ejs.a(cpg.xW))
                  .a(ejs.a(cpg.kp))
                  .a(ejs.a(cpg.pc))
                  .a(ejs.a(cpg.oy).a(2))
                  .a(ejs.a(cpg.pv).a(2))
                  .a(ejs.a(cpg.oO).a(2))
                  .a(ejs.a(cpg.ov).a(2))
                  .a(ejs.a(cpg.sh).a(2))
            )
      );
      $$0.accept(
         eja.aT,
         ejk.b()
            .a(
               ejj.a()
                  .a(emu.a(1.0F))
                  .a(ejs.a(cpg.xG))
                  .a(ejs.a(cpg.xK))
                  .a(ejs.a(cpg.xQ))
                  .a(ejs.a(cpg.xR))
                  .a(ejs.a(cpg.pc))
                  .a(ejs.a(cpg.oy).a(2))
                  .a(ejs.a(cpg.pv).a(2))
                  .a(ejs.a(cpg.oO).a(2))
                  .a(ejs.a(cpg.ov).a(2))
                  .a(ejs.a(cpg.sh).a(2))
            )
      );
   }
}
