import java.util.function.BiConsumer;

public class ls implements ll {
   @Override
   public void generate(BiConsumer<ajc, ekg.a> $$0) {
      $$0.accept(
         ejw.aO,
         ekg.b()
            .a(
               ekf.a()
                  .a(enq.a(1.0F))
                  .a(eko.a(cpt.xF).a(2))
                  .a(eko.a(cpt.xH).a(2))
                  .a(eko.a(cpt.qK))
                  .a(eko.a(cpt.oy))
                  .a(eko.a(cpt.po))
                  .a(
                     eko.a(cpt.vQ)
                        .a(
                           emc.c()
                              .a(bnu.p, env.a(7.0F, 10.0F))
                              .a(bnu.h, env.a(7.0F, 10.0F))
                              .a(bnu.r, env.a(6.0F, 8.0F))
                              .a(bnu.o, env.a(5.0F, 7.0F))
                              .a(bnu.s, env.a(10.0F, 20.0F))
                              .a(bnu.w, env.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ejw.aP,
         ekg.b()
            .a(
               ekf.a()
                  .a(enq.a(1.0F))
                  .a(eko.a(cpt.xE))
                  .a(eko.a(cpt.xP))
                  .a(eko.a(cpt.xS))
                  .a(eko.a(cpt.xV))
                  .a(eko.a(cpt.ox))
                  .a(eko.a(cpt.mc))
                  .a(eko.a(cpt.pt))
                  .a(eko.a(cpt.oy))
            )
      );
      $$0.accept(
         ejw.aQ,
         ekg.b()
            .a(
               ekf.a()
                  .a(enq.a(1.0F))
                  .a(eko.a(cpt.oy).a(2))
                  .a(eko.a(cpt.pv).a(2))
                  .a(eko.a(cpt.oO).a(2))
                  .a(eko.a(cpt.eW).a(2))
                  .a(eko.a(cpt.qK).a(2))
                  .a(eko.a(cpt.rl).a(2))
                  .a(eko.a(cpt.rs).a(2))
                  .a(eko.a(cpt.rk).a(2))
                  .a(eko.a(cpt.rh).a(2))
                  .a(eko.a(cpt.ri).a(2))
                  .a(eko.a(cpt.wZ).a(2))
                  .a(eko.a(cpt.wY).a(2))
                  .a(eko.a(cpt.wV).a(2))
                  .a(eko.a(cpt.wX).a(2))
                  .a(eko.a(cpt.iu))
                  .a(eko.a(cpt.iy))
                  .a(eko.a(cpt.iD))
                  .a(eko.a(cpt.iv))
                  .a(eko.a(cpt.iG))
                  .a(eko.a(cpt.iw))
                  .a(eko.a(cpt.iC))
                  .a(eko.a(cpt.qn))
                  .a(eko.a(cpt.qm))
                  .a(eko.a(cpt.sh))
                  .a(eko.a(cpt.ov))
                  .a(eko.a(cpt.pu))
                  .a(eko.a(cpt.vh))
                  .a(eko.a(cpt.cQ))
                  .a(eko.a(cpt.ua))
                  .a(eko.a(cpt.pr))
                  .a(eko.a(cpt.uG))
            )
      );
      $$0.accept(
         ejw.aR,
         ekg.b()
            .a(
               ekf.a()
                  .a(enq.a(1.0F))
                  .a(eko.a(cpt.xI))
                  .a(eko.a(cpt.xJ))
                  .a(eko.a(cpt.xL))
                  .a(eko.a(cpt.xM))
                  .a(eko.a(cpt.xN))
                  .a(eko.a(cpt.xO))
                  .a(eko.a(cpt.xT))
                  .a(eko.a(cpt.xy))
                  .a(eko.a(cpt.xB))
                  .a(eko.a(cpt.xz))
                  .a(eko.a(cpt.xC))
                  .a(eko.a(cpt.vH))
            )
      );
      $$0.accept(
         ejw.aS,
         ekg.b()
            .a(
               ekf.a()
                  .a(enq.a(1.0F))
                  .a(eko.a(cpt.xD))
                  .a(eko.a(cpt.xU))
                  .a(eko.a(cpt.xW))
                  .a(eko.a(cpt.kp))
                  .a(eko.a(cpt.pc))
                  .a(eko.a(cpt.oy).a(2))
                  .a(eko.a(cpt.pv).a(2))
                  .a(eko.a(cpt.oO).a(2))
                  .a(eko.a(cpt.ov).a(2))
                  .a(eko.a(cpt.sh).a(2))
            )
      );
      $$0.accept(
         ejw.aT,
         ekg.b()
            .a(
               ekf.a()
                  .a(enq.a(1.0F))
                  .a(eko.a(cpt.xG))
                  .a(eko.a(cpt.xK))
                  .a(eko.a(cpt.xQ))
                  .a(eko.a(cpt.xR))
                  .a(eko.a(cpt.pc))
                  .a(eko.a(cpt.oy).a(2))
                  .a(eko.a(cpt.pv).a(2))
                  .a(eko.a(cpt.oO).a(2))
                  .a(eko.a(cpt.ov).a(2))
                  .a(eko.a(cpt.sh).a(2))
            )
      );
   }
}
