import java.util.function.BiConsumer;

public class lu implements lm {
   @Override
   public void generate(BiConsumer<ajh, ele.a> $$0) {
      $$0.accept(
         eku.aP,
         ele.b()
            .a(
               eld.a()
                  .a(eoo.a(1.0F))
                  .a(elm.a(cqp.xH).a(2))
                  .a(elm.a(cqp.xJ).a(2))
                  .a(elm.a(cqp.qK))
                  .a(elm.a(cqp.oy))
                  .a(elm.a(cqp.po))
                  .a(
                     elm.a(cqp.vS)
                        .a(
                           ena.c()
                              .a(bom.p, eot.a(7.0F, 10.0F))
                              .a(bom.h, eot.a(7.0F, 10.0F))
                              .a(bom.r, eot.a(6.0F, 8.0F))
                              .a(bom.o, eot.a(5.0F, 7.0F))
                              .a(bom.s, eot.a(10.0F, 20.0F))
                              .a(bom.w, eot.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         eku.aQ,
         ele.b()
            .a(
               eld.a()
                  .a(eoo.a(1.0F))
                  .a(elm.a(cqp.xG))
                  .a(elm.a(cqp.xR))
                  .a(elm.a(cqp.xU))
                  .a(elm.a(cqp.xX))
                  .a(elm.a(cqp.ox))
                  .a(elm.a(cqp.mc))
                  .a(elm.a(cqp.pt))
                  .a(elm.a(cqp.oy))
            )
      );
      $$0.accept(
         eku.aR,
         ele.b()
            .a(
               eld.a()
                  .a(eoo.a(1.0F))
                  .a(elm.a(cqp.oy).a(2))
                  .a(elm.a(cqp.pv).a(2))
                  .a(elm.a(cqp.oO).a(2))
                  .a(elm.a(cqp.eW).a(2))
                  .a(elm.a(cqp.qK).a(2))
                  .a(elm.a(cqp.rl).a(2))
                  .a(elm.a(cqp.rs).a(2))
                  .a(elm.a(cqp.rk).a(2))
                  .a(elm.a(cqp.rh).a(2))
                  .a(elm.a(cqp.ri).a(2))
                  .a(elm.a(cqp.xb).a(2))
                  .a(elm.a(cqp.xa).a(2))
                  .a(elm.a(cqp.wX).a(2))
                  .a(elm.a(cqp.wZ).a(2))
                  .a(elm.a(cqp.iu))
                  .a(elm.a(cqp.iy))
                  .a(elm.a(cqp.iD))
                  .a(elm.a(cqp.iv))
                  .a(elm.a(cqp.iG))
                  .a(elm.a(cqp.iw))
                  .a(elm.a(cqp.iC))
                  .a(elm.a(cqp.qn))
                  .a(elm.a(cqp.qm))
                  .a(elm.a(cqp.sh))
                  .a(elm.a(cqp.ov))
                  .a(elm.a(cqp.pu))
                  .a(elm.a(cqp.vj))
                  .a(elm.a(cqp.cQ))
                  .a(elm.a(cqp.uc))
                  .a(elm.a(cqp.pr))
                  .a(elm.a(cqp.uI))
            )
      );
      $$0.accept(
         eku.aS,
         ele.b()
            .a(
               eld.a()
                  .a(eoo.a(1.0F))
                  .a(elm.a(cqp.xK))
                  .a(elm.a(cqp.xL))
                  .a(elm.a(cqp.xN))
                  .a(elm.a(cqp.xO))
                  .a(elm.a(cqp.xP))
                  .a(elm.a(cqp.xQ))
                  .a(elm.a(cqp.xV))
                  .a(elm.a(cqp.xA))
                  .a(elm.a(cqp.xD))
                  .a(elm.a(cqp.xB))
                  .a(elm.a(cqp.xE))
                  .a(elm.a(cqp.vJ))
            )
      );
      $$0.accept(
         eku.aT,
         ele.b()
            .a(
               eld.a()
                  .a(eoo.a(1.0F))
                  .a(elm.a(cqp.xF))
                  .a(elm.a(cqp.xW))
                  .a(elm.a(cqp.xY))
                  .a(elm.a(cqp.kp))
                  .a(elm.a(cqp.pc))
                  .a(elm.a(cqp.oy).a(2))
                  .a(elm.a(cqp.pv).a(2))
                  .a(elm.a(cqp.oO).a(2))
                  .a(elm.a(cqp.ov).a(2))
                  .a(elm.a(cqp.sh).a(2))
            )
      );
      $$0.accept(
         eku.aU,
         ele.b()
            .a(
               eld.a()
                  .a(eoo.a(1.0F))
                  .a(elm.a(cqp.xI))
                  .a(elm.a(cqp.xM))
                  .a(elm.a(cqp.xS))
                  .a(elm.a(cqp.xT))
                  .a(elm.a(cqp.pc))
                  .a(elm.a(cqp.oy).a(2))
                  .a(elm.a(cqp.pv).a(2))
                  .a(elm.a(cqp.oO).a(2))
                  .a(elm.a(cqp.ov).a(2))
                  .a(elm.a(cqp.sh).a(2))
            )
      );
   }
}
