import java.util.function.BiConsumer;

public class lu implements lm {
   @Override
   public void generate(BiConsumer<ajh, elc.a> $$0) {
      $$0.accept(
         eks.aO,
         elc.b()
            .a(
               elb.a()
                  .a(eom.a(1.0F))
                  .a(elk.a(cqn.xG).a(2))
                  .a(elk.a(cqn.xI).a(2))
                  .a(elk.a(cqn.qK))
                  .a(elk.a(cqn.oy))
                  .a(elk.a(cqn.po))
                  .a(
                     elk.a(cqn.vR)
                        .a(
                           emy.c()
                              .a(bol.p, eor.a(7.0F, 10.0F))
                              .a(bol.h, eor.a(7.0F, 10.0F))
                              .a(bol.r, eor.a(6.0F, 8.0F))
                              .a(bol.o, eor.a(5.0F, 7.0F))
                              .a(bol.s, eor.a(10.0F, 20.0F))
                              .a(bol.w, eor.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         eks.aP,
         elc.b()
            .a(
               elb.a()
                  .a(eom.a(1.0F))
                  .a(elk.a(cqn.xF))
                  .a(elk.a(cqn.xQ))
                  .a(elk.a(cqn.xT))
                  .a(elk.a(cqn.xW))
                  .a(elk.a(cqn.ox))
                  .a(elk.a(cqn.mc))
                  .a(elk.a(cqn.pt))
                  .a(elk.a(cqn.oy))
            )
      );
      $$0.accept(
         eks.aQ,
         elc.b()
            .a(
               elb.a()
                  .a(eom.a(1.0F))
                  .a(elk.a(cqn.oy).a(2))
                  .a(elk.a(cqn.pv).a(2))
                  .a(elk.a(cqn.oO).a(2))
                  .a(elk.a(cqn.eW).a(2))
                  .a(elk.a(cqn.qK).a(2))
                  .a(elk.a(cqn.rl).a(2))
                  .a(elk.a(cqn.rs).a(2))
                  .a(elk.a(cqn.rk).a(2))
                  .a(elk.a(cqn.rh).a(2))
                  .a(elk.a(cqn.ri).a(2))
                  .a(elk.a(cqn.xa).a(2))
                  .a(elk.a(cqn.wZ).a(2))
                  .a(elk.a(cqn.wW).a(2))
                  .a(elk.a(cqn.wY).a(2))
                  .a(elk.a(cqn.iu))
                  .a(elk.a(cqn.iy))
                  .a(elk.a(cqn.iD))
                  .a(elk.a(cqn.iv))
                  .a(elk.a(cqn.iG))
                  .a(elk.a(cqn.iw))
                  .a(elk.a(cqn.iC))
                  .a(elk.a(cqn.qn))
                  .a(elk.a(cqn.qm))
                  .a(elk.a(cqn.sh))
                  .a(elk.a(cqn.ov))
                  .a(elk.a(cqn.pu))
                  .a(elk.a(cqn.vi))
                  .a(elk.a(cqn.cQ))
                  .a(elk.a(cqn.ub))
                  .a(elk.a(cqn.pr))
                  .a(elk.a(cqn.uH))
            )
      );
      $$0.accept(
         eks.aR,
         elc.b()
            .a(
               elb.a()
                  .a(eom.a(1.0F))
                  .a(elk.a(cqn.xJ))
                  .a(elk.a(cqn.xK))
                  .a(elk.a(cqn.xM))
                  .a(elk.a(cqn.xN))
                  .a(elk.a(cqn.xO))
                  .a(elk.a(cqn.xP))
                  .a(elk.a(cqn.xU))
                  .a(elk.a(cqn.xz))
                  .a(elk.a(cqn.xC))
                  .a(elk.a(cqn.xA))
                  .a(elk.a(cqn.xD))
                  .a(elk.a(cqn.vI))
            )
      );
      $$0.accept(
         eks.aS,
         elc.b()
            .a(
               elb.a()
                  .a(eom.a(1.0F))
                  .a(elk.a(cqn.xE))
                  .a(elk.a(cqn.xV))
                  .a(elk.a(cqn.xX))
                  .a(elk.a(cqn.kp))
                  .a(elk.a(cqn.pc))
                  .a(elk.a(cqn.oy).a(2))
                  .a(elk.a(cqn.pv).a(2))
                  .a(elk.a(cqn.oO).a(2))
                  .a(elk.a(cqn.ov).a(2))
                  .a(elk.a(cqn.sh).a(2))
            )
      );
      $$0.accept(
         eks.aT,
         elc.b()
            .a(
               elb.a()
                  .a(eom.a(1.0F))
                  .a(elk.a(cqn.xH))
                  .a(elk.a(cqn.xL))
                  .a(elk.a(cqn.xR))
                  .a(elk.a(cqn.xS))
                  .a(elk.a(cqn.pc))
                  .a(elk.a(cqn.oy).a(2))
                  .a(elk.a(cqn.pv).a(2))
                  .a(elk.a(cqn.oO).a(2))
                  .a(elk.a(cqn.ov).a(2))
                  .a(elk.a(cqn.sh).a(2))
            )
      );
   }
}
