import java.util.function.BiConsumer;

public class mf implements lw {
   @Override
   public void generate(in.a $$0, BiConsumer<ajt, enj.a> $$1) {
      $$1.accept(
         emz.aQ,
         enj.b()
            .a(
               eni.a()
                  .a(eqv.a(1.0F))
                  .a(enr.a(crm.xH).a(2))
                  .a(enr.a(crm.xJ).a(2))
                  .a(enr.a(crm.qK))
                  .a(enr.a(crm.oy))
                  .a(enr.a(crm.po))
                  .a(
                     enr.a(crm.vS)
                        .a(
                           eph.c()
                              .a(bpj.p, era.a(7.0F, 10.0F))
                              .a(bpj.h, era.a(7.0F, 10.0F))
                              .a(bpj.r, era.a(6.0F, 8.0F))
                              .a(bpj.o, era.a(5.0F, 7.0F))
                              .a(bpj.s, era.a(10.0F, 20.0F))
                              .a(bpj.w, era.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$1.accept(
         emz.aR,
         enj.b()
            .a(
               eni.a()
                  .a(eqv.a(1.0F))
                  .a(enr.a(crm.xG))
                  .a(enr.a(crm.xR))
                  .a(enr.a(crm.xU))
                  .a(enr.a(crm.xX))
                  .a(enr.a(crm.ox))
                  .a(enr.a(crm.mc))
                  .a(enr.a(crm.pt))
                  .a(enr.a(crm.oy))
            )
      );
      $$1.accept(
         emz.aS,
         enj.b()
            .a(
               eni.a()
                  .a(eqv.a(1.0F))
                  .a(enr.a(crm.oy).a(2))
                  .a(enr.a(crm.pv).a(2))
                  .a(enr.a(crm.oO).a(2))
                  .a(enr.a(crm.eW).a(2))
                  .a(enr.a(crm.qK).a(2))
                  .a(enr.a(crm.rl).a(2))
                  .a(enr.a(crm.rs).a(2))
                  .a(enr.a(crm.rk).a(2))
                  .a(enr.a(crm.rh).a(2))
                  .a(enr.a(crm.ri).a(2))
                  .a(enr.a(crm.xb).a(2))
                  .a(enr.a(crm.xa).a(2))
                  .a(enr.a(crm.wX).a(2))
                  .a(enr.a(crm.wZ).a(2))
                  .a(enr.a(crm.iu))
                  .a(enr.a(crm.iy))
                  .a(enr.a(crm.iD))
                  .a(enr.a(crm.iv))
                  .a(enr.a(crm.iG))
                  .a(enr.a(crm.iw))
                  .a(enr.a(crm.iC))
                  .a(enr.a(crm.qn))
                  .a(enr.a(crm.qm))
                  .a(enr.a(crm.sh))
                  .a(enr.a(crm.ov))
                  .a(enr.a(crm.pu))
                  .a(enr.a(crm.vj))
                  .a(enr.a(crm.cQ))
                  .a(enr.a(crm.uc))
                  .a(enr.a(crm.pr))
                  .a(enr.a(crm.uI))
            )
      );
      $$1.accept(
         emz.aT,
         enj.b()
            .a(
               eni.a()
                  .a(eqv.a(1.0F))
                  .a(enr.a(crm.xK))
                  .a(enr.a(crm.xL))
                  .a(enr.a(crm.xN))
                  .a(enr.a(crm.xO))
                  .a(enr.a(crm.xP))
                  .a(enr.a(crm.xQ))
                  .a(enr.a(crm.xV))
                  .a(enr.a(crm.xA))
                  .a(enr.a(crm.xD))
                  .a(enr.a(crm.xB))
                  .a(enr.a(crm.xE))
                  .a(enr.a(crm.vJ))
            )
      );
      $$1.accept(
         emz.aU,
         enj.b()
            .a(
               eni.a()
                  .a(eqv.a(1.0F))
                  .a(enr.a(crm.xF))
                  .a(enr.a(crm.xW))
                  .a(enr.a(crm.xY))
                  .a(enr.a(crm.kp))
                  .a(enr.a(crm.pc))
                  .a(enr.a(crm.oy).a(2))
                  .a(enr.a(crm.pv).a(2))
                  .a(enr.a(crm.oO).a(2))
                  .a(enr.a(crm.ov).a(2))
                  .a(enr.a(crm.sh).a(2))
            )
      );
      $$1.accept(
         emz.aV,
         enj.b()
            .a(
               eni.a()
                  .a(eqv.a(1.0F))
                  .a(enr.a(crm.xI))
                  .a(enr.a(crm.xM))
                  .a(enr.a(crm.xS))
                  .a(enr.a(crm.xT))
                  .a(enr.a(crm.pc))
                  .a(enr.a(crm.oy).a(2))
                  .a(enr.a(crm.pv).a(2))
                  .a(enr.a(crm.oO).a(2))
                  .a(enr.a(crm.ov).a(2))
                  .a(enr.a(crm.sh).a(2))
            )
      );
   }
}
