import java.util.function.BiConsumer;

public class mh implements ly {
   @Override
   public void generate(ip.a $$0, BiConsumer<ajv, ens.a> $$1) {
      $$1.accept(
         eni.aQ,
         ens.b()
            .a(
               enr.a()
                  .a(ere.a(1.0F))
                  .a(eoa.a(crv.xH).a(2))
                  .a(eoa.a(crv.xJ).a(2))
                  .a(eoa.a(crv.qK))
                  .a(eoa.a(crv.oy))
                  .a(eoa.a(crv.po))
                  .a(
                     eoa.a(crv.vS)
                        .a(
                           epq.c()
                              .a(bpo.p, erj.a(7.0F, 10.0F))
                              .a(bpo.h, erj.a(7.0F, 10.0F))
                              .a(bpo.r, erj.a(6.0F, 8.0F))
                              .a(bpo.o, erj.a(5.0F, 7.0F))
                              .a(bpo.s, erj.a(10.0F, 20.0F))
                              .a(bpo.w, erj.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$1.accept(
         eni.aR,
         ens.b()
            .a(
               enr.a()
                  .a(ere.a(1.0F))
                  .a(eoa.a(crv.xG))
                  .a(eoa.a(crv.xR))
                  .a(eoa.a(crv.xU))
                  .a(eoa.a(crv.xX))
                  .a(eoa.a(crv.ox))
                  .a(eoa.a(crv.mc))
                  .a(eoa.a(crv.pt))
                  .a(eoa.a(crv.oy))
            )
      );
      $$1.accept(
         eni.aS,
         ens.b()
            .a(
               enr.a()
                  .a(ere.a(1.0F))
                  .a(eoa.a(crv.oy).a(2))
                  .a(eoa.a(crv.pv).a(2))
                  .a(eoa.a(crv.oO).a(2))
                  .a(eoa.a(crv.eW).a(2))
                  .a(eoa.a(crv.qK).a(2))
                  .a(eoa.a(crv.rl).a(2))
                  .a(eoa.a(crv.rs).a(2))
                  .a(eoa.a(crv.rk).a(2))
                  .a(eoa.a(crv.rh).a(2))
                  .a(eoa.a(crv.ri).a(2))
                  .a(eoa.a(crv.xb).a(2))
                  .a(eoa.a(crv.xa).a(2))
                  .a(eoa.a(crv.wX).a(2))
                  .a(eoa.a(crv.wZ).a(2))
                  .a(eoa.a(crv.iu))
                  .a(eoa.a(crv.iy))
                  .a(eoa.a(crv.iD))
                  .a(eoa.a(crv.iv))
                  .a(eoa.a(crv.iG))
                  .a(eoa.a(crv.iw))
                  .a(eoa.a(crv.iC))
                  .a(eoa.a(crv.qn))
                  .a(eoa.a(crv.qm))
                  .a(eoa.a(crv.sh))
                  .a(eoa.a(crv.ov))
                  .a(eoa.a(crv.pu))
                  .a(eoa.a(crv.vj))
                  .a(eoa.a(crv.cQ))
                  .a(eoa.a(crv.uc))
                  .a(eoa.a(crv.pr))
                  .a(eoa.a(crv.uI))
            )
      );
      $$1.accept(
         eni.aT,
         ens.b()
            .a(
               enr.a()
                  .a(ere.a(1.0F))
                  .a(eoa.a(crv.xK))
                  .a(eoa.a(crv.xL))
                  .a(eoa.a(crv.xN))
                  .a(eoa.a(crv.xO))
                  .a(eoa.a(crv.xP))
                  .a(eoa.a(crv.xQ))
                  .a(eoa.a(crv.xV))
                  .a(eoa.a(crv.xA))
                  .a(eoa.a(crv.xD))
                  .a(eoa.a(crv.xB))
                  .a(eoa.a(crv.xE))
                  .a(eoa.a(crv.vJ))
            )
      );
      $$1.accept(
         eni.aU,
         ens.b()
            .a(
               enr.a()
                  .a(ere.a(1.0F))
                  .a(eoa.a(crv.xF))
                  .a(eoa.a(crv.xW))
                  .a(eoa.a(crv.xY))
                  .a(eoa.a(crv.kp))
                  .a(eoa.a(crv.pc))
                  .a(eoa.a(crv.oy).a(2))
                  .a(eoa.a(crv.pv).a(2))
                  .a(eoa.a(crv.oO).a(2))
                  .a(eoa.a(crv.ov).a(2))
                  .a(eoa.a(crv.sh).a(2))
            )
      );
      $$1.accept(
         eni.aV,
         ens.b()
            .a(
               enr.a()
                  .a(ere.a(1.0F))
                  .a(eoa.a(crv.xI))
                  .a(eoa.a(crv.xM))
                  .a(eoa.a(crv.xS))
                  .a(eoa.a(crv.xT))
                  .a(eoa.a(crv.pc))
                  .a(eoa.a(crv.oy).a(2))
                  .a(eoa.a(crv.pv).a(2))
                  .a(eoa.a(crv.oO).a(2))
                  .a(eoa.a(crv.ov).a(2))
                  .a(eoa.a(crv.sh).a(2))
            )
      );
   }
}
