import java.util.Optional;
import java.util.stream.IntStream;

public class ml {
   public static final mk a = a("cube", mn.c, mn.j, mn.k, mn.l, mn.m, mn.n, mn.o);
   public static final mk b = a("cube_directional", mn.c, mn.j, mn.k, mn.l, mn.m, mn.n, mn.o);
   public static final mk c = a("cube_all", mn.a);
   public static final mk d = a("cube_mirrored_all", "_mirrored", mn.a);
   public static final mk e = a("cube_north_west_mirrored_all", "_north_west_mirrored", mn.a);
   public static final mk f = a("cube_column_uv_locked_x", "_x", mn.d, mn.i);
   public static final mk g = a("cube_column_uv_locked_y", "_y", mn.d, mn.i);
   public static final mk h = a("cube_column_uv_locked_z", "_z", mn.d, mn.i);
   public static final mk i = a("cube_column", mn.d, mn.i);
   public static final mk j = a("cube_column_horizontal", "_horizontal", mn.d, mn.i);
   public static final mk k = a("cube_column_mirrored", "_mirrored", mn.d, mn.i);
   public static final mk l = a("cube_top", mn.f, mn.i);
   public static final mk m = a("cube_bottom_top", mn.f, mn.e, mn.i);
   public static final mk n = a("orientable", mn.f, mn.g, mn.i);
   public static final mk o = a("orientable_with_bottom", mn.f, mn.e, mn.i, mn.g);
   public static final mk p = a("orientable_vertical", "_vertical", mn.g, mn.i);
   public static final mk q = a("button", mn.b);
   public static final mk r = a("button_pressed", "_pressed", mn.b);
   public static final mk s = a("button_inventory", "_inventory", mn.b);
   public static final mk t = a("door_bottom_left", "_bottom_left", mn.f, mn.e);
   public static final mk u = a("door_bottom_left_open", "_bottom_left_open", mn.f, mn.e);
   public static final mk v = a("door_bottom_right", "_bottom_right", mn.f, mn.e);
   public static final mk w = a("door_bottom_right_open", "_bottom_right_open", mn.f, mn.e);
   public static final mk x = a("door_top_left", "_top_left", mn.f, mn.e);
   public static final mk y = a("door_top_left_open", "_top_left_open", mn.f, mn.e);
   public static final mk z = a("door_top_right", "_top_right", mn.f, mn.e);
   public static final mk A = a("door_top_right_open", "_top_right_open", mn.f, mn.e);
   public static final mk B = a("custom_fence_post", "_post", mn.b, mn.c);
   public static final mk C = a("custom_fence_side_north", "_side_north", mn.b);
   public static final mk D = a("custom_fence_side_east", "_side_east", mn.b);
   public static final mk E = a("custom_fence_side_south", "_side_south", mn.b);
   public static final mk F = a("custom_fence_side_west", "_side_west", mn.b);
   public static final mk G = a("custom_fence_inventory", "_inventory", mn.b);
   public static final mk H = a("fence_post", "_post", mn.b);
   public static final mk I = a("fence_side", "_side", mn.b);
   public static final mk J = a("fence_inventory", "_inventory", mn.b);
   public static final mk K = a("template_wall_post", "_post", mn.r);
   public static final mk L = a("template_wall_side", "_side", mn.r);
   public static final mk M = a("template_wall_side_tall", "_side_tall", mn.r);
   public static final mk N = a("wall_inventory", "_inventory", mn.r);
   public static final mk O = a("template_custom_fence_gate", mn.b, mn.c);
   public static final mk P = a("template_custom_fence_gate_open", "_open", mn.b, mn.c);
   public static final mk Q = a("template_custom_fence_gate_wall", "_wall", mn.b, mn.c);
   public static final mk R = a("template_custom_fence_gate_wall_open", "_wall_open", mn.b, mn.c);
   public static final mk S = a("template_fence_gate", mn.b);
   public static final mk T = a("template_fence_gate_open", "_open", mn.b);
   public static final mk U = a("template_fence_gate_wall", "_wall", mn.b);
   public static final mk V = a("template_fence_gate_wall_open", "_wall_open", mn.b);
   public static final mk W = a("pressure_plate_up", mn.b);
   public static final mk X = a("pressure_plate_down", "_down", mn.b);
   public static final mk Y = a(mn.c);
   public static final mk Z = a("slab", mn.e, mn.f, mn.i);
   public static final mk aa = a("slab_top", "_top", mn.e, mn.f, mn.i);
   public static final mk ab = a("leaves", mn.a);
   public static final mk ac = a("stairs", mn.e, mn.f, mn.i);
   public static final mk ad = a("inner_stairs", "_inner", mn.e, mn.f, mn.i);
   public static final mk ae = a("outer_stairs", "_outer", mn.e, mn.f, mn.i);
   public static final mk af = a("template_trapdoor_top", "_top", mn.b);
   public static final mk ag = a("template_trapdoor_bottom", "_bottom", mn.b);
   public static final mk ah = a("template_trapdoor_open", "_open", mn.b);
   public static final mk ai = a("template_orientable_trapdoor_top", "_top", mn.b);
   public static final mk aj = a("template_orientable_trapdoor_bottom", "_bottom", mn.b);
   public static final mk ak = a("template_orientable_trapdoor_open", "_open", mn.b);
   public static final mk al = a("pointed_dripstone", mn.p);
   public static final mk am = a("cross", mn.p);
   public static final mk an = a("tinted_cross", mn.p);
   public static final mk ao = a("flower_pot_cross", mn.q);
   public static final mk ap = a("tinted_flower_pot_cross", mn.q);
   public static final mk aq = a("rail_flat", mn.s);
   public static final mk ar = a("rail_curved", "_corner", mn.s);
   public static final mk as = a("template_rail_raised_ne", "_raised_ne", mn.s);
   public static final mk at = a("template_rail_raised_sw", "_raised_sw", mn.s);
   public static final mk au = a("carpet", mn.t);
   public static final mk av = a("flowerbed_1", "_1", mn.P, mn.y);
   public static final mk aw = a("flowerbed_2", "_2", mn.P, mn.y);
   public static final mk ax = a("flowerbed_3", "_3", mn.P, mn.y);
   public static final mk ay = a("flowerbed_4", "_4", mn.P, mn.y);
   public static final mk az = a("coral_fan", mn.x);
   public static final mk aA = a("coral_wall_fan", mn.x);
   public static final mk aB = a("template_glazed_terracotta", mn.u);
   public static final mk aC = a("template_chorus_flower", mn.b);
   public static final mk aD = a("template_daylight_detector", mn.f, mn.i);
   public static final mk aE = a("template_glass_pane_noside", "_noside", mn.v);
   public static final mk aF = a("template_glass_pane_noside_alt", "_noside_alt", mn.v);
   public static final mk aG = a("template_glass_pane_post", "_post", mn.v, mn.w);
   public static final mk aH = a("template_glass_pane_side", "_side", mn.v, mn.w);
   public static final mk aI = a("template_glass_pane_side_alt", "_side_alt", mn.v, mn.w);
   public static final mk aJ = a("template_command_block", mn.g, mn.h, mn.i);
   public static final mk aK = a("template_chiseled_bookshelf_slot_top_left", "_slot_top_left", mn.b);
   public static final mk aL = a("template_chiseled_bookshelf_slot_top_mid", "_slot_top_mid", mn.b);
   public static final mk aM = a("template_chiseled_bookshelf_slot_top_right", "_slot_top_right", mn.b);
   public static final mk aN = a("template_chiseled_bookshelf_slot_bottom_left", "_slot_bottom_left", mn.b);
   public static final mk aO = a("template_chiseled_bookshelf_slot_bottom_mid", "_slot_bottom_mid", mn.b);
   public static final mk aP = a("template_chiseled_bookshelf_slot_bottom_right", "_slot_bottom_right", mn.b);
   public static final mk aQ = a("template_anvil", mn.f);
   public static final mk[] aR = IntStream.range(0, 8).mapToObj($$0 -> a("stem_growth" + $$0, "_stage" + $$0, mn.y)).toArray(mk[]::new);
   public static final mk aS = a("stem_fruit", mn.y, mn.z);
   public static final mk aT = a("crop", mn.A);
   public static final mk aU = a("template_farmland", mn.B, mn.f);
   public static final mk aV = a("template_fire_floor", mn.C);
   public static final mk aW = a("template_fire_side", mn.C);
   public static final mk aX = a("template_fire_side_alt", mn.C);
   public static final mk aY = a("template_fire_up", mn.C);
   public static final mk aZ = a("template_fire_up_alt", mn.C);
   public static final mk ba = a("template_campfire", mn.C, mn.K);
   public static final mk bb = a("template_lantern", mn.D);
   public static final mk bc = a("template_hanging_lantern", "_hanging", mn.D);
   public static final mk bd = a("template_torch", mn.G);
   public static final mk be = a("template_torch_wall", mn.G);
   public static final mk bf = a("template_piston", mn.E, mn.e, mn.i);
   public static final mk bg = a("template_piston_head", mn.E, mn.i, mn.F);
   public static final mk bh = a("template_piston_head_short", mn.E, mn.i, mn.F);
   public static final mk bi = a("template_seagrass", mn.b);
   public static final mk bj = a("template_turtle_egg", mn.a);
   public static final mk bk = a("template_two_turtle_eggs", mn.a);
   public static final mk bl = a("template_three_turtle_eggs", mn.a);
   public static final mk bm = a("template_four_turtle_eggs", mn.a);
   public static final mk bn = a("template_single_face", mn.b);
   public static final mk bo = a("template_cauldron_level1", mn.N, mn.M, mn.c, mn.f, mn.e, mn.i);
   public static final mk bp = a("template_cauldron_level2", mn.N, mn.M, mn.c, mn.f, mn.e, mn.i);
   public static final mk bq = a("template_cauldron_full", mn.N, mn.M, mn.c, mn.f, mn.e, mn.i);
   public static final mk br = a("template_azalea", mn.f, mn.i);
   public static final mk bs = a("template_potted_azalea_bush", mn.q, mn.f, mn.i);
   public static final mk bt = a("template_potted_azalea_bush", mn.q, mn.f, mn.i);
   public static final mk bu = a("sniffer_egg", mn.f, mn.e, mn.j, mn.k, mn.l, mn.m);
   public static final mk bv = b("generated", mn.H);
   public static final mk bw = b("template_music_disc", mn.H);
   public static final mk bx = b("handheld", mn.H);
   public static final mk by = b("handheld_rod", mn.H);
   public static final mk bz = b("generated", mn.H, mn.I);
   public static final mk bA = b("generated", mn.H, mn.I, mn.J);
   public static final mk bB = b("template_shulker_box", mn.c);
   public static final mk bC = b("template_bed", mn.c);
   public static final mk bD = b("template_banner");
   public static final mk bE = b("template_skull");
   public static final mk bF = a("template_candle", mn.a, mn.c);
   public static final mk bG = a("template_two_candles", mn.a, mn.c);
   public static final mk bH = a("template_three_candles", mn.a, mn.c);
   public static final mk bI = a("template_four_candles", mn.a, mn.c);
   public static final mk bJ = a("template_cake_with_candle", mn.L, mn.e, mn.i, mn.f, mn.c);
   public static final mk bK = a("template_sculk_shrieker", mn.e, mn.i, mn.f, mn.c, mn.O);

   private static mk a(mn... $$0) {
      return new mk(Optional.empty(), Optional.empty(), $$0);
   }

   private static mk a(String $$0, mn... $$1) {
      return new mk(Optional.of(new agm("minecraft", "block/" + $$0)), Optional.empty(), $$1);
   }

   private static mk b(String $$0, mn... $$1) {
      return new mk(Optional.of(new agm("minecraft", "item/" + $$0)), Optional.empty(), $$1);
   }

   private static mk a(String $$0, String $$1, mn... $$2) {
      return new mk(Optional.of(new agm("minecraft", "block/" + $$0)), Optional.of($$1), $$2);
   }
}
