import java.util.concurrent.CompletableFuture;

public class mp extends nc<cqt> {
   public mp(jk $$0, CompletableFuture<hg.b> $$1) {
      super($$0, jc.ap, $$1);
   }

   @Override
   protected void a(hg.b $$0) {
      this.b(apr.a).a(cra.X).a(cra.V).a(cra.T).a(cra.R);
      this.b(apr.b).b(apr.a).a(cra.W).a(cra.S).a(cra.U).a(cra.Q).a(cra.P);
      this.b(apr.c).a(cra.M).a(cra.N);
      this.b(apr.d).a(cra.K).a(cra.L);
      this.b(apr.e).a(cra.D).a(cra.H).a(cra.I).a(cra.J).a(cra.G).a(cra.E);
      this.b(apr.f).a(cra.A).a(cra.B).a(cra.C);
      this.b(apr.g).a(cra.t).a(cra.v).a(cra.u);
      this.b(apr.h).a(cra.p).a(cra.q).a(cra.n).a(cra.o);
      this.b(apr.i).a(cra.z).a(cra.x).a(cra.y);
      this.b(apr.j).a(cra.i).a(cra.j).a(cra.k).a(cra.m).a(cra.l).a(cra.F);
      this.b(apr.k).a(cra.r).a(cra.s).a(cra.w);
      nc.b<cqt> $$1 = this.b(apr.m);
      crh.a.a.a().forEach($$1::a);
      nc.b<cqt> $$2 = this.b(apr.l);
      crh.a.b.a().forEach($$2::a);
      this.b(apr.n).a(cra.ah).a(cra.ai).a(cra.aj).a(cra.ak).a(cra.al);
      this.b(apr.p).b(apr.c);
      this.b(apr.q).a(cra.f);
      this.b(apr.r).a(cra.q).a(cra.d).a(cra.G);
      this.b(apr.s).a(cra.z).a(cra.x);
      this.b(apr.t)
         .b(apr.b)
         .b(apr.d)
         .b(apr.c)
         .b(apr.e)
         .b(apr.g)
         .b(apr.h)
         .b(apr.i)
         .b(apr.j)
         .a(cra.O)
         .a(cra.Y)
         .a(cra.e)
         .a(cra.w)
         .a(cra.f)
         .a(cra.r)
         .a(cra.d)
         .a(cra.b)
         .a(cra.c)
         .a(cra.g)
         .a(cra.h)
         .a(cra.s)
         .a(cra.Z)
         .a(cra.aa);
      this.b(apr.u).b(apr.f);
      this.b(apr.X).a(cra.ab);
      this.b(apr.v).b(apr.a);
      this.b(apr.W).b(apr.b).b(apr.d);
      this.b(apr.w).a(cra.W).a(cra.U).a(cra.S).a(cra.X).a(cra.V).a(cra.T);
      this.b(apr.x).a(cra.Q).a(cra.P).a(cra.R);
      this.b(apr.y).a(cra.f).a(cra.b).a(cra.r).a(cra.d).a(cra.p).b(apr.e).a(cra.F);
      this.b(apr.z).a(cra.f);
      this.b(apr.A).b(apr.i);
      this.b(apr.B).b(apr.b);
      this.b(apr.C).a(cra.g).a(cra.h);
      this.b(apr.D).b(apr.f).b(apr.g).a(cra.s).a(cra.w).a(cra.O).b(apr.e);
      this.b(apr.E).b(apr.c).b(apr.d).b(apr.h).b(apr.j).a(cra.Y).a(cra.e).a(cra.Z).a(cra.aa).a(cra.r).a(cra.d).a(cra.b).a(cra.c);
      this.b(apr.F).b(apr.c);
      this.b(apr.G).b(apr.b);
      this.b(apr.I).a(cra.g);
      this.b(apr.J).a(cra.f);
      this.b(apr.K).a(cra.b).a(cra.D);
      this.b(apr.L).a(cra.r);
      this.b(apr.M).a(cra.d);
      this.b(apr.N).a(cra.p);
      this.b(apr.O).a(cra.p).a(cra.q).a(cra.n).a(cra.o).a(cra.m).a(cra.x);
      this.b(apr.P).a(cra.l);
      this.b(apr.o)
         .a(cra.b)
         .a(cra.c)
         .a(cra.d)
         .a(cra.e)
         .a(cra.f)
         .a(cra.i)
         .a(cra.j)
         .a(cra.k)
         .a(cra.l)
         .a(cra.m)
         .a(cra.n)
         .a(cra.o)
         .a(cra.p)
         .a(cra.q)
         .a(cra.r)
         .a(cra.s)
         .a(cra.t)
         .a(cra.u)
         .a(cra.v)
         .a(cra.w)
         .a(cra.x)
         .a(cra.y)
         .a(cra.z)
         .a(cra.A)
         .a(cra.B)
         .a(cra.C)
         .a(cra.D)
         .a(cra.F)
         .a(cra.G)
         .a(cra.H)
         .a(cra.I)
         .a(cra.J)
         .a(cra.Y)
         .a(cra.Z)
         .a(cra.aa);
      this.b(apr.H).b(apr.l);
      this.b(apr.Q).b(apr.m);
      this.b(apr.R).a(cra.af);
      this.b(apr.S).a(cra.ae).a(cra.ac).a(cra.af).a(cra.ad);
      this.b(apr.T).a(cra.ab);
      this.b(apr.U).b(apr.m);
      this.b(apr.V).a(cra.ai).a(cra.aj);
      this.b(apr.ab).a(cra.P);
      this.b(apr.Y).b(apr.b).b(apr.d);
      this.b(apr.Z).a(cra.g).a(cra.h);
      this.b(apr.aa).b(apr.b).b(apr.d).a(cra.g).a(cra.h);
      this.b(apr.ae).a(cra.Y);
      this.b(apr.af).a(cra.Y);
      this.b(apr.ag).a(cra.a);
      this.b(apr.ah).a(cra.d).a(cra.e).a(cra.H).a(cra.I).a(cra.G).a(cra.W).a(cra.X).a(cra.F).a(cra.ab).a(cra.L).a(cra.q).a(cra.N).b(apr.n);
      this.b(apr.ai).a(cra.f).a(cra.P).b(apr.i).b(apr.k).b(apr.m).b(apr.f).a(cra.h);
      this.b(apr.aj).a(cra.f);
      this.b(apr.ak).a(cra.d).a(cra.e).a(cra.W).a(cra.q).a(cra.L).a(cra.N).a(cra.H).a(cra.I).a(cra.G).a(cra.F);
      this.b(apr.al).b(apr.d);
      this.b(apr.am).a(cra.aa);
      this.b(apr.an).a(cra.W).a(cra.X);
      this.b(apr.ao).b(apr.d);
      this.b(apr.ap).a(cra.g).a(cra.h);
      this.b(apr.aq).a(cra.d).a(cra.e).a(cra.W).a(cra.q).a(cra.L).a(cra.N).a(cra.H).a(cra.I).a(cra.G).a(cra.F);
      this.b(apr.ac).a(cra.z).a(cra.Y).a(cra.h).a(cra.G).a(cra.H).a(cra.I).a(cra.g).a(cra.x);
      this.b(apr.ad).a(cra.A).a(cra.ag).a(cra.ae).a(cra.f).a(cra.B).a(cra.ac).a(cra.r).a(cra.s).a(cra.af).a(cra.ad).a(cra.w).a(cra.C);
   }
}
