import java.util.function.BiConsumer;

public class mq implements mh {
   @Override
   public void generate(ix.a $$0, BiConsumer<akf, eoi.a> $$1) {
      $$1.accept(
         eny.aT,
         eoi.b()
            .a(
               eoh.a()
                  .a(esa.a(1.0F))
                  .a(eoq.a(csg.xN).a(2))
                  .a(eoq.a(csg.xP).a(2))
                  .a(eoq.a(csg.qL))
                  .a(eoq.a(csg.oz))
                  .a(eoq.a(csg.pp))
                  .a(
                     eoq.a(csg.vU)
                        .a(
                           eqk.c()
                              .a(bpz.p, esf.a(7.0F, 10.0F))
                              .a(bpz.h, esf.a(7.0F, 10.0F))
                              .a(bpz.r, esf.a(6.0F, 8.0F))
                              .a(bpz.o, esf.a(5.0F, 7.0F))
                              .a(bpz.s, esf.a(10.0F, 20.0F))
                              .a(bpz.w, esf.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$1.accept(
         eny.aU,
         eoi.b()
            .a(
               eoh.a()
                  .a(esa.a(1.0F))
                  .a(eoq.a(csg.xM))
                  .a(eoq.a(csg.xZ))
                  .a(eoq.a(csg.yc))
                  .a(eoq.a(csg.yg))
                  .a(eoq.a(csg.oy))
                  .a(eoq.a(csg.md))
                  .a(eoq.a(csg.pu))
                  .a(eoq.a(csg.oz))
            )
      );
      $$1.accept(
         eny.aV,
         eoi.b()
            .a(
               eoh.a()
                  .a(esa.a(1.0F))
                  .a(eoq.a(csg.oz).a(2))
                  .a(eoq.a(csg.pw).a(2))
                  .a(eoq.a(csg.oP).a(2))
                  .a(eoq.a(csg.eX).a(2))
                  .a(eoq.a(csg.qL).a(2))
                  .a(eoq.a(csg.rm).a(2))
                  .a(eoq.a(csg.rt).a(2))
                  .a(eoq.a(csg.rl).a(2))
                  .a(eoq.a(csg.ri).a(2))
                  .a(eoq.a(csg.rj).a(2))
                  .a(eoq.a(csg.xf).a(2))
                  .a(eoq.a(csg.xe).a(2))
                  .a(eoq.a(csg.xb).a(2))
                  .a(eoq.a(csg.xd).a(2))
                  .a(eoq.a(csg.iv))
                  .a(eoq.a(csg.iz))
                  .a(eoq.a(csg.iE))
                  .a(eoq.a(csg.iw))
                  .a(eoq.a(csg.iH))
                  .a(eoq.a(csg.ix))
                  .a(eoq.a(csg.iD))
                  .a(eoq.a(csg.qo))
                  .a(eoq.a(csg.qn))
                  .a(eoq.a(csg.si))
                  .a(eoq.a(csg.ow))
                  .a(eoq.a(csg.pv))
                  .a(eoq.a(csg.vl))
                  .a(eoq.a(csg.cR))
                  .a(eoq.a(csg.ue))
                  .a(eoq.a(csg.ps))
                  .a(eoq.a(csg.uK))
            )
      );
      $$1.accept(
         eny.aW,
         eoi.b()
            .a(
               eoh.a()
                  .a(esa.a(1.0F))
                  .a(eoq.a(csg.xQ))
                  .a(eoq.a(csg.xR))
                  .a(eoq.a(csg.xU))
                  .a(eoq.a(csg.xW))
                  .a(eoq.a(csg.xX))
                  .a(eoq.a(csg.xY))
                  .a(eoq.a(csg.ye))
                  .a(eoq.a(csg.xE))
                  .a(eoq.a(csg.xH))
                  .a(eoq.a(csg.xF))
                  .a(eoq.a(csg.xI))
                  .a(eoq.a(csg.vL))
            )
      );
      $$1.accept(
         eny.aX,
         eoi.b()
            .a(
               eoh.a()
                  .a(esa.a(1.0F))
                  .a(eoq.a(csg.xL))
                  .a(eoq.a(csg.yf))
                  .a(eoq.a(csg.yh))
                  .a(eoq.a(csg.kq))
                  .a(eoq.a(csg.pd))
                  .a(eoq.a(csg.oz).a(2))
                  .a(eoq.a(csg.pw).a(2))
                  .a(eoq.a(csg.oP).a(2))
                  .a(eoq.a(csg.ow).a(2))
                  .a(eoq.a(csg.si).a(2))
            )
      );
      $$1.accept(
         eny.aY,
         eoi.b()
            .a(
               eoh.a()
                  .a(esa.a(1.0F))
                  .a(eoq.a(csg.xO))
                  .a(eoq.a(csg.xS))
                  .a(eoq.a(csg.ya))
                  .a(eoq.a(csg.yb))
                  .a(eoq.a(csg.pd))
                  .a(eoq.a(csg.oz).a(2))
                  .a(eoq.a(csg.pw).a(2))
                  .a(eoq.a(csg.oP).a(2))
                  .a(eoq.a(csg.ow).a(2))
                  .a(eoq.a(csg.si).a(2))
            )
      );
   }
}
