import java.util.function.BiConsumer;

public class mr implements mi {
   @Override
   public void generate(iy.a $$0, BiConsumer<akg<eoq>, eoq.a> $$1) {
      $$1.accept(
         eoj.aT,
         eoq.b()
            .a(
               eop.a()
                  .a(esj.a(1.0F))
                  .a(eoy.a(ctc.xN).a(2))
                  .a(eoy.a(ctc.xP).a(2))
                  .a(eoy.a(ctc.qL))
                  .a(eoy.a(ctc.oz))
                  .a(eoy.a(ctc.pp))
                  .a(
                     eoy.a(ctc.vU)
                        .a(
                           eqs.c()
                              .a(bqv.p, esp.a(7.0F, 10.0F))
                              .a(bqv.h, esp.a(7.0F, 10.0F))
                              .a(bqv.r, esp.a(6.0F, 8.0F))
                              .a(bqv.o, esp.a(5.0F, 7.0F))
                              .a(bqv.s, esp.a(10.0F, 20.0F))
                              .a(bqv.w, esp.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$1.accept(
         eoj.aU,
         eoq.b()
            .a(
               eop.a()
                  .a(esj.a(1.0F))
                  .a(eoy.a(ctc.xM))
                  .a(eoy.a(ctc.xZ))
                  .a(eoy.a(ctc.yc))
                  .a(eoy.a(ctc.yg))
                  .a(eoy.a(ctc.oy))
                  .a(eoy.a(ctc.md))
                  .a(eoy.a(ctc.pu))
                  .a(eoy.a(ctc.oz))
            )
      );
      $$1.accept(
         eoj.aV,
         eoq.b()
            .a(
               eop.a()
                  .a(esj.a(1.0F))
                  .a(eoy.a(ctc.oz).a(2))
                  .a(eoy.a(ctc.pw).a(2))
                  .a(eoy.a(ctc.oP).a(2))
                  .a(eoy.a(ctc.eX).a(2))
                  .a(eoy.a(ctc.qL).a(2))
                  .a(eoy.a(ctc.rm).a(2))
                  .a(eoy.a(ctc.rt).a(2))
                  .a(eoy.a(ctc.rl).a(2))
                  .a(eoy.a(ctc.ri).a(2))
                  .a(eoy.a(ctc.rj).a(2))
                  .a(eoy.a(ctc.xf).a(2))
                  .a(eoy.a(ctc.xe).a(2))
                  .a(eoy.a(ctc.xb).a(2))
                  .a(eoy.a(ctc.xd).a(2))
                  .a(eoy.a(ctc.iv))
                  .a(eoy.a(ctc.iz))
                  .a(eoy.a(ctc.iE))
                  .a(eoy.a(ctc.iw))
                  .a(eoy.a(ctc.iH))
                  .a(eoy.a(ctc.ix))
                  .a(eoy.a(ctc.iD))
                  .a(eoy.a(ctc.qo))
                  .a(eoy.a(ctc.qn))
                  .a(eoy.a(ctc.si))
                  .a(eoy.a(ctc.ow))
                  .a(eoy.a(ctc.pv))
                  .a(eoy.a(ctc.vl))
                  .a(eoy.a(ctc.cR))
                  .a(eoy.a(ctc.ue))
                  .a(eoy.a(ctc.ps))
                  .a(eoy.a(ctc.uK))
            )
      );
      $$1.accept(
         eoj.aW,
         eoq.b()
            .a(
               eop.a()
                  .a(esj.a(1.0F))
                  .a(eoy.a(ctc.xQ))
                  .a(eoy.a(ctc.xR))
                  .a(eoy.a(ctc.xU))
                  .a(eoy.a(ctc.xW))
                  .a(eoy.a(ctc.xX))
                  .a(eoy.a(ctc.xY))
                  .a(eoy.a(ctc.ye))
                  .a(eoy.a(ctc.xE))
                  .a(eoy.a(ctc.xH))
                  .a(eoy.a(ctc.xF))
                  .a(eoy.a(ctc.xI))
                  .a(eoy.a(ctc.vL))
            )
      );
      $$1.accept(
         eoj.aX,
         eoq.b()
            .a(
               eop.a()
                  .a(esj.a(1.0F))
                  .a(eoy.a(ctc.xL))
                  .a(eoy.a(ctc.yf))
                  .a(eoy.a(ctc.yh))
                  .a(eoy.a(ctc.kq))
                  .a(eoy.a(ctc.pd))
                  .a(eoy.a(ctc.oz).a(2))
                  .a(eoy.a(ctc.pw).a(2))
                  .a(eoy.a(ctc.oP).a(2))
                  .a(eoy.a(ctc.ow).a(2))
                  .a(eoy.a(ctc.si).a(2))
            )
      );
      $$1.accept(
         eoj.aY,
         eoq.b()
            .a(
               eop.a()
                  .a(esj.a(1.0F))
                  .a(eoy.a(ctc.xO))
                  .a(eoy.a(ctc.xS))
                  .a(eoy.a(ctc.ya))
                  .a(eoy.a(ctc.yb))
                  .a(eoy.a(ctc.pd))
                  .a(eoy.a(ctc.oz).a(2))
                  .a(eoy.a(ctc.pw).a(2))
                  .a(eoy.a(ctc.oP).a(2))
                  .a(eoy.a(ctc.ow).a(2))
                  .a(eoy.a(ctc.si).a(2))
            )
      );
   }
}
