import java.util.function.BiConsumer;

public class mw implements mn {
   @Override
   public void generate(jc.a $$0, BiConsumer<aks<eru>, eru.a> $$1) {
      $$1.accept(
         ern.bm,
         eru.b()
            .a(
               ert.a()
                  .a(evo.a(1.0F))
                  .a(esc.a(cuk.zA).a(2))
                  .a(esc.a(cuk.zC).a(2))
                  .a(esc.a(cuk.si))
                  .a(esc.a(cuk.pP))
                  .a(esc.a(cuk.qI))
                  .a(
                     esc.a(cuk.xF)
                        .a(
                           etw.c()
                              .a(brj.p, evu.a(7.0F, 10.0F))
                              .a(brj.h, evu.a(7.0F, 10.0F))
                              .a(brj.r, evu.a(6.0F, 8.0F))
                              .a(brj.o, evu.a(5.0F, 7.0F))
                              .a(brj.s, evu.a(10.0F, 20.0F))
                              .a(brj.w, evu.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$1.accept(
         ern.bn,
         eru.b()
            .a(
               ert.a()
                  .a(evo.a(1.0F))
                  .a(esc.a(cuk.zz))
                  .a(esc.a(cuk.zM))
                  .a(esc.a(cuk.zP))
                  .a(esc.a(cuk.zT))
                  .a(esc.a(cuk.pO))
                  .a(esc.a(cuk.nt))
                  .a(esc.a(cuk.qN))
                  .a(esc.a(cuk.pP))
            )
      );
      $$1.accept(
         ern.bo,
         eru.b()
            .a(
               ert.a()
                  .a(evo.a(1.0F))
                  .a(esc.a(cuk.pP).a(2))
                  .a(esc.a(cuk.qP).a(2))
                  .a(esc.a(cuk.qi).a(2))
                  .a(esc.a(cuk.gi).a(2))
                  .a(esc.a(cuk.si).a(2))
                  .a(esc.a(cuk.sJ).a(2))
                  .a(esc.a(cuk.sQ).a(2))
                  .a(esc.a(cuk.sI).a(2))
                  .a(esc.a(cuk.sF).a(2))
                  .a(esc.a(cuk.sG).a(2))
                  .a(esc.a(cuk.yS).a(2))
                  .a(esc.a(cuk.yR).a(2))
                  .a(esc.a(cuk.yO).a(2))
                  .a(esc.a(cuk.yQ).a(2))
                  .a(esc.a(cuk.jK))
                  .a(esc.a(cuk.jO))
                  .a(esc.a(cuk.jT))
                  .a(esc.a(cuk.jL))
                  .a(esc.a(cuk.jW))
                  .a(esc.a(cuk.jM))
                  .a(esc.a(cuk.jS))
                  .a(esc.a(cuk.rL))
                  .a(esc.a(cuk.rK))
                  .a(esc.a(cuk.tF))
                  .a(esc.a(cuk.pM))
                  .a(esc.a(cuk.qO))
                  .a(esc.a(cuk.wW))
                  .a(esc.a(cuk.dY))
                  .a(esc.a(cuk.vG))
                  .a(esc.a(cuk.qL))
                  .a(esc.a(cuk.wv))
            )
      );
      $$1.accept(
         ern.bp,
         eru.b()
            .a(
               ert.a()
                  .a(evo.a(1.0F))
                  .a(esc.a(cuk.zD))
                  .a(esc.a(cuk.zE))
                  .a(esc.a(cuk.zH))
                  .a(esc.a(cuk.zJ))
                  .a(esc.a(cuk.zK))
                  .a(esc.a(cuk.zL))
                  .a(esc.a(cuk.zR))
                  .a(esc.a(cuk.zr))
                  .a(esc.a(cuk.zu))
                  .a(esc.a(cuk.zs))
                  .a(esc.a(cuk.zv))
                  .a(esc.a(cuk.xw))
            )
      );
      $$1.accept(
         ern.bq,
         eru.b()
            .a(
               ert.a()
                  .a(evo.a(1.0F))
                  .a(esc.a(cuk.zy))
                  .a(esc.a(cuk.zS))
                  .a(esc.a(cuk.zU))
                  .a(esc.a(cuk.lF))
                  .a(esc.a(cuk.qw))
                  .a(esc.a(cuk.pP).a(2))
                  .a(esc.a(cuk.qP).a(2))
                  .a(esc.a(cuk.qi).a(2))
                  .a(esc.a(cuk.pM).a(2))
                  .a(esc.a(cuk.tF).a(2))
            )
      );
      $$1.accept(
         ern.br,
         eru.b()
            .a(
               ert.a()
                  .a(evo.a(1.0F))
                  .a(esc.a(cuk.zB))
                  .a(esc.a(cuk.zF))
                  .a(esc.a(cuk.zN))
                  .a(esc.a(cuk.zO))
                  .a(esc.a(cuk.qw))
                  .a(esc.a(cuk.pP).a(2))
                  .a(esc.a(cuk.qP).a(2))
                  .a(esc.a(cuk.qi).a(2))
                  .a(esc.a(cuk.pM).a(2))
                  .a(esc.a(cuk.tF).a(2))
            )
      );
   }
}
