import java.util.function.BiConsumer;

public record na(jo.a a) implements mw {
   @Override
   public void generate(BiConsumer<akp<erq>, erq.a> $$0) {
      $$0.accept(
         erh.bd,
         erq.b()
            .a(
               erp.a()
                  .a(evp.a(1.0F))
                  .a(ery.a(cur.xQ).a(2))
                  .a(ery.a(cur.xS).a(2))
                  .a(ery.a(cur.qL))
                  .a(ery.a(cur.oA))
                  .a(ery.a(cur.pq))
                  .a(
                     ery.a(cur.vX)
                        .a(
                           etx.c()
                              .a(bsa.p, evw.a(7.0F, 10.0F))
                              .a(bsa.h, evw.a(7.0F, 10.0F))
                              .a(bsa.r, evw.a(6.0F, 8.0F))
                              .a(bsa.o, evw.a(5.0F, 7.0F))
                              .a(bsa.s, evw.a(10.0F, 20.0F))
                              .a(bsa.w, evw.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         erh.be,
         erq.b()
            .a(
               erp.a()
                  .a(evp.a(1.0F))
                  .a(ery.a(cur.xP))
                  .a(ery.a(cur.yc))
                  .a(ery.a(cur.yf))
                  .a(ery.a(cur.yj))
                  .a(ery.a(cur.oz))
                  .a(ery.a(cur.md))
                  .a(ery.a(cur.pu))
                  .a(ery.a(cur.oA))
            )
      );
      $$0.accept(
         erh.bf,
         erq.b()
            .a(
               erp.a()
                  .a(evp.a(1.0F))
                  .a(ery.a(cur.oA).a(2))
                  .a(ery.a(cur.pw).a(2))
                  .a(ery.a(cur.oQ).a(2))
                  .a(ery.a(cur.eX).a(2))
                  .a(ery.a(cur.qL).a(2))
                  .a(ery.a(cur.rm).a(2))
                  .a(ery.a(cur.rt).a(2))
                  .a(ery.a(cur.rl).a(2))
                  .a(ery.a(cur.ri).a(2))
                  .a(ery.a(cur.rj).a(2))
                  .a(ery.a(cur.xi).a(2))
                  .a(ery.a(cur.xh).a(2))
                  .a(ery.a(cur.xe).a(2))
                  .a(ery.a(cur.xg).a(2))
                  .a(ery.a(cur.iv))
                  .a(ery.a(cur.iz))
                  .a(ery.a(cur.iE))
                  .a(ery.a(cur.iw))
                  .a(ery.a(cur.iH))
                  .a(ery.a(cur.ix))
                  .a(ery.a(cur.iD))
                  .a(ery.a(cur.qo))
                  .a(ery.a(cur.qn))
                  .a(ery.a(cur.si))
                  .a(ery.a(cur.ox))
                  .a(ery.a(cur.pv))
                  .a(ery.a(cur.vl))
                  .a(ery.a(cur.cR))
                  .a(ery.a(cur.ue))
                  .a(ery.a(cur.ps))
                  .a(ery.a(cur.uK))
            )
      );
      $$0.accept(
         erh.bg,
         erq.b()
            .a(
               erp.a()
                  .a(evp.a(1.0F))
                  .a(ery.a(cur.xT))
                  .a(ery.a(cur.xU))
                  .a(ery.a(cur.xX))
                  .a(ery.a(cur.xZ))
                  .a(ery.a(cur.ya))
                  .a(ery.a(cur.yb))
                  .a(ery.a(cur.yh))
                  .a(ery.a(cur.xH))
                  .a(ery.a(cur.xK))
                  .a(ery.a(cur.xI))
                  .a(ery.a(cur.xL))
                  .a(ery.a(cur.vN))
            )
      );
      $$0.accept(
         erh.bh,
         erq.b()
            .a(
               erp.a()
                  .a(evp.a(1.0F))
                  .a(ery.a(cur.xO))
                  .a(ery.a(cur.yi))
                  .a(ery.a(cur.yk))
                  .a(ery.a(cur.kq))
                  .a(ery.a(cur.pe))
                  .a(ery.a(cur.oA).a(2))
                  .a(ery.a(cur.pw).a(2))
                  .a(ery.a(cur.oQ).a(2))
                  .a(ery.a(cur.ox).a(2))
                  .a(ery.a(cur.si).a(2))
            )
      );
      $$0.accept(
         erh.bi,
         erq.b()
            .a(
               erp.a()
                  .a(evp.a(1.0F))
                  .a(ery.a(cur.xR))
                  .a(ery.a(cur.xV))
                  .a(ery.a(cur.yd))
                  .a(ery.a(cur.ye))
                  .a(ery.a(cur.pe))
                  .a(ery.a(cur.oA).a(2))
                  .a(ery.a(cur.pw).a(2))
                  .a(ery.a(cur.oQ).a(2))
                  .a(ery.a(cur.ox).a(2))
                  .a(ery.a(cur.si).a(2))
            )
      );
   }
}
