import java.util.function.BiConsumer;

public record ne(jp.a a) implements mz {
   @Override
   public void generate(BiConsumer<alb<etm>, etm.a> $$0) {
      $$0.accept(
         etd.aS,
         etm.b()
            .a(
               etl.a()
                  .a(exl.a(1.0F))
                  .a(etu.a(cvt.xT).a(2))
                  .a(etu.a(cvt.xV).a(2))
                  .a(etu.a(cvt.qM))
                  .a(etu.a(cvt.oB))
                  .a(etu.a(cvt.pr))
                  .a(
                     etu.a(cvt.vY)
                        .a(
                           evt.c()
                              .a(bsx.p, exs.a(7.0F, 10.0F))
                              .a(bsx.h, exs.a(7.0F, 10.0F))
                              .a(bsx.r, exs.a(6.0F, 8.0F))
                              .a(bsx.o, exs.a(5.0F, 7.0F))
                              .a(bsx.s, exs.a(10.0F, 20.0F))
                              .a(bsx.w, exs.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         etd.aT,
         etm.b()
            .a(
               etl.a()
                  .a(exl.a(1.0F))
                  .a(etu.a(cvt.xS))
                  .a(etu.a(cvt.yf))
                  .a(etu.a(cvt.yi))
                  .a(etu.a(cvt.ym))
                  .a(etu.a(cvt.oA))
                  .a(etu.a(cvt.md))
                  .a(etu.a(cvt.pv))
                  .a(etu.a(cvt.oB))
            )
      );
      $$0.accept(
         etd.aU,
         etm.b()
            .a(
               etl.a()
                  .a(exl.a(1.0F))
                  .a(etu.a(cvt.oB).a(2))
                  .a(etu.a(cvt.px).a(2))
                  .a(etu.a(cvt.oR).a(2))
                  .a(etu.a(cvt.eX).a(2))
                  .a(etu.a(cvt.qM).a(2))
                  .a(etu.a(cvt.rn).a(2))
                  .a(etu.a(cvt.ru).a(2))
                  .a(etu.a(cvt.rm).a(2))
                  .a(etu.a(cvt.rj).a(2))
                  .a(etu.a(cvt.rk).a(2))
                  .a(etu.a(cvt.xl).a(2))
                  .a(etu.a(cvt.xk).a(2))
                  .a(etu.a(cvt.xh).a(2))
                  .a(etu.a(cvt.xj).a(2))
                  .a(etu.a(cvt.iv))
                  .a(etu.a(cvt.iz))
                  .a(etu.a(cvt.iE))
                  .a(etu.a(cvt.iw))
                  .a(etu.a(cvt.iH))
                  .a(etu.a(cvt.ix))
                  .a(etu.a(cvt.iD))
                  .a(etu.a(cvt.qp))
                  .a(etu.a(cvt.qo))
                  .a(etu.a(cvt.sj))
                  .a(etu.a(cvt.oy))
                  .a(etu.a(cvt.pw))
                  .a(etu.a(cvt.vn))
                  .a(etu.a(cvt.cR))
                  .a(etu.a(cvt.ug))
                  .a(etu.a(cvt.pt))
                  .a(etu.a(cvt.uM))
            )
      );
      $$0.accept(
         etd.aV,
         etm.b()
            .a(
               etl.a()
                  .a(exl.a(1.0F))
                  .a(etu.a(cvt.xW))
                  .a(etu.a(cvt.xX))
                  .a(etu.a(cvt.ya))
                  .a(etu.a(cvt.yc))
                  .a(etu.a(cvt.yd))
                  .a(etu.a(cvt.ye))
                  .a(etu.a(cvt.yk))
                  .a(etu.a(cvt.xK))
                  .a(etu.a(cvt.xN))
                  .a(etu.a(cvt.xL))
                  .a(etu.a(cvt.xO))
                  .a(etu.a(cvt.vP))
            )
      );
      $$0.accept(
         etd.aW,
         etm.b()
            .a(
               etl.a()
                  .a(exl.a(1.0F))
                  .a(etu.a(cvt.xR))
                  .a(etu.a(cvt.yl))
                  .a(etu.a(cvt.yn))
                  .a(etu.a(cvt.kq))
                  .a(etu.a(cvt.pf))
                  .a(etu.a(cvt.oB).a(2))
                  .a(etu.a(cvt.px).a(2))
                  .a(etu.a(cvt.oR).a(2))
                  .a(etu.a(cvt.oy).a(2))
                  .a(etu.a(cvt.sj).a(2))
            )
      );
      $$0.accept(
         etd.aX,
         etm.b()
            .a(
               etl.a()
                  .a(exl.a(1.0F))
                  .a(etu.a(cvt.xU))
                  .a(etu.a(cvt.xY))
                  .a(etu.a(cvt.yg))
                  .a(etu.a(cvt.yh))
                  .a(etu.a(cvt.pf))
                  .a(etu.a(cvt.oB).a(2))
                  .a(etu.a(cvt.px).a(2))
                  .a(etu.a(cvt.oR).a(2))
                  .a(etu.a(cvt.oy).a(2))
                  .a(etu.a(cvt.sj).a(2))
            )
      );
   }
}
