import java.util.function.BiConsumer;

public class ne implements mu {
   @Override
   public void generate(jk.a $$0, BiConsumer<ale<eqo>, eqo.a> $$1) {
      $$1.accept(
         eqf.bd,
         eqo.b()
            .a(
               eqn.a()
                  .a(eum.a(1.0F))
                  .a(eqw.a(cut.xN).a(2))
                  .a(eqw.a(cut.xP).a(2))
                  .a(eqw.a(cut.qL))
                  .a(eqw.a(cut.oz))
                  .a(eqw.a(cut.pp))
                  .a(
                     eqw.a(cut.vU)
                        .a(
                           esv.c()
                              .a(bsf.p, eus.a(7.0F, 10.0F))
                              .a(bsf.h, eus.a(7.0F, 10.0F))
                              .a(bsf.r, eus.a(6.0F, 8.0F))
                              .a(bsf.o, eus.a(5.0F, 7.0F))
                              .a(bsf.s, eus.a(10.0F, 20.0F))
                              .a(bsf.w, eus.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$1.accept(
         eqf.be,
         eqo.b()
            .a(
               eqn.a()
                  .a(eum.a(1.0F))
                  .a(eqw.a(cut.xM))
                  .a(eqw.a(cut.xZ))
                  .a(eqw.a(cut.yc))
                  .a(eqw.a(cut.yg))
                  .a(eqw.a(cut.oy))
                  .a(eqw.a(cut.md))
                  .a(eqw.a(cut.pu))
                  .a(eqw.a(cut.oz))
            )
      );
      $$1.accept(
         eqf.bf,
         eqo.b()
            .a(
               eqn.a()
                  .a(eum.a(1.0F))
                  .a(eqw.a(cut.oz).a(2))
                  .a(eqw.a(cut.pw).a(2))
                  .a(eqw.a(cut.oP).a(2))
                  .a(eqw.a(cut.eX).a(2))
                  .a(eqw.a(cut.qL).a(2))
                  .a(eqw.a(cut.rm).a(2))
                  .a(eqw.a(cut.rt).a(2))
                  .a(eqw.a(cut.rl).a(2))
                  .a(eqw.a(cut.ri).a(2))
                  .a(eqw.a(cut.rj).a(2))
                  .a(eqw.a(cut.xf).a(2))
                  .a(eqw.a(cut.xe).a(2))
                  .a(eqw.a(cut.xb).a(2))
                  .a(eqw.a(cut.xd).a(2))
                  .a(eqw.a(cut.iv))
                  .a(eqw.a(cut.iz))
                  .a(eqw.a(cut.iE))
                  .a(eqw.a(cut.iw))
                  .a(eqw.a(cut.iH))
                  .a(eqw.a(cut.ix))
                  .a(eqw.a(cut.iD))
                  .a(eqw.a(cut.qo))
                  .a(eqw.a(cut.qn))
                  .a(eqw.a(cut.si))
                  .a(eqw.a(cut.ow))
                  .a(eqw.a(cut.pv))
                  .a(eqw.a(cut.vl))
                  .a(eqw.a(cut.cR))
                  .a(eqw.a(cut.ue))
                  .a(eqw.a(cut.ps))
                  .a(eqw.a(cut.uK))
            )
      );
      $$1.accept(
         eqf.bg,
         eqo.b()
            .a(
               eqn.a()
                  .a(eum.a(1.0F))
                  .a(eqw.a(cut.xQ))
                  .a(eqw.a(cut.xR))
                  .a(eqw.a(cut.xU))
                  .a(eqw.a(cut.xW))
                  .a(eqw.a(cut.xX))
                  .a(eqw.a(cut.xY))
                  .a(eqw.a(cut.ye))
                  .a(eqw.a(cut.xE))
                  .a(eqw.a(cut.xH))
                  .a(eqw.a(cut.xF))
                  .a(eqw.a(cut.xI))
                  .a(eqw.a(cut.vL))
            )
      );
      $$1.accept(
         eqf.bh,
         eqo.b()
            .a(
               eqn.a()
                  .a(eum.a(1.0F))
                  .a(eqw.a(cut.xL))
                  .a(eqw.a(cut.yf))
                  .a(eqw.a(cut.yh))
                  .a(eqw.a(cut.kq))
                  .a(eqw.a(cut.pd))
                  .a(eqw.a(cut.oz).a(2))
                  .a(eqw.a(cut.pw).a(2))
                  .a(eqw.a(cut.oP).a(2))
                  .a(eqw.a(cut.ow).a(2))
                  .a(eqw.a(cut.si).a(2))
            )
      );
      $$1.accept(
         eqf.bi,
         eqo.b()
            .a(
               eqn.a()
                  .a(eum.a(1.0F))
                  .a(eqw.a(cut.xO))
                  .a(eqw.a(cut.xS))
                  .a(eqw.a(cut.ya))
                  .a(eqw.a(cut.yb))
                  .a(eqw.a(cut.pd))
                  .a(eqw.a(cut.oz).a(2))
                  .a(eqw.a(cut.pw).a(2))
                  .a(eqw.a(cut.oP).a(2))
                  .a(eqw.a(cut.ow).a(2))
                  .a(eqw.a(cut.si).a(2))
            )
      );
   }
}
