import java.util.function.BiConsumer;

public record nf(jq.a a) implements na {
   @Override
   public void generate(BiConsumer<ald<etq>, etq.a> $$0) {
      $$0.accept(
         eth.aT,
         etq.b()
            .a(
               etp.a()
                  .a(exp.a(1.0F))
                  .a(ety.a(cvw.xT).a(2))
                  .a(ety.a(cvw.xV).a(2))
                  .a(ety.a(cvw.qM))
                  .a(ety.a(cvw.oB))
                  .a(ety.a(cvw.pr))
                  .a(
                     ety.a(cvw.vY)
                        .a(
                           evx.c()
                              .a(bta.p, exw.a(7.0F, 10.0F))
                              .a(bta.h, exw.a(7.0F, 10.0F))
                              .a(bta.r, exw.a(6.0F, 8.0F))
                              .a(bta.o, exw.a(5.0F, 7.0F))
                              .a(bta.s, exw.a(10.0F, 20.0F))
                              .a(bta.w, exw.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         eth.aU,
         etq.b()
            .a(
               etp.a()
                  .a(exp.a(1.0F))
                  .a(ety.a(cvw.xS))
                  .a(ety.a(cvw.yf))
                  .a(ety.a(cvw.yi))
                  .a(ety.a(cvw.ym))
                  .a(ety.a(cvw.oA))
                  .a(ety.a(cvw.md))
                  .a(ety.a(cvw.pv))
                  .a(ety.a(cvw.oB))
            )
      );
      $$0.accept(
         eth.aV,
         etq.b()
            .a(
               etp.a()
                  .a(exp.a(1.0F))
                  .a(ety.a(cvw.oB).a(2))
                  .a(ety.a(cvw.px).a(2))
                  .a(ety.a(cvw.oR).a(2))
                  .a(ety.a(cvw.eX).a(2))
                  .a(ety.a(cvw.qM).a(2))
                  .a(ety.a(cvw.rn).a(2))
                  .a(ety.a(cvw.ru).a(2))
                  .a(ety.a(cvw.rm).a(2))
                  .a(ety.a(cvw.rj).a(2))
                  .a(ety.a(cvw.rk).a(2))
                  .a(ety.a(cvw.xl).a(2))
                  .a(ety.a(cvw.xk).a(2))
                  .a(ety.a(cvw.xh).a(2))
                  .a(ety.a(cvw.xj).a(2))
                  .a(ety.a(cvw.iv))
                  .a(ety.a(cvw.iz))
                  .a(ety.a(cvw.iE))
                  .a(ety.a(cvw.iw))
                  .a(ety.a(cvw.iH))
                  .a(ety.a(cvw.ix))
                  .a(ety.a(cvw.iD))
                  .a(ety.a(cvw.qp))
                  .a(ety.a(cvw.qo))
                  .a(ety.a(cvw.sj))
                  .a(ety.a(cvw.oy))
                  .a(ety.a(cvw.pw))
                  .a(ety.a(cvw.vn))
                  .a(ety.a(cvw.cR))
                  .a(ety.a(cvw.ug))
                  .a(ety.a(cvw.pt))
                  .a(ety.a(cvw.uM))
            )
      );
      $$0.accept(
         eth.aW,
         etq.b()
            .a(
               etp.a()
                  .a(exp.a(1.0F))
                  .a(ety.a(cvw.xW))
                  .a(ety.a(cvw.xX))
                  .a(ety.a(cvw.ya))
                  .a(ety.a(cvw.yc))
                  .a(ety.a(cvw.yd))
                  .a(ety.a(cvw.ye))
                  .a(ety.a(cvw.yk))
                  .a(ety.a(cvw.xK))
                  .a(ety.a(cvw.xN))
                  .a(ety.a(cvw.xL))
                  .a(ety.a(cvw.xO))
                  .a(ety.a(cvw.vP))
            )
      );
      $$0.accept(
         eth.aX,
         etq.b()
            .a(
               etp.a()
                  .a(exp.a(1.0F))
                  .a(ety.a(cvw.xR))
                  .a(ety.a(cvw.yl))
                  .a(ety.a(cvw.yn))
                  .a(ety.a(cvw.kq))
                  .a(ety.a(cvw.pf))
                  .a(ety.a(cvw.oB).a(2))
                  .a(ety.a(cvw.px).a(2))
                  .a(ety.a(cvw.oR).a(2))
                  .a(ety.a(cvw.oy).a(2))
                  .a(ety.a(cvw.sj).a(2))
            )
      );
      $$0.accept(
         eth.aY,
         etq.b()
            .a(
               etp.a()
                  .a(exp.a(1.0F))
                  .a(ety.a(cvw.xU))
                  .a(ety.a(cvw.xY))
                  .a(ety.a(cvw.yg))
                  .a(ety.a(cvw.yh))
                  .a(ety.a(cvw.pf))
                  .a(ety.a(cvw.oB).a(2))
                  .a(ety.a(cvw.px).a(2))
                  .a(ety.a(cvw.oR).a(2))
                  .a(ety.a(cvw.oy).a(2))
                  .a(ety.a(cvw.sj).a(2))
            )
      );
   }
}
