import java.util.function.BiConsumer;

public record nh(jr.a a) implements nc {
   @Override
   public void generate(BiConsumer<alg<eub>, eub.a> $$0) {
      $$0.accept(
         ets.aT,
         eub.b()
            .a(
               eua.a()
                  .a(eya.a(1.0F))
                  .a(euj.a(cwb.xT).a(2))
                  .a(euj.a(cwb.xV).a(2))
                  .a(euj.a(cwb.qM))
                  .a(euj.a(cwb.oB))
                  .a(euj.a(cwb.pr))
                  .a(
                     euj.a(cwb.vY)
                        .a(
                           ewi.c()
                              .a(btg.p, eyh.a(7.0F, 10.0F))
                              .a(btg.h, eyh.a(7.0F, 10.0F))
                              .a(btg.r, eyh.a(6.0F, 8.0F))
                              .a(btg.o, eyh.a(5.0F, 7.0F))
                              .a(btg.s, eyh.a(10.0F, 20.0F))
                              .a(btg.w, eyh.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ets.aU,
         eub.b()
            .a(
               eua.a()
                  .a(eya.a(1.0F))
                  .a(euj.a(cwb.xS))
                  .a(euj.a(cwb.yf))
                  .a(euj.a(cwb.yi))
                  .a(euj.a(cwb.ym))
                  .a(euj.a(cwb.oA))
                  .a(euj.a(cwb.md))
                  .a(euj.a(cwb.pv))
                  .a(euj.a(cwb.oB))
            )
      );
      $$0.accept(
         ets.aV,
         eub.b()
            .a(
               eua.a()
                  .a(eya.a(1.0F))
                  .a(euj.a(cwb.oB).a(2))
                  .a(euj.a(cwb.px).a(2))
                  .a(euj.a(cwb.oR).a(2))
                  .a(euj.a(cwb.eX).a(2))
                  .a(euj.a(cwb.qM).a(2))
                  .a(euj.a(cwb.rn).a(2))
                  .a(euj.a(cwb.ru).a(2))
                  .a(euj.a(cwb.rm).a(2))
                  .a(euj.a(cwb.rj).a(2))
                  .a(euj.a(cwb.rk).a(2))
                  .a(euj.a(cwb.xl).a(2))
                  .a(euj.a(cwb.xk).a(2))
                  .a(euj.a(cwb.xh).a(2))
                  .a(euj.a(cwb.xj).a(2))
                  .a(euj.a(cwb.iv))
                  .a(euj.a(cwb.iz))
                  .a(euj.a(cwb.iE))
                  .a(euj.a(cwb.iw))
                  .a(euj.a(cwb.iH))
                  .a(euj.a(cwb.ix))
                  .a(euj.a(cwb.iD))
                  .a(euj.a(cwb.qp))
                  .a(euj.a(cwb.qo))
                  .a(euj.a(cwb.sj))
                  .a(euj.a(cwb.oy))
                  .a(euj.a(cwb.pw))
                  .a(euj.a(cwb.vn))
                  .a(euj.a(cwb.cR))
                  .a(euj.a(cwb.ug))
                  .a(euj.a(cwb.pt))
                  .a(euj.a(cwb.uM))
            )
      );
      $$0.accept(
         ets.aW,
         eub.b()
            .a(
               eua.a()
                  .a(eya.a(1.0F))
                  .a(euj.a(cwb.xW))
                  .a(euj.a(cwb.xX))
                  .a(euj.a(cwb.ya))
                  .a(euj.a(cwb.yc))
                  .a(euj.a(cwb.yd))
                  .a(euj.a(cwb.ye))
                  .a(euj.a(cwb.yk))
                  .a(euj.a(cwb.xK))
                  .a(euj.a(cwb.xN))
                  .a(euj.a(cwb.xL))
                  .a(euj.a(cwb.xO))
                  .a(euj.a(cwb.vP))
            )
      );
      $$0.accept(
         ets.aX,
         eub.b()
            .a(
               eua.a()
                  .a(eya.a(1.0F))
                  .a(euj.a(cwb.xR))
                  .a(euj.a(cwb.yl))
                  .a(euj.a(cwb.yn))
                  .a(euj.a(cwb.kq))
                  .a(euj.a(cwb.pf))
                  .a(euj.a(cwb.oB).a(2))
                  .a(euj.a(cwb.px).a(2))
                  .a(euj.a(cwb.oR).a(2))
                  .a(euj.a(cwb.oy).a(2))
                  .a(euj.a(cwb.sj).a(2))
            )
      );
      $$0.accept(
         ets.aY,
         eub.b()
            .a(
               eua.a()
                  .a(eya.a(1.0F))
                  .a(euj.a(cwb.xU))
                  .a(euj.a(cwb.xY))
                  .a(euj.a(cwb.yg))
                  .a(euj.a(cwb.yh))
                  .a(euj.a(cwb.pf))
                  .a(euj.a(cwb.oB).a(2))
                  .a(euj.a(cwb.px).a(2))
                  .a(euj.a(cwb.oR).a(2))
                  .a(euj.a(cwb.oy).a(2))
                  .a(euj.a(cwb.sj).a(2))
            )
      );
   }
}
