import java.util.function.BiConsumer;

public record ni(js.a a) implements nd {
   @Override
   public void generate(BiConsumer<alh<euh>, euh.a> $$0) {
      $$0.accept(
         ety.aX,
         euh.b()
            .a(
               eug.a()
                  .a(eyg.a(1.0F))
                  .a(eup.a(cwf.xT).a(2))
                  .a(eup.a(cwf.xV).a(2))
                  .a(eup.a(cwf.qM))
                  .a(eup.a(cwf.oB))
                  .a(eup.a(cwf.pr))
                  .a(
                     eup.a(cwf.vY)
                        .a(
                           ewo.c()
                              .a(btl.p, eyn.a(7.0F, 10.0F))
                              .a(btl.h, eyn.a(7.0F, 10.0F))
                              .a(btl.r, eyn.a(6.0F, 8.0F))
                              .a(btl.o, eyn.a(5.0F, 7.0F))
                              .a(btl.s, eyn.a(10.0F, 20.0F))
                              .a(btl.w, eyn.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ety.aY,
         euh.b()
            .a(
               eug.a()
                  .a(eyg.a(1.0F))
                  .a(eup.a(cwf.xS))
                  .a(eup.a(cwf.yf))
                  .a(eup.a(cwf.yi))
                  .a(eup.a(cwf.ym))
                  .a(eup.a(cwf.oA))
                  .a(eup.a(cwf.md))
                  .a(eup.a(cwf.pv))
                  .a(eup.a(cwf.oB))
            )
      );
      $$0.accept(
         ety.aZ,
         euh.b()
            .a(
               eug.a()
                  .a(eyg.a(1.0F))
                  .a(eup.a(cwf.oB).a(2))
                  .a(eup.a(cwf.px).a(2))
                  .a(eup.a(cwf.oR).a(2))
                  .a(eup.a(cwf.eX).a(2))
                  .a(eup.a(cwf.qM).a(2))
                  .a(eup.a(cwf.rn).a(2))
                  .a(eup.a(cwf.ru).a(2))
                  .a(eup.a(cwf.rm).a(2))
                  .a(eup.a(cwf.rj).a(2))
                  .a(eup.a(cwf.rk).a(2))
                  .a(eup.a(cwf.xl).a(2))
                  .a(eup.a(cwf.xk).a(2))
                  .a(eup.a(cwf.xh).a(2))
                  .a(eup.a(cwf.xj).a(2))
                  .a(eup.a(cwf.iv))
                  .a(eup.a(cwf.iz))
                  .a(eup.a(cwf.iE))
                  .a(eup.a(cwf.iw))
                  .a(eup.a(cwf.iH))
                  .a(eup.a(cwf.ix))
                  .a(eup.a(cwf.iD))
                  .a(eup.a(cwf.qp))
                  .a(eup.a(cwf.qo))
                  .a(eup.a(cwf.sj))
                  .a(eup.a(cwf.oy))
                  .a(eup.a(cwf.pw))
                  .a(eup.a(cwf.vn))
                  .a(eup.a(cwf.cR))
                  .a(eup.a(cwf.ug))
                  .a(eup.a(cwf.pt))
                  .a(eup.a(cwf.uM))
            )
      );
      $$0.accept(
         ety.ba,
         euh.b()
            .a(
               eug.a()
                  .a(eyg.a(1.0F))
                  .a(eup.a(cwf.xW))
                  .a(eup.a(cwf.xX))
                  .a(eup.a(cwf.ya))
                  .a(eup.a(cwf.yc))
                  .a(eup.a(cwf.yd))
                  .a(eup.a(cwf.ye))
                  .a(eup.a(cwf.yk))
                  .a(eup.a(cwf.xK))
                  .a(eup.a(cwf.xN))
                  .a(eup.a(cwf.xL))
                  .a(eup.a(cwf.xO))
                  .a(eup.a(cwf.vP))
            )
      );
      $$0.accept(
         ety.bb,
         euh.b()
            .a(
               eug.a()
                  .a(eyg.a(1.0F))
                  .a(eup.a(cwf.xR))
                  .a(eup.a(cwf.yl))
                  .a(eup.a(cwf.yn))
                  .a(eup.a(cwf.kq))
                  .a(eup.a(cwf.pf))
                  .a(eup.a(cwf.oB).a(2))
                  .a(eup.a(cwf.px).a(2))
                  .a(eup.a(cwf.oR).a(2))
                  .a(eup.a(cwf.oy).a(2))
                  .a(eup.a(cwf.sj).a(2))
            )
      );
      $$0.accept(
         ety.bc,
         euh.b()
            .a(
               eug.a()
                  .a(eyg.a(1.0F))
                  .a(eup.a(cwf.xU))
                  .a(eup.a(cwf.xY))
                  .a(eup.a(cwf.yg))
                  .a(eup.a(cwf.yh))
                  .a(eup.a(cwf.pf))
                  .a(eup.a(cwf.oB).a(2))
                  .a(eup.a(cwf.px).a(2))
                  .a(eup.a(cwf.oR).a(2))
                  .a(eup.a(cwf.oy).a(2))
                  .a(eup.a(cwf.sj).a(2))
            )
      );
   }
}
