import java.util.function.BiConsumer;

public record nj(js.a a) implements ne {
   @Override
   public void generate(BiConsumer<alk<eul>, eul.a> $$0) {
      $$0.accept(
         euc.aX,
         eul.b()
            .a(
               euk.a()
                  .a(eyk.a(1.0F))
                  .a(eut.a(cwj.yj).a(2))
                  .a(eut.a(cwj.yl).a(2))
                  .a(eut.a(cwj.qM))
                  .a(eut.a(cwj.oB))
                  .a(eut.a(cwj.pr))
                  .a(
                     eut.a(cwj.wo)
                        .a(
                           ews.c()
                              .a(btp.p, eyr.a(7.0F, 10.0F))
                              .a(btp.h, eyr.a(7.0F, 10.0F))
                              .a(btp.r, eyr.a(6.0F, 8.0F))
                              .a(btp.o, eyr.a(5.0F, 7.0F))
                              .a(btp.s, eyr.a(10.0F, 20.0F))
                              .a(btp.w, eyr.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         euc.aY,
         eul.b()
            .a(
               euk.a()
                  .a(eyk.a(1.0F))
                  .a(eut.a(cwj.yi))
                  .a(eut.a(cwj.yv))
                  .a(eut.a(cwj.yy))
                  .a(eut.a(cwj.yC))
                  .a(eut.a(cwj.oA))
                  .a(eut.a(cwj.md))
                  .a(eut.a(cwj.pv))
                  .a(eut.a(cwj.oB))
            )
      );
      $$0.accept(
         euc.aZ,
         eul.b()
            .a(
               euk.a()
                  .a(eyk.a(1.0F))
                  .a(eut.a(cwj.oB).a(2))
                  .a(eut.a(cwj.px).a(2))
                  .a(eut.a(cwj.oR).a(2))
                  .a(eut.a(cwj.eX).a(2))
                  .a(eut.a(cwj.qM).a(2))
                  .a(eut.a(cwj.rD).a(2))
                  .a(eut.a(cwj.rK).a(2))
                  .a(eut.a(cwj.rC).a(2))
                  .a(eut.a(cwj.rz).a(2))
                  .a(eut.a(cwj.rA).a(2))
                  .a(eut.a(cwj.xB).a(2))
                  .a(eut.a(cwj.xA).a(2))
                  .a(eut.a(cwj.xx).a(2))
                  .a(eut.a(cwj.xz).a(2))
                  .a(eut.a(cwj.iv))
                  .a(eut.a(cwj.iz))
                  .a(eut.a(cwj.iE))
                  .a(eut.a(cwj.iw))
                  .a(eut.a(cwj.iH))
                  .a(eut.a(cwj.ix))
                  .a(eut.a(cwj.iD))
                  .a(eut.a(cwj.qp))
                  .a(eut.a(cwj.qo))
                  .a(eut.a(cwj.sz))
                  .a(eut.a(cwj.oy))
                  .a(eut.a(cwj.pw))
                  .a(eut.a(cwj.vD))
                  .a(eut.a(cwj.cR))
                  .a(eut.a(cwj.uw))
                  .a(eut.a(cwj.pt))
                  .a(eut.a(cwj.vc))
            )
      );
      $$0.accept(
         euc.ba,
         eul.b()
            .a(
               euk.a()
                  .a(eyk.a(1.0F))
                  .a(eut.a(cwj.ym))
                  .a(eut.a(cwj.yn))
                  .a(eut.a(cwj.yq))
                  .a(eut.a(cwj.ys))
                  .a(eut.a(cwj.yt))
                  .a(eut.a(cwj.yu))
                  .a(eut.a(cwj.yA))
                  .a(eut.a(cwj.ya))
                  .a(eut.a(cwj.yd))
                  .a(eut.a(cwj.yb))
                  .a(eut.a(cwj.ye))
                  .a(eut.a(cwj.wf))
            )
      );
      $$0.accept(
         euc.bb,
         eul.b()
            .a(
               euk.a()
                  .a(eyk.a(1.0F))
                  .a(eut.a(cwj.yh))
                  .a(eut.a(cwj.yB))
                  .a(eut.a(cwj.yD))
                  .a(eut.a(cwj.kq))
                  .a(eut.a(cwj.pf))
                  .a(eut.a(cwj.oB).a(2))
                  .a(eut.a(cwj.px).a(2))
                  .a(eut.a(cwj.oR).a(2))
                  .a(eut.a(cwj.oy).a(2))
                  .a(eut.a(cwj.sz).a(2))
            )
      );
      $$0.accept(
         euc.bc,
         eul.b()
            .a(
               euk.a()
                  .a(eyk.a(1.0F))
                  .a(eut.a(cwj.yk))
                  .a(eut.a(cwj.yo))
                  .a(eut.a(cwj.yw))
                  .a(eut.a(cwj.yx))
                  .a(eut.a(cwj.pf))
                  .a(eut.a(cwj.oB).a(2))
                  .a(eut.a(cwj.px).a(2))
                  .a(eut.a(cwj.oR).a(2))
                  .a(eut.a(cwj.oy).a(2))
                  .a(eut.a(cwj.sz).a(2))
            )
      );
   }
}
