import java.util.function.BiConsumer;

public record nk(js.a a) implements nf {
   @Override
   public void generate(BiConsumer<alo<ewn>, ewn.a> $$0) {
      $$0.accept(
         ewe.aX,
         ewn.b()
            .a(
               ewm.a()
                  .a(fak.a(1.0F))
                  .a(ewv.a(cxk.yR).a(2))
                  .a(ewv.a(cxk.yT).a(2))
                  .a(ewv.a(cxk.rs))
                  .a(ewv.a(cxk.pf))
                  .a(ewv.a(cxk.pV))
                  .a(
                     ewv.a(cxk.wW)
                        .a(
                           eyu.c()
                              .a(bui.p, far.a(7.0F, 10.0F))
                              .a(bui.h, far.a(7.0F, 10.0F))
                              .a(bui.r, far.a(6.0F, 8.0F))
                              .a(bui.o, far.a(5.0F, 7.0F))
                              .a(bui.s, far.a(10.0F, 20.0F))
                              .a(bui.w, far.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ewe.aY,
         ewn.b()
            .a(
               ewm.a()
                  .a(fak.a(1.0F))
                  .a(ewv.a(cxk.yQ))
                  .a(ewv.a(cxk.zd))
                  .a(ewv.a(cxk.zg))
                  .a(ewv.a(cxk.zk))
                  .a(ewv.a(cxk.pe))
                  .a(ewv.a(cxk.mA))
                  .a(ewv.a(cxk.pZ))
                  .a(ewv.a(cxk.pf))
            )
      );
      $$0.accept(
         ewe.aZ,
         ewn.b()
            .a(
               ewm.a()
                  .a(fak.a(1.0F))
                  .a(ewv.a(cxk.pf).a(2))
                  .a(ewv.a(cxk.qb).a(2))
                  .a(ewv.a(cxk.pv).a(2))
                  .a(ewv.a(cxk.fl).a(2))
                  .a(ewv.a(cxk.rs).a(2))
                  .a(ewv.a(cxk.sj).a(2))
                  .a(ewv.a(cxk.sq).a(2))
                  .a(ewv.a(cxk.si).a(2))
                  .a(ewv.a(cxk.sf).a(2))
                  .a(ewv.a(cxk.sg).a(2))
                  .a(ewv.a(cxk.yj).a(2))
                  .a(ewv.a(cxk.yi).a(2))
                  .a(ewv.a(cxk.yf).a(2))
                  .a(ewv.a(cxk.yh).a(2))
                  .a(ewv.a(cxk.iS))
                  .a(ewv.a(cxk.iW))
                  .a(ewv.a(cxk.jb))
                  .a(ewv.a(cxk.iT))
                  .a(ewv.a(cxk.je))
                  .a(ewv.a(cxk.iU))
                  .a(ewv.a(cxk.ja))
                  .a(ewv.a(cxk.qU))
                  .a(ewv.a(cxk.qT))
                  .a(ewv.a(cxk.tf))
                  .a(ewv.a(cxk.pc))
                  .a(ewv.a(cxk.qa))
                  .a(ewv.a(cxk.wl))
                  .a(ewv.a(cxk.cY))
                  .a(ewv.a(cxk.vd))
                  .a(ewv.a(cxk.pX))
                  .a(ewv.a(cxk.vK))
            )
      );
      $$0.accept(
         ewe.ba,
         ewn.b()
            .a(
               ewm.a()
                  .a(fak.a(1.0F))
                  .a(ewv.a(cxk.yU))
                  .a(ewv.a(cxk.yV))
                  .a(ewv.a(cxk.yY))
                  .a(ewv.a(cxk.za))
                  .a(ewv.a(cxk.zb))
                  .a(ewv.a(cxk.zc))
                  .a(ewv.a(cxk.zi))
                  .a(ewv.a(cxk.yI))
                  .a(ewv.a(cxk.yL))
                  .a(ewv.a(cxk.yJ))
                  .a(ewv.a(cxk.yM))
                  .a(ewv.a(cxk.wN))
            )
      );
      $$0.accept(
         ewe.bb,
         ewn.b()
            .a(
               ewm.a()
                  .a(fak.a(1.0F))
                  .a(ewv.a(cxk.yP))
                  .a(ewv.a(cxk.zj))
                  .a(ewv.a(cxk.zl))
                  .a(ewv.a(cxk.kN))
                  .a(ewv.a(cxk.pJ))
                  .a(ewv.a(cxk.pf).a(2))
                  .a(ewv.a(cxk.qb).a(2))
                  .a(ewv.a(cxk.pv).a(2))
                  .a(ewv.a(cxk.pc).a(2))
                  .a(ewv.a(cxk.tf).a(2))
            )
      );
      $$0.accept(
         ewe.bc,
         ewn.b()
            .a(
               ewm.a()
                  .a(fak.a(1.0F))
                  .a(ewv.a(cxk.yS))
                  .a(ewv.a(cxk.yW))
                  .a(ewv.a(cxk.ze))
                  .a(ewv.a(cxk.zf))
                  .a(ewv.a(cxk.pJ))
                  .a(ewv.a(cxk.pf).a(2))
                  .a(ewv.a(cxk.qb).a(2))
                  .a(ewv.a(cxk.pv).a(2))
                  .a(ewv.a(cxk.pc).a(2))
                  .a(ewv.a(cxk.tf).a(2))
            )
      );
   }
}
