import java.util.function.BiConsumer;

public record nl(jt.a a) implements ng {
   @Override
   public void generate(BiConsumer<akt<evu>, evu.a> $$0) {
      $$0.accept(
         evl.aX,
         evu.b()
            .a(
               evt.a()
                  .a(ezr.a(1.0F))
                  .a(ewc.a(cwr.yR).a(2))
                  .a(ewc.a(cwr.yT).a(2))
                  .a(ewc.a(cwr.rs))
                  .a(ewc.a(cwr.pf))
                  .a(ewc.a(cwr.pV))
                  .a(
                     ewc.a(cwr.wW)
                        .a(
                           eyb.c()
                              .a(btq.p, ezy.a(7.0F, 10.0F))
                              .a(btq.h, ezy.a(7.0F, 10.0F))
                              .a(btq.r, ezy.a(6.0F, 8.0F))
                              .a(btq.o, ezy.a(5.0F, 7.0F))
                              .a(btq.s, ezy.a(10.0F, 20.0F))
                              .a(btq.w, ezy.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         evl.aY,
         evu.b()
            .a(
               evt.a()
                  .a(ezr.a(1.0F))
                  .a(ewc.a(cwr.yQ))
                  .a(ewc.a(cwr.zd))
                  .a(ewc.a(cwr.zg))
                  .a(ewc.a(cwr.zk))
                  .a(ewc.a(cwr.pe))
                  .a(ewc.a(cwr.mA))
                  .a(ewc.a(cwr.pZ))
                  .a(ewc.a(cwr.pf))
            )
      );
      $$0.accept(
         evl.aZ,
         evu.b()
            .a(
               evt.a()
                  .a(ezr.a(1.0F))
                  .a(ewc.a(cwr.pf).a(2))
                  .a(ewc.a(cwr.qb).a(2))
                  .a(ewc.a(cwr.pv).a(2))
                  .a(ewc.a(cwr.fl).a(2))
                  .a(ewc.a(cwr.rs).a(2))
                  .a(ewc.a(cwr.sj).a(2))
                  .a(ewc.a(cwr.sq).a(2))
                  .a(ewc.a(cwr.si).a(2))
                  .a(ewc.a(cwr.sf).a(2))
                  .a(ewc.a(cwr.sg).a(2))
                  .a(ewc.a(cwr.yj).a(2))
                  .a(ewc.a(cwr.yi).a(2))
                  .a(ewc.a(cwr.yf).a(2))
                  .a(ewc.a(cwr.yh).a(2))
                  .a(ewc.a(cwr.iS))
                  .a(ewc.a(cwr.iW))
                  .a(ewc.a(cwr.jb))
                  .a(ewc.a(cwr.iT))
                  .a(ewc.a(cwr.je))
                  .a(ewc.a(cwr.iU))
                  .a(ewc.a(cwr.ja))
                  .a(ewc.a(cwr.qU))
                  .a(ewc.a(cwr.qT))
                  .a(ewc.a(cwr.tf))
                  .a(ewc.a(cwr.pc))
                  .a(ewc.a(cwr.qa))
                  .a(ewc.a(cwr.wl))
                  .a(ewc.a(cwr.cY))
                  .a(ewc.a(cwr.vd))
                  .a(ewc.a(cwr.pX))
                  .a(ewc.a(cwr.vK))
            )
      );
      $$0.accept(
         evl.ba,
         evu.b()
            .a(
               evt.a()
                  .a(ezr.a(1.0F))
                  .a(ewc.a(cwr.yU))
                  .a(ewc.a(cwr.yV))
                  .a(ewc.a(cwr.yY))
                  .a(ewc.a(cwr.za))
                  .a(ewc.a(cwr.zb))
                  .a(ewc.a(cwr.zc))
                  .a(ewc.a(cwr.zi))
                  .a(ewc.a(cwr.yI))
                  .a(ewc.a(cwr.yL))
                  .a(ewc.a(cwr.yJ))
                  .a(ewc.a(cwr.yM))
                  .a(ewc.a(cwr.wN))
            )
      );
      $$0.accept(
         evl.bb,
         evu.b()
            .a(
               evt.a()
                  .a(ezr.a(1.0F))
                  .a(ewc.a(cwr.yP))
                  .a(ewc.a(cwr.zj))
                  .a(ewc.a(cwr.zl))
                  .a(ewc.a(cwr.kN))
                  .a(ewc.a(cwr.pJ))
                  .a(ewc.a(cwr.pf).a(2))
                  .a(ewc.a(cwr.qb).a(2))
                  .a(ewc.a(cwr.pv).a(2))
                  .a(ewc.a(cwr.pc).a(2))
                  .a(ewc.a(cwr.tf).a(2))
            )
      );
      $$0.accept(
         evl.bc,
         evu.b()
            .a(
               evt.a()
                  .a(ezr.a(1.0F))
                  .a(ewc.a(cwr.yS))
                  .a(ewc.a(cwr.yW))
                  .a(ewc.a(cwr.ze))
                  .a(ewc.a(cwr.zf))
                  .a(ewc.a(cwr.pJ))
                  .a(ewc.a(cwr.pf).a(2))
                  .a(ewc.a(cwr.qb).a(2))
                  .a(ewc.a(cwr.pv).a(2))
                  .a(ewc.a(cwr.pc).a(2))
                  .a(ewc.a(cwr.tf).a(2))
            )
      );
   }
}
