import java.util.function.BiConsumer;

public record nl(jt.a a) implements ng {
   @Override
   public void generate(BiConsumer<aku<evx>, evx.a> $$0) {
      $$0.accept(
         evo.aX,
         evx.b()
            .a(
               evw.a()
                  .a(ezu.a(1.0F))
                  .a(ewf.a(cwu.yR).a(2))
                  .a(ewf.a(cwu.yT).a(2))
                  .a(ewf.a(cwu.rs))
                  .a(ewf.a(cwu.pf))
                  .a(ewf.a(cwu.pV))
                  .a(
                     ewf.a(cwu.wW)
                        .a(
                           eye.c()
                              .a(btt.p, fab.a(7.0F, 10.0F))
                              .a(btt.h, fab.a(7.0F, 10.0F))
                              .a(btt.r, fab.a(6.0F, 8.0F))
                              .a(btt.o, fab.a(5.0F, 7.0F))
                              .a(btt.s, fab.a(10.0F, 20.0F))
                              .a(btt.w, fab.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         evo.aY,
         evx.b()
            .a(
               evw.a()
                  .a(ezu.a(1.0F))
                  .a(ewf.a(cwu.yQ))
                  .a(ewf.a(cwu.zd))
                  .a(ewf.a(cwu.zg))
                  .a(ewf.a(cwu.zk))
                  .a(ewf.a(cwu.pe))
                  .a(ewf.a(cwu.mA))
                  .a(ewf.a(cwu.pZ))
                  .a(ewf.a(cwu.pf))
            )
      );
      $$0.accept(
         evo.aZ,
         evx.b()
            .a(
               evw.a()
                  .a(ezu.a(1.0F))
                  .a(ewf.a(cwu.pf).a(2))
                  .a(ewf.a(cwu.qb).a(2))
                  .a(ewf.a(cwu.pv).a(2))
                  .a(ewf.a(cwu.fl).a(2))
                  .a(ewf.a(cwu.rs).a(2))
                  .a(ewf.a(cwu.sj).a(2))
                  .a(ewf.a(cwu.sq).a(2))
                  .a(ewf.a(cwu.si).a(2))
                  .a(ewf.a(cwu.sf).a(2))
                  .a(ewf.a(cwu.sg).a(2))
                  .a(ewf.a(cwu.yj).a(2))
                  .a(ewf.a(cwu.yi).a(2))
                  .a(ewf.a(cwu.yf).a(2))
                  .a(ewf.a(cwu.yh).a(2))
                  .a(ewf.a(cwu.iS))
                  .a(ewf.a(cwu.iW))
                  .a(ewf.a(cwu.jb))
                  .a(ewf.a(cwu.iT))
                  .a(ewf.a(cwu.je))
                  .a(ewf.a(cwu.iU))
                  .a(ewf.a(cwu.ja))
                  .a(ewf.a(cwu.qU))
                  .a(ewf.a(cwu.qT))
                  .a(ewf.a(cwu.tf))
                  .a(ewf.a(cwu.pc))
                  .a(ewf.a(cwu.qa))
                  .a(ewf.a(cwu.wl))
                  .a(ewf.a(cwu.cY))
                  .a(ewf.a(cwu.vd))
                  .a(ewf.a(cwu.pX))
                  .a(ewf.a(cwu.vK))
            )
      );
      $$0.accept(
         evo.ba,
         evx.b()
            .a(
               evw.a()
                  .a(ezu.a(1.0F))
                  .a(ewf.a(cwu.yU))
                  .a(ewf.a(cwu.yV))
                  .a(ewf.a(cwu.yY))
                  .a(ewf.a(cwu.za))
                  .a(ewf.a(cwu.zb))
                  .a(ewf.a(cwu.zc))
                  .a(ewf.a(cwu.zi))
                  .a(ewf.a(cwu.yI))
                  .a(ewf.a(cwu.yL))
                  .a(ewf.a(cwu.yJ))
                  .a(ewf.a(cwu.yM))
                  .a(ewf.a(cwu.wN))
            )
      );
      $$0.accept(
         evo.bb,
         evx.b()
            .a(
               evw.a()
                  .a(ezu.a(1.0F))
                  .a(ewf.a(cwu.yP))
                  .a(ewf.a(cwu.zj))
                  .a(ewf.a(cwu.zl))
                  .a(ewf.a(cwu.kN))
                  .a(ewf.a(cwu.pJ))
                  .a(ewf.a(cwu.pf).a(2))
                  .a(ewf.a(cwu.qb).a(2))
                  .a(ewf.a(cwu.pv).a(2))
                  .a(ewf.a(cwu.pc).a(2))
                  .a(ewf.a(cwu.tf).a(2))
            )
      );
      $$0.accept(
         evo.bc,
         evx.b()
            .a(
               evw.a()
                  .a(ezu.a(1.0F))
                  .a(ewf.a(cwu.yS))
                  .a(ewf.a(cwu.yW))
                  .a(ewf.a(cwu.ze))
                  .a(ewf.a(cwu.zf))
                  .a(ewf.a(cwu.pJ))
                  .a(ewf.a(cwu.pf).a(2))
                  .a(ewf.a(cwu.qb).a(2))
                  .a(ewf.a(cwu.pv).a(2))
                  .a(ewf.a(cwu.pc).a(2))
                  .a(ewf.a(cwu.tf).a(2))
            )
      );
   }
}
