import java.util.function.BiConsumer;

public record nl(jt.a a) implements ng {
   @Override
   public void generate(BiConsumer<aku<evw>, evw.a> $$0) {
      $$0.accept(
         evn.aX,
         evw.b()
            .a(
               evv.a()
                  .a(ezt.a(1.0F))
                  .a(ewe.a(cwt.yR).a(2))
                  .a(ewe.a(cwt.yT).a(2))
                  .a(ewe.a(cwt.rs))
                  .a(ewe.a(cwt.pf))
                  .a(ewe.a(cwt.pV))
                  .a(
                     ewe.a(cwt.wW)
                        .a(
                           eyd.c()
                              .a(bts.p, faa.a(7.0F, 10.0F))
                              .a(bts.h, faa.a(7.0F, 10.0F))
                              .a(bts.r, faa.a(6.0F, 8.0F))
                              .a(bts.o, faa.a(5.0F, 7.0F))
                              .a(bts.s, faa.a(10.0F, 20.0F))
                              .a(bts.w, faa.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         evn.aY,
         evw.b()
            .a(
               evv.a()
                  .a(ezt.a(1.0F))
                  .a(ewe.a(cwt.yQ))
                  .a(ewe.a(cwt.zd))
                  .a(ewe.a(cwt.zg))
                  .a(ewe.a(cwt.zk))
                  .a(ewe.a(cwt.pe))
                  .a(ewe.a(cwt.mA))
                  .a(ewe.a(cwt.pZ))
                  .a(ewe.a(cwt.pf))
            )
      );
      $$0.accept(
         evn.aZ,
         evw.b()
            .a(
               evv.a()
                  .a(ezt.a(1.0F))
                  .a(ewe.a(cwt.pf).a(2))
                  .a(ewe.a(cwt.qb).a(2))
                  .a(ewe.a(cwt.pv).a(2))
                  .a(ewe.a(cwt.fl).a(2))
                  .a(ewe.a(cwt.rs).a(2))
                  .a(ewe.a(cwt.sj).a(2))
                  .a(ewe.a(cwt.sq).a(2))
                  .a(ewe.a(cwt.si).a(2))
                  .a(ewe.a(cwt.sf).a(2))
                  .a(ewe.a(cwt.sg).a(2))
                  .a(ewe.a(cwt.yj).a(2))
                  .a(ewe.a(cwt.yi).a(2))
                  .a(ewe.a(cwt.yf).a(2))
                  .a(ewe.a(cwt.yh).a(2))
                  .a(ewe.a(cwt.iS))
                  .a(ewe.a(cwt.iW))
                  .a(ewe.a(cwt.jb))
                  .a(ewe.a(cwt.iT))
                  .a(ewe.a(cwt.je))
                  .a(ewe.a(cwt.iU))
                  .a(ewe.a(cwt.ja))
                  .a(ewe.a(cwt.qU))
                  .a(ewe.a(cwt.qT))
                  .a(ewe.a(cwt.tf))
                  .a(ewe.a(cwt.pc))
                  .a(ewe.a(cwt.qa))
                  .a(ewe.a(cwt.wl))
                  .a(ewe.a(cwt.cY))
                  .a(ewe.a(cwt.vd))
                  .a(ewe.a(cwt.pX))
                  .a(ewe.a(cwt.vK))
            )
      );
      $$0.accept(
         evn.ba,
         evw.b()
            .a(
               evv.a()
                  .a(ezt.a(1.0F))
                  .a(ewe.a(cwt.yU))
                  .a(ewe.a(cwt.yV))
                  .a(ewe.a(cwt.yY))
                  .a(ewe.a(cwt.za))
                  .a(ewe.a(cwt.zb))
                  .a(ewe.a(cwt.zc))
                  .a(ewe.a(cwt.zi))
                  .a(ewe.a(cwt.yI))
                  .a(ewe.a(cwt.yL))
                  .a(ewe.a(cwt.yJ))
                  .a(ewe.a(cwt.yM))
                  .a(ewe.a(cwt.wN))
            )
      );
      $$0.accept(
         evn.bb,
         evw.b()
            .a(
               evv.a()
                  .a(ezt.a(1.0F))
                  .a(ewe.a(cwt.yP))
                  .a(ewe.a(cwt.zj))
                  .a(ewe.a(cwt.zl))
                  .a(ewe.a(cwt.kN))
                  .a(ewe.a(cwt.pJ))
                  .a(ewe.a(cwt.pf).a(2))
                  .a(ewe.a(cwt.qb).a(2))
                  .a(ewe.a(cwt.pv).a(2))
                  .a(ewe.a(cwt.pc).a(2))
                  .a(ewe.a(cwt.tf).a(2))
            )
      );
      $$0.accept(
         evn.bc,
         evw.b()
            .a(
               evv.a()
                  .a(ezt.a(1.0F))
                  .a(ewe.a(cwt.yS))
                  .a(ewe.a(cwt.yW))
                  .a(ewe.a(cwt.ze))
                  .a(ewe.a(cwt.zf))
                  .a(ewe.a(cwt.pJ))
                  .a(ewe.a(cwt.pf).a(2))
                  .a(ewe.a(cwt.qb).a(2))
                  .a(ewe.a(cwt.pv).a(2))
                  .a(ewe.a(cwt.pc).a(2))
                  .a(ewe.a(cwt.tf).a(2))
            )
      );
   }
}
