import java.util.function.BiConsumer;

public record nm(js.a a) implements nh {
   @Override
   public void generate(BiConsumer<aly<ewm>, ewm.a> $$0) {
      $$0.accept(
         ewd.aX,
         ewm.b()
            .a(
               ewl.a()
                  .a(fal.a(1.0F))
                  .a(ewu.a(cxo.yH).a(2))
                  .a(ewu.a(cxo.yJ).a(2))
                  .a(ewu.a(cxo.rj))
                  .a(ewu.a(cxo.oW))
                  .a(ewu.a(cxo.pM))
                  .a(
                     ewu.a(cxo.wM)
                        .a(
                           eyt.c()
                              .a(bum.p, fas.a(7.0F, 10.0F))
                              .a(bum.h, fas.a(7.0F, 10.0F))
                              .a(bum.r, fas.a(6.0F, 8.0F))
                              .a(bum.o, fas.a(5.0F, 7.0F))
                              .a(bum.s, fas.a(10.0F, 20.0F))
                              .a(bum.w, fas.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ewd.aY,
         ewm.b()
            .a(
               ewl.a()
                  .a(fal.a(1.0F))
                  .a(ewu.a(cxo.yG))
                  .a(ewu.a(cxo.yT))
                  .a(ewu.a(cxo.yW))
                  .a(ewu.a(cxo.za))
                  .a(ewu.a(cxo.oV))
                  .a(ewu.a(cxo.mr))
                  .a(ewu.a(cxo.pQ))
                  .a(ewu.a(cxo.oW))
            )
      );
      $$0.accept(
         ewd.aZ,
         ewm.b()
            .a(
               ewl.a()
                  .a(fal.a(1.0F))
                  .a(ewu.a(cxo.oW).a(2))
                  .a(ewu.a(cxo.pS).a(2))
                  .a(ewu.a(cxo.pm).a(2))
                  .a(ewu.a(cxo.fj).a(2))
                  .a(ewu.a(cxo.rj).a(2))
                  .a(ewu.a(cxo.sa).a(2))
                  .a(ewu.a(cxo.sh).a(2))
                  .a(ewu.a(cxo.rZ).a(2))
                  .a(ewu.a(cxo.rW).a(2))
                  .a(ewu.a(cxo.rX).a(2))
                  .a(ewu.a(cxo.xZ).a(2))
                  .a(ewu.a(cxo.xY).a(2))
                  .a(ewu.a(cxo.xV).a(2))
                  .a(ewu.a(cxo.xX).a(2))
                  .a(ewu.a(cxo.iJ))
                  .a(ewu.a(cxo.iN))
                  .a(ewu.a(cxo.iS))
                  .a(ewu.a(cxo.iK))
                  .a(ewu.a(cxo.iV))
                  .a(ewu.a(cxo.iL))
                  .a(ewu.a(cxo.iR))
                  .a(ewu.a(cxo.qL))
                  .a(ewu.a(cxo.qK))
                  .a(ewu.a(cxo.sW))
                  .a(ewu.a(cxo.oT))
                  .a(ewu.a(cxo.pR))
                  .a(ewu.a(cxo.wb))
                  .a(ewu.a(cxo.cY))
                  .a(ewu.a(cxo.uU))
                  .a(ewu.a(cxo.pO))
                  .a(ewu.a(cxo.vA))
            )
      );
      $$0.accept(
         ewd.ba,
         ewm.b()
            .a(
               ewl.a()
                  .a(fal.a(1.0F))
                  .a(ewu.a(cxo.yK))
                  .a(ewu.a(cxo.yL))
                  .a(ewu.a(cxo.yO))
                  .a(ewu.a(cxo.yQ))
                  .a(ewu.a(cxo.yR))
                  .a(ewu.a(cxo.yS))
                  .a(ewu.a(cxo.yY))
                  .a(ewu.a(cxo.yy))
                  .a(ewu.a(cxo.yB))
                  .a(ewu.a(cxo.yz))
                  .a(ewu.a(cxo.yC))
                  .a(ewu.a(cxo.wD))
            )
      );
      $$0.accept(
         ewd.bb,
         ewm.b()
            .a(
               ewl.a()
                  .a(fal.a(1.0F))
                  .a(ewu.a(cxo.yF))
                  .a(ewu.a(cxo.yZ))
                  .a(ewu.a(cxo.zb))
                  .a(ewu.a(cxo.kE))
                  .a(ewu.a(cxo.pA))
                  .a(ewu.a(cxo.oW).a(2))
                  .a(ewu.a(cxo.pS).a(2))
                  .a(ewu.a(cxo.pm).a(2))
                  .a(ewu.a(cxo.oT).a(2))
                  .a(ewu.a(cxo.sW).a(2))
            )
      );
      $$0.accept(
         ewd.bc,
         ewm.b()
            .a(
               ewl.a()
                  .a(fal.a(1.0F))
                  .a(ewu.a(cxo.yI))
                  .a(ewu.a(cxo.yM))
                  .a(ewu.a(cxo.yU))
                  .a(ewu.a(cxo.yV))
                  .a(ewu.a(cxo.pA))
                  .a(ewu.a(cxo.oW).a(2))
                  .a(ewu.a(cxo.pS).a(2))
                  .a(ewu.a(cxo.pm).a(2))
                  .a(ewu.a(cxo.oT).a(2))
                  .a(ewu.a(cxo.sW).a(2))
            )
      );
   }
}
