import java.util.function.BiConsumer;

public record np(jg.a a) implements nk {
   @Override
   public void generate(BiConsumer<ald<eys>, eys.a> $$0) {
      $$0.accept(
         eyj.aX,
         eys.b()
            .a(
               eyr.a()
                  .a(fcp.a(1.0F))
                  .a(eza.a(cyw.yV).a(2))
                  .a(eza.a(cyw.yX).a(2))
                  .a(eza.a(cyw.rw))
                  .a(eza.a(cyw.pj))
                  .a(eza.a(cyw.pZ))
                  .a(
                     eza.a(cyw.xa)
                        .a(
                           faz.c()
                              .a(bvg.p, fcw.a(7.0F, 10.0F))
                              .a(bvg.h, fcw.a(7.0F, 10.0F))
                              .a(bvg.r, fcw.a(6.0F, 8.0F))
                              .a(bvg.o, fcw.a(5.0F, 7.0F))
                              .a(bvg.s, fcw.a(10.0F, 20.0F))
                              .a(bvg.w, fcw.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         eyj.aY,
         eys.b()
            .a(
               eyr.a()
                  .a(fcp.a(1.0F))
                  .a(eza.a(cyw.yU))
                  .a(eza.a(cyw.zh))
                  .a(eza.a(cyw.zk))
                  .a(eza.a(cyw.zo))
                  .a(eza.a(cyw.pi))
                  .a(eza.a(cyw.mC))
                  .a(eza.a(cyw.qd))
                  .a(eza.a(cyw.pj))
            )
      );
      $$0.accept(
         eyj.aZ,
         eys.b()
            .a(
               eyr.a()
                  .a(fcp.a(1.0F))
                  .a(eza.a(cyw.pj).a(2))
                  .a(eza.a(cyw.qf).a(2))
                  .a(eza.a(cyw.pz).a(2))
                  .a(eza.a(cyw.fn).a(2))
                  .a(eza.a(cyw.rw).a(2))
                  .a(eza.a(cyw.sn).a(2))
                  .a(eza.a(cyw.su).a(2))
                  .a(eza.a(cyw.sm).a(2))
                  .a(eza.a(cyw.sj).a(2))
                  .a(eza.a(cyw.sk).a(2))
                  .a(eza.a(cyw.yn).a(2))
                  .a(eza.a(cyw.ym).a(2))
                  .a(eza.a(cyw.yj).a(2))
                  .a(eza.a(cyw.yl).a(2))
                  .a(eza.a(cyw.iU))
                  .a(eza.a(cyw.iY))
                  .a(eza.a(cyw.jd))
                  .a(eza.a(cyw.iV))
                  .a(eza.a(cyw.jg))
                  .a(eza.a(cyw.iW))
                  .a(eza.a(cyw.jc))
                  .a(eza.a(cyw.qY))
                  .a(eza.a(cyw.qX))
                  .a(eza.a(cyw.tj))
                  .a(eza.a(cyw.pg))
                  .a(eza.a(cyw.qe))
                  .a(eza.a(cyw.wp))
                  .a(eza.a(cyw.cY))
                  .a(eza.a(cyw.vh))
                  .a(eza.a(cyw.qb))
                  .a(eza.a(cyw.vO))
            )
      );
      $$0.accept(
         eyj.ba,
         eys.b()
            .a(
               eyr.a()
                  .a(fcp.a(1.0F))
                  .a(eza.a(cyw.yY))
                  .a(eza.a(cyw.yZ))
                  .a(eza.a(cyw.zc))
                  .a(eza.a(cyw.ze))
                  .a(eza.a(cyw.zf))
                  .a(eza.a(cyw.zg))
                  .a(eza.a(cyw.zm))
                  .a(eza.a(cyw.yM))
                  .a(eza.a(cyw.yP))
                  .a(eza.a(cyw.yN))
                  .a(eza.a(cyw.yQ))
                  .a(eza.a(cyw.wR))
            )
      );
      $$0.accept(
         eyj.bb,
         eys.b()
            .a(
               eyr.a()
                  .a(fcp.a(1.0F))
                  .a(eza.a(cyw.yT))
                  .a(eza.a(cyw.zn))
                  .a(eza.a(cyw.zp))
                  .a(eza.a(cyw.kP))
                  .a(eza.a(cyw.pN))
                  .a(eza.a(cyw.pj).a(2))
                  .a(eza.a(cyw.qf).a(2))
                  .a(eza.a(cyw.pz).a(2))
                  .a(eza.a(cyw.pg).a(2))
                  .a(eza.a(cyw.tj).a(2))
            )
      );
      $$0.accept(
         eyj.bc,
         eys.b()
            .a(
               eyr.a()
                  .a(fcp.a(1.0F))
                  .a(eza.a(cyw.yW))
                  .a(eza.a(cyw.za))
                  .a(eza.a(cyw.zi))
                  .a(eza.a(cyw.zj))
                  .a(eza.a(cyw.pN))
                  .a(eza.a(cyw.pj).a(2))
                  .a(eza.a(cyw.qf).a(2))
                  .a(eza.a(cyw.pz).a(2))
                  .a(eza.a(cyw.pg).a(2))
                  .a(eza.a(cyw.tj).a(2))
            )
      );
   }
}
