import java.util.function.BiConsumer;

public record np(jg.a a) implements nk {
   @Override
   public void generate(BiConsumer<alf<ezm>, ezm.a> $$0) {
      $$0.accept(
         ezd.aX,
         ezm.b()
            .a(
               ezl.a()
                  .a(fdj.a(1.0F))
                  .a(ezu.a(czh.zc).a(2))
                  .a(ezu.a(czh.ze).a(2))
                  .a(ezu.a(czh.rB))
                  .a(ezu.a(czh.po))
                  .a(ezu.a(czh.qe))
                  .a(
                     ezu.a(czh.xh)
                        .a(
                           fbt.c()
                              .a(bvl.p, fdq.a(7.0F, 10.0F))
                              .a(bvl.h, fdq.a(7.0F, 10.0F))
                              .a(bvl.r, fdq.a(6.0F, 8.0F))
                              .a(bvl.o, fdq.a(5.0F, 7.0F))
                              .a(bvl.s, fdq.a(10.0F, 20.0F))
                              .a(bvl.w, fdq.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         ezd.aY,
         ezm.b()
            .a(
               ezl.a()
                  .a(fdj.a(1.0F))
                  .a(ezu.a(czh.zb))
                  .a(ezu.a(czh.zo))
                  .a(ezu.a(czh.zr))
                  .a(ezu.a(czh.zv))
                  .a(ezu.a(czh.pn))
                  .a(ezu.a(czh.mH))
                  .a(ezu.a(czh.qi))
                  .a(ezu.a(czh.po))
            )
      );
      $$0.accept(
         ezd.aZ,
         ezm.b()
            .a(
               ezl.a()
                  .a(fdj.a(1.0F))
                  .a(ezu.a(czh.po).a(2))
                  .a(ezu.a(czh.qk).a(2))
                  .a(ezu.a(czh.pE).a(2))
                  .a(ezu.a(czh.fs).a(2))
                  .a(ezu.a(czh.rB).a(2))
                  .a(ezu.a(czh.su).a(2))
                  .a(ezu.a(czh.sB).a(2))
                  .a(ezu.a(czh.st).a(2))
                  .a(ezu.a(czh.sq).a(2))
                  .a(ezu.a(czh.sr).a(2))
                  .a(ezu.a(czh.yu).a(2))
                  .a(ezu.a(czh.yt).a(2))
                  .a(ezu.a(czh.yq).a(2))
                  .a(ezu.a(czh.ys).a(2))
                  .a(ezu.a(czh.iZ))
                  .a(ezu.a(czh.jd))
                  .a(ezu.a(czh.ji))
                  .a(ezu.a(czh.ja))
                  .a(ezu.a(czh.jl))
                  .a(ezu.a(czh.jb))
                  .a(ezu.a(czh.jh))
                  .a(ezu.a(czh.rd))
                  .a(ezu.a(czh.rc))
                  .a(ezu.a(czh.tq))
                  .a(ezu.a(czh.pl))
                  .a(ezu.a(czh.qj))
                  .a(ezu.a(czh.ww))
                  .a(ezu.a(czh.cZ))
                  .a(ezu.a(czh.vo))
                  .a(ezu.a(czh.qg))
                  .a(ezu.a(czh.vV))
            )
      );
      $$0.accept(
         ezd.ba,
         ezm.b()
            .a(
               ezl.a()
                  .a(fdj.a(1.0F))
                  .a(ezu.a(czh.zf))
                  .a(ezu.a(czh.zg))
                  .a(ezu.a(czh.zj))
                  .a(ezu.a(czh.zl))
                  .a(ezu.a(czh.zm))
                  .a(ezu.a(czh.zn))
                  .a(ezu.a(czh.zt))
                  .a(ezu.a(czh.yT))
                  .a(ezu.a(czh.yW))
                  .a(ezu.a(czh.yU))
                  .a(ezu.a(czh.yX))
                  .a(ezu.a(czh.wY))
            )
      );
      $$0.accept(
         ezd.bb,
         ezm.b()
            .a(
               ezl.a()
                  .a(fdj.a(1.0F))
                  .a(ezu.a(czh.za))
                  .a(ezu.a(czh.zu))
                  .a(ezu.a(czh.zw))
                  .a(ezu.a(czh.kU))
                  .a(ezu.a(czh.pS))
                  .a(ezu.a(czh.po).a(2))
                  .a(ezu.a(czh.qk).a(2))
                  .a(ezu.a(czh.pE).a(2))
                  .a(ezu.a(czh.pl).a(2))
                  .a(ezu.a(czh.tq).a(2))
            )
      );
      $$0.accept(
         ezd.bc,
         ezm.b()
            .a(
               ezl.a()
                  .a(fdj.a(1.0F))
                  .a(ezu.a(czh.zd))
                  .a(ezu.a(czh.zh))
                  .a(ezu.a(czh.zp))
                  .a(ezu.a(czh.zq))
                  .a(ezu.a(czh.pS))
                  .a(ezu.a(czh.po).a(2))
                  .a(ezu.a(czh.qk).a(2))
                  .a(ezu.a(czh.pE).a(2))
                  .a(ezu.a(czh.pl).a(2))
                  .a(ezu.a(czh.tq).a(2))
            )
      );
   }
}
