import java.util.function.BiConsumer;

public record np(jg.a a) implements nk {
   @Override
   public void generate(BiConsumer<alf<eze>, eze.a> $$0) {
      $$0.accept(
         eyv.aX,
         eze.b()
            .a(
               ezd.a()
                  .a(fdb.a(1.0F))
                  .a(ezm.a(czc.yX).a(2))
                  .a(ezm.a(czc.yZ).a(2))
                  .a(ezm.a(czc.ry))
                  .a(ezm.a(czc.pl))
                  .a(ezm.a(czc.qb))
                  .a(
                     ezm.a(czc.xc)
                        .a(
                           fbl.c()
                              .a(bvj.p, fdi.a(7.0F, 10.0F))
                              .a(bvj.h, fdi.a(7.0F, 10.0F))
                              .a(bvj.r, fdi.a(6.0F, 8.0F))
                              .a(bvj.o, fdi.a(5.0F, 7.0F))
                              .a(bvj.s, fdi.a(10.0F, 20.0F))
                              .a(bvj.w, fdi.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         eyv.aY,
         eze.b()
            .a(
               ezd.a()
                  .a(fdb.a(1.0F))
                  .a(ezm.a(czc.yW))
                  .a(ezm.a(czc.zj))
                  .a(ezm.a(czc.zm))
                  .a(ezm.a(czc.zq))
                  .a(ezm.a(czc.pk))
                  .a(ezm.a(czc.mE))
                  .a(ezm.a(czc.qf))
                  .a(ezm.a(czc.pl))
            )
      );
      $$0.accept(
         eyv.aZ,
         eze.b()
            .a(
               ezd.a()
                  .a(fdb.a(1.0F))
                  .a(ezm.a(czc.pl).a(2))
                  .a(ezm.a(czc.qh).a(2))
                  .a(ezm.a(czc.pB).a(2))
                  .a(ezm.a(czc.fp).a(2))
                  .a(ezm.a(czc.ry).a(2))
                  .a(ezm.a(czc.sp).a(2))
                  .a(ezm.a(czc.sw).a(2))
                  .a(ezm.a(czc.so).a(2))
                  .a(ezm.a(czc.sl).a(2))
                  .a(ezm.a(czc.sm).a(2))
                  .a(ezm.a(czc.yp).a(2))
                  .a(ezm.a(czc.yo).a(2))
                  .a(ezm.a(czc.yl).a(2))
                  .a(ezm.a(czc.yn).a(2))
                  .a(ezm.a(czc.iW))
                  .a(ezm.a(czc.ja))
                  .a(ezm.a(czc.jf))
                  .a(ezm.a(czc.iX))
                  .a(ezm.a(czc.ji))
                  .a(ezm.a(czc.iY))
                  .a(ezm.a(czc.je))
                  .a(ezm.a(czc.ra))
                  .a(ezm.a(czc.qZ))
                  .a(ezm.a(czc.tl))
                  .a(ezm.a(czc.pi))
                  .a(ezm.a(czc.qg))
                  .a(ezm.a(czc.wr))
                  .a(ezm.a(czc.cZ))
                  .a(ezm.a(czc.vj))
                  .a(ezm.a(czc.qd))
                  .a(ezm.a(czc.vQ))
            )
      );
      $$0.accept(
         eyv.ba,
         eze.b()
            .a(
               ezd.a()
                  .a(fdb.a(1.0F))
                  .a(ezm.a(czc.za))
                  .a(ezm.a(czc.zb))
                  .a(ezm.a(czc.ze))
                  .a(ezm.a(czc.zg))
                  .a(ezm.a(czc.zh))
                  .a(ezm.a(czc.zi))
                  .a(ezm.a(czc.zo))
                  .a(ezm.a(czc.yO))
                  .a(ezm.a(czc.yR))
                  .a(ezm.a(czc.yP))
                  .a(ezm.a(czc.yS))
                  .a(ezm.a(czc.wT))
            )
      );
      $$0.accept(
         eyv.bb,
         eze.b()
            .a(
               ezd.a()
                  .a(fdb.a(1.0F))
                  .a(ezm.a(czc.yV))
                  .a(ezm.a(czc.zp))
                  .a(ezm.a(czc.zr))
                  .a(ezm.a(czc.kR))
                  .a(ezm.a(czc.pP))
                  .a(ezm.a(czc.pl).a(2))
                  .a(ezm.a(czc.qh).a(2))
                  .a(ezm.a(czc.pB).a(2))
                  .a(ezm.a(czc.pi).a(2))
                  .a(ezm.a(czc.tl).a(2))
            )
      );
      $$0.accept(
         eyv.bc,
         eze.b()
            .a(
               ezd.a()
                  .a(fdb.a(1.0F))
                  .a(ezm.a(czc.yY))
                  .a(ezm.a(czc.zc))
                  .a(ezm.a(czc.zk))
                  .a(ezm.a(czc.zl))
                  .a(ezm.a(czc.pP))
                  .a(ezm.a(czc.pl).a(2))
                  .a(ezm.a(czc.qh).a(2))
                  .a(ezm.a(czc.pB).a(2))
                  .a(ezm.a(czc.pi).a(2))
                  .a(ezm.a(czc.tl).a(2))
            )
      );
   }
}
