import java.util.function.BiConsumer;

public record nq(jh.a a) implements nl {
   @Override
   public void generate(BiConsumer<alh<fam>, fam.a> $$0) {
      $$0.accept(
         fad.aX,
         fam.b()
            .a(
               fal.a()
                  .a(fej.a(1.0F))
                  .a(fau.a(dac.zc).a(2))
                  .a(fau.a(dac.ze).a(2))
                  .a(fau.a(dac.rB))
                  .a(fau.a(dac.po))
                  .a(fau.a(dac.qe))
                  .a(
                     fau.a(dac.xh)
                        .a(
                           fct.c()
                              .a(bvz.p, feq.a(7.0F, 10.0F))
                              .a(bvz.h, feq.a(7.0F, 10.0F))
                              .a(bvz.r, feq.a(6.0F, 8.0F))
                              .a(bvz.o, feq.a(5.0F, 7.0F))
                              .a(bvz.s, feq.a(10.0F, 20.0F))
                              .a(bvz.w, feq.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         fad.aY,
         fam.b()
            .a(
               fal.a()
                  .a(fej.a(1.0F))
                  .a(fau.a(dac.zb))
                  .a(fau.a(dac.zo))
                  .a(fau.a(dac.zr))
                  .a(fau.a(dac.zv))
                  .a(fau.a(dac.pn))
                  .a(fau.a(dac.mH))
                  .a(fau.a(dac.qi))
                  .a(fau.a(dac.po))
            )
      );
      $$0.accept(
         fad.aZ,
         fam.b()
            .a(
               fal.a()
                  .a(fej.a(1.0F))
                  .a(fau.a(dac.po).a(2))
                  .a(fau.a(dac.qk).a(2))
                  .a(fau.a(dac.pE).a(2))
                  .a(fau.a(dac.fs).a(2))
                  .a(fau.a(dac.rB).a(2))
                  .a(fau.a(dac.su).a(2))
                  .a(fau.a(dac.sB).a(2))
                  .a(fau.a(dac.st).a(2))
                  .a(fau.a(dac.sq).a(2))
                  .a(fau.a(dac.sr).a(2))
                  .a(fau.a(dac.yu).a(2))
                  .a(fau.a(dac.yt).a(2))
                  .a(fau.a(dac.yq).a(2))
                  .a(fau.a(dac.ys).a(2))
                  .a(fau.a(dac.iZ))
                  .a(fau.a(dac.jd))
                  .a(fau.a(dac.ji))
                  .a(fau.a(dac.ja))
                  .a(fau.a(dac.jl))
                  .a(fau.a(dac.jb))
                  .a(fau.a(dac.jh))
                  .a(fau.a(dac.rd))
                  .a(fau.a(dac.rc))
                  .a(fau.a(dac.tq))
                  .a(fau.a(dac.pl))
                  .a(fau.a(dac.qj))
                  .a(fau.a(dac.ww))
                  .a(fau.a(dac.cZ))
                  .a(fau.a(dac.vo))
                  .a(fau.a(dac.qg))
                  .a(fau.a(dac.vV))
            )
      );
      $$0.accept(
         fad.ba,
         fam.b()
            .a(
               fal.a()
                  .a(fej.a(1.0F))
                  .a(fau.a(dac.zf))
                  .a(fau.a(dac.zg))
                  .a(fau.a(dac.zj))
                  .a(fau.a(dac.zl))
                  .a(fau.a(dac.zm))
                  .a(fau.a(dac.zn))
                  .a(fau.a(dac.zt))
                  .a(fau.a(dac.yT))
                  .a(fau.a(dac.yW))
                  .a(fau.a(dac.yU))
                  .a(fau.a(dac.yX))
                  .a(fau.a(dac.wY))
            )
      );
      $$0.accept(
         fad.bb,
         fam.b()
            .a(
               fal.a()
                  .a(fej.a(1.0F))
                  .a(fau.a(dac.za))
                  .a(fau.a(dac.zu))
                  .a(fau.a(dac.zw))
                  .a(fau.a(dac.kU))
                  .a(fau.a(dac.pS))
                  .a(fau.a(dac.po).a(2))
                  .a(fau.a(dac.qk).a(2))
                  .a(fau.a(dac.pE).a(2))
                  .a(fau.a(dac.pl).a(2))
                  .a(fau.a(dac.tq).a(2))
            )
      );
      $$0.accept(
         fad.bc,
         fam.b()
            .a(
               fal.a()
                  .a(fej.a(1.0F))
                  .a(fau.a(dac.zd))
                  .a(fau.a(dac.zh))
                  .a(fau.a(dac.zp))
                  .a(fau.a(dac.zq))
                  .a(fau.a(dac.pS))
                  .a(fau.a(dac.po).a(2))
                  .a(fau.a(dac.qk).a(2))
                  .a(fau.a(dac.pE).a(2))
                  .a(fau.a(dac.pl).a(2))
                  .a(fau.a(dac.tq).a(2))
            )
      );
   }
}
