import java.util.function.BiConsumer;

public record nr(ji.a a) implements nm {
   @Override
   public void generate(BiConsumer<alj<fao>, fao.a> $$0) {
      $$0.accept(
         faf.aX,
         fao.b()
            .a(
               fan.a()
                  .a(fel.a(1.0F))
                  .a(faw.a(dae.zc).a(2))
                  .a(faw.a(dae.ze).a(2))
                  .a(faw.a(dae.rB))
                  .a(faw.a(dae.po))
                  .a(faw.a(dae.qe))
                  .a(
                     faw.a(dae.xh)
                        .a(
                           fcv.c()
                              .a(bwb.p, fes.a(7.0F, 10.0F))
                              .a(bwb.h, fes.a(7.0F, 10.0F))
                              .a(bwb.r, fes.a(6.0F, 8.0F))
                              .a(bwb.o, fes.a(5.0F, 7.0F))
                              .a(bwb.s, fes.a(10.0F, 20.0F))
                              .a(bwb.w, fes.a(7.0F, 10.0F))
                        )
                  )
            )
      );
      $$0.accept(
         faf.aY,
         fao.b()
            .a(
               fan.a()
                  .a(fel.a(1.0F))
                  .a(faw.a(dae.zb))
                  .a(faw.a(dae.zo))
                  .a(faw.a(dae.zr))
                  .a(faw.a(dae.zv))
                  .a(faw.a(dae.pn))
                  .a(faw.a(dae.mH))
                  .a(faw.a(dae.qi))
                  .a(faw.a(dae.po))
            )
      );
      $$0.accept(
         faf.aZ,
         fao.b()
            .a(
               fan.a()
                  .a(fel.a(1.0F))
                  .a(faw.a(dae.po).a(2))
                  .a(faw.a(dae.qk).a(2))
                  .a(faw.a(dae.pE).a(2))
                  .a(faw.a(dae.fs).a(2))
                  .a(faw.a(dae.rB).a(2))
                  .a(faw.a(dae.su).a(2))
                  .a(faw.a(dae.sB).a(2))
                  .a(faw.a(dae.st).a(2))
                  .a(faw.a(dae.sq).a(2))
                  .a(faw.a(dae.sr).a(2))
                  .a(faw.a(dae.yu).a(2))
                  .a(faw.a(dae.yt).a(2))
                  .a(faw.a(dae.yq).a(2))
                  .a(faw.a(dae.ys).a(2))
                  .a(faw.a(dae.iZ))
                  .a(faw.a(dae.jd))
                  .a(faw.a(dae.ji))
                  .a(faw.a(dae.ja))
                  .a(faw.a(dae.jl))
                  .a(faw.a(dae.jb))
                  .a(faw.a(dae.jh))
                  .a(faw.a(dae.rd))
                  .a(faw.a(dae.rc))
                  .a(faw.a(dae.tq))
                  .a(faw.a(dae.pl))
                  .a(faw.a(dae.qj))
                  .a(faw.a(dae.ww))
                  .a(faw.a(dae.cZ))
                  .a(faw.a(dae.vo))
                  .a(faw.a(dae.qg))
                  .a(faw.a(dae.vV))
            )
      );
      $$0.accept(
         faf.ba,
         fao.b()
            .a(
               fan.a()
                  .a(fel.a(1.0F))
                  .a(faw.a(dae.zf))
                  .a(faw.a(dae.zg))
                  .a(faw.a(dae.zj))
                  .a(faw.a(dae.zl))
                  .a(faw.a(dae.zm))
                  .a(faw.a(dae.zn))
                  .a(faw.a(dae.zt))
                  .a(faw.a(dae.yT))
                  .a(faw.a(dae.yW))
                  .a(faw.a(dae.yU))
                  .a(faw.a(dae.yX))
                  .a(faw.a(dae.wY))
            )
      );
      $$0.accept(
         faf.bb,
         fao.b()
            .a(
               fan.a()
                  .a(fel.a(1.0F))
                  .a(faw.a(dae.za))
                  .a(faw.a(dae.zu))
                  .a(faw.a(dae.zw))
                  .a(faw.a(dae.kU))
                  .a(faw.a(dae.pS))
                  .a(faw.a(dae.po).a(2))
                  .a(faw.a(dae.qk).a(2))
                  .a(faw.a(dae.pE).a(2))
                  .a(faw.a(dae.pl).a(2))
                  .a(faw.a(dae.tq).a(2))
            )
      );
      $$0.accept(
         faf.bc,
         fao.b()
            .a(
               fan.a()
                  .a(fel.a(1.0F))
                  .a(faw.a(dae.zd))
                  .a(faw.a(dae.zh))
                  .a(faw.a(dae.zp))
                  .a(faw.a(dae.zq))
                  .a(faw.a(dae.pS))
                  .a(faw.a(dae.po).a(2))
                  .a(faw.a(dae.qk).a(2))
                  .a(faw.a(dae.pE).a(2))
                  .a(faw.a(dae.pl).a(2))
                  .a(faw.a(dae.tq).a(2))
            )
      );
   }
}
