import java.util.List;

public class op {
   public static final aeq<dna<?, ?>> a = om.a("ore_magma");
   public static final aeq<dna<?, ?>> b = om.a("ore_soul_sand");
   public static final aeq<dna<?, ?>> c = om.a("ore_nether_gold");
   public static final aeq<dna<?, ?>> d = om.a("ore_quartz");
   public static final aeq<dna<?, ?>> e = om.a("ore_gravel_nether");
   public static final aeq<dna<?, ?>> f = om.a("ore_blackstone");
   public static final aeq<dna<?, ?>> g = om.a("ore_dirt");
   public static final aeq<dna<?, ?>> h = om.a("ore_gravel");
   public static final aeq<dna<?, ?>> i = om.a("ore_granite");
   public static final aeq<dna<?, ?>> j = om.a("ore_diorite");
   public static final aeq<dna<?, ?>> k = om.a("ore_andesite");
   public static final aeq<dna<?, ?>> l = om.a("ore_tuff");
   public static final aeq<dna<?, ?>> m = om.a("ore_coal");
   public static final aeq<dna<?, ?>> n = om.a("ore_coal_buried");
   public static final aeq<dna<?, ?>> o = om.a("ore_iron");
   public static final aeq<dna<?, ?>> p = om.a("ore_iron_small");
   public static final aeq<dna<?, ?>> q = om.a("ore_gold");
   public static final aeq<dna<?, ?>> r = om.a("ore_gold_buried");
   public static final aeq<dna<?, ?>> s = om.a("ore_redstone");
   public static final aeq<dna<?, ?>> t = om.a("ore_diamond_small");
   public static final aeq<dna<?, ?>> u = om.a("ore_diamond_medium");
   public static final aeq<dna<?, ?>> v = om.a("ore_diamond_large");
   public static final aeq<dna<?, ?>> w = om.a("ore_diamond_buried");
   public static final aeq<dna<?, ?>> x = om.a("ore_lapis");
   public static final aeq<dna<?, ?>> y = om.a("ore_lapis_buried");
   public static final aeq<dna<?, ?>> z = om.a("ore_infested");
   public static final aeq<dna<?, ?>> A = om.a("ore_emerald");
   public static final aeq<dna<?, ?>> B = om.a("ore_ancient_debris_large");
   public static final aeq<dna<?, ?>> C = om.a("ore_ancient_debris_small");
   public static final aeq<dna<?, ?>> D = om.a("ore_copper_small");
   public static final aeq<dna<?, ?>> E = om.a("ore_copper_large");
   public static final aeq<dna<?, ?>> F = om.a("ore_clay");

   public static void a(nm<dna<?, ?>> $$0) {
      dym $$1 = new dyu(apl.bd);
      dym $$2 = new dyu(apl.be);
      dym $$3 = new dyu(apl.bf);
      dym $$4 = new dxv(csn.dW);
      dym $$5 = new dyu(apl.bg);
      List<dpz.a> $$6 = List.of(dpz.a($$2, csn.P.n()), dpz.a($$3, csn.Q.n()));
      List<dpz.a> $$7 = List.of(dpz.a($$2, csn.N.n()), dpz.a($$3, csn.O.n()));
      List<dpz.a> $$8 = List.of(dpz.a($$2, csn.cx.n()), dpz.a($$3, csn.cy.n()));
      List<dpz.a> $$9 = List.of(dpz.a($$2, csn.aR.n()), dpz.a($$3, csn.aS.n()));
      List<dpz.a> $$10 = List.of(dpz.a($$2, csn.qN.n()), dpz.a($$3, csn.qO.n()));
      List<dpz.a> $$11 = List.of(dpz.a($$2, csn.R.n()), dpz.a($$3, csn.S.n()));
      om.a($$0, a, dnn.I, new dpz($$4, csn.kJ.n(), 33));
      om.a($$0, b, dnn.I, new dpz($$4, csn.dX.n(), 12));
      om.a($$0, c, dnn.I, new dpz($$4, csn.T.n(), 10));
      om.a($$0, d, dnn.I, new dpz($$4, csn.hb.n(), 14));
      om.a($$0, e, dnn.I, new dpz($$4, csn.L.n(), 33));
      om.a($$0, f, dnn.I, new dpz($$4, csn.pr.n(), 33));
      om.a($$0, g, dnn.I, new dpz($$1, csn.j.n(), 33));
      om.a($$0, h, dnn.I, new dpz($$1, csn.L.n(), 33));
      om.a($$0, i, dnn.I, new dpz($$1, csn.c.n(), 64));
      om.a($$0, j, dnn.I, new dpz($$1, csn.e.n(), 64));
      om.a($$0, k, dnn.I, new dpz($$1, csn.g.n(), 64));
      om.a($$0, l, dnn.I, new dpz($$1, csn.qz.n(), 64));
      om.a($$0, m, dnn.I, new dpz($$11, 17));
      om.a($$0, n, dnn.I, new dpz($$11, 17, 0.5F));
      om.a($$0, o, dnn.I, new dpz($$6, 9));
      om.a($$0, p, dnn.I, new dpz($$6, 4));
      om.a($$0, q, dnn.I, new dpz($$7, 9));
      om.a($$0, r, dnn.I, new dpz($$7, 9, 0.5F));
      om.a($$0, s, dnn.I, new dpz(List.of(dpz.a($$2, csn.dI.n()), dpz.a($$3, csn.dJ.n())), 8));
      om.a($$0, t, dnn.I, new dpz($$8, 4, 0.5F));
      om.a($$0, v, dnn.I, new dpz($$8, 12, 0.7F));
      om.a($$0, w, dnn.I, new dpz($$8, 8, 1.0F));
      om.a($$0, u, dnn.I, new dpz($$8, 8, 0.5F));
      om.a($$0, x, dnn.I, new dpz($$9, 7));
      om.a($$0, y, dnn.I, new dpz($$9, 7, 1.0F));
      om.a($$0, z, dnn.I, new dpz(List.of(dpz.a($$2, csn.eO.n()), dpz.a($$3, csn.sc.n())), 9));
      om.a($$0, A, dnn.I, new dpz(List.of(dpz.a($$2, csn.fE.n()), dpz.a($$3, csn.fF.n())), 3));
      om.a($$0, B, dnn.ae, new dpz($$5, csn.pj.n(), 3, 1.0F));
      om.a($$0, C, dnn.ae, new dpz($$5, csn.pj.n(), 2, 1.0F));
      om.a($$0, D, dnn.I, new dpz($$10, 10));
      om.a($$0, E, dnn.I, new dpz($$10, 20));
      om.a($$0, F, dnn.I, new dpz($$1, csn.dR.n(), 33));
   }
}
