import java.util.Optional;
import java.util.stream.IntStream;

public class os {
   public static final or a = a("cube", ou.c, ou.j, ou.k, ou.l, ou.m, ou.n, ou.o);
   public static final or b = a("cube_directional", ou.c, ou.j, ou.k, ou.l, ou.m, ou.n, ou.o);
   public static final or c = a("cube_all", ou.a);
   public static final or d = a("cube_all_inner_faces", ou.a);
   public static final or e = a("cube_mirrored_all", "_mirrored", ou.a);
   public static final or f = a("cube_north_west_mirrored_all", "_north_west_mirrored", ou.a);
   public static final or g = a("cube_column_uv_locked_x", "_x", ou.d, ou.i);
   public static final or h = a("cube_column_uv_locked_y", "_y", ou.d, ou.i);
   public static final or i = a("cube_column_uv_locked_z", "_z", ou.d, ou.i);
   public static final or j = a("cube_column", ou.d, ou.i);
   public static final or k = a("cube_column_horizontal", "_horizontal", ou.d, ou.i);
   public static final or l = a("cube_column_mirrored", "_mirrored", ou.d, ou.i);
   public static final or m = a("cube_top", ou.f, ou.i);
   public static final or n = a("cube_bottom_top", ou.f, ou.e, ou.i);
   public static final or o = a("cube_bottom_top_inner_faces", ou.f, ou.e, ou.i);
   public static final or p = a("orientable", ou.f, ou.g, ou.i);
   public static final or q = a("orientable_with_bottom", ou.f, ou.e, ou.i, ou.g);
   public static final or r = a("orientable_vertical", "_vertical", ou.g, ou.i);
   public static final or s = a("button", ou.b);
   public static final or t = a("button_pressed", "_pressed", ou.b);
   public static final or u = a("button_inventory", "_inventory", ou.b);
   public static final or v = a("door_bottom_left", "_bottom_left", ou.f, ou.e);
   public static final or w = a("door_bottom_left_open", "_bottom_left_open", ou.f, ou.e);
   public static final or x = a("door_bottom_right", "_bottom_right", ou.f, ou.e);
   public static final or y = a("door_bottom_right_open", "_bottom_right_open", ou.f, ou.e);
   public static final or z = a("door_top_left", "_top_left", ou.f, ou.e);
   public static final or A = a("door_top_left_open", "_top_left_open", ou.f, ou.e);
   public static final or B = a("door_top_right", "_top_right", ou.f, ou.e);
   public static final or C = a("door_top_right_open", "_top_right_open", ou.f, ou.e);
   public static final or D = a("custom_fence_post", "_post", ou.b, ou.c);
   public static final or E = a("custom_fence_side_north", "_side_north", ou.b);
   public static final or F = a("custom_fence_side_east", "_side_east", ou.b);
   public static final or G = a("custom_fence_side_south", "_side_south", ou.b);
   public static final or H = a("custom_fence_side_west", "_side_west", ou.b);
   public static final or I = a("custom_fence_inventory", "_inventory", ou.b);
   public static final or J = a("fence_post", "_post", ou.b);
   public static final or K = a("fence_side", "_side", ou.b);
   public static final or L = a("fence_inventory", "_inventory", ou.b);
   public static final or M = a("template_wall_post", "_post", ou.r);
   public static final or N = a("template_wall_side", "_side", ou.r);
   public static final or O = a("template_wall_side_tall", "_side_tall", ou.r);
   public static final or P = a("wall_inventory", "_inventory", ou.r);
   public static final or Q = a("template_custom_fence_gate", ou.b, ou.c);
   public static final or R = a("template_custom_fence_gate_open", "_open", ou.b, ou.c);
   public static final or S = a("template_custom_fence_gate_wall", "_wall", ou.b, ou.c);
   public static final or T = a("template_custom_fence_gate_wall_open", "_wall_open", ou.b, ou.c);
   public static final or U = a("template_fence_gate", ou.b);
   public static final or V = a("template_fence_gate_open", "_open", ou.b);
   public static final or W = a("template_fence_gate_wall", "_wall", ou.b);
   public static final or X = a("template_fence_gate_wall_open", "_wall_open", ou.b);
   public static final or Y = a("pressure_plate_up", ou.b);
   public static final or Z = a("pressure_plate_down", "_down", ou.b);
   public static final or aa = a(ou.c);
   public static final or ab = a("slab", ou.e, ou.f, ou.i);
   public static final or ac = a("slab_top", "_top", ou.e, ou.f, ou.i);
   public static final or ad = a("leaves", ou.a);
   public static final or ae = a("stairs", ou.e, ou.f, ou.i);
   public static final or af = a("inner_stairs", "_inner", ou.e, ou.f, ou.i);
   public static final or ag = a("outer_stairs", "_outer", ou.e, ou.f, ou.i);
   public static final or ah = a("template_trapdoor_top", "_top", ou.b);
   public static final or ai = a("template_trapdoor_bottom", "_bottom", ou.b);
   public static final or aj = a("template_trapdoor_open", "_open", ou.b);
   public static final or ak = a("template_orientable_trapdoor_top", "_top", ou.b);
   public static final or al = a("template_orientable_trapdoor_bottom", "_bottom", ou.b);
   public static final or am = a("template_orientable_trapdoor_open", "_open", ou.b);
   public static final or an = a("pointed_dripstone", ou.p);
   public static final or ao = a("cross", ou.p);
   public static final or ap = a("tinted_cross", ou.p);
   public static final or aq = a("flower_pot_cross", ou.q);
   public static final or ar = a("tinted_flower_pot_cross", ou.q);
   public static final or as = a("rail_flat", ou.s);
   public static final or at = a("rail_curved", "_corner", ou.s);
   public static final or au = a("template_rail_raised_ne", "_raised_ne", ou.s);
   public static final or av = a("template_rail_raised_sw", "_raised_sw", ou.s);
   public static final or aw = a("carpet", ou.t);
   public static final or ax = a("mossy_carpet_side", ou.i);
   public static final or ay = a("flowerbed_1", "_1", ou.P, ou.y);
   public static final or az = a("flowerbed_2", "_2", ou.P, ou.y);
   public static final or aA = a("flowerbed_3", "_3", ou.P, ou.y);
   public static final or aB = a("flowerbed_4", "_4", ou.P, ou.y);
   public static final or aC = a("coral_fan", ou.x);
   public static final or aD = a("coral_wall_fan", ou.x);
   public static final or aE = a("template_glazed_terracotta", ou.u);
   public static final or aF = a("template_chorus_flower", ou.b);
   public static final or aG = a("template_daylight_detector", ou.f, ou.i);
   public static final or aH = a("template_glass_pane_noside", "_noside", ou.v);
   public static final or aI = a("template_glass_pane_noside_alt", "_noside_alt", ou.v);
   public static final or aJ = a("template_glass_pane_post", "_post", ou.v, ou.w);
   public static final or aK = a("template_glass_pane_side", "_side", ou.v, ou.w);
   public static final or aL = a("template_glass_pane_side_alt", "_side_alt", ou.v, ou.w);
   public static final or aM = a("template_command_block", ou.g, ou.h, ou.i);
   public static final or aN = a("template_chiseled_bookshelf_slot_top_left", "_slot_top_left", ou.b);
   public static final or aO = a("template_chiseled_bookshelf_slot_top_mid", "_slot_top_mid", ou.b);
   public static final or aP = a("template_chiseled_bookshelf_slot_top_right", "_slot_top_right", ou.b);
   public static final or aQ = a("template_chiseled_bookshelf_slot_bottom_left", "_slot_bottom_left", ou.b);
   public static final or aR = a("template_chiseled_bookshelf_slot_bottom_mid", "_slot_bottom_mid", ou.b);
   public static final or aS = a("template_chiseled_bookshelf_slot_bottom_right", "_slot_bottom_right", ou.b);
   public static final or aT = a("template_anvil", ou.f);
   public static final or[] aU = IntStream.range(0, 8).mapToObj($$0 -> a("stem_growth" + $$0, "_stage" + $$0, ou.y)).toArray(or[]::new);
   public static final or aV = a("stem_fruit", ou.y, ou.z);
   public static final or aW = a("crop", ou.A);
   public static final or aX = a("template_farmland", ou.B, ou.f);
   public static final or aY = a("template_fire_floor", ou.C);
   public static final or aZ = a("template_fire_side", ou.C);
   public static final or ba = a("template_fire_side_alt", ou.C);
   public static final or bb = a("template_fire_up", ou.C);
   public static final or bc = a("template_fire_up_alt", ou.C);
   public static final or bd = a("template_campfire", ou.C, ou.K);
   public static final or be = a("template_lantern", ou.D);
   public static final or bf = a("template_hanging_lantern", "_hanging", ou.D);
   public static final or bg = a("template_torch", ou.G);
   public static final or bh = a("template_torch_unlit", ou.G);
   public static final or bi = a("template_torch_wall", ou.G);
   public static final or bj = a("template_torch_wall_unlit", ou.G);
   public static final or bk = a("template_redstone_torch", ou.G);
   public static final or bl = a("template_redstone_torch_wall", ou.G);
   public static final or bm = a("template_piston", ou.E, ou.e, ou.i);
   public static final or bn = a("template_piston_head", ou.E, ou.i, ou.F);
   public static final or bo = a("template_piston_head_short", ou.E, ou.i, ou.F);
   public static final or bp = a("template_seagrass", ou.b);
   public static final or bq = a("template_turtle_egg", ou.a);
   public static final or br = a("template_two_turtle_eggs", ou.a);
   public static final or bs = a("template_three_turtle_eggs", ou.a);
   public static final or bt = a("template_four_turtle_eggs", ou.a);
   public static final or bu = a("template_single_face", ou.b);
   public static final or bv = a("template_cauldron_level1", ou.N, ou.M, ou.c, ou.f, ou.e, ou.i);
   public static final or bw = a("template_cauldron_level2", ou.N, ou.M, ou.c, ou.f, ou.e, ou.i);
   public static final or bx = a("template_cauldron_full", ou.N, ou.M, ou.c, ou.f, ou.e, ou.i);
   public static final or by = a("template_azalea", ou.f, ou.i);
   public static final or bz = a("template_potted_azalea_bush", ou.q, ou.f, ou.i);
   public static final or bA = a("template_potted_azalea_bush", ou.q, ou.f, ou.i);
   public static final or bB = a("sniffer_egg", ou.f, ou.e, ou.j, ou.k, ou.l, ou.m);
   public static final or bC = b("generated", ou.H);
   public static final or bD = b("template_music_disc", ou.H);
   public static final or bE = b("handheld", ou.H);
   public static final or bF = b("handheld_rod", ou.H);
   public static final or bG = b("generated", ou.H, ou.I);
   public static final or bH = b("generated", ou.H, ou.I, ou.J);
   public static final or bI = b("template_shulker_box", ou.c);
   public static final or bJ = b("template_bed", ou.c);
   public static final or bK = b("template_banner");
   public static final or bL = b("template_skull");
   public static final or bM = a("template_candle", ou.a, ou.c);
   public static final or bN = a("template_two_candles", ou.a, ou.c);
   public static final or bO = a("template_three_candles", ou.a, ou.c);
   public static final or bP = a("template_four_candles", ou.a, ou.c);
   public static final or bQ = a("template_cake_with_candle", ou.L, ou.e, ou.i, ou.f, ou.c);
   public static final or bR = a("template_sculk_shrieker", ou.e, ou.i, ou.f, ou.c, ou.O);
   public static final or bS = a("template_vault", ou.f, ou.e, ou.i, ou.g);
   public static final or bT = b("handheld_mace", ou.H);

   private static or a(ou... $$0) {
      return new or(Optional.empty(), Optional.empty(), $$0);
   }

   private static or a(String $$0, ou... $$1) {
      return new or(Optional.of(alz.b("block/" + $$0)), Optional.empty(), $$1);
   }

   private static or b(String $$0, ou... $$1) {
      return new or(Optional.of(alz.b("item/" + $$0)), Optional.empty(), $$1);
   }

   private static or a(String $$0, String $$1, ou... $$2) {
      return new or(Optional.of(alz.b("block/" + $$0)), Optional.of($$1), $$2);
   }
}
