import java.util.List;

public class ou {
   public static final aey<dnd<?, ?>> a = or.a("ore_magma");
   public static final aey<dnd<?, ?>> b = or.a("ore_soul_sand");
   public static final aey<dnd<?, ?>> c = or.a("ore_nether_gold");
   public static final aey<dnd<?, ?>> d = or.a("ore_quartz");
   public static final aey<dnd<?, ?>> e = or.a("ore_gravel_nether");
   public static final aey<dnd<?, ?>> f = or.a("ore_blackstone");
   public static final aey<dnd<?, ?>> g = or.a("ore_dirt");
   public static final aey<dnd<?, ?>> h = or.a("ore_gravel");
   public static final aey<dnd<?, ?>> i = or.a("ore_granite");
   public static final aey<dnd<?, ?>> j = or.a("ore_diorite");
   public static final aey<dnd<?, ?>> k = or.a("ore_andesite");
   public static final aey<dnd<?, ?>> l = or.a("ore_tuff");
   public static final aey<dnd<?, ?>> m = or.a("ore_coal");
   public static final aey<dnd<?, ?>> n = or.a("ore_coal_buried");
   public static final aey<dnd<?, ?>> o = or.a("ore_iron");
   public static final aey<dnd<?, ?>> p = or.a("ore_iron_small");
   public static final aey<dnd<?, ?>> q = or.a("ore_gold");
   public static final aey<dnd<?, ?>> r = or.a("ore_gold_buried");
   public static final aey<dnd<?, ?>> s = or.a("ore_redstone");
   public static final aey<dnd<?, ?>> t = or.a("ore_diamond_small");
   public static final aey<dnd<?, ?>> u = or.a("ore_diamond_medium");
   public static final aey<dnd<?, ?>> v = or.a("ore_diamond_large");
   public static final aey<dnd<?, ?>> w = or.a("ore_diamond_buried");
   public static final aey<dnd<?, ?>> x = or.a("ore_lapis");
   public static final aey<dnd<?, ?>> y = or.a("ore_lapis_buried");
   public static final aey<dnd<?, ?>> z = or.a("ore_infested");
   public static final aey<dnd<?, ?>> A = or.a("ore_emerald");
   public static final aey<dnd<?, ?>> B = or.a("ore_ancient_debris_large");
   public static final aey<dnd<?, ?>> C = or.a("ore_ancient_debris_small");
   public static final aey<dnd<?, ?>> D = or.a("ore_copper_small");
   public static final aey<dnd<?, ?>> E = or.a("ore_copper_large");
   public static final aey<dnd<?, ?>> F = or.a("ore_clay");

   public static void a(nr<dnd<?, ?>> $$0) {
      dyp $$1 = new dyx(apv.bd);
      dyp $$2 = new dyx(apv.be);
      dyp $$3 = new dyx(apv.bf);
      dyp $$4 = new dxy(cte.dV);
      dyp $$5 = new dyx(apv.bg);
      List<dqc.a> $$6 = List.of(dqc.a($$2, cte.P.o()), dqc.a($$3, cte.Q.o()));
      List<dqc.a> $$7 = List.of(dqc.a($$2, cte.N.o()), dqc.a($$3, cte.O.o()));
      List<dqc.a> $$8 = List.of(dqc.a($$2, cte.cx.o()), dqc.a($$3, cte.cy.o()));
      List<dqc.a> $$9 = List.of(dqc.a($$2, cte.aR.o()), dqc.a($$3, cte.aS.o()));
      List<dqc.a> $$10 = List.of(dqc.a($$2, cte.qN.o()), dqc.a($$3, cte.qO.o()));
      List<dqc.a> $$11 = List.of(dqc.a($$2, cte.R.o()), dqc.a($$3, cte.S.o()));
      or.a($$0, a, dnq.I, new dqc($$4, cte.kJ.o(), 33));
      or.a($$0, b, dnq.I, new dqc($$4, cte.dW.o(), 12));
      or.a($$0, c, dnq.I, new dqc($$4, cte.T.o(), 10));
      or.a($$0, d, dnq.I, new dqc($$4, cte.hb.o(), 14));
      or.a($$0, e, dnq.I, new dqc($$4, cte.L.o(), 33));
      or.a($$0, f, dnq.I, new dqc($$4, cte.pr.o(), 33));
      or.a($$0, g, dnq.I, new dqc($$1, cte.j.o(), 33));
      or.a($$0, h, dnq.I, new dqc($$1, cte.L.o(), 33));
      or.a($$0, i, dnq.I, new dqc($$1, cte.c.o(), 64));
      or.a($$0, j, dnq.I, new dqc($$1, cte.e.o(), 64));
      or.a($$0, k, dnq.I, new dqc($$1, cte.g.o(), 64));
      or.a($$0, l, dnq.I, new dqc($$1, cte.qz.o(), 64));
      or.a($$0, m, dnq.I, new dqc($$11, 17));
      or.a($$0, n, dnq.I, new dqc($$11, 17, 0.5F));
      or.a($$0, o, dnq.I, new dqc($$6, 9));
      or.a($$0, p, dnq.I, new dqc($$6, 4));
      or.a($$0, q, dnq.I, new dqc($$7, 9));
      or.a($$0, r, dnq.I, new dqc($$7, 9, 0.5F));
      or.a($$0, s, dnq.I, new dqc(List.of(dqc.a($$2, cte.dI.o()), dqc.a($$3, cte.dJ.o())), 8));
      or.a($$0, t, dnq.I, new dqc($$8, 4, 0.5F));
      or.a($$0, v, dnq.I, new dqc($$8, 12, 0.7F));
      or.a($$0, w, dnq.I, new dqc($$8, 8, 1.0F));
      or.a($$0, u, dnq.I, new dqc($$8, 8, 0.5F));
      or.a($$0, x, dnq.I, new dqc($$9, 7));
      or.a($$0, y, dnq.I, new dqc($$9, 7, 1.0F));
      or.a($$0, z, dnq.I, new dqc(List.of(dqc.a($$2, cte.eN.o()), dqc.a($$3, cte.sc.o())), 9));
      or.a($$0, A, dnq.I, new dqc(List.of(dqc.a($$2, cte.fE.o()), dqc.a($$3, cte.fF.o())), 3));
      or.a($$0, B, dnq.ae, new dqc($$5, cte.pj.o(), 3, 1.0F));
      or.a($$0, C, dnq.ae, new dqc($$5, cte.pj.o(), 2, 1.0F));
      or.a($$0, D, dnq.I, new dqc($$10, 10));
      or.a($$0, E, dnq.I, new dqc($$10, 20));
      or.a($$0, F, dnq.I, new dqc($$1, cte.dR.o(), 33));
   }
}
