import java.util.List;

public class ow {
   public static final aex<dnl<?, ?>> a = ot.a("ore_magma");
   public static final aex<dnl<?, ?>> b = ot.a("ore_soul_sand");
   public static final aex<dnl<?, ?>> c = ot.a("ore_nether_gold");
   public static final aex<dnl<?, ?>> d = ot.a("ore_quartz");
   public static final aex<dnl<?, ?>> e = ot.a("ore_gravel_nether");
   public static final aex<dnl<?, ?>> f = ot.a("ore_blackstone");
   public static final aex<dnl<?, ?>> g = ot.a("ore_dirt");
   public static final aex<dnl<?, ?>> h = ot.a("ore_gravel");
   public static final aex<dnl<?, ?>> i = ot.a("ore_granite");
   public static final aex<dnl<?, ?>> j = ot.a("ore_diorite");
   public static final aex<dnl<?, ?>> k = ot.a("ore_andesite");
   public static final aex<dnl<?, ?>> l = ot.a("ore_tuff");
   public static final aex<dnl<?, ?>> m = ot.a("ore_coal");
   public static final aex<dnl<?, ?>> n = ot.a("ore_coal_buried");
   public static final aex<dnl<?, ?>> o = ot.a("ore_iron");
   public static final aex<dnl<?, ?>> p = ot.a("ore_iron_small");
   public static final aex<dnl<?, ?>> q = ot.a("ore_gold");
   public static final aex<dnl<?, ?>> r = ot.a("ore_gold_buried");
   public static final aex<dnl<?, ?>> s = ot.a("ore_redstone");
   public static final aex<dnl<?, ?>> t = ot.a("ore_diamond_small");
   public static final aex<dnl<?, ?>> u = ot.a("ore_diamond_medium");
   public static final aex<dnl<?, ?>> v = ot.a("ore_diamond_large");
   public static final aex<dnl<?, ?>> w = ot.a("ore_diamond_buried");
   public static final aex<dnl<?, ?>> x = ot.a("ore_lapis");
   public static final aex<dnl<?, ?>> y = ot.a("ore_lapis_buried");
   public static final aex<dnl<?, ?>> z = ot.a("ore_infested");
   public static final aex<dnl<?, ?>> A = ot.a("ore_emerald");
   public static final aex<dnl<?, ?>> B = ot.a("ore_ancient_debris_large");
   public static final aex<dnl<?, ?>> C = ot.a("ore_ancient_debris_small");
   public static final aex<dnl<?, ?>> D = ot.a("ore_copper_small");
   public static final aex<dnl<?, ?>> E = ot.a("ore_copper_large");
   public static final aex<dnl<?, ?>> F = ot.a("ore_clay");

   public static void a(nt<dnl<?, ?>> $$0) {
      dyx $$1 = new dzf(apu.bd);
      dyx $$2 = new dzf(apu.be);
      dyx $$3 = new dzf(apu.bf);
      dyx $$4 = new dyg(csy.dW);
      dyx $$5 = new dzf(apu.bg);
      List<dqk.a> $$6 = List.of(dqk.a($$2, csy.P.n()), dqk.a($$3, csy.Q.n()));
      List<dqk.a> $$7 = List.of(dqk.a($$2, csy.N.n()), dqk.a($$3, csy.O.n()));
      List<dqk.a> $$8 = List.of(dqk.a($$2, csy.cx.n()), dqk.a($$3, csy.cy.n()));
      List<dqk.a> $$9 = List.of(dqk.a($$2, csy.aR.n()), dqk.a($$3, csy.aS.n()));
      List<dqk.a> $$10 = List.of(dqk.a($$2, csy.qN.n()), dqk.a($$3, csy.qO.n()));
      List<dqk.a> $$11 = List.of(dqk.a($$2, csy.R.n()), dqk.a($$3, csy.S.n()));
      ot.a($$0, a, dny.I, new dqk($$4, csy.kJ.n(), 33));
      ot.a($$0, b, dny.I, new dqk($$4, csy.dX.n(), 12));
      ot.a($$0, c, dny.I, new dqk($$4, csy.T.n(), 10));
      ot.a($$0, d, dny.I, new dqk($$4, csy.hb.n(), 14));
      ot.a($$0, e, dny.I, new dqk($$4, csy.L.n(), 33));
      ot.a($$0, f, dny.I, new dqk($$4, csy.pr.n(), 33));
      ot.a($$0, g, dny.I, new dqk($$1, csy.j.n(), 33));
      ot.a($$0, h, dny.I, new dqk($$1, csy.L.n(), 33));
      ot.a($$0, i, dny.I, new dqk($$1, csy.c.n(), 64));
      ot.a($$0, j, dny.I, new dqk($$1, csy.e.n(), 64));
      ot.a($$0, k, dny.I, new dqk($$1, csy.g.n(), 64));
      ot.a($$0, l, dny.I, new dqk($$1, csy.qz.n(), 64));
      ot.a($$0, m, dny.I, new dqk($$11, 17));
      ot.a($$0, n, dny.I, new dqk($$11, 17, 0.5F));
      ot.a($$0, o, dny.I, new dqk($$6, 9));
      ot.a($$0, p, dny.I, new dqk($$6, 4));
      ot.a($$0, q, dny.I, new dqk($$7, 9));
      ot.a($$0, r, dny.I, new dqk($$7, 9, 0.5F));
      ot.a($$0, s, dny.I, new dqk(List.of(dqk.a($$2, csy.dI.n()), dqk.a($$3, csy.dJ.n())), 8));
      ot.a($$0, t, dny.I, new dqk($$8, 4, 0.5F));
      ot.a($$0, v, dny.I, new dqk($$8, 12, 0.7F));
      ot.a($$0, w, dny.I, new dqk($$8, 8, 1.0F));
      ot.a($$0, u, dny.I, new dqk($$8, 8, 0.5F));
      ot.a($$0, x, dny.I, new dqk($$9, 7));
      ot.a($$0, y, dny.I, new dqk($$9, 7, 1.0F));
      ot.a($$0, z, dny.I, new dqk(List.of(dqk.a($$2, csy.eO.n()), dqk.a($$3, csy.sc.n())), 9));
      ot.a($$0, A, dny.I, new dqk(List.of(dqk.a($$2, csy.fE.n()), dqk.a($$3, csy.fF.n())), 3));
      ot.a($$0, B, dny.ae, new dqk($$5, csy.pj.n(), 3, 1.0F));
      ot.a($$0, C, dny.ae, new dqk($$5, csy.pj.n(), 2, 1.0F));
      ot.a($$0, D, dny.I, new dqk($$10, 10));
      ot.a($$0, E, dny.I, new dqk($$10, 20));
      ot.a($$0, F, dny.I, new dqk($$1, csy.dR.n(), 33));
   }
}
