public class ox {
   public static final aeo<dub> a = pc.a("monster_room");
   public static final aeo<dub> b = pc.a("monster_room_deep");
   public static final aeo<dub> c = pc.a("fossil_upper");
   public static final aeo<dub> d = pc.a("fossil_lower");
   public static final aeo<dub> e = pc.a("dripstone_cluster");
   public static final aeo<dub> f = pc.a("large_dripstone");
   public static final aeo<dub> g = pc.a("pointed_dripstone");
   public static final aeo<dub> h = pc.a("underwater_magma");
   public static final aeo<dub> i = pc.a("glow_lichen");
   public static final aeo<dub> j = pc.a("rooted_azalea_tree");
   public static final aeo<dub> k = pc.a("cave_vines");
   public static final aeo<dub> l = pc.a("lush_caves_vegetation");
   public static final aeo<dub> m = pc.a("lush_caves_clay");
   public static final aeo<dub> n = pc.a("lush_caves_ceiling_vegetation");
   public static final aeo<dub> o = pc.a("spore_blossom");
   public static final aeo<dub> p = pc.a("classic_vines_cave_feature");
   public static final aeo<dub> q = pc.a("amethyst_geode");
   public static final aeo<dub> r = pc.a("sculk_patch_deep_dark");
   public static final aeo<dub> s = pc.a("sculk_patch_ancient_city");
   public static final aeo<dub> t = pc.a("sculk_vein");

   public static void a(nn<dub> $$0) {
      hg<dmy<?, ?>> $$1 = $$0.a(jd.as);
      hf<dmy<?, ?>> $$2 = $$1.b(ol.a);
      hf<dmy<?, ?>> $$3 = $$1.b(ol.b);
      hf<dmy<?, ?>> $$4 = $$1.b(ol.c);
      hf<dmy<?, ?>> $$5 = $$1.b(ol.d);
      hf<dmy<?, ?>> $$6 = $$1.b(ol.e);
      hf<dmy<?, ?>> $$7 = $$1.b(ol.f);
      hf<dmy<?, ?>> $$8 = $$1.b(ol.g);
      hf<dmy<?, ?>> $$9 = $$1.b(ol.h);
      hf<dmy<?, ?>> $$10 = $$1.b(ol.i);
      hf<dmy<?, ?>> $$11 = $$1.b(ol.j);
      hf<dmy<?, ?>> $$12 = $$1.b(ol.m);
      hf<dmy<?, ?>> $$13 = $$1.b(ol.r);
      hf<dmy<?, ?>> $$14 = $$1.b(ol.s);
      hf<dmy<?, ?>> $$15 = $$1.b(ol.t);
      hf<dmy<?, ?>> $$16 = $$1.b(ot.c);
      hf<dmy<?, ?>> $$17 = $$1.b(ol.u);
      hf<dmy<?, ?>> $$18 = $$1.b(ol.v);
      hf<dmy<?, ?>> $$19 = $$1.b(ol.w);
      hf<dmy<?, ?>> $$20 = $$1.b(ol.x);
      pc.a($$0, a, $$2, dtu.a(10), dty.a(), dtw.a(dlb.a(0), dlb.b()), dtp.a());
      pc.a($$0, b, $$2, dtu.a(4), dty.a(), dtw.a(dlb.b(6), dlb.a(-1)), dtp.a());
      pc.a($$0, c, $$3, duh.a(64), dty.a(), dtw.a(dlb.a(0), dlb.b()), dtp.a());
      pc.a($$0, d, $$4, duh.a(64), dty.a(), dtw.a(dlb.a(), dlb.a(-8)), dtp.a());
      pc.a($$0, e, $$5, dtu.a(bfz.a(48, 96)), dty.a(), pc.i, dtp.a());
      pc.a($$0, f, $$6, dtu.a(bfz.a(10, 48)), dty.a(), pc.i, dtp.a());
      pc.a($$0, g, $$7, dtu.a(bfz.a(192, 256)), dty.a(), pc.i, dtu.a(bfz.a(1, 5)), dug.a(bfo.a(0.0F, 3.0F, -10, 10), bfo.a(0.0F, 0.6F, -2, 2)), dtp.a());
      pc.a($$0, h, $$8, dtu.a(bfz.a(44, 52)), dty.a(), pc.i, duj.a(dkh.a.c, Integer.MIN_VALUE, -2), dtp.a());
      pc.a($$0, i, $$9, dtu.a(bfz.a(104, 157)), pc.i, dty.a(), duj.a(dkh.a.c, Integer.MIN_VALUE, -13), dtp.a());
      pc.a($$0, j, $$10, dtu.a(bfz.a(1, 2)), dty.a(), pc.i, dtv.a(hb.b, dlo.c(), dlo.c, 12), dug.a(bfq.a(-1)), dtp.a());
      pc.a($$0, k, $$11, dtu.a(188), dty.a(), pc.i, dtv.a(hb.b, dlo.a(hb.a), dlo.c, 12), dug.a(bfq.a(-1)), dtp.a());
      pc.a($$0, l, $$12, dtu.a(125), dty.a(), pc.i, dtv.a(hb.a, dlo.c(), dlo.c, 12), dug.a(bfq.a(1)), dtp.a());
      pc.a($$0, m, $$13, dtu.a(62), dty.a(), pc.i, dtv.a(hb.a, dlo.c(), dlo.c, 12), dug.a(bfq.a(1)), dtp.a());
      pc.a($$0, n, $$14, dtu.a(125), dty.a(), pc.i, dtv.a(hb.b, dlo.c(), dlo.c, 12), dug.a(bfq.a(-1)), dtp.a());
      pc.a($$0, o, $$15, dtu.a(25), dty.a(), pc.i, dtv.a(hb.b, dlo.c(), dlo.c, 12), dug.a(bfq.a(-1)), dtp.a());
      pc.a($$0, p, $$16, dtu.a(256), dty.a(), pc.i, dtp.a());
      pc.a($$0, q, $$17, duh.a(24), dty.a(), dtw.a(dlb.b(6), dlb.a(30)), dtp.a());
      pc.a($$0, r, $$18, dtu.a(bfq.a(256)), dty.a(), pc.i, dtp.a());
      pc.a($$0, s, $$19);
      pc.a($$0, t, $$20, dtu.a(bfz.a(204, 250)), dty.a(), pc.i, dtp.a());
   }
}
