import java.util.List;

public class pc {
   public static final aeq<duc> a = pb.a("crimson_fungi");
   public static final aeq<duc> b = pb.a("warped_fungi");
   public static final aeq<duc> c = pb.a("oak_checked");
   public static final aeq<duc> d = pb.a("dark_oak_checked");
   public static final aeq<duc> e = pb.a("birch_checked");
   public static final aeq<duc> f = pb.a("acacia_checked");
   public static final aeq<duc> g = pb.a("spruce_checked");
   public static final aeq<duc> h = pb.a("mangrove_checked");
   public static final aeq<duc> i = pb.a("cherry_checked");
   public static final aeq<duc> j = pb.a("pine_on_snow");
   public static final aeq<duc> k = pb.a("spruce_on_snow");
   public static final aeq<duc> l = pb.a("pine_checked");
   public static final aeq<duc> m = pb.a("jungle_tree");
   public static final aeq<duc> n = pb.a("fancy_oak_checked");
   public static final aeq<duc> o = pb.a("mega_jungle_tree_checked");
   public static final aeq<duc> p = pb.a("mega_spruce_checked");
   public static final aeq<duc> q = pb.a("mega_pine_checked");
   public static final aeq<duc> r = pb.a("tall_mangrove_checked");
   public static final aeq<duc> s = pb.a("jungle_bush");
   public static final aeq<duc> t = pb.a("super_birch_bees_0002");
   public static final aeq<duc> u = pb.a("super_birch_bees");
   public static final aeq<duc> v = pb.a("oak_bees_0002");
   public static final aeq<duc> w = pb.a("oak_bees_002");
   public static final aeq<duc> x = pb.a("birch_bees_0002");
   public static final aeq<duc> y = pb.a("birch_bees_002");
   public static final aeq<duc> z = pb.a("fancy_oak_bees_0002");
   public static final aeq<duc> A = pb.a("fancy_oak_bees_002");
   public static final aeq<duc> B = pb.a("fancy_oak_bees");
   public static final aeq<duc> C = pb.a("cherry_bees_005");

   public static void a(nm<duc> $$0) {
      hf<dmz<?, ?>> $$1 = $$0.a(jc.as);
      he<dmz<?, ?>> $$2 = $$1.b(or.a);
      he<dmz<?, ?>> $$3 = $$1.b(or.c);
      he<dmz<?, ?>> $$4 = $$1.b(or.g);
      he<dmz<?, ?>> $$5 = $$1.b(or.h);
      he<dmz<?, ?>> $$6 = $$1.b(or.i);
      he<dmz<?, ?>> $$7 = $$1.b(or.j);
      he<dmz<?, ?>> $$8 = $$1.b(or.k);
      he<dmz<?, ?>> $$9 = $$1.b(or.x);
      he<dmz<?, ?>> $$10 = $$1.b(or.z);
      he<dmz<?, ?>> $$11 = $$1.b(or.l);
      he<dmz<?, ?>> $$12 = $$1.b(or.m);
      he<dmz<?, ?>> $$13 = $$1.b(or.n);
      he<dmz<?, ?>> $$14 = $$1.b(or.p);
      he<dmz<?, ?>> $$15 = $$1.b(or.q);
      he<dmz<?, ?>> $$16 = $$1.b(or.r);
      he<dmz<?, ?>> $$17 = $$1.b(or.y);
      he<dmz<?, ?>> $$18 = $$1.b(or.v);
      he<dmz<?, ?>> $$19 = $$1.b(or.s);
      he<dmz<?, ?>> $$20 = $$1.b(or.t);
      he<dmz<?, ?>> $$21 = $$1.b(or.A);
      he<dmz<?, ?>> $$22 = $$1.b(or.B);
      he<dmz<?, ?>> $$23 = $$1.b(or.D);
      he<dmz<?, ?>> $$24 = $$1.b(or.E);
      he<dmz<?, ?>> $$25 = $$1.b(or.G);
      he<dmz<?, ?>> $$26 = $$1.b(or.H);
      he<dmz<?, ?>> $$27 = $$1.b(or.J);
      he<dmz<?, ?>> $$28 = $$1.b(or.K);
      pb.a($$0, a, $$2, dtu.a(8), dtq.a());
      pb.a($$0, b, $$3, dtu.a(8), dtq.a());
      pb.a($$0, c, $$4, pb.a(csm.x));
      pb.a($$0, d, $$5, pb.a(csm.D));
      pb.a($$0, e, $$6, pb.a(csm.z));
      pb.a($$0, f, $$7, pb.a(csm.B));
      pb.a($$0, g, $$8, pb.a(csm.y));
      pb.a($$0, h, $$9, pb.a(csm.E));
      pb.a($$0, i, $$10, pb.a(csm.C));
      dlp $$29 = dlp.a(ha.a.q(), csm.dP, csm.qC);
      List<duf> $$30 = List.of(dtw.a(ha.b, dlp.a(dlp.a(csm.qC)), 8), dtr.a($$29));
      pb.a($$0, j, $$11, $$30);
      pb.a($$0, k, $$8, $$30);
      pb.a($$0, l, $$11, pb.a(csm.y));
      pb.a($$0, m, $$12, pb.a(csm.A));
      pb.a($$0, n, $$13, pb.a(csm.x));
      pb.a($$0, o, $$14, pb.a(csm.A));
      pb.a($$0, p, $$15, pb.a(csm.y));
      pb.a($$0, q, $$16, pb.a(csm.y));
      pb.a($$0, r, $$17, pb.a(csm.E));
      pb.a($$0, s, $$18, pb.a(csm.x));
      pb.a($$0, t, $$19, pb.a(csm.z));
      pb.a($$0, u, $$20, pb.a(csm.z));
      pb.a($$0, v, $$21, pb.a(csm.x));
      pb.a($$0, w, $$22, pb.a(csm.x));
      pb.a($$0, x, $$23, pb.a(csm.z));
      pb.a($$0, y, $$24, pb.a(csm.z));
      pb.a($$0, z, $$25, pb.a(csm.x));
      pb.a($$0, A, $$26, pb.a(csm.x));
      pb.a($$0, B, $$27, pb.a(csm.x));
      pb.a($$0, C, $$28, pb.a(csm.C));
   }
}
