public class pd {
   public static final aew<dum> a = pi.a("monster_room");
   public static final aew<dum> b = pi.a("monster_room_deep");
   public static final aew<dum> c = pi.a("fossil_upper");
   public static final aew<dum> d = pi.a("fossil_lower");
   public static final aew<dum> e = pi.a("dripstone_cluster");
   public static final aew<dum> f = pi.a("large_dripstone");
   public static final aew<dum> g = pi.a("pointed_dripstone");
   public static final aew<dum> h = pi.a("underwater_magma");
   public static final aew<dum> i = pi.a("glow_lichen");
   public static final aew<dum> j = pi.a("rooted_azalea_tree");
   public static final aew<dum> k = pi.a("cave_vines");
   public static final aew<dum> l = pi.a("lush_caves_vegetation");
   public static final aew<dum> m = pi.a("lush_caves_clay");
   public static final aew<dum> n = pi.a("lush_caves_ceiling_vegetation");
   public static final aew<dum> o = pi.a("spore_blossom");
   public static final aew<dum> p = pi.a("classic_vines_cave_feature");
   public static final aew<dum> q = pi.a("amethyst_geode");
   public static final aew<dum> r = pi.a("sculk_patch_deep_dark");
   public static final aew<dum> s = pi.a("sculk_patch_ancient_city");
   public static final aew<dum> t = pi.a("sculk_vein");

   public static void a(nt<dum> $$0) {
      hh<dnj<?, ?>> $$1 = $$0.a(je.as);
      hg<dnj<?, ?>> $$2 = $$1.b(or.a);
      hg<dnj<?, ?>> $$3 = $$1.b(or.b);
      hg<dnj<?, ?>> $$4 = $$1.b(or.c);
      hg<dnj<?, ?>> $$5 = $$1.b(or.d);
      hg<dnj<?, ?>> $$6 = $$1.b(or.e);
      hg<dnj<?, ?>> $$7 = $$1.b(or.f);
      hg<dnj<?, ?>> $$8 = $$1.b(or.g);
      hg<dnj<?, ?>> $$9 = $$1.b(or.h);
      hg<dnj<?, ?>> $$10 = $$1.b(or.i);
      hg<dnj<?, ?>> $$11 = $$1.b(or.j);
      hg<dnj<?, ?>> $$12 = $$1.b(or.m);
      hg<dnj<?, ?>> $$13 = $$1.b(or.r);
      hg<dnj<?, ?>> $$14 = $$1.b(or.s);
      hg<dnj<?, ?>> $$15 = $$1.b(or.t);
      hg<dnj<?, ?>> $$16 = $$1.b(oz.c);
      hg<dnj<?, ?>> $$17 = $$1.b(or.u);
      hg<dnj<?, ?>> $$18 = $$1.b(or.v);
      hg<dnj<?, ?>> $$19 = $$1.b(or.w);
      hg<dnj<?, ?>> $$20 = $$1.b(or.x);
      pi.a($$0, a, $$2, duf.a(10), duj.a(), duh.a(dlm.a(0), dlm.b()), dua.a());
      pi.a($$0, b, $$2, duf.a(4), duj.a(), duh.a(dlm.b(6), dlm.a(-1)), dua.a());
      pi.a($$0, c, $$3, dus.a(64), duj.a(), duh.a(dlm.a(0), dlm.b()), dua.a());
      pi.a($$0, d, $$4, dus.a(64), duj.a(), duh.a(dlm.a(), dlm.a(-8)), dua.a());
      pi.a($$0, e, $$5, duf.a(bgj.a(48, 96)), duj.a(), pi.i, dua.a());
      pi.a($$0, f, $$6, duf.a(bgj.a(10, 48)), duj.a(), pi.i, dua.a());
      pi.a($$0, g, $$7, duf.a(bgj.a(192, 256)), duj.a(), pi.i, duf.a(bgj.a(1, 5)), dur.a(bfy.a(0.0F, 3.0F, -10, 10), bfy.a(0.0F, 0.6F, -2, 2)), dua.a());
      pi.a($$0, h, $$8, duf.a(bgj.a(44, 52)), duj.a(), pi.i, duu.a(dks.a.c, Integer.MIN_VALUE, -2), dua.a());
      pi.a($$0, i, $$9, duf.a(bgj.a(104, 157)), pi.i, duj.a(), duu.a(dks.a.c, Integer.MIN_VALUE, -13), dua.a());
      pi.a($$0, j, $$10, duf.a(bgj.a(1, 2)), duj.a(), pi.i, dug.a(hc.b, dlz.c(), dlz.c, 12), dur.a(bga.a(-1)), dua.a());
      pi.a($$0, k, $$11, duf.a(188), duj.a(), pi.i, dug.a(hc.b, dlz.a(hc.a), dlz.c, 12), dur.a(bga.a(-1)), dua.a());
      pi.a($$0, l, $$12, duf.a(125), duj.a(), pi.i, dug.a(hc.a, dlz.c(), dlz.c, 12), dur.a(bga.a(1)), dua.a());
      pi.a($$0, m, $$13, duf.a(62), duj.a(), pi.i, dug.a(hc.a, dlz.c(), dlz.c, 12), dur.a(bga.a(1)), dua.a());
      pi.a($$0, n, $$14, duf.a(125), duj.a(), pi.i, dug.a(hc.b, dlz.c(), dlz.c, 12), dur.a(bga.a(-1)), dua.a());
      pi.a($$0, o, $$15, duf.a(25), duj.a(), pi.i, dug.a(hc.b, dlz.c(), dlz.c, 12), dur.a(bga.a(-1)), dua.a());
      pi.a($$0, p, $$16, duf.a(256), duj.a(), pi.i, dua.a());
      pi.a($$0, q, $$17, dus.a(24), duj.a(), duh.a(dlm.b(6), dlm.a(30)), dua.a());
      pi.a($$0, r, $$18, duf.a(bga.a(256)), duj.a(), pi.i, dua.a());
      pi.a($$0, s, $$19);
      pi.a($$0, t, $$20, duf.a(bgj.a(204, 250)), duj.a(), pi.i, dua.a());
   }
}
