import java.util.List;

public class pf {
   public static final aet<duh> a = pe.a("crimson_fungi");
   public static final aet<duh> b = pe.a("warped_fungi");
   public static final aet<duh> c = pe.a("oak_checked");
   public static final aet<duh> d = pe.a("dark_oak_checked");
   public static final aet<duh> e = pe.a("birch_checked");
   public static final aet<duh> f = pe.a("acacia_checked");
   public static final aet<duh> g = pe.a("spruce_checked");
   public static final aet<duh> h = pe.a("mangrove_checked");
   public static final aet<duh> i = pe.a("cherry_checked");
   public static final aet<duh> j = pe.a("pine_on_snow");
   public static final aet<duh> k = pe.a("spruce_on_snow");
   public static final aet<duh> l = pe.a("pine_checked");
   public static final aet<duh> m = pe.a("jungle_tree");
   public static final aet<duh> n = pe.a("fancy_oak_checked");
   public static final aet<duh> o = pe.a("mega_jungle_tree_checked");
   public static final aet<duh> p = pe.a("mega_spruce_checked");
   public static final aet<duh> q = pe.a("mega_pine_checked");
   public static final aet<duh> r = pe.a("tall_mangrove_checked");
   public static final aet<duh> s = pe.a("jungle_bush");
   public static final aet<duh> t = pe.a("super_birch_bees_0002");
   public static final aet<duh> u = pe.a("super_birch_bees");
   public static final aet<duh> v = pe.a("oak_bees_0002");
   public static final aet<duh> w = pe.a("oak_bees_002");
   public static final aet<duh> x = pe.a("birch_bees_0002");
   public static final aet<duh> y = pe.a("birch_bees_002");
   public static final aet<duh> z = pe.a("fancy_oak_bees_0002");
   public static final aet<duh> A = pe.a("fancy_oak_bees_002");
   public static final aet<duh> B = pe.a("fancy_oak_bees");
   public static final aet<duh> C = pe.a("cherry_bees_005");

   public static void a(np<duh> $$0) {
      hh<dne<?, ?>> $$1 = $$0.a(je.as);
      hg<dne<?, ?>> $$2 = $$1.b(ou.a);
      hg<dne<?, ?>> $$3 = $$1.b(ou.c);
      hg<dne<?, ?>> $$4 = $$1.b(ou.g);
      hg<dne<?, ?>> $$5 = $$1.b(ou.h);
      hg<dne<?, ?>> $$6 = $$1.b(ou.i);
      hg<dne<?, ?>> $$7 = $$1.b(ou.j);
      hg<dne<?, ?>> $$8 = $$1.b(ou.k);
      hg<dne<?, ?>> $$9 = $$1.b(ou.x);
      hg<dne<?, ?>> $$10 = $$1.b(ou.z);
      hg<dne<?, ?>> $$11 = $$1.b(ou.l);
      hg<dne<?, ?>> $$12 = $$1.b(ou.m);
      hg<dne<?, ?>> $$13 = $$1.b(ou.n);
      hg<dne<?, ?>> $$14 = $$1.b(ou.p);
      hg<dne<?, ?>> $$15 = $$1.b(ou.q);
      hg<dne<?, ?>> $$16 = $$1.b(ou.r);
      hg<dne<?, ?>> $$17 = $$1.b(ou.y);
      hg<dne<?, ?>> $$18 = $$1.b(ou.v);
      hg<dne<?, ?>> $$19 = $$1.b(ou.s);
      hg<dne<?, ?>> $$20 = $$1.b(ou.t);
      hg<dne<?, ?>> $$21 = $$1.b(ou.A);
      hg<dne<?, ?>> $$22 = $$1.b(ou.B);
      hg<dne<?, ?>> $$23 = $$1.b(ou.D);
      hg<dne<?, ?>> $$24 = $$1.b(ou.E);
      hg<dne<?, ?>> $$25 = $$1.b(ou.G);
      hg<dne<?, ?>> $$26 = $$1.b(ou.H);
      hg<dne<?, ?>> $$27 = $$1.b(ou.J);
      hg<dne<?, ?>> $$28 = $$1.b(ou.K);
      pe.a($$0, a, $$2, dtz.a(8), dtv.a());
      pe.a($$0, b, $$3, dtz.a(8), dtv.a());
      pe.a($$0, c, $$4, pe.a(csr.x));
      pe.a($$0, d, $$5, pe.a(csr.D));
      pe.a($$0, e, $$6, pe.a(csr.z));
      pe.a($$0, f, $$7, pe.a(csr.B));
      pe.a($$0, g, $$8, pe.a(csr.y));
      pe.a($$0, h, $$9, pe.a(csr.E));
      pe.a($$0, i, $$10, pe.a(csr.C));
      dlu $$29 = dlu.a(hc.a.q(), csr.dP, csr.qC);
      List<duk> $$30 = List.of(dub.a(hc.b, dlu.a(dlu.a(csr.qC)), 8), dtw.a($$29));
      pe.a($$0, j, $$11, $$30);
      pe.a($$0, k, $$8, $$30);
      pe.a($$0, l, $$11, pe.a(csr.y));
      pe.a($$0, m, $$12, pe.a(csr.A));
      pe.a($$0, n, $$13, pe.a(csr.x));
      pe.a($$0, o, $$14, pe.a(csr.A));
      pe.a($$0, p, $$15, pe.a(csr.y));
      pe.a($$0, q, $$16, pe.a(csr.y));
      pe.a($$0, r, $$17, pe.a(csr.E));
      pe.a($$0, s, $$18, pe.a(csr.x));
      pe.a($$0, t, $$19, pe.a(csr.z));
      pe.a($$0, u, $$20, pe.a(csr.z));
      pe.a($$0, v, $$21, pe.a(csr.x));
      pe.a($$0, w, $$22, pe.a(csr.x));
      pe.a($$0, x, $$23, pe.a(csr.z));
      pe.a($$0, y, $$24, pe.a(csr.z));
      pe.a($$0, z, $$25, pe.a(csr.x));
      pe.a($$0, A, $$26, pe.a(csr.x));
      pe.a($$0, B, $$27, pe.a(csr.x));
      pe.a($$0, C, $$28, pe.a(csr.C));
   }
}
