import java.util.List;

public class pj {
   public static final aew<dum> a = pi.a("crimson_fungi");
   public static final aew<dum> b = pi.a("warped_fungi");
   public static final aew<dum> c = pi.a("oak_checked");
   public static final aew<dum> d = pi.a("dark_oak_checked");
   public static final aew<dum> e = pi.a("birch_checked");
   public static final aew<dum> f = pi.a("acacia_checked");
   public static final aew<dum> g = pi.a("spruce_checked");
   public static final aew<dum> h = pi.a("mangrove_checked");
   public static final aew<dum> i = pi.a("cherry_checked");
   public static final aew<dum> j = pi.a("pine_on_snow");
   public static final aew<dum> k = pi.a("spruce_on_snow");
   public static final aew<dum> l = pi.a("pine_checked");
   public static final aew<dum> m = pi.a("jungle_tree");
   public static final aew<dum> n = pi.a("fancy_oak_checked");
   public static final aew<dum> o = pi.a("mega_jungle_tree_checked");
   public static final aew<dum> p = pi.a("mega_spruce_checked");
   public static final aew<dum> q = pi.a("mega_pine_checked");
   public static final aew<dum> r = pi.a("tall_mangrove_checked");
   public static final aew<dum> s = pi.a("jungle_bush");
   public static final aew<dum> t = pi.a("super_birch_bees_0002");
   public static final aew<dum> u = pi.a("super_birch_bees");
   public static final aew<dum> v = pi.a("oak_bees_0002");
   public static final aew<dum> w = pi.a("oak_bees_002");
   public static final aew<dum> x = pi.a("birch_bees_0002");
   public static final aew<dum> y = pi.a("birch_bees_002");
   public static final aew<dum> z = pi.a("fancy_oak_bees_0002");
   public static final aew<dum> A = pi.a("fancy_oak_bees_002");
   public static final aew<dum> B = pi.a("fancy_oak_bees");
   public static final aew<dum> C = pi.a("cherry_bees_005");

   public static void a(nt<dum> $$0) {
      hh<dnj<?, ?>> $$1 = $$0.a(je.as);
      hg<dnj<?, ?>> $$2 = $$1.b(oy.a);
      hg<dnj<?, ?>> $$3 = $$1.b(oy.c);
      hg<dnj<?, ?>> $$4 = $$1.b(oy.g);
      hg<dnj<?, ?>> $$5 = $$1.b(oy.h);
      hg<dnj<?, ?>> $$6 = $$1.b(oy.i);
      hg<dnj<?, ?>> $$7 = $$1.b(oy.j);
      hg<dnj<?, ?>> $$8 = $$1.b(oy.k);
      hg<dnj<?, ?>> $$9 = $$1.b(oy.x);
      hg<dnj<?, ?>> $$10 = $$1.b(oy.z);
      hg<dnj<?, ?>> $$11 = $$1.b(oy.l);
      hg<dnj<?, ?>> $$12 = $$1.b(oy.m);
      hg<dnj<?, ?>> $$13 = $$1.b(oy.n);
      hg<dnj<?, ?>> $$14 = $$1.b(oy.p);
      hg<dnj<?, ?>> $$15 = $$1.b(oy.q);
      hg<dnj<?, ?>> $$16 = $$1.b(oy.r);
      hg<dnj<?, ?>> $$17 = $$1.b(oy.y);
      hg<dnj<?, ?>> $$18 = $$1.b(oy.v);
      hg<dnj<?, ?>> $$19 = $$1.b(oy.s);
      hg<dnj<?, ?>> $$20 = $$1.b(oy.t);
      hg<dnj<?, ?>> $$21 = $$1.b(oy.A);
      hg<dnj<?, ?>> $$22 = $$1.b(oy.B);
      hg<dnj<?, ?>> $$23 = $$1.b(oy.D);
      hg<dnj<?, ?>> $$24 = $$1.b(oy.E);
      hg<dnj<?, ?>> $$25 = $$1.b(oy.G);
      hg<dnj<?, ?>> $$26 = $$1.b(oy.H);
      hg<dnj<?, ?>> $$27 = $$1.b(oy.J);
      hg<dnj<?, ?>> $$28 = $$1.b(oy.K);
      pi.a($$0, a, $$2, due.a(8), dua.a());
      pi.a($$0, b, $$3, due.a(8), dua.a());
      pi.a($$0, c, $$4, pi.a(csw.x));
      pi.a($$0, d, $$5, pi.a(csw.D));
      pi.a($$0, e, $$6, pi.a(csw.z));
      pi.a($$0, f, $$7, pi.a(csw.B));
      pi.a($$0, g, $$8, pi.a(csw.y));
      pi.a($$0, h, $$9, pi.a(csw.E));
      pi.a($$0, i, $$10, pi.a(csw.C));
      dlz $$29 = dlz.a(hc.a.q(), csw.dP, csw.qC);
      List<dup> $$30 = List.of(dug.a(hc.b, dlz.a(dlz.a(csw.qC)), 8), dub.a($$29));
      pi.a($$0, j, $$11, $$30);
      pi.a($$0, k, $$8, $$30);
      pi.a($$0, l, $$11, pi.a(csw.y));
      pi.a($$0, m, $$12, pi.a(csw.A));
      pi.a($$0, n, $$13, pi.a(csw.x));
      pi.a($$0, o, $$14, pi.a(csw.A));
      pi.a($$0, p, $$15, pi.a(csw.y));
      pi.a($$0, q, $$16, pi.a(csw.y));
      pi.a($$0, r, $$17, pi.a(csw.E));
      pi.a($$0, s, $$18, pi.a(csw.x));
      pi.a($$0, t, $$19, pi.a(csw.z));
      pi.a($$0, u, $$20, pi.a(csw.z));
      pi.a($$0, v, $$21, pi.a(csw.x));
      pi.a($$0, w, $$22, pi.a(csw.x));
      pi.a($$0, x, $$23, pi.a(csw.z));
      pi.a($$0, y, $$24, pi.a(csw.z));
      pi.a($$0, z, $$25, pi.a(csw.x));
      pi.a($$0, A, $$26, pi.a(csw.x));
      pi.a($$0, B, $$27, pi.a(csw.x));
      pi.a($$0, C, $$28, pi.a(csw.C));
   }
}
