import java.util.List;

public class pj {
   public static final aex<duo> a = pi.a("crimson_fungi");
   public static final aex<duo> b = pi.a("warped_fungi");
   public static final aex<duo> c = pi.a("oak_checked");
   public static final aex<duo> d = pi.a("dark_oak_checked");
   public static final aex<duo> e = pi.a("birch_checked");
   public static final aex<duo> f = pi.a("acacia_checked");
   public static final aex<duo> g = pi.a("spruce_checked");
   public static final aex<duo> h = pi.a("mangrove_checked");
   public static final aex<duo> i = pi.a("cherry_checked");
   public static final aex<duo> j = pi.a("pine_on_snow");
   public static final aex<duo> k = pi.a("spruce_on_snow");
   public static final aex<duo> l = pi.a("pine_checked");
   public static final aex<duo> m = pi.a("jungle_tree");
   public static final aex<duo> n = pi.a("fancy_oak_checked");
   public static final aex<duo> o = pi.a("mega_jungle_tree_checked");
   public static final aex<duo> p = pi.a("mega_spruce_checked");
   public static final aex<duo> q = pi.a("mega_pine_checked");
   public static final aex<duo> r = pi.a("tall_mangrove_checked");
   public static final aex<duo> s = pi.a("jungle_bush");
   public static final aex<duo> t = pi.a("super_birch_bees_0002");
   public static final aex<duo> u = pi.a("super_birch_bees");
   public static final aex<duo> v = pi.a("oak_bees_0002");
   public static final aex<duo> w = pi.a("oak_bees_002");
   public static final aex<duo> x = pi.a("birch_bees_0002");
   public static final aex<duo> y = pi.a("birch_bees_002");
   public static final aex<duo> z = pi.a("fancy_oak_bees_0002");
   public static final aex<duo> A = pi.a("fancy_oak_bees_002");
   public static final aex<duo> B = pi.a("fancy_oak_bees");
   public static final aex<duo> C = pi.a("cherry_bees_005");

   public static void a(nt<duo> $$0) {
      hh<dnl<?, ?>> $$1 = $$0.a(je.as);
      hg<dnl<?, ?>> $$2 = $$1.b(oy.a);
      hg<dnl<?, ?>> $$3 = $$1.b(oy.c);
      hg<dnl<?, ?>> $$4 = $$1.b(oy.g);
      hg<dnl<?, ?>> $$5 = $$1.b(oy.h);
      hg<dnl<?, ?>> $$6 = $$1.b(oy.i);
      hg<dnl<?, ?>> $$7 = $$1.b(oy.j);
      hg<dnl<?, ?>> $$8 = $$1.b(oy.k);
      hg<dnl<?, ?>> $$9 = $$1.b(oy.x);
      hg<dnl<?, ?>> $$10 = $$1.b(oy.z);
      hg<dnl<?, ?>> $$11 = $$1.b(oy.l);
      hg<dnl<?, ?>> $$12 = $$1.b(oy.m);
      hg<dnl<?, ?>> $$13 = $$1.b(oy.n);
      hg<dnl<?, ?>> $$14 = $$1.b(oy.p);
      hg<dnl<?, ?>> $$15 = $$1.b(oy.q);
      hg<dnl<?, ?>> $$16 = $$1.b(oy.r);
      hg<dnl<?, ?>> $$17 = $$1.b(oy.y);
      hg<dnl<?, ?>> $$18 = $$1.b(oy.v);
      hg<dnl<?, ?>> $$19 = $$1.b(oy.s);
      hg<dnl<?, ?>> $$20 = $$1.b(oy.t);
      hg<dnl<?, ?>> $$21 = $$1.b(oy.A);
      hg<dnl<?, ?>> $$22 = $$1.b(oy.B);
      hg<dnl<?, ?>> $$23 = $$1.b(oy.D);
      hg<dnl<?, ?>> $$24 = $$1.b(oy.E);
      hg<dnl<?, ?>> $$25 = $$1.b(oy.G);
      hg<dnl<?, ?>> $$26 = $$1.b(oy.H);
      hg<dnl<?, ?>> $$27 = $$1.b(oy.J);
      hg<dnl<?, ?>> $$28 = $$1.b(oy.K);
      pi.a($$0, a, $$2, dug.a(8), duc.a());
      pi.a($$0, b, $$3, dug.a(8), duc.a());
      pi.a($$0, c, $$4, pi.a(csy.x));
      pi.a($$0, d, $$5, pi.a(csy.D));
      pi.a($$0, e, $$6, pi.a(csy.z));
      pi.a($$0, f, $$7, pi.a(csy.B));
      pi.a($$0, g, $$8, pi.a(csy.y));
      pi.a($$0, h, $$9, pi.a(csy.E));
      pi.a($$0, i, $$10, pi.a(csy.C));
      dmb $$29 = dmb.a(hc.a.q(), csy.dP, csy.qC);
      List<dur> $$30 = List.of(dui.a(hc.b, dmb.a(dmb.a(csy.qC)), 8), dud.a($$29));
      pi.a($$0, j, $$11, $$30);
      pi.a($$0, k, $$8, $$30);
      pi.a($$0, l, $$11, pi.a(csy.y));
      pi.a($$0, m, $$12, pi.a(csy.A));
      pi.a($$0, n, $$13, pi.a(csy.x));
      pi.a($$0, o, $$14, pi.a(csy.A));
      pi.a($$0, p, $$15, pi.a(csy.y));
      pi.a($$0, q, $$16, pi.a(csy.y));
      pi.a($$0, r, $$17, pi.a(csy.E));
      pi.a($$0, s, $$18, pi.a(csy.x));
      pi.a($$0, t, $$19, pi.a(csy.z));
      pi.a($$0, u, $$20, pi.a(csy.z));
      pi.a($$0, v, $$21, pi.a(csy.x));
      pi.a($$0, w, $$22, pi.a(csy.x));
      pi.a($$0, x, $$23, pi.a(csy.z));
      pi.a($$0, y, $$24, pi.a(csy.z));
      pi.a($$0, z, $$25, pi.a(csy.x));
      pi.a($$0, A, $$26, pi.a(csy.x));
      pi.a($$0, B, $$27, pi.a(csy.x));
      pi.a($$0, C, $$28, pi.a(csy.C));
   }
}
