import java.util.List;

public class px {
   public static final agf<dow<?, ?>> a = pu.a("ore_magma");
   public static final agf<dow<?, ?>> b = pu.a("ore_soul_sand");
   public static final agf<dow<?, ?>> c = pu.a("ore_nether_gold");
   public static final agf<dow<?, ?>> d = pu.a("ore_quartz");
   public static final agf<dow<?, ?>> e = pu.a("ore_gravel_nether");
   public static final agf<dow<?, ?>> f = pu.a("ore_blackstone");
   public static final agf<dow<?, ?>> g = pu.a("ore_dirt");
   public static final agf<dow<?, ?>> h = pu.a("ore_gravel");
   public static final agf<dow<?, ?>> i = pu.a("ore_granite");
   public static final agf<dow<?, ?>> j = pu.a("ore_diorite");
   public static final agf<dow<?, ?>> k = pu.a("ore_andesite");
   public static final agf<dow<?, ?>> l = pu.a("ore_tuff");
   public static final agf<dow<?, ?>> m = pu.a("ore_coal");
   public static final agf<dow<?, ?>> n = pu.a("ore_coal_buried");
   public static final agf<dow<?, ?>> o = pu.a("ore_iron");
   public static final agf<dow<?, ?>> p = pu.a("ore_iron_small");
   public static final agf<dow<?, ?>> q = pu.a("ore_gold");
   public static final agf<dow<?, ?>> r = pu.a("ore_gold_buried");
   public static final agf<dow<?, ?>> s = pu.a("ore_redstone");
   public static final agf<dow<?, ?>> t = pu.a("ore_diamond_small");
   public static final agf<dow<?, ?>> u = pu.a("ore_diamond_medium");
   public static final agf<dow<?, ?>> v = pu.a("ore_diamond_large");
   public static final agf<dow<?, ?>> w = pu.a("ore_diamond_buried");
   public static final agf<dow<?, ?>> x = pu.a("ore_lapis");
   public static final agf<dow<?, ?>> y = pu.a("ore_lapis_buried");
   public static final agf<dow<?, ?>> z = pu.a("ore_infested");
   public static final agf<dow<?, ?>> A = pu.a("ore_emerald");
   public static final agf<dow<?, ?>> B = pu.a("ore_ancient_debris_large");
   public static final agf<dow<?, ?>> C = pu.a("ore_ancient_debris_small");
   public static final agf<dow<?, ?>> D = pu.a("ore_copper_small");
   public static final agf<dow<?, ?>> E = pu.a("ore_copper_large");
   public static final agf<dow<?, ?>> F = pu.a("ore_clay");

   public static void a(ou<dow<?, ?>> $$0) {
      eap $$1 = new eax(arc.bd);
      eap $$2 = new eax(arc.be);
      eap $$3 = new eax(arc.bf);
      eap $$4 = new dzy(cuv.dV);
      eap $$5 = new eax(arc.bg);
      List<drv.a> $$6 = List.of(drv.a($$2, cuv.P.o()), drv.a($$3, cuv.Q.o()));
      List<drv.a> $$7 = List.of(drv.a($$2, cuv.N.o()), drv.a($$3, cuv.O.o()));
      List<drv.a> $$8 = List.of(drv.a($$2, cuv.cx.o()), drv.a($$3, cuv.cy.o()));
      List<drv.a> $$9 = List.of(drv.a($$2, cuv.aR.o()), drv.a($$3, cuv.aS.o()));
      List<drv.a> $$10 = List.of(drv.a($$2, cuv.qN.o()), drv.a($$3, cuv.qO.o()));
      List<drv.a> $$11 = List.of(drv.a($$2, cuv.R.o()), drv.a($$3, cuv.S.o()));
      pu.a($$0, a, dpj.I, new drv($$4, cuv.kJ.o(), 33));
      pu.a($$0, b, dpj.I, new drv($$4, cuv.dW.o(), 12));
      pu.a($$0, c, dpj.I, new drv($$4, cuv.T.o(), 10));
      pu.a($$0, d, dpj.I, new drv($$4, cuv.hb.o(), 14));
      pu.a($$0, e, dpj.I, new drv($$4, cuv.L.o(), 33));
      pu.a($$0, f, dpj.I, new drv($$4, cuv.pr.o(), 33));
      pu.a($$0, g, dpj.I, new drv($$1, cuv.j.o(), 33));
      pu.a($$0, h, dpj.I, new drv($$1, cuv.L.o(), 33));
      pu.a($$0, i, dpj.I, new drv($$1, cuv.c.o(), 64));
      pu.a($$0, j, dpj.I, new drv($$1, cuv.e.o(), 64));
      pu.a($$0, k, dpj.I, new drv($$1, cuv.g.o(), 64));
      pu.a($$0, l, dpj.I, new drv($$1, cuv.qz.o(), 64));
      pu.a($$0, m, dpj.I, new drv($$11, 17));
      pu.a($$0, n, dpj.I, new drv($$11, 17, 0.5F));
      pu.a($$0, o, dpj.I, new drv($$6, 9));
      pu.a($$0, p, dpj.I, new drv($$6, 4));
      pu.a($$0, q, dpj.I, new drv($$7, 9));
      pu.a($$0, r, dpj.I, new drv($$7, 9, 0.5F));
      pu.a($$0, s, dpj.I, new drv(List.of(drv.a($$2, cuv.dI.o()), drv.a($$3, cuv.dJ.o())), 8));
      pu.a($$0, t, dpj.I, new drv($$8, 4, 0.5F));
      pu.a($$0, v, dpj.I, new drv($$8, 12, 0.7F));
      pu.a($$0, w, dpj.I, new drv($$8, 8, 1.0F));
      pu.a($$0, u, dpj.I, new drv($$8, 8, 0.5F));
      pu.a($$0, x, dpj.I, new drv($$9, 7));
      pu.a($$0, y, dpj.I, new drv($$9, 7, 1.0F));
      pu.a($$0, z, dpj.I, new drv(List.of(drv.a($$2, cuv.eN.o()), drv.a($$3, cuv.sc.o())), 9));
      pu.a($$0, A, dpj.I, new drv(List.of(drv.a($$2, cuv.fE.o()), drv.a($$3, cuv.fF.o())), 3));
      pu.a($$0, B, dpj.ae, new drv($$5, cuv.pj.o(), 3, 1.0F));
      pu.a($$0, C, dpj.ae, new drv($$5, cuv.pj.o(), 2, 1.0F));
      pu.a($$0, D, dpj.I, new drv($$10, 10));
      pu.a($$0, E, dpj.I, new drv($$10, 20));
      pu.a($$0, F, dpj.I, new drv($$1, cuv.dR.o(), 33));
   }
}
