import java.util.concurrent.CompletableFuture;
import java.util.function.Predicate;

public class qb extends qp<dic> {
   public qb(mj $$0, CompletableFuture<js.a> $$1) {
      super($$0, mb.aH, $$1);
   }

   @Override
   protected void a(js.a $$0) {
      this.b(axt.a).a(dij.X).a(dij.V).a(dij.T).a(dij.R);
      this.b(axt.b).b(axt.a).a(dij.W).a(dij.S).a(dij.U).a(dij.Q).a(dij.P);
      this.b(axt.c).a(dij.M).a(dij.N);
      this.b(axt.d).a(dij.K).a(dij.L);
      this.b(axt.e).a(dij.D).a(dij.H).a(dij.I).a(dij.J).a(dij.G).a(dij.E);
      this.b(axt.f).a(dij.A).a(dij.B).a(dij.C);
      this.b(axt.g).a(dij.t).a(dij.v).a(dij.u);
      this.b(axt.h).a(dij.p).a(dij.q).a(dij.n).a(dij.o);
      this.b(axt.i).a(dij.z).a(dij.x).a(dij.y);
      this.b(axt.j).a(dij.i).a(dij.j).a(dij.k).a(dij.m).a(dij.l).a(dij.F);
      this.b(axt.k).a(dij.r).a(dij.s).a(dij.w);
      qp.b<dic> $$1 = this.b(axt.m);
      diq.a.a.a().forEach($$1::a);
      qp.b<dic> $$2 = this.b(axt.l);
      diq.a.b.a().forEach($$2::a);
      this.b(axt.n).a(dij.ah).a(dij.ai).a(dij.aj).a(dij.ak).a(dij.al);
      this.b(axt.p).b(axt.c);
      this.b(axt.q).a(dij.f);
      this.b(axt.r).a(dij.q).a(dij.d).a(dij.G);
      this.b(axt.s).a(dij.z).a(dij.x);
      this.b(axt.t)
         .b(axt.b)
         .b(axt.d)
         .b(axt.c)
         .b(axt.e)
         .b(axt.g)
         .b(axt.h)
         .b(axt.i)
         .b(axt.j)
         .a(dij.O)
         .a(dij.Y)
         .a(dij.e)
         .a(dij.w)
         .a(dij.f)
         .a(dij.r)
         .a(dij.d)
         .a(dij.b)
         .a(dij.c)
         .a(dij.g)
         .a(dij.h)
         .a(dij.s)
         .a(dij.Z)
         .a(dij.aa);
      this.b(axt.u).b(axt.f);
      this.b(axt.Y).a(dij.ab);
      this.b(axt.v).b(axt.a);
      this.b(axt.X).b(axt.b).b(axt.d);
      this.b(axt.w).a(dij.W).a(dij.U).a(dij.S).a(dij.X).a(dij.V).a(dij.T);
      this.b(axt.x).a(dij.Q).a(dij.P).a(dij.R);
      this.b(axt.y).a(dij.f).a(dij.b).a(dij.r).a(dij.d).a(dij.p).b(axt.e).a(dij.F);
      this.b(axt.z).a(dij.f);
      this.b(axt.A).b(axt.i);
      this.b(axt.B).b(axt.b);
      this.b(axt.C).a(dij.g).a(dij.h);
      this.b(axt.D).b(axt.f).b(axt.g).a(dij.s).a(dij.w).a(dij.O).b(axt.e);
      this.b(axt.E).b(axt.c).b(axt.d).b(axt.h).b(axt.j).a(dij.Y).a(dij.e).a(dij.Z).a(dij.aa).a(dij.r).a(dij.d).a(dij.b).a(dij.c);
      this.b(axt.F).b(axt.c);
      this.b(axt.G).b(axt.b);
      this.b(axt.J).a(dij.g);
      this.b(axt.K).a(dij.f);
      this.b(axt.L).a(dij.b).a(dij.D);
      this.b(axt.M).a(dij.r);
      this.b(axt.N).a(dij.d);
      this.b(axt.O).a(dij.p);
      this.b(axt.P).a(dij.p).a(dij.q).a(dij.n).a(dij.o).a(dij.m).a(dij.x);
      this.b(axt.Q).a(dij.l);
      this.b(axt.o)
         .a(dij.b)
         .a(dij.c)
         .a(dij.d)
         .a(dij.e)
         .a(dij.f)
         .a(dij.i)
         .a(dij.j)
         .a(dij.k)
         .a(dij.l)
         .a(dij.m)
         .a(dij.n)
         .a(dij.o)
         .a(dij.p)
         .a(dij.q)
         .a(dij.r)
         .a(dij.s)
         .a(dij.t)
         .a(dij.u)
         .a(dij.v)
         .a(dij.w)
         .a(dij.x)
         .a(dij.y)
         .a(dij.z)
         .a(dij.A)
         .a(dij.B)
         .a(dij.C)
         .a(dij.D)
         .a(dij.F)
         .a(dij.G)
         .a(dij.H)
         .a(dij.I)
         .a(dij.J)
         .a(dij.Y)
         .a(dij.Z)
         .a(dij.aa);
      this.b(axt.H).b(axt.l);
      qp.b<dic> $$3 = this.b(axt.I);
      diq.a.b.a().filter(Predicate.not(dij.ab::equals)).forEach($$3::a);
      this.b(axt.R).b(axt.m);
      this.b(axt.S).a(dij.af);
      this.b(axt.T).a(dij.ae).a(dij.ac).a(dij.af).a(dij.ad);
      this.b(axt.U).a(dij.ab);
      this.b(axt.V).b(axt.m);
      this.b(axt.W).a(dij.ai).a(dij.aj);
      this.b(axt.ac).a(dij.P);
      this.b(axt.Z).b(axt.b).b(axt.d);
      this.b(axt.aa).a(dij.g).a(dij.h);
      this.b(axt.ab).b(axt.b).b(axt.d).a(dij.g).a(dij.h);
      this.b(axt.af).a(dij.Y);
      this.b(axt.ag).a(dij.Y);
      this.b(axt.ah).a(dij.a);
      this.b(axt.ai).a(dij.d).a(dij.e).a(dij.H).a(dij.I).a(dij.G).a(dij.W).a(dij.X).a(dij.F).a(dij.ab).a(dij.L).a(dij.q).a(dij.N).b(axt.n);
      this.b(axt.aj).a(dij.f).a(dij.P).b(axt.i).b(axt.k).b(axt.m).b(axt.f).a(dij.h);
      this.b(axt.ak).a(dij.f);
      this.b(axt.al).a(dij.d).a(dij.e).a(dij.W).a(dij.q).a(dij.L).a(dij.N).a(dij.H).a(dij.I).a(dij.G).a(dij.F);
      this.b(axt.am).b(axt.d);
      this.b(axt.an).a(dij.aa);
      this.b(axt.ao).a(dij.W).a(dij.X);
      this.b(axt.ap).b(axt.d);
      this.b(axt.aq).a(dij.g).a(dij.h);
      this.b(axt.ar).a(dij.d).a(dij.e).a(dij.W).a(dij.q).a(dij.L).a(dij.N).a(dij.H).a(dij.I).a(dij.G).a(dij.F);
      this.b(axt.ad).a(dij.z).a(dij.Y).a(dij.h).a(dij.G).a(dij.H).a(dij.I).a(dij.g).a(dij.x);
      this.b(axt.ae).a(dij.A).a(dij.ag).a(dij.ae).a(dij.f).a(dij.B).a(dij.ac).a(dij.r).a(dij.s).a(dij.af).a(dij.ad).a(dij.w).a(dij.C);
   }
}
