import java.util.List;

public class qm {
   public static final ahf<drg<?, ?>> a = qj.a("ore_magma");
   public static final ahf<drg<?, ?>> b = qj.a("ore_soul_sand");
   public static final ahf<drg<?, ?>> c = qj.a("ore_nether_gold");
   public static final ahf<drg<?, ?>> d = qj.a("ore_quartz");
   public static final ahf<drg<?, ?>> e = qj.a("ore_gravel_nether");
   public static final ahf<drg<?, ?>> f = qj.a("ore_blackstone");
   public static final ahf<drg<?, ?>> g = qj.a("ore_dirt");
   public static final ahf<drg<?, ?>> h = qj.a("ore_gravel");
   public static final ahf<drg<?, ?>> i = qj.a("ore_granite");
   public static final ahf<drg<?, ?>> j = qj.a("ore_diorite");
   public static final ahf<drg<?, ?>> k = qj.a("ore_andesite");
   public static final ahf<drg<?, ?>> l = qj.a("ore_tuff");
   public static final ahf<drg<?, ?>> m = qj.a("ore_coal");
   public static final ahf<drg<?, ?>> n = qj.a("ore_coal_buried");
   public static final ahf<drg<?, ?>> o = qj.a("ore_iron");
   public static final ahf<drg<?, ?>> p = qj.a("ore_iron_small");
   public static final ahf<drg<?, ?>> q = qj.a("ore_gold");
   public static final ahf<drg<?, ?>> r = qj.a("ore_gold_buried");
   public static final ahf<drg<?, ?>> s = qj.a("ore_redstone");
   public static final ahf<drg<?, ?>> t = qj.a("ore_diamond_small");
   public static final ahf<drg<?, ?>> u = qj.a("ore_diamond_medium");
   public static final ahf<drg<?, ?>> v = qj.a("ore_diamond_large");
   public static final ahf<drg<?, ?>> w = qj.a("ore_diamond_buried");
   public static final ahf<drg<?, ?>> x = qj.a("ore_lapis");
   public static final ahf<drg<?, ?>> y = qj.a("ore_lapis_buried");
   public static final ahf<drg<?, ?>> z = qj.a("ore_infested");
   public static final ahf<drg<?, ?>> A = qj.a("ore_emerald");
   public static final ahf<drg<?, ?>> B = qj.a("ore_ancient_debris_large");
   public static final ahf<drg<?, ?>> C = qj.a("ore_ancient_debris_small");
   public static final ahf<drg<?, ?>> D = qj.a("ore_copper_small");
   public static final ahf<drg<?, ?>> E = qj.a("ore_copper_large");
   public static final ahf<drg<?, ?>> F = qj.a("ore_clay");

   public static void a(pe<drg<?, ?>> $$0) {
      ecz $$1 = new edh(asg.bd);
      ecz $$2 = new edh(asg.be);
      ecz $$3 = new edh(asg.bf);
      ecz $$4 = new eci(cwr.dV);
      ecz $$5 = new edh(asg.bg);
      List<duf.a> $$6 = List.of(duf.a($$2, cwr.P.o()), duf.a($$3, cwr.Q.o()));
      List<duf.a> $$7 = List.of(duf.a($$2, cwr.N.o()), duf.a($$3, cwr.O.o()));
      List<duf.a> $$8 = List.of(duf.a($$2, cwr.cx.o()), duf.a($$3, cwr.cy.o()));
      List<duf.a> $$9 = List.of(duf.a($$2, cwr.aR.o()), duf.a($$3, cwr.aS.o()));
      List<duf.a> $$10 = List.of(duf.a($$2, cwr.ra.o()), duf.a($$3, cwr.rb.o()));
      List<duf.a> $$11 = List.of(duf.a($$2, cwr.R.o()), duf.a($$3, cwr.S.o()));
      qj.a($$0, a, drt.I, new duf($$4, cwr.kJ.o(), 33));
      qj.a($$0, b, drt.I, new duf($$4, cwr.dW.o(), 12));
      qj.a($$0, c, drt.I, new duf($$4, cwr.T.o(), 10));
      qj.a($$0, d, drt.I, new duf($$4, cwr.hb.o(), 14));
      qj.a($$0, e, drt.I, new duf($$4, cwr.L.o(), 33));
      qj.a($$0, f, drt.I, new duf($$4, cwr.pr.o(), 33));
      qj.a($$0, g, drt.I, new duf($$1, cwr.j.o(), 33));
      qj.a($$0, h, drt.I, new duf($$1, cwr.L.o(), 33));
      qj.a($$0, i, drt.I, new duf($$1, cwr.c.o(), 64));
      qj.a($$0, j, drt.I, new duf($$1, cwr.e.o(), 64));
      qj.a($$0, k, drt.I, new duf($$1, cwr.g.o(), 64));
      qj.a($$0, l, drt.I, new duf($$1, cwr.qz.o(), 64));
      qj.a($$0, m, drt.I, new duf($$11, 17));
      qj.a($$0, n, drt.I, new duf($$11, 17, 0.5F));
      qj.a($$0, o, drt.I, new duf($$6, 9));
      qj.a($$0, p, drt.I, new duf($$6, 4));
      qj.a($$0, q, drt.I, new duf($$7, 9));
      qj.a($$0, r, drt.I, new duf($$7, 9, 0.5F));
      qj.a($$0, s, drt.I, new duf(List.of(duf.a($$2, cwr.dI.o()), duf.a($$3, cwr.dJ.o())), 8));
      qj.a($$0, t, drt.I, new duf($$8, 4, 0.5F));
      qj.a($$0, v, drt.I, new duf($$8, 12, 0.7F));
      qj.a($$0, w, drt.I, new duf($$8, 8, 1.0F));
      qj.a($$0, u, drt.I, new duf($$8, 8, 0.5F));
      qj.a($$0, x, drt.I, new duf($$9, 7));
      qj.a($$0, y, drt.I, new duf($$9, 7, 1.0F));
      qj.a($$0, z, drt.I, new duf(List.of(duf.a($$2, cwr.eN.o()), duf.a($$3, cwr.td.o())), 9));
      qj.a($$0, A, drt.I, new duf(List.of(duf.a($$2, cwr.fE.o()), duf.a($$3, cwr.fF.o())), 3));
      qj.a($$0, B, drt.ae, new duf($$5, cwr.pj.o(), 3, 1.0F));
      qj.a($$0, C, drt.ae, new duf($$5, cwr.pj.o(), 2, 1.0F));
      qj.a($$0, D, drt.I, new duf($$10, 10));
      qj.a($$0, E, drt.I, new duf($$10, 20));
      qj.a($$0, F, drt.I, new duf($$1, cwr.dR.o(), 33));
   }
}
