import java.util.List;

public class qm {
   public static final ahf<drh<?, ?>> a = qj.a("ore_magma");
   public static final ahf<drh<?, ?>> b = qj.a("ore_soul_sand");
   public static final ahf<drh<?, ?>> c = qj.a("ore_nether_gold");
   public static final ahf<drh<?, ?>> d = qj.a("ore_quartz");
   public static final ahf<drh<?, ?>> e = qj.a("ore_gravel_nether");
   public static final ahf<drh<?, ?>> f = qj.a("ore_blackstone");
   public static final ahf<drh<?, ?>> g = qj.a("ore_dirt");
   public static final ahf<drh<?, ?>> h = qj.a("ore_gravel");
   public static final ahf<drh<?, ?>> i = qj.a("ore_granite");
   public static final ahf<drh<?, ?>> j = qj.a("ore_diorite");
   public static final ahf<drh<?, ?>> k = qj.a("ore_andesite");
   public static final ahf<drh<?, ?>> l = qj.a("ore_tuff");
   public static final ahf<drh<?, ?>> m = qj.a("ore_coal");
   public static final ahf<drh<?, ?>> n = qj.a("ore_coal_buried");
   public static final ahf<drh<?, ?>> o = qj.a("ore_iron");
   public static final ahf<drh<?, ?>> p = qj.a("ore_iron_small");
   public static final ahf<drh<?, ?>> q = qj.a("ore_gold");
   public static final ahf<drh<?, ?>> r = qj.a("ore_gold_buried");
   public static final ahf<drh<?, ?>> s = qj.a("ore_redstone");
   public static final ahf<drh<?, ?>> t = qj.a("ore_diamond_small");
   public static final ahf<drh<?, ?>> u = qj.a("ore_diamond_medium");
   public static final ahf<drh<?, ?>> v = qj.a("ore_diamond_large");
   public static final ahf<drh<?, ?>> w = qj.a("ore_diamond_buried");
   public static final ahf<drh<?, ?>> x = qj.a("ore_lapis");
   public static final ahf<drh<?, ?>> y = qj.a("ore_lapis_buried");
   public static final ahf<drh<?, ?>> z = qj.a("ore_infested");
   public static final ahf<drh<?, ?>> A = qj.a("ore_emerald");
   public static final ahf<drh<?, ?>> B = qj.a("ore_ancient_debris_large");
   public static final ahf<drh<?, ?>> C = qj.a("ore_ancient_debris_small");
   public static final ahf<drh<?, ?>> D = qj.a("ore_copper_small");
   public static final ahf<drh<?, ?>> E = qj.a("ore_copper_large");
   public static final ahf<drh<?, ?>> F = qj.a("ore_clay");

   public static void a(pe<drh<?, ?>> $$0) {
      eda $$1 = new edi(ash.bd);
      eda $$2 = new edi(ash.be);
      eda $$3 = new edi(ash.bf);
      eda $$4 = new ecj(cws.dV);
      eda $$5 = new edi(ash.bg);
      List<dug.a> $$6 = List.of(dug.a($$2, cws.P.o()), dug.a($$3, cws.Q.o()));
      List<dug.a> $$7 = List.of(dug.a($$2, cws.N.o()), dug.a($$3, cws.O.o()));
      List<dug.a> $$8 = List.of(dug.a($$2, cws.cx.o()), dug.a($$3, cws.cy.o()));
      List<dug.a> $$9 = List.of(dug.a($$2, cws.aR.o()), dug.a($$3, cws.aS.o()));
      List<dug.a> $$10 = List.of(dug.a($$2, cws.ra.o()), dug.a($$3, cws.rb.o()));
      List<dug.a> $$11 = List.of(dug.a($$2, cws.R.o()), dug.a($$3, cws.S.o()));
      qj.a($$0, a, dru.I, new dug($$4, cws.kJ.o(), 33));
      qj.a($$0, b, dru.I, new dug($$4, cws.dW.o(), 12));
      qj.a($$0, c, dru.I, new dug($$4, cws.T.o(), 10));
      qj.a($$0, d, dru.I, new dug($$4, cws.hb.o(), 14));
      qj.a($$0, e, dru.I, new dug($$4, cws.L.o(), 33));
      qj.a($$0, f, dru.I, new dug($$4, cws.pr.o(), 33));
      qj.a($$0, g, dru.I, new dug($$1, cws.j.o(), 33));
      qj.a($$0, h, dru.I, new dug($$1, cws.L.o(), 33));
      qj.a($$0, i, dru.I, new dug($$1, cws.c.o(), 64));
      qj.a($$0, j, dru.I, new dug($$1, cws.e.o(), 64));
      qj.a($$0, k, dru.I, new dug($$1, cws.g.o(), 64));
      qj.a($$0, l, dru.I, new dug($$1, cws.qz.o(), 64));
      qj.a($$0, m, dru.I, new dug($$11, 17));
      qj.a($$0, n, dru.I, new dug($$11, 17, 0.5F));
      qj.a($$0, o, dru.I, new dug($$6, 9));
      qj.a($$0, p, dru.I, new dug($$6, 4));
      qj.a($$0, q, dru.I, new dug($$7, 9));
      qj.a($$0, r, dru.I, new dug($$7, 9, 0.5F));
      qj.a($$0, s, dru.I, new dug(List.of(dug.a($$2, cws.dI.o()), dug.a($$3, cws.dJ.o())), 8));
      qj.a($$0, t, dru.I, new dug($$8, 4, 0.5F));
      qj.a($$0, v, dru.I, new dug($$8, 12, 0.7F));
      qj.a($$0, w, dru.I, new dug($$8, 8, 1.0F));
      qj.a($$0, u, dru.I, new dug($$8, 8, 0.5F));
      qj.a($$0, x, dru.I, new dug($$9, 7));
      qj.a($$0, y, dru.I, new dug($$9, 7, 1.0F));
      qj.a($$0, z, dru.I, new dug(List.of(dug.a($$2, cws.eN.o()), dug.a($$3, cws.td.o())), 9));
      qj.a($$0, A, dru.I, new dug(List.of(dug.a($$2, cws.fE.o()), dug.a($$3, cws.fF.o())), 3));
      qj.a($$0, B, dru.ae, new dug($$5, cws.pj.o(), 3, 1.0F));
      qj.a($$0, C, dru.ae, new dug($$5, cws.pj.o(), 2, 1.0F));
      qj.a($$0, D, dru.I, new dug($$10, 10));
      qj.a($$0, E, dru.I, new dug($$10, 20));
      qj.a($$0, F, dru.I, new dug($$1, cws.dR.o(), 33));
   }
}
