import java.util.List;

public class qp {
   public static final aix<dtm<?, ?>> a = qm.a("ore_magma");
   public static final aix<dtm<?, ?>> b = qm.a("ore_soul_sand");
   public static final aix<dtm<?, ?>> c = qm.a("ore_nether_gold");
   public static final aix<dtm<?, ?>> d = qm.a("ore_quartz");
   public static final aix<dtm<?, ?>> e = qm.a("ore_gravel_nether");
   public static final aix<dtm<?, ?>> f = qm.a("ore_blackstone");
   public static final aix<dtm<?, ?>> g = qm.a("ore_dirt");
   public static final aix<dtm<?, ?>> h = qm.a("ore_gravel");
   public static final aix<dtm<?, ?>> i = qm.a("ore_granite");
   public static final aix<dtm<?, ?>> j = qm.a("ore_diorite");
   public static final aix<dtm<?, ?>> k = qm.a("ore_andesite");
   public static final aix<dtm<?, ?>> l = qm.a("ore_tuff");
   public static final aix<dtm<?, ?>> m = qm.a("ore_coal");
   public static final aix<dtm<?, ?>> n = qm.a("ore_coal_buried");
   public static final aix<dtm<?, ?>> o = qm.a("ore_iron");
   public static final aix<dtm<?, ?>> p = qm.a("ore_iron_small");
   public static final aix<dtm<?, ?>> q = qm.a("ore_gold");
   public static final aix<dtm<?, ?>> r = qm.a("ore_gold_buried");
   public static final aix<dtm<?, ?>> s = qm.a("ore_redstone");
   public static final aix<dtm<?, ?>> t = qm.a("ore_diamond_small");
   public static final aix<dtm<?, ?>> u = qm.a("ore_diamond_medium");
   public static final aix<dtm<?, ?>> v = qm.a("ore_diamond_large");
   public static final aix<dtm<?, ?>> w = qm.a("ore_diamond_buried");
   public static final aix<dtm<?, ?>> x = qm.a("ore_lapis");
   public static final aix<dtm<?, ?>> y = qm.a("ore_lapis_buried");
   public static final aix<dtm<?, ?>> z = qm.a("ore_infested");
   public static final aix<dtm<?, ?>> A = qm.a("ore_emerald");
   public static final aix<dtm<?, ?>> B = qm.a("ore_ancient_debris_large");
   public static final aix<dtm<?, ?>> C = qm.a("ore_ancient_debris_small");
   public static final aix<dtm<?, ?>> D = qm.a("ore_copper_small");
   public static final aix<dtm<?, ?>> E = qm.a("ore_copper_large");
   public static final aix<dtm<?, ?>> F = qm.a("ore_clay");

   public static void a(ph<dtm<?, ?>> $$0) {
      eff $$1 = new efn(aua.bd);
      eff $$2 = new efn(aua.be);
      eff $$3 = new efn(aua.bf);
      eff $$4 = new eeo(cyu.dV);
      eff $$5 = new efn(aua.bg);
      List<dwl.a> $$6 = List.of(dwl.a($$2, cyu.P.o()), dwl.a($$3, cyu.Q.o()));
      List<dwl.a> $$7 = List.of(dwl.a($$2, cyu.N.o()), dwl.a($$3, cyu.O.o()));
      List<dwl.a> $$8 = List.of(dwl.a($$2, cyu.cx.o()), dwl.a($$3, cyu.cy.o()));
      List<dwl.a> $$9 = List.of(dwl.a($$2, cyu.aR.o()), dwl.a($$3, cyu.aS.o()));
      List<dwl.a> $$10 = List.of(dwl.a($$2, cyu.ra.o()), dwl.a($$3, cyu.rb.o()));
      List<dwl.a> $$11 = List.of(dwl.a($$2, cyu.R.o()), dwl.a($$3, cyu.S.o()));
      qm.a($$0, a, dtz.I, new dwl($$4, cyu.kJ.o(), 33));
      qm.a($$0, b, dtz.I, new dwl($$4, cyu.dW.o(), 12));
      qm.a($$0, c, dtz.I, new dwl($$4, cyu.T.o(), 10));
      qm.a($$0, d, dtz.I, new dwl($$4, cyu.hb.o(), 14));
      qm.a($$0, e, dtz.I, new dwl($$4, cyu.L.o(), 33));
      qm.a($$0, f, dtz.I, new dwl($$4, cyu.pr.o(), 33));
      qm.a($$0, g, dtz.I, new dwl($$1, cyu.j.o(), 33));
      qm.a($$0, h, dtz.I, new dwl($$1, cyu.L.o(), 33));
      qm.a($$0, i, dtz.I, new dwl($$1, cyu.c.o(), 64));
      qm.a($$0, j, dtz.I, new dwl($$1, cyu.e.o(), 64));
      qm.a($$0, k, dtz.I, new dwl($$1, cyu.g.o(), 64));
      qm.a($$0, l, dtz.I, new dwl($$1, cyu.qz.o(), 64));
      qm.a($$0, m, dtz.I, new dwl($$11, 17));
      qm.a($$0, n, dtz.I, new dwl($$11, 17, 0.5F));
      qm.a($$0, o, dtz.I, new dwl($$6, 9));
      qm.a($$0, p, dtz.I, new dwl($$6, 4));
      qm.a($$0, q, dtz.I, new dwl($$7, 9));
      qm.a($$0, r, dtz.I, new dwl($$7, 9, 0.5F));
      qm.a($$0, s, dtz.I, new dwl(List.of(dwl.a($$2, cyu.dI.o()), dwl.a($$3, cyu.dJ.o())), 8));
      qm.a($$0, t, dtz.I, new dwl($$8, 4, 0.5F));
      qm.a($$0, v, dtz.I, new dwl($$8, 12, 0.7F));
      qm.a($$0, w, dtz.I, new dwl($$8, 8, 1.0F));
      qm.a($$0, u, dtz.I, new dwl($$8, 8, 0.5F));
      qm.a($$0, x, dtz.I, new dwl($$9, 7));
      qm.a($$0, y, dtz.I, new dwl($$9, 7, 1.0F));
      qm.a($$0, z, dtz.I, new dwl(List.of(dwl.a($$2, cyu.eN.o()), dwl.a($$3, cyu.td.o())), 9));
      qm.a($$0, A, dtz.I, new dwl(List.of(dwl.a($$2, cyu.fE.o()), dwl.a($$3, cyu.fF.o())), 3));
      qm.a($$0, B, dtz.ae, new dwl($$5, cyu.pj.o(), 3, 1.0F));
      qm.a($$0, C, dtz.ae, new dwl($$5, cyu.pj.o(), 2, 1.0F));
      qm.a($$0, D, dtz.I, new dwl($$10, 10));
      qm.a($$0, E, dtz.I, new dwl($$10, 20));
      qm.a($$0, F, dtz.I, new dwl($$1, cyu.dR.o(), 33));
   }
}
