public class qr {
   public static final ahc<dyd> a = qw.a("monster_room");
   public static final ahc<dyd> b = qw.a("monster_room_deep");
   public static final ahc<dyd> c = qw.a("fossil_upper");
   public static final ahc<dyd> d = qw.a("fossil_lower");
   public static final ahc<dyd> e = qw.a("dripstone_cluster");
   public static final ahc<dyd> f = qw.a("large_dripstone");
   public static final ahc<dyd> g = qw.a("pointed_dripstone");
   public static final ahc<dyd> h = qw.a("underwater_magma");
   public static final ahc<dyd> i = qw.a("glow_lichen");
   public static final ahc<dyd> j = qw.a("rooted_azalea_tree");
   public static final ahc<dyd> k = qw.a("cave_vines");
   public static final ahc<dyd> l = qw.a("lush_caves_vegetation");
   public static final ahc<dyd> m = qw.a("lush_caves_clay");
   public static final ahc<dyd> n = qw.a("lush_caves_ceiling_vegetation");
   public static final ahc<dyd> o = qw.a("spore_blossom");
   public static final ahc<dyd> p = qw.a("classic_vines_cave_feature");
   public static final ahc<dyd> q = qw.a("amethyst_geode");
   public static final ahc<dyd> r = qw.a("sculk_patch_deep_dark");
   public static final ahc<dyd> s = qw.a("sculk_patch_ancient_city");
   public static final ahc<dyd> t = qw.a("sculk_vein");

   public static void a(pc<dyd> $$0) {
      ii<dra<?, ?>> $$1 = $$0.a(ke.aw);
      ih<dra<?, ?>> $$2 = $$1.b(qf.a);
      ih<dra<?, ?>> $$3 = $$1.b(qf.b);
      ih<dra<?, ?>> $$4 = $$1.b(qf.c);
      ih<dra<?, ?>> $$5 = $$1.b(qf.d);
      ih<dra<?, ?>> $$6 = $$1.b(qf.e);
      ih<dra<?, ?>> $$7 = $$1.b(qf.f);
      ih<dra<?, ?>> $$8 = $$1.b(qf.g);
      ih<dra<?, ?>> $$9 = $$1.b(qf.h);
      ih<dra<?, ?>> $$10 = $$1.b(qf.i);
      ih<dra<?, ?>> $$11 = $$1.b(qf.j);
      ih<dra<?, ?>> $$12 = $$1.b(qf.m);
      ih<dra<?, ?>> $$13 = $$1.b(qf.r);
      ih<dra<?, ?>> $$14 = $$1.b(qf.s);
      ih<dra<?, ?>> $$15 = $$1.b(qf.t);
      ih<dra<?, ?>> $$16 = $$1.b(qn.c);
      ih<dra<?, ?>> $$17 = $$1.b(qf.u);
      ih<dra<?, ?>> $$18 = $$1.b(qf.v);
      ih<dra<?, ?>> $$19 = $$1.b(qf.w);
      ih<dra<?, ?>> $$20 = $$1.b(qf.x);
      qw.a($$0, a, $$2, dxw.a(10), dya.a(), dxy.a(dpd.a(0), dpd.b()), dxr.a());
      qw.a($$0, b, $$2, dxw.a(4), dya.a(), dxy.a(dpd.b(6), dpd.a(-1)), dxr.a());
      qw.a($$0, c, $$3, dyj.a(64), dya.a(), dxy.a(dpd.a(0), dpd.b()), dxr.a());
      qw.a($$0, d, $$4, dyj.a(64), dya.a(), dxy.a(dpd.a(), dpd.a(-8)), dxr.a());
      qw.a($$0, e, $$5, dxw.a(bjg.a(48, 96)), dya.a(), qw.i, dxr.a());
      qw.a($$0, f, $$6, dxw.a(bjg.a(10, 48)), dya.a(), qw.i, dxr.a());
      qw.a($$0, g, $$7, dxw.a(bjg.a(192, 256)), dya.a(), qw.i, dxw.a(bjg.a(1, 5)), dyi.a(biv.a(0.0F, 3.0F, -10, 10), biv.a(0.0F, 0.6F, -2, 2)), dxr.a());
      qw.a($$0, h, $$8, dxw.a(bjg.a(44, 52)), dya.a(), qw.i, dyl.a(doj.a.c, Integer.MIN_VALUE, -2), dxr.a());
      qw.a($$0, i, $$9, dxw.a(bjg.a(104, 157)), qw.i, dya.a(), dyl.a(doj.a.c, Integer.MIN_VALUE, -13), dxr.a());
      qw.a($$0, j, $$10, dxw.a(bjg.a(1, 2)), dya.a(), qw.i, dxx.a(ic.b, dpq.c(), dpq.c, 12), dyi.a(bix.a(-1)), dxr.a());
      qw.a($$0, k, $$11, dxw.a(188), dya.a(), qw.i, dxx.a(ic.b, dpq.a(ic.a), dpq.c, 12), dyi.a(bix.a(-1)), dxr.a());
      qw.a($$0, l, $$12, dxw.a(125), dya.a(), qw.i, dxx.a(ic.a, dpq.c(), dpq.c, 12), dyi.a(bix.a(1)), dxr.a());
      qw.a($$0, m, $$13, dxw.a(62), dya.a(), qw.i, dxx.a(ic.a, dpq.c(), dpq.c, 12), dyi.a(bix.a(1)), dxr.a());
      qw.a($$0, n, $$14, dxw.a(125), dya.a(), qw.i, dxx.a(ic.b, dpq.c(), dpq.c, 12), dyi.a(bix.a(-1)), dxr.a());
      qw.a($$0, o, $$15, dxw.a(25), dya.a(), qw.i, dxx.a(ic.b, dpq.c(), dpq.c, 12), dyi.a(bix.a(-1)), dxr.a());
      qw.a($$0, p, $$16, dxw.a(256), dya.a(), qw.i, dxr.a());
      qw.a($$0, q, $$17, dyj.a(24), dya.a(), dxy.a(dpd.b(6), dpd.a(30)), dxr.a());
      qw.a($$0, r, $$18, dxw.a(bix.a(256)), dya.a(), qw.i, dxr.a());
      qw.a($$0, s, $$19);
      qw.a($$0, t, $$20, dxw.a(bjg.a(204, 250)), dya.a(), qw.i, dxr.a());
   }
}
