public class qt {
   public static final ahf<dyj> a = qy.a("monster_room");
   public static final ahf<dyj> b = qy.a("monster_room_deep");
   public static final ahf<dyj> c = qy.a("fossil_upper");
   public static final ahf<dyj> d = qy.a("fossil_lower");
   public static final ahf<dyj> e = qy.a("dripstone_cluster");
   public static final ahf<dyj> f = qy.a("large_dripstone");
   public static final ahf<dyj> g = qy.a("pointed_dripstone");
   public static final ahf<dyj> h = qy.a("underwater_magma");
   public static final ahf<dyj> i = qy.a("glow_lichen");
   public static final ahf<dyj> j = qy.a("rooted_azalea_tree");
   public static final ahf<dyj> k = qy.a("cave_vines");
   public static final ahf<dyj> l = qy.a("lush_caves_vegetation");
   public static final ahf<dyj> m = qy.a("lush_caves_clay");
   public static final ahf<dyj> n = qy.a("lush_caves_ceiling_vegetation");
   public static final ahf<dyj> o = qy.a("spore_blossom");
   public static final ahf<dyj> p = qy.a("classic_vines_cave_feature");
   public static final ahf<dyj> q = qy.a("amethyst_geode");
   public static final ahf<dyj> r = qy.a("sculk_patch_deep_dark");
   public static final ahf<dyj> s = qy.a("sculk_patch_ancient_city");
   public static final ahf<dyj> t = qy.a("sculk_vein");

   public static void a(pe<dyj> $$0) {
      ii<drg<?, ?>> $$1 = $$0.a(ke.aw);
      ih<drg<?, ?>> $$2 = $$1.b(qh.a);
      ih<drg<?, ?>> $$3 = $$1.b(qh.b);
      ih<drg<?, ?>> $$4 = $$1.b(qh.c);
      ih<drg<?, ?>> $$5 = $$1.b(qh.d);
      ih<drg<?, ?>> $$6 = $$1.b(qh.e);
      ih<drg<?, ?>> $$7 = $$1.b(qh.f);
      ih<drg<?, ?>> $$8 = $$1.b(qh.g);
      ih<drg<?, ?>> $$9 = $$1.b(qh.h);
      ih<drg<?, ?>> $$10 = $$1.b(qh.i);
      ih<drg<?, ?>> $$11 = $$1.b(qh.j);
      ih<drg<?, ?>> $$12 = $$1.b(qh.m);
      ih<drg<?, ?>> $$13 = $$1.b(qh.r);
      ih<drg<?, ?>> $$14 = $$1.b(qh.s);
      ih<drg<?, ?>> $$15 = $$1.b(qh.t);
      ih<drg<?, ?>> $$16 = $$1.b(qp.c);
      ih<drg<?, ?>> $$17 = $$1.b(qh.u);
      ih<drg<?, ?>> $$18 = $$1.b(qh.v);
      ih<drg<?, ?>> $$19 = $$1.b(qh.w);
      ih<drg<?, ?>> $$20 = $$1.b(qh.x);
      qy.a($$0, a, $$2, dyc.a(10), dyg.a(), dye.a(dpj.a(0), dpj.b()), dxx.a());
      qy.a($$0, b, $$2, dyc.a(4), dyg.a(), dye.a(dpj.b(6), dpj.a(-1)), dxx.a());
      qy.a($$0, c, $$3, dyp.a(64), dyg.a(), dye.a(dpj.a(0), dpj.b()), dxx.a());
      qy.a($$0, d, $$4, dyp.a(64), dyg.a(), dye.a(dpj.a(), dpj.a(-8)), dxx.a());
      qy.a($$0, e, $$5, dyc.a(bjl.a(48, 96)), dyg.a(), qy.i, dxx.a());
      qy.a($$0, f, $$6, dyc.a(bjl.a(10, 48)), dyg.a(), qy.i, dxx.a());
      qy.a($$0, g, $$7, dyc.a(bjl.a(192, 256)), dyg.a(), qy.i, dyc.a(bjl.a(1, 5)), dyo.a(bja.a(0.0F, 3.0F, -10, 10), bja.a(0.0F, 0.6F, -2, 2)), dxx.a());
      qy.a($$0, h, $$8, dyc.a(bjl.a(44, 52)), dyg.a(), qy.i, dyr.a(dop.a.c, Integer.MIN_VALUE, -2), dxx.a());
      qy.a($$0, i, $$9, dyc.a(bjl.a(104, 157)), qy.i, dyg.a(), dyr.a(dop.a.c, Integer.MIN_VALUE, -13), dxx.a());
      qy.a($$0, j, $$10, dyc.a(bjl.a(1, 2)), dyg.a(), qy.i, dyd.a(ic.b, dpw.c(), dpw.c, 12), dyo.a(bjc.a(-1)), dxx.a());
      qy.a($$0, k, $$11, dyc.a(188), dyg.a(), qy.i, dyd.a(ic.b, dpw.a(ic.a), dpw.c, 12), dyo.a(bjc.a(-1)), dxx.a());
      qy.a($$0, l, $$12, dyc.a(125), dyg.a(), qy.i, dyd.a(ic.a, dpw.c(), dpw.c, 12), dyo.a(bjc.a(1)), dxx.a());
      qy.a($$0, m, $$13, dyc.a(62), dyg.a(), qy.i, dyd.a(ic.a, dpw.c(), dpw.c, 12), dyo.a(bjc.a(1)), dxx.a());
      qy.a($$0, n, $$14, dyc.a(125), dyg.a(), qy.i, dyd.a(ic.b, dpw.c(), dpw.c, 12), dyo.a(bjc.a(-1)), dxx.a());
      qy.a($$0, o, $$15, dyc.a(25), dyg.a(), qy.i, dyd.a(ic.b, dpw.c(), dpw.c, 12), dyo.a(bjc.a(-1)), dxx.a());
      qy.a($$0, p, $$16, dyc.a(256), dyg.a(), qy.i, dxx.a());
      qy.a($$0, q, $$17, dyp.a(24), dyg.a(), dye.a(dpj.b(6), dpj.a(30)), dxx.a());
      qy.a($$0, r, $$18, dyc.a(bjc.a(256)), dyg.a(), qy.i, dxx.a());
      qy.a($$0, s, $$19);
      qy.a($$0, t, $$20, dyc.a(bjl.a(204, 250)), dyg.a(), qy.i, dxx.a());
   }
}
