import java.util.List;

public class qt {
   public static final ajg<dvd<?, ?>> a = qq.a("ore_magma");
   public static final ajg<dvd<?, ?>> b = qq.a("ore_soul_sand");
   public static final ajg<dvd<?, ?>> c = qq.a("ore_nether_gold");
   public static final ajg<dvd<?, ?>> d = qq.a("ore_quartz");
   public static final ajg<dvd<?, ?>> e = qq.a("ore_gravel_nether");
   public static final ajg<dvd<?, ?>> f = qq.a("ore_blackstone");
   public static final ajg<dvd<?, ?>> g = qq.a("ore_dirt");
   public static final ajg<dvd<?, ?>> h = qq.a("ore_gravel");
   public static final ajg<dvd<?, ?>> i = qq.a("ore_granite");
   public static final ajg<dvd<?, ?>> j = qq.a("ore_diorite");
   public static final ajg<dvd<?, ?>> k = qq.a("ore_andesite");
   public static final ajg<dvd<?, ?>> l = qq.a("ore_tuff");
   public static final ajg<dvd<?, ?>> m = qq.a("ore_coal");
   public static final ajg<dvd<?, ?>> n = qq.a("ore_coal_buried");
   public static final ajg<dvd<?, ?>> o = qq.a("ore_iron");
   public static final ajg<dvd<?, ?>> p = qq.a("ore_iron_small");
   public static final ajg<dvd<?, ?>> q = qq.a("ore_gold");
   public static final ajg<dvd<?, ?>> r = qq.a("ore_gold_buried");
   public static final ajg<dvd<?, ?>> s = qq.a("ore_redstone");
   public static final ajg<dvd<?, ?>> t = qq.a("ore_diamond_small");
   public static final ajg<dvd<?, ?>> u = qq.a("ore_diamond_medium");
   public static final ajg<dvd<?, ?>> v = qq.a("ore_diamond_large");
   public static final ajg<dvd<?, ?>> w = qq.a("ore_diamond_buried");
   public static final ajg<dvd<?, ?>> x = qq.a("ore_lapis");
   public static final ajg<dvd<?, ?>> y = qq.a("ore_lapis_buried");
   public static final ajg<dvd<?, ?>> z = qq.a("ore_infested");
   public static final ajg<dvd<?, ?>> A = qq.a("ore_emerald");
   public static final ajg<dvd<?, ?>> B = qq.a("ore_ancient_debris_large");
   public static final ajg<dvd<?, ?>> C = qq.a("ore_ancient_debris_small");
   public static final ajg<dvd<?, ?>> D = qq.a("ore_copper_small");
   public static final ajg<dvd<?, ?>> E = qq.a("ore_copper_large");
   public static final ajg<dvd<?, ?>> F = qq.a("ore_clay");

   public static void a(pl<dvd<?, ?>> $$0) {
      egw $$1 = new ehe(aun.be);
      egw $$2 = new ehe(aun.bf);
      egw $$3 = new ehe(aun.bg);
      egw $$4 = new egf(dac.dV);
      egw $$5 = new ehe(aun.bh);
      List<dyc.a> $$6 = List.of(dyc.a($$2, dac.P.o()), dyc.a($$3, dac.Q.o()));
      List<dyc.a> $$7 = List.of(dyc.a($$2, dac.N.o()), dyc.a($$3, dac.O.o()));
      List<dyc.a> $$8 = List.of(dyc.a($$2, dac.cx.o()), dyc.a($$3, dac.cy.o()));
      List<dyc.a> $$9 = List.of(dyc.a($$2, dac.aR.o()), dyc.a($$3, dac.aS.o()));
      List<dyc.a> $$10 = List.of(dyc.a($$2, dac.ra.o()), dyc.a($$3, dac.rb.o()));
      List<dyc.a> $$11 = List.of(dyc.a($$2, dac.R.o()), dyc.a($$3, dac.S.o()));
      qq.a($$0, a, dvq.I, new dyc($$4, dac.kJ.o(), 33));
      qq.a($$0, b, dvq.I, new dyc($$4, dac.dW.o(), 12));
      qq.a($$0, c, dvq.I, new dyc($$4, dac.T.o(), 10));
      qq.a($$0, d, dvq.I, new dyc($$4, dac.hb.o(), 14));
      qq.a($$0, e, dvq.I, new dyc($$4, dac.L.o(), 33));
      qq.a($$0, f, dvq.I, new dyc($$4, dac.pr.o(), 33));
      qq.a($$0, g, dvq.I, new dyc($$1, dac.j.o(), 33));
      qq.a($$0, h, dvq.I, new dyc($$1, dac.L.o(), 33));
      qq.a($$0, i, dvq.I, new dyc($$1, dac.c.o(), 64));
      qq.a($$0, j, dvq.I, new dyc($$1, dac.e.o(), 64));
      qq.a($$0, k, dvq.I, new dyc($$1, dac.g.o(), 64));
      qq.a($$0, l, dvq.I, new dyc($$1, dac.qz.o(), 64));
      qq.a($$0, m, dvq.I, new dyc($$11, 17));
      qq.a($$0, n, dvq.I, new dyc($$11, 17, 0.5F));
      qq.a($$0, o, dvq.I, new dyc($$6, 9));
      qq.a($$0, p, dvq.I, new dyc($$6, 4));
      qq.a($$0, q, dvq.I, new dyc($$7, 9));
      qq.a($$0, r, dvq.I, new dyc($$7, 9, 0.5F));
      qq.a($$0, s, dvq.I, new dyc(List.of(dyc.a($$2, dac.dI.o()), dyc.a($$3, dac.dJ.o())), 8));
      qq.a($$0, t, dvq.I, new dyc($$8, 4, 0.5F));
      qq.a($$0, v, dvq.I, new dyc($$8, 12, 0.7F));
      qq.a($$0, w, dvq.I, new dyc($$8, 8, 1.0F));
      qq.a($$0, u, dvq.I, new dyc($$8, 8, 0.5F));
      qq.a($$0, x, dvq.I, new dyc($$9, 7));
      qq.a($$0, y, dvq.I, new dyc($$9, 7, 1.0F));
      qq.a($$0, z, dvq.I, new dyc(List.of(dyc.a($$2, dac.eN.o()), dyc.a($$3, dac.td.o())), 9));
      qq.a($$0, A, dvq.I, new dyc(List.of(dyc.a($$2, dac.fE.o()), dyc.a($$3, dac.fF.o())), 3));
      qq.a($$0, B, dvq.ae, new dyc($$5, dac.pj.o(), 3, 1.0F));
      qq.a($$0, C, dvq.ae, new dyc($$5, dac.pj.o(), 2, 1.0F));
      qq.a($$0, D, dvq.I, new dyc($$10, 10));
      qq.a($$0, E, dvq.I, new dyc($$10, 20));
      qq.a($$0, F, dvq.I, new dyc($$1, dac.dR.o(), 33));
   }
}
