public class qw {
   public static final aix<eai> a = rb.a("monster_room");
   public static final aix<eai> b = rb.a("monster_room_deep");
   public static final aix<eai> c = rb.a("fossil_upper");
   public static final aix<eai> d = rb.a("fossil_lower");
   public static final aix<eai> e = rb.a("dripstone_cluster");
   public static final aix<eai> f = rb.a("large_dripstone");
   public static final aix<eai> g = rb.a("pointed_dripstone");
   public static final aix<eai> h = rb.a("underwater_magma");
   public static final aix<eai> i = rb.a("glow_lichen");
   public static final aix<eai> j = rb.a("rooted_azalea_tree");
   public static final aix<eai> k = rb.a("cave_vines");
   public static final aix<eai> l = rb.a("lush_caves_vegetation");
   public static final aix<eai> m = rb.a("lush_caves_clay");
   public static final aix<eai> n = rb.a("lush_caves_ceiling_vegetation");
   public static final aix<eai> o = rb.a("spore_blossom");
   public static final aix<eai> p = rb.a("classic_vines_cave_feature");
   public static final aix<eai> q = rb.a("amethyst_geode");
   public static final aix<eai> r = rb.a("sculk_patch_deep_dark");
   public static final aix<eai> s = rb.a("sculk_patch_ancient_city");
   public static final aix<eai> t = rb.a("sculk_vein");

   public static void a(ph<eai> $$0) {
      ik<dtf<?, ?>> $$1 = $$0.a(kg.aw);
      ij<dtf<?, ?>> $$2 = $$1.b(qk.a);
      ij<dtf<?, ?>> $$3 = $$1.b(qk.b);
      ij<dtf<?, ?>> $$4 = $$1.b(qk.c);
      ij<dtf<?, ?>> $$5 = $$1.b(qk.d);
      ij<dtf<?, ?>> $$6 = $$1.b(qk.e);
      ij<dtf<?, ?>> $$7 = $$1.b(qk.f);
      ij<dtf<?, ?>> $$8 = $$1.b(qk.g);
      ij<dtf<?, ?>> $$9 = $$1.b(qk.h);
      ij<dtf<?, ?>> $$10 = $$1.b(qk.i);
      ij<dtf<?, ?>> $$11 = $$1.b(qk.j);
      ij<dtf<?, ?>> $$12 = $$1.b(qk.m);
      ij<dtf<?, ?>> $$13 = $$1.b(qk.r);
      ij<dtf<?, ?>> $$14 = $$1.b(qk.s);
      ij<dtf<?, ?>> $$15 = $$1.b(qk.t);
      ij<dtf<?, ?>> $$16 = $$1.b(qs.c);
      ij<dtf<?, ?>> $$17 = $$1.b(qk.u);
      ij<dtf<?, ?>> $$18 = $$1.b(qk.v);
      ij<dtf<?, ?>> $$19 = $$1.b(qk.w);
      ij<dtf<?, ?>> $$20 = $$1.b(qk.x);
      rb.a($$0, a, $$2, eab.a(10), eaf.a(), ead.a(dri.a(0), dri.b()), dzw.a());
      rb.a($$0, b, $$2, eab.a(4), eaf.a(), ead.a(dri.b(6), dri.a(-1)), dzw.a());
      rb.a($$0, c, $$3, eao.a(64), eaf.a(), ead.a(dri.a(0), dri.b()), dzw.a());
      rb.a($$0, d, $$4, eao.a(64), eaf.a(), ead.a(dri.a(), dri.a(-8)), dzw.a());
      rb.a($$0, e, $$5, eab.a(blf.a(48, 96)), eaf.a(), rb.i, dzw.a());
      rb.a($$0, f, $$6, eab.a(blf.a(10, 48)), eaf.a(), rb.i, dzw.a());
      rb.a($$0, g, $$7, eab.a(blf.a(192, 256)), eaf.a(), rb.i, eab.a(blf.a(1, 5)), ean.a(bku.a(0.0F, 3.0F, -10, 10), bku.a(0.0F, 0.6F, -2, 2)), dzw.a());
      rb.a($$0, h, $$8, eab.a(blf.a(44, 52)), eaf.a(), rb.i, eaq.a(dqo.a.c, Integer.MIN_VALUE, -2), dzw.a());
      rb.a($$0, i, $$9, eab.a(blf.a(104, 157)), rb.i, eaf.a(), eaq.a(dqo.a.c, Integer.MIN_VALUE, -13), dzw.a());
      rb.a($$0, j, $$10, eab.a(blf.a(1, 2)), eaf.a(), rb.i, eac.a(ie.b, drv.c(), drv.c, 12), ean.a(bkw.a(-1)), dzw.a());
      rb.a($$0, k, $$11, eab.a(188), eaf.a(), rb.i, eac.a(ie.b, drv.a(ie.a), drv.c, 12), ean.a(bkw.a(-1)), dzw.a());
      rb.a($$0, l, $$12, eab.a(125), eaf.a(), rb.i, eac.a(ie.a, drv.c(), drv.c, 12), ean.a(bkw.a(1)), dzw.a());
      rb.a($$0, m, $$13, eab.a(62), eaf.a(), rb.i, eac.a(ie.a, drv.c(), drv.c, 12), ean.a(bkw.a(1)), dzw.a());
      rb.a($$0, n, $$14, eab.a(125), eaf.a(), rb.i, eac.a(ie.b, drv.c(), drv.c, 12), ean.a(bkw.a(-1)), dzw.a());
      rb.a($$0, o, $$15, eab.a(25), eaf.a(), rb.i, eac.a(ie.b, drv.c(), drv.c, 12), ean.a(bkw.a(-1)), dzw.a());
      rb.a($$0, p, $$16, eab.a(256), eaf.a(), rb.i, dzw.a());
      rb.a($$0, q, $$17, eao.a(24), eaf.a(), ead.a(dri.b(6), dri.a(30)), dzw.a());
      rb.a($$0, r, $$18, eab.a(bkw.a(256)), eaf.a(), rb.i, dzw.a());
      rb.a($$0, s, $$19);
      rb.a($$0, t, $$20, eab.a(blf.a(204, 250)), eaf.a(), rb.i, dzw.a());
   }
}
