import java.util.List;

public class qx {
   public static final ahc<dyd> a = qw.a("crimson_fungi");
   public static final ahc<dyd> b = qw.a("warped_fungi");
   public static final ahc<dyd> c = qw.a("oak_checked");
   public static final ahc<dyd> d = qw.a("dark_oak_checked");
   public static final ahc<dyd> e = qw.a("birch_checked");
   public static final ahc<dyd> f = qw.a("acacia_checked");
   public static final ahc<dyd> g = qw.a("spruce_checked");
   public static final ahc<dyd> h = qw.a("mangrove_checked");
   public static final ahc<dyd> i = qw.a("cherry_checked");
   public static final ahc<dyd> j = qw.a("pine_on_snow");
   public static final ahc<dyd> k = qw.a("spruce_on_snow");
   public static final ahc<dyd> l = qw.a("pine_checked");
   public static final ahc<dyd> m = qw.a("jungle_tree");
   public static final ahc<dyd> n = qw.a("fancy_oak_checked");
   public static final ahc<dyd> o = qw.a("mega_jungle_tree_checked");
   public static final ahc<dyd> p = qw.a("mega_spruce_checked");
   public static final ahc<dyd> q = qw.a("mega_pine_checked");
   public static final ahc<dyd> r = qw.a("tall_mangrove_checked");
   public static final ahc<dyd> s = qw.a("jungle_bush");
   public static final ahc<dyd> t = qw.a("super_birch_bees_0002");
   public static final ahc<dyd> u = qw.a("super_birch_bees");
   public static final ahc<dyd> v = qw.a("oak_bees_0002");
   public static final ahc<dyd> w = qw.a("oak_bees_002");
   public static final ahc<dyd> x = qw.a("birch_bees_0002");
   public static final ahc<dyd> y = qw.a("birch_bees_002");
   public static final ahc<dyd> z = qw.a("fancy_oak_bees_0002");
   public static final ahc<dyd> A = qw.a("fancy_oak_bees_002");
   public static final ahc<dyd> B = qw.a("fancy_oak_bees");
   public static final ahc<dyd> C = qw.a("cherry_bees_005");

   public static void a(pc<dyd> $$0) {
      ii<dra<?, ?>> $$1 = $$0.a(ke.aw);
      ih<dra<?, ?>> $$2 = $$1.b(qm.a);
      ih<dra<?, ?>> $$3 = $$1.b(qm.c);
      ih<dra<?, ?>> $$4 = $$1.b(qm.g);
      ih<dra<?, ?>> $$5 = $$1.b(qm.h);
      ih<dra<?, ?>> $$6 = $$1.b(qm.i);
      ih<dra<?, ?>> $$7 = $$1.b(qm.j);
      ih<dra<?, ?>> $$8 = $$1.b(qm.k);
      ih<dra<?, ?>> $$9 = $$1.b(qm.x);
      ih<dra<?, ?>> $$10 = $$1.b(qm.z);
      ih<dra<?, ?>> $$11 = $$1.b(qm.l);
      ih<dra<?, ?>> $$12 = $$1.b(qm.m);
      ih<dra<?, ?>> $$13 = $$1.b(qm.n);
      ih<dra<?, ?>> $$14 = $$1.b(qm.p);
      ih<dra<?, ?>> $$15 = $$1.b(qm.q);
      ih<dra<?, ?>> $$16 = $$1.b(qm.r);
      ih<dra<?, ?>> $$17 = $$1.b(qm.y);
      ih<dra<?, ?>> $$18 = $$1.b(qm.v);
      ih<dra<?, ?>> $$19 = $$1.b(qm.s);
      ih<dra<?, ?>> $$20 = $$1.b(qm.t);
      ih<dra<?, ?>> $$21 = $$1.b(qm.A);
      ih<dra<?, ?>> $$22 = $$1.b(qm.B);
      ih<dra<?, ?>> $$23 = $$1.b(qm.D);
      ih<dra<?, ?>> $$24 = $$1.b(qm.E);
      ih<dra<?, ?>> $$25 = $$1.b(qm.G);
      ih<dra<?, ?>> $$26 = $$1.b(qm.H);
      ih<dra<?, ?>> $$27 = $$1.b(qm.J);
      ih<dra<?, ?>> $$28 = $$1.b(qm.K);
      qw.a($$0, a, $$2, dxv.a(8), dxr.a());
      qw.a($$0, b, $$3, dxv.a(8), dxr.a());
      qw.a($$0, c, $$4, qw.a(cwl.x));
      qw.a($$0, d, $$5, qw.a(cwl.D));
      qw.a($$0, e, $$6, qw.a(cwl.z));
      qw.a($$0, f, $$7, qw.a(cwl.B));
      qw.a($$0, g, $$8, qw.a(cwl.y));
      qw.a($$0, h, $$9, qw.a(cwl.E));
      qw.a($$0, i, $$10, qw.a(cwl.C));
      dpq $$29 = dpq.a(ic.a.q(), cwl.dP, cwl.qP);
      List<dyg> $$30 = List.of(dxx.a(ic.b, dpq.a(dpq.a(cwl.qP)), 8), dxs.a($$29));
      qw.a($$0, j, $$11, $$30);
      qw.a($$0, k, $$8, $$30);
      qw.a($$0, l, $$11, qw.a(cwl.y));
      qw.a($$0, m, $$12, qw.a(cwl.A));
      qw.a($$0, n, $$13, qw.a(cwl.x));
      qw.a($$0, o, $$14, qw.a(cwl.A));
      qw.a($$0, p, $$15, qw.a(cwl.y));
      qw.a($$0, q, $$16, qw.a(cwl.y));
      qw.a($$0, r, $$17, qw.a(cwl.E));
      qw.a($$0, s, $$18, qw.a(cwl.x));
      qw.a($$0, t, $$19, qw.a(cwl.z));
      qw.a($$0, u, $$20, qw.a(cwl.z));
      qw.a($$0, v, $$21, qw.a(cwl.x));
      qw.a($$0, w, $$22, qw.a(cwl.x));
      qw.a($$0, x, $$23, qw.a(cwl.z));
      qw.a($$0, y, $$24, qw.a(cwl.z));
      qw.a($$0, z, $$25, qw.a(cwl.x));
      qw.a($$0, A, $$26, qw.a(cwl.x));
      qw.a($$0, B, $$27, qw.a(cwl.x));
      qw.a($$0, C, $$28, qw.a(cwl.C));
   }
}
