import java.util.List;

public class qz {
   public static final ahf<dyj> a = qy.a("crimson_fungi");
   public static final ahf<dyj> b = qy.a("warped_fungi");
   public static final ahf<dyj> c = qy.a("oak_checked");
   public static final ahf<dyj> d = qy.a("dark_oak_checked");
   public static final ahf<dyj> e = qy.a("birch_checked");
   public static final ahf<dyj> f = qy.a("acacia_checked");
   public static final ahf<dyj> g = qy.a("spruce_checked");
   public static final ahf<dyj> h = qy.a("mangrove_checked");
   public static final ahf<dyj> i = qy.a("cherry_checked");
   public static final ahf<dyj> j = qy.a("pine_on_snow");
   public static final ahf<dyj> k = qy.a("spruce_on_snow");
   public static final ahf<dyj> l = qy.a("pine_checked");
   public static final ahf<dyj> m = qy.a("jungle_tree");
   public static final ahf<dyj> n = qy.a("fancy_oak_checked");
   public static final ahf<dyj> o = qy.a("mega_jungle_tree_checked");
   public static final ahf<dyj> p = qy.a("mega_spruce_checked");
   public static final ahf<dyj> q = qy.a("mega_pine_checked");
   public static final ahf<dyj> r = qy.a("tall_mangrove_checked");
   public static final ahf<dyj> s = qy.a("jungle_bush");
   public static final ahf<dyj> t = qy.a("super_birch_bees_0002");
   public static final ahf<dyj> u = qy.a("super_birch_bees");
   public static final ahf<dyj> v = qy.a("oak_bees_0002");
   public static final ahf<dyj> w = qy.a("oak_bees_002");
   public static final ahf<dyj> x = qy.a("birch_bees_0002");
   public static final ahf<dyj> y = qy.a("birch_bees_002");
   public static final ahf<dyj> z = qy.a("fancy_oak_bees_0002");
   public static final ahf<dyj> A = qy.a("fancy_oak_bees_002");
   public static final ahf<dyj> B = qy.a("fancy_oak_bees");
   public static final ahf<dyj> C = qy.a("cherry_bees_005");

   public static void a(pe<dyj> $$0) {
      ii<drg<?, ?>> $$1 = $$0.a(ke.aw);
      ih<drg<?, ?>> $$2 = $$1.b(qo.a);
      ih<drg<?, ?>> $$3 = $$1.b(qo.c);
      ih<drg<?, ?>> $$4 = $$1.b(qo.g);
      ih<drg<?, ?>> $$5 = $$1.b(qo.h);
      ih<drg<?, ?>> $$6 = $$1.b(qo.i);
      ih<drg<?, ?>> $$7 = $$1.b(qo.j);
      ih<drg<?, ?>> $$8 = $$1.b(qo.k);
      ih<drg<?, ?>> $$9 = $$1.b(qo.x);
      ih<drg<?, ?>> $$10 = $$1.b(qo.z);
      ih<drg<?, ?>> $$11 = $$1.b(qo.l);
      ih<drg<?, ?>> $$12 = $$1.b(qo.m);
      ih<drg<?, ?>> $$13 = $$1.b(qo.n);
      ih<drg<?, ?>> $$14 = $$1.b(qo.p);
      ih<drg<?, ?>> $$15 = $$1.b(qo.q);
      ih<drg<?, ?>> $$16 = $$1.b(qo.r);
      ih<drg<?, ?>> $$17 = $$1.b(qo.y);
      ih<drg<?, ?>> $$18 = $$1.b(qo.v);
      ih<drg<?, ?>> $$19 = $$1.b(qo.s);
      ih<drg<?, ?>> $$20 = $$1.b(qo.t);
      ih<drg<?, ?>> $$21 = $$1.b(qo.A);
      ih<drg<?, ?>> $$22 = $$1.b(qo.B);
      ih<drg<?, ?>> $$23 = $$1.b(qo.D);
      ih<drg<?, ?>> $$24 = $$1.b(qo.E);
      ih<drg<?, ?>> $$25 = $$1.b(qo.G);
      ih<drg<?, ?>> $$26 = $$1.b(qo.H);
      ih<drg<?, ?>> $$27 = $$1.b(qo.J);
      ih<drg<?, ?>> $$28 = $$1.b(qo.K);
      qy.a($$0, a, $$2, dyb.a(8), dxx.a());
      qy.a($$0, b, $$3, dyb.a(8), dxx.a());
      qy.a($$0, c, $$4, qy.a(cwr.x));
      qy.a($$0, d, $$5, qy.a(cwr.D));
      qy.a($$0, e, $$6, qy.a(cwr.z));
      qy.a($$0, f, $$7, qy.a(cwr.B));
      qy.a($$0, g, $$8, qy.a(cwr.y));
      qy.a($$0, h, $$9, qy.a(cwr.E));
      qy.a($$0, i, $$10, qy.a(cwr.C));
      dpw $$29 = dpw.a(ic.a.q(), cwr.dP, cwr.qP);
      List<dym> $$30 = List.of(dyd.a(ic.b, dpw.a(dpw.a(cwr.qP)), 8), dxy.a($$29));
      qy.a($$0, j, $$11, $$30);
      qy.a($$0, k, $$8, $$30);
      qy.a($$0, l, $$11, qy.a(cwr.y));
      qy.a($$0, m, $$12, qy.a(cwr.A));
      qy.a($$0, n, $$13, qy.a(cwr.x));
      qy.a($$0, o, $$14, qy.a(cwr.A));
      qy.a($$0, p, $$15, qy.a(cwr.y));
      qy.a($$0, q, $$16, qy.a(cwr.y));
      qy.a($$0, r, $$17, qy.a(cwr.E));
      qy.a($$0, s, $$18, qy.a(cwr.x));
      qy.a($$0, t, $$19, qy.a(cwr.z));
      qy.a($$0, u, $$20, qy.a(cwr.z));
      qy.a($$0, v, $$21, qy.a(cwr.x));
      qy.a($$0, w, $$22, qy.a(cwr.x));
      qy.a($$0, x, $$23, qy.a(cwr.z));
      qy.a($$0, y, $$24, qy.a(cwr.z));
      qy.a($$0, z, $$25, qy.a(cwr.x));
      qy.a($$0, A, $$26, qy.a(cwr.x));
      qy.a($$0, B, $$27, qy.a(cwr.x));
      qy.a($$0, C, $$28, qy.a(cwr.C));
   }
}
