import java.util.List;

public class ra {
   public static final ahg<dys> a = qz.a("crimson_fungi");
   public static final ahg<dys> b = qz.a("warped_fungi");
   public static final ahg<dys> c = qz.a("oak_checked");
   public static final ahg<dys> d = qz.a("dark_oak_checked");
   public static final ahg<dys> e = qz.a("birch_checked");
   public static final ahg<dys> f = qz.a("acacia_checked");
   public static final ahg<dys> g = qz.a("spruce_checked");
   public static final ahg<dys> h = qz.a("mangrove_checked");
   public static final ahg<dys> i = qz.a("cherry_checked");
   public static final ahg<dys> j = qz.a("pine_on_snow");
   public static final ahg<dys> k = qz.a("spruce_on_snow");
   public static final ahg<dys> l = qz.a("pine_checked");
   public static final ahg<dys> m = qz.a("jungle_tree");
   public static final ahg<dys> n = qz.a("fancy_oak_checked");
   public static final ahg<dys> o = qz.a("mega_jungle_tree_checked");
   public static final ahg<dys> p = qz.a("mega_spruce_checked");
   public static final ahg<dys> q = qz.a("mega_pine_checked");
   public static final ahg<dys> r = qz.a("tall_mangrove_checked");
   public static final ahg<dys> s = qz.a("jungle_bush");
   public static final ahg<dys> t = qz.a("super_birch_bees_0002");
   public static final ahg<dys> u = qz.a("super_birch_bees");
   public static final ahg<dys> v = qz.a("oak_bees_0002");
   public static final ahg<dys> w = qz.a("oak_bees_002");
   public static final ahg<dys> x = qz.a("birch_bees_0002");
   public static final ahg<dys> y = qz.a("birch_bees_002");
   public static final ahg<dys> z = qz.a("fancy_oak_bees_0002");
   public static final ahg<dys> A = qz.a("fancy_oak_bees_002");
   public static final ahg<dys> B = qz.a("fancy_oak_bees");
   public static final ahg<dys> C = qz.a("cherry_bees_005");

   public static void a(pf<dys> $$0) {
      ii<drp<?, ?>> $$1 = $$0.a(ke.aw);
      ih<drp<?, ?>> $$2 = $$1.b(qp.a);
      ih<drp<?, ?>> $$3 = $$1.b(qp.c);
      ih<drp<?, ?>> $$4 = $$1.b(qp.g);
      ih<drp<?, ?>> $$5 = $$1.b(qp.h);
      ih<drp<?, ?>> $$6 = $$1.b(qp.i);
      ih<drp<?, ?>> $$7 = $$1.b(qp.j);
      ih<drp<?, ?>> $$8 = $$1.b(qp.k);
      ih<drp<?, ?>> $$9 = $$1.b(qp.x);
      ih<drp<?, ?>> $$10 = $$1.b(qp.z);
      ih<drp<?, ?>> $$11 = $$1.b(qp.l);
      ih<drp<?, ?>> $$12 = $$1.b(qp.m);
      ih<drp<?, ?>> $$13 = $$1.b(qp.n);
      ih<drp<?, ?>> $$14 = $$1.b(qp.p);
      ih<drp<?, ?>> $$15 = $$1.b(qp.q);
      ih<drp<?, ?>> $$16 = $$1.b(qp.r);
      ih<drp<?, ?>> $$17 = $$1.b(qp.y);
      ih<drp<?, ?>> $$18 = $$1.b(qp.v);
      ih<drp<?, ?>> $$19 = $$1.b(qp.s);
      ih<drp<?, ?>> $$20 = $$1.b(qp.t);
      ih<drp<?, ?>> $$21 = $$1.b(qp.A);
      ih<drp<?, ?>> $$22 = $$1.b(qp.B);
      ih<drp<?, ?>> $$23 = $$1.b(qp.D);
      ih<drp<?, ?>> $$24 = $$1.b(qp.E);
      ih<drp<?, ?>> $$25 = $$1.b(qp.G);
      ih<drp<?, ?>> $$26 = $$1.b(qp.H);
      ih<drp<?, ?>> $$27 = $$1.b(qp.J);
      ih<drp<?, ?>> $$28 = $$1.b(qp.K);
      qz.a($$0, a, $$2, dyk.a(8), dyg.a());
      qz.a($$0, b, $$3, dyk.a(8), dyg.a());
      qz.a($$0, c, $$4, qz.a(cxa.x));
      qz.a($$0, d, $$5, qz.a(cxa.D));
      qz.a($$0, e, $$6, qz.a(cxa.z));
      qz.a($$0, f, $$7, qz.a(cxa.B));
      qz.a($$0, g, $$8, qz.a(cxa.y));
      qz.a($$0, h, $$9, qz.a(cxa.E));
      qz.a($$0, i, $$10, qz.a(cxa.C));
      dqf $$29 = dqf.a(ic.a.q(), cxa.dP, cxa.qP);
      List<dyv> $$30 = List.of(dym.a(ic.b, dqf.a(dqf.a(cxa.qP)), 8), dyh.a($$29));
      qz.a($$0, j, $$11, $$30);
      qz.a($$0, k, $$8, $$30);
      qz.a($$0, l, $$11, qz.a(cxa.y));
      qz.a($$0, m, $$12, qz.a(cxa.A));
      qz.a($$0, n, $$13, qz.a(cxa.x));
      qz.a($$0, o, $$14, qz.a(cxa.A));
      qz.a($$0, p, $$15, qz.a(cxa.y));
      qz.a($$0, q, $$16, qz.a(cxa.y));
      qz.a($$0, r, $$17, qz.a(cxa.E));
      qz.a($$0, s, $$18, qz.a(cxa.x));
      qz.a($$0, t, $$19, qz.a(cxa.z));
      qz.a($$0, u, $$20, qz.a(cxa.z));
      qz.a($$0, v, $$21, qz.a(cxa.x));
      qz.a($$0, w, $$22, qz.a(cxa.x));
      qz.a($$0, x, $$23, qz.a(cxa.z));
      qz.a($$0, y, $$24, qz.a(cxa.z));
      qz.a($$0, z, $$25, qz.a(cxa.x));
      qz.a($$0, A, $$26, qz.a(cxa.x));
      qz.a($$0, B, $$27, qz.a(cxa.x));
      qz.a($$0, C, $$28, qz.a(cxa.C));
   }
}
