import java.util.List;

public class rc {
   public static final aix<eap> a = rb.a("crimson_fungi");
   public static final aix<eap> b = rb.a("warped_fungi");
   public static final aix<eap> c = rb.a("oak_checked");
   public static final aix<eap> d = rb.a("dark_oak_checked");
   public static final aix<eap> e = rb.a("birch_checked");
   public static final aix<eap> f = rb.a("acacia_checked");
   public static final aix<eap> g = rb.a("spruce_checked");
   public static final aix<eap> h = rb.a("mangrove_checked");
   public static final aix<eap> i = rb.a("cherry_checked");
   public static final aix<eap> j = rb.a("pine_on_snow");
   public static final aix<eap> k = rb.a("spruce_on_snow");
   public static final aix<eap> l = rb.a("pine_checked");
   public static final aix<eap> m = rb.a("jungle_tree");
   public static final aix<eap> n = rb.a("fancy_oak_checked");
   public static final aix<eap> o = rb.a("mega_jungle_tree_checked");
   public static final aix<eap> p = rb.a("mega_spruce_checked");
   public static final aix<eap> q = rb.a("mega_pine_checked");
   public static final aix<eap> r = rb.a("tall_mangrove_checked");
   public static final aix<eap> s = rb.a("jungle_bush");
   public static final aix<eap> t = rb.a("super_birch_bees_0002");
   public static final aix<eap> u = rb.a("super_birch_bees");
   public static final aix<eap> v = rb.a("oak_bees_0002");
   public static final aix<eap> w = rb.a("oak_bees_002");
   public static final aix<eap> x = rb.a("birch_bees_0002");
   public static final aix<eap> y = rb.a("birch_bees_002");
   public static final aix<eap> z = rb.a("fancy_oak_bees_0002");
   public static final aix<eap> A = rb.a("fancy_oak_bees_002");
   public static final aix<eap> B = rb.a("fancy_oak_bees");
   public static final aix<eap> C = rb.a("cherry_bees_005");

   public static void a(ph<eap> $$0) {
      ik<dtm<?, ?>> $$1 = $$0.a(kg.aw);
      ij<dtm<?, ?>> $$2 = $$1.b(qr.a);
      ij<dtm<?, ?>> $$3 = $$1.b(qr.c);
      ij<dtm<?, ?>> $$4 = $$1.b(qr.g);
      ij<dtm<?, ?>> $$5 = $$1.b(qr.h);
      ij<dtm<?, ?>> $$6 = $$1.b(qr.i);
      ij<dtm<?, ?>> $$7 = $$1.b(qr.j);
      ij<dtm<?, ?>> $$8 = $$1.b(qr.k);
      ij<dtm<?, ?>> $$9 = $$1.b(qr.x);
      ij<dtm<?, ?>> $$10 = $$1.b(qr.z);
      ij<dtm<?, ?>> $$11 = $$1.b(qr.l);
      ij<dtm<?, ?>> $$12 = $$1.b(qr.m);
      ij<dtm<?, ?>> $$13 = $$1.b(qr.n);
      ij<dtm<?, ?>> $$14 = $$1.b(qr.p);
      ij<dtm<?, ?>> $$15 = $$1.b(qr.q);
      ij<dtm<?, ?>> $$16 = $$1.b(qr.r);
      ij<dtm<?, ?>> $$17 = $$1.b(qr.y);
      ij<dtm<?, ?>> $$18 = $$1.b(qr.v);
      ij<dtm<?, ?>> $$19 = $$1.b(qr.s);
      ij<dtm<?, ?>> $$20 = $$1.b(qr.t);
      ij<dtm<?, ?>> $$21 = $$1.b(qr.A);
      ij<dtm<?, ?>> $$22 = $$1.b(qr.B);
      ij<dtm<?, ?>> $$23 = $$1.b(qr.D);
      ij<dtm<?, ?>> $$24 = $$1.b(qr.E);
      ij<dtm<?, ?>> $$25 = $$1.b(qr.G);
      ij<dtm<?, ?>> $$26 = $$1.b(qr.H);
      ij<dtm<?, ?>> $$27 = $$1.b(qr.J);
      ij<dtm<?, ?>> $$28 = $$1.b(qr.K);
      rb.a($$0, a, $$2, eah.a(8), ead.a());
      rb.a($$0, b, $$3, eah.a(8), ead.a());
      rb.a($$0, c, $$4, rb.a(cyu.x));
      rb.a($$0, d, $$5, rb.a(cyu.D));
      rb.a($$0, e, $$6, rb.a(cyu.z));
      rb.a($$0, f, $$7, rb.a(cyu.B));
      rb.a($$0, g, $$8, rb.a(cyu.y));
      rb.a($$0, h, $$9, rb.a(cyu.E));
      rb.a($$0, i, $$10, rb.a(cyu.C));
      dsc $$29 = dsc.a(ie.a.q(), cyu.dP, cyu.qP);
      List<eas> $$30 = List.of(eaj.a(ie.b, dsc.a(dsc.a(cyu.qP)), 8), eae.a($$29));
      rb.a($$0, j, $$11, $$30);
      rb.a($$0, k, $$8, $$30);
      rb.a($$0, l, $$11, rb.a(cyu.y));
      rb.a($$0, m, $$12, rb.a(cyu.A));
      rb.a($$0, n, $$13, rb.a(cyu.x));
      rb.a($$0, o, $$14, rb.a(cyu.A));
      rb.a($$0, p, $$15, rb.a(cyu.y));
      rb.a($$0, q, $$16, rb.a(cyu.y));
      rb.a($$0, r, $$17, rb.a(cyu.E));
      rb.a($$0, s, $$18, rb.a(cyu.x));
      rb.a($$0, t, $$19, rb.a(cyu.z));
      rb.a($$0, u, $$20, rb.a(cyu.z));
      rb.a($$0, v, $$21, rb.a(cyu.x));
      rb.a($$0, w, $$22, rb.a(cyu.x));
      rb.a($$0, x, $$23, rb.a(cyu.z));
      rb.a($$0, y, $$24, rb.a(cyu.z));
      rb.a($$0, z, $$25, rb.a(cyu.x));
      rb.a($$0, A, $$26, rb.a(cyu.x));
      rb.a($$0, B, $$27, rb.a(cyu.x));
      rb.a($$0, C, $$28, rb.a(cyu.C));
   }
}
