import java.util.List;

public class re {
   public static final ajb<ebk> a = rd.a("crimson_fungi");
   public static final ajb<ebk> b = rd.a("warped_fungi");
   public static final ajb<ebk> c = rd.a("oak_checked");
   public static final ajb<ebk> d = rd.a("dark_oak_checked");
   public static final ajb<ebk> e = rd.a("birch_checked");
   public static final ajb<ebk> f = rd.a("acacia_checked");
   public static final ajb<ebk> g = rd.a("spruce_checked");
   public static final ajb<ebk> h = rd.a("mangrove_checked");
   public static final ajb<ebk> i = rd.a("cherry_checked");
   public static final ajb<ebk> j = rd.a("pine_on_snow");
   public static final ajb<ebk> k = rd.a("spruce_on_snow");
   public static final ajb<ebk> l = rd.a("pine_checked");
   public static final ajb<ebk> m = rd.a("jungle_tree");
   public static final ajb<ebk> n = rd.a("fancy_oak_checked");
   public static final ajb<ebk> o = rd.a("mega_jungle_tree_checked");
   public static final ajb<ebk> p = rd.a("mega_spruce_checked");
   public static final ajb<ebk> q = rd.a("mega_pine_checked");
   public static final ajb<ebk> r = rd.a("tall_mangrove_checked");
   public static final ajb<ebk> s = rd.a("jungle_bush");
   public static final ajb<ebk> t = rd.a("super_birch_bees_0002");
   public static final ajb<ebk> u = rd.a("super_birch_bees");
   public static final ajb<ebk> v = rd.a("oak_bees_0002");
   public static final ajb<ebk> w = rd.a("oak_bees_002");
   public static final ajb<ebk> x = rd.a("birch_bees_0002");
   public static final ajb<ebk> y = rd.a("birch_bees_002");
   public static final ajb<ebk> z = rd.a("fancy_oak_bees_0002");
   public static final ajb<ebk> A = rd.a("fancy_oak_bees_002");
   public static final ajb<ebk> B = rd.a("fancy_oak_bees");
   public static final ajb<ebk> C = rd.a("cherry_bees_005");

   public static void a(pj<ebk> $$0) {
      im<duh<?, ?>> $$1 = $$0.a(ki.ax);
      il<duh<?, ?>> $$2 = $$1.b(qt.a);
      il<duh<?, ?>> $$3 = $$1.b(qt.c);
      il<duh<?, ?>> $$4 = $$1.b(qt.g);
      il<duh<?, ?>> $$5 = $$1.b(qt.h);
      il<duh<?, ?>> $$6 = $$1.b(qt.i);
      il<duh<?, ?>> $$7 = $$1.b(qt.j);
      il<duh<?, ?>> $$8 = $$1.b(qt.k);
      il<duh<?, ?>> $$9 = $$1.b(qt.x);
      il<duh<?, ?>> $$10 = $$1.b(qt.z);
      il<duh<?, ?>> $$11 = $$1.b(qt.l);
      il<duh<?, ?>> $$12 = $$1.b(qt.m);
      il<duh<?, ?>> $$13 = $$1.b(qt.n);
      il<duh<?, ?>> $$14 = $$1.b(qt.p);
      il<duh<?, ?>> $$15 = $$1.b(qt.q);
      il<duh<?, ?>> $$16 = $$1.b(qt.r);
      il<duh<?, ?>> $$17 = $$1.b(qt.y);
      il<duh<?, ?>> $$18 = $$1.b(qt.v);
      il<duh<?, ?>> $$19 = $$1.b(qt.s);
      il<duh<?, ?>> $$20 = $$1.b(qt.t);
      il<duh<?, ?>> $$21 = $$1.b(qt.A);
      il<duh<?, ?>> $$22 = $$1.b(qt.B);
      il<duh<?, ?>> $$23 = $$1.b(qt.D);
      il<duh<?, ?>> $$24 = $$1.b(qt.E);
      il<duh<?, ?>> $$25 = $$1.b(qt.G);
      il<duh<?, ?>> $$26 = $$1.b(qt.H);
      il<duh<?, ?>> $$27 = $$1.b(qt.J);
      il<duh<?, ?>> $$28 = $$1.b(qt.K);
      rd.a($$0, a, $$2, ebc.a(8), eay.a());
      rd.a($$0, b, $$3, ebc.a(8), eay.a());
      rd.a($$0, c, $$4, rd.a(czh.x));
      rd.a($$0, d, $$5, rd.a(czh.D));
      rd.a($$0, e, $$6, rd.a(czh.z));
      rd.a($$0, f, $$7, rd.a(czh.B));
      rd.a($$0, g, $$8, rd.a(czh.y));
      rd.a($$0, h, $$9, rd.a(czh.E));
      rd.a($$0, i, $$10, rd.a(czh.C));
      dsx $$29 = dsx.a(ih.a.q(), czh.dP, czh.qP);
      List<ebn> $$30 = List.of(ebe.a(ih.b, dsx.a(dsx.a(czh.qP)), 8), eaz.a($$29));
      rd.a($$0, j, $$11, $$30);
      rd.a($$0, k, $$8, $$30);
      rd.a($$0, l, $$11, rd.a(czh.y));
      rd.a($$0, m, $$12, rd.a(czh.A));
      rd.a($$0, n, $$13, rd.a(czh.x));
      rd.a($$0, o, $$14, rd.a(czh.A));
      rd.a($$0, p, $$15, rd.a(czh.y));
      rd.a($$0, q, $$16, rd.a(czh.y));
      rd.a($$0, r, $$17, rd.a(czh.E));
      rd.a($$0, s, $$18, rd.a(czh.x));
      rd.a($$0, t, $$19, rd.a(czh.z));
      rd.a($$0, u, $$20, rd.a(czh.z));
      rd.a($$0, v, $$21, rd.a(czh.x));
      rd.a($$0, w, $$22, rd.a(czh.x));
      rd.a($$0, x, $$23, rd.a(czh.z));
      rd.a($$0, y, $$24, rd.a(czh.z));
      rd.a($$0, z, $$25, rd.a(czh.x));
      rd.a($$0, A, $$26, rd.a(czh.x));
      rd.a($$0, B, $$27, rd.a(czh.x));
      rd.a($$0, C, $$28, rd.a(czh.C));
   }
}
