public abstract class rf {
   public static void a(qm<ddg> $$0) {
      jk<eib> $$1 = $$0.a(lr.aP);
      jk<eak<?>> $$2 = $$0.a(lr.aG);
      $$0.a(ddn.a, ri.j($$1, $$2));
      $$0.a(ddn.b, ri.a($$1, $$2, false, false, false));
      $$0.a(ddn.c, ri.a($$1, $$2, true, false, false));
      $$0.a(ddn.d, ri.a($$1, $$2, false, true, false));
      $$0.a(ddn.e, ri.a($$1, $$2, false, true, true));
      $$0.a(ddn.f, ri.d($$1, $$2));
      $$0.a(ddn.g, ri.h($$1, $$2));
      $$0.a(ddn.h, ri.i($$1, $$2));
      $$0.a(ddn.i, ri.b($$1, $$2, false, false, false));
      $$0.a(ddn.j, ri.b($$1, $$2, false, false, true));
      $$0.a(ddn.k, ri.b($$1, $$2, true, false, false));
      $$0.a(ddn.l, ri.g($$1, $$2));
      $$0.a(ddn.m, ri.b($$1, $$2, true, true, false));
      $$0.a(ddn.n, ri.a($$1, $$2, false));
      $$0.a(ddn.o, ri.a($$1, $$2, true));
      $$0.a(ddn.p, ri.h($$1, $$2, false));
      $$0.a(ddn.q, ri.h($$1, $$2, true));
      $$0.a(ddn.r, ri.a($$1, $$2, false, false));
      $$0.a(ddn.s, ri.a($$1, $$2, false, true));
      $$0.a(ddn.t, ri.b($$1, $$2, false));
      $$0.a(ddn.u, ri.b($$1, $$2, false));
      $$0.a(ddn.v, ri.b($$1, $$2, true));
      $$0.a(ddn.w, ri.a($$1, $$2, true, false));
      $$0.a(ddn.x, ri.b($$1, $$2));
      $$0.a(ddn.y, ri.a($$1, $$2));
      $$0.a(ddn.z, ri.c($$1, $$2));
      $$0.a(ddn.A, ri.c($$1, $$2, false));
      $$0.a(ddn.B, ri.c($$1, $$2, false));
      $$0.a(ddn.C, ri.c($$1, $$2, true));
      $$0.a(ddn.D, ri.j($$1, $$2, false));
      $$0.a(ddn.E, ri.j($$1, $$2, true));
      $$0.a(ddn.F, ri.o($$1, $$2));
      $$0.a(ddn.G, ri.n($$1, $$2));
      $$0.a(ddn.H, ri.k($$1, $$2));
      $$0.a(ddn.I, ri.l($$1, $$2));
      $$0.a(ddn.J, ri.m($$1, $$2));
      $$0.a(ddn.K, ri.i($$1, $$2, false));
      $$0.a(ddn.L, ri.i($$1, $$2, true));
      $$0.a(ddn.M, ri.b($$1, $$2, false, false));
      $$0.a(ddn.N, ri.b($$1, $$2, true, false));
      $$0.a(ddn.O, ri.b($$1, $$2, false, true));
      $$0.a(ddn.P, ri.f($$1, $$2));
      $$0.a(ddn.Q, ri.f($$1, $$2, false));
      $$0.a(ddn.R, ri.f($$1, $$2, true));
      $$0.a(ddn.S, ri.e($$1, $$2, false));
      $$0.a(ddn.T, ri.e($$1, $$2, true));
      $$0.a(ddn.U, ri.d($$1, $$2, false));
      $$0.a(ddn.V, ri.d($$1, $$2, true));
      $$0.a(ddn.W, ri.g($$1, $$2, false));
      $$0.a(ddn.X, ri.g($$1, $$2, true));
      $$0.a(ddn.Y, ri.e($$1, $$2));
      $$0.a(ddn.Z, ri.q($$1, $$2));
      $$0.a(ddn.aa, ri.p($$1, $$2));
      $$0.a(ddn.ab, ri.r($$1, $$2));
      $$0.a(ddn.ac, rh.a($$1, $$2));
      $$0.a(ddn.ad, rh.e($$1, $$2));
      $$0.a(ddn.ae, rh.d($$1, $$2));
      $$0.a(ddn.af, rh.b($$1, $$2));
      $$0.a(ddn.ag, rh.c($$1, $$2));
      $$0.a(ddn.ah, rg.b($$1, $$2));
      $$0.a(ddn.ai, rg.d($$1, $$2));
      $$0.a(ddn.aj, rg.c($$1, $$2));
      $$0.a(ddn.ak, rg.e($$1, $$2));
      $$0.a(ddn.al, rg.a($$1, $$2));
   }
}
