import java.util.List;

public class rg {
   public static final ajg<ecg> a = rf.a("crimson_fungi");
   public static final ajg<ecg> b = rf.a("warped_fungi");
   public static final ajg<ecg> c = rf.a("oak_checked");
   public static final ajg<ecg> d = rf.a("dark_oak_checked");
   public static final ajg<ecg> e = rf.a("birch_checked");
   public static final ajg<ecg> f = rf.a("acacia_checked");
   public static final ajg<ecg> g = rf.a("spruce_checked");
   public static final ajg<ecg> h = rf.a("mangrove_checked");
   public static final ajg<ecg> i = rf.a("cherry_checked");
   public static final ajg<ecg> j = rf.a("pine_on_snow");
   public static final ajg<ecg> k = rf.a("spruce_on_snow");
   public static final ajg<ecg> l = rf.a("pine_checked");
   public static final ajg<ecg> m = rf.a("jungle_tree");
   public static final ajg<ecg> n = rf.a("fancy_oak_checked");
   public static final ajg<ecg> o = rf.a("mega_jungle_tree_checked");
   public static final ajg<ecg> p = rf.a("mega_spruce_checked");
   public static final ajg<ecg> q = rf.a("mega_pine_checked");
   public static final ajg<ecg> r = rf.a("tall_mangrove_checked");
   public static final ajg<ecg> s = rf.a("jungle_bush");
   public static final ajg<ecg> t = rf.a("super_birch_bees_0002");
   public static final ajg<ecg> u = rf.a("super_birch_bees");
   public static final ajg<ecg> v = rf.a("oak_bees_0002");
   public static final ajg<ecg> w = rf.a("oak_bees_002");
   public static final ajg<ecg> x = rf.a("birch_bees_0002");
   public static final ajg<ecg> y = rf.a("birch_bees_002");
   public static final ajg<ecg> z = rf.a("fancy_oak_bees_0002");
   public static final ajg<ecg> A = rf.a("fancy_oak_bees_002");
   public static final ajg<ecg> B = rf.a("fancy_oak_bees");
   public static final ajg<ecg> C = rf.a("cherry_bees_005");

   public static void a(pl<ecg> $$0) {
      im<dvd<?, ?>> $$1 = $$0.a(kj.ax);
      il<dvd<?, ?>> $$2 = $$1.b(qv.a);
      il<dvd<?, ?>> $$3 = $$1.b(qv.c);
      il<dvd<?, ?>> $$4 = $$1.b(qv.g);
      il<dvd<?, ?>> $$5 = $$1.b(qv.h);
      il<dvd<?, ?>> $$6 = $$1.b(qv.i);
      il<dvd<?, ?>> $$7 = $$1.b(qv.j);
      il<dvd<?, ?>> $$8 = $$1.b(qv.k);
      il<dvd<?, ?>> $$9 = $$1.b(qv.x);
      il<dvd<?, ?>> $$10 = $$1.b(qv.z);
      il<dvd<?, ?>> $$11 = $$1.b(qv.l);
      il<dvd<?, ?>> $$12 = $$1.b(qv.m);
      il<dvd<?, ?>> $$13 = $$1.b(qv.n);
      il<dvd<?, ?>> $$14 = $$1.b(qv.p);
      il<dvd<?, ?>> $$15 = $$1.b(qv.q);
      il<dvd<?, ?>> $$16 = $$1.b(qv.r);
      il<dvd<?, ?>> $$17 = $$1.b(qv.y);
      il<dvd<?, ?>> $$18 = $$1.b(qv.v);
      il<dvd<?, ?>> $$19 = $$1.b(qv.s);
      il<dvd<?, ?>> $$20 = $$1.b(qv.t);
      il<dvd<?, ?>> $$21 = $$1.b(qv.A);
      il<dvd<?, ?>> $$22 = $$1.b(qv.B);
      il<dvd<?, ?>> $$23 = $$1.b(qv.D);
      il<dvd<?, ?>> $$24 = $$1.b(qv.E);
      il<dvd<?, ?>> $$25 = $$1.b(qv.G);
      il<dvd<?, ?>> $$26 = $$1.b(qv.H);
      il<dvd<?, ?>> $$27 = $$1.b(qv.J);
      il<dvd<?, ?>> $$28 = $$1.b(qv.K);
      rf.a($$0, a, $$2, eby.a(8), ebu.a());
      rf.a($$0, b, $$3, eby.a(8), ebu.a());
      rf.a($$0, c, $$4, rf.a(dac.x));
      rf.a($$0, d, $$5, rf.a(dac.D));
      rf.a($$0, e, $$6, rf.a(dac.z));
      rf.a($$0, f, $$7, rf.a(dac.B));
      rf.a($$0, g, $$8, rf.a(dac.y));
      rf.a($$0, h, $$9, rf.a(dac.E));
      rf.a($$0, i, $$10, rf.a(dac.C));
      dtt $$29 = dtt.a(ih.a.q(), dac.dP, dac.qP);
      List<ecj> $$30 = List.of(eca.a(ih.b, dtt.a(dtt.a(dac.qP)), 8), ebv.a($$29));
      rf.a($$0, j, $$11, $$30);
      rf.a($$0, k, $$8, $$30);
      rf.a($$0, l, $$11, rf.a(dac.y));
      rf.a($$0, m, $$12, rf.a(dac.A));
      rf.a($$0, n, $$13, rf.a(dac.x));
      rf.a($$0, o, $$14, rf.a(dac.A));
      rf.a($$0, p, $$15, rf.a(dac.y));
      rf.a($$0, q, $$16, rf.a(dac.y));
      rf.a($$0, r, $$17, rf.a(dac.E));
      rf.a($$0, s, $$18, rf.a(dac.x));
      rf.a($$0, t, $$19, rf.a(dac.z));
      rf.a($$0, u, $$20, rf.a(dac.z));
      rf.a($$0, v, $$21, rf.a(dac.x));
      rf.a($$0, w, $$22, rf.a(dac.x));
      rf.a($$0, x, $$23, rf.a(dac.z));
      rf.a($$0, y, $$24, rf.a(dac.z));
      rf.a($$0, z, $$25, rf.a(dac.x));
      rf.a($$0, A, $$26, rf.a(dac.x));
      rf.a($$0, B, $$27, rf.a(dac.x));
      rf.a($$0, C, $$28, rf.a(dac.C));
   }
}
