import java.util.List;

public class ri {
   public static final aku<efj<?, ?>> a = rf.a("ore_magma");
   public static final aku<efj<?, ?>> b = rf.a("ore_soul_sand");
   public static final aku<efj<?, ?>> c = rf.a("ore_nether_gold");
   public static final aku<efj<?, ?>> d = rf.a("ore_quartz");
   public static final aku<efj<?, ?>> e = rf.a("ore_gravel_nether");
   public static final aku<efj<?, ?>> f = rf.a("ore_blackstone");
   public static final aku<efj<?, ?>> g = rf.a("ore_dirt");
   public static final aku<efj<?, ?>> h = rf.a("ore_gravel");
   public static final aku<efj<?, ?>> i = rf.a("ore_granite");
   public static final aku<efj<?, ?>> j = rf.a("ore_diorite");
   public static final aku<efj<?, ?>> k = rf.a("ore_andesite");
   public static final aku<efj<?, ?>> l = rf.a("ore_tuff");
   public static final aku<efj<?, ?>> m = rf.a("ore_coal");
   public static final aku<efj<?, ?>> n = rf.a("ore_coal_buried");
   public static final aku<efj<?, ?>> o = rf.a("ore_iron");
   public static final aku<efj<?, ?>> p = rf.a("ore_iron_small");
   public static final aku<efj<?, ?>> q = rf.a("ore_gold");
   public static final aku<efj<?, ?>> r = rf.a("ore_gold_buried");
   public static final aku<efj<?, ?>> s = rf.a("ore_redstone");
   public static final aku<efj<?, ?>> t = rf.a("ore_diamond_small");
   public static final aku<efj<?, ?>> u = rf.a("ore_diamond_medium");
   public static final aku<efj<?, ?>> v = rf.a("ore_diamond_large");
   public static final aku<efj<?, ?>> w = rf.a("ore_diamond_buried");
   public static final aku<efj<?, ?>> x = rf.a("ore_lapis");
   public static final aku<efj<?, ?>> y = rf.a("ore_lapis_buried");
   public static final aku<efj<?, ?>> z = rf.a("ore_infested");
   public static final aku<efj<?, ?>> A = rf.a("ore_emerald");
   public static final aku<efj<?, ?>> B = rf.a("ore_ancient_debris_large");
   public static final aku<efj<?, ?>> C = rf.a("ore_ancient_debris_small");
   public static final aku<efj<?, ?>> D = rf.a("ore_copper_small");
   public static final aku<efj<?, ?>> E = rf.a("ore_copper_large");
   public static final aku<efj<?, ?>> F = rf.a("ore_clay");

   public static void a(qe<efj<?, ?>> $$0) {
      erh $$1 = new erp(awp.bg);
      erh $$2 = new erp(awp.bh);
      erh $$3 = new erp(awp.bi);
      erh $$4 = new eqp(djn.ei);
      erh $$5 = new erp(awp.bj);
      List<eij.a> $$6 = List.of(eij.a($$2, djn.S.m()), eij.a($$3, djn.T.m()));
      List<eij.a> $$7 = List.of(eij.a($$2, djn.Q.m()), eij.a($$3, djn.R.m()));
      List<eij.a> $$8 = List.of(eij.a($$2, djn.cF.m()), eij.a($$3, djn.cG.m()));
      List<eij.a> $$9 = List.of(eij.a($$2, djn.aY.m()), eij.a($$3, djn.aZ.m()));
      List<eij.a> $$10 = List.of(eij.a($$2, djn.rC.m()), eij.a($$3, djn.rD.m()));
      List<eij.a> $$11 = List.of(eij.a($$2, djn.U.m()), eij.a($$3, djn.V.m()));
      rf.a($$0, a, efx.I, new eij($$4, djn.ll.m(), 33));
      rf.a($$0, b, efx.I, new eij($$4, djn.ej.m(), 12));
      rf.a($$0, c, efx.I, new eij($$4, djn.W.m(), 10));
      rf.a($$0, d, efx.I, new eij($$4, djn.hy.m(), 14));
      rf.a($$0, e, efx.I, new eij($$4, djn.O.m(), 33));
      rf.a($$0, f, efx.I, new eij($$4, djn.pT.m(), 33));
      rf.a($$0, g, efx.I, new eij($$1, djn.j.m(), 33));
      rf.a($$0, h, efx.I, new eij($$1, djn.O.m(), 33));
      rf.a($$0, i, efx.I, new eij($$1, djn.c.m(), 64));
      rf.a($$0, j, efx.I, new eij($$1, djn.e.m(), 64));
      rf.a($$0, k, efx.I, new eij($$1, djn.g.m(), 64));
      rf.a($$0, l, efx.I, new eij($$1, djn.rb.m(), 64));
      rf.a($$0, m, efx.I, new eij($$11, 17));
      rf.a($$0, n, efx.I, new eij($$11, 17, 0.5F));
      rf.a($$0, o, efx.I, new eij($$6, 9));
      rf.a($$0, p, efx.I, new eij($$6, 4));
      rf.a($$0, q, efx.I, new eij($$7, 9));
      rf.a($$0, r, efx.I, new eij($$7, 9, 0.5F));
      rf.a($$0, s, efx.I, new eij(List.of(eij.a($$2, djn.dV.m()), eij.a($$3, djn.dW.m())), 8));
      rf.a($$0, t, efx.I, new eij($$8, 4, 0.5F));
      rf.a($$0, v, efx.I, new eij($$8, 12, 0.7F));
      rf.a($$0, w, efx.I, new eij($$8, 8, 1.0F));
      rf.a($$0, u, efx.I, new eij($$8, 8, 0.5F));
      rf.a($$0, x, efx.I, new eij($$9, 7));
      rf.a($$0, y, efx.I, new eij($$9, 7, 1.0F));
      rf.a($$0, z, efx.I, new eij(List.of(eij.a($$2, djn.fb.m()), eij.a($$3, djn.tF.m())), 9));
      rf.a($$0, A, efx.I, new eij(List.of(eij.a($$2, djn.fZ.m()), eij.a($$3, djn.ga.m())), 3));
      rf.a($$0, B, efx.af, new eij($$5, djn.pL.m(), 3, 1.0F));
      rf.a($$0, C, efx.af, new eij($$5, djn.pL.m(), 2, 1.0F));
      rf.a($$0, D, efx.I, new eij($$10, 10));
      rf.a($$0, E, efx.I, new eij($$10, 20));
      rf.a($$0, F, efx.I, new eij($$1, djn.ee.m(), 33));
   }
}
