import java.util.List;

public class rl {
   public static final ald<eif<?, ?>> a = ri.a("ore_magma");
   public static final ald<eif<?, ?>> b = ri.a("ore_soul_sand");
   public static final ald<eif<?, ?>> c = ri.a("ore_nether_gold");
   public static final ald<eif<?, ?>> d = ri.a("ore_quartz");
   public static final ald<eif<?, ?>> e = ri.a("ore_gravel_nether");
   public static final ald<eif<?, ?>> f = ri.a("ore_blackstone");
   public static final ald<eif<?, ?>> g = ri.a("ore_dirt");
   public static final ald<eif<?, ?>> h = ri.a("ore_gravel");
   public static final ald<eif<?, ?>> i = ri.a("ore_granite");
   public static final ald<eif<?, ?>> j = ri.a("ore_diorite");
   public static final ald<eif<?, ?>> k = ri.a("ore_andesite");
   public static final ald<eif<?, ?>> l = ri.a("ore_tuff");
   public static final ald<eif<?, ?>> m = ri.a("ore_coal");
   public static final ald<eif<?, ?>> n = ri.a("ore_coal_buried");
   public static final ald<eif<?, ?>> o = ri.a("ore_iron");
   public static final ald<eif<?, ?>> p = ri.a("ore_iron_small");
   public static final ald<eif<?, ?>> q = ri.a("ore_gold");
   public static final ald<eif<?, ?>> r = ri.a("ore_gold_buried");
   public static final ald<eif<?, ?>> s = ri.a("ore_redstone");
   public static final ald<eif<?, ?>> t = ri.a("ore_diamond_small");
   public static final ald<eif<?, ?>> u = ri.a("ore_diamond_medium");
   public static final ald<eif<?, ?>> v = ri.a("ore_diamond_large");
   public static final ald<eif<?, ?>> w = ri.a("ore_diamond_buried");
   public static final ald<eif<?, ?>> x = ri.a("ore_lapis");
   public static final ald<eif<?, ?>> y = ri.a("ore_lapis_buried");
   public static final ald<eif<?, ?>> z = ri.a("ore_infested");
   public static final ald<eif<?, ?>> A = ri.a("ore_emerald");
   public static final ald<eif<?, ?>> B = ri.a("ore_ancient_debris_large");
   public static final ald<eif<?, ?>> C = ri.a("ore_ancient_debris_small");
   public static final ald<eif<?, ?>> D = ri.a("ore_copper_small");
   public static final ald<eif<?, ?>> E = ri.a("ore_copper_large");
   public static final ald<eif<?, ?>> F = ri.a("ore_clay");

   public static void a(qh<eif<?, ?>> $$0) {
      eue $$1 = new eum(axa.bg);
      eue $$2 = new eum(axa.bh);
      eue $$3 = new eum(axa.bi);
      eue $$4 = new etm(dlw.ei);
      eue $$5 = new eum(axa.bj);
      List<elf.a> $$6 = List.of(elf.a($$2, dlw.S.m()), elf.a($$3, dlw.T.m()));
      List<elf.a> $$7 = List.of(elf.a($$2, dlw.Q.m()), elf.a($$3, dlw.R.m()));
      List<elf.a> $$8 = List.of(elf.a($$2, dlw.cF.m()), elf.a($$3, dlw.cG.m()));
      List<elf.a> $$9 = List.of(elf.a($$2, dlw.aY.m()), elf.a($$3, dlw.aZ.m()));
      List<elf.a> $$10 = List.of(elf.a($$2, dlw.rE.m()), elf.a($$3, dlw.rF.m()));
      List<elf.a> $$11 = List.of(elf.a($$2, dlw.U.m()), elf.a($$3, dlw.V.m()));
      ri.a($$0, a, eit.I, new elf($$4, dlw.ll.m(), 33));
      ri.a($$0, b, eit.I, new elf($$4, dlw.ej.m(), 12));
      ri.a($$0, c, eit.I, new elf($$4, dlw.W.m(), 10));
      ri.a($$0, d, eit.I, new elf($$4, dlw.hy.m(), 14));
      ri.a($$0, e, eit.I, new elf($$4, dlw.O.m(), 33));
      ri.a($$0, f, eit.I, new elf($$4, dlw.pV.m(), 33));
      ri.a($$0, g, eit.I, new elf($$1, dlw.j.m(), 33));
      ri.a($$0, h, eit.I, new elf($$1, dlw.O.m(), 33));
      ri.a($$0, i, eit.I, new elf($$1, dlw.c.m(), 64));
      ri.a($$0, j, eit.I, new elf($$1, dlw.e.m(), 64));
      ri.a($$0, k, eit.I, new elf($$1, dlw.g.m(), 64));
      ri.a($$0, l, eit.I, new elf($$1, dlw.rd.m(), 64));
      ri.a($$0, m, eit.I, new elf($$11, 17));
      ri.a($$0, n, eit.I, new elf($$11, 17, 0.5F));
      ri.a($$0, o, eit.I, new elf($$6, 9));
      ri.a($$0, p, eit.I, new elf($$6, 4));
      ri.a($$0, q, eit.I, new elf($$7, 9));
      ri.a($$0, r, eit.I, new elf($$7, 9, 0.5F));
      ri.a($$0, s, eit.I, new elf(List.of(elf.a($$2, dlw.dV.m()), elf.a($$3, dlw.dW.m())), 8));
      ri.a($$0, t, eit.I, new elf($$8, 4, 0.5F));
      ri.a($$0, v, eit.I, new elf($$8, 12, 0.7F));
      ri.a($$0, w, eit.I, new elf($$8, 8, 1.0F));
      ri.a($$0, u, eit.I, new elf($$8, 8, 0.5F));
      ri.a($$0, x, eit.I, new elf($$9, 7));
      ri.a($$0, y, eit.I, new elf($$9, 7, 1.0F));
      ri.a($$0, z, eit.I, new elf(List.of(elf.a($$2, dlw.fb.m()), elf.a($$3, dlw.tJ.m())), 9));
      ri.a($$0, A, eit.I, new elf(List.of(elf.a($$2, dlw.fZ.m()), elf.a($$3, dlw.ga.m())), 3));
      ri.a($$0, B, eit.af, new elf($$5, dlw.pN.m(), 3, 1.0F));
      ri.a($$0, C, eit.af, new elf($$5, dlw.pN.m(), 2, 1.0F));
      ri.a($$0, D, eit.I, new elf($$10, 10));
      ri.a($$0, E, eit.I, new elf($$10, 20));
      ri.a($$0, F, eit.I, new elf($$1, dlw.ee.m(), 33));
   }
}
