import java.util.List;

public class rl {
   public static final alf<ejk<?, ?>> a = ri.a("ore_magma");
   public static final alf<ejk<?, ?>> b = ri.a("ore_soul_sand");
   public static final alf<ejk<?, ?>> c = ri.a("ore_nether_gold");
   public static final alf<ejk<?, ?>> d = ri.a("ore_quartz");
   public static final alf<ejk<?, ?>> e = ri.a("ore_gravel_nether");
   public static final alf<ejk<?, ?>> f = ri.a("ore_blackstone");
   public static final alf<ejk<?, ?>> g = ri.a("ore_dirt");
   public static final alf<ejk<?, ?>> h = ri.a("ore_gravel");
   public static final alf<ejk<?, ?>> i = ri.a("ore_granite");
   public static final alf<ejk<?, ?>> j = ri.a("ore_diorite");
   public static final alf<ejk<?, ?>> k = ri.a("ore_andesite");
   public static final alf<ejk<?, ?>> l = ri.a("ore_tuff");
   public static final alf<ejk<?, ?>> m = ri.a("ore_coal");
   public static final alf<ejk<?, ?>> n = ri.a("ore_coal_buried");
   public static final alf<ejk<?, ?>> o = ri.a("ore_iron");
   public static final alf<ejk<?, ?>> p = ri.a("ore_iron_small");
   public static final alf<ejk<?, ?>> q = ri.a("ore_gold");
   public static final alf<ejk<?, ?>> r = ri.a("ore_gold_buried");
   public static final alf<ejk<?, ?>> s = ri.a("ore_redstone");
   public static final alf<ejk<?, ?>> t = ri.a("ore_diamond_small");
   public static final alf<ejk<?, ?>> u = ri.a("ore_diamond_medium");
   public static final alf<ejk<?, ?>> v = ri.a("ore_diamond_large");
   public static final alf<ejk<?, ?>> w = ri.a("ore_diamond_buried");
   public static final alf<ejk<?, ?>> x = ri.a("ore_lapis");
   public static final alf<ejk<?, ?>> y = ri.a("ore_lapis_buried");
   public static final alf<ejk<?, ?>> z = ri.a("ore_infested");
   public static final alf<ejk<?, ?>> A = ri.a("ore_emerald");
   public static final alf<ejk<?, ?>> B = ri.a("ore_ancient_debris_large");
   public static final alf<ejk<?, ?>> C = ri.a("ore_ancient_debris_small");
   public static final alf<ejk<?, ?>> D = ri.a("ore_copper_small");
   public static final alf<ejk<?, ?>> E = ri.a("ore_copper_large");
   public static final alf<ejk<?, ?>> F = ri.a("ore_clay");

   public static void a(qh<ejk<?, ?>> $$0) {
      evj $$1 = new evr(axc.bh);
      evj $$2 = new evr(axc.bi);
      evj $$3 = new evr(axc.bj);
      evj $$4 = new eur(dmt.em);
      evj $$5 = new evr(axc.bk);
      List<emk.a> $$6 = List.of(emk.a($$2, dmt.S.m()), emk.a($$3, dmt.T.m()));
      List<emk.a> $$7 = List.of(emk.a($$2, dmt.Q.m()), emk.a($$3, dmt.R.m()));
      List<emk.a> $$8 = List.of(emk.a($$2, dmt.cI.m()), emk.a($$3, dmt.cJ.m()));
      List<emk.a> $$9 = List.of(emk.a($$2, dmt.aY.m()), emk.a($$3, dmt.aZ.m()));
      List<emk.a> $$10 = List.of(emk.a($$2, dmt.rI.m()), emk.a($$3, dmt.rJ.m()));
      List<emk.a> $$11 = List.of(emk.a($$2, dmt.U.m()), emk.a($$3, dmt.V.m()));
      ri.a($$0, a, ejy.I, new emk($$4, dmt.lp.m(), 33));
      ri.a($$0, b, ejy.I, new emk($$4, dmt.en.m(), 12));
      ri.a($$0, c, ejy.I, new emk($$4, dmt.W.m(), 10));
      ri.a($$0, d, ejy.I, new emk($$4, dmt.hC.m(), 14));
      ri.a($$0, e, ejy.I, new emk($$4, dmt.O.m(), 33));
      ri.a($$0, f, ejy.I, new emk($$4, dmt.pZ.m(), 33));
      ri.a($$0, g, ejy.I, new emk($$1, dmt.j.m(), 33));
      ri.a($$0, h, ejy.I, new emk($$1, dmt.O.m(), 33));
      ri.a($$0, i, ejy.I, new emk($$1, dmt.c.m(), 64));
      ri.a($$0, j, ejy.I, new emk($$1, dmt.e.m(), 64));
      ri.a($$0, k, ejy.I, new emk($$1, dmt.g.m(), 64));
      ri.a($$0, l, ejy.I, new emk($$1, dmt.rh.m(), 64));
      ri.a($$0, m, ejy.I, new emk($$11, 17));
      ri.a($$0, n, ejy.I, new emk($$11, 17, 0.5F));
      ri.a($$0, o, ejy.I, new emk($$6, 9));
      ri.a($$0, p, ejy.I, new emk($$6, 4));
      ri.a($$0, q, ejy.I, new emk($$7, 9));
      ri.a($$0, r, ejy.I, new emk($$7, 9, 0.5F));
      ri.a($$0, s, ejy.I, new emk(List.of(emk.a($$2, dmt.dY.m()), emk.a($$3, dmt.dZ.m())), 8));
      ri.a($$0, t, ejy.I, new emk($$8, 4, 0.5F));
      ri.a($$0, v, ejy.I, new emk($$8, 12, 0.7F));
      ri.a($$0, w, ejy.I, new emk($$8, 8, 1.0F));
      ri.a($$0, u, ejy.I, new emk($$8, 8, 0.5F));
      ri.a($$0, x, ejy.I, new emk($$9, 7));
      ri.a($$0, y, ejy.I, new emk($$9, 7, 1.0F));
      ri.a($$0, z, ejy.I, new emk(List.of(emk.a($$2, dmt.ff.m()), emk.a($$3, dmt.tN.m())), 9));
      ri.a($$0, A, ejy.I, new emk(List.of(emk.a($$2, dmt.gd.m()), emk.a($$3, dmt.ge.m())), 3));
      ri.a($$0, B, ejy.af, new emk($$5, dmt.pR.m(), 3, 1.0F));
      ri.a($$0, C, ejy.af, new emk($$5, dmt.pR.m(), 2, 1.0F));
      ri.a($$0, D, ejy.I, new emk($$10, 10));
      ri.a($$0, E, ejy.I, new emk($$10, 20));
      ri.a($$0, F, ejy.I, new emk($$1, dmt.ei.m(), 33));
   }
}
