import java.util.List;

public class rm {
   public static final alq<ekh<?, ?>> a = rj.a("ore_magma");
   public static final alq<ekh<?, ?>> b = rj.a("ore_soul_sand");
   public static final alq<ekh<?, ?>> c = rj.a("ore_nether_gold");
   public static final alq<ekh<?, ?>> d = rj.a("ore_quartz");
   public static final alq<ekh<?, ?>> e = rj.a("ore_gravel_nether");
   public static final alq<ekh<?, ?>> f = rj.a("ore_blackstone");
   public static final alq<ekh<?, ?>> g = rj.a("ore_dirt");
   public static final alq<ekh<?, ?>> h = rj.a("ore_gravel");
   public static final alq<ekh<?, ?>> i = rj.a("ore_granite");
   public static final alq<ekh<?, ?>> j = rj.a("ore_diorite");
   public static final alq<ekh<?, ?>> k = rj.a("ore_andesite");
   public static final alq<ekh<?, ?>> l = rj.a("ore_tuff");
   public static final alq<ekh<?, ?>> m = rj.a("ore_coal");
   public static final alq<ekh<?, ?>> n = rj.a("ore_coal_buried");
   public static final alq<ekh<?, ?>> o = rj.a("ore_iron");
   public static final alq<ekh<?, ?>> p = rj.a("ore_iron_small");
   public static final alq<ekh<?, ?>> q = rj.a("ore_gold");
   public static final alq<ekh<?, ?>> r = rj.a("ore_gold_buried");
   public static final alq<ekh<?, ?>> s = rj.a("ore_redstone");
   public static final alq<ekh<?, ?>> t = rj.a("ore_diamond_small");
   public static final alq<ekh<?, ?>> u = rj.a("ore_diamond_medium");
   public static final alq<ekh<?, ?>> v = rj.a("ore_diamond_large");
   public static final alq<ekh<?, ?>> w = rj.a("ore_diamond_buried");
   public static final alq<ekh<?, ?>> x = rj.a("ore_lapis");
   public static final alq<ekh<?, ?>> y = rj.a("ore_lapis_buried");
   public static final alq<ekh<?, ?>> z = rj.a("ore_infested");
   public static final alq<ekh<?, ?>> A = rj.a("ore_emerald");
   public static final alq<ekh<?, ?>> B = rj.a("ore_ancient_debris_large");
   public static final alq<ekh<?, ?>> C = rj.a("ore_ancient_debris_small");
   public static final alq<ekh<?, ?>> D = rj.a("ore_copper_small");
   public static final alq<ekh<?, ?>> E = rj.a("ore_copper_large");
   public static final alq<ekh<?, ?>> F = rj.a("ore_clay");

   public static void a(qi<ekh<?, ?>> $$0) {
      ewj $$1 = new ewr(axn.bh);
      ewj $$2 = new ewr(axn.bi);
      ewj $$3 = new ewr(axn.bj);
      ewj $$4 = new evr(dnq.em);
      ewj $$5 = new ewr(axn.bk);
      List<enj.a> $$6 = List.of(enj.a($$2, dnq.S.m()), enj.a($$3, dnq.T.m()));
      List<enj.a> $$7 = List.of(enj.a($$2, dnq.Q.m()), enj.a($$3, dnq.R.m()));
      List<enj.a> $$8 = List.of(enj.a($$2, dnq.cI.m()), enj.a($$3, dnq.cJ.m()));
      List<enj.a> $$9 = List.of(enj.a($$2, dnq.aY.m()), enj.a($$3, dnq.aZ.m()));
      List<enj.a> $$10 = List.of(enj.a($$2, dnq.rI.m()), enj.a($$3, dnq.rJ.m()));
      List<enj.a> $$11 = List.of(enj.a($$2, dnq.U.m()), enj.a($$3, dnq.V.m()));
      rj.a($$0, a, ekw.J, new enj($$4, dnq.lp.m(), 33));
      rj.a($$0, b, ekw.J, new enj($$4, dnq.en.m(), 12));
      rj.a($$0, c, ekw.J, new enj($$4, dnq.W.m(), 10));
      rj.a($$0, d, ekw.J, new enj($$4, dnq.hC.m(), 14));
      rj.a($$0, e, ekw.J, new enj($$4, dnq.O.m(), 33));
      rj.a($$0, f, ekw.J, new enj($$4, dnq.pZ.m(), 33));
      rj.a($$0, g, ekw.J, new enj($$1, dnq.j.m(), 33));
      rj.a($$0, h, ekw.J, new enj($$1, dnq.O.m(), 33));
      rj.a($$0, i, ekw.J, new enj($$1, dnq.c.m(), 64));
      rj.a($$0, j, ekw.J, new enj($$1, dnq.e.m(), 64));
      rj.a($$0, k, ekw.J, new enj($$1, dnq.g.m(), 64));
      rj.a($$0, l, ekw.J, new enj($$1, dnq.rh.m(), 64));
      rj.a($$0, m, ekw.J, new enj($$11, 17));
      rj.a($$0, n, ekw.J, new enj($$11, 17, 0.5F));
      rj.a($$0, o, ekw.J, new enj($$6, 9));
      rj.a($$0, p, ekw.J, new enj($$6, 4));
      rj.a($$0, q, ekw.J, new enj($$7, 9));
      rj.a($$0, r, ekw.J, new enj($$7, 9, 0.5F));
      rj.a($$0, s, ekw.J, new enj(List.of(enj.a($$2, dnq.dY.m()), enj.a($$3, dnq.dZ.m())), 8));
      rj.a($$0, t, ekw.J, new enj($$8, 4, 0.5F));
      rj.a($$0, v, ekw.J, new enj($$8, 12, 0.7F));
      rj.a($$0, w, ekw.J, new enj($$8, 8, 1.0F));
      rj.a($$0, u, ekw.J, new enj($$8, 8, 0.5F));
      rj.a($$0, x, ekw.J, new enj($$9, 7));
      rj.a($$0, y, ekw.J, new enj($$9, 7, 1.0F));
      rj.a($$0, z, ekw.J, new enj(List.of(enj.a($$2, dnq.ff.m()), enj.a($$3, dnq.tN.m())), 9));
      rj.a($$0, A, ekw.J, new enj(List.of(enj.a($$2, dnq.gd.m()), enj.a($$3, dnq.ge.m())), 3));
      rj.a($$0, B, ekw.ag, new enj($$5, dnq.pR.m(), 3, 1.0F));
      rj.a($$0, C, ekw.ag, new enj($$5, dnq.pR.m(), 2, 1.0F));
      rj.a($$0, D, ekw.J, new enj($$10, 10));
      rj.a($$0, E, ekw.J, new enj($$10, 20));
      rj.a($$0, F, ekw.J, new enj($$1, dnq.ei.m(), 33));
   }
}
