public class rp {
   public static final aku<emq> a = ru.a("monster_room");
   public static final aku<emq> b = ru.a("monster_room_deep");
   public static final aku<emq> c = ru.a("fossil_upper");
   public static final aku<emq> d = ru.a("fossil_lower");
   public static final aku<emq> e = ru.a("dripstone_cluster");
   public static final aku<emq> f = ru.a("large_dripstone");
   public static final aku<emq> g = ru.a("pointed_dripstone");
   public static final aku<emq> h = ru.a("underwater_magma");
   public static final aku<emq> i = ru.a("glow_lichen");
   public static final aku<emq> j = ru.a("rooted_azalea_tree");
   public static final aku<emq> k = ru.a("cave_vines");
   public static final aku<emq> l = ru.a("lush_caves_vegetation");
   public static final aku<emq> m = ru.a("lush_caves_clay");
   public static final aku<emq> n = ru.a("lush_caves_ceiling_vegetation");
   public static final aku<emq> o = ru.a("spore_blossom");
   public static final aku<emq> p = ru.a("classic_vines_cave_feature");
   public static final aku<emq> q = ru.a("amethyst_geode");
   public static final aku<emq> r = ru.a("sculk_patch_deep_dark");
   public static final aku<emq> s = ru.a("sculk_patch_ancient_city");
   public static final aku<emq> t = ru.a("sculk_vein");

   public static void a(qe<emq> $$0) {
      js<efk<?, ?>> $$1 = $$0.a(mc.aL);
      jr<efk<?, ?>> $$2 = $$1.b(rd.a);
      jr<efk<?, ?>> $$3 = $$1.b(rd.b);
      jr<efk<?, ?>> $$4 = $$1.b(rd.c);
      jr<efk<?, ?>> $$5 = $$1.b(rd.d);
      jr<efk<?, ?>> $$6 = $$1.b(rd.e);
      jr<efk<?, ?>> $$7 = $$1.b(rd.f);
      jr<efk<?, ?>> $$8 = $$1.b(rd.g);
      jr<efk<?, ?>> $$9 = $$1.b(rd.h);
      jr<efk<?, ?>> $$10 = $$1.b(rd.i);
      jr<efk<?, ?>> $$11 = $$1.b(rd.j);
      jr<efk<?, ?>> $$12 = $$1.b(rd.m);
      jr<efk<?, ?>> $$13 = $$1.b(rd.r);
      jr<efk<?, ?>> $$14 = $$1.b(rd.s);
      jr<efk<?, ?>> $$15 = $$1.b(rd.t);
      jr<efk<?, ?>> $$16 = $$1.b(rl.c);
      jr<efk<?, ?>> $$17 = $$1.b(rd.u);
      jr<efk<?, ?>> $$18 = $$1.b(rd.v);
      jr<efk<?, ?>> $$19 = $$1.b(rd.w);
      jr<efk<?, ?>> $$20 = $$1.b(rd.x);
      ru.a($$0, a, $$2, emi.a(10), emn.a(), eml.a(edm.a(0), edm.b()), eme.a());
      ru.a($$0, b, $$2, emi.a(4), emn.a(), eml.a(edm.b(6), edm.a(-1)), eme.a());
      ru.a($$0, c, $$3, emw.a(64), emn.a(), eml.a(edm.a(0), edm.b()), eme.a());
      ru.a($$0, d, $$4, emw.a(64), emn.a(), eml.a(edm.a(), edm.a(-8)), eme.a());
      ru.a($$0, e, $$5, emi.a(brv.a(48, 96)), emn.a(), ru.j, eme.a());
      ru.a($$0, f, $$6, emi.a(brv.a(10, 48)), emn.a(), ru.j, eme.a());
      ru.a($$0, g, $$7, emi.a(brv.a(192, 256)), emn.a(), ru.j, emi.a(brv.a(1, 5)), emv.a(brk.a(0.0F, 3.0F, -10, 10), brk.a(0.0F, 0.6F, -2, 2)), eme.a());
      ru.a($$0, h, $$8, emi.a(brv.a(44, 52)), emn.a(), ru.j, emy.a(ecs.a.c, Integer.MIN_VALUE, -2), eme.a());
      ru.a($$0, i, $$9, emi.a(brv.a(104, 157)), ru.j, emn.a(), emy.a(ecs.a.c, Integer.MIN_VALUE, -13), eme.a());
      ru.a($$0, j, $$10, emi.a(brv.a(1, 2)), emn.a(), ru.j, emj.a(jn.b, edz.c(), edz.c, 12), emv.a(brm.a(-1)), eme.a());
      ru.a($$0, k, $$11, emi.a(188), emn.a(), ru.j, emj.a(jn.b, edz.a(jn.a), edz.c, 12), emv.a(brm.a(-1)), eme.a());
      ru.a($$0, l, $$12, emi.a(125), emn.a(), ru.j, emj.a(jn.a, edz.c(), edz.c, 12), emv.a(brm.a(1)), eme.a());
      ru.a($$0, m, $$13, emi.a(62), emn.a(), ru.j, emj.a(jn.a, edz.c(), edz.c, 12), emv.a(brm.a(1)), eme.a());
      ru.a($$0, n, $$14, emi.a(125), emn.a(), ru.j, emj.a(jn.b, edz.c(), edz.c, 12), emv.a(brm.a(-1)), eme.a());
      ru.a($$0, o, $$15, emi.a(25), emn.a(), ru.j, emj.a(jn.b, edz.c(), edz.c, 12), emv.a(brm.a(-1)), eme.a());
      ru.a($$0, p, $$16, emi.a(256), emn.a(), ru.j, eme.a());
      ru.a($$0, q, $$17, emw.a(24), emn.a(), eml.a(edm.b(6), edm.a(30)), eme.a());
      ru.a($$0, r, $$18, emi.a(brm.a(256)), emn.a(), ru.j, eme.a());
      ru.a($$0, s, $$19);
      ru.a($$0, t, $$20, emi.a(brv.a(204, 250)), emn.a(), ru.j, eme.a());
   }
}
