import java.util.List;

public class rq {
   public static final akj<eax<?, ?>> a = rn.a("ore_magma");
   public static final akj<eax<?, ?>> b = rn.a("ore_soul_sand");
   public static final akj<eax<?, ?>> c = rn.a("ore_nether_gold");
   public static final akj<eax<?, ?>> d = rn.a("ore_quartz");
   public static final akj<eax<?, ?>> e = rn.a("ore_gravel_nether");
   public static final akj<eax<?, ?>> f = rn.a("ore_blackstone");
   public static final akj<eax<?, ?>> g = rn.a("ore_dirt");
   public static final akj<eax<?, ?>> h = rn.a("ore_gravel");
   public static final akj<eax<?, ?>> i = rn.a("ore_granite");
   public static final akj<eax<?, ?>> j = rn.a("ore_diorite");
   public static final akj<eax<?, ?>> k = rn.a("ore_andesite");
   public static final akj<eax<?, ?>> l = rn.a("ore_tuff");
   public static final akj<eax<?, ?>> m = rn.a("ore_coal");
   public static final akj<eax<?, ?>> n = rn.a("ore_coal_buried");
   public static final akj<eax<?, ?>> o = rn.a("ore_iron");
   public static final akj<eax<?, ?>> p = rn.a("ore_iron_small");
   public static final akj<eax<?, ?>> q = rn.a("ore_gold");
   public static final akj<eax<?, ?>> r = rn.a("ore_gold_buried");
   public static final akj<eax<?, ?>> s = rn.a("ore_redstone");
   public static final akj<eax<?, ?>> t = rn.a("ore_diamond_small");
   public static final akj<eax<?, ?>> u = rn.a("ore_diamond_medium");
   public static final akj<eax<?, ?>> v = rn.a("ore_diamond_large");
   public static final akj<eax<?, ?>> w = rn.a("ore_diamond_buried");
   public static final akj<eax<?, ?>> x = rn.a("ore_lapis");
   public static final akj<eax<?, ?>> y = rn.a("ore_lapis_buried");
   public static final akj<eax<?, ?>> z = rn.a("ore_infested");
   public static final akj<eax<?, ?>> A = rn.a("ore_emerald");
   public static final akj<eax<?, ?>> B = rn.a("ore_ancient_debris_large");
   public static final akj<eax<?, ?>> C = rn.a("ore_ancient_debris_small");
   public static final akj<eax<?, ?>> D = rn.a("ore_copper_small");
   public static final akj<eax<?, ?>> E = rn.a("ore_copper_large");
   public static final akj<eax<?, ?>> F = rn.a("ore_clay");

   public static void a(qm<eax<?, ?>> $$0) {
      emq $$1 = new emy(avw.be);
      emq $$2 = new emy(avw.bf);
      emq $$3 = new emy(avw.bg);
      emq $$4 = new elz(dfj.dV);
      emq $$5 = new emy(avw.bh);
      List<edw.a> $$6 = List.of(edw.a($$2, dfj.P.o()), edw.a($$3, dfj.Q.o()));
      List<edw.a> $$7 = List.of(edw.a($$2, dfj.N.o()), edw.a($$3, dfj.O.o()));
      List<edw.a> $$8 = List.of(edw.a($$2, dfj.cx.o()), edw.a($$3, dfj.cy.o()));
      List<edw.a> $$9 = List.of(edw.a($$2, dfj.aR.o()), edw.a($$3, dfj.aS.o()));
      List<edw.a> $$10 = List.of(edw.a($$2, dfj.ra.o()), edw.a($$3, dfj.rb.o()));
      List<edw.a> $$11 = List.of(edw.a($$2, dfj.R.o()), edw.a($$3, dfj.S.o()));
      rn.a($$0, a, ebk.I, new edw($$4, dfj.kJ.o(), 33));
      rn.a($$0, b, ebk.I, new edw($$4, dfj.dW.o(), 12));
      rn.a($$0, c, ebk.I, new edw($$4, dfj.T.o(), 10));
      rn.a($$0, d, ebk.I, new edw($$4, dfj.hb.o(), 14));
      rn.a($$0, e, ebk.I, new edw($$4, dfj.L.o(), 33));
      rn.a($$0, f, ebk.I, new edw($$4, dfj.pr.o(), 33));
      rn.a($$0, g, ebk.I, new edw($$1, dfj.j.o(), 33));
      rn.a($$0, h, ebk.I, new edw($$1, dfj.L.o(), 33));
      rn.a($$0, i, ebk.I, new edw($$1, dfj.c.o(), 64));
      rn.a($$0, j, ebk.I, new edw($$1, dfj.e.o(), 64));
      rn.a($$0, k, ebk.I, new edw($$1, dfj.g.o(), 64));
      rn.a($$0, l, ebk.I, new edw($$1, dfj.qz.o(), 64));
      rn.a($$0, m, ebk.I, new edw($$11, 17));
      rn.a($$0, n, ebk.I, new edw($$11, 17, 0.5F));
      rn.a($$0, o, ebk.I, new edw($$6, 9));
      rn.a($$0, p, ebk.I, new edw($$6, 4));
      rn.a($$0, q, ebk.I, new edw($$7, 9));
      rn.a($$0, r, ebk.I, new edw($$7, 9, 0.5F));
      rn.a($$0, s, ebk.I, new edw(List.of(edw.a($$2, dfj.dI.o()), edw.a($$3, dfj.dJ.o())), 8));
      rn.a($$0, t, ebk.I, new edw($$8, 4, 0.5F));
      rn.a($$0, v, ebk.I, new edw($$8, 12, 0.7F));
      rn.a($$0, w, ebk.I, new edw($$8, 8, 1.0F));
      rn.a($$0, u, ebk.I, new edw($$8, 8, 0.5F));
      rn.a($$0, x, ebk.I, new edw($$9, 7));
      rn.a($$0, y, ebk.I, new edw($$9, 7, 1.0F));
      rn.a($$0, z, ebk.I, new edw(List.of(edw.a($$2, dfj.eN.o()), edw.a($$3, dfj.td.o())), 9));
      rn.a($$0, A, ebk.I, new edw(List.of(edw.a($$2, dfj.fE.o()), edw.a($$3, dfj.fF.o())), 3));
      rn.a($$0, B, ebk.ae, new edw($$5, dfj.pj.o(), 3, 1.0F));
      rn.a($$0, C, ebk.ae, new edw($$5, dfj.pj.o(), 2, 1.0F));
      rn.a($$0, D, ebk.I, new edw($$10, 10));
      rn.a($$0, E, ebk.I, new edw($$10, 20));
      rn.a($$0, F, ebk.I, new edw($$1, dfj.dR.o(), 33));
   }
}
