public class rs {
   public static final alf<eqf> a = rx.a("monster_room");
   public static final alf<eqf> b = rx.a("monster_room_deep");
   public static final alf<eqf> c = rx.a("fossil_upper");
   public static final alf<eqf> d = rx.a("fossil_lower");
   public static final alf<eqf> e = rx.a("dripstone_cluster");
   public static final alf<eqf> f = rx.a("large_dripstone");
   public static final alf<eqf> g = rx.a("pointed_dripstone");
   public static final alf<eqf> h = rx.a("underwater_magma");
   public static final alf<eqf> i = rx.a("glow_lichen");
   public static final alf<eqf> j = rx.a("rooted_azalea_tree");
   public static final alf<eqf> k = rx.a("cave_vines");
   public static final alf<eqf> l = rx.a("lush_caves_vegetation");
   public static final alf<eqf> m = rx.a("lush_caves_clay");
   public static final alf<eqf> n = rx.a("lush_caves_ceiling_vegetation");
   public static final alf<eqf> o = rx.a("spore_blossom");
   public static final alf<eqf> p = rx.a("classic_vines_cave_feature");
   public static final alf<eqf> q = rx.a("amethyst_geode");
   public static final alf<eqf> r = rx.a("sculk_patch_deep_dark");
   public static final alf<eqf> s = rx.a("sculk_patch_ancient_city");
   public static final alf<eqf> t = rx.a("sculk_vein");

   public static void a(qh<eqf> $$0) {
      jf<eiy<?, ?>> $$1 = $$0.a(mg.aL);
      je<eiy<?, ?>> $$2 = $$1.b(rg.a);
      je<eiy<?, ?>> $$3 = $$1.b(rg.b);
      je<eiy<?, ?>> $$4 = $$1.b(rg.c);
      je<eiy<?, ?>> $$5 = $$1.b(rg.d);
      je<eiy<?, ?>> $$6 = $$1.b(rg.e);
      je<eiy<?, ?>> $$7 = $$1.b(rg.f);
      je<eiy<?, ?>> $$8 = $$1.b(rg.g);
      je<eiy<?, ?>> $$9 = $$1.b(rg.h);
      je<eiy<?, ?>> $$10 = $$1.b(rg.i);
      je<eiy<?, ?>> $$11 = $$1.b(rg.j);
      je<eiy<?, ?>> $$12 = $$1.b(rg.m);
      je<eiy<?, ?>> $$13 = $$1.b(rg.r);
      je<eiy<?, ?>> $$14 = $$1.b(rg.s);
      je<eiy<?, ?>> $$15 = $$1.b(rg.t);
      je<eiy<?, ?>> $$16 = $$1.b(ro.c);
      je<eiy<?, ?>> $$17 = $$1.b(rg.u);
      je<eiy<?, ?>> $$18 = $$1.b(rg.v);
      je<eiy<?, ?>> $$19 = $$1.b(rg.w);
      je<eiy<?, ?>> $$20 = $$1.b(rg.x);
      rx.a($$0, a, $$2, epx.a(10), eqc.a(), eqa.a(eha.a(0), eha.b()), ept.a());
      rx.a($$0, b, $$2, epx.a(4), eqc.a(), eqa.a(eha.b(6), eha.a(-1)), ept.a());
      rx.a($$0, c, $$3, eql.a(64), eqc.a(), eqa.a(eha.a(0), eha.b()), ept.a());
      rx.a($$0, d, $$4, eql.a(64), eqc.a(), eqa.a(eha.a(), eha.a(-8)), ept.a());
      rx.a($$0, e, $$5, epx.a(bto.a(48, 96)), eqc.a(), rx.j, ept.a());
      rx.a($$0, f, $$6, epx.a(bto.a(10, 48)), eqc.a(), rx.j, ept.a());
      rx.a($$0, g, $$7, epx.a(bto.a(192, 256)), eqc.a(), rx.j, epx.a(bto.a(1, 5)), eqk.a(btd.a(0.0F, 3.0F, -10, 10), btd.a(0.0F, 0.6F, -2, 2)), ept.a());
      rx.a($$0, h, $$8, epx.a(bto.a(44, 52)), eqc.a(), rx.j, eqn.a(egg.a.c, Integer.MIN_VALUE, -2), ept.a());
      rx.a($$0, i, $$9, epx.a(bto.a(104, 157)), rx.j, eqc.a(), eqn.a(egg.a.c, Integer.MIN_VALUE, -13), ept.a());
      rx.a($$0, j, $$10, epx.a(bto.a(1, 2)), eqc.a(), rx.j, epy.a(ja.b, ehn.c(), ehn.c, 12), eqk.a(btf.a(-1)), ept.a());
      rx.a($$0, k, $$11, epx.a(188), eqc.a(), rx.j, epy.a(ja.b, ehn.a(ja.a), ehn.c, 12), eqk.a(btf.a(-1)), ept.a());
      rx.a($$0, l, $$12, epx.a(125), eqc.a(), rx.j, epy.a(ja.a, ehn.c(), ehn.c, 12), eqk.a(btf.a(1)), ept.a());
      rx.a($$0, m, $$13, epx.a(62), eqc.a(), rx.j, epy.a(ja.a, ehn.c(), ehn.c, 12), eqk.a(btf.a(1)), ept.a());
      rx.a($$0, n, $$14, epx.a(125), eqc.a(), rx.j, epy.a(ja.b, ehn.c(), ehn.c, 12), eqk.a(btf.a(-1)), ept.a());
      rx.a($$0, o, $$15, epx.a(25), eqc.a(), rx.j, epy.a(ja.b, ehn.c(), ehn.c, 12), eqk.a(btf.a(-1)), ept.a());
      rx.a($$0, p, $$16, epx.a(256), eqc.a(), rx.j, ept.a());
      rx.a($$0, q, $$17, eql.a(24), eqc.a(), eqa.a(eha.b(6), eha.a(30)), ept.a());
      rx.a($$0, r, $$18, epx.a(btf.a(256)), eqc.a(), rx.j, ept.a());
      rx.a($$0, s, $$19);
      rx.a($$0, t, $$20, epx.a(bto.a(204, 250)), eqc.a(), rx.j, ept.a());
   }
}
