public class rs {
   public static final ald<epm> a = rx.a("monster_room");
   public static final ald<epm> b = rx.a("monster_room_deep");
   public static final ald<epm> c = rx.a("fossil_upper");
   public static final ald<epm> d = rx.a("fossil_lower");
   public static final ald<epm> e = rx.a("dripstone_cluster");
   public static final ald<epm> f = rx.a("large_dripstone");
   public static final ald<epm> g = rx.a("pointed_dripstone");
   public static final ald<epm> h = rx.a("underwater_magma");
   public static final ald<epm> i = rx.a("glow_lichen");
   public static final ald<epm> j = rx.a("rooted_azalea_tree");
   public static final ald<epm> k = rx.a("cave_vines");
   public static final ald<epm> l = rx.a("lush_caves_vegetation");
   public static final ald<epm> m = rx.a("lush_caves_clay");
   public static final ald<epm> n = rx.a("lush_caves_ceiling_vegetation");
   public static final ald<epm> o = rx.a("spore_blossom");
   public static final ald<epm> p = rx.a("classic_vines_cave_feature");
   public static final ald<epm> q = rx.a("amethyst_geode");
   public static final ald<epm> r = rx.a("sculk_patch_deep_dark");
   public static final ald<epm> s = rx.a("sculk_patch_ancient_city");
   public static final ald<epm> t = rx.a("sculk_vein");

   public static void a(qh<epm> $$0) {
      jf<eif<?, ?>> $$1 = $$0.a(mg.aK);
      je<eif<?, ?>> $$2 = $$1.b(rg.a);
      je<eif<?, ?>> $$3 = $$1.b(rg.b);
      je<eif<?, ?>> $$4 = $$1.b(rg.c);
      je<eif<?, ?>> $$5 = $$1.b(rg.d);
      je<eif<?, ?>> $$6 = $$1.b(rg.e);
      je<eif<?, ?>> $$7 = $$1.b(rg.f);
      je<eif<?, ?>> $$8 = $$1.b(rg.g);
      je<eif<?, ?>> $$9 = $$1.b(rg.h);
      je<eif<?, ?>> $$10 = $$1.b(rg.i);
      je<eif<?, ?>> $$11 = $$1.b(rg.j);
      je<eif<?, ?>> $$12 = $$1.b(rg.m);
      je<eif<?, ?>> $$13 = $$1.b(rg.r);
      je<eif<?, ?>> $$14 = $$1.b(rg.s);
      je<eif<?, ?>> $$15 = $$1.b(rg.t);
      je<eif<?, ?>> $$16 = $$1.b(ro.c);
      je<eif<?, ?>> $$17 = $$1.b(rg.u);
      je<eif<?, ?>> $$18 = $$1.b(rg.v);
      je<eif<?, ?>> $$19 = $$1.b(rg.w);
      je<eif<?, ?>> $$20 = $$1.b(rg.x);
      rx.a($$0, a, $$2, epe.a(10), epj.a(), eph.a(egh.a(0), egh.b()), epa.a());
      rx.a($$0, b, $$2, epe.a(4), epj.a(), eph.a(egh.b(6), egh.a(-1)), epa.a());
      rx.a($$0, c, $$3, eps.a(64), epj.a(), eph.a(egh.a(0), egh.b()), epa.a());
      rx.a($$0, d, $$4, eps.a(64), epj.a(), eph.a(egh.a(), egh.a(-8)), epa.a());
      rx.a($$0, e, $$5, epe.a(btj.a(48, 96)), epj.a(), rx.j, epa.a());
      rx.a($$0, f, $$6, epe.a(btj.a(10, 48)), epj.a(), rx.j, epa.a());
      rx.a($$0, g, $$7, epe.a(btj.a(192, 256)), epj.a(), rx.j, epe.a(btj.a(1, 5)), epr.a(bsy.a(0.0F, 3.0F, -10, 10), bsy.a(0.0F, 0.6F, -2, 2)), epa.a());
      rx.a($$0, h, $$8, epe.a(btj.a(44, 52)), epj.a(), rx.j, epu.a(efn.a.c, Integer.MIN_VALUE, -2), epa.a());
      rx.a($$0, i, $$9, epe.a(btj.a(104, 157)), rx.j, epj.a(), epu.a(efn.a.c, Integer.MIN_VALUE, -13), epa.a());
      rx.a($$0, j, $$10, epe.a(btj.a(1, 2)), epj.a(), rx.j, epf.a(ja.b, egu.c(), egu.c, 12), epr.a(bta.a(-1)), epa.a());
      rx.a($$0, k, $$11, epe.a(188), epj.a(), rx.j, epf.a(ja.b, egu.a(ja.a), egu.c, 12), epr.a(bta.a(-1)), epa.a());
      rx.a($$0, l, $$12, epe.a(125), epj.a(), rx.j, epf.a(ja.a, egu.c(), egu.c, 12), epr.a(bta.a(1)), epa.a());
      rx.a($$0, m, $$13, epe.a(62), epj.a(), rx.j, epf.a(ja.a, egu.c(), egu.c, 12), epr.a(bta.a(1)), epa.a());
      rx.a($$0, n, $$14, epe.a(125), epj.a(), rx.j, epf.a(ja.b, egu.c(), egu.c, 12), epr.a(bta.a(-1)), epa.a());
      rx.a($$0, o, $$15, epe.a(25), epj.a(), rx.j, epf.a(ja.b, egu.c(), egu.c, 12), epr.a(bta.a(-1)), epa.a());
      rx.a($$0, p, $$16, epe.a(256), epj.a(), rx.j, epa.a());
      rx.a($$0, q, $$17, eps.a(24), epj.a(), eph.a(egh.b(6), egh.a(30)), epa.a());
      rx.a($$0, r, $$18, epe.a(bta.a(256)), epj.a(), rx.j, epa.a());
      rx.a($$0, s, $$19);
      rx.a($$0, t, $$20, epe.a(btj.a(204, 250)), epj.a(), rx.j, epa.a());
   }
}
