import java.util.List;

public class ru {
   public static final aju<eeu> a = rt.a("crimson_fungi");
   public static final aju<eeu> b = rt.a("warped_fungi");
   public static final aju<eeu> c = rt.a("oak_checked");
   public static final aju<eeu> d = rt.a("dark_oak_checked");
   public static final aju<eeu> e = rt.a("birch_checked");
   public static final aju<eeu> f = rt.a("acacia_checked");
   public static final aju<eeu> g = rt.a("spruce_checked");
   public static final aju<eeu> h = rt.a("mangrove_checked");
   public static final aju<eeu> i = rt.a("cherry_checked");
   public static final aju<eeu> j = rt.a("pine_on_snow");
   public static final aju<eeu> k = rt.a("spruce_on_snow");
   public static final aju<eeu> l = rt.a("pine_checked");
   public static final aju<eeu> m = rt.a("jungle_tree");
   public static final aju<eeu> n = rt.a("fancy_oak_checked");
   public static final aju<eeu> o = rt.a("mega_jungle_tree_checked");
   public static final aju<eeu> p = rt.a("mega_spruce_checked");
   public static final aju<eeu> q = rt.a("mega_pine_checked");
   public static final aju<eeu> r = rt.a("tall_mangrove_checked");
   public static final aju<eeu> s = rt.a("jungle_bush");
   public static final aju<eeu> t = rt.a("super_birch_bees_0002");
   public static final aju<eeu> u = rt.a("super_birch_bees");
   public static final aju<eeu> v = rt.a("oak_bees_0002");
   public static final aju<eeu> w = rt.a("oak_bees_002");
   public static final aju<eeu> x = rt.a("birch_bees_0002");
   public static final aju<eeu> y = rt.a("birch_bees_002");
   public static final aju<eeu> z = rt.a("fancy_oak_bees_0002");
   public static final aju<eeu> A = rt.a("fancy_oak_bees_002");
   public static final aju<eeu> B = rt.a("fancy_oak_bees");
   public static final aju<eeu> C = rt.a("cherry_bees_005");

   public static void a(pz<eeu> $$0) {
      io<dxr<?, ?>> $$1 = $$0.a(ku.az);
      in<dxr<?, ?>> $$2 = $$1.b(rj.a);
      in<dxr<?, ?>> $$3 = $$1.b(rj.c);
      in<dxr<?, ?>> $$4 = $$1.b(rj.g);
      in<dxr<?, ?>> $$5 = $$1.b(rj.h);
      in<dxr<?, ?>> $$6 = $$1.b(rj.i);
      in<dxr<?, ?>> $$7 = $$1.b(rj.j);
      in<dxr<?, ?>> $$8 = $$1.b(rj.k);
      in<dxr<?, ?>> $$9 = $$1.b(rj.x);
      in<dxr<?, ?>> $$10 = $$1.b(rj.z);
      in<dxr<?, ?>> $$11 = $$1.b(rj.l);
      in<dxr<?, ?>> $$12 = $$1.b(rj.m);
      in<dxr<?, ?>> $$13 = $$1.b(rj.n);
      in<dxr<?, ?>> $$14 = $$1.b(rj.p);
      in<dxr<?, ?>> $$15 = $$1.b(rj.q);
      in<dxr<?, ?>> $$16 = $$1.b(rj.r);
      in<dxr<?, ?>> $$17 = $$1.b(rj.y);
      in<dxr<?, ?>> $$18 = $$1.b(rj.v);
      in<dxr<?, ?>> $$19 = $$1.b(rj.s);
      in<dxr<?, ?>> $$20 = $$1.b(rj.t);
      in<dxr<?, ?>> $$21 = $$1.b(rj.A);
      in<dxr<?, ?>> $$22 = $$1.b(rj.B);
      in<dxr<?, ?>> $$23 = $$1.b(rj.D);
      in<dxr<?, ?>> $$24 = $$1.b(rj.E);
      in<dxr<?, ?>> $$25 = $$1.b(rj.G);
      in<dxr<?, ?>> $$26 = $$1.b(rj.H);
      in<dxr<?, ?>> $$27 = $$1.b(rj.J);
      in<dxr<?, ?>> $$28 = $$1.b(rj.K);
      rt.a($$0, a, $$2, eem.a(8), eei.a());
      rt.a($$0, b, $$3, eem.a(8), eei.a());
      rt.a($$0, c, $$4, rt.a(dcj.x));
      rt.a($$0, d, $$5, rt.a(dcj.D));
      rt.a($$0, e, $$6, rt.a(dcj.z));
      rt.a($$0, f, $$7, rt.a(dcj.B));
      rt.a($$0, g, $$8, rt.a(dcj.y));
      rt.a($$0, h, $$9, rt.a(dcj.E));
      rt.a($$0, i, $$10, rt.a(dcj.C));
      dwh $$29 = dwh.a(ij.a.q(), dcj.dP, dcj.qP);
      List<eex> $$30 = List.of(eeo.a(ij.b, dwh.a(dwh.a(dcj.qP)), 8), eej.a($$29));
      rt.a($$0, j, $$11, $$30);
      rt.a($$0, k, $$8, $$30);
      rt.a($$0, l, $$11, rt.a(dcj.y));
      rt.a($$0, m, $$12, rt.a(dcj.A));
      rt.a($$0, n, $$13, rt.a(dcj.x));
      rt.a($$0, o, $$14, rt.a(dcj.A));
      rt.a($$0, p, $$15, rt.a(dcj.y));
      rt.a($$0, q, $$16, rt.a(dcj.y));
      rt.a($$0, r, $$17, rt.a(dcj.E));
      rt.a($$0, s, $$18, rt.a(dcj.x));
      rt.a($$0, t, $$19, rt.a(dcj.z));
      rt.a($$0, u, $$20, rt.a(dcj.z));
      rt.a($$0, v, $$21, rt.a(dcj.x));
      rt.a($$0, w, $$22, rt.a(dcj.x));
      rt.a($$0, x, $$23, rt.a(dcj.z));
      rt.a($$0, y, $$24, rt.a(dcj.z));
      rt.a($$0, z, $$25, rt.a(dcj.x));
      rt.a($$0, A, $$26, rt.a(dcj.x));
      rt.a($$0, B, $$27, rt.a(dcj.x));
      rt.a($$0, C, $$28, rt.a(dcj.C));
   }
}
