import java.util.List;

public class rv {
   public static final aku<emr> a = ru.a("crimson_fungi");
   public static final aku<emr> b = ru.a("warped_fungi");
   public static final aku<emr> c = ru.a("oak_checked");
   public static final aku<emr> d = ru.a("dark_oak_checked");
   public static final aku<emr> e = ru.a("pale_oak_checked");
   public static final aku<emr> f = ru.a("pale_oak_creaking_checked");
   public static final aku<emr> g = ru.a("birch_checked");
   public static final aku<emr> h = ru.a("acacia_checked");
   public static final aku<emr> i = ru.a("spruce_checked");
   public static final aku<emr> j = ru.a("mangrove_checked");
   public static final aku<emr> k = ru.a("cherry_checked");
   public static final aku<emr> l = ru.a("pine_on_snow");
   public static final aku<emr> m = ru.a("spruce_on_snow");
   public static final aku<emr> n = ru.a("pine_checked");
   public static final aku<emr> o = ru.a("jungle_tree");
   public static final aku<emr> p = ru.a("fancy_oak_checked");
   public static final aku<emr> q = ru.a("mega_jungle_tree_checked");
   public static final aku<emr> r = ru.a("mega_spruce_checked");
   public static final aku<emr> s = ru.a("mega_pine_checked");
   public static final aku<emr> t = ru.a("tall_mangrove_checked");
   public static final aku<emr> u = ru.a("jungle_bush");
   public static final aku<emr> v = ru.a("super_birch_bees_0002");
   public static final aku<emr> w = ru.a("super_birch_bees");
   public static final aku<emr> x = ru.a("oak_bees_0002");
   public static final aku<emr> y = ru.a("oak_bees_002");
   public static final aku<emr> z = ru.a("birch_bees_0002");
   public static final aku<emr> A = ru.a("birch_bees_002");
   public static final aku<emr> B = ru.a("fancy_oak_bees_0002");
   public static final aku<emr> C = ru.a("fancy_oak_bees_002");
   public static final aku<emr> D = ru.a("fancy_oak_bees");
   public static final aku<emr> E = ru.a("cherry_bees_005");

   public static void a(qe<emr> $$0) {
      js<efl<?, ?>> $$1 = $$0.a(mc.aL);
      jr<efl<?, ?>> $$2 = $$1.b(rk.a);
      jr<efl<?, ?>> $$3 = $$1.b(rk.c);
      jr<efl<?, ?>> $$4 = $$1.b(rk.g);
      jr<efl<?, ?>> $$5 = $$1.b(rk.h);
      jr<efl<?, ?>> $$6 = $$1.b(rk.i);
      jr<efl<?, ?>> $$7 = $$1.b(rk.k);
      jr<efl<?, ?>> $$8 = $$1.b(rk.l);
      jr<efl<?, ?>> $$9 = $$1.b(rk.m);
      jr<efl<?, ?>> $$10 = $$1.b(rk.n);
      jr<efl<?, ?>> $$11 = $$1.b(rk.A);
      jr<efl<?, ?>> $$12 = $$1.b(rk.C);
      jr<efl<?, ?>> $$13 = $$1.b(rk.o);
      jr<efl<?, ?>> $$14 = $$1.b(rk.p);
      jr<efl<?, ?>> $$15 = $$1.b(rk.q);
      jr<efl<?, ?>> $$16 = $$1.b(rk.s);
      jr<efl<?, ?>> $$17 = $$1.b(rk.t);
      jr<efl<?, ?>> $$18 = $$1.b(rk.u);
      jr<efl<?, ?>> $$19 = $$1.b(rk.B);
      jr<efl<?, ?>> $$20 = $$1.b(rk.y);
      jr<efl<?, ?>> $$21 = $$1.b(rk.v);
      jr<efl<?, ?>> $$22 = $$1.b(rk.w);
      jr<efl<?, ?>> $$23 = $$1.b(rk.D);
      jr<efl<?, ?>> $$24 = $$1.b(rk.E);
      jr<efl<?, ?>> $$25 = $$1.b(rk.G);
      jr<efl<?, ?>> $$26 = $$1.b(rk.H);
      jr<efl<?, ?>> $$27 = $$1.b(rk.J);
      jr<efl<?, ?>> $$28 = $$1.b(rk.K);
      jr<efl<?, ?>> $$29 = $$1.b(rk.M);
      jr<efl<?, ?>> $$30 = $$1.b(rk.N);
      ru.a($$0, a, $$2, emi.a(8), emf.a());
      ru.a($$0, b, $$3, emi.a(8), emf.a());
      ru.a($$0, c, $$4, ru.a(djp.z));
      ru.a($$0, d, $$5, ru.a(djp.F));
      ru.a($$0, e, $$6, ru.a(djp.G));
      ru.a($$0, f, $$7, ru.a(djp.G));
      ru.a($$0, g, $$8, ru.a(djp.B));
      ru.a($$0, h, $$9, ru.a(djp.D));
      ru.a($$0, i, $$10, ru.a(djp.A));
      ru.a($$0, j, $$11, ru.a(djp.H));
      ru.a($$0, k, $$12, ru.a(djp.E));
      eea $$31 = eea.a(jn.a.q(), djp.ec, djp.rr);
      List<emu> $$32 = List.of(emk.a(jn.b, eea.a(eea.a(djp.rr)), 8), emg.a($$31));
      ru.a($$0, l, $$13, $$32);
      ru.a($$0, m, $$10, $$32);
      ru.a($$0, n, $$13, ru.a(djp.A));
      ru.a($$0, o, $$14, ru.a(djp.C));
      ru.a($$0, p, $$15, ru.a(djp.z));
      ru.a($$0, q, $$16, ru.a(djp.C));
      ru.a($$0, r, $$17, ru.a(djp.A));
      ru.a($$0, s, $$18, ru.a(djp.A));
      ru.a($$0, t, $$19, ru.a(djp.H));
      ru.a($$0, u, $$20, ru.a(djp.z));
      ru.a($$0, v, $$21, ru.a(djp.B));
      ru.a($$0, w, $$22, ru.a(djp.B));
      ru.a($$0, x, $$23, ru.a(djp.z));
      ru.a($$0, y, $$24, ru.a(djp.z));
      ru.a($$0, z, $$25, ru.a(djp.B));
      ru.a($$0, A, $$26, ru.a(djp.B));
      ru.a($$0, B, $$27, ru.a(djp.z));
      ru.a($$0, C, $$28, ru.a(djp.z));
      ru.a($$0, D, $$29, ru.a(djp.z));
      ru.a($$0, E, $$30, ru.a(djp.E));
   }
}
