import java.util.List;

public class rv {
   public static final aku<emp> a = ru.a("crimson_fungi");
   public static final aku<emp> b = ru.a("warped_fungi");
   public static final aku<emp> c = ru.a("oak_checked");
   public static final aku<emp> d = ru.a("dark_oak_checked");
   public static final aku<emp> e = ru.a("pale_oak_checked");
   public static final aku<emp> f = ru.a("pale_oak_creaking_checked");
   public static final aku<emp> g = ru.a("birch_checked");
   public static final aku<emp> h = ru.a("acacia_checked");
   public static final aku<emp> i = ru.a("spruce_checked");
   public static final aku<emp> j = ru.a("mangrove_checked");
   public static final aku<emp> k = ru.a("cherry_checked");
   public static final aku<emp> l = ru.a("pine_on_snow");
   public static final aku<emp> m = ru.a("spruce_on_snow");
   public static final aku<emp> n = ru.a("pine_checked");
   public static final aku<emp> o = ru.a("jungle_tree");
   public static final aku<emp> p = ru.a("fancy_oak_checked");
   public static final aku<emp> q = ru.a("mega_jungle_tree_checked");
   public static final aku<emp> r = ru.a("mega_spruce_checked");
   public static final aku<emp> s = ru.a("mega_pine_checked");
   public static final aku<emp> t = ru.a("tall_mangrove_checked");
   public static final aku<emp> u = ru.a("jungle_bush");
   public static final aku<emp> v = ru.a("super_birch_bees_0002");
   public static final aku<emp> w = ru.a("super_birch_bees");
   public static final aku<emp> x = ru.a("oak_bees_0002");
   public static final aku<emp> y = ru.a("oak_bees_002");
   public static final aku<emp> z = ru.a("birch_bees_0002");
   public static final aku<emp> A = ru.a("birch_bees_002");
   public static final aku<emp> B = ru.a("fancy_oak_bees_0002");
   public static final aku<emp> C = ru.a("fancy_oak_bees_002");
   public static final aku<emp> D = ru.a("fancy_oak_bees");
   public static final aku<emp> E = ru.a("cherry_bees_005");

   public static void a(qe<emp> $$0) {
      js<efj<?, ?>> $$1 = $$0.a(mc.aL);
      jr<efj<?, ?>> $$2 = $$1.b(rk.a);
      jr<efj<?, ?>> $$3 = $$1.b(rk.c);
      jr<efj<?, ?>> $$4 = $$1.b(rk.g);
      jr<efj<?, ?>> $$5 = $$1.b(rk.h);
      jr<efj<?, ?>> $$6 = $$1.b(rk.i);
      jr<efj<?, ?>> $$7 = $$1.b(rk.k);
      jr<efj<?, ?>> $$8 = $$1.b(rk.l);
      jr<efj<?, ?>> $$9 = $$1.b(rk.m);
      jr<efj<?, ?>> $$10 = $$1.b(rk.n);
      jr<efj<?, ?>> $$11 = $$1.b(rk.A);
      jr<efj<?, ?>> $$12 = $$1.b(rk.C);
      jr<efj<?, ?>> $$13 = $$1.b(rk.o);
      jr<efj<?, ?>> $$14 = $$1.b(rk.p);
      jr<efj<?, ?>> $$15 = $$1.b(rk.q);
      jr<efj<?, ?>> $$16 = $$1.b(rk.s);
      jr<efj<?, ?>> $$17 = $$1.b(rk.t);
      jr<efj<?, ?>> $$18 = $$1.b(rk.u);
      jr<efj<?, ?>> $$19 = $$1.b(rk.B);
      jr<efj<?, ?>> $$20 = $$1.b(rk.y);
      jr<efj<?, ?>> $$21 = $$1.b(rk.v);
      jr<efj<?, ?>> $$22 = $$1.b(rk.w);
      jr<efj<?, ?>> $$23 = $$1.b(rk.D);
      jr<efj<?, ?>> $$24 = $$1.b(rk.E);
      jr<efj<?, ?>> $$25 = $$1.b(rk.G);
      jr<efj<?, ?>> $$26 = $$1.b(rk.H);
      jr<efj<?, ?>> $$27 = $$1.b(rk.J);
      jr<efj<?, ?>> $$28 = $$1.b(rk.K);
      jr<efj<?, ?>> $$29 = $$1.b(rk.M);
      jr<efj<?, ?>> $$30 = $$1.b(rk.N);
      ru.a($$0, a, $$2, emg.a(8), emd.a());
      ru.a($$0, b, $$3, emg.a(8), emd.a());
      ru.a($$0, c, $$4, ru.a(djn.z));
      ru.a($$0, d, $$5, ru.a(djn.F));
      ru.a($$0, e, $$6, ru.a(djn.G));
      ru.a($$0, f, $$7, ru.a(djn.G));
      ru.a($$0, g, $$8, ru.a(djn.B));
      ru.a($$0, h, $$9, ru.a(djn.D));
      ru.a($$0, i, $$10, ru.a(djn.A));
      ru.a($$0, j, $$11, ru.a(djn.H));
      ru.a($$0, k, $$12, ru.a(djn.E));
      edy $$31 = edy.a(jn.a.q(), djn.ec, djn.rr);
      List<ems> $$32 = List.of(emi.a(jn.b, edy.a(edy.a(djn.rr)), 8), eme.a($$31));
      ru.a($$0, l, $$13, $$32);
      ru.a($$0, m, $$10, $$32);
      ru.a($$0, n, $$13, ru.a(djn.A));
      ru.a($$0, o, $$14, ru.a(djn.C));
      ru.a($$0, p, $$15, ru.a(djn.z));
      ru.a($$0, q, $$16, ru.a(djn.C));
      ru.a($$0, r, $$17, ru.a(djn.A));
      ru.a($$0, s, $$18, ru.a(djn.A));
      ru.a($$0, t, $$19, ru.a(djn.H));
      ru.a($$0, u, $$20, ru.a(djn.z));
      ru.a($$0, v, $$21, ru.a(djn.B));
      ru.a($$0, w, $$22, ru.a(djn.B));
      ru.a($$0, x, $$23, ru.a(djn.z));
      ru.a($$0, y, $$24, ru.a(djn.z));
      ru.a($$0, z, $$25, ru.a(djn.B));
      ru.a($$0, A, $$26, ru.a(djn.B));
      ru.a($$0, B, $$27, ru.a(djn.z));
      ru.a($$0, C, $$28, ru.a(djn.z));
      ru.a($$0, D, $$29, ru.a(djn.z));
      ru.a($$0, E, $$30, ru.a(djn.E));
   }
}
