public class rx {
   public static final akj<eia> a = sc.a("monster_room");
   public static final akj<eia> b = sc.a("monster_room_deep");
   public static final akj<eia> c = sc.a("fossil_upper");
   public static final akj<eia> d = sc.a("fossil_lower");
   public static final akj<eia> e = sc.a("dripstone_cluster");
   public static final akj<eia> f = sc.a("large_dripstone");
   public static final akj<eia> g = sc.a("pointed_dripstone");
   public static final akj<eia> h = sc.a("underwater_magma");
   public static final akj<eia> i = sc.a("glow_lichen");
   public static final akj<eia> j = sc.a("rooted_azalea_tree");
   public static final akj<eia> k = sc.a("cave_vines");
   public static final akj<eia> l = sc.a("lush_caves_vegetation");
   public static final akj<eia> m = sc.a("lush_caves_clay");
   public static final akj<eia> n = sc.a("lush_caves_ceiling_vegetation");
   public static final akj<eia> o = sc.a("spore_blossom");
   public static final akj<eia> p = sc.a("classic_vines_cave_feature");
   public static final akj<eia> q = sc.a("amethyst_geode");
   public static final akj<eia> r = sc.a("sculk_patch_deep_dark");
   public static final akj<eia> s = sc.a("sculk_patch_ancient_city");
   public static final akj<eia> t = sc.a("sculk_vein");

   public static void a(qm<eia> $$0) {
      jk<eax<?, ?>> $$1 = $$0.a(lr.aH);
      jj<eax<?, ?>> $$2 = $$1.b(rl.a);
      jj<eax<?, ?>> $$3 = $$1.b(rl.b);
      jj<eax<?, ?>> $$4 = $$1.b(rl.c);
      jj<eax<?, ?>> $$5 = $$1.b(rl.d);
      jj<eax<?, ?>> $$6 = $$1.b(rl.e);
      jj<eax<?, ?>> $$7 = $$1.b(rl.f);
      jj<eax<?, ?>> $$8 = $$1.b(rl.g);
      jj<eax<?, ?>> $$9 = $$1.b(rl.h);
      jj<eax<?, ?>> $$10 = $$1.b(rl.i);
      jj<eax<?, ?>> $$11 = $$1.b(rl.j);
      jj<eax<?, ?>> $$12 = $$1.b(rl.m);
      jj<eax<?, ?>> $$13 = $$1.b(rl.r);
      jj<eax<?, ?>> $$14 = $$1.b(rl.s);
      jj<eax<?, ?>> $$15 = $$1.b(rl.t);
      jj<eax<?, ?>> $$16 = $$1.b(rt.c);
      jj<eax<?, ?>> $$17 = $$1.b(rl.u);
      jj<eax<?, ?>> $$18 = $$1.b(rl.v);
      jj<eax<?, ?>> $$19 = $$1.b(rl.w);
      jj<eax<?, ?>> $$20 = $$1.b(rl.x);
      sc.a($$0, a, $$2, eht.a(10), ehx.a(), ehv.a(dyz.a(0), dyz.b()), eho.a());
      sc.a($$0, b, $$2, eht.a(4), ehx.a(), ehv.a(dyz.b(6), dyz.a(-1)), eho.a());
      sc.a($$0, c, $$3, eig.a(64), ehx.a(), ehv.a(dyz.a(0), dyz.b()), eho.a());
      sc.a($$0, d, $$4, eig.a(64), ehx.a(), ehv.a(dyz.a(), dyz.a(-8)), eho.a());
      sc.a($$0, e, $$5, eht.a(bpr.a(48, 96)), ehx.a(), sc.i, eho.a());
      sc.a($$0, f, $$6, eht.a(bpr.a(10, 48)), ehx.a(), sc.i, eho.a());
      sc.a($$0, g, $$7, eht.a(bpr.a(192, 256)), ehx.a(), sc.i, eht.a(bpr.a(1, 5)), eif.a(bpg.a(0.0F, 3.0F, -10, 10), bpg.a(0.0F, 0.6F, -2, 2)), eho.a());
      sc.a($$0, h, $$8, eht.a(bpr.a(44, 52)), ehx.a(), sc.i, eii.a(dyf.a.c, Integer.MIN_VALUE, -2), eho.a());
      sc.a($$0, i, $$9, eht.a(bpr.a(104, 157)), sc.i, ehx.a(), eii.a(dyf.a.c, Integer.MIN_VALUE, -13), eho.a());
      sc.a($$0, j, $$10, eht.a(bpr.a(1, 2)), ehx.a(), sc.i, ehu.a(jf.b, dzm.c(), dzm.c, 12), eif.a(bpi.a(-1)), eho.a());
      sc.a($$0, k, $$11, eht.a(188), ehx.a(), sc.i, ehu.a(jf.b, dzm.a(jf.a), dzm.c, 12), eif.a(bpi.a(-1)), eho.a());
      sc.a($$0, l, $$12, eht.a(125), ehx.a(), sc.i, ehu.a(jf.a, dzm.c(), dzm.c, 12), eif.a(bpi.a(1)), eho.a());
      sc.a($$0, m, $$13, eht.a(62), ehx.a(), sc.i, ehu.a(jf.a, dzm.c(), dzm.c, 12), eif.a(bpi.a(1)), eho.a());
      sc.a($$0, n, $$14, eht.a(125), ehx.a(), sc.i, ehu.a(jf.b, dzm.c(), dzm.c, 12), eif.a(bpi.a(-1)), eho.a());
      sc.a($$0, o, $$15, eht.a(25), ehx.a(), sc.i, ehu.a(jf.b, dzm.c(), dzm.c, 12), eif.a(bpi.a(-1)), eho.a());
      sc.a($$0, p, $$16, eht.a(256), ehx.a(), sc.i, eho.a());
      sc.a($$0, q, $$17, eig.a(24), ehx.a(), ehv.a(dyz.b(6), dyz.a(30)), eho.a());
      sc.a($$0, r, $$18, eht.a(bpi.a(256)), ehx.a(), sc.i, eho.a());
      sc.a($$0, s, $$19);
      sc.a($$0, t, $$20, eht.a(bpr.a(204, 250)), ehx.a(), sc.i, eho.a());
   }
}
