import java.util.List;

public class rx {
   public static final alb<edc<?, ?>> a = ru.a("ore_magma");
   public static final alb<edc<?, ?>> b = ru.a("ore_soul_sand");
   public static final alb<edc<?, ?>> c = ru.a("ore_nether_gold");
   public static final alb<edc<?, ?>> d = ru.a("ore_quartz");
   public static final alb<edc<?, ?>> e = ru.a("ore_gravel_nether");
   public static final alb<edc<?, ?>> f = ru.a("ore_blackstone");
   public static final alb<edc<?, ?>> g = ru.a("ore_dirt");
   public static final alb<edc<?, ?>> h = ru.a("ore_gravel");
   public static final alb<edc<?, ?>> i = ru.a("ore_granite");
   public static final alb<edc<?, ?>> j = ru.a("ore_diorite");
   public static final alb<edc<?, ?>> k = ru.a("ore_andesite");
   public static final alb<edc<?, ?>> l = ru.a("ore_tuff");
   public static final alb<edc<?, ?>> m = ru.a("ore_coal");
   public static final alb<edc<?, ?>> n = ru.a("ore_coal_buried");
   public static final alb<edc<?, ?>> o = ru.a("ore_iron");
   public static final alb<edc<?, ?>> p = ru.a("ore_iron_small");
   public static final alb<edc<?, ?>> q = ru.a("ore_gold");
   public static final alb<edc<?, ?>> r = ru.a("ore_gold_buried");
   public static final alb<edc<?, ?>> s = ru.a("ore_redstone");
   public static final alb<edc<?, ?>> t = ru.a("ore_diamond_small");
   public static final alb<edc<?, ?>> u = ru.a("ore_diamond_medium");
   public static final alb<edc<?, ?>> v = ru.a("ore_diamond_large");
   public static final alb<edc<?, ?>> w = ru.a("ore_diamond_buried");
   public static final alb<edc<?, ?>> x = ru.a("ore_lapis");
   public static final alb<edc<?, ?>> y = ru.a("ore_lapis_buried");
   public static final alb<edc<?, ?>> z = ru.a("ore_infested");
   public static final alb<edc<?, ?>> A = ru.a("ore_emerald");
   public static final alb<edc<?, ?>> B = ru.a("ore_ancient_debris_large");
   public static final alb<edc<?, ?>> C = ru.a("ore_ancient_debris_small");
   public static final alb<edc<?, ?>> D = ru.a("ore_copper_small");
   public static final alb<edc<?, ?>> E = ru.a("ore_copper_large");
   public static final alb<edc<?, ?>> F = ru.a("ore_clay");

   public static void a(qt<edc<?, ?>> $$0) {
      eoy $$1 = new epg(awt.bf);
      eoy $$2 = new epg(awt.bg);
      eoy $$3 = new epg(awt.bh);
      eoy $$4 = new eog(dhl.dV);
      eoy $$5 = new epg(awt.bi);
      List<egc.a> $$6 = List.of(egc.a($$2, dhl.P.o()), egc.a($$3, dhl.Q.o()));
      List<egc.a> $$7 = List.of(egc.a($$2, dhl.N.o()), egc.a($$3, dhl.O.o()));
      List<egc.a> $$8 = List.of(egc.a($$2, dhl.cx.o()), egc.a($$3, dhl.cy.o()));
      List<egc.a> $$9 = List.of(egc.a($$2, dhl.aR.o()), egc.a($$3, dhl.aS.o()));
      List<egc.a> $$10 = List.of(egc.a($$2, dhl.ra.o()), egc.a($$3, dhl.rb.o()));
      List<egc.a> $$11 = List.of(egc.a($$2, dhl.R.o()), egc.a($$3, dhl.S.o()));
      ru.a($$0, a, edq.I, new egc($$4, dhl.kJ.o(), 33));
      ru.a($$0, b, edq.I, new egc($$4, dhl.dW.o(), 12));
      ru.a($$0, c, edq.I, new egc($$4, dhl.T.o(), 10));
      ru.a($$0, d, edq.I, new egc($$4, dhl.hb.o(), 14));
      ru.a($$0, e, edq.I, new egc($$4, dhl.L.o(), 33));
      ru.a($$0, f, edq.I, new egc($$4, dhl.pr.o(), 33));
      ru.a($$0, g, edq.I, new egc($$1, dhl.j.o(), 33));
      ru.a($$0, h, edq.I, new egc($$1, dhl.L.o(), 33));
      ru.a($$0, i, edq.I, new egc($$1, dhl.c.o(), 64));
      ru.a($$0, j, edq.I, new egc($$1, dhl.e.o(), 64));
      ru.a($$0, k, edq.I, new egc($$1, dhl.g.o(), 64));
      ru.a($$0, l, edq.I, new egc($$1, dhl.qz.o(), 64));
      ru.a($$0, m, edq.I, new egc($$11, 17));
      ru.a($$0, n, edq.I, new egc($$11, 17, 0.5F));
      ru.a($$0, o, edq.I, new egc($$6, 9));
      ru.a($$0, p, edq.I, new egc($$6, 4));
      ru.a($$0, q, edq.I, new egc($$7, 9));
      ru.a($$0, r, edq.I, new egc($$7, 9, 0.5F));
      ru.a($$0, s, edq.I, new egc(List.of(egc.a($$2, dhl.dI.o()), egc.a($$3, dhl.dJ.o())), 8));
      ru.a($$0, t, edq.I, new egc($$8, 4, 0.5F));
      ru.a($$0, v, edq.I, new egc($$8, 12, 0.7F));
      ru.a($$0, w, edq.I, new egc($$8, 8, 1.0F));
      ru.a($$0, u, edq.I, new egc($$8, 8, 0.5F));
      ru.a($$0, x, edq.I, new egc($$9, 7));
      ru.a($$0, y, edq.I, new egc($$9, 7, 1.0F));
      ru.a($$0, z, edq.I, new egc(List.of(egc.a($$2, dhl.eN.o()), egc.a($$3, dhl.td.o())), 9));
      ru.a($$0, A, edq.I, new egc(List.of(egc.a($$2, dhl.fE.o()), egc.a($$3, dhl.fF.o())), 3));
      ru.a($$0, B, edq.af, new egc($$5, dhl.pj.o(), 3, 1.0F));
      ru.a($$0, C, edq.af, new egc($$5, dhl.pj.o(), 2, 1.0F));
      ru.a($$0, D, edq.I, new egc($$10, 10));
      ru.a($$0, E, edq.I, new egc($$10, 20));
      ru.a($$0, F, edq.I, new egc($$1, dhl.dR.o(), 33));
   }
}
