import java.util.List;

public class ry {
   public static final alf<eqm> a = rx.a("crimson_fungi");
   public static final alf<eqm> b = rx.a("warped_fungi");
   public static final alf<eqm> c = rx.a("oak_checked");
   public static final alf<eqm> d = rx.a("dark_oak_checked");
   public static final alf<eqm> e = rx.a("pale_oak_checked");
   public static final alf<eqm> f = rx.a("pale_oak_creaking_checked");
   public static final alf<eqm> g = rx.a("birch_checked");
   public static final alf<eqm> h = rx.a("acacia_checked");
   public static final alf<eqm> i = rx.a("spruce_checked");
   public static final alf<eqm> j = rx.a("mangrove_checked");
   public static final alf<eqm> k = rx.a("cherry_checked");
   public static final alf<eqm> l = rx.a("pine_on_snow");
   public static final alf<eqm> m = rx.a("spruce_on_snow");
   public static final alf<eqm> n = rx.a("pine_checked");
   public static final alf<eqm> o = rx.a("jungle_tree");
   public static final alf<eqm> p = rx.a("fancy_oak_checked");
   public static final alf<eqm> q = rx.a("mega_jungle_tree_checked");
   public static final alf<eqm> r = rx.a("mega_spruce_checked");
   public static final alf<eqm> s = rx.a("mega_pine_checked");
   public static final alf<eqm> t = rx.a("tall_mangrove_checked");
   public static final alf<eqm> u = rx.a("jungle_bush");
   public static final alf<eqm> v = rx.a("super_birch_bees_0002");
   public static final alf<eqm> w = rx.a("super_birch_bees");
   public static final alf<eqm> x = rx.a("oak_bees_0002_leaf_litter");
   public static final alf<eqm> y = rx.a("oak_bees_002");
   public static final alf<eqm> z = rx.a("birch_bees_0002");
   public static final alf<eqm> A = rx.a("birch_bees_0002_leaf_litter");
   public static final alf<eqm> B = rx.a("birch_bees_002");
   public static final alf<eqm> C = rx.a("fancy_oak_bees_0002_leaf_litter");
   public static final alf<eqm> D = rx.a("fancy_oak_bees_002");
   public static final alf<eqm> E = rx.a("fancy_oak_bees");
   public static final alf<eqm> F = rx.a("cherry_bees_005");
   public static final alf<eqm> G = rx.a("oak_leaf_litter");
   public static final alf<eqm> H = rx.a("dark_oak_leaf_litter");
   public static final alf<eqm> I = rx.a("birch_leaf_litter");
   public static final alf<eqm> J = rx.a("fancy_oak_leaf_litter");

   public static void a(qh<eqm> $$0) {
      jg<ejf<?, ?>> $$1 = $$0.a(mh.aL);
      jf<ejf<?, ?>> $$2 = $$1.b(rn.a);
      jf<ejf<?, ?>> $$3 = $$1.b(rn.c);
      jf<ejf<?, ?>> $$4 = $$1.b(rn.g);
      jf<ejf<?, ?>> $$5 = $$1.b(rn.h);
      jf<ejf<?, ?>> $$6 = $$1.b(rn.i);
      jf<ejf<?, ?>> $$7 = $$1.b(rn.k);
      jf<ejf<?, ?>> $$8 = $$1.b(rn.l);
      jf<ejf<?, ?>> $$9 = $$1.b(rn.m);
      jf<ejf<?, ?>> $$10 = $$1.b(rn.n);
      jf<ejf<?, ?>> $$11 = $$1.b(rn.A);
      jf<ejf<?, ?>> $$12 = $$1.b(rn.C);
      jf<ejf<?, ?>> $$13 = $$1.b(rn.o);
      jf<ejf<?, ?>> $$14 = $$1.b(rn.p);
      jf<ejf<?, ?>> $$15 = $$1.b(rn.q);
      jf<ejf<?, ?>> $$16 = $$1.b(rn.s);
      jf<ejf<?, ?>> $$17 = $$1.b(rn.t);
      jf<ejf<?, ?>> $$18 = $$1.b(rn.u);
      jf<ejf<?, ?>> $$19 = $$1.b(rn.B);
      jf<ejf<?, ?>> $$20 = $$1.b(rn.y);
      jf<ejf<?, ?>> $$21 = $$1.b(rn.v);
      jf<ejf<?, ?>> $$22 = $$1.b(rn.w);
      jf<ejf<?, ?>> $$23 = $$1.b(rn.D);
      jf<ejf<?, ?>> $$24 = $$1.b(rn.E);
      jf<ejf<?, ?>> $$25 = $$1.b(rn.G);
      jf<ejf<?, ?>> $$26 = $$1.b(rn.H);
      jf<ejf<?, ?>> $$27 = $$1.b(rn.I);
      jf<ejf<?, ?>> $$28 = $$1.b(rn.K);
      jf<ejf<?, ?>> $$29 = $$1.b(rn.L);
      jf<ejf<?, ?>> $$30 = $$1.b(rn.N);
      jf<ejf<?, ?>> $$31 = $$1.b(rn.O);
      jf<ejf<?, ?>> $$32 = $$1.b(rn.P);
      jf<ejf<?, ?>> $$33 = $$1.b(rn.Q);
      jf<ejf<?, ?>> $$34 = $$1.b(rn.R);
      jf<ejf<?, ?>> $$35 = $$1.b(rn.S);
      rx.a($$0, a, $$2, eqd.a(8), eqa.a());
      rx.a($$0, b, $$3, eqd.a(8), eqa.a());
      rx.a($$0, c, $$4, rx.a(dmo.z));
      rx.a($$0, d, $$5, rx.a(dmo.F));
      rx.a($$0, e, $$6, rx.a(dmo.G));
      rx.a($$0, f, $$7, rx.a(dmo.G));
      rx.a($$0, g, $$8, rx.a(dmo.B));
      rx.a($$0, h, $$9, rx.a(dmo.D));
      rx.a($$0, i, $$10, rx.a(dmo.A));
      rx.a($$0, j, $$11, rx.a(dmo.H));
      rx.a($$0, k, $$12, rx.a(dmo.E));
      ehu $$36 = ehu.a(jb.a.q(), dmo.ef, dmo.rx);
      List<eqp> $$37 = List.of(eqf.a(jb.b, ehu.a(ehu.a(dmo.rx)), 8), eqb.a($$36));
      rx.a($$0, l, $$13, $$37);
      rx.a($$0, m, $$10, $$37);
      rx.a($$0, n, $$13, rx.a(dmo.A));
      rx.a($$0, o, $$14, rx.a(dmo.C));
      rx.a($$0, p, $$15, rx.a(dmo.z));
      rx.a($$0, q, $$16, rx.a(dmo.C));
      rx.a($$0, r, $$17, rx.a(dmo.A));
      rx.a($$0, s, $$18, rx.a(dmo.A));
      rx.a($$0, t, $$19, rx.a(dmo.H));
      rx.a($$0, u, $$20, rx.a(dmo.z));
      rx.a($$0, v, $$21, rx.a(dmo.B));
      rx.a($$0, w, $$22, rx.a(dmo.B));
      rx.a($$0, x, $$23, rx.a(dmo.z));
      rx.a($$0, y, $$24, rx.a(dmo.z));
      rx.a($$0, z, $$25, rx.a(dmo.B));
      rx.a($$0, A, $$26, rx.a(dmo.B));
      rx.a($$0, B, $$27, rx.a(dmo.B));
      rx.a($$0, C, $$28, rx.a(dmo.z));
      rx.a($$0, D, $$29, rx.a(dmo.z));
      rx.a($$0, E, $$30, rx.a(dmo.z));
      rx.a($$0, F, $$31, rx.a(dmo.E));
      rx.a($$0, G, $$32, rx.a(dmo.z));
      rx.a($$0, H, $$33, rx.a(dmo.F));
      rx.a($$0, I, $$34, rx.a(dmo.B));
      rx.a($$0, J, $$35, rx.a(dmo.z));
   }
}
