import java.util.List;

public class ry {
   public static final alf<epx> a = rx.a("crimson_fungi");
   public static final alf<epx> b = rx.a("warped_fungi");
   public static final alf<epx> c = rx.a("oak_checked");
   public static final alf<epx> d = rx.a("dark_oak_checked");
   public static final alf<epx> e = rx.a("pale_oak_checked");
   public static final alf<epx> f = rx.a("pale_oak_creaking_checked");
   public static final alf<epx> g = rx.a("birch_checked");
   public static final alf<epx> h = rx.a("acacia_checked");
   public static final alf<epx> i = rx.a("spruce_checked");
   public static final alf<epx> j = rx.a("mangrove_checked");
   public static final alf<epx> k = rx.a("cherry_checked");
   public static final alf<epx> l = rx.a("pine_on_snow");
   public static final alf<epx> m = rx.a("spruce_on_snow");
   public static final alf<epx> n = rx.a("pine_checked");
   public static final alf<epx> o = rx.a("jungle_tree");
   public static final alf<epx> p = rx.a("fancy_oak_checked");
   public static final alf<epx> q = rx.a("mega_jungle_tree_checked");
   public static final alf<epx> r = rx.a("mega_spruce_checked");
   public static final alf<epx> s = rx.a("mega_pine_checked");
   public static final alf<epx> t = rx.a("tall_mangrove_checked");
   public static final alf<epx> u = rx.a("jungle_bush");
   public static final alf<epx> v = rx.a("super_birch_bees_0002");
   public static final alf<epx> w = rx.a("super_birch_bees");
   public static final alf<epx> x = rx.a("oak_bees_0002_leaf_litter");
   public static final alf<epx> y = rx.a("oak_bees_002");
   public static final alf<epx> z = rx.a("birch_bees_0002");
   public static final alf<epx> A = rx.a("birch_bees_0002_leaf_litter");
   public static final alf<epx> B = rx.a("birch_bees_002");
   public static final alf<epx> C = rx.a("fancy_oak_bees_0002_leaf_litter");
   public static final alf<epx> D = rx.a("fancy_oak_bees_002");
   public static final alf<epx> E = rx.a("fancy_oak_bees");
   public static final alf<epx> F = rx.a("cherry_bees_005");
   public static final alf<epx> G = rx.a("oak_leaf_litter");
   public static final alf<epx> H = rx.a("dark_oak_leaf_litter");
   public static final alf<epx> I = rx.a("birch_leaf_litter");
   public static final alf<epx> J = rx.a("fancy_oak_leaf_litter");

   public static void a(qh<epx> $$0) {
      jf<eiq<?, ?>> $$1 = $$0.a(mg.aK);
      je<eiq<?, ?>> $$2 = $$1.b(rn.a);
      je<eiq<?, ?>> $$3 = $$1.b(rn.c);
      je<eiq<?, ?>> $$4 = $$1.b(rn.g);
      je<eiq<?, ?>> $$5 = $$1.b(rn.h);
      je<eiq<?, ?>> $$6 = $$1.b(rn.i);
      je<eiq<?, ?>> $$7 = $$1.b(rn.k);
      je<eiq<?, ?>> $$8 = $$1.b(rn.l);
      je<eiq<?, ?>> $$9 = $$1.b(rn.m);
      je<eiq<?, ?>> $$10 = $$1.b(rn.n);
      je<eiq<?, ?>> $$11 = $$1.b(rn.A);
      je<eiq<?, ?>> $$12 = $$1.b(rn.C);
      je<eiq<?, ?>> $$13 = $$1.b(rn.o);
      je<eiq<?, ?>> $$14 = $$1.b(rn.p);
      je<eiq<?, ?>> $$15 = $$1.b(rn.q);
      je<eiq<?, ?>> $$16 = $$1.b(rn.s);
      je<eiq<?, ?>> $$17 = $$1.b(rn.t);
      je<eiq<?, ?>> $$18 = $$1.b(rn.u);
      je<eiq<?, ?>> $$19 = $$1.b(rn.B);
      je<eiq<?, ?>> $$20 = $$1.b(rn.y);
      je<eiq<?, ?>> $$21 = $$1.b(rn.v);
      je<eiq<?, ?>> $$22 = $$1.b(rn.w);
      je<eiq<?, ?>> $$23 = $$1.b(rn.D);
      je<eiq<?, ?>> $$24 = $$1.b(rn.E);
      je<eiq<?, ?>> $$25 = $$1.b(rn.G);
      je<eiq<?, ?>> $$26 = $$1.b(rn.H);
      je<eiq<?, ?>> $$27 = $$1.b(rn.I);
      je<eiq<?, ?>> $$28 = $$1.b(rn.K);
      je<eiq<?, ?>> $$29 = $$1.b(rn.L);
      je<eiq<?, ?>> $$30 = $$1.b(rn.N);
      je<eiq<?, ?>> $$31 = $$1.b(rn.O);
      je<eiq<?, ?>> $$32 = $$1.b(rn.P);
      je<eiq<?, ?>> $$33 = $$1.b(rn.Q);
      je<eiq<?, ?>> $$34 = $$1.b(rn.R);
      je<eiq<?, ?>> $$35 = $$1.b(rn.S);
      rx.a($$0, a, $$2, epo.a(8), epl.a());
      rx.a($$0, b, $$3, epo.a(8), epl.a());
      rx.a($$0, c, $$4, rx.a(dmc.z));
      rx.a($$0, d, $$5, rx.a(dmc.F));
      rx.a($$0, e, $$6, rx.a(dmc.G));
      rx.a($$0, f, $$7, rx.a(dmc.G));
      rx.a($$0, g, $$8, rx.a(dmc.B));
      rx.a($$0, h, $$9, rx.a(dmc.D));
      rx.a($$0, i, $$10, rx.a(dmc.A));
      rx.a($$0, j, $$11, rx.a(dmc.H));
      rx.a($$0, k, $$12, rx.a(dmc.E));
      ehf $$36 = ehf.a(ja.a.q(), dmc.ed, dmc.ru);
      List<eqa> $$37 = List.of(epq.a(ja.b, ehf.a(ehf.a(dmc.ru)), 8), epm.a($$36));
      rx.a($$0, l, $$13, $$37);
      rx.a($$0, m, $$10, $$37);
      rx.a($$0, n, $$13, rx.a(dmc.A));
      rx.a($$0, o, $$14, rx.a(dmc.C));
      rx.a($$0, p, $$15, rx.a(dmc.z));
      rx.a($$0, q, $$16, rx.a(dmc.C));
      rx.a($$0, r, $$17, rx.a(dmc.A));
      rx.a($$0, s, $$18, rx.a(dmc.A));
      rx.a($$0, t, $$19, rx.a(dmc.H));
      rx.a($$0, u, $$20, rx.a(dmc.z));
      rx.a($$0, v, $$21, rx.a(dmc.B));
      rx.a($$0, w, $$22, rx.a(dmc.B));
      rx.a($$0, x, $$23, rx.a(dmc.z));
      rx.a($$0, y, $$24, rx.a(dmc.z));
      rx.a($$0, z, $$25, rx.a(dmc.B));
      rx.a($$0, A, $$26, rx.a(dmc.B));
      rx.a($$0, B, $$27, rx.a(dmc.B));
      rx.a($$0, C, $$28, rx.a(dmc.z));
      rx.a($$0, D, $$29, rx.a(dmc.z));
      rx.a($$0, E, $$30, rx.a(dmc.z));
      rx.a($$0, F, $$31, rx.a(dmc.E));
      rx.a($$0, G, $$32, rx.a(dmc.z));
      rx.a($$0, H, $$33, rx.a(dmc.F));
      rx.a($$0, I, $$34, rx.a(dmc.B));
      rx.a($$0, J, $$35, rx.a(dmc.z));
   }
}
