import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableList.Builder;
import java.util.List;
import javax.annotation.Nullable;

public class rz {
   public static final alf<eqr> a = rx.a("bamboo_light");
   public static final alf<eqr> b = rx.a("bamboo");
   public static final alf<eqr> c = rx.a("vines");
   public static final alf<eqr> d = rx.a("patch_sunflower");
   public static final alf<eqr> e = rx.a("patch_pumpkin");
   public static final alf<eqr> f = rx.a("patch_grass_plain");
   public static final alf<eqr> g = rx.a("patch_grass_meadow");
   public static final alf<eqr> h = rx.a("patch_grass_forest");
   public static final alf<eqr> i = rx.a("patch_grass_badlands");
   public static final alf<eqr> j = rx.a("patch_grass_savanna");
   public static final alf<eqr> k = rx.a("patch_grass_normal");
   public static final alf<eqr> l = rx.a("patch_grass_taiga_2");
   public static final alf<eqr> m = rx.a("patch_grass_taiga");
   public static final alf<eqr> n = rx.a("patch_grass_jungle");
   public static final alf<eqr> o = rx.a("grass_bonemeal");
   public static final alf<eqr> p = rx.a("patch_dead_bush_2");
   public static final alf<eqr> q = rx.a("patch_dead_bush");
   public static final alf<eqr> r = rx.a("patch_dead_bush_badlands");
   public static final alf<eqr> s = rx.a("patch_dry_grass_badlands");
   public static final alf<eqr> t = rx.a("patch_dry_grass_desert");
   public static final alf<eqr> u = rx.a("patch_melon");
   public static final alf<eqr> v = rx.a("patch_melon_sparse");
   public static final alf<eqr> w = rx.a("patch_berry_common");
   public static final alf<eqr> x = rx.a("patch_berry_rare");
   public static final alf<eqr> y = rx.a("patch_waterlily");
   public static final alf<eqr> z = rx.a("patch_tall_grass_2");
   public static final alf<eqr> A = rx.a("patch_tall_grass");
   public static final alf<eqr> B = rx.a("patch_large_fern");
   public static final alf<eqr> C = rx.a("patch_bush");
   public static final alf<eqr> D = rx.a("patch_leaf_litter");
   public static final alf<eqr> E = rx.a("patch_cactus_desert");
   public static final alf<eqr> F = rx.a("patch_cactus_decorated");
   public static final alf<eqr> G = rx.a("patch_sugar_cane_swamp");
   public static final alf<eqr> H = rx.a("patch_sugar_cane_desert");
   public static final alf<eqr> I = rx.a("patch_sugar_cane_badlands");
   public static final alf<eqr> J = rx.a("patch_sugar_cane");
   public static final alf<eqr> K = rx.a("patch_firefly_bush_swamp");
   public static final alf<eqr> L = rx.a("patch_firefly_bush_near_water_swamp");
   public static final alf<eqr> M = rx.a("patch_firefly_bush_near_water");
   public static final alf<eqr> N = rx.a("brown_mushroom_nether");
   public static final alf<eqr> O = rx.a("red_mushroom_nether");
   public static final alf<eqr> P = rx.a("brown_mushroom_normal");
   public static final alf<eqr> Q = rx.a("red_mushroom_normal");
   public static final alf<eqr> R = rx.a("brown_mushroom_taiga");
   public static final alf<eqr> S = rx.a("red_mushroom_taiga");
   public static final alf<eqr> T = rx.a("brown_mushroom_old_growth");
   public static final alf<eqr> U = rx.a("red_mushroom_old_growth");
   public static final alf<eqr> V = rx.a("brown_mushroom_swamp");
   public static final alf<eqr> W = rx.a("red_mushroom_swamp");
   public static final alf<eqr> X = rx.a("flower_warm");
   public static final alf<eqr> Y = rx.a("flower_default");
   public static final alf<eqr> Z = rx.a("flower_flower_forest");
   public static final alf<eqr> aa = rx.a("flower_swamp");
   public static final alf<eqr> ab = rx.a("flower_plains");
   public static final alf<eqr> ac = rx.a("flower_meadow");
   public static final alf<eqr> ad = rx.a("flower_cherry");
   public static final alf<eqr> ae = rx.a("flower_pale_garden");
   public static final alf<eqr> af = rx.a("wildflowers_birch_forest");
   public static final alf<eqr> ag = rx.a("wildflowers_meadow");
   public static final alf<eqr> ah = rx.a("trees_plains");
   public static final alf<eqr> ai = rx.a("dark_forest_vegetation");
   public static final alf<eqr> aj = rx.a("pale_garden_vegetation");
   public static final alf<eqr> ak = rx.a("flower_forest_flowers");
   public static final alf<eqr> al = rx.a("forest_flowers");
   public static final alf<eqr> am = rx.a("pale_garden_flowers");
   public static final alf<eqr> an = rx.a("pale_moss_patch");
   public static final alf<eqr> ao = rx.a("trees_flower_forest");
   public static final alf<eqr> ap = rx.a("trees_meadow");
   public static final alf<eqr> aq = rx.a("trees_cherry");
   public static final alf<eqr> ar = rx.a("trees_taiga");
   public static final alf<eqr> as = rx.a("trees_grove");
   public static final alf<eqr> at = rx.a("trees_badlands");
   public static final alf<eqr> au = rx.a("trees_snowy");
   public static final alf<eqr> av = rx.a("trees_swamp");
   public static final alf<eqr> aw = rx.a("trees_windswept_savanna");
   public static final alf<eqr> ax = rx.a("trees_savanna");
   public static final alf<eqr> ay = rx.a("birch_tall");
   public static final alf<eqr> az = rx.a("trees_birch");
   public static final alf<eqr> aA = rx.a("trees_windswept_forest");
   public static final alf<eqr> aB = rx.a("trees_windswept_hills");
   public static final alf<eqr> aC = rx.a("trees_water");
   public static final alf<eqr> aD = rx.a("trees_birch_and_oak_leaf_litter");
   public static final alf<eqr> aE = rx.a("trees_sparse_jungle");
   public static final alf<eqr> aF = rx.a("trees_old_growth_spruce_taiga");
   public static final alf<eqr> aG = rx.a("trees_old_growth_pine_taiga");
   public static final alf<eqr> aH = rx.a("trees_jungle");
   public static final alf<eqr> aI = rx.a("bamboo_vegetation");
   public static final alf<eqr> aJ = rx.a("mushroom_island_vegetation");
   public static final alf<eqr> aK = rx.a("trees_mangrove");
   private static final equ aL = era.a(0);

   public static List<equ> a(int $$0) {
      return List.of(eqj.a($$0), eqo.a(), rx.d, eqf.a());
   }

   private static List<equ> a(int $$0, @Nullable equ $$1) {
      Builder<equ> $$2 = ImmutableList.builder();
      if ($$1 != null) {
         $$2.add($$1);
      }

      if ($$0 != 0) {
         $$2.add(eqx.a($$0));
      }

      $$2.add(eqo.a());
      $$2.add(rx.a);
      $$2.add(eqf.a());
      return $$2.build();
   }

   private static Builder<equ> b(equ $$0) {
      return ImmutableList.builder().add($$0).add(eqo.a()).add(aL).add(rx.e).add(eqf.a());
   }

   public static List<equ> a(equ $$0) {
      return b($$0).build();
   }

   public static List<equ> a(equ $$0, dmr $$1) {
      return b($$0).add(eqg.a(ehz.a($$1.m(), iv.c))).build();
   }

   public static void a(qh<eqr> $$0) {
      jg<ejk<?, ?>> $$1 = $$0.a(mh.aL);
      jf<ejk<?, ?>> $$2 = $$1.b(ro.a);
      jf<ejk<?, ?>> $$3 = $$1.b(ro.b);
      jf<ejk<?, ?>> $$4 = $$1.b(ro.c);
      jf<ejk<?, ?>> $$5 = $$1.b(ro.f);
      jf<ejk<?, ?>> $$6 = $$1.b(ro.g);
      jf<ejk<?, ?>> $$7 = $$1.b(ro.j);
      jf<ejk<?, ?>> $$8 = $$1.b(ro.k);
      jf<ejk<?, ?>> $$9 = $$1.b(ro.u);
      jf<ejk<?, ?>> $$10 = $$1.b(ro.i);
      jf<ejk<?, ?>> $$11 = $$1.b(ro.l);
      jf<ejk<?, ?>> $$12 = $$1.b(ro.m);
      jf<ejk<?, ?>> $$13 = $$1.b(ro.n);
      jf<ejk<?, ?>> $$14 = $$1.b(ro.o);
      jf<ejk<?, ?>> $$15 = $$1.b(ro.v);
      jf<ejk<?, ?>> $$16 = $$1.b(ro.p);
      jf<ejk<?, ?>> $$17 = $$1.b(ro.h);
      jf<ejk<?, ?>> $$18 = $$1.b(ro.q);
      jf<ejk<?, ?>> $$19 = $$1.b(ro.r);
      jf<ejk<?, ?>> $$20 = $$1.b(ro.s);
      jf<ejk<?, ?>> $$21 = $$1.b(ro.t);
      jf<ejk<?, ?>> $$22 = $$1.b(ro.w);
      jf<ejk<?, ?>> $$23 = $$1.b(ro.x);
      jf<ejk<?, ?>> $$24 = $$1.b(ro.d);
      jf<ejk<?, ?>> $$25 = $$1.b(ro.e);
      jf<ejk<?, ?>> $$26 = $$1.b(ro.y);
      jf<ejk<?, ?>> $$27 = $$1.b(ro.z);
      jf<ejk<?, ?>> $$28 = $$1.b(ro.A);
      jf<ejk<?, ?>> $$29 = $$1.b(ro.B);
      jf<ejk<?, ?>> $$30 = $$1.b(ro.C);
      jf<ejk<?, ?>> $$31 = $$1.b(ro.D);
      jf<ejk<?, ?>> $$32 = $$1.b(ro.E);
      jf<ejk<?, ?>> $$33 = $$1.b(ro.F);
      jf<ejk<?, ?>> $$34 = $$1.b(ro.G);
      jf<ejk<?, ?>> $$35 = $$1.b(ro.X);
      jf<ejk<?, ?>> $$36 = $$1.b(ro.J);
      jf<ejk<?, ?>> $$37 = $$1.b(ro.K);
      jf<ejk<?, ?>> $$38 = $$1.b(ro.H);
      jf<ejk<?, ?>> $$39 = $$1.b(ro.I);
      jf<ejk<?, ?>> $$40 = $$1.b(ro.M);
      jf<ejk<?, ?>> $$41 = $$1.b(ro.O);
      jf<ejk<?, ?>> $$42 = $$1.b(ro.P);
      jf<ejk<?, ?>> $$43 = $$1.b(ro.Q);
      jf<ejk<?, ?>> $$44 = $$1.b(ro.R);
      jf<ejk<?, ?>> $$45 = $$1.b(rn.g);
      jf<ejk<?, ?>> $$46 = $$1.b(rn.n);
      jf<ejk<?, ?>> $$47 = $$1.b(rn.O);
      jf<ejk<?, ?>> $$48 = $$1.b(rn.x);
      jf<ejk<?, ?>> $$49 = $$1.b(ro.S);
      jf<ejk<?, ?>> $$50 = $$1.b(ro.T);
      jf<ejk<?, ?>> $$51 = $$1.b(rn.G);
      jf<ejk<?, ?>> $$52 = $$1.b(ro.U);
      jf<ejk<?, ?>> $$53 = $$1.b(ro.V);
      jf<ejk<?, ?>> $$54 = $$1.b(ro.W);
      jf<ejk<?, ?>> $$55 = $$1.b(ro.Y);
      jf<ejk<?, ?>> $$56 = $$1.b(ro.Z);
      jf<ejk<?, ?>> $$57 = $$1.b(ro.aa);
      jf<ejk<?, ?>> $$58 = $$1.b(ro.ab);
      jf<ejk<?, ?>> $$59 = $$1.b(ro.ac);
      jf<ejk<?, ?>> $$60 = $$1.b(ro.ad);
      jf<ejk<?, ?>> $$61 = $$1.b(ro.ae);
      jf<ejk<?, ?>> $$62 = $$1.b(rn.P);
      rx.a($$0, a, $$2, eqx.a(4), eqo.a(), rx.a, eqf.a());
      rx.a($$0, b, $$3, eqp.a(160, 80.0, 0.3), eqo.a(), rx.d, eqf.a());
      rx.a($$0, c, $$4, eqj.a(127), eqo.a(), eqm.a(ehm.a(64), ehm.a(100)), eqf.a());
      rx.a($$0, d, $$5, eqx.a(3), eqo.a(), rx.a, eqf.a());
      rx.a($$0, e, $$6, eqx.a(300), eqo.a(), rx.a, eqf.a());
      rx.a($$0, f, $$7, eqq.a(-0.8, 5, 10), eqo.a(), rx.d, eqf.a());
      rx.a($$0, g, $$8, eqq.a(-0.8, 5, 10), eqo.a(), rx.d, eqf.a());
      rx.a($$0, h, $$7, a(2));
      rx.a($$0, D, $$9, a(2));
      rx.a($$0, i, $$7, eqo.a(), rx.d, eqf.a());
      rx.a($$0, j, $$7, a(20));
      rx.a($$0, k, $$7, a(5));
      rx.a($$0, l, $$10, eqo.a(), rx.d, eqf.a());
      rx.a($$0, m, $$10, a(7));
      rx.a($$0, n, $$11, a(25));
      rx.a($$0, o, $$12, rx.a());
      rx.a($$0, p, $$13, a(2));
      rx.a($$0, q, $$13, eqo.a(), rx.d, eqf.a());
      rx.a($$0, r, $$13, a(20));
      rx.a($$0, s, $$14, eqx.a(6), eqo.a(), rx.a, eqf.a());
      rx.a($$0, t, $$14, eqx.a(3), eqo.a(), rx.a, eqf.a());
      rx.a($$0, u, $$16, eqx.a(6), eqo.a(), rx.a, eqf.a());
      rx.a($$0, v, $$16, eqx.a(64), eqo.a(), rx.a, eqf.a());
      rx.a($$0, w, $$17, eqx.a(32), eqo.a(), rx.d, eqf.a());
      rx.a($$0, x, $$17, eqx.a(384), eqo.a(), rx.d, eqf.a());
      rx.a($$0, y, $$18, a(4));
      rx.a($$0, z, $$19, eqq.a(-0.8, 0, 7), eqx.a(32), eqo.a(), rx.a, eqf.a());
      rx.a($$0, A, $$19, eqx.a(5), eqo.a(), rx.a, eqf.a());
      rx.a($$0, B, $$20, eqx.a(5), eqo.a(), rx.a, eqf.a());
      rx.a($$0, C, $$21, eqx.a(4), eqo.a(), rx.a, eqf.a());
      rx.a($$0, E, $$22, eqx.a(6), eqo.a(), rx.a, eqf.a());
      rx.a($$0, F, $$22, eqx.a(13), eqo.a(), rx.a, eqf.a());
      rx.a($$0, G, $$23, eqx.a(3), eqo.a(), rx.a, eqf.a());
      rx.a($$0, H, $$23, eqo.a(), rx.a, eqf.a());
      rx.a($$0, I, $$23, eqx.a(5), eqo.a(), rx.a, eqf.a());
      rx.a($$0, J, $$23, eqx.a(6), eqo.a(), rx.a, eqf.a());
      rx.a($$0, M, $$15, eqj.a(2), eqo.a(), rx.a, eqf.a(), ro.a(dmt.ul));
      rx.a($$0, L, $$15, eqj.a(3), eqo.a(), rx.a, eqf.a(), ro.a(dmt.ul));
      rx.a($$0, K, $$15, eqx.a(8), eqo.a(), rx.a, eqf.a());
      rx.a($$0, N, $$24, eqx.a(2), eqo.a(), rx.f, eqf.a());
      rx.a($$0, O, $$25, eqx.a(2), eqo.a(), rx.f, eqf.a());
      rx.a($$0, P, $$24, a(256, null));
      rx.a($$0, Q, $$25, a(512, null));
      rx.a($$0, R, $$24, a(4, null));
      rx.a($$0, S, $$25, a(256, null));
      rx.a($$0, T, $$24, a(4, eqj.a(3)));
      rx.a($$0, U, $$25, a(171, null));
      rx.a($$0, V, $$24, a(0, eqj.a(2)));
      rx.a($$0, W, $$25, a(64, null));
      rx.a($$0, X, $$26, eqx.a(16), eqo.a(), rx.a, eqf.a());
      rx.a($$0, Y, $$26, eqx.a(32), eqo.a(), rx.a, eqf.a());
      rx.a($$0, Z, $$27, eqj.a(3), eqx.a(2), eqo.a(), rx.a, eqf.a());
      rx.a($$0, aa, $$28, eqx.a(32), eqo.a(), rx.a, eqf.a());
      rx.a($$0, ab, $$29, eqq.a(-0.8, 15, 4), eqx.a(32), eqo.a(), rx.a, eqf.a());
      rx.a($$0, ad, $$31, eqq.a(-0.8, 5, 10), eqo.a(), rx.a, eqf.a());
      rx.a($$0, ac, $$30, eqo.a(), rx.a, eqf.a());
      rx.a($$0, ae, $$32, eqx.a(32), eqo.a(), rx.a, eqf.a());
      rx.a($$0, af, $$33, eqj.a(3), eqx.a(2), eqo.a(), rx.a, eqf.a());
      rx.a($$0, ag, $$34, eqq.a(-0.8, 5, 10), eqo.a(), rx.a, eqf.a());
      equ $$63 = era.a(0);
      rx.a($$0, ah, $$35, rx.a(0, 0.05F, 1), eqo.a(), $$63, rx.e, eqg.a(ehz.a(dmt.z.m(), iv.c)), eqf.a());
      rx.a($$0, ai, $$36, eqj.a(16), eqo.a(), $$63, rx.e, eqf.a());
      rx.a($$0, aj, $$37, eqj.a(16), eqo.a(), $$63, rx.e, eqf.a());
      rx.a($$0, ak, $$38, eqx.a(7), eqo.a(), rx.a, eqj.a(bte.a(btr.a(-1, 3), 0, 3)), eqf.a());
      rx.a($$0, al, $$38, eqx.a(7), eqo.a(), rx.a, eqj.a(bte.a(btr.a(-3, 1), 0, 1)), eqf.a());
      rx.a($$0, am, $$39, eqx.a(8), eqo.a(), rx.b, eqf.a());
      rx.a($$0, an, $$40, eqj.a(1), eqo.a(), rx.b, eqf.a());
      rx.a($$0, ao, $$41, a(rx.a(6, 0.1F, 1)));
      rx.a($$0, ap, $$42, a(eqx.a(100)));
      rx.a($$0, aq, $$47, a(rx.a(10, 0.1F, 1), dmt.E));
      rx.a($$0, ar, $$43, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, as, $$44, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, at, $$62, a(rx.a(5, 0.1F, 1), dmt.z));
      rx.a($$0, au, $$46, a(rx.a(0, 0.1F, 1), dmt.A));
      rx.a($$0, av, $$48, rx.a(2, 0.1F, 1), eqo.a(), era.a(2), rx.e, eqf.a(), eqg.a(ehz.a(dmt.z.m(), iv.c)));
      rx.a($$0, aw, $$49, a(rx.a(2, 0.1F, 1)));
      rx.a($$0, ax, $$49, a(rx.a(1, 0.1F, 1)));
      rx.a($$0, ay, $$50, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, az, $$51, a(rx.a(10, 0.1F, 1), dmt.B));
      rx.a($$0, aA, $$52, a(rx.a(3, 0.1F, 1)));
      rx.a($$0, aB, $$52, a(rx.a(0, 0.1F, 1)));
      rx.a($$0, aC, $$53, a(rx.a(0, 0.1F, 1)));
      rx.a($$0, aD, $$54, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, aE, $$55, a(rx.a(2, 0.1F, 1)));
      rx.a($$0, aF, $$56, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, aG, $$57, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, aH, $$58, a(rx.a(50, 0.1F, 1)));
      rx.a($$0, aI, $$59, a(rx.a(30, 0.1F, 1)));
      rx.a($$0, aJ, $$60, eqo.a(), rx.a, eqf.a());
      rx.a($$0, aK, $$61, eqj.a(25), eqo.a(), era.a(5), rx.e, eqf.a(), eqg.a(ehz.a(dmt.H.m(), iv.c)));
   }
}
