import java.util.List;

public class rz {
   public static final alq<err> a = ry.a("crimson_fungi");
   public static final alq<err> b = ry.a("warped_fungi");
   public static final alq<err> c = ry.a("oak_checked");
   public static final alq<err> d = ry.a("dark_oak_checked");
   public static final alq<err> e = ry.a("pale_oak_checked");
   public static final alq<err> f = ry.a("pale_oak_creaking_checked");
   public static final alq<err> g = ry.a("birch_checked");
   public static final alq<err> h = ry.a("acacia_checked");
   public static final alq<err> i = ry.a("spruce_checked");
   public static final alq<err> j = ry.a("mangrove_checked");
   public static final alq<err> k = ry.a("cherry_checked");
   public static final alq<err> l = ry.a("pine_on_snow");
   public static final alq<err> m = ry.a("spruce_on_snow");
   public static final alq<err> n = ry.a("pine_checked");
   public static final alq<err> o = ry.a("jungle_tree");
   public static final alq<err> p = ry.a("fancy_oak_checked");
   public static final alq<err> q = ry.a("mega_jungle_tree_checked");
   public static final alq<err> r = ry.a("mega_spruce_checked");
   public static final alq<err> s = ry.a("mega_pine_checked");
   public static final alq<err> t = ry.a("tall_mangrove_checked");
   public static final alq<err> u = ry.a("jungle_bush");
   public static final alq<err> v = ry.a("super_birch_bees_0002");
   public static final alq<err> w = ry.a("super_birch_bees");
   public static final alq<err> x = ry.a("oak_bees_0002_leaf_litter");
   public static final alq<err> y = ry.a("oak_bees_002");
   public static final alq<err> z = ry.a("birch_bees_0002");
   public static final alq<err> A = ry.a("birch_bees_0002_leaf_litter");
   public static final alq<err> B = ry.a("birch_bees_002");
   public static final alq<err> C = ry.a("fancy_oak_bees_0002_leaf_litter");
   public static final alq<err> D = ry.a("fancy_oak_bees_002");
   public static final alq<err> E = ry.a("fancy_oak_bees");
   public static final alq<err> F = ry.a("cherry_bees_005");
   public static final alq<err> G = ry.a("oak_leaf_litter");
   public static final alq<err> H = ry.a("dark_oak_leaf_litter");
   public static final alq<err> I = ry.a("birch_leaf_litter");
   public static final alq<err> J = ry.a("fancy_oak_leaf_litter");
   public static final alq<err> K = ry.a("fallen_oak_tree");
   public static final alq<err> L = ry.a("fallen_birch_tree");
   public static final alq<err> M = ry.a("fallen_super_birch_tree");
   public static final alq<err> N = ry.a("fallen_spruce_tree");
   public static final alq<err> O = ry.a("fallen_jungle_tree");

   public static void a(qi<err> $$0) {
      jh<ekh<?, ?>> $$1 = $$0.a(mi.aL);
      jg<ekh<?, ?>> $$2 = $$1.b(ro.a);
      jg<ekh<?, ?>> $$3 = $$1.b(ro.c);
      jg<ekh<?, ?>> $$4 = $$1.b(ro.g);
      jg<ekh<?, ?>> $$5 = $$1.b(ro.h);
      jg<ekh<?, ?>> $$6 = $$1.b(ro.i);
      jg<ekh<?, ?>> $$7 = $$1.b(ro.k);
      jg<ekh<?, ?>> $$8 = $$1.b(ro.l);
      jg<ekh<?, ?>> $$9 = $$1.b(ro.m);
      jg<ekh<?, ?>> $$10 = $$1.b(ro.n);
      jg<ekh<?, ?>> $$11 = $$1.b(ro.A);
      jg<ekh<?, ?>> $$12 = $$1.b(ro.C);
      jg<ekh<?, ?>> $$13 = $$1.b(ro.o);
      jg<ekh<?, ?>> $$14 = $$1.b(ro.p);
      jg<ekh<?, ?>> $$15 = $$1.b(ro.q);
      jg<ekh<?, ?>> $$16 = $$1.b(ro.s);
      jg<ekh<?, ?>> $$17 = $$1.b(ro.t);
      jg<ekh<?, ?>> $$18 = $$1.b(ro.u);
      jg<ekh<?, ?>> $$19 = $$1.b(ro.B);
      jg<ekh<?, ?>> $$20 = $$1.b(ro.y);
      jg<ekh<?, ?>> $$21 = $$1.b(ro.v);
      jg<ekh<?, ?>> $$22 = $$1.b(ro.w);
      jg<ekh<?, ?>> $$23 = $$1.b(ro.D);
      jg<ekh<?, ?>> $$24 = $$1.b(ro.E);
      jg<ekh<?, ?>> $$25 = $$1.b(ro.G);
      jg<ekh<?, ?>> $$26 = $$1.b(ro.H);
      jg<ekh<?, ?>> $$27 = $$1.b(ro.I);
      jg<ekh<?, ?>> $$28 = $$1.b(ro.K);
      jg<ekh<?, ?>> $$29 = $$1.b(ro.L);
      jg<ekh<?, ?>> $$30 = $$1.b(ro.N);
      jg<ekh<?, ?>> $$31 = $$1.b(ro.O);
      jg<ekh<?, ?>> $$32 = $$1.b(ro.P);
      jg<ekh<?, ?>> $$33 = $$1.b(ro.Q);
      jg<ekh<?, ?>> $$34 = $$1.b(ro.R);
      jg<ekh<?, ?>> $$35 = $$1.b(ro.S);
      jg<ekh<?, ?>> $$36 = $$1.b(ro.T);
      jg<ekh<?, ?>> $$37 = $$1.b(ro.W);
      jg<ekh<?, ?>> $$38 = $$1.b(ro.X);
      jg<ekh<?, ?>> $$39 = $$1.b(ro.V);
      jg<ekh<?, ?>> $$40 = $$1.b(ro.U);
      ry.a($$0, a, $$2, eri.a(8), erf.a());
      ry.a($$0, b, $$3, eri.a(8), erf.a());
      ry.a($$0, c, $$4, ry.a(dnq.z));
      ry.a($$0, d, $$5, ry.a(dnq.F));
      ry.a($$0, e, $$6, ry.a(dnq.G));
      ry.a($$0, f, $$7, ry.a(dnq.G));
      ry.a($$0, g, $$8, ry.a(dnq.B));
      ry.a($$0, h, $$9, ry.a(dnq.D));
      ry.a($$0, i, $$10, ry.a(dnq.A));
      ry.a($$0, j, $$11, ry.a(dnq.H));
      ry.a($$0, k, $$12, ry.a(dnq.E));
      eiw $$41 = eiw.a(jc.a.q(), dnq.ef, dnq.rx);
      List<eru> $$42 = List.of(erk.a(jc.b, eiw.a(eiw.a(dnq.rx)), 8), erg.a($$41));
      ry.a($$0, l, $$13, $$42);
      ry.a($$0, m, $$10, $$42);
      ry.a($$0, n, $$13, ry.a(dnq.A));
      ry.a($$0, o, $$14, ry.a(dnq.C));
      ry.a($$0, p, $$15, ry.a(dnq.z));
      ry.a($$0, q, $$16, ry.a(dnq.C));
      ry.a($$0, r, $$17, ry.a(dnq.A));
      ry.a($$0, s, $$18, ry.a(dnq.A));
      ry.a($$0, t, $$19, ry.a(dnq.H));
      ry.a($$0, u, $$20, ry.a(dnq.z));
      ry.a($$0, v, $$21, ry.a(dnq.B));
      ry.a($$0, w, $$22, ry.a(dnq.B));
      ry.a($$0, x, $$23, ry.a(dnq.z));
      ry.a($$0, y, $$24, ry.a(dnq.z));
      ry.a($$0, z, $$25, ry.a(dnq.B));
      ry.a($$0, A, $$26, ry.a(dnq.B));
      ry.a($$0, B, $$27, ry.a(dnq.B));
      ry.a($$0, C, $$28, ry.a(dnq.z));
      ry.a($$0, D, $$29, ry.a(dnq.z));
      ry.a($$0, E, $$30, ry.a(dnq.z));
      ry.a($$0, F, $$31, ry.a(dnq.E));
      ry.a($$0, G, $$32, ry.a(dnq.z));
      ry.a($$0, H, $$33, ry.a(dnq.F));
      ry.a($$0, I, $$34, ry.a(dnq.B));
      ry.a($$0, J, $$35, ry.a(dnq.z));
      ry.a($$0, K, $$36, ry.a(dnq.z));
      ry.a($$0, L, $$37, ry.a(dnq.B));
      ry.a($$0, M, $$38, ry.a(dnq.B));
      ry.a($$0, N, $$39, ry.a(dnq.A));
      ry.a($$0, O, $$40, ry.a(dnq.C));
   }
}
