import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableList.Builder;
import java.util.List;
import javax.annotation.Nullable;

public class rz {
   public static final alf<epx> a = rx.a("bamboo_light");
   public static final alf<epx> b = rx.a("bamboo");
   public static final alf<epx> c = rx.a("vines");
   public static final alf<epx> d = rx.a("patch_sunflower");
   public static final alf<epx> e = rx.a("patch_pumpkin");
   public static final alf<epx> f = rx.a("patch_grass_plain");
   public static final alf<epx> g = rx.a("patch_grass_meadow");
   public static final alf<epx> h = rx.a("patch_grass_forest");
   public static final alf<epx> i = rx.a("patch_grass_badlands");
   public static final alf<epx> j = rx.a("patch_grass_savanna");
   public static final alf<epx> k = rx.a("patch_grass_normal");
   public static final alf<epx> l = rx.a("patch_grass_taiga_2");
   public static final alf<epx> m = rx.a("patch_grass_taiga");
   public static final alf<epx> n = rx.a("patch_grass_jungle");
   public static final alf<epx> o = rx.a("grass_bonemeal");
   public static final alf<epx> p = rx.a("patch_dead_bush_2");
   public static final alf<epx> q = rx.a("patch_dead_bush");
   public static final alf<epx> r = rx.a("patch_dead_bush_badlands");
   public static final alf<epx> s = rx.a("patch_melon");
   public static final alf<epx> t = rx.a("patch_melon_sparse");
   public static final alf<epx> u = rx.a("patch_berry_common");
   public static final alf<epx> v = rx.a("patch_berry_rare");
   public static final alf<epx> w = rx.a("patch_waterlily");
   public static final alf<epx> x = rx.a("patch_tall_grass_2");
   public static final alf<epx> y = rx.a("patch_tall_grass");
   public static final alf<epx> z = rx.a("patch_large_fern");
   public static final alf<epx> A = rx.a("patch_bush");
   public static final alf<epx> B = rx.a("patch_leaf_litter");
   public static final alf<epx> C = rx.a("patch_cactus_desert");
   public static final alf<epx> D = rx.a("patch_cactus_decorated");
   public static final alf<epx> E = rx.a("patch_sugar_cane_swamp");
   public static final alf<epx> F = rx.a("patch_sugar_cane_desert");
   public static final alf<epx> G = rx.a("patch_sugar_cane_badlands");
   public static final alf<epx> H = rx.a("patch_sugar_cane");
   public static final alf<epx> I = rx.a("patch_firefly_bush_swamp");
   public static final alf<epx> J = rx.a("patch_firefly_bush_near_water");
   public static final alf<epx> K = rx.a("patch_firefly_bush_near_water_swamp");
   public static final alf<epx> L = rx.a("brown_mushroom_nether");
   public static final alf<epx> M = rx.a("red_mushroom_nether");
   public static final alf<epx> N = rx.a("brown_mushroom_normal");
   public static final alf<epx> O = rx.a("red_mushroom_normal");
   public static final alf<epx> P = rx.a("brown_mushroom_taiga");
   public static final alf<epx> Q = rx.a("red_mushroom_taiga");
   public static final alf<epx> R = rx.a("brown_mushroom_old_growth");
   public static final alf<epx> S = rx.a("red_mushroom_old_growth");
   public static final alf<epx> T = rx.a("brown_mushroom_swamp");
   public static final alf<epx> U = rx.a("red_mushroom_swamp");
   public static final alf<epx> V = rx.a("flower_warm");
   public static final alf<epx> W = rx.a("flower_default");
   public static final alf<epx> X = rx.a("flower_flower_forest");
   public static final alf<epx> Y = rx.a("flower_swamp");
   public static final alf<epx> Z = rx.a("flower_plains");
   public static final alf<epx> aa = rx.a("flower_meadow");
   public static final alf<epx> ab = rx.a("flower_cherry");
   public static final alf<epx> ac = rx.a("flower_pale_garden");
   public static final alf<epx> ad = rx.a("wildflowers_birch_forest");
   public static final alf<epx> ae = rx.a("wildflowers_meadow");
   public static final alf<epx> af = rx.a("trees_plains");
   public static final alf<epx> ag = rx.a("dark_forest_vegetation");
   public static final alf<epx> ah = rx.a("pale_garden_vegetation");
   public static final alf<epx> ai = rx.a("flower_forest_flowers");
   public static final alf<epx> aj = rx.a("forest_flowers");
   public static final alf<epx> ak = rx.a("pale_garden_flowers");
   public static final alf<epx> al = rx.a("pale_moss_patch");
   public static final alf<epx> am = rx.a("trees_flower_forest");
   public static final alf<epx> an = rx.a("trees_meadow");
   public static final alf<epx> ao = rx.a("trees_cherry");
   public static final alf<epx> ap = rx.a("trees_taiga");
   public static final alf<epx> aq = rx.a("trees_grove");
   public static final alf<epx> ar = rx.a("trees_badlands");
   public static final alf<epx> as = rx.a("trees_snowy");
   public static final alf<epx> at = rx.a("trees_swamp");
   public static final alf<epx> au = rx.a("trees_windswept_savanna");
   public static final alf<epx> av = rx.a("trees_savanna");
   public static final alf<epx> aw = rx.a("birch_tall");
   public static final alf<epx> ax = rx.a("trees_birch");
   public static final alf<epx> ay = rx.a("trees_windswept_forest");
   public static final alf<epx> az = rx.a("trees_windswept_hills");
   public static final alf<epx> aA = rx.a("trees_water");
   public static final alf<epx> aB = rx.a("trees_birch_and_oak_leaf_litter");
   public static final alf<epx> aC = rx.a("trees_sparse_jungle");
   public static final alf<epx> aD = rx.a("trees_old_growth_spruce_taiga");
   public static final alf<epx> aE = rx.a("trees_old_growth_pine_taiga");
   public static final alf<epx> aF = rx.a("trees_jungle");
   public static final alf<epx> aG = rx.a("bamboo_vegetation");
   public static final alf<epx> aH = rx.a("mushroom_island_vegetation");
   public static final alf<epx> aI = rx.a("trees_mangrove");
   private static final eqa aJ = eqg.a(0);

   public static List<eqa> a(int $$0) {
      return List.of(epp.a($$0), epu.a(), rx.d, epl.a());
   }

   private static List<eqa> a(int $$0, @Nullable eqa $$1) {
      Builder<eqa> $$2 = ImmutableList.builder();
      if ($$1 != null) {
         $$2.add($$1);
      }

      if ($$0 != 0) {
         $$2.add(eqd.a($$0));
      }

      $$2.add(epu.a());
      $$2.add(rx.a);
      $$2.add(epl.a());
      return $$2.build();
   }

   private static Builder<eqa> b(eqa $$0) {
      return ImmutableList.builder().add($$0).add(epu.a()).add(aJ).add(rx.e).add(epl.a());
   }

   public static List<eqa> a(eqa $$0) {
      return b($$0).build();
   }

   public static List<eqa> a(eqa $$0, dma $$1) {
      return b($$0).add(epm.a(ehf.a($$1.m(), iu.c))).build();
   }

   public static void a(qh<epx> $$0) {
      jf<eiq<?, ?>> $$1 = $$0.a(mg.aK);
      je<eiq<?, ?>> $$2 = $$1.b(ro.a);
      je<eiq<?, ?>> $$3 = $$1.b(ro.b);
      je<eiq<?, ?>> $$4 = $$1.b(ro.c);
      je<eiq<?, ?>> $$5 = $$1.b(ro.f);
      je<eiq<?, ?>> $$6 = $$1.b(ro.g);
      je<eiq<?, ?>> $$7 = $$1.b(ro.j);
      je<eiq<?, ?>> $$8 = $$1.b(ro.k);
      je<eiq<?, ?>> $$9 = $$1.b(ro.t);
      je<eiq<?, ?>> $$10 = $$1.b(ro.i);
      je<eiq<?, ?>> $$11 = $$1.b(ro.l);
      je<eiq<?, ?>> $$12 = $$1.b(ro.m);
      je<eiq<?, ?>> $$13 = $$1.b(ro.n);
      je<eiq<?, ?>> $$14 = $$1.b(ro.u);
      je<eiq<?, ?>> $$15 = $$1.b(ro.v);
      je<eiq<?, ?>> $$16 = $$1.b(ro.w);
      je<eiq<?, ?>> $$17 = $$1.b(ro.o);
      je<eiq<?, ?>> $$18 = $$1.b(ro.h);
      je<eiq<?, ?>> $$19 = $$1.b(ro.p);
      je<eiq<?, ?>> $$20 = $$1.b(ro.q);
      je<eiq<?, ?>> $$21 = $$1.b(ro.r);
      je<eiq<?, ?>> $$22 = $$1.b(ro.s);
      je<eiq<?, ?>> $$23 = $$1.b(ro.x);
      je<eiq<?, ?>> $$24 = $$1.b(ro.y);
      je<eiq<?, ?>> $$25 = $$1.b(ro.d);
      je<eiq<?, ?>> $$26 = $$1.b(ro.e);
      je<eiq<?, ?>> $$27 = $$1.b(ro.z);
      je<eiq<?, ?>> $$28 = $$1.b(ro.A);
      je<eiq<?, ?>> $$29 = $$1.b(ro.B);
      je<eiq<?, ?>> $$30 = $$1.b(ro.C);
      je<eiq<?, ?>> $$31 = $$1.b(ro.D);
      je<eiq<?, ?>> $$32 = $$1.b(ro.E);
      je<eiq<?, ?>> $$33 = $$1.b(ro.F);
      je<eiq<?, ?>> $$34 = $$1.b(ro.G);
      je<eiq<?, ?>> $$35 = $$1.b(ro.H);
      je<eiq<?, ?>> $$36 = $$1.b(ro.Y);
      je<eiq<?, ?>> $$37 = $$1.b(ro.K);
      je<eiq<?, ?>> $$38 = $$1.b(ro.L);
      je<eiq<?, ?>> $$39 = $$1.b(ro.I);
      je<eiq<?, ?>> $$40 = $$1.b(ro.J);
      je<eiq<?, ?>> $$41 = $$1.b(ro.N);
      je<eiq<?, ?>> $$42 = $$1.b(ro.P);
      je<eiq<?, ?>> $$43 = $$1.b(ro.Q);
      je<eiq<?, ?>> $$44 = $$1.b(ro.R);
      je<eiq<?, ?>> $$45 = $$1.b(ro.S);
      je<eiq<?, ?>> $$46 = $$1.b(rn.g);
      je<eiq<?, ?>> $$47 = $$1.b(rn.n);
      je<eiq<?, ?>> $$48 = $$1.b(rn.O);
      je<eiq<?, ?>> $$49 = $$1.b(rn.x);
      je<eiq<?, ?>> $$50 = $$1.b(ro.T);
      je<eiq<?, ?>> $$51 = $$1.b(ro.U);
      je<eiq<?, ?>> $$52 = $$1.b(rn.G);
      je<eiq<?, ?>> $$53 = $$1.b(ro.V);
      je<eiq<?, ?>> $$54 = $$1.b(ro.W);
      je<eiq<?, ?>> $$55 = $$1.b(ro.X);
      je<eiq<?, ?>> $$56 = $$1.b(ro.Z);
      je<eiq<?, ?>> $$57 = $$1.b(ro.aa);
      je<eiq<?, ?>> $$58 = $$1.b(ro.ab);
      je<eiq<?, ?>> $$59 = $$1.b(ro.ac);
      je<eiq<?, ?>> $$60 = $$1.b(ro.ad);
      je<eiq<?, ?>> $$61 = $$1.b(ro.ae);
      je<eiq<?, ?>> $$62 = $$1.b(ro.af);
      je<eiq<?, ?>> $$63 = $$1.b(rn.P);
      rx.a($$0, a, $$2, eqd.a(4), epu.a(), rx.a, epl.a());
      rx.a($$0, b, $$3, epv.a(160, 80.0, 0.3), epu.a(), rx.d, epl.a());
      rx.a($$0, c, $$4, epp.a(127), epu.a(), eps.a(egs.a(64), egs.a(100)), epl.a());
      rx.a($$0, d, $$5, eqd.a(3), epu.a(), rx.a, epl.a());
      rx.a($$0, e, $$6, eqd.a(300), epu.a(), rx.a, epl.a());
      rx.a($$0, f, $$7, epw.a(-0.8, 5, 10), epu.a(), rx.d, epl.a());
      rx.a($$0, g, $$8, epw.a(-0.8, 5, 10), epu.a(), rx.d, epl.a());
      rx.a($$0, h, $$7, a(2));
      rx.a($$0, B, $$9, a(2));
      rx.a($$0, i, $$7, epu.a(), rx.d, epl.a());
      rx.a($$0, j, $$7, a(20));
      rx.a($$0, k, $$7, a(5));
      rx.a($$0, l, $$10, epu.a(), rx.d, epl.a());
      rx.a($$0, m, $$10, a(7));
      rx.a($$0, n, $$11, a(25));
      rx.a($$0, o, $$12, rx.a());
      rx.a($$0, p, $$13, a(2));
      rx.a($$0, q, $$13, epu.a(), rx.d, epl.a());
      rx.a($$0, r, $$13, a(20));
      rx.a($$0, s, $$17, eqd.a(6), epu.a(), rx.a, epl.a());
      rx.a($$0, t, $$17, eqd.a(64), epu.a(), rx.a, epl.a());
      rx.a($$0, u, $$18, eqd.a(32), epu.a(), rx.d, epl.a());
      rx.a($$0, v, $$18, eqd.a(384), epu.a(), rx.d, epl.a());
      rx.a($$0, w, $$19, a(4));
      rx.a($$0, x, $$20, epw.a(-0.8, 0, 7), eqd.a(32), epu.a(), rx.a, epl.a());
      rx.a($$0, y, $$20, eqd.a(5), epu.a(), rx.a, epl.a());
      rx.a($$0, z, $$21, eqd.a(5), epu.a(), rx.a, epl.a());
      rx.a($$0, A, $$22, eqd.a(4), epu.a(), rx.a, epl.a());
      rx.a($$0, C, $$23, eqd.a(6), epu.a(), rx.a, epl.a());
      rx.a($$0, D, $$23, eqd.a(13), epu.a(), rx.a, epl.a());
      rx.a($$0, E, $$24, eqd.a(3), epu.a(), rx.a, epl.a());
      rx.a($$0, F, $$24, epu.a(), rx.a, epl.a());
      rx.a($$0, G, $$24, eqd.a(5), epu.a(), rx.a, epl.a());
      rx.a($$0, H, $$24, eqd.a(6), epu.a(), rx.a, epl.a());
      rx.a($$0, J, $$16, eqd.a(6), epu.a(), rx.a, epl.a());
      rx.a($$0, K, $$14, epp.a(4), epu.a(), rx.a, epl.a(), ro.a(dmc.ui));
      rx.a($$0, I, $$15, epu.a(), rx.d, epl.a());
      rx.a($$0, L, $$25, eqd.a(2), epu.a(), rx.f, epl.a());
      rx.a($$0, M, $$26, eqd.a(2), epu.a(), rx.f, epl.a());
      rx.a($$0, N, $$25, a(256, null));
      rx.a($$0, O, $$26, a(512, null));
      rx.a($$0, P, $$25, a(4, null));
      rx.a($$0, Q, $$26, a(256, null));
      rx.a($$0, R, $$25, a(4, epp.a(3)));
      rx.a($$0, S, $$26, a(171, null));
      rx.a($$0, T, $$25, a(0, epp.a(2)));
      rx.a($$0, U, $$26, a(64, null));
      rx.a($$0, V, $$27, eqd.a(16), epu.a(), rx.a, epl.a());
      rx.a($$0, W, $$27, eqd.a(32), epu.a(), rx.a, epl.a());
      rx.a($$0, X, $$28, epp.a(3), eqd.a(2), epu.a(), rx.a, epl.a());
      rx.a($$0, Y, $$29, eqd.a(32), epu.a(), rx.a, epl.a());
      rx.a($$0, Z, $$30, epw.a(-0.8, 15, 4), eqd.a(32), epu.a(), rx.a, epl.a());
      rx.a($$0, ab, $$32, epw.a(-0.8, 5, 10), epu.a(), rx.a, epl.a());
      rx.a($$0, aa, $$31, epu.a(), rx.a, epl.a());
      rx.a($$0, ac, $$33, eqd.a(32), epu.a(), rx.a, epl.a());
      rx.a($$0, ad, $$34, epp.a(3), eqd.a(2), epu.a(), rx.a, epl.a());
      rx.a($$0, ae, $$35, epw.a(-0.8, 5, 10), epu.a(), rx.a, epl.a());
      eqa $$64 = eqg.a(0);
      rx.a($$0, af, $$36, rx.a(0, 0.05F, 1), epu.a(), $$64, rx.e, epm.a(ehf.a(dmc.z.m(), iu.c)), epl.a());
      rx.a($$0, ag, $$37, epp.a(16), epu.a(), $$64, rx.e, epl.a());
      rx.a($$0, ah, $$38, epp.a(16), epu.a(), $$64, rx.e, epl.a());
      rx.a($$0, ai, $$39, eqd.a(7), epu.a(), rx.a, epp.a(bsz.a(btm.a(-1, 3), 0, 3)), epl.a());
      rx.a($$0, aj, $$39, eqd.a(7), epu.a(), rx.a, epp.a(bsz.a(btm.a(-3, 1), 0, 1)), epl.a());
      rx.a($$0, ak, $$40, eqd.a(8), epu.a(), rx.b, epl.a());
      rx.a($$0, al, $$41, epp.a(1), epu.a(), rx.b, epl.a());
      rx.a($$0, am, $$42, a(rx.a(6, 0.1F, 1)));
      rx.a($$0, an, $$43, a(eqd.a(100)));
      rx.a($$0, ao, $$48, a(rx.a(10, 0.1F, 1), dmc.E));
      rx.a($$0, ap, $$44, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, aq, $$45, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, ar, $$63, a(rx.a(5, 0.1F, 1), dmc.z));
      rx.a($$0, as, $$47, a(rx.a(0, 0.1F, 1), dmc.A));
      rx.a($$0, at, $$49, rx.a(2, 0.1F, 1), epu.a(), eqg.a(2), rx.e, epl.a(), epm.a(ehf.a(dmc.z.m(), iu.c)));
      rx.a($$0, au, $$50, a(rx.a(2, 0.1F, 1)));
      rx.a($$0, av, $$50, a(rx.a(1, 0.1F, 1)));
      rx.a($$0, aw, $$51, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, ax, $$52, a(rx.a(10, 0.1F, 1), dmc.B));
      rx.a($$0, ay, $$53, a(rx.a(3, 0.1F, 1)));
      rx.a($$0, az, $$53, a(rx.a(0, 0.1F, 1)));
      rx.a($$0, aA, $$54, a(rx.a(0, 0.1F, 1)));
      rx.a($$0, aB, $$55, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, aC, $$56, a(rx.a(2, 0.1F, 1)));
      rx.a($$0, aD, $$57, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, aE, $$58, a(rx.a(10, 0.1F, 1)));
      rx.a($$0, aF, $$59, a(rx.a(50, 0.1F, 1)));
      rx.a($$0, aG, $$60, a(rx.a(30, 0.1F, 1)));
      rx.a($$0, aH, $$61, epu.a(), rx.a, epl.a());
      rx.a($$0, aI, $$62, epp.a(25), epu.a(), eqg.a(5), rx.e, epl.a(), epm.a(ehf.a(dmc.H.m(), iu.c)));
   }
}
