import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableList.Builder;
import java.util.List;
import javax.annotation.Nullable;

public class sa {
   public static final alj<erh> a = ry.a("bamboo_light");
   public static final alj<erh> b = ry.a("bamboo");
   public static final alj<erh> c = ry.a("vines");
   public static final alj<erh> d = ry.a("patch_sunflower");
   public static final alj<erh> e = ry.a("patch_pumpkin");
   public static final alj<erh> f = ry.a("patch_grass_plain");
   public static final alj<erh> g = ry.a("patch_grass_meadow");
   public static final alj<erh> h = ry.a("patch_grass_forest");
   public static final alj<erh> i = ry.a("patch_grass_badlands");
   public static final alj<erh> j = ry.a("patch_grass_savanna");
   public static final alj<erh> k = ry.a("patch_grass_normal");
   public static final alj<erh> l = ry.a("patch_grass_taiga_2");
   public static final alj<erh> m = ry.a("patch_grass_taiga");
   public static final alj<erh> n = ry.a("patch_grass_jungle");
   public static final alj<erh> o = ry.a("grass_bonemeal");
   public static final alj<erh> p = ry.a("patch_dead_bush_2");
   public static final alj<erh> q = ry.a("patch_dead_bush");
   public static final alj<erh> r = ry.a("patch_dead_bush_badlands");
   public static final alj<erh> s = ry.a("patch_dry_grass_badlands");
   public static final alj<erh> t = ry.a("patch_dry_grass_desert");
   public static final alj<erh> u = ry.a("patch_melon");
   public static final alj<erh> v = ry.a("patch_melon_sparse");
   public static final alj<erh> w = ry.a("patch_berry_common");
   public static final alj<erh> x = ry.a("patch_berry_rare");
   public static final alj<erh> y = ry.a("patch_waterlily");
   public static final alj<erh> z = ry.a("patch_tall_grass_2");
   public static final alj<erh> A = ry.a("patch_tall_grass");
   public static final alj<erh> B = ry.a("patch_large_fern");
   public static final alj<erh> C = ry.a("patch_bush");
   public static final alj<erh> D = ry.a("patch_leaf_litter");
   public static final alj<erh> E = ry.a("patch_cactus_desert");
   public static final alj<erh> F = ry.a("patch_cactus_decorated");
   public static final alj<erh> G = ry.a("patch_sugar_cane_swamp");
   public static final alj<erh> H = ry.a("patch_sugar_cane_desert");
   public static final alj<erh> I = ry.a("patch_sugar_cane_badlands");
   public static final alj<erh> J = ry.a("patch_sugar_cane");
   public static final alj<erh> K = ry.a("patch_firefly_bush_swamp");
   public static final alj<erh> L = ry.a("patch_firefly_bush_near_water_swamp");
   public static final alj<erh> M = ry.a("patch_firefly_bush_near_water");
   public static final alj<erh> N = ry.a("brown_mushroom_nether");
   public static final alj<erh> O = ry.a("red_mushroom_nether");
   public static final alj<erh> P = ry.a("brown_mushroom_normal");
   public static final alj<erh> Q = ry.a("red_mushroom_normal");
   public static final alj<erh> R = ry.a("brown_mushroom_taiga");
   public static final alj<erh> S = ry.a("red_mushroom_taiga");
   public static final alj<erh> T = ry.a("brown_mushroom_old_growth");
   public static final alj<erh> U = ry.a("red_mushroom_old_growth");
   public static final alj<erh> V = ry.a("brown_mushroom_swamp");
   public static final alj<erh> W = ry.a("red_mushroom_swamp");
   public static final alj<erh> X = ry.a("flower_warm");
   public static final alj<erh> Y = ry.a("flower_default");
   public static final alj<erh> Z = ry.a("flower_flower_forest");
   public static final alj<erh> aa = ry.a("flower_swamp");
   public static final alj<erh> ab = ry.a("flower_plains");
   public static final alj<erh> ac = ry.a("flower_meadow");
   public static final alj<erh> ad = ry.a("flower_cherry");
   public static final alj<erh> ae = ry.a("flower_pale_garden");
   public static final alj<erh> af = ry.a("wildflowers_birch_forest");
   public static final alj<erh> ag = ry.a("wildflowers_meadow");
   public static final alj<erh> ah = ry.a("trees_plains");
   public static final alj<erh> ai = ry.a("dark_forest_vegetation");
   public static final alj<erh> aj = ry.a("pale_garden_vegetation");
   public static final alj<erh> ak = ry.a("flower_forest_flowers");
   public static final alj<erh> al = ry.a("forest_flowers");
   public static final alj<erh> am = ry.a("pale_garden_flowers");
   public static final alj<erh> an = ry.a("pale_moss_patch");
   public static final alj<erh> ao = ry.a("trees_flower_forest");
   public static final alj<erh> ap = ry.a("trees_meadow");
   public static final alj<erh> aq = ry.a("trees_cherry");
   public static final alj<erh> ar = ry.a("trees_taiga");
   public static final alj<erh> as = ry.a("trees_grove");
   public static final alj<erh> at = ry.a("trees_badlands");
   public static final alj<erh> au = ry.a("trees_snowy");
   public static final alj<erh> av = ry.a("trees_swamp");
   public static final alj<erh> aw = ry.a("trees_windswept_savanna");
   public static final alj<erh> ax = ry.a("trees_savanna");
   public static final alj<erh> ay = ry.a("birch_tall");
   public static final alj<erh> az = ry.a("trees_birch");
   public static final alj<erh> aA = ry.a("trees_windswept_forest");
   public static final alj<erh> aB = ry.a("trees_windswept_hills");
   public static final alj<erh> aC = ry.a("trees_water");
   public static final alj<erh> aD = ry.a("trees_birch_and_oak_leaf_litter");
   public static final alj<erh> aE = ry.a("trees_sparse_jungle");
   public static final alj<erh> aF = ry.a("trees_old_growth_spruce_taiga");
   public static final alj<erh> aG = ry.a("trees_old_growth_pine_taiga");
   public static final alj<erh> aH = ry.a("trees_jungle");
   public static final alj<erh> aI = ry.a("bamboo_vegetation");
   public static final alj<erh> aJ = ry.a("mushroom_island_vegetation");
   public static final alj<erh> aK = ry.a("trees_mangrove");
   private static final erk aL = erq.a(0);

   public static List<erk> a(int $$0) {
      return List.of(eqz.a($$0), ere.a(), ry.d, eqv.a());
   }

   private static List<erk> a(int $$0, @Nullable erk $$1) {
      Builder<erk> $$2 = ImmutableList.builder();
      if ($$1 != null) {
         $$2.add($$1);
      }

      if ($$0 != 0) {
         $$2.add(ern.a($$0));
      }

      $$2.add(ere.a());
      $$2.add(ry.a);
      $$2.add(eqv.a());
      return $$2.build();
   }

   private static Builder<erk> b(erk $$0) {
      return ImmutableList.builder().add($$0).add(ere.a()).add(aL).add(ry.e).add(eqv.a());
   }

   public static List<erk> a(erk $$0) {
      return b($$0).build();
   }

   public static List<erk> a(erk $$0, dne $$1) {
      return b($$0).add(eqw.a(eim.a($$1.m(), iw.c))).build();
   }

   public static void a(qi<erh> $$0) {
      jh<ejx<?, ?>> $$1 = $$0.a(mi.aL);
      jg<ejx<?, ?>> $$2 = $$1.b(rp.a);
      jg<ejx<?, ?>> $$3 = $$1.b(rp.b);
      jg<ejx<?, ?>> $$4 = $$1.b(rp.c);
      jg<ejx<?, ?>> $$5 = $$1.b(rp.f);
      jg<ejx<?, ?>> $$6 = $$1.b(rp.g);
      jg<ejx<?, ?>> $$7 = $$1.b(rp.j);
      jg<ejx<?, ?>> $$8 = $$1.b(rp.k);
      jg<ejx<?, ?>> $$9 = $$1.b(rp.u);
      jg<ejx<?, ?>> $$10 = $$1.b(rp.i);
      jg<ejx<?, ?>> $$11 = $$1.b(rp.l);
      jg<ejx<?, ?>> $$12 = $$1.b(rp.m);
      jg<ejx<?, ?>> $$13 = $$1.b(rp.n);
      jg<ejx<?, ?>> $$14 = $$1.b(rp.o);
      jg<ejx<?, ?>> $$15 = $$1.b(rp.v);
      jg<ejx<?, ?>> $$16 = $$1.b(rp.p);
      jg<ejx<?, ?>> $$17 = $$1.b(rp.h);
      jg<ejx<?, ?>> $$18 = $$1.b(rp.q);
      jg<ejx<?, ?>> $$19 = $$1.b(rp.r);
      jg<ejx<?, ?>> $$20 = $$1.b(rp.s);
      jg<ejx<?, ?>> $$21 = $$1.b(rp.t);
      jg<ejx<?, ?>> $$22 = $$1.b(rp.w);
      jg<ejx<?, ?>> $$23 = $$1.b(rp.x);
      jg<ejx<?, ?>> $$24 = $$1.b(rp.d);
      jg<ejx<?, ?>> $$25 = $$1.b(rp.e);
      jg<ejx<?, ?>> $$26 = $$1.b(rp.y);
      jg<ejx<?, ?>> $$27 = $$1.b(rp.z);
      jg<ejx<?, ?>> $$28 = $$1.b(rp.A);
      jg<ejx<?, ?>> $$29 = $$1.b(rp.B);
      jg<ejx<?, ?>> $$30 = $$1.b(rp.C);
      jg<ejx<?, ?>> $$31 = $$1.b(rp.D);
      jg<ejx<?, ?>> $$32 = $$1.b(rp.E);
      jg<ejx<?, ?>> $$33 = $$1.b(rp.F);
      jg<ejx<?, ?>> $$34 = $$1.b(rp.G);
      jg<ejx<?, ?>> $$35 = $$1.b(rp.aa);
      jg<ejx<?, ?>> $$36 = $$1.b(rp.J);
      jg<ejx<?, ?>> $$37 = $$1.b(rp.K);
      jg<ejx<?, ?>> $$38 = $$1.b(rp.H);
      jg<ejx<?, ?>> $$39 = $$1.b(rp.I);
      jg<ejx<?, ?>> $$40 = $$1.b(rp.M);
      jg<ejx<?, ?>> $$41 = $$1.b(rp.O);
      jg<ejx<?, ?>> $$42 = $$1.b(rp.P);
      jg<ejx<?, ?>> $$43 = $$1.b(rp.Q);
      jg<ejx<?, ?>> $$44 = $$1.b(rp.R);
      jg<ejx<?, ?>> $$45 = $$1.b(rp.S);
      jg<ejx<?, ?>> $$46 = $$1.b(rp.U);
      jg<ejx<?, ?>> $$47 = $$1.b(ro.O);
      jg<ejx<?, ?>> $$48 = $$1.b(ro.x);
      jg<ejx<?, ?>> $$49 = $$1.b(rp.T);
      jg<ejx<?, ?>> $$50 = $$1.b(rp.W);
      jg<ejx<?, ?>> $$51 = $$1.b(rp.V);
      jg<ejx<?, ?>> $$52 = $$1.b(rp.X);
      jg<ejx<?, ?>> $$53 = $$1.b(rp.Y);
      jg<ejx<?, ?>> $$54 = $$1.b(rp.Z);
      jg<ejx<?, ?>> $$55 = $$1.b(rp.ab);
      jg<ejx<?, ?>> $$56 = $$1.b(rp.ac);
      jg<ejx<?, ?>> $$57 = $$1.b(rp.ad);
      jg<ejx<?, ?>> $$58 = $$1.b(rp.ae);
      jg<ejx<?, ?>> $$59 = $$1.b(rp.af);
      jg<ejx<?, ?>> $$60 = $$1.b(rp.ag);
      jg<ejx<?, ?>> $$61 = $$1.b(rp.ah);
      ry.a($$0, a, $$2, ern.a(4), ere.a(), ry.a, eqv.a());
      ry.a($$0, b, $$3, erf.a(160, 80.0, 0.3), ere.a(), ry.d, eqv.a());
      ry.a($$0, c, $$4, eqz.a(127), ere.a(), erc.a(ehz.a(64), ehz.a(100)), eqv.a());
      ry.a($$0, d, $$5, ern.a(3), ere.a(), ry.a, eqv.a());
      ry.a($$0, e, $$6, ern.a(300), ere.a(), ry.a, eqv.a());
      ry.a($$0, f, $$7, erg.a(-0.8, 5, 10), ere.a(), ry.d, eqv.a());
      ry.a($$0, g, $$8, erg.a(-0.8, 5, 10), ere.a(), ry.d, eqv.a());
      ry.a($$0, h, $$7, a(2));
      ry.a($$0, D, $$9, a(2));
      ry.a($$0, i, $$7, ere.a(), ry.d, eqv.a());
      ry.a($$0, j, $$7, a(20));
      ry.a($$0, k, $$7, a(5));
      ry.a($$0, l, $$10, ere.a(), ry.d, eqv.a());
      ry.a($$0, m, $$10, a(7));
      ry.a($$0, n, $$11, a(25));
      ry.a($$0, o, $$12, ry.a());
      ry.a($$0, p, $$13, a(2));
      ry.a($$0, q, $$13, ere.a(), ry.d, eqv.a());
      ry.a($$0, r, $$13, a(20));
      ry.a($$0, s, $$14, ern.a(6), ere.a(), ry.a, eqv.a());
      ry.a($$0, t, $$14, ern.a(3), ere.a(), ry.a, eqv.a());
      ry.a($$0, u, $$16, ern.a(6), ere.a(), ry.a, eqv.a());
      ry.a($$0, v, $$16, ern.a(64), ere.a(), ry.a, eqv.a());
      ry.a($$0, w, $$17, ern.a(32), ere.a(), ry.d, eqv.a());
      ry.a($$0, x, $$17, ern.a(384), ere.a(), ry.d, eqv.a());
      ry.a($$0, y, $$18, a(4));
      ry.a($$0, z, $$19, erg.a(-0.8, 0, 7), ern.a(32), ere.a(), ry.a, eqv.a());
      ry.a($$0, A, $$19, ern.a(5), ere.a(), ry.a, eqv.a());
      ry.a($$0, B, $$20, ern.a(5), ere.a(), ry.a, eqv.a());
      ry.a($$0, C, $$21, ern.a(4), ere.a(), ry.a, eqv.a());
      ry.a($$0, E, $$22, ern.a(6), ere.a(), ry.a, eqv.a());
      ry.a($$0, F, $$22, ern.a(13), ere.a(), ry.a, eqv.a());
      ry.a($$0, G, $$23, ern.a(3), ere.a(), ry.a, eqv.a());
      ry.a($$0, H, $$23, ere.a(), ry.a, eqv.a());
      ry.a($$0, I, $$23, ern.a(5), ere.a(), ry.a, eqv.a());
      ry.a($$0, J, $$23, ern.a(6), ere.a(), ry.a, eqv.a());
      ry.a($$0, M, $$15, eqz.a(2), ere.a(), ry.b, eqv.a(), rp.a(dng.ul));
      ry.a($$0, L, $$15, eqz.a(3), ere.a(), ry.a, eqv.a(), rp.a(dng.ul));
      ry.a($$0, K, $$15, ern.a(8), ere.a(), ry.a, eqv.a());
      ry.a($$0, N, $$24, ern.a(2), ere.a(), ry.f, eqv.a());
      ry.a($$0, O, $$25, ern.a(2), ere.a(), ry.f, eqv.a());
      ry.a($$0, P, $$24, a(256, null));
      ry.a($$0, Q, $$25, a(512, null));
      ry.a($$0, R, $$24, a(4, null));
      ry.a($$0, S, $$25, a(256, null));
      ry.a($$0, T, $$24, a(4, eqz.a(3)));
      ry.a($$0, U, $$25, a(171, null));
      ry.a($$0, V, $$24, a(0, eqz.a(2)));
      ry.a($$0, W, $$25, a(64, null));
      ry.a($$0, X, $$26, ern.a(16), ere.a(), ry.a, eqv.a());
      ry.a($$0, Y, $$26, ern.a(32), ere.a(), ry.a, eqv.a());
      ry.a($$0, Z, $$27, eqz.a(3), ern.a(2), ere.a(), ry.a, eqv.a());
      ry.a($$0, aa, $$28, ern.a(32), ere.a(), ry.a, eqv.a());
      ry.a($$0, ab, $$29, erg.a(-0.8, 15, 4), ern.a(32), ere.a(), ry.a, eqv.a());
      ry.a($$0, ad, $$31, erg.a(-0.8, 5, 10), ere.a(), ry.a, eqv.a());
      ry.a($$0, ac, $$30, ere.a(), ry.a, eqv.a());
      ry.a($$0, ae, $$32, ern.a(32), ere.a(), ry.a, eqv.a());
      ry.a($$0, af, $$33, eqz.a(3), ern.a(2), ere.a(), ry.a, eqv.a());
      ry.a($$0, ag, $$34, erg.a(-0.8, 5, 10), ere.a(), ry.a, eqv.a());
      erk $$62 = erq.a(0);
      ry.a($$0, ah, $$35, ry.a(0, 0.05F, 1), ere.a(), $$62, ry.e, eqw.a(eim.a(dng.z.m(), iw.c)), eqv.a());
      ry.a($$0, ai, $$36, eqz.a(16), ere.a(), $$62, ry.e, eqv.a());
      ry.a($$0, aj, $$37, eqz.a(16), ere.a(), $$62, ry.e, eqv.a());
      ry.a($$0, ak, $$38, ern.a(7), ere.a(), ry.a, eqz.a(btr.a(bue.a(-1, 3), 0, 3)), eqv.a());
      ry.a($$0, al, $$38, ern.a(7), ere.a(), ry.a, eqz.a(btr.a(bue.a(-3, 1), 0, 1)), eqv.a());
      ry.a($$0, am, $$39, ern.a(8), ere.a(), ry.b, eqv.a());
      ry.a($$0, an, $$40, eqz.a(1), ere.a(), ry.b, eqv.a());
      ry.a($$0, ao, $$41, a(ry.a(6, 0.1F, 1)));
      ry.a($$0, ap, $$42, a(ern.a(100)));
      ry.a($$0, aq, $$47, a(ry.a(10, 0.1F, 1), dng.E));
      ry.a($$0, ar, $$43, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, as, $$45, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, at, $$44, a(ry.a(5, 0.1F, 1), dng.z));
      ry.a($$0, au, $$46, a(ry.a(0, 0.1F, 1), dng.A));
      ry.a($$0, av, $$48, ry.a(2, 0.1F, 1), ere.a(), erq.a(2), ry.e, eqv.a(), eqw.a(eim.a(dng.z.m(), iw.c)));
      ry.a($$0, aw, $$49, a(ry.a(2, 0.1F, 1)));
      ry.a($$0, ax, $$49, a(ry.a(1, 0.1F, 1)));
      ry.a($$0, ay, $$50, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, az, $$51, a(ry.a(10, 0.1F, 1), dng.B));
      ry.a($$0, aA, $$52, a(ry.a(3, 0.1F, 1)));
      ry.a($$0, aB, $$52, a(ry.a(0, 0.1F, 1)));
      ry.a($$0, aC, $$53, a(ry.a(0, 0.1F, 1)));
      ry.a($$0, aD, $$54, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, aE, $$55, a(ry.a(2, 0.1F, 1)));
      ry.a($$0, aF, $$56, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, aG, $$57, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, aH, $$58, a(ry.a(50, 0.1F, 1)));
      ry.a($$0, aI, $$59, a(ry.a(30, 0.1F, 1)));
      ry.a($$0, aJ, $$60, ere.a(), ry.a, eqv.a());
      ry.a($$0, aK, $$61, eqz.a(25), ere.a(), erq.a(5), ry.e, eqv.a(), eqw.a(eim.a(dng.H.m(), iw.c)));
   }
}
