import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableList.Builder;
import java.util.List;
import javax.annotation.Nullable;

public class sa {
   public static final alq<err> a = ry.a("bamboo_light");
   public static final alq<err> b = ry.a("bamboo");
   public static final alq<err> c = ry.a("vines");
   public static final alq<err> d = ry.a("patch_sunflower");
   public static final alq<err> e = ry.a("patch_pumpkin");
   public static final alq<err> f = ry.a("patch_grass_plain");
   public static final alq<err> g = ry.a("patch_grass_meadow");
   public static final alq<err> h = ry.a("patch_grass_forest");
   public static final alq<err> i = ry.a("patch_grass_badlands");
   public static final alq<err> j = ry.a("patch_grass_savanna");
   public static final alq<err> k = ry.a("patch_grass_normal");
   public static final alq<err> l = ry.a("patch_grass_taiga_2");
   public static final alq<err> m = ry.a("patch_grass_taiga");
   public static final alq<err> n = ry.a("patch_grass_jungle");
   public static final alq<err> o = ry.a("grass_bonemeal");
   public static final alq<err> p = ry.a("patch_dead_bush_2");
   public static final alq<err> q = ry.a("patch_dead_bush");
   public static final alq<err> r = ry.a("patch_dead_bush_badlands");
   public static final alq<err> s = ry.a("patch_dry_grass_badlands");
   public static final alq<err> t = ry.a("patch_dry_grass_desert");
   public static final alq<err> u = ry.a("patch_melon");
   public static final alq<err> v = ry.a("patch_melon_sparse");
   public static final alq<err> w = ry.a("patch_berry_common");
   public static final alq<err> x = ry.a("patch_berry_rare");
   public static final alq<err> y = ry.a("patch_waterlily");
   public static final alq<err> z = ry.a("patch_tall_grass_2");
   public static final alq<err> A = ry.a("patch_tall_grass");
   public static final alq<err> B = ry.a("patch_large_fern");
   public static final alq<err> C = ry.a("patch_bush");
   public static final alq<err> D = ry.a("patch_leaf_litter");
   public static final alq<err> E = ry.a("patch_cactus_desert");
   public static final alq<err> F = ry.a("patch_cactus_decorated");
   public static final alq<err> G = ry.a("patch_sugar_cane_swamp");
   public static final alq<err> H = ry.a("patch_sugar_cane_desert");
   public static final alq<err> I = ry.a("patch_sugar_cane_badlands");
   public static final alq<err> J = ry.a("patch_sugar_cane");
   public static final alq<err> K = ry.a("patch_firefly_bush_swamp");
   public static final alq<err> L = ry.a("patch_firefly_bush_near_water_swamp");
   public static final alq<err> M = ry.a("patch_firefly_bush_near_water");
   public static final alq<err> N = ry.a("brown_mushroom_nether");
   public static final alq<err> O = ry.a("red_mushroom_nether");
   public static final alq<err> P = ry.a("brown_mushroom_normal");
   public static final alq<err> Q = ry.a("red_mushroom_normal");
   public static final alq<err> R = ry.a("brown_mushroom_taiga");
   public static final alq<err> S = ry.a("red_mushroom_taiga");
   public static final alq<err> T = ry.a("brown_mushroom_old_growth");
   public static final alq<err> U = ry.a("red_mushroom_old_growth");
   public static final alq<err> V = ry.a("brown_mushroom_swamp");
   public static final alq<err> W = ry.a("red_mushroom_swamp");
   public static final alq<err> X = ry.a("flower_warm");
   public static final alq<err> Y = ry.a("flower_default");
   public static final alq<err> Z = ry.a("flower_flower_forest");
   public static final alq<err> aa = ry.a("flower_swamp");
   public static final alq<err> ab = ry.a("flower_plains");
   public static final alq<err> ac = ry.a("flower_meadow");
   public static final alq<err> ad = ry.a("flower_cherry");
   public static final alq<err> ae = ry.a("flower_pale_garden");
   public static final alq<err> af = ry.a("wildflowers_birch_forest");
   public static final alq<err> ag = ry.a("wildflowers_meadow");
   public static final alq<err> ah = ry.a("trees_plains");
   public static final alq<err> ai = ry.a("dark_forest_vegetation");
   public static final alq<err> aj = ry.a("pale_garden_vegetation");
   public static final alq<err> ak = ry.a("flower_forest_flowers");
   public static final alq<err> al = ry.a("forest_flowers");
   public static final alq<err> am = ry.a("pale_garden_flowers");
   public static final alq<err> an = ry.a("pale_moss_patch");
   public static final alq<err> ao = ry.a("trees_flower_forest");
   public static final alq<err> ap = ry.a("trees_meadow");
   public static final alq<err> aq = ry.a("trees_cherry");
   public static final alq<err> ar = ry.a("trees_taiga");
   public static final alq<err> as = ry.a("trees_grove");
   public static final alq<err> at = ry.a("trees_badlands");
   public static final alq<err> au = ry.a("trees_snowy");
   public static final alq<err> av = ry.a("trees_swamp");
   public static final alq<err> aw = ry.a("trees_windswept_savanna");
   public static final alq<err> ax = ry.a("trees_savanna");
   public static final alq<err> ay = ry.a("birch_tall");
   public static final alq<err> az = ry.a("trees_birch");
   public static final alq<err> aA = ry.a("trees_windswept_forest");
   public static final alq<err> aB = ry.a("trees_windswept_hills");
   public static final alq<err> aC = ry.a("trees_water");
   public static final alq<err> aD = ry.a("trees_birch_and_oak_leaf_litter");
   public static final alq<err> aE = ry.a("trees_sparse_jungle");
   public static final alq<err> aF = ry.a("trees_old_growth_spruce_taiga");
   public static final alq<err> aG = ry.a("trees_old_growth_pine_taiga");
   public static final alq<err> aH = ry.a("trees_jungle");
   public static final alq<err> aI = ry.a("bamboo_vegetation");
   public static final alq<err> aJ = ry.a("mushroom_island_vegetation");
   public static final alq<err> aK = ry.a("trees_mangrove");
   private static final eru aL = esa.a(0);

   public static List<eru> a(int $$0) {
      return List.of(erj.a($$0), ero.a(), ry.d, erf.a());
   }

   private static List<eru> a(int $$0, @Nullable eru $$1) {
      Builder<eru> $$2 = ImmutableList.builder();
      if ($$1 != null) {
         $$2.add($$1);
      }

      if ($$0 != 0) {
         $$2.add(erx.a($$0));
      }

      $$2.add(ero.a());
      $$2.add(ry.a);
      $$2.add(erf.a());
      return $$2.build();
   }

   private static Builder<eru> b(eru $$0) {
      return ImmutableList.builder().add($$0).add(ero.a()).add(aL).add(ry.e).add(erf.a());
   }

   public static List<eru> a(eru $$0) {
      return b($$0).build();
   }

   public static List<eru> a(eru $$0, dno $$1) {
      return b($$0).add(erg.a(eiw.a($$1.m(), iw.c))).build();
   }

   public static void a(qi<err> $$0) {
      jh<ekh<?, ?>> $$1 = $$0.a(mi.aL);
      jg<ekh<?, ?>> $$2 = $$1.b(rp.a);
      jg<ekh<?, ?>> $$3 = $$1.b(rp.b);
      jg<ekh<?, ?>> $$4 = $$1.b(rp.c);
      jg<ekh<?, ?>> $$5 = $$1.b(rp.f);
      jg<ekh<?, ?>> $$6 = $$1.b(rp.g);
      jg<ekh<?, ?>> $$7 = $$1.b(rp.j);
      jg<ekh<?, ?>> $$8 = $$1.b(rp.k);
      jg<ekh<?, ?>> $$9 = $$1.b(rp.u);
      jg<ekh<?, ?>> $$10 = $$1.b(rp.i);
      jg<ekh<?, ?>> $$11 = $$1.b(rp.l);
      jg<ekh<?, ?>> $$12 = $$1.b(rp.m);
      jg<ekh<?, ?>> $$13 = $$1.b(rp.n);
      jg<ekh<?, ?>> $$14 = $$1.b(rp.o);
      jg<ekh<?, ?>> $$15 = $$1.b(rp.v);
      jg<ekh<?, ?>> $$16 = $$1.b(rp.p);
      jg<ekh<?, ?>> $$17 = $$1.b(rp.h);
      jg<ekh<?, ?>> $$18 = $$1.b(rp.q);
      jg<ekh<?, ?>> $$19 = $$1.b(rp.r);
      jg<ekh<?, ?>> $$20 = $$1.b(rp.s);
      jg<ekh<?, ?>> $$21 = $$1.b(rp.t);
      jg<ekh<?, ?>> $$22 = $$1.b(rp.w);
      jg<ekh<?, ?>> $$23 = $$1.b(rp.x);
      jg<ekh<?, ?>> $$24 = $$1.b(rp.d);
      jg<ekh<?, ?>> $$25 = $$1.b(rp.e);
      jg<ekh<?, ?>> $$26 = $$1.b(rp.y);
      jg<ekh<?, ?>> $$27 = $$1.b(rp.z);
      jg<ekh<?, ?>> $$28 = $$1.b(rp.A);
      jg<ekh<?, ?>> $$29 = $$1.b(rp.B);
      jg<ekh<?, ?>> $$30 = $$1.b(rp.C);
      jg<ekh<?, ?>> $$31 = $$1.b(rp.D);
      jg<ekh<?, ?>> $$32 = $$1.b(rp.E);
      jg<ekh<?, ?>> $$33 = $$1.b(rp.F);
      jg<ekh<?, ?>> $$34 = $$1.b(rp.G);
      jg<ekh<?, ?>> $$35 = $$1.b(rp.aa);
      jg<ekh<?, ?>> $$36 = $$1.b(rp.J);
      jg<ekh<?, ?>> $$37 = $$1.b(rp.K);
      jg<ekh<?, ?>> $$38 = $$1.b(rp.H);
      jg<ekh<?, ?>> $$39 = $$1.b(rp.I);
      jg<ekh<?, ?>> $$40 = $$1.b(rp.M);
      jg<ekh<?, ?>> $$41 = $$1.b(rp.O);
      jg<ekh<?, ?>> $$42 = $$1.b(rp.P);
      jg<ekh<?, ?>> $$43 = $$1.b(rp.Q);
      jg<ekh<?, ?>> $$44 = $$1.b(rp.R);
      jg<ekh<?, ?>> $$45 = $$1.b(rp.S);
      jg<ekh<?, ?>> $$46 = $$1.b(rp.U);
      jg<ekh<?, ?>> $$47 = $$1.b(ro.O);
      jg<ekh<?, ?>> $$48 = $$1.b(ro.x);
      jg<ekh<?, ?>> $$49 = $$1.b(rp.T);
      jg<ekh<?, ?>> $$50 = $$1.b(rp.W);
      jg<ekh<?, ?>> $$51 = $$1.b(rp.V);
      jg<ekh<?, ?>> $$52 = $$1.b(rp.X);
      jg<ekh<?, ?>> $$53 = $$1.b(rp.Y);
      jg<ekh<?, ?>> $$54 = $$1.b(rp.Z);
      jg<ekh<?, ?>> $$55 = $$1.b(rp.ab);
      jg<ekh<?, ?>> $$56 = $$1.b(rp.ac);
      jg<ekh<?, ?>> $$57 = $$1.b(rp.ad);
      jg<ekh<?, ?>> $$58 = $$1.b(rp.ae);
      jg<ekh<?, ?>> $$59 = $$1.b(rp.af);
      jg<ekh<?, ?>> $$60 = $$1.b(rp.ag);
      jg<ekh<?, ?>> $$61 = $$1.b(rp.ah);
      ry.a($$0, a, $$2, erx.a(4), ero.a(), ry.a, erf.a());
      ry.a($$0, b, $$3, erp.a(160, 80.0, 0.3), ero.a(), ry.d, erf.a());
      ry.a($$0, c, $$4, erj.a(127), ero.a(), erm.a(eij.a(64), eij.a(100)), erf.a());
      ry.a($$0, d, $$5, erx.a(3), ero.a(), ry.a, erf.a());
      ry.a($$0, e, $$6, erx.a(300), ero.a(), ry.a, erf.a());
      ry.a($$0, f, $$7, erq.a(-0.8, 5, 10), ero.a(), ry.d, erf.a());
      ry.a($$0, g, $$8, erq.a(-0.8, 5, 10), ero.a(), ry.d, erf.a());
      ry.a($$0, h, $$7, a(2));
      ry.a($$0, D, $$9, a(2));
      ry.a($$0, i, $$7, ero.a(), ry.d, erf.a());
      ry.a($$0, j, $$7, a(20));
      ry.a($$0, k, $$7, a(5));
      ry.a($$0, l, $$10, ero.a(), ry.d, erf.a());
      ry.a($$0, m, $$10, a(7));
      ry.a($$0, n, $$11, a(25));
      ry.a($$0, o, $$12, ry.a());
      ry.a($$0, p, $$13, a(2));
      ry.a($$0, q, $$13, ero.a(), ry.d, erf.a());
      ry.a($$0, r, $$13, a(20));
      ry.a($$0, s, $$14, erx.a(6), ero.a(), ry.a, erf.a());
      ry.a($$0, t, $$14, erx.a(3), ero.a(), ry.a, erf.a());
      ry.a($$0, u, $$16, erx.a(6), ero.a(), ry.a, erf.a());
      ry.a($$0, v, $$16, erx.a(64), ero.a(), ry.a, erf.a());
      ry.a($$0, w, $$17, erx.a(32), ero.a(), ry.d, erf.a());
      ry.a($$0, x, $$17, erx.a(384), ero.a(), ry.d, erf.a());
      ry.a($$0, y, $$18, a(4));
      ry.a($$0, z, $$19, erq.a(-0.8, 0, 7), erx.a(32), ero.a(), ry.a, erf.a());
      ry.a($$0, A, $$19, erx.a(5), ero.a(), ry.a, erf.a());
      ry.a($$0, B, $$20, erx.a(5), ero.a(), ry.a, erf.a());
      ry.a($$0, C, $$21, erx.a(4), ero.a(), ry.a, erf.a());
      ry.a($$0, E, $$22, erx.a(6), ero.a(), ry.a, erf.a());
      ry.a($$0, F, $$22, erx.a(13), ero.a(), ry.a, erf.a());
      ry.a($$0, G, $$23, erx.a(3), ero.a(), ry.a, erf.a());
      ry.a($$0, H, $$23, ero.a(), ry.a, erf.a());
      ry.a($$0, I, $$23, erx.a(5), ero.a(), ry.a, erf.a());
      ry.a($$0, J, $$23, erx.a(6), ero.a(), ry.a, erf.a());
      ry.a($$0, M, $$15, erj.a(2), ero.a(), ry.b, erf.a(), rp.a(dnq.ul));
      ry.a($$0, L, $$15, erj.a(3), ero.a(), ry.a, erf.a(), rp.a(dnq.ul));
      ry.a($$0, K, $$15, erx.a(8), ero.a(), ry.a, erf.a());
      ry.a($$0, N, $$24, erx.a(2), ero.a(), ry.f, erf.a());
      ry.a($$0, O, $$25, erx.a(2), ero.a(), ry.f, erf.a());
      ry.a($$0, P, $$24, a(256, null));
      ry.a($$0, Q, $$25, a(512, null));
      ry.a($$0, R, $$24, a(4, null));
      ry.a($$0, S, $$25, a(256, null));
      ry.a($$0, T, $$24, a(4, erj.a(3)));
      ry.a($$0, U, $$25, a(171, null));
      ry.a($$0, V, $$24, a(0, erj.a(2)));
      ry.a($$0, W, $$25, a(64, null));
      ry.a($$0, X, $$26, erx.a(16), ero.a(), ry.a, erf.a());
      ry.a($$0, Y, $$26, erx.a(32), ero.a(), ry.a, erf.a());
      ry.a($$0, Z, $$27, erj.a(3), erx.a(2), ero.a(), ry.a, erf.a());
      ry.a($$0, aa, $$28, erx.a(32), ero.a(), ry.a, erf.a());
      ry.a($$0, ab, $$29, erq.a(-0.8, 15, 4), erx.a(32), ero.a(), ry.a, erf.a());
      ry.a($$0, ad, $$31, erq.a(-0.8, 5, 10), ero.a(), ry.a, erf.a());
      ry.a($$0, ac, $$30, ero.a(), ry.a, erf.a());
      ry.a($$0, ae, $$32, erx.a(32), ero.a(), ry.a, erf.a());
      ry.a($$0, af, $$33, erj.a(3), erx.a(2), ero.a(), ry.a, erf.a());
      ry.a($$0, ag, $$34, erq.a(-0.8, 5, 10), ero.a(), ry.a, erf.a());
      eru $$62 = esa.a(0);
      ry.a($$0, ah, $$35, ry.a(0, 0.05F, 1), ero.a(), $$62, ry.e, erg.a(eiw.a(dnq.z.m(), iw.c)), erf.a());
      ry.a($$0, ai, $$36, erj.a(16), ero.a(), $$62, ry.e, erf.a());
      ry.a($$0, aj, $$37, erj.a(16), ero.a(), $$62, ry.e, erf.a());
      ry.a($$0, ak, $$38, erx.a(7), ero.a(), ry.a, erj.a(bua.a(bun.a(-1, 3), 0, 3)), erf.a());
      ry.a($$0, al, $$38, erx.a(7), ero.a(), ry.a, erj.a(bua.a(bun.a(-3, 1), 0, 1)), erf.a());
      ry.a($$0, am, $$39, erx.a(8), ero.a(), ry.b, erf.a());
      ry.a($$0, an, $$40, erj.a(1), ero.a(), ry.b, erf.a());
      ry.a($$0, ao, $$41, a(ry.a(6, 0.1F, 1)));
      ry.a($$0, ap, $$42, a(erx.a(100)));
      ry.a($$0, aq, $$47, a(ry.a(10, 0.1F, 1), dnq.E));
      ry.a($$0, ar, $$43, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, as, $$45, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, at, $$44, a(ry.a(5, 0.1F, 1), dnq.z));
      ry.a($$0, au, $$46, a(ry.a(0, 0.1F, 1), dnq.A));
      ry.a($$0, av, $$48, ry.a(2, 0.1F, 1), ero.a(), esa.a(2), ry.e, erf.a(), erg.a(eiw.a(dnq.z.m(), iw.c)));
      ry.a($$0, aw, $$49, a(ry.a(2, 0.1F, 1)));
      ry.a($$0, ax, $$49, a(ry.a(1, 0.1F, 1)));
      ry.a($$0, ay, $$50, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, az, $$51, a(ry.a(10, 0.1F, 1), dnq.B));
      ry.a($$0, aA, $$52, a(ry.a(3, 0.1F, 1)));
      ry.a($$0, aB, $$52, a(ry.a(0, 0.1F, 1)));
      ry.a($$0, aC, $$53, a(ry.a(0, 0.1F, 1)));
      ry.a($$0, aD, $$54, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, aE, $$55, a(ry.a(2, 0.1F, 1)));
      ry.a($$0, aF, $$56, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, aG, $$57, a(ry.a(10, 0.1F, 1)));
      ry.a($$0, aH, $$58, a(ry.a(50, 0.1F, 1)));
      ry.a($$0, aI, $$59, a(ry.a(30, 0.1F, 1)));
      ry.a($$0, aJ, $$60, ero.a(), ry.a, erf.a());
      ry.a($$0, aK, $$61, erj.a(25), ero.a(), esa.a(5), ry.e, erf.a(), erg.a(eiw.a(dnq.H.m(), iw.c)));
   }
}
