import java.util.List;

public class sb {
   public static final alg<edr<?, ?>> a = ry.a("ore_magma");
   public static final alg<edr<?, ?>> b = ry.a("ore_soul_sand");
   public static final alg<edr<?, ?>> c = ry.a("ore_nether_gold");
   public static final alg<edr<?, ?>> d = ry.a("ore_quartz");
   public static final alg<edr<?, ?>> e = ry.a("ore_gravel_nether");
   public static final alg<edr<?, ?>> f = ry.a("ore_blackstone");
   public static final alg<edr<?, ?>> g = ry.a("ore_dirt");
   public static final alg<edr<?, ?>> h = ry.a("ore_gravel");
   public static final alg<edr<?, ?>> i = ry.a("ore_granite");
   public static final alg<edr<?, ?>> j = ry.a("ore_diorite");
   public static final alg<edr<?, ?>> k = ry.a("ore_andesite");
   public static final alg<edr<?, ?>> l = ry.a("ore_tuff");
   public static final alg<edr<?, ?>> m = ry.a("ore_coal");
   public static final alg<edr<?, ?>> n = ry.a("ore_coal_buried");
   public static final alg<edr<?, ?>> o = ry.a("ore_iron");
   public static final alg<edr<?, ?>> p = ry.a("ore_iron_small");
   public static final alg<edr<?, ?>> q = ry.a("ore_gold");
   public static final alg<edr<?, ?>> r = ry.a("ore_gold_buried");
   public static final alg<edr<?, ?>> s = ry.a("ore_redstone");
   public static final alg<edr<?, ?>> t = ry.a("ore_diamond_small");
   public static final alg<edr<?, ?>> u = ry.a("ore_diamond_medium");
   public static final alg<edr<?, ?>> v = ry.a("ore_diamond_large");
   public static final alg<edr<?, ?>> w = ry.a("ore_diamond_buried");
   public static final alg<edr<?, ?>> x = ry.a("ore_lapis");
   public static final alg<edr<?, ?>> y = ry.a("ore_lapis_buried");
   public static final alg<edr<?, ?>> z = ry.a("ore_infested");
   public static final alg<edr<?, ?>> A = ry.a("ore_emerald");
   public static final alg<edr<?, ?>> B = ry.a("ore_ancient_debris_large");
   public static final alg<edr<?, ?>> C = ry.a("ore_ancient_debris_small");
   public static final alg<edr<?, ?>> D = ry.a("ore_copper_small");
   public static final alg<edr<?, ?>> E = ry.a("ore_copper_large");
   public static final alg<edr<?, ?>> F = ry.a("ore_clay");

   public static void a(qx<edr<?, ?>> $$0) {
      epn $$1 = new epv(awz.bf);
      epn $$2 = new epv(awz.bg);
      epn $$3 = new epv(awz.bh);
      epn $$4 = new eov(dia.dV);
      epn $$5 = new epv(awz.bi);
      List<egr.a> $$6 = List.of(egr.a($$2, dia.P.m()), egr.a($$3, dia.Q.m()));
      List<egr.a> $$7 = List.of(egr.a($$2, dia.N.m()), egr.a($$3, dia.O.m()));
      List<egr.a> $$8 = List.of(egr.a($$2, dia.cx.m()), egr.a($$3, dia.cy.m()));
      List<egr.a> $$9 = List.of(egr.a($$2, dia.aR.m()), egr.a($$3, dia.aS.m()));
      List<egr.a> $$10 = List.of(egr.a($$2, dia.ra.m()), egr.a($$3, dia.rb.m()));
      List<egr.a> $$11 = List.of(egr.a($$2, dia.R.m()), egr.a($$3, dia.S.m()));
      ry.a($$0, a, eef.I, new egr($$4, dia.kJ.m(), 33));
      ry.a($$0, b, eef.I, new egr($$4, dia.dW.m(), 12));
      ry.a($$0, c, eef.I, new egr($$4, dia.T.m(), 10));
      ry.a($$0, d, eef.I, new egr($$4, dia.hb.m(), 14));
      ry.a($$0, e, eef.I, new egr($$4, dia.L.m(), 33));
      ry.a($$0, f, eef.I, new egr($$4, dia.pr.m(), 33));
      ry.a($$0, g, eef.I, new egr($$1, dia.j.m(), 33));
      ry.a($$0, h, eef.I, new egr($$1, dia.L.m(), 33));
      ry.a($$0, i, eef.I, new egr($$1, dia.c.m(), 64));
      ry.a($$0, j, eef.I, new egr($$1, dia.e.m(), 64));
      ry.a($$0, k, eef.I, new egr($$1, dia.g.m(), 64));
      ry.a($$0, l, eef.I, new egr($$1, dia.qz.m(), 64));
      ry.a($$0, m, eef.I, new egr($$11, 17));
      ry.a($$0, n, eef.I, new egr($$11, 17, 0.5F));
      ry.a($$0, o, eef.I, new egr($$6, 9));
      ry.a($$0, p, eef.I, new egr($$6, 4));
      ry.a($$0, q, eef.I, new egr($$7, 9));
      ry.a($$0, r, eef.I, new egr($$7, 9, 0.5F));
      ry.a($$0, s, eef.I, new egr(List.of(egr.a($$2, dia.dI.m()), egr.a($$3, dia.dJ.m())), 8));
      ry.a($$0, t, eef.I, new egr($$8, 4, 0.5F));
      ry.a($$0, v, eef.I, new egr($$8, 12, 0.7F));
      ry.a($$0, w, eef.I, new egr($$8, 8, 1.0F));
      ry.a($$0, u, eef.I, new egr($$8, 8, 0.5F));
      ry.a($$0, x, eef.I, new egr($$9, 7));
      ry.a($$0, y, eef.I, new egr($$9, 7, 1.0F));
      ry.a($$0, z, eef.I, new egr(List.of(egr.a($$2, dia.eN.m()), egr.a($$3, dia.td.m())), 9));
      ry.a($$0, A, eef.I, new egr(List.of(egr.a($$2, dia.fE.m()), egr.a($$3, dia.fF.m())), 3));
      ry.a($$0, B, eef.af, new egr($$5, dia.pj.m(), 3, 1.0F));
      ry.a($$0, C, eef.af, new egr($$5, dia.pj.m(), 2, 1.0F));
      ry.a($$0, D, eef.I, new egr($$10, 10));
      ry.a($$0, E, eef.I, new egr($$10, 20));
      ry.a($$0, F, eef.I, new egr($$1, dia.dR.m(), 33));
   }
}
