public class sb {
   public static final akq<eit> a = sg.a("monster_room");
   public static final akq<eit> b = sg.a("monster_room_deep");
   public static final akq<eit> c = sg.a("fossil_upper");
   public static final akq<eit> d = sg.a("fossil_lower");
   public static final akq<eit> e = sg.a("dripstone_cluster");
   public static final akq<eit> f = sg.a("large_dripstone");
   public static final akq<eit> g = sg.a("pointed_dripstone");
   public static final akq<eit> h = sg.a("underwater_magma");
   public static final akq<eit> i = sg.a("glow_lichen");
   public static final akq<eit> j = sg.a("rooted_azalea_tree");
   public static final akq<eit> k = sg.a("cave_vines");
   public static final akq<eit> l = sg.a("lush_caves_vegetation");
   public static final akq<eit> m = sg.a("lush_caves_clay");
   public static final akq<eit> n = sg.a("lush_caves_ceiling_vegetation");
   public static final akq<eit> o = sg.a("spore_blossom");
   public static final akq<eit> p = sg.a("classic_vines_cave_feature");
   public static final akq<eit> q = sg.a("amethyst_geode");
   public static final akq<eit> r = sg.a("sculk_patch_deep_dark");
   public static final akq<eit> s = sg.a("sculk_patch_ancient_city");
   public static final akq<eit> t = sg.a("sculk_vein");

   public static void a(qq<eit> $$0) {
      jn<ebq<?, ?>> $$1 = $$0.a(lu.aI);
      jm<ebq<?, ?>> $$2 = $$1.b(rp.a);
      jm<ebq<?, ?>> $$3 = $$1.b(rp.b);
      jm<ebq<?, ?>> $$4 = $$1.b(rp.c);
      jm<ebq<?, ?>> $$5 = $$1.b(rp.d);
      jm<ebq<?, ?>> $$6 = $$1.b(rp.e);
      jm<ebq<?, ?>> $$7 = $$1.b(rp.f);
      jm<ebq<?, ?>> $$8 = $$1.b(rp.g);
      jm<ebq<?, ?>> $$9 = $$1.b(rp.h);
      jm<ebq<?, ?>> $$10 = $$1.b(rp.i);
      jm<ebq<?, ?>> $$11 = $$1.b(rp.j);
      jm<ebq<?, ?>> $$12 = $$1.b(rp.m);
      jm<ebq<?, ?>> $$13 = $$1.b(rp.r);
      jm<ebq<?, ?>> $$14 = $$1.b(rp.s);
      jm<ebq<?, ?>> $$15 = $$1.b(rp.t);
      jm<ebq<?, ?>> $$16 = $$1.b(rx.c);
      jm<ebq<?, ?>> $$17 = $$1.b(rp.u);
      jm<ebq<?, ?>> $$18 = $$1.b(rp.v);
      jm<ebq<?, ?>> $$19 = $$1.b(rp.w);
      jm<ebq<?, ?>> $$20 = $$1.b(rp.x);
      sg.a($$0, a, $$2, eim.a(10), eiq.a(), eio.a(dzs.a(0), dzs.b()), eih.a());
      sg.a($$0, b, $$2, eim.a(4), eiq.a(), eio.a(dzs.b(6), dzs.a(-1)), eih.a());
      sg.a($$0, c, $$3, eiz.a(64), eiq.a(), eio.a(dzs.a(0), dzs.b()), eih.a());
      sg.a($$0, d, $$4, eiz.a(64), eiq.a(), eio.a(dzs.a(), dzs.a(-8)), eih.a());
      sg.a($$0, e, $$5, eim.a(bqc.a(48, 96)), eiq.a(), sg.i, eih.a());
      sg.a($$0, f, $$6, eim.a(bqc.a(10, 48)), eiq.a(), sg.i, eih.a());
      sg.a($$0, g, $$7, eim.a(bqc.a(192, 256)), eiq.a(), sg.i, eim.a(bqc.a(1, 5)), eiy.a(bpr.a(0.0F, 3.0F, -10, 10), bpr.a(0.0F, 0.6F, -2, 2)), eih.a());
      sg.a($$0, h, $$8, eim.a(bqc.a(44, 52)), eiq.a(), sg.i, ejb.a(dyy.a.c, Integer.MIN_VALUE, -2), eih.a());
      sg.a($$0, i, $$9, eim.a(bqc.a(104, 157)), sg.i, eiq.a(), ejb.a(dyy.a.c, Integer.MIN_VALUE, -13), eih.a());
      sg.a($$0, j, $$10, eim.a(bqc.a(1, 2)), eiq.a(), sg.i, ein.a(ji.b, eaf.c(), eaf.c, 12), eiy.a(bpt.a(-1)), eih.a());
      sg.a($$0, k, $$11, eim.a(188), eiq.a(), sg.i, ein.a(ji.b, eaf.a(ji.a), eaf.c, 12), eiy.a(bpt.a(-1)), eih.a());
      sg.a($$0, l, $$12, eim.a(125), eiq.a(), sg.i, ein.a(ji.a, eaf.c(), eaf.c, 12), eiy.a(bpt.a(1)), eih.a());
      sg.a($$0, m, $$13, eim.a(62), eiq.a(), sg.i, ein.a(ji.a, eaf.c(), eaf.c, 12), eiy.a(bpt.a(1)), eih.a());
      sg.a($$0, n, $$14, eim.a(125), eiq.a(), sg.i, ein.a(ji.b, eaf.c(), eaf.c, 12), eiy.a(bpt.a(-1)), eih.a());
      sg.a($$0, o, $$15, eim.a(25), eiq.a(), sg.i, ein.a(ji.b, eaf.c(), eaf.c, 12), eiy.a(bpt.a(-1)), eih.a());
      sg.a($$0, p, $$16, eim.a(256), eiq.a(), sg.i, eih.a());
      sg.a($$0, q, $$17, eiz.a(24), eiq.a(), eio.a(dzs.b(6), dzs.a(30)), eih.a());
      sg.a($$0, r, $$18, eim.a(bpt.a(256)), eiq.a(), sg.i, eih.a());
      sg.a($$0, s, $$19);
      sg.a($$0, t, $$20, eim.a(bqc.a(204, 250)), eiq.a(), sg.i, eih.a());
   }
}
