import java.util.List;

public class sd {
   public static final akj<eib> a = sc.a("crimson_fungi");
   public static final akj<eib> b = sc.a("warped_fungi");
   public static final akj<eib> c = sc.a("oak_checked");
   public static final akj<eib> d = sc.a("dark_oak_checked");
   public static final akj<eib> e = sc.a("birch_checked");
   public static final akj<eib> f = sc.a("acacia_checked");
   public static final akj<eib> g = sc.a("spruce_checked");
   public static final akj<eib> h = sc.a("mangrove_checked");
   public static final akj<eib> i = sc.a("cherry_checked");
   public static final akj<eib> j = sc.a("pine_on_snow");
   public static final akj<eib> k = sc.a("spruce_on_snow");
   public static final akj<eib> l = sc.a("pine_checked");
   public static final akj<eib> m = sc.a("jungle_tree");
   public static final akj<eib> n = sc.a("fancy_oak_checked");
   public static final akj<eib> o = sc.a("mega_jungle_tree_checked");
   public static final akj<eib> p = sc.a("mega_spruce_checked");
   public static final akj<eib> q = sc.a("mega_pine_checked");
   public static final akj<eib> r = sc.a("tall_mangrove_checked");
   public static final akj<eib> s = sc.a("jungle_bush");
   public static final akj<eib> t = sc.a("super_birch_bees_0002");
   public static final akj<eib> u = sc.a("super_birch_bees");
   public static final akj<eib> v = sc.a("oak_bees_0002");
   public static final akj<eib> w = sc.a("oak_bees_002");
   public static final akj<eib> x = sc.a("birch_bees_0002");
   public static final akj<eib> y = sc.a("birch_bees_002");
   public static final akj<eib> z = sc.a("fancy_oak_bees_0002");
   public static final akj<eib> A = sc.a("fancy_oak_bees_002");
   public static final akj<eib> B = sc.a("fancy_oak_bees");
   public static final akj<eib> C = sc.a("cherry_bees_005");

   public static void a(qm<eib> $$0) {
      jk<eay<?, ?>> $$1 = $$0.a(lr.aH);
      jj<eay<?, ?>> $$2 = $$1.b(rs.a);
      jj<eay<?, ?>> $$3 = $$1.b(rs.c);
      jj<eay<?, ?>> $$4 = $$1.b(rs.g);
      jj<eay<?, ?>> $$5 = $$1.b(rs.h);
      jj<eay<?, ?>> $$6 = $$1.b(rs.i);
      jj<eay<?, ?>> $$7 = $$1.b(rs.j);
      jj<eay<?, ?>> $$8 = $$1.b(rs.k);
      jj<eay<?, ?>> $$9 = $$1.b(rs.x);
      jj<eay<?, ?>> $$10 = $$1.b(rs.z);
      jj<eay<?, ?>> $$11 = $$1.b(rs.l);
      jj<eay<?, ?>> $$12 = $$1.b(rs.m);
      jj<eay<?, ?>> $$13 = $$1.b(rs.n);
      jj<eay<?, ?>> $$14 = $$1.b(rs.p);
      jj<eay<?, ?>> $$15 = $$1.b(rs.q);
      jj<eay<?, ?>> $$16 = $$1.b(rs.r);
      jj<eay<?, ?>> $$17 = $$1.b(rs.y);
      jj<eay<?, ?>> $$18 = $$1.b(rs.v);
      jj<eay<?, ?>> $$19 = $$1.b(rs.s);
      jj<eay<?, ?>> $$20 = $$1.b(rs.t);
      jj<eay<?, ?>> $$21 = $$1.b(rs.A);
      jj<eay<?, ?>> $$22 = $$1.b(rs.B);
      jj<eay<?, ?>> $$23 = $$1.b(rs.D);
      jj<eay<?, ?>> $$24 = $$1.b(rs.E);
      jj<eay<?, ?>> $$25 = $$1.b(rs.G);
      jj<eay<?, ?>> $$26 = $$1.b(rs.H);
      jj<eay<?, ?>> $$27 = $$1.b(rs.J);
      jj<eay<?, ?>> $$28 = $$1.b(rs.K);
      sc.a($$0, a, $$2, eht.a(8), ehp.a());
      sc.a($$0, b, $$3, eht.a(8), ehp.a());
      sc.a($$0, c, $$4, sc.a(dfk.x));
      sc.a($$0, d, $$5, sc.a(dfk.D));
      sc.a($$0, e, $$6, sc.a(dfk.z));
      sc.a($$0, f, $$7, sc.a(dfk.B));
      sc.a($$0, g, $$8, sc.a(dfk.y));
      sc.a($$0, h, $$9, sc.a(dfk.E));
      sc.a($$0, i, $$10, sc.a(dfk.C));
      dzn $$29 = dzn.a(jf.a.q(), dfk.dP, dfk.qP);
      List<eie> $$30 = List.of(ehv.a(jf.b, dzn.a(dzn.a(dfk.qP)), 8), ehq.a($$29));
      sc.a($$0, j, $$11, $$30);
      sc.a($$0, k, $$8, $$30);
      sc.a($$0, l, $$11, sc.a(dfk.y));
      sc.a($$0, m, $$12, sc.a(dfk.A));
      sc.a($$0, n, $$13, sc.a(dfk.x));
      sc.a($$0, o, $$14, sc.a(dfk.A));
      sc.a($$0, p, $$15, sc.a(dfk.y));
      sc.a($$0, q, $$16, sc.a(dfk.y));
      sc.a($$0, r, $$17, sc.a(dfk.E));
      sc.a($$0, s, $$18, sc.a(dfk.x));
      sc.a($$0, t, $$19, sc.a(dfk.z));
      sc.a($$0, u, $$20, sc.a(dfk.z));
      sc.a($$0, v, $$21, sc.a(dfk.x));
      sc.a($$0, w, $$22, sc.a(dfk.x));
      sc.a($$0, x, $$23, sc.a(dfk.z));
      sc.a($$0, y, $$24, sc.a(dfk.z));
      sc.a($$0, z, $$25, sc.a(dfk.x));
      sc.a($$0, A, $$26, sc.a(dfk.x));
      sc.a($$0, B, $$27, sc.a(dfk.x));
      sc.a($$0, C, $$28, sc.a(dfk.C));
   }
}
