import java.util.List;

public class sd {
   public static final akj<eia> a = sc.a("crimson_fungi");
   public static final akj<eia> b = sc.a("warped_fungi");
   public static final akj<eia> c = sc.a("oak_checked");
   public static final akj<eia> d = sc.a("dark_oak_checked");
   public static final akj<eia> e = sc.a("birch_checked");
   public static final akj<eia> f = sc.a("acacia_checked");
   public static final akj<eia> g = sc.a("spruce_checked");
   public static final akj<eia> h = sc.a("mangrove_checked");
   public static final akj<eia> i = sc.a("cherry_checked");
   public static final akj<eia> j = sc.a("pine_on_snow");
   public static final akj<eia> k = sc.a("spruce_on_snow");
   public static final akj<eia> l = sc.a("pine_checked");
   public static final akj<eia> m = sc.a("jungle_tree");
   public static final akj<eia> n = sc.a("fancy_oak_checked");
   public static final akj<eia> o = sc.a("mega_jungle_tree_checked");
   public static final akj<eia> p = sc.a("mega_spruce_checked");
   public static final akj<eia> q = sc.a("mega_pine_checked");
   public static final akj<eia> r = sc.a("tall_mangrove_checked");
   public static final akj<eia> s = sc.a("jungle_bush");
   public static final akj<eia> t = sc.a("super_birch_bees_0002");
   public static final akj<eia> u = sc.a("super_birch_bees");
   public static final akj<eia> v = sc.a("oak_bees_0002");
   public static final akj<eia> w = sc.a("oak_bees_002");
   public static final akj<eia> x = sc.a("birch_bees_0002");
   public static final akj<eia> y = sc.a("birch_bees_002");
   public static final akj<eia> z = sc.a("fancy_oak_bees_0002");
   public static final akj<eia> A = sc.a("fancy_oak_bees_002");
   public static final akj<eia> B = sc.a("fancy_oak_bees");
   public static final akj<eia> C = sc.a("cherry_bees_005");

   public static void a(qm<eia> $$0) {
      jk<eax<?, ?>> $$1 = $$0.a(lr.aH);
      jj<eax<?, ?>> $$2 = $$1.b(rs.a);
      jj<eax<?, ?>> $$3 = $$1.b(rs.c);
      jj<eax<?, ?>> $$4 = $$1.b(rs.g);
      jj<eax<?, ?>> $$5 = $$1.b(rs.h);
      jj<eax<?, ?>> $$6 = $$1.b(rs.i);
      jj<eax<?, ?>> $$7 = $$1.b(rs.j);
      jj<eax<?, ?>> $$8 = $$1.b(rs.k);
      jj<eax<?, ?>> $$9 = $$1.b(rs.x);
      jj<eax<?, ?>> $$10 = $$1.b(rs.z);
      jj<eax<?, ?>> $$11 = $$1.b(rs.l);
      jj<eax<?, ?>> $$12 = $$1.b(rs.m);
      jj<eax<?, ?>> $$13 = $$1.b(rs.n);
      jj<eax<?, ?>> $$14 = $$1.b(rs.p);
      jj<eax<?, ?>> $$15 = $$1.b(rs.q);
      jj<eax<?, ?>> $$16 = $$1.b(rs.r);
      jj<eax<?, ?>> $$17 = $$1.b(rs.y);
      jj<eax<?, ?>> $$18 = $$1.b(rs.v);
      jj<eax<?, ?>> $$19 = $$1.b(rs.s);
      jj<eax<?, ?>> $$20 = $$1.b(rs.t);
      jj<eax<?, ?>> $$21 = $$1.b(rs.A);
      jj<eax<?, ?>> $$22 = $$1.b(rs.B);
      jj<eax<?, ?>> $$23 = $$1.b(rs.D);
      jj<eax<?, ?>> $$24 = $$1.b(rs.E);
      jj<eax<?, ?>> $$25 = $$1.b(rs.G);
      jj<eax<?, ?>> $$26 = $$1.b(rs.H);
      jj<eax<?, ?>> $$27 = $$1.b(rs.J);
      jj<eax<?, ?>> $$28 = $$1.b(rs.K);
      sc.a($$0, a, $$2, ehs.a(8), eho.a());
      sc.a($$0, b, $$3, ehs.a(8), eho.a());
      sc.a($$0, c, $$4, sc.a(dfj.x));
      sc.a($$0, d, $$5, sc.a(dfj.D));
      sc.a($$0, e, $$6, sc.a(dfj.z));
      sc.a($$0, f, $$7, sc.a(dfj.B));
      sc.a($$0, g, $$8, sc.a(dfj.y));
      sc.a($$0, h, $$9, sc.a(dfj.E));
      sc.a($$0, i, $$10, sc.a(dfj.C));
      dzm $$29 = dzm.a(jf.a.q(), dfj.dP, dfj.qP);
      List<eid> $$30 = List.of(ehu.a(jf.b, dzm.a(dzm.a(dfj.qP)), 8), ehp.a($$29));
      sc.a($$0, j, $$11, $$30);
      sc.a($$0, k, $$8, $$30);
      sc.a($$0, l, $$11, sc.a(dfj.y));
      sc.a($$0, m, $$12, sc.a(dfj.A));
      sc.a($$0, n, $$13, sc.a(dfj.x));
      sc.a($$0, o, $$14, sc.a(dfj.A));
      sc.a($$0, p, $$15, sc.a(dfj.y));
      sc.a($$0, q, $$16, sc.a(dfj.y));
      sc.a($$0, r, $$17, sc.a(dfj.E));
      sc.a($$0, s, $$18, sc.a(dfj.x));
      sc.a($$0, t, $$19, sc.a(dfj.z));
      sc.a($$0, u, $$20, sc.a(dfj.z));
      sc.a($$0, v, $$21, sc.a(dfj.x));
      sc.a($$0, w, $$22, sc.a(dfj.x));
      sc.a($$0, x, $$23, sc.a(dfj.z));
      sc.a($$0, y, $$24, sc.a(dfj.z));
      sc.a($$0, z, $$25, sc.a(dfj.x));
      sc.a($$0, A, $$26, sc.a(dfj.x));
      sc.a($$0, B, $$27, sc.a(dfj.x));
      sc.a($$0, C, $$28, sc.a(dfj.C));
   }
}
