import java.util.List;

public class sf {
   public static final alk<eeb<?, ?>> a = sc.a("ore_magma");
   public static final alk<eeb<?, ?>> b = sc.a("ore_soul_sand");
   public static final alk<eeb<?, ?>> c = sc.a("ore_nether_gold");
   public static final alk<eeb<?, ?>> d = sc.a("ore_quartz");
   public static final alk<eeb<?, ?>> e = sc.a("ore_gravel_nether");
   public static final alk<eeb<?, ?>> f = sc.a("ore_blackstone");
   public static final alk<eeb<?, ?>> g = sc.a("ore_dirt");
   public static final alk<eeb<?, ?>> h = sc.a("ore_gravel");
   public static final alk<eeb<?, ?>> i = sc.a("ore_granite");
   public static final alk<eeb<?, ?>> j = sc.a("ore_diorite");
   public static final alk<eeb<?, ?>> k = sc.a("ore_andesite");
   public static final alk<eeb<?, ?>> l = sc.a("ore_tuff");
   public static final alk<eeb<?, ?>> m = sc.a("ore_coal");
   public static final alk<eeb<?, ?>> n = sc.a("ore_coal_buried");
   public static final alk<eeb<?, ?>> o = sc.a("ore_iron");
   public static final alk<eeb<?, ?>> p = sc.a("ore_iron_small");
   public static final alk<eeb<?, ?>> q = sc.a("ore_gold");
   public static final alk<eeb<?, ?>> r = sc.a("ore_gold_buried");
   public static final alk<eeb<?, ?>> s = sc.a("ore_redstone");
   public static final alk<eeb<?, ?>> t = sc.a("ore_diamond_small");
   public static final alk<eeb<?, ?>> u = sc.a("ore_diamond_medium");
   public static final alk<eeb<?, ?>> v = sc.a("ore_diamond_large");
   public static final alk<eeb<?, ?>> w = sc.a("ore_diamond_buried");
   public static final alk<eeb<?, ?>> x = sc.a("ore_lapis");
   public static final alk<eeb<?, ?>> y = sc.a("ore_lapis_buried");
   public static final alk<eeb<?, ?>> z = sc.a("ore_infested");
   public static final alk<eeb<?, ?>> A = sc.a("ore_emerald");
   public static final alk<eeb<?, ?>> B = sc.a("ore_ancient_debris_large");
   public static final alk<eeb<?, ?>> C = sc.a("ore_ancient_debris_small");
   public static final alk<eeb<?, ?>> D = sc.a("ore_copper_small");
   public static final alk<eeb<?, ?>> E = sc.a("ore_copper_large");
   public static final alk<eeb<?, ?>> F = sc.a("ore_clay");

   public static void a(rb<eeb<?, ?>> $$0) {
      epx $$1 = new eqf(axd.bf);
      epx $$2 = new eqf(axd.bg);
      epx $$3 = new eqf(axd.bh);
      epx $$4 = new epf(dil.dV);
      epx $$5 = new eqf(axd.bi);
      List<ehb.a> $$6 = List.of(ehb.a($$2, dil.P.m()), ehb.a($$3, dil.Q.m()));
      List<ehb.a> $$7 = List.of(ehb.a($$2, dil.N.m()), ehb.a($$3, dil.O.m()));
      List<ehb.a> $$8 = List.of(ehb.a($$2, dil.cx.m()), ehb.a($$3, dil.cy.m()));
      List<ehb.a> $$9 = List.of(ehb.a($$2, dil.aR.m()), ehb.a($$3, dil.aS.m()));
      List<ehb.a> $$10 = List.of(ehb.a($$2, dil.ra.m()), ehb.a($$3, dil.rb.m()));
      List<ehb.a> $$11 = List.of(ehb.a($$2, dil.R.m()), ehb.a($$3, dil.S.m()));
      sc.a($$0, a, eep.I, new ehb($$4, dil.kJ.m(), 33));
      sc.a($$0, b, eep.I, new ehb($$4, dil.dW.m(), 12));
      sc.a($$0, c, eep.I, new ehb($$4, dil.T.m(), 10));
      sc.a($$0, d, eep.I, new ehb($$4, dil.hb.m(), 14));
      sc.a($$0, e, eep.I, new ehb($$4, dil.L.m(), 33));
      sc.a($$0, f, eep.I, new ehb($$4, dil.pr.m(), 33));
      sc.a($$0, g, eep.I, new ehb($$1, dil.j.m(), 33));
      sc.a($$0, h, eep.I, new ehb($$1, dil.L.m(), 33));
      sc.a($$0, i, eep.I, new ehb($$1, dil.c.m(), 64));
      sc.a($$0, j, eep.I, new ehb($$1, dil.e.m(), 64));
      sc.a($$0, k, eep.I, new ehb($$1, dil.g.m(), 64));
      sc.a($$0, l, eep.I, new ehb($$1, dil.qz.m(), 64));
      sc.a($$0, m, eep.I, new ehb($$11, 17));
      sc.a($$0, n, eep.I, new ehb($$11, 17, 0.5F));
      sc.a($$0, o, eep.I, new ehb($$6, 9));
      sc.a($$0, p, eep.I, new ehb($$6, 4));
      sc.a($$0, q, eep.I, new ehb($$7, 9));
      sc.a($$0, r, eep.I, new ehb($$7, 9, 0.5F));
      sc.a($$0, s, eep.I, new ehb(List.of(ehb.a($$2, dil.dI.m()), ehb.a($$3, dil.dJ.m())), 8));
      sc.a($$0, t, eep.I, new ehb($$8, 4, 0.5F));
      sc.a($$0, v, eep.I, new ehb($$8, 12, 0.7F));
      sc.a($$0, w, eep.I, new ehb($$8, 8, 1.0F));
      sc.a($$0, u, eep.I, new ehb($$8, 8, 0.5F));
      sc.a($$0, x, eep.I, new ehb($$9, 7));
      sc.a($$0, y, eep.I, new ehb($$9, 7, 1.0F));
      sc.a($$0, z, eep.I, new ehb(List.of(ehb.a($$2, dil.eN.m()), ehb.a($$3, dil.td.m())), 9));
      sc.a($$0, A, eep.I, new ehb(List.of(ehb.a($$2, dil.fE.m()), ehb.a($$3, dil.fF.m())), 3));
      sc.a($$0, B, eep.af, new ehb($$5, dil.pj.m(), 3, 1.0F));
      sc.a($$0, C, eep.af, new ehb($$5, dil.pj.m(), 2, 1.0F));
      sc.a($$0, D, eep.I, new ehb($$10, 10));
      sc.a($$0, E, eep.I, new ehb($$10, 20));
      sc.a($$0, F, eep.I, new ehb($$1, dil.dR.m(), 33));
   }
}
