import java.util.List;

public class sh {
   public static final akq<eit> a = sg.a("crimson_fungi");
   public static final akq<eit> b = sg.a("warped_fungi");
   public static final akq<eit> c = sg.a("oak_checked");
   public static final akq<eit> d = sg.a("dark_oak_checked");
   public static final akq<eit> e = sg.a("birch_checked");
   public static final akq<eit> f = sg.a("acacia_checked");
   public static final akq<eit> g = sg.a("spruce_checked");
   public static final akq<eit> h = sg.a("mangrove_checked");
   public static final akq<eit> i = sg.a("cherry_checked");
   public static final akq<eit> j = sg.a("pine_on_snow");
   public static final akq<eit> k = sg.a("spruce_on_snow");
   public static final akq<eit> l = sg.a("pine_checked");
   public static final akq<eit> m = sg.a("jungle_tree");
   public static final akq<eit> n = sg.a("fancy_oak_checked");
   public static final akq<eit> o = sg.a("mega_jungle_tree_checked");
   public static final akq<eit> p = sg.a("mega_spruce_checked");
   public static final akq<eit> q = sg.a("mega_pine_checked");
   public static final akq<eit> r = sg.a("tall_mangrove_checked");
   public static final akq<eit> s = sg.a("jungle_bush");
   public static final akq<eit> t = sg.a("super_birch_bees_0002");
   public static final akq<eit> u = sg.a("super_birch_bees");
   public static final akq<eit> v = sg.a("oak_bees_0002");
   public static final akq<eit> w = sg.a("oak_bees_002");
   public static final akq<eit> x = sg.a("birch_bees_0002");
   public static final akq<eit> y = sg.a("birch_bees_002");
   public static final akq<eit> z = sg.a("fancy_oak_bees_0002");
   public static final akq<eit> A = sg.a("fancy_oak_bees_002");
   public static final akq<eit> B = sg.a("fancy_oak_bees");
   public static final akq<eit> C = sg.a("cherry_bees_005");

   public static void a(qq<eit> $$0) {
      jn<ebq<?, ?>> $$1 = $$0.a(lu.aI);
      jm<ebq<?, ?>> $$2 = $$1.b(rw.a);
      jm<ebq<?, ?>> $$3 = $$1.b(rw.c);
      jm<ebq<?, ?>> $$4 = $$1.b(rw.g);
      jm<ebq<?, ?>> $$5 = $$1.b(rw.h);
      jm<ebq<?, ?>> $$6 = $$1.b(rw.i);
      jm<ebq<?, ?>> $$7 = $$1.b(rw.j);
      jm<ebq<?, ?>> $$8 = $$1.b(rw.k);
      jm<ebq<?, ?>> $$9 = $$1.b(rw.x);
      jm<ebq<?, ?>> $$10 = $$1.b(rw.z);
      jm<ebq<?, ?>> $$11 = $$1.b(rw.l);
      jm<ebq<?, ?>> $$12 = $$1.b(rw.m);
      jm<ebq<?, ?>> $$13 = $$1.b(rw.n);
      jm<ebq<?, ?>> $$14 = $$1.b(rw.p);
      jm<ebq<?, ?>> $$15 = $$1.b(rw.q);
      jm<ebq<?, ?>> $$16 = $$1.b(rw.r);
      jm<ebq<?, ?>> $$17 = $$1.b(rw.y);
      jm<ebq<?, ?>> $$18 = $$1.b(rw.v);
      jm<ebq<?, ?>> $$19 = $$1.b(rw.s);
      jm<ebq<?, ?>> $$20 = $$1.b(rw.t);
      jm<ebq<?, ?>> $$21 = $$1.b(rw.A);
      jm<ebq<?, ?>> $$22 = $$1.b(rw.B);
      jm<ebq<?, ?>> $$23 = $$1.b(rw.D);
      jm<ebq<?, ?>> $$24 = $$1.b(rw.E);
      jm<ebq<?, ?>> $$25 = $$1.b(rw.G);
      jm<ebq<?, ?>> $$26 = $$1.b(rw.H);
      jm<ebq<?, ?>> $$27 = $$1.b(rw.J);
      jm<ebq<?, ?>> $$28 = $$1.b(rw.K);
      sg.a($$0, a, $$2, eil.a(8), eih.a());
      sg.a($$0, b, $$3, eil.a(8), eih.a());
      sg.a($$0, c, $$4, sg.a(dga.x));
      sg.a($$0, d, $$5, sg.a(dga.D));
      sg.a($$0, e, $$6, sg.a(dga.z));
      sg.a($$0, f, $$7, sg.a(dga.B));
      sg.a($$0, g, $$8, sg.a(dga.y));
      sg.a($$0, h, $$9, sg.a(dga.E));
      sg.a($$0, i, $$10, sg.a(dga.C));
      eaf $$29 = eaf.a(ji.a.q(), dga.dP, dga.qP);
      List<eiw> $$30 = List.of(ein.a(ji.b, eaf.a(eaf.a(dga.qP)), 8), eii.a($$29));
      sg.a($$0, j, $$11, $$30);
      sg.a($$0, k, $$8, $$30);
      sg.a($$0, l, $$11, sg.a(dga.y));
      sg.a($$0, m, $$12, sg.a(dga.A));
      sg.a($$0, n, $$13, sg.a(dga.x));
      sg.a($$0, o, $$14, sg.a(dga.A));
      sg.a($$0, p, $$15, sg.a(dga.y));
      sg.a($$0, q, $$16, sg.a(dga.y));
      sg.a($$0, r, $$17, sg.a(dga.E));
      sg.a($$0, s, $$18, sg.a(dga.x));
      sg.a($$0, t, $$19, sg.a(dga.z));
      sg.a($$0, u, $$20, sg.a(dga.z));
      sg.a($$0, v, $$21, sg.a(dga.x));
      sg.a($$0, w, $$22, sg.a(dga.x));
      sg.a($$0, x, $$23, sg.a(dga.z));
      sg.a($$0, y, $$24, sg.a(dga.z));
      sg.a($$0, z, $$25, sg.a(dga.x));
      sg.a($$0, A, $$26, sg.a(dga.x));
      sg.a($$0, B, $$27, sg.a(dga.x));
      sg.a($$0, C, $$28, sg.a(dga.C));
   }
}
