public class si {
   public static final alg<ekv> a = sn.a("monster_room");
   public static final alg<ekv> b = sn.a("monster_room_deep");
   public static final alg<ekv> c = sn.a("fossil_upper");
   public static final alg<ekv> d = sn.a("fossil_lower");
   public static final alg<ekv> e = sn.a("dripstone_cluster");
   public static final alg<ekv> f = sn.a("large_dripstone");
   public static final alg<ekv> g = sn.a("pointed_dripstone");
   public static final alg<ekv> h = sn.a("underwater_magma");
   public static final alg<ekv> i = sn.a("glow_lichen");
   public static final alg<ekv> j = sn.a("rooted_azalea_tree");
   public static final alg<ekv> k = sn.a("cave_vines");
   public static final alg<ekv> l = sn.a("lush_caves_vegetation");
   public static final alg<ekv> m = sn.a("lush_caves_clay");
   public static final alg<ekv> n = sn.a("lush_caves_ceiling_vegetation");
   public static final alg<ekv> o = sn.a("spore_blossom");
   public static final alg<ekv> p = sn.a("classic_vines_cave_feature");
   public static final alg<ekv> q = sn.a("amethyst_geode");
   public static final alg<ekv> r = sn.a("sculk_patch_deep_dark");
   public static final alg<ekv> s = sn.a("sculk_patch_ancient_city");
   public static final alg<ekv> t = sn.a("sculk_vein");

   public static void a(qx<ekv> $$0) {
      jq<edr<?, ?>> $$1 = $$0.a(ly.aJ);
      jp<edr<?, ?>> $$2 = $$1.b(rw.a);
      jp<edr<?, ?>> $$3 = $$1.b(rw.b);
      jp<edr<?, ?>> $$4 = $$1.b(rw.c);
      jp<edr<?, ?>> $$5 = $$1.b(rw.d);
      jp<edr<?, ?>> $$6 = $$1.b(rw.e);
      jp<edr<?, ?>> $$7 = $$1.b(rw.f);
      jp<edr<?, ?>> $$8 = $$1.b(rw.g);
      jp<edr<?, ?>> $$9 = $$1.b(rw.h);
      jp<edr<?, ?>> $$10 = $$1.b(rw.i);
      jp<edr<?, ?>> $$11 = $$1.b(rw.j);
      jp<edr<?, ?>> $$12 = $$1.b(rw.m);
      jp<edr<?, ?>> $$13 = $$1.b(rw.r);
      jp<edr<?, ?>> $$14 = $$1.b(rw.s);
      jp<edr<?, ?>> $$15 = $$1.b(rw.t);
      jp<edr<?, ?>> $$16 = $$1.b(se.c);
      jp<edr<?, ?>> $$17 = $$1.b(rw.u);
      jp<edr<?, ?>> $$18 = $$1.b(rw.v);
      jp<edr<?, ?>> $$19 = $$1.b(rw.w);
      jp<edr<?, ?>> $$20 = $$1.b(rw.x);
      sn.a($$0, a, $$2, ekn.a(10), eks.a(), ekq.a(ebt.a(0), ebt.b()), ekj.a());
      sn.a($$0, b, $$2, ekn.a(4), eks.a(), ekq.a(ebt.b(6), ebt.a(-1)), ekj.a());
      sn.a($$0, c, $$3, elb.a(64), eks.a(), ekq.a(ebt.a(0), ebt.b()), ekj.a());
      sn.a($$0, d, $$4, elb.a(64), eks.a(), ekq.a(ebt.a(), ebt.a(-8)), ekj.a());
      sn.a($$0, e, $$5, ekn.a(brj.a(48, 96)), eks.a(), sn.i, ekj.a());
      sn.a($$0, f, $$6, ekn.a(brj.a(10, 48)), eks.a(), sn.i, ekj.a());
      sn.a($$0, g, $$7, ekn.a(brj.a(192, 256)), eks.a(), sn.i, ekn.a(brj.a(1, 5)), ela.a(bqy.a(0.0F, 3.0F, -10, 10), bqy.a(0.0F, 0.6F, -2, 2)), ekj.a());
      sn.a($$0, h, $$8, ekn.a(brj.a(44, 52)), eks.a(), sn.i, eld.a(eaz.a.c, Integer.MIN_VALUE, -2), ekj.a());
      sn.a($$0, i, $$9, ekn.a(brj.a(104, 157)), sn.i, eks.a(), eld.a(eaz.a.c, Integer.MIN_VALUE, -13), ekj.a());
      sn.a($$0, j, $$10, ekn.a(brj.a(1, 2)), eks.a(), sn.i, eko.a(jl.b, ecg.c(), ecg.c, 12), ela.a(bra.a(-1)), ekj.a());
      sn.a($$0, k, $$11, ekn.a(188), eks.a(), sn.i, eko.a(jl.b, ecg.a(jl.a), ecg.c, 12), ela.a(bra.a(-1)), ekj.a());
      sn.a($$0, l, $$12, ekn.a(125), eks.a(), sn.i, eko.a(jl.a, ecg.c(), ecg.c, 12), ela.a(bra.a(1)), ekj.a());
      sn.a($$0, m, $$13, ekn.a(62), eks.a(), sn.i, eko.a(jl.a, ecg.c(), ecg.c, 12), ela.a(bra.a(1)), ekj.a());
      sn.a($$0, n, $$14, ekn.a(125), eks.a(), sn.i, eko.a(jl.b, ecg.c(), ecg.c, 12), ela.a(bra.a(-1)), ekj.a());
      sn.a($$0, o, $$15, ekn.a(25), eks.a(), sn.i, eko.a(jl.b, ecg.c(), ecg.c, 12), ela.a(bra.a(-1)), ekj.a());
      sn.a($$0, p, $$16, ekn.a(256), eks.a(), sn.i, ekj.a());
      sn.a($$0, q, $$17, elb.a(24), eks.a(), ekq.a(ebt.b(6), ebt.a(30)), ekj.a());
      sn.a($$0, r, $$18, ekn.a(bra.a(256)), eks.a(), sn.i, ekj.a());
      sn.a($$0, s, $$19);
      sn.a($$0, t, $$20, ekn.a(brj.a(204, 250)), eks.a(), sn.i, ekj.a());
   }
}
