import java.util.List;

public class sk {
   public static final ald<eak<?, ?>> a = sh.a("ore_magma");
   public static final ald<eak<?, ?>> b = sh.a("ore_soul_sand");
   public static final ald<eak<?, ?>> c = sh.a("ore_nether_gold");
   public static final ald<eak<?, ?>> d = sh.a("ore_quartz");
   public static final ald<eak<?, ?>> e = sh.a("ore_gravel_nether");
   public static final ald<eak<?, ?>> f = sh.a("ore_blackstone");
   public static final ald<eak<?, ?>> g = sh.a("ore_dirt");
   public static final ald<eak<?, ?>> h = sh.a("ore_gravel");
   public static final ald<eak<?, ?>> i = sh.a("ore_granite");
   public static final ald<eak<?, ?>> j = sh.a("ore_diorite");
   public static final ald<eak<?, ?>> k = sh.a("ore_andesite");
   public static final ald<eak<?, ?>> l = sh.a("ore_tuff");
   public static final ald<eak<?, ?>> m = sh.a("ore_coal");
   public static final ald<eak<?, ?>> n = sh.a("ore_coal_buried");
   public static final ald<eak<?, ?>> o = sh.a("ore_iron");
   public static final ald<eak<?, ?>> p = sh.a("ore_iron_small");
   public static final ald<eak<?, ?>> q = sh.a("ore_gold");
   public static final ald<eak<?, ?>> r = sh.a("ore_gold_buried");
   public static final ald<eak<?, ?>> s = sh.a("ore_redstone");
   public static final ald<eak<?, ?>> t = sh.a("ore_diamond_small");
   public static final ald<eak<?, ?>> u = sh.a("ore_diamond_medium");
   public static final ald<eak<?, ?>> v = sh.a("ore_diamond_large");
   public static final ald<eak<?, ?>> w = sh.a("ore_diamond_buried");
   public static final ald<eak<?, ?>> x = sh.a("ore_lapis");
   public static final ald<eak<?, ?>> y = sh.a("ore_lapis_buried");
   public static final ald<eak<?, ?>> z = sh.a("ore_infested");
   public static final ald<eak<?, ?>> A = sh.a("ore_emerald");
   public static final ald<eak<?, ?>> B = sh.a("ore_ancient_debris_large");
   public static final ald<eak<?, ?>> C = sh.a("ore_ancient_debris_small");
   public static final ald<eak<?, ?>> D = sh.a("ore_copper_small");
   public static final ald<eak<?, ?>> E = sh.a("ore_copper_large");
   public static final ald<eak<?, ?>> F = sh.a("ore_clay");

   public static void a(rc<eak<?, ?>> $$0) {
      emd $$1 = new eml(awo.be);
      emd $$2 = new eml(awo.bf);
      emd $$3 = new eml(awo.bg);
      emd $$4 = new elm(dfa.dV);
      emd $$5 = new eml(awo.bh);
      List<edj.a> $$6 = List.of(edj.a($$2, dfa.P.o()), edj.a($$3, dfa.Q.o()));
      List<edj.a> $$7 = List.of(edj.a($$2, dfa.N.o()), edj.a($$3, dfa.O.o()));
      List<edj.a> $$8 = List.of(edj.a($$2, dfa.cx.o()), edj.a($$3, dfa.cy.o()));
      List<edj.a> $$9 = List.of(edj.a($$2, dfa.aR.o()), edj.a($$3, dfa.aS.o()));
      List<edj.a> $$10 = List.of(edj.a($$2, dfa.ra.o()), edj.a($$3, dfa.rb.o()));
      List<edj.a> $$11 = List.of(edj.a($$2, dfa.R.o()), edj.a($$3, dfa.S.o()));
      sh.a($$0, a, eax.I, new edj($$4, dfa.kJ.o(), 33));
      sh.a($$0, b, eax.I, new edj($$4, dfa.dW.o(), 12));
      sh.a($$0, c, eax.I, new edj($$4, dfa.T.o(), 10));
      sh.a($$0, d, eax.I, new edj($$4, dfa.hb.o(), 14));
      sh.a($$0, e, eax.I, new edj($$4, dfa.L.o(), 33));
      sh.a($$0, f, eax.I, new edj($$4, dfa.pr.o(), 33));
      sh.a($$0, g, eax.I, new edj($$1, dfa.j.o(), 33));
      sh.a($$0, h, eax.I, new edj($$1, dfa.L.o(), 33));
      sh.a($$0, i, eax.I, new edj($$1, dfa.c.o(), 64));
      sh.a($$0, j, eax.I, new edj($$1, dfa.e.o(), 64));
      sh.a($$0, k, eax.I, new edj($$1, dfa.g.o(), 64));
      sh.a($$0, l, eax.I, new edj($$1, dfa.qz.o(), 64));
      sh.a($$0, m, eax.I, new edj($$11, 17));
      sh.a($$0, n, eax.I, new edj($$11, 17, 0.5F));
      sh.a($$0, o, eax.I, new edj($$6, 9));
      sh.a($$0, p, eax.I, new edj($$6, 4));
      sh.a($$0, q, eax.I, new edj($$7, 9));
      sh.a($$0, r, eax.I, new edj($$7, 9, 0.5F));
      sh.a($$0, s, eax.I, new edj(List.of(edj.a($$2, dfa.dI.o()), edj.a($$3, dfa.dJ.o())), 8));
      sh.a($$0, t, eax.I, new edj($$8, 4, 0.5F));
      sh.a($$0, v, eax.I, new edj($$8, 12, 0.7F));
      sh.a($$0, w, eax.I, new edj($$8, 8, 1.0F));
      sh.a($$0, u, eax.I, new edj($$8, 8, 0.5F));
      sh.a($$0, x, eax.I, new edj($$9, 7));
      sh.a($$0, y, eax.I, new edj($$9, 7, 1.0F));
      sh.a($$0, z, eax.I, new edj(List.of(edj.a($$2, dfa.eN.o()), edj.a($$3, dfa.td.o())), 9));
      sh.a($$0, A, eax.I, new edj(List.of(edj.a($$2, dfa.fE.o()), edj.a($$3, dfa.fF.o())), 3));
      sh.a($$0, B, eax.ae, new edj($$5, dfa.pj.o(), 3, 1.0F));
      sh.a($$0, C, eax.ae, new edj($$5, dfa.pj.o(), 2, 1.0F));
      sh.a($$0, D, eax.I, new edj($$10, 10));
      sh.a($$0, E, eax.I, new edj($$10, 20));
      sh.a($$0, F, eax.I, new edj($$1, dfa.dR.o(), 33));
   }
}
