public class sk {
   public static final aks<eix> a = sp.a("monster_room");
   public static final aks<eix> b = sp.a("monster_room_deep");
   public static final aks<eix> c = sp.a("fossil_upper");
   public static final aks<eix> d = sp.a("fossil_lower");
   public static final aks<eix> e = sp.a("dripstone_cluster");
   public static final aks<eix> f = sp.a("large_dripstone");
   public static final aks<eix> g = sp.a("large_potatostone");
   public static final aks<eix> h = sp.a("pointed_dripstone");
   public static final aks<eix> i = sp.a("underwater_magma");
   public static final aks<eix> j = sp.a("glow_lichen");
   public static final aks<eix> k = sp.a("rooted_azalea_tree");
   public static final aks<eix> l = sp.a("cave_vines");
   public static final aks<eix> m = sp.a("lush_caves_vegetation");
   public static final aks<eix> n = sp.a("lush_caves_clay");
   public static final aks<eix> o = sp.a("lush_caves_ceiling_vegetation");
   public static final aks<eix> p = sp.a("spore_blossom");
   public static final aks<eix> q = sp.a("classic_vines_cave_feature");
   public static final aks<eix> r = sp.a("amethyst_geode");
   public static final aks<eix> s = sp.a("potato_geode");
   public static final aks<eix> t = sp.a("sculk_patch_deep_dark");
   public static final aks<eix> u = sp.a("sculk_patch_ancient_city");
   public static final aks<eix> v = sp.a("sculk_vein");
   public static final aks<eix> w = sp.a("potato_leaf");
   public static final aks<eix> x = sp.a("twisted_potato");

   public static void a(qq<eix> $$0) {
      jb<ebm<?, ?>> $$1 = $$0.a(li.aC);
      ja<ebm<?, ?>> $$2 = $$1.b(ry.a);
      ja<ebm<?, ?>> $$3 = $$1.b(ry.b);
      ja<ebm<?, ?>> $$4 = $$1.b(ry.c);
      ja<ebm<?, ?>> $$5 = $$1.b(ry.d);
      ja<ebm<?, ?>> $$6 = $$1.b(ry.e);
      ja<ebm<?, ?>> $$7 = $$1.b(ry.f);
      ja<ebm<?, ?>> $$8 = $$1.b(ry.g);
      ja<ebm<?, ?>> $$9 = $$1.b(ry.h);
      ja<ebm<?, ?>> $$10 = $$1.b(ry.i);
      ja<ebm<?, ?>> $$11 = $$1.b(ry.j);
      ja<ebm<?, ?>> $$12 = $$1.b(ry.k);
      ja<ebm<?, ?>> $$13 = $$1.b(ry.n);
      ja<ebm<?, ?>> $$14 = $$1.b(ry.u);
      ja<ebm<?, ?>> $$15 = $$1.b(ry.v);
      ja<ebm<?, ?>> $$16 = $$1.b(ry.w);
      ja<ebm<?, ?>> $$17 = $$1.b(sg.c);
      ja<ebm<?, ?>> $$18 = $$1.b(ry.x);
      ja<ebm<?, ?>> $$19 = $$1.b(ry.y);
      ja<ebm<?, ?>> $$20 = $$1.b(ry.z);
      ja<ebm<?, ?>> $$21 = $$1.b(ry.A);
      ja<ebm<?, ?>> $$22 = $$1.b(ry.B);
      ja<ebm<?, ?>> $$23 = $$1.b(ry.p);
      ja<ebm<?, ?>> $$24 = $$1.b(ry.q);
      sp.a($$0, a, $$2, eiq.a(10), eiu.a(), eis.a(dzo.a(0), dzo.b()), eik.a());
      sp.a($$0, b, $$2, eiq.a(4), eiu.a(), eis.a(dzo.b(6), dzo.a(-1)), eik.a());
      sp.a($$0, c, $$3, ejd.a(64), eiu.a(), eis.a(dzo.a(0), dzo.b()), eik.a());
      sp.a($$0, d, $$4, ejd.a(64), eiu.a(), eis.a(dzo.a(), dzo.a(-8)), eik.a());
      sp.a($$0, e, $$5, eiq.a(bpl.a(48, 96)), eiu.a(), sp.i, eik.a());
      sp.a($$0, f, $$6, eiq.a(bpl.a(10, 48)), eiu.a(), sp.i, eik.a());
      sp.a($$0, g, $$7, eiq.a(bpl.a(5, 10)), eiu.a(), sp.i, eik.a());
      sp.a($$0, h, $$8, eiq.a(bpl.a(192, 256)), eiu.a(), sp.i, eiq.a(bpl.a(1, 5)), ejc.a(bpa.a(0.0F, 3.0F, -10, 10), bpa.a(0.0F, 0.6F, -2, 2)), eik.a());
      sp.a($$0, i, $$9, eiq.a(bpl.a(44, 52)), eiu.a(), sp.i, ejf.a(dyu.a.c, Integer.MIN_VALUE, -2), eik.a());
      sp.a($$0, j, $$10, eiq.a(bpl.a(104, 157)), sp.i, eiu.a(), ejf.a(dyu.a.c, Integer.MIN_VALUE, -13), eik.a());
      sp.a($$0, k, $$11, eiq.a(bpl.a(1, 2)), eiu.a(), sp.i, eir.a(iw.b, eab.c(), eab.c, 12), ejc.a(bpc.a(-1)), eik.a());
      sp.a($$0, l, $$12, eiq.a(188), eiu.a(), sp.i, eir.a(iw.b, eab.a(iw.a), eab.c, 12), ejc.a(bpc.a(-1)), eik.a());
      sp.a($$0, m, $$13, eiq.a(125), eiu.a(), sp.i, eir.a(iw.a, eab.c(), eab.c, 12), ejc.a(bpc.a(1)), eik.a());
      sp.a($$0, n, $$14, eiq.a(62), eiu.a(), sp.i, eir.a(iw.a, eab.c(), eab.c, 12), ejc.a(bpc.a(1)), eik.a());
      sp.a($$0, o, $$15, eiq.a(125), eiu.a(), sp.i, eir.a(iw.b, eab.c(), eab.c, 12), ejc.a(bpc.a(-1)), eik.a());
      sp.a($$0, p, $$16, eiq.a(25), eiu.a(), sp.i, eir.a(iw.b, eab.c(), eab.c, 12), ejc.a(bpc.a(-1)), eik.a());
      sp.a($$0, q, $$17, eiq.a(256), eiu.a(), sp.i, eik.a());
      sp.a($$0, r, $$18, ejd.a(24), eiu.a(), eis.a(dzo.b(6), dzo.a(30)), eik.a());
      sp.a($$0, s, $$19, ejd.a(18), eiu.a(), eis.a(dzo.b(6), dzo.a(30)), eik.a());
      sp.a($$0, t, $$20, eiq.a(bpc.a(256)), eiu.a(), sp.i, eik.a());
      sp.a($$0, u, $$21);
      sp.a($$0, v, $$22, eiq.a(bpl.a(204, 250)), eiu.a(), sp.i, eik.a());
      sp.a($$0, w, $$23, eip.a(1), ejd.a(5), eik.a());
      sp.a($$0, x, $$24, eip.a(1), ejd.a(13), eik.a());
   }
}
