import java.util.List;

public class sl {
   public static final ale<ean<?, ?>> a = si.a("ore_magma");
   public static final ale<ean<?, ?>> b = si.a("ore_soul_sand");
   public static final ale<ean<?, ?>> c = si.a("ore_nether_gold");
   public static final ale<ean<?, ?>> d = si.a("ore_quartz");
   public static final ale<ean<?, ?>> e = si.a("ore_gravel_nether");
   public static final ale<ean<?, ?>> f = si.a("ore_blackstone");
   public static final ale<ean<?, ?>> g = si.a("ore_dirt");
   public static final ale<ean<?, ?>> h = si.a("ore_gravel");
   public static final ale<ean<?, ?>> i = si.a("ore_granite");
   public static final ale<ean<?, ?>> j = si.a("ore_diorite");
   public static final ale<ean<?, ?>> k = si.a("ore_andesite");
   public static final ale<ean<?, ?>> l = si.a("ore_tuff");
   public static final ale<ean<?, ?>> m = si.a("ore_coal");
   public static final ale<ean<?, ?>> n = si.a("ore_coal_buried");
   public static final ale<ean<?, ?>> o = si.a("ore_iron");
   public static final ale<ean<?, ?>> p = si.a("ore_iron_small");
   public static final ale<ean<?, ?>> q = si.a("ore_gold");
   public static final ale<ean<?, ?>> r = si.a("ore_gold_buried");
   public static final ale<ean<?, ?>> s = si.a("ore_redstone");
   public static final ale<ean<?, ?>> t = si.a("ore_diamond_small");
   public static final ale<ean<?, ?>> u = si.a("ore_diamond_medium");
   public static final ale<ean<?, ?>> v = si.a("ore_diamond_large");
   public static final ale<ean<?, ?>> w = si.a("ore_diamond_buried");
   public static final ale<ean<?, ?>> x = si.a("ore_lapis");
   public static final ale<ean<?, ?>> y = si.a("ore_lapis_buried");
   public static final ale<ean<?, ?>> z = si.a("ore_infested");
   public static final ale<ean<?, ?>> A = si.a("ore_emerald");
   public static final ale<ean<?, ?>> B = si.a("ore_ancient_debris_large");
   public static final ale<ean<?, ?>> C = si.a("ore_ancient_debris_small");
   public static final ale<ean<?, ?>> D = si.a("ore_copper_small");
   public static final ale<ean<?, ?>> E = si.a("ore_copper_large");
   public static final ale<ean<?, ?>> F = si.a("ore_clay");

   public static void a(rc<ean<?, ?>> $$0) {
      emg $$1 = new emo(awp.be);
      emg $$2 = new emo(awp.bf);
      emg $$3 = new emo(awp.bg);
      emg $$4 = new elp(dfd.dV);
      emg $$5 = new emo(awp.bh);
      List<edm.a> $$6 = List.of(edm.a($$2, dfd.P.o()), edm.a($$3, dfd.Q.o()));
      List<edm.a> $$7 = List.of(edm.a($$2, dfd.N.o()), edm.a($$3, dfd.O.o()));
      List<edm.a> $$8 = List.of(edm.a($$2, dfd.cx.o()), edm.a($$3, dfd.cy.o()));
      List<edm.a> $$9 = List.of(edm.a($$2, dfd.aR.o()), edm.a($$3, dfd.aS.o()));
      List<edm.a> $$10 = List.of(edm.a($$2, dfd.ra.o()), edm.a($$3, dfd.rb.o()));
      List<edm.a> $$11 = List.of(edm.a($$2, dfd.R.o()), edm.a($$3, dfd.S.o()));
      si.a($$0, a, eba.I, new edm($$4, dfd.kJ.o(), 33));
      si.a($$0, b, eba.I, new edm($$4, dfd.dW.o(), 12));
      si.a($$0, c, eba.I, new edm($$4, dfd.T.o(), 10));
      si.a($$0, d, eba.I, new edm($$4, dfd.hb.o(), 14));
      si.a($$0, e, eba.I, new edm($$4, dfd.L.o(), 33));
      si.a($$0, f, eba.I, new edm($$4, dfd.pr.o(), 33));
      si.a($$0, g, eba.I, new edm($$1, dfd.j.o(), 33));
      si.a($$0, h, eba.I, new edm($$1, dfd.L.o(), 33));
      si.a($$0, i, eba.I, new edm($$1, dfd.c.o(), 64));
      si.a($$0, j, eba.I, new edm($$1, dfd.e.o(), 64));
      si.a($$0, k, eba.I, new edm($$1, dfd.g.o(), 64));
      si.a($$0, l, eba.I, new edm($$1, dfd.qz.o(), 64));
      si.a($$0, m, eba.I, new edm($$11, 17));
      si.a($$0, n, eba.I, new edm($$11, 17, 0.5F));
      si.a($$0, o, eba.I, new edm($$6, 9));
      si.a($$0, p, eba.I, new edm($$6, 4));
      si.a($$0, q, eba.I, new edm($$7, 9));
      si.a($$0, r, eba.I, new edm($$7, 9, 0.5F));
      si.a($$0, s, eba.I, new edm(List.of(edm.a($$2, dfd.dI.o()), edm.a($$3, dfd.dJ.o())), 8));
      si.a($$0, t, eba.I, new edm($$8, 4, 0.5F));
      si.a($$0, v, eba.I, new edm($$8, 12, 0.7F));
      si.a($$0, w, eba.I, new edm($$8, 8, 1.0F));
      si.a($$0, u, eba.I, new edm($$8, 8, 0.5F));
      si.a($$0, x, eba.I, new edm($$9, 7));
      si.a($$0, y, eba.I, new edm($$9, 7, 1.0F));
      si.a($$0, z, eba.I, new edm(List.of(edm.a($$2, dfd.eN.o()), edm.a($$3, dfd.td.o())), 9));
      si.a($$0, A, eba.I, new edm(List.of(edm.a($$2, dfd.fE.o()), edm.a($$3, dfd.fF.o())), 3));
      si.a($$0, B, eba.ae, new edm($$5, dfd.pj.o(), 3, 1.0F));
      si.a($$0, C, eba.ae, new edm($$5, dfd.pj.o(), 2, 1.0F));
      si.a($$0, D, eba.I, new edm($$10, 10));
      si.a($$0, E, eba.I, new edm($$10, 20));
      si.a($$0, F, eba.I, new edm($$1, dfd.dR.o(), 33));
   }
}
