import java.util.List;

public class sl {
   public static final ale<eam<?, ?>> a = si.a("ore_magma");
   public static final ale<eam<?, ?>> b = si.a("ore_soul_sand");
   public static final ale<eam<?, ?>> c = si.a("ore_nether_gold");
   public static final ale<eam<?, ?>> d = si.a("ore_quartz");
   public static final ale<eam<?, ?>> e = si.a("ore_gravel_nether");
   public static final ale<eam<?, ?>> f = si.a("ore_blackstone");
   public static final ale<eam<?, ?>> g = si.a("ore_dirt");
   public static final ale<eam<?, ?>> h = si.a("ore_gravel");
   public static final ale<eam<?, ?>> i = si.a("ore_granite");
   public static final ale<eam<?, ?>> j = si.a("ore_diorite");
   public static final ale<eam<?, ?>> k = si.a("ore_andesite");
   public static final ale<eam<?, ?>> l = si.a("ore_tuff");
   public static final ale<eam<?, ?>> m = si.a("ore_coal");
   public static final ale<eam<?, ?>> n = si.a("ore_coal_buried");
   public static final ale<eam<?, ?>> o = si.a("ore_iron");
   public static final ale<eam<?, ?>> p = si.a("ore_iron_small");
   public static final ale<eam<?, ?>> q = si.a("ore_gold");
   public static final ale<eam<?, ?>> r = si.a("ore_gold_buried");
   public static final ale<eam<?, ?>> s = si.a("ore_redstone");
   public static final ale<eam<?, ?>> t = si.a("ore_diamond_small");
   public static final ale<eam<?, ?>> u = si.a("ore_diamond_medium");
   public static final ale<eam<?, ?>> v = si.a("ore_diamond_large");
   public static final ale<eam<?, ?>> w = si.a("ore_diamond_buried");
   public static final ale<eam<?, ?>> x = si.a("ore_lapis");
   public static final ale<eam<?, ?>> y = si.a("ore_lapis_buried");
   public static final ale<eam<?, ?>> z = si.a("ore_infested");
   public static final ale<eam<?, ?>> A = si.a("ore_emerald");
   public static final ale<eam<?, ?>> B = si.a("ore_ancient_debris_large");
   public static final ale<eam<?, ?>> C = si.a("ore_ancient_debris_small");
   public static final ale<eam<?, ?>> D = si.a("ore_copper_small");
   public static final ale<eam<?, ?>> E = si.a("ore_copper_large");
   public static final ale<eam<?, ?>> F = si.a("ore_clay");

   public static void a(rc<eam<?, ?>> $$0) {
      emf $$1 = new emn(awp.be);
      emf $$2 = new emn(awp.bf);
      emf $$3 = new emn(awp.bg);
      emf $$4 = new elo(dfc.dV);
      emf $$5 = new emn(awp.bh);
      List<edl.a> $$6 = List.of(edl.a($$2, dfc.P.o()), edl.a($$3, dfc.Q.o()));
      List<edl.a> $$7 = List.of(edl.a($$2, dfc.N.o()), edl.a($$3, dfc.O.o()));
      List<edl.a> $$8 = List.of(edl.a($$2, dfc.cx.o()), edl.a($$3, dfc.cy.o()));
      List<edl.a> $$9 = List.of(edl.a($$2, dfc.aR.o()), edl.a($$3, dfc.aS.o()));
      List<edl.a> $$10 = List.of(edl.a($$2, dfc.ra.o()), edl.a($$3, dfc.rb.o()));
      List<edl.a> $$11 = List.of(edl.a($$2, dfc.R.o()), edl.a($$3, dfc.S.o()));
      si.a($$0, a, eaz.I, new edl($$4, dfc.kJ.o(), 33));
      si.a($$0, b, eaz.I, new edl($$4, dfc.dW.o(), 12));
      si.a($$0, c, eaz.I, new edl($$4, dfc.T.o(), 10));
      si.a($$0, d, eaz.I, new edl($$4, dfc.hb.o(), 14));
      si.a($$0, e, eaz.I, new edl($$4, dfc.L.o(), 33));
      si.a($$0, f, eaz.I, new edl($$4, dfc.pr.o(), 33));
      si.a($$0, g, eaz.I, new edl($$1, dfc.j.o(), 33));
      si.a($$0, h, eaz.I, new edl($$1, dfc.L.o(), 33));
      si.a($$0, i, eaz.I, new edl($$1, dfc.c.o(), 64));
      si.a($$0, j, eaz.I, new edl($$1, dfc.e.o(), 64));
      si.a($$0, k, eaz.I, new edl($$1, dfc.g.o(), 64));
      si.a($$0, l, eaz.I, new edl($$1, dfc.qz.o(), 64));
      si.a($$0, m, eaz.I, new edl($$11, 17));
      si.a($$0, n, eaz.I, new edl($$11, 17, 0.5F));
      si.a($$0, o, eaz.I, new edl($$6, 9));
      si.a($$0, p, eaz.I, new edl($$6, 4));
      si.a($$0, q, eaz.I, new edl($$7, 9));
      si.a($$0, r, eaz.I, new edl($$7, 9, 0.5F));
      si.a($$0, s, eaz.I, new edl(List.of(edl.a($$2, dfc.dI.o()), edl.a($$3, dfc.dJ.o())), 8));
      si.a($$0, t, eaz.I, new edl($$8, 4, 0.5F));
      si.a($$0, v, eaz.I, new edl($$8, 12, 0.7F));
      si.a($$0, w, eaz.I, new edl($$8, 8, 1.0F));
      si.a($$0, u, eaz.I, new edl($$8, 8, 0.5F));
      si.a($$0, x, eaz.I, new edl($$9, 7));
      si.a($$0, y, eaz.I, new edl($$9, 7, 1.0F));
      si.a($$0, z, eaz.I, new edl(List.of(edl.a($$2, dfc.eN.o()), edl.a($$3, dfc.td.o())), 9));
      si.a($$0, A, eaz.I, new edl(List.of(edl.a($$2, dfc.fE.o()), edl.a($$3, dfc.fF.o())), 3));
      si.a($$0, B, eaz.ae, new edl($$5, dfc.pj.o(), 3, 1.0F));
      si.a($$0, C, eaz.ae, new edl($$5, dfc.pj.o(), 2, 1.0F));
      si.a($$0, D, eaz.I, new edl($$10, 10));
      si.a($$0, E, eaz.I, new edl($$10, 20));
      si.a($$0, F, eaz.I, new edl($$1, dfc.dR.o(), 33));
   }
}
