import java.util.List;

public class sl {
   public static final ald<ekk> a = sk.a("crimson_fungi");
   public static final ald<ekk> b = sk.a("warped_fungi");
   public static final ald<ekk> c = sk.a("oak_checked");
   public static final ald<ekk> d = sk.a("dark_oak_checked");
   public static final ald<ekk> e = sk.a("birch_checked");
   public static final ald<ekk> f = sk.a("acacia_checked");
   public static final ald<ekk> g = sk.a("spruce_checked");
   public static final ald<ekk> h = sk.a("mangrove_checked");
   public static final ald<ekk> i = sk.a("cherry_checked");
   public static final ald<ekk> j = sk.a("pine_on_snow");
   public static final ald<ekk> k = sk.a("spruce_on_snow");
   public static final ald<ekk> l = sk.a("pine_checked");
   public static final ald<ekk> m = sk.a("jungle_tree");
   public static final ald<ekk> n = sk.a("fancy_oak_checked");
   public static final ald<ekk> o = sk.a("mega_jungle_tree_checked");
   public static final ald<ekk> p = sk.a("mega_spruce_checked");
   public static final ald<ekk> q = sk.a("mega_pine_checked");
   public static final ald<ekk> r = sk.a("tall_mangrove_checked");
   public static final ald<ekk> s = sk.a("jungle_bush");
   public static final ald<ekk> t = sk.a("super_birch_bees_0002");
   public static final ald<ekk> u = sk.a("super_birch_bees");
   public static final ald<ekk> v = sk.a("oak_bees_0002");
   public static final ald<ekk> w = sk.a("oak_bees_002");
   public static final ald<ekk> x = sk.a("birch_bees_0002");
   public static final ald<ekk> y = sk.a("birch_bees_002");
   public static final ald<ekk> z = sk.a("fancy_oak_bees_0002");
   public static final ald<ekk> A = sk.a("fancy_oak_bees_002");
   public static final ald<ekk> B = sk.a("fancy_oak_bees");
   public static final ald<ekk> C = sk.a("cherry_bees_005");

   public static void a(qu<ekk> $$0) {
      jp<edg<?, ?>> $$1 = $$0.a(lw.aK);
      jo<edg<?, ?>> $$2 = $$1.b(sa.a);
      jo<edg<?, ?>> $$3 = $$1.b(sa.c);
      jo<edg<?, ?>> $$4 = $$1.b(sa.g);
      jo<edg<?, ?>> $$5 = $$1.b(sa.h);
      jo<edg<?, ?>> $$6 = $$1.b(sa.i);
      jo<edg<?, ?>> $$7 = $$1.b(sa.j);
      jo<edg<?, ?>> $$8 = $$1.b(sa.k);
      jo<edg<?, ?>> $$9 = $$1.b(sa.x);
      jo<edg<?, ?>> $$10 = $$1.b(sa.z);
      jo<edg<?, ?>> $$11 = $$1.b(sa.l);
      jo<edg<?, ?>> $$12 = $$1.b(sa.m);
      jo<edg<?, ?>> $$13 = $$1.b(sa.n);
      jo<edg<?, ?>> $$14 = $$1.b(sa.p);
      jo<edg<?, ?>> $$15 = $$1.b(sa.q);
      jo<edg<?, ?>> $$16 = $$1.b(sa.r);
      jo<edg<?, ?>> $$17 = $$1.b(sa.y);
      jo<edg<?, ?>> $$18 = $$1.b(sa.v);
      jo<edg<?, ?>> $$19 = $$1.b(sa.s);
      jo<edg<?, ?>> $$20 = $$1.b(sa.t);
      jo<edg<?, ?>> $$21 = $$1.b(sa.A);
      jo<edg<?, ?>> $$22 = $$1.b(sa.B);
      jo<edg<?, ?>> $$23 = $$1.b(sa.D);
      jo<edg<?, ?>> $$24 = $$1.b(sa.E);
      jo<edg<?, ?>> $$25 = $$1.b(sa.G);
      jo<edg<?, ?>> $$26 = $$1.b(sa.H);
      jo<edg<?, ?>> $$27 = $$1.b(sa.J);
      jo<edg<?, ?>> $$28 = $$1.b(sa.K);
      sk.a($$0, a, $$2, ekb.a(8), ejy.a());
      sk.a($$0, b, $$3, ekb.a(8), ejy.a());
      sk.a($$0, c, $$4, sk.a(dho.x));
      sk.a($$0, d, $$5, sk.a(dho.D));
      sk.a($$0, e, $$6, sk.a(dho.z));
      sk.a($$0, f, $$7, sk.a(dho.B));
      sk.a($$0, g, $$8, sk.a(dho.y));
      sk.a($$0, h, $$9, sk.a(dho.E));
      sk.a($$0, i, $$10, sk.a(dho.C));
      ebv $$29 = ebv.a(jk.a.q(), dho.dP, dho.qP);
      List<ekn> $$30 = List.of(ekd.a(jk.b, ebv.a(ebv.a(dho.qP)), 8), ejz.a($$29));
      sk.a($$0, j, $$11, $$30);
      sk.a($$0, k, $$8, $$30);
      sk.a($$0, l, $$11, sk.a(dho.y));
      sk.a($$0, m, $$12, sk.a(dho.A));
      sk.a($$0, n, $$13, sk.a(dho.x));
      sk.a($$0, o, $$14, sk.a(dho.A));
      sk.a($$0, p, $$15, sk.a(dho.y));
      sk.a($$0, q, $$16, sk.a(dho.y));
      sk.a($$0, r, $$17, sk.a(dho.E));
      sk.a($$0, s, $$18, sk.a(dho.x));
      sk.a($$0, t, $$19, sk.a(dho.z));
      sk.a($$0, u, $$20, sk.a(dho.z));
      sk.a($$0, v, $$21, sk.a(dho.x));
      sk.a($$0, w, $$22, sk.a(dho.x));
      sk.a($$0, x, $$23, sk.a(dho.z));
      sk.a($$0, y, $$24, sk.a(dho.z));
      sk.a($$0, z, $$25, sk.a(dho.x));
      sk.a($$0, A, $$26, sk.a(dho.x));
      sk.a($$0, B, $$27, sk.a(dho.x));
      sk.a($$0, C, $$28, sk.a(dho.C));
   }
}
