import java.util.List;

public class sp {
   public static final alh<elb> a = so.a("crimson_fungi");
   public static final alh<elb> b = so.a("warped_fungi");
   public static final alh<elb> c = so.a("oak_checked");
   public static final alh<elb> d = so.a("dark_oak_checked");
   public static final alh<elb> e = so.a("birch_checked");
   public static final alh<elb> f = so.a("acacia_checked");
   public static final alh<elb> g = so.a("spruce_checked");
   public static final alh<elb> h = so.a("mangrove_checked");
   public static final alh<elb> i = so.a("cherry_checked");
   public static final alh<elb> j = so.a("pine_on_snow");
   public static final alh<elb> k = so.a("spruce_on_snow");
   public static final alh<elb> l = so.a("pine_checked");
   public static final alh<elb> m = so.a("jungle_tree");
   public static final alh<elb> n = so.a("fancy_oak_checked");
   public static final alh<elb> o = so.a("mega_jungle_tree_checked");
   public static final alh<elb> p = so.a("mega_spruce_checked");
   public static final alh<elb> q = so.a("mega_pine_checked");
   public static final alh<elb> r = so.a("tall_mangrove_checked");
   public static final alh<elb> s = so.a("jungle_bush");
   public static final alh<elb> t = so.a("super_birch_bees_0002");
   public static final alh<elb> u = so.a("super_birch_bees");
   public static final alh<elb> v = so.a("oak_bees_0002");
   public static final alh<elb> w = so.a("oak_bees_002");
   public static final alh<elb> x = so.a("birch_bees_0002");
   public static final alh<elb> y = so.a("birch_bees_002");
   public static final alh<elb> z = so.a("fancy_oak_bees_0002");
   public static final alh<elb> A = so.a("fancy_oak_bees_002");
   public static final alh<elb> B = so.a("fancy_oak_bees");
   public static final alh<elb> C = so.a("cherry_bees_005");

   public static void a(qy<elb> $$0) {
      jr<edx<?, ?>> $$1 = $$0.a(lz.aJ);
      jq<edx<?, ?>> $$2 = $$1.b(se.a);
      jq<edx<?, ?>> $$3 = $$1.b(se.c);
      jq<edx<?, ?>> $$4 = $$1.b(se.g);
      jq<edx<?, ?>> $$5 = $$1.b(se.h);
      jq<edx<?, ?>> $$6 = $$1.b(se.i);
      jq<edx<?, ?>> $$7 = $$1.b(se.j);
      jq<edx<?, ?>> $$8 = $$1.b(se.k);
      jq<edx<?, ?>> $$9 = $$1.b(se.x);
      jq<edx<?, ?>> $$10 = $$1.b(se.z);
      jq<edx<?, ?>> $$11 = $$1.b(se.l);
      jq<edx<?, ?>> $$12 = $$1.b(se.m);
      jq<edx<?, ?>> $$13 = $$1.b(se.n);
      jq<edx<?, ?>> $$14 = $$1.b(se.p);
      jq<edx<?, ?>> $$15 = $$1.b(se.q);
      jq<edx<?, ?>> $$16 = $$1.b(se.r);
      jq<edx<?, ?>> $$17 = $$1.b(se.y);
      jq<edx<?, ?>> $$18 = $$1.b(se.v);
      jq<edx<?, ?>> $$19 = $$1.b(se.s);
      jq<edx<?, ?>> $$20 = $$1.b(se.t);
      jq<edx<?, ?>> $$21 = $$1.b(se.A);
      jq<edx<?, ?>> $$22 = $$1.b(se.B);
      jq<edx<?, ?>> $$23 = $$1.b(se.D);
      jq<edx<?, ?>> $$24 = $$1.b(se.E);
      jq<edx<?, ?>> $$25 = $$1.b(se.G);
      jq<edx<?, ?>> $$26 = $$1.b(se.H);
      jq<edx<?, ?>> $$27 = $$1.b(se.J);
      jq<edx<?, ?>> $$28 = $$1.b(se.K);
      so.a($$0, a, $$2, eks.a(8), ekp.a());
      so.a($$0, b, $$3, eks.a(8), ekp.a());
      so.a($$0, c, $$4, so.a(dig.x));
      so.a($$0, d, $$5, so.a(dig.D));
      so.a($$0, e, $$6, so.a(dig.z));
      so.a($$0, f, $$7, so.a(dig.B));
      so.a($$0, g, $$8, so.a(dig.y));
      so.a($$0, h, $$9, so.a(dig.E));
      so.a($$0, i, $$10, so.a(dig.C));
      ecm $$29 = ecm.a(jm.a.q(), dig.dP, dig.qP);
      List<ele> $$30 = List.of(eku.a(jm.b, ecm.a(ecm.a(dig.qP)), 8), ekq.a($$29));
      so.a($$0, j, $$11, $$30);
      so.a($$0, k, $$8, $$30);
      so.a($$0, l, $$11, so.a(dig.y));
      so.a($$0, m, $$12, so.a(dig.A));
      so.a($$0, n, $$13, so.a(dig.x));
      so.a($$0, o, $$14, so.a(dig.A));
      so.a($$0, p, $$15, so.a(dig.y));
      so.a($$0, q, $$16, so.a(dig.y));
      so.a($$0, r, $$17, so.a(dig.E));
      so.a($$0, s, $$18, so.a(dig.x));
      so.a($$0, t, $$19, so.a(dig.z));
      so.a($$0, u, $$20, so.a(dig.z));
      so.a($$0, v, $$21, so.a(dig.x));
      so.a($$0, w, $$22, so.a(dig.x));
      so.a($$0, x, $$23, so.a(dig.z));
      so.a($$0, y, $$24, so.a(dig.z));
      so.a($$0, z, $$25, so.a(dig.x));
      so.a($$0, A, $$26, so.a(dig.x));
      so.a($$0, B, $$27, so.a(dig.x));
      so.a($$0, C, $$28, so.a(dig.C));
   }
}
