import java.util.List;

public class sq {
   public static final ali<elm> a = sp.a("crimson_fungi");
   public static final ali<elm> b = sp.a("warped_fungi");
   public static final ali<elm> c = sp.a("oak_checked");
   public static final ali<elm> d = sp.a("dark_oak_checked");
   public static final ali<elm> e = sp.a("birch_checked");
   public static final ali<elm> f = sp.a("acacia_checked");
   public static final ali<elm> g = sp.a("spruce_checked");
   public static final ali<elm> h = sp.a("mangrove_checked");
   public static final ali<elm> i = sp.a("cherry_checked");
   public static final ali<elm> j = sp.a("pine_on_snow");
   public static final ali<elm> k = sp.a("spruce_on_snow");
   public static final ali<elm> l = sp.a("pine_checked");
   public static final ali<elm> m = sp.a("jungle_tree");
   public static final ali<elm> n = sp.a("fancy_oak_checked");
   public static final ali<elm> o = sp.a("mega_jungle_tree_checked");
   public static final ali<elm> p = sp.a("mega_spruce_checked");
   public static final ali<elm> q = sp.a("mega_pine_checked");
   public static final ali<elm> r = sp.a("tall_mangrove_checked");
   public static final ali<elm> s = sp.a("jungle_bush");
   public static final ali<elm> t = sp.a("super_birch_bees_0002");
   public static final ali<elm> u = sp.a("super_birch_bees");
   public static final ali<elm> v = sp.a("oak_bees_0002");
   public static final ali<elm> w = sp.a("oak_bees_002");
   public static final ali<elm> x = sp.a("birch_bees_0002");
   public static final ali<elm> y = sp.a("birch_bees_002");
   public static final ali<elm> z = sp.a("fancy_oak_bees_0002");
   public static final ali<elm> A = sp.a("fancy_oak_bees_002");
   public static final ali<elm> B = sp.a("fancy_oak_bees");
   public static final ali<elm> C = sp.a("cherry_bees_005");

   public static void a(qz<elm> $$0) {
      jr<eei<?, ?>> $$1 = $$0.a(ma.aJ);
      jq<eei<?, ?>> $$2 = $$1.b(sf.a);
      jq<eei<?, ?>> $$3 = $$1.b(sf.c);
      jq<eei<?, ?>> $$4 = $$1.b(sf.g);
      jq<eei<?, ?>> $$5 = $$1.b(sf.h);
      jq<eei<?, ?>> $$6 = $$1.b(sf.i);
      jq<eei<?, ?>> $$7 = $$1.b(sf.j);
      jq<eei<?, ?>> $$8 = $$1.b(sf.k);
      jq<eei<?, ?>> $$9 = $$1.b(sf.x);
      jq<eei<?, ?>> $$10 = $$1.b(sf.z);
      jq<eei<?, ?>> $$11 = $$1.b(sf.l);
      jq<eei<?, ?>> $$12 = $$1.b(sf.m);
      jq<eei<?, ?>> $$13 = $$1.b(sf.n);
      jq<eei<?, ?>> $$14 = $$1.b(sf.p);
      jq<eei<?, ?>> $$15 = $$1.b(sf.q);
      jq<eei<?, ?>> $$16 = $$1.b(sf.r);
      jq<eei<?, ?>> $$17 = $$1.b(sf.y);
      jq<eei<?, ?>> $$18 = $$1.b(sf.v);
      jq<eei<?, ?>> $$19 = $$1.b(sf.s);
      jq<eei<?, ?>> $$20 = $$1.b(sf.t);
      jq<eei<?, ?>> $$21 = $$1.b(sf.A);
      jq<eei<?, ?>> $$22 = $$1.b(sf.B);
      jq<eei<?, ?>> $$23 = $$1.b(sf.D);
      jq<eei<?, ?>> $$24 = $$1.b(sf.E);
      jq<eei<?, ?>> $$25 = $$1.b(sf.G);
      jq<eei<?, ?>> $$26 = $$1.b(sf.H);
      jq<eei<?, ?>> $$27 = $$1.b(sf.J);
      jq<eei<?, ?>> $$28 = $$1.b(sf.K);
      sp.a($$0, a, $$2, eld.a(8), ela.a());
      sp.a($$0, b, $$3, eld.a(8), ela.a());
      sp.a($$0, c, $$4, sp.a(dis.x));
      sp.a($$0, d, $$5, sp.a(dis.D));
      sp.a($$0, e, $$6, sp.a(dis.z));
      sp.a($$0, f, $$7, sp.a(dis.B));
      sp.a($$0, g, $$8, sp.a(dis.y));
      sp.a($$0, h, $$9, sp.a(dis.E));
      sp.a($$0, i, $$10, sp.a(dis.C));
      ecx $$29 = ecx.a(jm.a.q(), dis.dP, dis.qP);
      List<elp> $$30 = List.of(elf.a(jm.b, ecx.a(ecx.a(dis.qP)), 8), elb.a($$29));
      sp.a($$0, j, $$11, $$30);
      sp.a($$0, k, $$8, $$30);
      sp.a($$0, l, $$11, sp.a(dis.y));
      sp.a($$0, m, $$12, sp.a(dis.A));
      sp.a($$0, n, $$13, sp.a(dis.x));
      sp.a($$0, o, $$14, sp.a(dis.A));
      sp.a($$0, p, $$15, sp.a(dis.y));
      sp.a($$0, q, $$16, sp.a(dis.y));
      sp.a($$0, r, $$17, sp.a(dis.E));
      sp.a($$0, s, $$18, sp.a(dis.x));
      sp.a($$0, t, $$19, sp.a(dis.z));
      sp.a($$0, u, $$20, sp.a(dis.z));
      sp.a($$0, v, $$21, sp.a(dis.x));
      sp.a($$0, w, $$22, sp.a(dis.x));
      sp.a($$0, x, $$23, sp.a(dis.z));
      sp.a($$0, y, $$24, sp.a(dis.z));
      sp.a($$0, z, $$25, sp.a(dis.x));
      sp.a($$0, A, $$26, sp.a(dis.x));
      sp.a($$0, B, $$27, sp.a(dis.x));
      sp.a($$0, C, $$28, sp.a(dis.C));
   }
}
