public class sr {
   public static final ald<ehm> a = sw.a("monster_room");
   public static final ald<ehm> b = sw.a("monster_room_deep");
   public static final ald<ehm> c = sw.a("fossil_upper");
   public static final ald<ehm> d = sw.a("fossil_lower");
   public static final ald<ehm> e = sw.a("dripstone_cluster");
   public static final ald<ehm> f = sw.a("large_dripstone");
   public static final ald<ehm> g = sw.a("pointed_dripstone");
   public static final ald<ehm> h = sw.a("underwater_magma");
   public static final ald<ehm> i = sw.a("glow_lichen");
   public static final ald<ehm> j = sw.a("rooted_azalea_tree");
   public static final ald<ehm> k = sw.a("cave_vines");
   public static final ald<ehm> l = sw.a("lush_caves_vegetation");
   public static final ald<ehm> m = sw.a("lush_caves_clay");
   public static final ald<ehm> n = sw.a("lush_caves_ceiling_vegetation");
   public static final ald<ehm> o = sw.a("spore_blossom");
   public static final ald<ehm> p = sw.a("classic_vines_cave_feature");
   public static final ald<ehm> q = sw.a("amethyst_geode");
   public static final ald<ehm> r = sw.a("sculk_patch_deep_dark");
   public static final ald<ehm> s = sw.a("sculk_patch_ancient_city");
   public static final ald<ehm> t = sw.a("sculk_vein");

   public static void a(rc<ehm> $$0) {
      jj<eaj<?, ?>> $$1 = $$0.a(lq.aC);
      ji<eaj<?, ?>> $$2 = $$1.b(sf.a);
      ji<eaj<?, ?>> $$3 = $$1.b(sf.b);
      ji<eaj<?, ?>> $$4 = $$1.b(sf.c);
      ji<eaj<?, ?>> $$5 = $$1.b(sf.d);
      ji<eaj<?, ?>> $$6 = $$1.b(sf.e);
      ji<eaj<?, ?>> $$7 = $$1.b(sf.f);
      ji<eaj<?, ?>> $$8 = $$1.b(sf.g);
      ji<eaj<?, ?>> $$9 = $$1.b(sf.h);
      ji<eaj<?, ?>> $$10 = $$1.b(sf.i);
      ji<eaj<?, ?>> $$11 = $$1.b(sf.j);
      ji<eaj<?, ?>> $$12 = $$1.b(sf.m);
      ji<eaj<?, ?>> $$13 = $$1.b(sf.r);
      ji<eaj<?, ?>> $$14 = $$1.b(sf.s);
      ji<eaj<?, ?>> $$15 = $$1.b(sf.t);
      ji<eaj<?, ?>> $$16 = $$1.b(sn.c);
      ji<eaj<?, ?>> $$17 = $$1.b(sf.u);
      ji<eaj<?, ?>> $$18 = $$1.b(sf.v);
      ji<eaj<?, ?>> $$19 = $$1.b(sf.w);
      ji<eaj<?, ?>> $$20 = $$1.b(sf.x);
      sw.a($$0, a, $$2, ehf.a(10), ehj.a(), ehh.a(dym.a(0), dym.b()), eha.a());
      sw.a($$0, b, $$2, ehf.a(4), ehj.a(), ehh.a(dym.b(6), dym.a(-1)), eha.a());
      sw.a($$0, c, $$3, ehs.a(64), ehj.a(), ehh.a(dym.a(0), dym.b()), eha.a());
      sw.a($$0, d, $$4, ehs.a(64), ehj.a(), ehh.a(dym.a(), dym.a(-8)), eha.a());
      sw.a($$0, e, $$5, ehf.a(bqd.a(48, 96)), ehj.a(), sw.i, eha.a());
      sw.a($$0, f, $$6, ehf.a(bqd.a(10, 48)), ehj.a(), sw.i, eha.a());
      sw.a($$0, g, $$7, ehf.a(bqd.a(192, 256)), ehj.a(), sw.i, ehf.a(bqd.a(1, 5)), ehr.a(bps.a(0.0F, 3.0F, -10, 10), bps.a(0.0F, 0.6F, -2, 2)), eha.a());
      sw.a($$0, h, $$8, ehf.a(bqd.a(44, 52)), ehj.a(), sw.i, ehu.a(dxs.a.c, Integer.MIN_VALUE, -2), eha.a());
      sw.a($$0, i, $$9, ehf.a(bqd.a(104, 157)), sw.i, ehj.a(), ehu.a(dxs.a.c, Integer.MIN_VALUE, -13), eha.a());
      sw.a($$0, j, $$10, ehf.a(bqd.a(1, 2)), ehj.a(), sw.i, ehg.a(je.b, dyz.c(), dyz.c, 12), ehr.a(bpu.a(-1)), eha.a());
      sw.a($$0, k, $$11, ehf.a(188), ehj.a(), sw.i, ehg.a(je.b, dyz.a(je.a), dyz.c, 12), ehr.a(bpu.a(-1)), eha.a());
      sw.a($$0, l, $$12, ehf.a(125), ehj.a(), sw.i, ehg.a(je.a, dyz.c(), dyz.c, 12), ehr.a(bpu.a(1)), eha.a());
      sw.a($$0, m, $$13, ehf.a(62), ehj.a(), sw.i, ehg.a(je.a, dyz.c(), dyz.c, 12), ehr.a(bpu.a(1)), eha.a());
      sw.a($$0, n, $$14, ehf.a(125), ehj.a(), sw.i, ehg.a(je.b, dyz.c(), dyz.c, 12), ehr.a(bpu.a(-1)), eha.a());
      sw.a($$0, o, $$15, ehf.a(25), ehj.a(), sw.i, ehg.a(je.b, dyz.c(), dyz.c, 12), ehr.a(bpu.a(-1)), eha.a());
      sw.a($$0, p, $$16, ehf.a(256), ehj.a(), sw.i, eha.a());
      sw.a($$0, q, $$17, ehs.a(24), ehj.a(), ehh.a(dym.b(6), dym.a(30)), eha.a());
      sw.a($$0, r, $$18, ehf.a(bpu.a(256)), ehj.a(), sw.i, eha.a());
      sw.a($$0, s, $$19);
      sw.a($$0, t, $$20, ehf.a(bqd.a(204, 250)), ehj.a(), sw.i, eha.a());
   }
}
