public class ss {
   public static final ale<eho> a = sx.a("monster_room");
   public static final ale<eho> b = sx.a("monster_room_deep");
   public static final ale<eho> c = sx.a("fossil_upper");
   public static final ale<eho> d = sx.a("fossil_lower");
   public static final ale<eho> e = sx.a("dripstone_cluster");
   public static final ale<eho> f = sx.a("large_dripstone");
   public static final ale<eho> g = sx.a("pointed_dripstone");
   public static final ale<eho> h = sx.a("underwater_magma");
   public static final ale<eho> i = sx.a("glow_lichen");
   public static final ale<eho> j = sx.a("rooted_azalea_tree");
   public static final ale<eho> k = sx.a("cave_vines");
   public static final ale<eho> l = sx.a("lush_caves_vegetation");
   public static final ale<eho> m = sx.a("lush_caves_clay");
   public static final ale<eho> n = sx.a("lush_caves_ceiling_vegetation");
   public static final ale<eho> o = sx.a("spore_blossom");
   public static final ale<eho> p = sx.a("classic_vines_cave_feature");
   public static final ale<eho> q = sx.a("amethyst_geode");
   public static final ale<eho> r = sx.a("sculk_patch_deep_dark");
   public static final ale<eho> s = sx.a("sculk_patch_ancient_city");
   public static final ale<eho> t = sx.a("sculk_vein");

   public static void a(rc<eho> $$0) {
      jj<eal<?, ?>> $$1 = $$0.a(lq.aC);
      ji<eal<?, ?>> $$2 = $$1.b(sg.a);
      ji<eal<?, ?>> $$3 = $$1.b(sg.b);
      ji<eal<?, ?>> $$4 = $$1.b(sg.c);
      ji<eal<?, ?>> $$5 = $$1.b(sg.d);
      ji<eal<?, ?>> $$6 = $$1.b(sg.e);
      ji<eal<?, ?>> $$7 = $$1.b(sg.f);
      ji<eal<?, ?>> $$8 = $$1.b(sg.g);
      ji<eal<?, ?>> $$9 = $$1.b(sg.h);
      ji<eal<?, ?>> $$10 = $$1.b(sg.i);
      ji<eal<?, ?>> $$11 = $$1.b(sg.j);
      ji<eal<?, ?>> $$12 = $$1.b(sg.m);
      ji<eal<?, ?>> $$13 = $$1.b(sg.r);
      ji<eal<?, ?>> $$14 = $$1.b(sg.s);
      ji<eal<?, ?>> $$15 = $$1.b(sg.t);
      ji<eal<?, ?>> $$16 = $$1.b(so.c);
      ji<eal<?, ?>> $$17 = $$1.b(sg.u);
      ji<eal<?, ?>> $$18 = $$1.b(sg.v);
      ji<eal<?, ?>> $$19 = $$1.b(sg.w);
      ji<eal<?, ?>> $$20 = $$1.b(sg.x);
      sx.a($$0, a, $$2, ehh.a(10), ehl.a(), ehj.a(dyo.a(0), dyo.b()), ehc.a());
      sx.a($$0, b, $$2, ehh.a(4), ehl.a(), ehj.a(dyo.b(6), dyo.a(-1)), ehc.a());
      sx.a($$0, c, $$3, ehu.a(64), ehl.a(), ehj.a(dyo.a(0), dyo.b()), ehc.a());
      sx.a($$0, d, $$4, ehu.a(64), ehl.a(), ehj.a(dyo.a(), dyo.a(-8)), ehc.a());
      sx.a($$0, e, $$5, ehh.a(bqf.a(48, 96)), ehl.a(), sx.i, ehc.a());
      sx.a($$0, f, $$6, ehh.a(bqf.a(10, 48)), ehl.a(), sx.i, ehc.a());
      sx.a($$0, g, $$7, ehh.a(bqf.a(192, 256)), ehl.a(), sx.i, ehh.a(bqf.a(1, 5)), eht.a(bpu.a(0.0F, 3.0F, -10, 10), bpu.a(0.0F, 0.6F, -2, 2)), ehc.a());
      sx.a($$0, h, $$8, ehh.a(bqf.a(44, 52)), ehl.a(), sx.i, ehw.a(dxu.a.c, Integer.MIN_VALUE, -2), ehc.a());
      sx.a($$0, i, $$9, ehh.a(bqf.a(104, 157)), sx.i, ehl.a(), ehw.a(dxu.a.c, Integer.MIN_VALUE, -13), ehc.a());
      sx.a($$0, j, $$10, ehh.a(bqf.a(1, 2)), ehl.a(), sx.i, ehi.a(je.b, dzb.c(), dzb.c, 12), eht.a(bpw.a(-1)), ehc.a());
      sx.a($$0, k, $$11, ehh.a(188), ehl.a(), sx.i, ehi.a(je.b, dzb.a(je.a), dzb.c, 12), eht.a(bpw.a(-1)), ehc.a());
      sx.a($$0, l, $$12, ehh.a(125), ehl.a(), sx.i, ehi.a(je.a, dzb.c(), dzb.c, 12), eht.a(bpw.a(1)), ehc.a());
      sx.a($$0, m, $$13, ehh.a(62), ehl.a(), sx.i, ehi.a(je.a, dzb.c(), dzb.c, 12), eht.a(bpw.a(1)), ehc.a());
      sx.a($$0, n, $$14, ehh.a(125), ehl.a(), sx.i, ehi.a(je.b, dzb.c(), dzb.c, 12), eht.a(bpw.a(-1)), ehc.a());
      sx.a($$0, o, $$15, ehh.a(25), ehl.a(), sx.i, ehi.a(je.b, dzb.c(), dzb.c, 12), eht.a(bpw.a(-1)), ehc.a());
      sx.a($$0, p, $$16, ehh.a(256), ehl.a(), sx.i, ehc.a());
      sx.a($$0, q, $$17, ehu.a(24), ehl.a(), ehj.a(dyo.b(6), dyo.a(30)), ehc.a());
      sx.a($$0, r, $$18, ehh.a(bpw.a(256)), ehl.a(), sx.i, ehc.a());
      sx.a($$0, s, $$19);
      sx.a($$0, t, $$20, ehh.a(bqf.a(204, 250)), ehl.a(), sx.i, ehc.a());
   }
}
