public class ss {
   public static final ale<ehq> a = sx.a("monster_room");
   public static final ale<ehq> b = sx.a("monster_room_deep");
   public static final ale<ehq> c = sx.a("fossil_upper");
   public static final ale<ehq> d = sx.a("fossil_lower");
   public static final ale<ehq> e = sx.a("dripstone_cluster");
   public static final ale<ehq> f = sx.a("large_dripstone");
   public static final ale<ehq> g = sx.a("pointed_dripstone");
   public static final ale<ehq> h = sx.a("underwater_magma");
   public static final ale<ehq> i = sx.a("glow_lichen");
   public static final ale<ehq> j = sx.a("rooted_azalea_tree");
   public static final ale<ehq> k = sx.a("cave_vines");
   public static final ale<ehq> l = sx.a("lush_caves_vegetation");
   public static final ale<ehq> m = sx.a("lush_caves_clay");
   public static final ale<ehq> n = sx.a("lush_caves_ceiling_vegetation");
   public static final ale<ehq> o = sx.a("spore_blossom");
   public static final ale<ehq> p = sx.a("classic_vines_cave_feature");
   public static final ale<ehq> q = sx.a("amethyst_geode");
   public static final ale<ehq> r = sx.a("sculk_patch_deep_dark");
   public static final ale<ehq> s = sx.a("sculk_patch_ancient_city");
   public static final ale<ehq> t = sx.a("sculk_vein");

   public static void a(rc<ehq> $$0) {
      jj<ean<?, ?>> $$1 = $$0.a(lq.aC);
      ji<ean<?, ?>> $$2 = $$1.b(sg.a);
      ji<ean<?, ?>> $$3 = $$1.b(sg.b);
      ji<ean<?, ?>> $$4 = $$1.b(sg.c);
      ji<ean<?, ?>> $$5 = $$1.b(sg.d);
      ji<ean<?, ?>> $$6 = $$1.b(sg.e);
      ji<ean<?, ?>> $$7 = $$1.b(sg.f);
      ji<ean<?, ?>> $$8 = $$1.b(sg.g);
      ji<ean<?, ?>> $$9 = $$1.b(sg.h);
      ji<ean<?, ?>> $$10 = $$1.b(sg.i);
      ji<ean<?, ?>> $$11 = $$1.b(sg.j);
      ji<ean<?, ?>> $$12 = $$1.b(sg.m);
      ji<ean<?, ?>> $$13 = $$1.b(sg.r);
      ji<ean<?, ?>> $$14 = $$1.b(sg.s);
      ji<ean<?, ?>> $$15 = $$1.b(sg.t);
      ji<ean<?, ?>> $$16 = $$1.b(so.c);
      ji<ean<?, ?>> $$17 = $$1.b(sg.u);
      ji<ean<?, ?>> $$18 = $$1.b(sg.v);
      ji<ean<?, ?>> $$19 = $$1.b(sg.w);
      ji<ean<?, ?>> $$20 = $$1.b(sg.x);
      sx.a($$0, a, $$2, ehj.a(10), ehn.a(), ehl.a(dyq.a(0), dyq.b()), ehe.a());
      sx.a($$0, b, $$2, ehj.a(4), ehn.a(), ehl.a(dyq.b(6), dyq.a(-1)), ehe.a());
      sx.a($$0, c, $$3, ehw.a(64), ehn.a(), ehl.a(dyq.a(0), dyq.b()), ehe.a());
      sx.a($$0, d, $$4, ehw.a(64), ehn.a(), ehl.a(dyq.a(), dyq.a(-8)), ehe.a());
      sx.a($$0, e, $$5, ehj.a(bqh.a(48, 96)), ehn.a(), sx.i, ehe.a());
      sx.a($$0, f, $$6, ehj.a(bqh.a(10, 48)), ehn.a(), sx.i, ehe.a());
      sx.a($$0, g, $$7, ehj.a(bqh.a(192, 256)), ehn.a(), sx.i, ehj.a(bqh.a(1, 5)), ehv.a(bpw.a(0.0F, 3.0F, -10, 10), bpw.a(0.0F, 0.6F, -2, 2)), ehe.a());
      sx.a($$0, h, $$8, ehj.a(bqh.a(44, 52)), ehn.a(), sx.i, ehy.a(dxw.a.c, Integer.MIN_VALUE, -2), ehe.a());
      sx.a($$0, i, $$9, ehj.a(bqh.a(104, 157)), sx.i, ehn.a(), ehy.a(dxw.a.c, Integer.MIN_VALUE, -13), ehe.a());
      sx.a($$0, j, $$10, ehj.a(bqh.a(1, 2)), ehn.a(), sx.i, ehk.a(je.b, dzd.c(), dzd.c, 12), ehv.a(bpy.a(-1)), ehe.a());
      sx.a($$0, k, $$11, ehj.a(188), ehn.a(), sx.i, ehk.a(je.b, dzd.a(je.a), dzd.c, 12), ehv.a(bpy.a(-1)), ehe.a());
      sx.a($$0, l, $$12, ehj.a(125), ehn.a(), sx.i, ehk.a(je.a, dzd.c(), dzd.c, 12), ehv.a(bpy.a(1)), ehe.a());
      sx.a($$0, m, $$13, ehj.a(62), ehn.a(), sx.i, ehk.a(je.a, dzd.c(), dzd.c, 12), ehv.a(bpy.a(1)), ehe.a());
      sx.a($$0, n, $$14, ehj.a(125), ehn.a(), sx.i, ehk.a(je.b, dzd.c(), dzd.c, 12), ehv.a(bpy.a(-1)), ehe.a());
      sx.a($$0, o, $$15, ehj.a(25), ehn.a(), sx.i, ehk.a(je.b, dzd.c(), dzd.c, 12), ehv.a(bpy.a(-1)), ehe.a());
      sx.a($$0, p, $$16, ehj.a(256), ehn.a(), sx.i, ehe.a());
      sx.a($$0, q, $$17, ehw.a(24), ehn.a(), ehl.a(dyq.b(6), dyq.a(30)), ehe.a());
      sx.a($$0, r, $$18, ehj.a(bpy.a(256)), ehn.a(), sx.i, ehe.a());
      sx.a($$0, s, $$19);
      sx.a($$0, t, $$20, ehj.a(bqh.a(204, 250)), ehn.a(), sx.i, ehe.a());
   }
}
