import java.util.List;

public class sx {
   public static final ald<ehm> a = sw.a("crimson_fungi");
   public static final ald<ehm> b = sw.a("warped_fungi");
   public static final ald<ehm> c = sw.a("oak_checked");
   public static final ald<ehm> d = sw.a("dark_oak_checked");
   public static final ald<ehm> e = sw.a("birch_checked");
   public static final ald<ehm> f = sw.a("acacia_checked");
   public static final ald<ehm> g = sw.a("spruce_checked");
   public static final ald<ehm> h = sw.a("mangrove_checked");
   public static final ald<ehm> i = sw.a("cherry_checked");
   public static final ald<ehm> j = sw.a("pine_on_snow");
   public static final ald<ehm> k = sw.a("spruce_on_snow");
   public static final ald<ehm> l = sw.a("pine_checked");
   public static final ald<ehm> m = sw.a("jungle_tree");
   public static final ald<ehm> n = sw.a("fancy_oak_checked");
   public static final ald<ehm> o = sw.a("mega_jungle_tree_checked");
   public static final ald<ehm> p = sw.a("mega_spruce_checked");
   public static final ald<ehm> q = sw.a("mega_pine_checked");
   public static final ald<ehm> r = sw.a("tall_mangrove_checked");
   public static final ald<ehm> s = sw.a("jungle_bush");
   public static final ald<ehm> t = sw.a("super_birch_bees_0002");
   public static final ald<ehm> u = sw.a("super_birch_bees");
   public static final ald<ehm> v = sw.a("oak_bees_0002");
   public static final ald<ehm> w = sw.a("oak_bees_002");
   public static final ald<ehm> x = sw.a("birch_bees_0002");
   public static final ald<ehm> y = sw.a("birch_bees_002");
   public static final ald<ehm> z = sw.a("fancy_oak_bees_0002");
   public static final ald<ehm> A = sw.a("fancy_oak_bees_002");
   public static final ald<ehm> B = sw.a("fancy_oak_bees");
   public static final ald<ehm> C = sw.a("cherry_bees_005");

   public static void a(rc<ehm> $$0) {
      jj<eaj<?, ?>> $$1 = $$0.a(lq.aC);
      ji<eaj<?, ?>> $$2 = $$1.b(sm.a);
      ji<eaj<?, ?>> $$3 = $$1.b(sm.c);
      ji<eaj<?, ?>> $$4 = $$1.b(sm.g);
      ji<eaj<?, ?>> $$5 = $$1.b(sm.h);
      ji<eaj<?, ?>> $$6 = $$1.b(sm.i);
      ji<eaj<?, ?>> $$7 = $$1.b(sm.j);
      ji<eaj<?, ?>> $$8 = $$1.b(sm.k);
      ji<eaj<?, ?>> $$9 = $$1.b(sm.x);
      ji<eaj<?, ?>> $$10 = $$1.b(sm.z);
      ji<eaj<?, ?>> $$11 = $$1.b(sm.l);
      ji<eaj<?, ?>> $$12 = $$1.b(sm.m);
      ji<eaj<?, ?>> $$13 = $$1.b(sm.n);
      ji<eaj<?, ?>> $$14 = $$1.b(sm.p);
      ji<eaj<?, ?>> $$15 = $$1.b(sm.q);
      ji<eaj<?, ?>> $$16 = $$1.b(sm.r);
      ji<eaj<?, ?>> $$17 = $$1.b(sm.y);
      ji<eaj<?, ?>> $$18 = $$1.b(sm.v);
      ji<eaj<?, ?>> $$19 = $$1.b(sm.s);
      ji<eaj<?, ?>> $$20 = $$1.b(sm.t);
      ji<eaj<?, ?>> $$21 = $$1.b(sm.A);
      ji<eaj<?, ?>> $$22 = $$1.b(sm.B);
      ji<eaj<?, ?>> $$23 = $$1.b(sm.D);
      ji<eaj<?, ?>> $$24 = $$1.b(sm.E);
      ji<eaj<?, ?>> $$25 = $$1.b(sm.G);
      ji<eaj<?, ?>> $$26 = $$1.b(sm.H);
      ji<eaj<?, ?>> $$27 = $$1.b(sm.J);
      ji<eaj<?, ?>> $$28 = $$1.b(sm.K);
      sw.a($$0, a, $$2, ehe.a(8), eha.a());
      sw.a($$0, b, $$3, ehe.a(8), eha.a());
      sw.a($$0, c, $$4, sw.a(dez.x));
      sw.a($$0, d, $$5, sw.a(dez.D));
      sw.a($$0, e, $$6, sw.a(dez.z));
      sw.a($$0, f, $$7, sw.a(dez.B));
      sw.a($$0, g, $$8, sw.a(dez.y));
      sw.a($$0, h, $$9, sw.a(dez.E));
      sw.a($$0, i, $$10, sw.a(dez.C));
      dyz $$29 = dyz.a(je.a.q(), dez.dP, dez.qP);
      List<ehp> $$30 = List.of(ehg.a(je.b, dyz.a(dyz.a(dez.qP)), 8), ehb.a($$29));
      sw.a($$0, j, $$11, $$30);
      sw.a($$0, k, $$8, $$30);
      sw.a($$0, l, $$11, sw.a(dez.y));
      sw.a($$0, m, $$12, sw.a(dez.A));
      sw.a($$0, n, $$13, sw.a(dez.x));
      sw.a($$0, o, $$14, sw.a(dez.A));
      sw.a($$0, p, $$15, sw.a(dez.y));
      sw.a($$0, q, $$16, sw.a(dez.y));
      sw.a($$0, r, $$17, sw.a(dez.E));
      sw.a($$0, s, $$18, sw.a(dez.x));
      sw.a($$0, t, $$19, sw.a(dez.z));
      sw.a($$0, u, $$20, sw.a(dez.z));
      sw.a($$0, v, $$21, sw.a(dez.x));
      sw.a($$0, w, $$22, sw.a(dez.x));
      sw.a($$0, x, $$23, sw.a(dez.z));
      sw.a($$0, y, $$24, sw.a(dez.z));
      sw.a($$0, z, $$25, sw.a(dez.x));
      sw.a($$0, A, $$26, sw.a(dez.x));
      sw.a($$0, B, $$27, sw.a(dez.x));
      sw.a($$0, C, $$28, sw.a(dez.C));
   }
}
