import java.util.List;

public class sy {
   public static final ale<ehp> a = sx.a("crimson_fungi");
   public static final ale<ehp> b = sx.a("warped_fungi");
   public static final ale<ehp> c = sx.a("oak_checked");
   public static final ale<ehp> d = sx.a("dark_oak_checked");
   public static final ale<ehp> e = sx.a("birch_checked");
   public static final ale<ehp> f = sx.a("acacia_checked");
   public static final ale<ehp> g = sx.a("spruce_checked");
   public static final ale<ehp> h = sx.a("mangrove_checked");
   public static final ale<ehp> i = sx.a("cherry_checked");
   public static final ale<ehp> j = sx.a("pine_on_snow");
   public static final ale<ehp> k = sx.a("spruce_on_snow");
   public static final ale<ehp> l = sx.a("pine_checked");
   public static final ale<ehp> m = sx.a("jungle_tree");
   public static final ale<ehp> n = sx.a("fancy_oak_checked");
   public static final ale<ehp> o = sx.a("mega_jungle_tree_checked");
   public static final ale<ehp> p = sx.a("mega_spruce_checked");
   public static final ale<ehp> q = sx.a("mega_pine_checked");
   public static final ale<ehp> r = sx.a("tall_mangrove_checked");
   public static final ale<ehp> s = sx.a("jungle_bush");
   public static final ale<ehp> t = sx.a("super_birch_bees_0002");
   public static final ale<ehp> u = sx.a("super_birch_bees");
   public static final ale<ehp> v = sx.a("oak_bees_0002");
   public static final ale<ehp> w = sx.a("oak_bees_002");
   public static final ale<ehp> x = sx.a("birch_bees_0002");
   public static final ale<ehp> y = sx.a("birch_bees_002");
   public static final ale<ehp> z = sx.a("fancy_oak_bees_0002");
   public static final ale<ehp> A = sx.a("fancy_oak_bees_002");
   public static final ale<ehp> B = sx.a("fancy_oak_bees");
   public static final ale<ehp> C = sx.a("cherry_bees_005");

   public static void a(rc<ehp> $$0) {
      jj<eam<?, ?>> $$1 = $$0.a(lq.aC);
      ji<eam<?, ?>> $$2 = $$1.b(sn.a);
      ji<eam<?, ?>> $$3 = $$1.b(sn.c);
      ji<eam<?, ?>> $$4 = $$1.b(sn.g);
      ji<eam<?, ?>> $$5 = $$1.b(sn.h);
      ji<eam<?, ?>> $$6 = $$1.b(sn.i);
      ji<eam<?, ?>> $$7 = $$1.b(sn.j);
      ji<eam<?, ?>> $$8 = $$1.b(sn.k);
      ji<eam<?, ?>> $$9 = $$1.b(sn.x);
      ji<eam<?, ?>> $$10 = $$1.b(sn.z);
      ji<eam<?, ?>> $$11 = $$1.b(sn.l);
      ji<eam<?, ?>> $$12 = $$1.b(sn.m);
      ji<eam<?, ?>> $$13 = $$1.b(sn.n);
      ji<eam<?, ?>> $$14 = $$1.b(sn.p);
      ji<eam<?, ?>> $$15 = $$1.b(sn.q);
      ji<eam<?, ?>> $$16 = $$1.b(sn.r);
      ji<eam<?, ?>> $$17 = $$1.b(sn.y);
      ji<eam<?, ?>> $$18 = $$1.b(sn.v);
      ji<eam<?, ?>> $$19 = $$1.b(sn.s);
      ji<eam<?, ?>> $$20 = $$1.b(sn.t);
      ji<eam<?, ?>> $$21 = $$1.b(sn.A);
      ji<eam<?, ?>> $$22 = $$1.b(sn.B);
      ji<eam<?, ?>> $$23 = $$1.b(sn.D);
      ji<eam<?, ?>> $$24 = $$1.b(sn.E);
      ji<eam<?, ?>> $$25 = $$1.b(sn.G);
      ji<eam<?, ?>> $$26 = $$1.b(sn.H);
      ji<eam<?, ?>> $$27 = $$1.b(sn.J);
      ji<eam<?, ?>> $$28 = $$1.b(sn.K);
      sx.a($$0, a, $$2, ehh.a(8), ehd.a());
      sx.a($$0, b, $$3, ehh.a(8), ehd.a());
      sx.a($$0, c, $$4, sx.a(dfc.x));
      sx.a($$0, d, $$5, sx.a(dfc.D));
      sx.a($$0, e, $$6, sx.a(dfc.z));
      sx.a($$0, f, $$7, sx.a(dfc.B));
      sx.a($$0, g, $$8, sx.a(dfc.y));
      sx.a($$0, h, $$9, sx.a(dfc.E));
      sx.a($$0, i, $$10, sx.a(dfc.C));
      dzc $$29 = dzc.a(je.a.q(), dfc.dP, dfc.qP);
      List<ehs> $$30 = List.of(ehj.a(je.b, dzc.a(dzc.a(dfc.qP)), 8), ehe.a($$29));
      sx.a($$0, j, $$11, $$30);
      sx.a($$0, k, $$8, $$30);
      sx.a($$0, l, $$11, sx.a(dfc.y));
      sx.a($$0, m, $$12, sx.a(dfc.A));
      sx.a($$0, n, $$13, sx.a(dfc.x));
      sx.a($$0, o, $$14, sx.a(dfc.A));
      sx.a($$0, p, $$15, sx.a(dfc.y));
      sx.a($$0, q, $$16, sx.a(dfc.y));
      sx.a($$0, r, $$17, sx.a(dfc.E));
      sx.a($$0, s, $$18, sx.a(dfc.x));
      sx.a($$0, t, $$19, sx.a(dfc.z));
      sx.a($$0, u, $$20, sx.a(dfc.z));
      sx.a($$0, v, $$21, sx.a(dfc.x));
      sx.a($$0, w, $$22, sx.a(dfc.x));
      sx.a($$0, x, $$23, sx.a(dfc.z));
      sx.a($$0, y, $$24, sx.a(dfc.z));
      sx.a($$0, z, $$25, sx.a(dfc.x));
      sx.a($$0, A, $$26, sx.a(dfc.x));
      sx.a($$0, B, $$27, sx.a(dfc.x));
      sx.a($$0, C, $$28, sx.a(dfc.C));
   }
}
