import java.util.List;

public class sy {
   public static final ale<ehq> a = sx.a("crimson_fungi");
   public static final ale<ehq> b = sx.a("warped_fungi");
   public static final ale<ehq> c = sx.a("oak_checked");
   public static final ale<ehq> d = sx.a("dark_oak_checked");
   public static final ale<ehq> e = sx.a("birch_checked");
   public static final ale<ehq> f = sx.a("acacia_checked");
   public static final ale<ehq> g = sx.a("spruce_checked");
   public static final ale<ehq> h = sx.a("mangrove_checked");
   public static final ale<ehq> i = sx.a("cherry_checked");
   public static final ale<ehq> j = sx.a("pine_on_snow");
   public static final ale<ehq> k = sx.a("spruce_on_snow");
   public static final ale<ehq> l = sx.a("pine_checked");
   public static final ale<ehq> m = sx.a("jungle_tree");
   public static final ale<ehq> n = sx.a("fancy_oak_checked");
   public static final ale<ehq> o = sx.a("mega_jungle_tree_checked");
   public static final ale<ehq> p = sx.a("mega_spruce_checked");
   public static final ale<ehq> q = sx.a("mega_pine_checked");
   public static final ale<ehq> r = sx.a("tall_mangrove_checked");
   public static final ale<ehq> s = sx.a("jungle_bush");
   public static final ale<ehq> t = sx.a("super_birch_bees_0002");
   public static final ale<ehq> u = sx.a("super_birch_bees");
   public static final ale<ehq> v = sx.a("oak_bees_0002");
   public static final ale<ehq> w = sx.a("oak_bees_002");
   public static final ale<ehq> x = sx.a("birch_bees_0002");
   public static final ale<ehq> y = sx.a("birch_bees_002");
   public static final ale<ehq> z = sx.a("fancy_oak_bees_0002");
   public static final ale<ehq> A = sx.a("fancy_oak_bees_002");
   public static final ale<ehq> B = sx.a("fancy_oak_bees");
   public static final ale<ehq> C = sx.a("cherry_bees_005");

   public static void a(rc<ehq> $$0) {
      jj<ean<?, ?>> $$1 = $$0.a(lq.aC);
      ji<ean<?, ?>> $$2 = $$1.b(sn.a);
      ji<ean<?, ?>> $$3 = $$1.b(sn.c);
      ji<ean<?, ?>> $$4 = $$1.b(sn.g);
      ji<ean<?, ?>> $$5 = $$1.b(sn.h);
      ji<ean<?, ?>> $$6 = $$1.b(sn.i);
      ji<ean<?, ?>> $$7 = $$1.b(sn.j);
      ji<ean<?, ?>> $$8 = $$1.b(sn.k);
      ji<ean<?, ?>> $$9 = $$1.b(sn.x);
      ji<ean<?, ?>> $$10 = $$1.b(sn.z);
      ji<ean<?, ?>> $$11 = $$1.b(sn.l);
      ji<ean<?, ?>> $$12 = $$1.b(sn.m);
      ji<ean<?, ?>> $$13 = $$1.b(sn.n);
      ji<ean<?, ?>> $$14 = $$1.b(sn.p);
      ji<ean<?, ?>> $$15 = $$1.b(sn.q);
      ji<ean<?, ?>> $$16 = $$1.b(sn.r);
      ji<ean<?, ?>> $$17 = $$1.b(sn.y);
      ji<ean<?, ?>> $$18 = $$1.b(sn.v);
      ji<ean<?, ?>> $$19 = $$1.b(sn.s);
      ji<ean<?, ?>> $$20 = $$1.b(sn.t);
      ji<ean<?, ?>> $$21 = $$1.b(sn.A);
      ji<ean<?, ?>> $$22 = $$1.b(sn.B);
      ji<ean<?, ?>> $$23 = $$1.b(sn.D);
      ji<ean<?, ?>> $$24 = $$1.b(sn.E);
      ji<ean<?, ?>> $$25 = $$1.b(sn.G);
      ji<ean<?, ?>> $$26 = $$1.b(sn.H);
      ji<ean<?, ?>> $$27 = $$1.b(sn.J);
      ji<ean<?, ?>> $$28 = $$1.b(sn.K);
      sx.a($$0, a, $$2, ehi.a(8), ehe.a());
      sx.a($$0, b, $$3, ehi.a(8), ehe.a());
      sx.a($$0, c, $$4, sx.a(dfd.x));
      sx.a($$0, d, $$5, sx.a(dfd.D));
      sx.a($$0, e, $$6, sx.a(dfd.z));
      sx.a($$0, f, $$7, sx.a(dfd.B));
      sx.a($$0, g, $$8, sx.a(dfd.y));
      sx.a($$0, h, $$9, sx.a(dfd.E));
      sx.a($$0, i, $$10, sx.a(dfd.C));
      dzd $$29 = dzd.a(je.a.q(), dfd.dP, dfd.qP);
      List<eht> $$30 = List.of(ehk.a(je.b, dzd.a(dzd.a(dfd.qP)), 8), ehf.a($$29));
      sx.a($$0, j, $$11, $$30);
      sx.a($$0, k, $$8, $$30);
      sx.a($$0, l, $$11, sx.a(dfd.y));
      sx.a($$0, m, $$12, sx.a(dfd.A));
      sx.a($$0, n, $$13, sx.a(dfd.x));
      sx.a($$0, o, $$14, sx.a(dfd.A));
      sx.a($$0, p, $$15, sx.a(dfd.y));
      sx.a($$0, q, $$16, sx.a(dfd.y));
      sx.a($$0, r, $$17, sx.a(dfd.E));
      sx.a($$0, s, $$18, sx.a(dfd.x));
      sx.a($$0, t, $$19, sx.a(dfd.z));
      sx.a($$0, u, $$20, sx.a(dfd.z));
      sx.a($$0, v, $$21, sx.a(dfd.x));
      sx.a($$0, w, $$22, sx.a(dfd.x));
      sx.a($$0, x, $$23, sx.a(dfd.z));
      sx.a($$0, y, $$24, sx.a(dfd.z));
      sx.a($$0, z, $$25, sx.a(dfd.x));
      sx.a($$0, A, $$26, sx.a(dfd.x));
      sx.a($$0, B, $$27, sx.a(dfd.x));
      sx.a($$0, C, $$28, sx.a(dfd.C));
   }
}
