import java.util.List;

public class tc {
   public static final aly<enn> a = tb.a("crimson_fungi");
   public static final aly<enn> b = tb.a("warped_fungi");
   public static final aly<enn> c = tb.a("oak_checked");
   public static final aly<enn> d = tb.a("dark_oak_checked");
   public static final aly<enn> e = tb.a("pale_oak_checked");
   public static final aly<enn> f = tb.a("pale_oak_creaking_checked");
   public static final aly<enn> g = tb.a("birch_checked");
   public static final aly<enn> h = tb.a("acacia_checked");
   public static final aly<enn> i = tb.a("spruce_checked");
   public static final aly<enn> j = tb.a("mangrove_checked");
   public static final aly<enn> k = tb.a("cherry_checked");
   public static final aly<enn> l = tb.a("pine_on_snow");
   public static final aly<enn> m = tb.a("spruce_on_snow");
   public static final aly<enn> n = tb.a("pine_checked");
   public static final aly<enn> o = tb.a("jungle_tree");
   public static final aly<enn> p = tb.a("fancy_oak_checked");
   public static final aly<enn> q = tb.a("mega_jungle_tree_checked");
   public static final aly<enn> r = tb.a("mega_spruce_checked");
   public static final aly<enn> s = tb.a("mega_pine_checked");
   public static final aly<enn> t = tb.a("tall_mangrove_checked");
   public static final aly<enn> u = tb.a("jungle_bush");
   public static final aly<enn> v = tb.a("super_birch_bees_0002");
   public static final aly<enn> w = tb.a("super_birch_bees");
   public static final aly<enn> x = tb.a("oak_bees_0002");
   public static final aly<enn> y = tb.a("oak_bees_002");
   public static final aly<enn> z = tb.a("birch_bees_0002");
   public static final aly<enn> A = tb.a("birch_bees_002");
   public static final aly<enn> B = tb.a("fancy_oak_bees_0002");
   public static final aly<enn> C = tb.a("fancy_oak_bees_002");
   public static final aly<enn> D = tb.a("fancy_oak_bees");
   public static final aly<enn> E = tb.a("cherry_bees_005");

   public static void a(rk<enn> $$0) {
      jr<egh<?, ?>> $$1 = $$0.a(mb.aL);
      jq<egh<?, ?>> $$2 = $$1.b(sr.a);
      jq<egh<?, ?>> $$3 = $$1.b(sr.c);
      jq<egh<?, ?>> $$4 = $$1.b(sr.g);
      jq<egh<?, ?>> $$5 = $$1.b(sr.h);
      jq<egh<?, ?>> $$6 = $$1.b(sr.i);
      jq<egh<?, ?>> $$7 = $$1.b(sr.j);
      jq<egh<?, ?>> $$8 = $$1.b(sr.k);
      jq<egh<?, ?>> $$9 = $$1.b(sr.l);
      jq<egh<?, ?>> $$10 = $$1.b(sr.m);
      jq<egh<?, ?>> $$11 = $$1.b(sr.z);
      jq<egh<?, ?>> $$12 = $$1.b(sr.B);
      jq<egh<?, ?>> $$13 = $$1.b(sr.n);
      jq<egh<?, ?>> $$14 = $$1.b(sr.o);
      jq<egh<?, ?>> $$15 = $$1.b(sr.p);
      jq<egh<?, ?>> $$16 = $$1.b(sr.r);
      jq<egh<?, ?>> $$17 = $$1.b(sr.s);
      jq<egh<?, ?>> $$18 = $$1.b(sr.t);
      jq<egh<?, ?>> $$19 = $$1.b(sr.A);
      jq<egh<?, ?>> $$20 = $$1.b(sr.x);
      jq<egh<?, ?>> $$21 = $$1.b(sr.u);
      jq<egh<?, ?>> $$22 = $$1.b(sr.v);
      jq<egh<?, ?>> $$23 = $$1.b(sr.C);
      jq<egh<?, ?>> $$24 = $$1.b(sr.D);
      jq<egh<?, ?>> $$25 = $$1.b(sr.F);
      jq<egh<?, ?>> $$26 = $$1.b(sr.G);
      jq<egh<?, ?>> $$27 = $$1.b(sr.I);
      jq<egh<?, ?>> $$28 = $$1.b(sr.J);
      jq<egh<?, ?>> $$29 = $$1.b(sr.L);
      jq<egh<?, ?>> $$30 = $$1.b(sr.M);
      tb.a($$0, a, $$2, ene.a(8), enb.a());
      tb.a($$0, b, $$3, ene.a(8), enb.a());
      tb.a($$0, c, $$4, tb.a(dkn.z));
      tb.a($$0, d, $$5, tb.a(dkn.F));
      tb.a($$0, e, $$6, tb.a(dkn.G));
      tb.a($$0, f, $$7, tb.a(dkn.G));
      tb.a($$0, g, $$8, tb.a(dkn.B));
      tb.a($$0, h, $$9, tb.a(dkn.D));
      tb.a($$0, i, $$10, tb.a(dkn.A));
      tb.a($$0, j, $$11, tb.a(dkn.H));
      tb.a($$0, k, $$12, tb.a(dkn.E));
      eew $$31 = eew.a(jm.a.q(), dkn.ec, dkn.rk);
      List<enq> $$32 = List.of(eng.a(jm.b, eew.a(eew.a(dkn.rk)), 8), enc.a($$31));
      tb.a($$0, l, $$13, $$32);
      tb.a($$0, m, $$10, $$32);
      tb.a($$0, n, $$13, tb.a(dkn.A));
      tb.a($$0, o, $$14, tb.a(dkn.C));
      tb.a($$0, p, $$15, tb.a(dkn.z));
      tb.a($$0, q, $$16, tb.a(dkn.C));
      tb.a($$0, r, $$17, tb.a(dkn.A));
      tb.a($$0, s, $$18, tb.a(dkn.A));
      tb.a($$0, t, $$19, tb.a(dkn.H));
      tb.a($$0, u, $$20, tb.a(dkn.z));
      tb.a($$0, v, $$21, tb.a(dkn.B));
      tb.a($$0, w, $$22, tb.a(dkn.B));
      tb.a($$0, x, $$23, tb.a(dkn.z));
      tb.a($$0, y, $$24, tb.a(dkn.z));
      tb.a($$0, z, $$25, tb.a(dkn.B));
      tb.a($$0, A, $$26, tb.a(dkn.B));
      tb.a($$0, B, $$27, tb.a(dkn.z));
      tb.a($$0, C, $$28, tb.a(dkn.z));
      tb.a($$0, D, $$29, tb.a(dkn.z));
      tb.a($$0, E, $$30, tb.a(dkn.E));
   }
}
